### ISSUE TITLE
Installing gekko in Virtual Server with ubuntu 16.04.02 npm installation issues

### ISSUE THREAD

**Issue by decoye** [askmike/gekko#1005]
Hey hey, 

i decided its a good idea to move gekko from my home server to a virtual server.
Virtual server has everything running so far, its running 16.04.02 Ubuntu lts.

However when i try to install the version of gekko that i have been running on my home server i runn into an sqlite issue with npm.

when i start to run gekko with "node gekko" it tells me i need to install sqlite3 database

> The plugin sqlite adapter expects the module sqlite3 to be installed. However it is not, install it by running: 

 	npm install sqlite3@3.1.4 

i sudo this command, however i recieve this error message then.

> npm ERR! path /root/gekko-eth/node_modules/sqlite/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/are-we-there-yet/node_modules/delegates
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/root/gekko-eth/node_modules/sqlite/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/are-we-there-yet/node_modules/delegates' -> '/root/gekko-eth/node_modules/sqlite/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/are-we-there-yet/node_modules/.delegates.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-08-19T09_02_53_172Z-debug.log

so far i was not able to resolve this issue. maybe somebody has more knowledge about the process and whats actually going on there.

i also found 4 prommising answers from google research, but theese also did not solve the issue.

**Comment by askmike** [comment]
What version of node are you running?

**Comment by GuyPaddock** [comment]
Also, are you using Ubuntu's older Node install, or did you install a newer version with something like nvm?

**Comment by decoye** [comment]
im running node version  8.4.0

**Comment by askmike** [comment]
Can you try the LTS?

**Comment by decoye** [comment]
im affraid im not exactly sure what you mean by that...

i just noticed that everything fails that i try to reinstall by npm.

**Comment by askmike** [comment]
Here you can download the LTS: https://nodejs.org/en/download/

**Comment by decoye** [comment]
i can install it but i cannot make the server use it. node --version tells me it still is 8.4.0

**Comment by askmike** [comment]
What if you remove all versions of node and than install the LTS?

**Comment by decoye** [comment]
Will try this next
Keep you posted.

**Comment by askmike** [comment]
I cannot reproduce on `ubuntu 16.04` with the same node version as you are using:

    root@test:~/gekko# npm cache clean --force
    npm WARN using --force I sure hope you know what you are doing.
    root@test:~/gekko# lsb_release -a
    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:  Ubuntu 16.04 LTS
    Release:  16.04
    Codename: xenial
    root@test:~/gekko# node -v
    v8.4.0
    root@test:~/gekko# npm install

    > websocket@1.0.24 install /root/gekko/node_modules/websocket
    > (node-gyp rebuild 2> builderror.log) || (exit 0)


    > sqlite3@3.1.9 install /root/gekko/node_modules/sqlite3
    > node-pre-gyp install --fallback-to-build

    [sqlite3] Success: "/root/gekko/node_modules/sqlite3/lib/binding/node-v57-linux-x64/node_sqlite3.node" is installed via remote

    > relieve@2.2.1 postinstall /root/gekko/node_modules/relieve
    > node links.js

    added 576 packages in 27.465s

**Comment by decoye** [comment]
Ive now deleted all the nodejs files, and it is working now.

But it really took me a while to remove really everything there, even after the whole process node --version gave me an answer.

it was not smooth, and as you say, it was probably something with the installation of ubuntu. but still on a new machine from my provider i get this error.

**Comment by askmike** [comment]
Happy to hear your got it working. Installing a version of node on ubuntu is outside of the support I can give..

**Comment by decoye** [comment]
Yes yes absolutely. That has never been asked. I was jusz wondering why it workes on my server at home that has the exact same ubuntu version but on my real server it does not.



- sent from mobile -
Mit freundlichen grüssen With kind regards

Andreas Schindler

Schindler.andreas@gmail.com 
-------- Ursprüngliche Nachricht --------Von: Mike van Rossum <notifications@github.com> Datum: 21.08.17  10:19  (GMT+01:00) An: askmike/gekko <gekko@noreply.github.com> Cc: decoye <schindler.andreas@gmail.com>, Author <author@noreply.github.com> Betreff: Re: [askmike/gekko] Installing gekko in Virtual Server with ubuntu 16.04.02 npm installation issues (#1005) 
Happy to hear your got it working. Installing a version of node on ubuntu is outside of the support I can give..

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/askmike/gekko","title":"askmike/gekko","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/askmike/gekko"}},"updates":{"snippets":[{"icon":"PERSON","message":"@askmike in #1005: Happy to hear your got it working. Installing a version of node on ubuntu is outside of the support I can give.."}],"action":{"name":"View Issue","url":"https://github.com/askmike/gekko/issues/1005#issuecomment-323678046"}}}
