### ISSUE TITLE
Having problems with okcoin.cn

### ISSUE THREAD

**Issue by remini04** [askmike/gekko#1008]
When I run gekko for live trading in okcoin.cn, it gives an error as follows

Error:

At this moment Gekko can't trade at OkCoin.

The trade advisor seems to run correctly.
I configured config.watch as follows.

config.watch = {
  // see https://gekko.wizb.it/docs/introduction/supported_exchanges.html
  exchange: 'okcoin',
  currency: 'CNY',
  asset: 'BTC'
}

Also, I configured and enabled config.trader correctly.
What makes an error? Is it come from my fault? Or is the live trading function not implemented for okcoin.cn yet?
Thanks.

**Comment by askmike** [comment]
>  Or is the live trading function not implemented for okcoin.cn yet?

I am pretty sure there is a current issue with OKCoin at the moment unfortunately. I will try to look at this asap!

**Comment by askmike** [comment]
To come back on this: live trading is just not supported in the UI. Via the CLI you can run a tradebot at okcoin: see here how to: https://gekko.wizb.it/docs/commandline/tradebot.html

I have just send some bitcoin to my okcoin account, will integrate trading via the UI asap!

**Comment by remini04** [comment]
Yeap, I have just tested gekko via the CLI and it still gives the same error.

Thanks for your fast response!

**Comment by askmike** [comment]
what error does it give for the CLI?

**Comment by remini04** [comment]
The following is the error message.

Gekko encountered an error and can't continue

Error:

At this moment Gekko can't trade at OkCoin.



Meta debug info:

Gekko version: v0.5.2
Nodejs version: v6.11.2

**Comment by askmike** [comment]
Apologies you are right! Working on this asap :)

**Comment by askmike** [comment]
Hey,

I have an account for okcoin.com but not for okcoin.cn, unfortunately I am unable to create an account for okcoin.cn since I am not a Chinese resident:

<img width="950" alt="screen shot 2017-08-22 at 00 20 26" src="https://user-images.githubusercontent.com/969743/29542097-a9dc2690-86d0-11e7-9cff-853afa8149b3.png">

---

Integrating an exchange fully in Gekko requires trade access at an account (if you can temporary provide some API keys I can work from there, in that case please email me at gekko@mvr.me).

**Comment by remini04** [comment]
I've just sent a mail to you. Thanks!

**Comment by askmike** [comment]
Hey @remini04 thanks for the email. I have fixed the integration so okcoin should work now on the develop branch, note that it's hard for me to test without having access myself.

Here you can download the develop branch: https://github.com/askmike/gekko/tree/develop

**Comment by remini04** [comment]
Works like a charm! Thanks!
