### ISSUE TITLE
Telegram & UI

### ISSUE THREAD

**Issue by raffus** [askmike/gekko#1009]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x] bug report

* **Action taken** (what you did)
Started gekko with UI and my telegram BOT stopped working.

* **Expected result** (what you hoped would happen)
Bot response

* **Actual result** (unexpected outcome)
I can see the bot gets the messages but it doesn't reply anymore or gives any advice alert.

**Comment by askmike** [comment]
The telegram plugin only works with the CLI version. Are you running 2 versions (CLI and UI) at the same time? On the same machine? Do you have multiple gekkos running on the same exchange?

**Comment by raffus** [comment]
I was first running in CLI mode.
Then I switched to UI mode and bot stopped working.
UI mode is nice cause it shows us partial results which can't be seen when running CLI mode...
Now I've switched it back to CLI because I like having the bot giving me the alerts.. :)

**Comment by askmike** [comment]
Ah like that: The telegram is a plugin you can use with Gekko, though only when running Gekko in CLI mode.

You can run both a CLI gekko and the UI at the same time (in a different command prompt / terminal), provided that:

- you are only running 1 real trader (per exchange account) - so either in the CLI or in the live trader (but not both)
- you are not running too many gekkos in total.

**Comment by askmike** [comment]
In some point in the future we might enable custom plugins (telegram, slack email) to live gekkos in the UI.

**Comment by askmike** [comment]
If you have any questions feel free to ask.
