### ISSUE TITLE
GDAX min threshold for BTC might be smaller than 0.01 BTC

### ISSUE THREAD

**Issue by GuyPaddock** [askmike/gekko#1010]
This issue is more informative than a feature request / bug report: I noticed that Gekko is configured not to do BTC trades with GDAX that are smaller than 0.01 BTC. This is consistent with GDAX's own docs; however, I think GDAX's actual BTC limit is much smaller now than BTC is trading so high, and the docs are out-of-date.

I did a few trades this week that were for 0.009 BTC and they were accepted by GDAX online. I've also lowered the minimum in the config for Gekko and it has been able to trade under 0.01 BTC as well.

A few days ago I filed a support case with GDAX about updating their docs, but it doesn't seem like their support team ever gets to GDAX tickets (Coinbase tickets seem to be the priority).

**Comment by askmike** [comment]
Interesting, if someone know the curent limit we can adjust it in Gekko.

**Comment by decoye** [comment]
Gdax has slme quite interesting quirks. For example its totally possible to trade with no fees at all when you are just over the current price with your sell and buy order. You pay no fee at all.
So if gekko puts the order 2 cents higher then the actual price in this moment fees are saved.

**Comment by askmike** [comment]
> For example its totally possible to trade with no fees at all when you are just over the current price with your sell and buy order.

I am pretty sure this is intentional to attract market makers. Gekko always tries to make orders which means Gekko pays 0 fees at GDAX in most situations.

**Comment by decoye** [comment]
Hmm. I never saw it that way. Absolutely convinced me.
Also the daily cap that gets reset with every new transaction... i love them hahahah
