### ISSUE TITLE
CEX.IO not showing up in UI

### ISSUE THREAD

**Issue by dannystommen** [askmike/gekko#1013]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Run Gekko UI, > Config > Add an API key,

CEX,IO is not available in the dropdown, where it is implemented in the exchanges directories.

* **Expected result** (what you hoped would happen)
CEX.IO shows in dropdown

* **Actual result** (unexpected outcome)
CEX.IO not showing up.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
I tried to debug what's going on. CEX.IO seems to be returned by the API, but somehow is filtered out by VUE. Unfortenately I'm not a VUE expert, so I was unable to pinpoint were it gets lost.

**Comment by askmike** [comment]
Ah! CEX.io live trading is not supported at this moment (and the "Supported exchanges" table is not up to date). I am having trouble logging into my CEX.io account so it will will take some time before I can update Gekko to properly support CEX.io with live trading..
