### ISSUE TITLE
Market watcher creating duplicates

### ISSUE THREAD

**Issue by CyborgDroid** [askmike/gekko#1014]
Is this a bug? If I create a new market watcher I see two in the list of gekkos.
![screen shot 2017-08-20 at 9 48 50 pm](https://user-images.githubusercontent.com/8703207/29500859-2fb6712e-85f2-11e7-8846-53c3774ad874.png)
Then I got a few ticker failures
![screen shot 2017-08-20 at 9 59 48 pm](https://user-images.githubusercontent.com/8703207/29501008-208c4538-85f3-11e7-82ac-64942d2d3426.png)
Then I refreshed the gekko page, and the extra tickers went away. I click on local data, scan available datasets, and get a few more ticker errors the same as before. Refresh the page, scan available data again, and got this:
![screen shot 2017-08-20 at 10 03 13 pm](https://user-images.githubusercontent.com/8703207/29501042-6d2ba442-85f3-11e7-9987-cba4ae65eca8.png)

**Comment by askmike** [comment]
So you have 4 different problems here.

> I see two in the list of gekkos.

This is a known bug, see #894.

> Then I got a few ticker failures

Please check out the link in the message (#514), it describes exactly why you got that message.

> I click on local data, scan available datasets, and get a few more ticker errors the same as before.

Which one?

> Refresh the page, scan available data again, and got this:

And you can ignore the fact that some markets where unscannable, that's just a message.

**Comment by askmike** [comment]
I am closing this as a dup of #894, if you have more comments please put them there!
