### ISSUE TITLE
[Feature Request] Automatic Backtesting

### ISSUE THREAD

**Issue by decoye** [askmike/gekko#1017]
Hey Hey, 

i am missing a feature, that automatically calculates the best strategy for an asset pair over a timeframe.

Explain:
User gathers a database of 2 weeks, and has made backtests on it with a strategy.
It would be a nice feature to have an option to find a better combination of indicator values for this startegy by gekko calculatin trough it by it self.
With DEMA indicators for example. you let the automatic backtester calculate the best candlesize, best shot value, best long value. 

The haasbot has a similar feature from my understanding, but i never personally used it.
Of course this will not be the best everlasting strategy then, but every once in a while you will have to make new calculations that may have been more profitable in the last 2 weeks or what ever timeframe you specify.

**Comment by imkane** [comment]
Agreed that this would be nice to have. I discussed a possible way to do this here: https://github.com/askmike/gekko/issues/831

And here's an implementation:
https://github.com/askmike/gekko/issues/840

**Comment by askmike** [comment]
Yes! Calculating the "best strategy" is a very hard problem:

1. first you have to define what best means:
  - least risky trades
  - most profit overall
  - combination of both (eg. sharpe)
  - least amount of trades that lost money
  - least exposure
  - a combination of all the above
2. than you need to figure out a way to come up with versions to test
  - GA (see links above)
  - brute force
  - AI/ML (at this point you probably ditch TA altogether)

-----

For this reason there is no one size fits all backtest optimizer.

Though @thegamecat already coded a solution that implements GA, see #767.

Note that whichever route you go, the backtester needs to be fast. The backtester is currently very slow. See [this comment](https://github.com/askmike/gekko/issues/747#issuecomment-304983276) to why it's slow and [this comment](https://github.com/askmike/gekko/issues/747#issuecomment-305319678) for my ideas on how to make it faster.

**Comment by thegamecat** [comment]
A 1m candle 28 day window takes about 3-4 seconds with native non talib indicators.

I'm doing some thinking about how the ga could be used in real time to evaluate possibilities but I don't think it's the right tool on its own, if at all. 

@decoye  you are describing a GA but a GA has limitations. It optimises for that specific scenario. What you want is machine learning to spot a scenario then execute the GA optimised strategy for that scenario.

**Comment by decoye** [comment]
> > Yes! Calculating the "best strategy" is a very hard problem:
> 
> first you have to define what best means:
> least risky trades
> most profit overall
> combination of both (eg. sharpe)
> least amount of trades that lost money
> least exposure

yes you are right. this will have to be defined, but where does the backtest tell me those things today?

For me the best is the one that is the highest away from the buy and hold.
Why not keep it simple?

**Comment by decoye** [comment]
> @decoye you are describing a GA but a GA has limitations. It optimises for that specific scenario. What you want is machine learning to spot a scenario then execute the GA optimised strategy for that scenario.


hmm, i would be happy with an automated process, that tests from a range to a range.
lets put up a scenario here.

lets see if we could have been profitable in the last 2 weeks with a simple dema strategy.

how i now would do it is to import the range of two weeks of the exchange in question.

and then make backtests on it. long demo is 5 short dema is 10 time is 2h, hmm damn thats not profitable against buy and hold.

okay, next one long is 6 short is 10 still 2h, still not good. on and on and on and on.

once i find a lead i write it down and carry on the test to maybe find a more profitable one.
this is brute force by plain food work. that can be done easily by gekko. i think.


oh when i say a range i mean, started from a long short combination of 3/8 up to 15/30.
and the best ones would be saved to a file or whatever.
