### ISSUE TITLE
Command Line Backtest Issue

### ISSUE THREAD

**Issue by Gab0** [askmike/gekko#1020]
[ bug report]

* **Action taken**
Imported poloniex data;
Ran a backtest on feb 1st to feb 2nd on the UI frontend.
Ran backtest from the command line. Same time period, same parameters (MACD standard)

* **Expected result**
Same results on both.

* **Actual result** 
Backtest result from UI seems fine, a profit of like 1% i think.
But on the command line, profit is -90%.
It seems to buy and sell always in clusters, in this standard MACD it always buys and then sells subsequently (suffering immediate loss from fee). With some settings it even buy/sells like eight times in sequence.

* **Other information** 
A piece of the debug:

> 2017-08-21 18:13:19 (DEBUG):	calculated MACD properties for candle:
> 2017-08-21 18:13:19 (DEBUG):		 short: 1022.78699510
> 2017-08-21 18:13:19 (DEBUG):		 long: 1020.56962192
> 2017-08-21 18:13:19 (DEBUG):		 macd: 2.21737317
> 2017-08-21 18:13:19 (DEBUG):		 signal: 2.18463573
> 2017-08-21 18:13:19 (DEBUG):		 macdiff: 0.03273744
> 2017-08-21 18:13:19 (DEBUG):	In uptrend since 20 candle(s)
> 2017-08-21 18:13:19 (INFO):	2017-02-04 14:37:00: Paper trader simulated a SELL 	109.99230337 USDT <= 0.00000000 BTC
> 2017-08-21 18:13:19 (INFO):	2017-02-04 14:50:00: Paper trader simulated a BUY 	0.00000000 USDT	=> 0.10804170 BTC
> 2017-08-21 18:13:19 (DEBUG):	calculated MACD properties for candle:
> 2017-08-21 18:13:19 (DEBUG):		 short: 1023.13213731
> 2017-08-21 18:13:19 (DEBUG):		 long: 1020.94377241
> 2017-08-21 18:13:19 (DEBUG):		 macd: 2.18836490
> 2017-08-21 18:13:19 (DEBUG):		 signal: 2.18538157
> 2017-08-21 18:13:19 (DEBUG):		 macdiff: 0.00298333

**Comment by askmike** [comment]
Can you share your:

- history folder (zipped or so)
- config used for CLI backtesting
- screenshot of UI backtest settings?

**Comment by Gab0** [comment]
Ran full seven month history for clearer results.
Profits:
UI         -58%
CMD     -100%
![gekko-ui-sample-backtest](https://user-images.githubusercontent.com/6483729/29541958-14812022-86ae-11e7-92b6-2c734cf64e64.jpg)

[poloniex-history.zip](https://github.com/askmike/gekko/files/1240358/poloniex-history.zip)
```
config.tradingAdvisor = {
  enabled: true,
  method: 'MACD',
  candleSize: 1,
  historySize: 10,
  adapter: 'sqlite',
  talib: {
    enabled: false,
    version: '1.0.2'
  }
}
.....
config.MACD = {
  // EMA weight (α)
  // the higher the weight, the more smooth (and delayed) the line
  short: 10,
  long: 21,
  signal: 9,
  // the difference between the EMAs (to act as triggers)
  thresholds: {
    down: -0.025,
    up: 0.025,
    // How many candle intervals should a trend persist
    // before we consider it real?
    persistence: 1
  }
};

....
config.paperTrader = {
  enabled: true,
  // report the profit in the currency or the asset?
  reportInCurrency: true,
  // start balance, on what the current balance is compared with
  simulationBalance: {
    // these are in the unit types configured in the watcher.
    asset: 1,
    currency: 100,
  },
  // how much fee in % does each trade cost?
  fee: 0.25,
  // how much slippage/spread should Gekko assume per trade?
  slippage: 0.05,
}

```

**Comment by askmike** [comment]
Ah! In your CLI config you set `candleSize` to 1. candleSize is in minutes. Could you try again with either the UI set to 1 minute or the CLI backtester to 60?

**Comment by Gab0** [comment]
And that was the problem :x
Would be nice to comment ' candle size in minutes' on the config file just to.. not let this be in vain haah Thanks.

**Comment by askmike** [comment]
Ah yes, great idea.
