### ISSUE TITLE
How to add other exchange? like BitYep

### ISSUE THREAD

**Issue by algorithmcode** [askmike/gekko#1021]
feature request
I found other exchange have nice price, like BitYep, 
The bitcoin price at this time:
bitfinex 3773
okcoin 3882
bityep 4050

* **Expected result** (what you hoped would happen)
So how to add function to these exchange ,Thanks

**Comment by askmike** [comment]
Hey @algorithmcode!

Here you can read what you need to do to add a new exchange to gekko: https://gekko.wizb.it/docs/extending/add_an_exchange.html

If you run into anything let me know :)
