### ISSUE TITLE
bitstamp live bot crashes

### ISSUE THREAD

**Issue by dannystommen** [askmike/gekko#1024]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Started a new live bot on BItstamp. After starting it, a child process crashes

* **Expected result** (what you hoped would happen)
A running bot

* **Actual result** (unexpected outcome)

Stacktrace: 

C:\Projects\gekko\exchanges\bitstamp.js:48
    if(!_.isEmpty(data.error)) {
                      ^

TypeError: Cannot read property 'error' of undefined
    at Trader.<anonymous> (C:\Projects\gekko\exchanges\bitstamp.js:48:23)
    at IncomingMessage.<anonymous> (C:\Projects\gekko\node_modules\bitstamp\bitstamp.js:50:16)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
I chose currency USD and asset BTC.

**Comment by askmike** [comment]
Was this a live tradebot?

**Comment by dannystommen** [comment]
"Start a new live Gekko" and on the next page select type "tradebot".

Just checked the bitstamp.js file.

Issue seems to be caused by
(line 46-48)
`  var set = function(err, data) {

    if(_.isEmpty(data.error)) {`

Bitstamp seems to be returning an error, so `err` is set, `data` is data.

Changed it to 
`
var set = function(err, data) {
    console.log('err='+ err);
    console.log('data='+ data);

    if(!_.isEmpty(err)) {
      log.error('BITSTAMP API ERROR: ' + err);
      return this.retry(this.getPortfolio, args);
    }
    if((data && !_.isEmpty(data.error))){
      log.error('BITSTAMP API ERROR: ' + data.error);
      return this.retry(this.getPortfolio, args);
    }
`
now it won't crash anymore.
Is it desirable to create a pull request for this change? Or will you change it yourself?

Can't find the output from log.error though, so temporary put a console.log into the code, and could see that there are issues with my API keys apparently, so I'll contact bitstamp regarding this topic.

**Comment by askmike** [comment]
Since your problem is related to your API keys Gekko shouldn't even retry since it is never going to work.

**Comment by askmike** [comment]
Could you try the develop branch and see what happens? It does 2 things:

- make sure we don't access data.error if data is empty (fixes the crash you reported)
- checks the error to see if Bitstamp specifically said the API keys are invalid.

(note you need to install the latest version of the bitstamp module)

**Comment by dannystommen** [comment]
sorry for delayed response, but I can confirm code on develop branch is working like expected.

**Comment by askmike** [comment]
Awesome! I released a new version of Gekko so the latest stable branch should also work.
