### ISSUE TITLE
Deprecated node module

### ISSUE THREAD

**Issue by LeMoussel** [askmike/gekko#1025]
On Windows 10 , Node.js v8.3.0 & NPM v5.3.0,  when I do  `npm install`, I got this Warning

```
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated crypto@0.0.3: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
```
**Rem** :  Install is OK & Gekko run perfectly.

**Comment by askmike** [comment]
Strange, I have seen that in the past but I don't see it anymore:

    ➜  gekko git:(develop) ✗ npm -v
    n5.2.0
    ➜  gekko git:(develop) ✗ node -v
    v8.0.0
    ➜  gekko git:(develop) ✗ npm i

    > sqlite3@3.1.8 install /Users/pear/projects/gekko/node_modules/sqlite3
    > node-pre-gyp install --fallback-to-build

    node-pre-gyp info it worked if it ends with ok
    node-pre-gyp verb cli [ '/Users/pear/.nvm/versions/node/v8.0.0/bin/node',
    node-pre-gyp verb cli   '/Users/pear/projects/gekko/node_modules/sqlite3/node_modules/.bin/node-pre-gyp',
    node-pre-gyp verb cli   'install',
    node-pre-gyp verb cli   '--fallback-to-build' ]
    node-pre-gyp info using node-pre-gyp@0.6.31
    node-pre-gyp info using node@8.0.0 | darwin | x64
    node-pre-gyp verb command install []
    node-pre-gyp info check checked for "/Users/pear/projects/gekko/node_modules/sqlite3/lib/binding/node-v57-darwin-x64/node_sqlite3.node" (not found)
    node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/node-v57-darwin-x64.tar.gz
    node-pre-gyp http 200 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/node-v57-darwin-x64.tar.gz
    node-pre-gyp info install unpacking node_sqlite3.node
    node-pre-gyp info tarball done parsing tarball
    node-pre-gyp info validate Running test command: '/Users/pear/.nvm/versions/node/v8.0.0/bin/node --eval 'require(\'/Users/pear/projects/gekko/node_modules/sqlite3/lib/binding/node-v57-darwin-x64/node_sqlite3.node\')''
    [sqlite3] Success: "/Users/pear/projects/gekko/node_modules/sqlite3/lib/binding/node-v57-darwin-x64/node_sqlite3.node" is installed via remote
    node-pre-gyp info ok 

    > websocket@1.0.24 install /Users/pear/projects/gekko/node_modules/websocket
    > (node-gyp rebuild 2> builderror.log) || (exit 0)

      CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
      SOLINK_MODULE(target) Release/bufferutil.node
      CXX(target) Release/obj.target/validation/src/validation.o
      SOLINK_MODULE(target) Release/validation.node

    > websocket@1.0.24 install /Users/pear/projects/gekko/node_modules/pushbullet/node_modules/websocket
    > (node-gyp rebuild 2> builderror.log) || (exit 0)

      CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
      SOLINK_MODULE(target) Release/bufferutil.node
      CXX(target) Release/obj.target/validation/src/validation.o
      SOLINK_MODULE(target) Release/validation.node

    > utf-8-validate@1.2.2 install /Users/pear/projects/gekko/node_modules/bitfinex-api-node/node_modules/utf-8-validate
    > node-gyp rebuild

      CXX(target) Release/obj.target/validation/src/validation.o
      SOLINK_MODULE(target) Release/validation.node

    > bufferutil@1.2.1 install /Users/pear/projects/gekko/node_modules/bitfinex-api-node/node_modules/bufferutil
    > node-gyp rebuild

      CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
      SOLINK_MODULE(target) Release/bufferutil.node

    > relieve@2.2.1 postinstall /Users/pear/projects/gekko/node_modules/relieve
    > node links.js

    added 974 packages in 38.812s
    ➜  gekko git:(develop) ✗ npm i
    updated 10 packages in 3.808s

**Comment by CyborgDroid** [comment]
Similar on an ubuntu linux AWS server after upgrading with git:

npm install

npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
*_long list of files_*
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN vue@0.2.0 No repository field.
npm WARN vue@0.2.0 No license field.

When I do: _npm install --only=production_ I get fewer messages:

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**Comment by LeMoussel** [comment]
On Win 7 Professionnal, I got same warnings

```
$ npm install
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated crypto@0.0.3: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130

> bufferutil@1.2.1 install C:\NodeJs\gekko-stable\node_modules\bufferutil
> node-gyp rebuild
> .......
> $ npm -v
> 5.3.0
> $ node -v
> v8.4.0
```

**Comment by katharxix** [comment]
I have this issue when itried to install npm apic

..\src\ursaNative.cc(157): warning C4244: 'argument': conversion from 'ssize_t' to 'int', possible loss of data [C:\Users\Asus\AppData\Roaming\npm\node_modules\apiconn
ect\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(172): warning C4244: 'argument': conversion from 'ssize_t' to 'int', possible loss of data [C:\Users\Asus\AppData\Roaming\npm\node_modules\apiconn
ect\node_modules\ursa\build\ursaNative.vcxproj]
LINK : fatal error LNK1181: cannot open input file 'C:\OpenSSL-Win64\lib\libeay32.lib' [C:\Users\Asus\AppData\Roaming\npm\node_modules\apiconnect\node_modules\ursa\bui
ld\ursaNative.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Asus\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Asus\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Asus\AppData\Roaming\npm\node_modules\apiconnect\node_modules\ursa
gyp ERR! node -v v6.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\apiconnect\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: modern-syslog@1.1.4 (node_modules\apiconnect\node_modules\modern-syslog):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for modern-syslog@1.1.4: wanted {"os":"!win32","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ursa@0.9.4 (node_modules\apiconnect\node_modules\ursa):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ursa@0.9.4 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

What happend ? i have install Python, Gyp, and OpenSSL . please help

**Comment by askmike** [comment]
@katharxix I am not sure what you are trying to install, but it's completely unrelated from this project.
