### ISSUE TITLE
Bitcoin Cash (BCH) assets do not work on Kraken.

### ISSUE THREAD

**Issue by ghost** [askmike/gekko#1027]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Tried to run a market watcher on Kraken using various asset combinations.

* **Expected result** (what you hoped would happen)
BCH should work as a currency or asset on Kraken.

* **Actual result** (unexpected outcome)
Gekko prompts the following error message:

ERROR: Gekko only supports the currencies [ CAD, EUR, GBP, JPY, USD, XBT ] at Kraken (not BCH)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Using Gekko v0.5.4

**Comment by askmike** [comment]
Could you try the latest develop branch? You can download it here:

https://github.com/askmike/gekko/tree/develop

(note that you need to fill BCH in as an asset, not a currency)

**Comment by ghost** [comment]
Thanks @askmike 

Just tested it with EUR/BCH and XBT/BCH which are working fine.

BCH/XBT is still an option and is causing the same error seen above. This pair needs removing.
