### ISSUE TITLE
[Feature Request] Tulip Indikators.

### ISSUE THREAD

**Issue by decoye** [askmike/gekko#1032]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**

[*] feature request

I like tulip indicators over the talib because the documentation is available and its well documented. would it not be nice to have this also available?

All the best.

**Comment by askmike** [comment]
It would be yes! However it's a lot of work to add. Closing this as a duplicate of #708.

**Comment by decoye** [comment]
alright thanks tho.

Am 23.08.17 um 18:37 schrieb Mike van Rossum:
