### ISSUE TITLE
[Request] Named instances

### ISSUE THREAD

**Issue by discosultan** [askmike/gekko#1033]
I'd find it very valuable if we could name gekko instances such that the name would show up both in the web UI as well as in the console (in the title bar, for example). The problem for me is that if I have a number of gekkos running, I find it difficult to track which instance is which.

What are the thoughts on this? Maybe something like this already exists and I'm simply unaware of it. I guess a workaround would be to view log files instead.

**Comment by askmike** [comment]
As for the CLI I am not sure how to even do this. What I do is use screen and name screen sessions accordingly. In different terminals you can sometimes set the title ([example](https://unix.stackexchange.com/questions/104018/set-dynamic-window-title-based-on-command-input)).

I definitely agree that we need this for the UI! The first step would be #911 which gives users more way to actually manage live gekkos. This is a nice follow up to that :)

**Comment by decoye** [comment]
Screen works perfectly fine for me here.

**Comment by discosultan** [comment]
And you could do this on Windows:

`start "Hi mom" node gekko.js`

**Comment by askmike** [comment]
Added this request to #911!
