### ISSUE TITLE
[Discussion] Experience Exchange Platform

### ISSUE THREAD

**Issue by decoye** [askmike/gekko#1035]
Hey Hey, 

i strongly opt for a platform where gekko users can exchange their knowledge about Gekko, from setting it up on different Systems to Trading strategies that they use.

Something like a forum or a subreddit, i often have the feeling that i and other users have questions that dont really fit into this place, but still need to be answered and a simple forum would be worth gold for that.

**Comment by askmike** [comment]
We have a discord channel now: https://discord.gg/26wMygt

Are you thinking something more permanent?

**Comment by decoye** [comment]
absolutely, i think learning only goes with consistency and spread of knowledge.
