### ISSUE TITLE
Common integration of the Gekko UI on a Server.

### ISSUE THREAD

**Issue by decoye** [askmike/gekko#1037]
Hey Hey, 

im interested in the way how people are accessing their ui in a server environment.
My interest is security, accessibility and comfort in the installation.

I would like to hear about ways how people have solved this.

**Comment by askmike** [comment]
AFAIK most people that run gekko in a public cloud use put nginx between the frontend and the backend, as described here:

https://gekko.wizb.it/docs/installation/installing_gekko_on_a_server.html#Configuring-Gekko-to-run-in-the-cloud

**Comment by decoye** [comment]
Thanks mike ill read into this.

**Comment by askmike** [comment]
cool!
