### ISSUE TITLE
GDAX import error

### ISSUE THREAD

**Issue by ghost** [askmike/gekko#1038]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Imported EUR/BTC on gdax from 2015-01-01 to 2017-08-08, import fails when scanning backwards at 2015-04-30

Also happens when importing from 2016 onwards (at 2016-05-27)

* **Expected result** (what you hoped would happen)
Import scans backwards successfully and then starts importing trades.

* **Actual result** (unexpected outcome)
2017-08-24 13:39:33 (DEBUG):    Scanning backwards...2016-05-27T01:30:35.205794Z
/home/x/gekko/exchanges/gdax.js:248
                if (moment.utc(last.time) < moment.utc(since)) {
                                   ^

TypeError: Cannot read property 'time' of undefined
    at Trader.<anonymous> (/home/x/gekko/exchanges/gdax.js:248:36)
    at Request._callback (/home/x/gekko/node_modules/gdax/lib/clients/public.js:45:7)
    at Request.self.callback (/home/x/gekko/node_modules/gdax/node_modules/request/request.js:187:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/home/x/gekko/node_modules/gdax/node_modules/request/request.js:1044:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/home/x/gekko/node_modules/gdax/node_modules/request/request.js:965:12)
    at emitNone (events.js:110:20)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Tested on main and develop branches.

**Comment by askmike** [comment]
Would you know by chance there was a market on GDAX for `EUR/BTC` before 2015-04-30?

**Comment by xyzzy529** [comment]
May 24, 2016 - Coinbase launches the Global Digital Asset Exchange (GDAX)
https://news.bitcoin.com/coinbase-launches-global-digital-asset-exchange-gdax/

So they probably loaded a year of back-data and that is it.
Good catch @askmike.
Maybe there could be a date (as we find them like this) for each exchange+pair that is the cut-off and the program could stop gracefully and put a warning out. 

"Warning: GDAX/BTC-EUR data starts on 2017/05/01"

**Comment by askmike** [comment]
Good idea, but hard to do that for all exchanges and markets, especially for exchanges like poloniex where Gekko can trade at ~200 different markets ([see here](https://github.com/askmike/gekko/blob/stable/exchanges/poloniex.js#L270-L585)).

Another solution would be: just before where it crashes here check if it was undefined. And if so stop Gekko with a message no trades were returned (and it most likely has to do with the market not being that old). What do you think?

**Comment by xyzzy529** [comment]
It would be good to have the check before it crashes.

Thinking if there was another config item that "could" be set to override some hard stop so Gekko would not generate errors.

Like: 
```
      { pair: ['BTC', 'USDE'], minimalOrder: { amount: 0.0001, unit: 'asset' } },
      { pair: ['BTC', 'USDT'], minimalOrder: { amount: 0.0001, unit: 'asset' },
              startHist: 1398924060000 /*new Date('May 1, 2015 12:01 AM')-0*/  },
      { pair: ['BTC', 'UTC'], minimalOrder: { amount: 0.0001, unit: 'asset' } },
```

As "we" the users find them, they can be refined in the code for an exchange. Most will probably just use whatever default you decide (like 2015/01/01 as an arbitrary default) to remove the error. If the user wants to go before 2015/01/01 then they will need to find a real date and add it to the exchange pair (as above example) and the code would use the market[].startHist to set a stop. 

I would worry that if the check is only for "no trades returned" then something else might cause that to happen and give a false stop.

**Comment by askmike** [comment]
Great idea! I am very open to a pull request for this - but for now I am closing as I won't have time for this anytime soon.
