### ISSUE TITLE
SQLITE_BUSY: database is locked at 23.59

### ISSUE THREAD

**Issue by THETCR** [askmike/gekko#1043]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)

Ran a market watcher.

* **Expected result** (what you hoped would happen)

Market watcher would run indefinitely. 

* **Actual result** (unexpected outcome)

Market watcher stops at 23.59.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

I ran it on different exchanges and by just starting the marker watcher or through the paper trader.

**Comment by decoye** [comment]
Would you have the console Log for it?

**Comment by THETCR** [comment]
Do you want the error gekko logs automatically or do you want me to edit the code so that it logs more?

The normal log displays this:

gekko    | Child process has died.
0|gekko    | events.js:182
0|gekko    |       throw er; // Unhandled 'error' event
0|gekko    |       ^
0|gekko    |
0|gekko    | Error: SQLITE_BUSY: database is locked
0|gekko    | RECEIVED ERROR IN GEKKO 913859956993271
0|gekko    | Child process has died.
0|gekko    | events.js:182
0|gekko    |       throw er; // Unhandled 'error' event
0|gekko    |       ^
0|gekko    |
0|gekko    | Error: SQLITE_BUSY: database is locked
0|gekko    | RECEIVED ERROR IN GEKKO 8589221147326636
0|gekko    | Child process has died.

**Comment by decoye** [comment]
What exaclty was it that you where doing when this happend?

**Comment by THETCR** [comment]
Gekko is running on my ubuntu server 24/7 with pm2. Everytime at midnight the market watchers crash. The server is not being used for anything else at the time and sqlite is only used for gekko.

**Comment by decoye** [comment]
okay, but what is gekko doing exactly?

oh sorry that was maybe unclear. what are you making gekko do by that time?

**Comment by askmike** [comment]
> SQLITE_BUSY: database is locked

Implies that Gekko could not open a handle to the sqlte database. Do you have more gekkos running connected to the same database?

**Comment by THETCR** [comment]
Just running a live market watcher or a paper trader in combination with a market watcher.

**Comment by askmike** [comment]
So in total you were running 2 live gekkos, and nothing else? Does this always happen at midnight?

**Comment by THETCR** [comment]
Nope, it happens on even one instance of a market watcher. It always happens at 00.00, with the last update occurring at 23.59

**Comment by decoye** [comment]
the time concerns me.
other than that i had similar issues with the sql, but the time factor i never had.

**Comment by askmike** [comment]
I am pretty sure this has something to do with your computer doing something at midnight (like a backup).

Can you tell me more about the system that is running Gekko? Type of system, OS, what else are you using it for?

**Comment by THETCR** [comment]
It's a vps with Ubuntu zesty. After your comment, i recon it could be a backup process from the provider. Will check it and report back.

**Comment by THETCR** [comment]
Apparently the provider runs a backup. Disabled it and the market watcher runs fine now. This issue can be closed.

**Comment by askmike** [comment]
great stuff :)

**Comment by thegamecat** [comment]
Anything else that accesses SQLite at the same time as Gekko = bad.
