### ISSUE TITLE
Feature request: Internal platform update functions

### ISSUE THREAD

**Issue by THETCR** [askmike/gekko#1045]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository

Current status:

Update gekko with git pull/clone

Wanted behavior:

Internal updater with ui/cli functions to make it easier to update gekko.

**Comment by askmike** [comment]
Good idea, pretty hard to implement though (cross platform). If anyone has any ideas how to do this properly, I am all ears :)

**Comment by THETCR** [comment]
My suggestion is to make a function that checks for the running version vs. the current(stable) version of gekko and then check the hash of the files (if the versions don't match). Then download the changed files accordingly, excluding config files.

**Comment by oktapodia** [comment]
@askmike you should schedule to use the github release, it will be easier to make an update with a check on this [endpoint](https://api.github.com/repos/askmike/gekko/releases)
