### ISSUE TITLE
Feature request: Store live traders

### ISSUE THREAD

**Issue by THETCR** [askmike/gekko#1046]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository

Current situation:

Wachters and traders aren't stored and lost on server reboot.

Wanted behavior:

Store watchers/traders in the database and restore on restart.

**Comment by askmike** [comment]
This is similar to #906, though how do you propose we automatically start Gekko when your server restarts?

**Comment by askmike** [comment]
I am closing this as a dup of #906, which will introduce a way to restart live gekkos whenever the UI restarts (see #911 for planned implementation). As for automatically starting Gekko on system reboot, you have to use something provided by your OS (like etc.initd)!

**Comment by THETCR** [comment]
I suggest adding the installation of pm2(preferred) or forever to the documentation and so making it the responsibility of the user.

**Comment by askmike** [comment]
Even if you install pm2 or forever: it won't restart your node process after your server reboots. Or is it nowadays?

**Comment by THETCR** [comment]
Nowadays it does.

Documentation:

http://pm2.keymetrics.io/docs/usage/startup/
