### ISSUE TITLE
Gekko Constant Crashing Windows 10 using Bash

### ISSUE THREAD

**Issue by sarktheshark** [askmike/gekko#1050]
**Bug report**

Whenever I try to import data from Poloniex or btcc - at completion (100%) it **faults** with this error code:

**Image of Fault:**
![poloniex import](https://user-images.githubusercontent.com/31423596/29797768-0e890cec-8c27-11e7-93ec-33c762a9109f.PNG)

**Code from Fault:**
![poloniex import code](https://user-images.githubusercontent.com/31423596/29797770-135fcb8e-8c27-11e7-984e-b12ca72013cf.PNG)

Also, when I try to scan for available data I get a similar error:

**Image of Fault:**
![scan available data](https://user-images.githubusercontent.com/31423596/29797644-670a42ba-8c26-11e7-9234-47e8b73003ef.PNG)

**Code from Fault:**
![scan available data code](https://user-images.githubusercontent.com/31423596/29797647-6bbe2f7e-8c26-11e7-95d7-8537512255ce.PNG)

System:
Windows 10 - I followed the "**Installing Gekko on Windows with bash on Windows 10**"
Step by step, code by code - yet this error is consistent.

Really good **100 mbps Cogeico** cable internet. 

Any suggestions would be appreciated.

**Comment by LeMoussel** [comment]
@sarktheshark,  subsidiary question : How did you install TA-Lib under Win 10?
Currently I got this message during installation :

>     $ npm install talib
>     npm ERR! code EBADPLATFORM
>     npm ERR! notsup Unsupported platform for talib@1.0.3: wanted {"os":"darwin,linux","arch":"any"}

**Comment by askmike** [comment]
ping @thegamecat

**Comment by vietlongn** [comment]
switch from sqlite to pgsql may solve this, it's work for me btw.

**Comment by sarktheshark** [comment]
@vietlongn sorry for the noob reply but what are those terms and how do I switch?

**Comment by vietlongn** [comment]
@sarktheshark you can follow these steps:

1. Install postgresql here https://www.postgresql.org/download/
2. Install  node pg module "npm install pg@6.1.0"
3. Open web/vue/UIconfig.js,  find adapter and change it to 'postgresql'
4. Open open web/routes/baseConfig.js and edit your postgresql connection string. It should be like this: postgres://postgres:{yourpasswordhere}@localhost:5432

**Comment by thegamecat** [comment]
Try these instructions with SQlite - almost certainly it's this.
http://gekkowarez.com/running-gekko-sqlite-in-windows-10-bash/

**Comment by thegamecat** [comment]
@LeMoussel  use BASH on windows 10 if you want to use talib. It's very easy to setup.
