### ISSUE TITLE
Stich Existing Local Data to Current Data in UI for New Trader Bot

### ISSUE THREAD

**Issue by KevTheRev13** [askmike/gekko#1051]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[X] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Let's say I have 5 days worth of history from a paper trader, importer, or other trader bot. I now start a new trader bot through the UI, 3 hours after stopping the last one. Currency, Asset, and all strategy parameters are exactly the same as the prior 5 days of history.

* **Expected result** (what you hoped would happen)
When starting the new trader bot from the UI, it would contact the exchange (Assuming it was one that could import) and it would fill in the missing time together between the 5 day history and the start time of the new bot - effectively dramatically shortening the warmup period. The UI would tell me that it is attempting to fill in the time gaps, and let me know if successful.

* **Actual result** (unexpected outcome)
The trader bot doesnt appear to see the old data at all due to the time gap. I couldn't get it to even check for local data when starting a new trader bot at all from the UI. I am, however, able to do this from the CL (it appears, havent tried too hard yet).

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
Will/is this being implemented for the UI? Thank you.

**Comment by askmike** [comment]
Whenever the UI starts a live trader we actually start 2 gekkos: one market watcher (that pumps market data in database) and one that "leeches" from the database. This way you can have multiple stratrunners on the same market very easy.

However this makes the above a bit trickier to implement. Will implement at some point, but not before #911.

**Comment by KevTheRev13** [comment]
Yes, I see that. No worries though, #911 has some great things too I see.

Thanks for putting this together! I look forward to future updates.

**Comment by Guceri** [comment]
I'm a little confused, I thought that gekko DOES fill in the missing data into the local database if a live strategy requires historical data that might not be completely available in the local data set. 

For example:
 If I have a strategy that requires 100 - 5min bars and I have 95 of them in my local data base when I start my live gekko,  it will work to download the missing data and then run my strategy once it has the 100 bars stored in the local database.....

is this not what gekko does now? It appears it does when I start my gekko through the UI.  I just put a simple console.log notice to see when the update/check functions would be called on and it seems that everything works shortly after turning a strat on through the UI

**Comment by askmike** [comment]
> If I have a strategy that requires 100 - 5min bars and I have 95 of them in my local data base when I start my live gekko, it will work to download the missing data and then run my strategy once it has the 100 bars stored in the local database.....

This system IS used when you start a live Gekko with the commandline interface: it will automatically stitch historical data. However this is NOT used with the UI: the live gekko will not use local data, just what data the exchange sends.

**Comment by Guceri** [comment]
Thanks Mike. Appreciate all the work you (and all the contributors) are doing...... I started a strategy through CLI and was finally able to get it to run (I was using the UI and couldn't figure out why the log & check functions were not firing).
