### ISSUE TITLE
I was able to install and run gekko successfully. however, when i install mongojs module it shows below error  

### ISSUE THREAD

**Issue by gauravkhrnr** [askmike/gekko#1052]
**Bug Report**
when i tried to install mongojs module from latest gekko i get the following error.. any help please
![mongojs_issue](https://user-images.githubusercontent.com/20242899/29805740-2c1ad178-8ca9-11e7-91d4-9af8a5b13c74.png)

**Comment by askmike** [comment]
This would only install a driver for mongo so that Gekko can talk to a mongo database. Before we look at the issue: do you have a mongo database installed / available?

**Comment by gauravkhrnr** [comment]
yes I have installed mongo database

**Comment by askmike** [comment]
Does this repeatedly fail?

**Comment by gauravkhrnr** [comment]
yes

**Comment by askmike** [comment]
ping @zeroX-tj, @S7evinK have you guys ever seen this?

**Comment by discosultan** [comment]
I also see this error whenever gekko gets an update and I need to run `npm i` again.

**Comment by S7evinK** [comment]
I guess running `npm i` before installing mongojs should solve this issue. (Like @discosultan mentioned)

The error message states, that it can't find `node_modules\sqlite3\node_modules\node-pre-gyp\node_modules\npmlog\node_modules\are-we-there-yet\node_modules\delegates`, probably because `npm install mongojs --save` was executed directly after checkout or something like that. (Couldn't reproduce this on Linux)

I'm not sure why installing mongojs would trigger something with sqlite3.

**Comment by gauravkhrnr** [comment]
after running npm i . I am facing same problem

**Comment by gauravkhrnr** [comment]
Even after running npm i ... I am facing same problem

**Comment by askmike** [comment]
can you post the full output of `npm i`? Maybe something went wrong. Also please post the output of:

    npm -v
    node -v

**Comment by S7evinK** [comment]
Just got the same error while trying to install `node-telegram-bot-api`

Running `npm install sqlite3 mongojs --save` works for me. (npm 5.3.0, node 8.4.0)

// Edit: Already reported https://github.com/mapbox/node-sqlite3/issues/866

**Comment by gauravkhrnr** [comment]
npm -v  o/p 5.3.0
node -v o/p v8.2.0

**Comment by S7evinK** [comment]
`npm i sqlite3@3.1.8 --save-exact`
`npm i mongojs --save`
`npm i`

should do the trick.

**Comment by gauravkhrnr** [comment]
Thank you very much friends for helping me. My problem is resolved. I did following activities and things worked for me
1) deleted node_modules folder in Gekko (because npm i was not installing properly)
2) npm i
3) npm node-pre-gyp install --fallback-to-build
4) npm install sqlite3 mongojs --save

**Comment by askmike** [comment]
great!

**Comment by mdomeralikhan** [comment]
![untitled](https://user-images.githubusercontent.com/34879237/34396541-74acba1c-eb92-11e7-8b6a-2b7b66fc776c.png)

**Comment by mdomeralikhan** [comment]
hello sir, i have followed the instructions but its not opening after reaching this point please help me out here. thank you
