### ISSUE TITLE
Gekko is not running on cloud

### ISSUE THREAD

**Issue by gauravkhrnr** [askmike/gekko#1057]
**bug report**
I deployed gekko on google cloud today ,however it didn't run on google cloud .giving me the below error
![googlcouldissue](https://user-images.githubusercontent.com/20242899/29933762-6c7c400a-8e96-11e7-958b-e231d718f2a6.png)

**Comment by askmike** [comment]
Gekko is running fine, that's a warning. The warning comes from you having set headless to false in the UIConfig. Please see the documentation here: https://gekko.wizb.it/docs/installation/installing_gekko_on_a_server.html

:)
