### ISSUE TITLE
[QUESTION] Determining trends, finding candle patterns, buy, sell, profit

### ISSUE THREAD

**Issue by chadillac81** [askmike/gekko#1060]
I'm attempting to combine DEMA with my own rules, for which I utilize the candle data (candle.close, etc).  How would one get the current trend from DEMA in the results?  When I log the results variable, it's blank.  How is the information stored?  Or, how can I reference this information?

I've looked through the documentation, but the small stuff like this doesn't seem to be documented.  Is there a decent custom strategy example that uses candle data along with a built-in trading strategy that you could point me to for reference?

**Comment by askmike** [comment]
Hey!

> I'm attempting to combine DEMA with my own rules, for which I utilize the candle data (candle.close, etc).

For this you would create your own strategy that adds the DEMA indicator. After this you have access to the DEMA diff value as well as the candle in each update call.

Here is an example: https://gist.github.com/askmike/9264c4364f230100d59dafb696d98a14

Feel free to ask further questions :)

The documentation is due for some improvement, I'd love some help with the docs (what exactly is not clear - how can we improve). If you have any ideas here let me know!
