### ISSUE TITLE
[SUGGESTION] Backtesting graph, draw indicators (MACD, DEMA, etc) on graph, and using candlesticks

### ISSUE THREAD

**Issue by chadillac81** [askmike/gekko#1061]
When backtesting, we get a line graph.  This project is based on candles, so why do we not get a candlestick chart instead?  Also, when apply MACD or DEMA or any other strategy, could these be drawn to the graph as well?

It just seems like it would make more sense if we could visualize what our config changes are doing by drawing it on the chart.

**Comment by askmike** [comment]
> Also, when apply MACD or DEMA or any other strategy, could these be drawn to the graph as well?

This is in progress, see #793 for details :)

> When backtesting, we get a line graph. This project is based on candles, so why do we not get a candlestick chart instead?

Good idea, I've added that to the TODO for #793.

**Comment by askmike** [comment]
Closing this as a dup of #793. feel free to reply either here or there :)
