### ISSUE TITLE
Getting gekko run in google cloud returned Mixed Content error

### ISSUE THREAD

**Issue by gauravkhrnr** [askmike/gekko#1062]
**bug report**
I deployed gekko on google cloud ,however I run gekko is disconnected giving me the below error on browser console
![issue](https://user-images.githubusercontent.com/20242899/29961312-db6d67d8-8f1c-11e7-8f71-ab7252bdf137.png)

**Comment by askmike** [comment]
Hey, you need to configure your UIConfig, see here: https://gekko.wizb.it/docs/installation/installing_gekko_on_a_server.html

In your case:
- Chrome is complaining about the API calls not going through ssl, if you set ssl to true in your config Gekko will use ssl links (HTTPS and WSS).
- After that: you have hosted Gekko in the cloud but your UIConfig is configured to connect to localhost, set the host and port properties to reflect where you are running gekko (the `node gekko --ui` command).

If you have any questions feel free to ask :)
