### ISSUE TITLE
UI styling Features

### ISSUE THREAD

**Issue by decoye** [askmike/gekko#1063]
Hey is it possible to have different ui styles by css?

how is the look of the UI defined in general?

**Comment by askmike** [comment]
This is the CSS framework used:

https://picnicss.com/

All other css is bundled by webpack (per vue component).

And yes that is possible, first setup the UI for development: https://gekko.wizb.it/docs/internals/gekko_ui.html

After that, you can create create a new css file and add it here: https://github.com/askmike/gekko/blob/stable/web/vue/index.html

Unfortunately that is how far custom CSS will go now! If you have any issues feel free to comment :)
