### ISSUE TITLE
Gekko GUI not working after launching docker containers

### ISSUE THREAD

**Issue by babatundebusari** [askmike/gekko#1065]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[* ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)

* **Expected result** (what you hoped would happen)
Working UI
http://<ip>:3000 should be working

* **Actual result** (unexpected outcome)
Not working
```
Disconnected
Something happened to either Gekko or the connection. Please check the terminal where Gekko is running or your network connection.
```

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

```
root@babatundebusari:~/gekko# docker-compose ps
    Name                   Command               State           Ports
-------------------------------------------------------------------------------
gekko_gekko_1   /usr/src/app/docker-entryp ...   Up      0.0.0.0:3000->3000/tcp
gekko_redis_1   docker-entrypoint.sh redis ...   Up      6379/tcp
root@babatundebusari:~/gekko# docker-compose ps
    Name                   Command               State           Ports
-------------------------------------------------------------------------------
gekko_gekko_1   /usr/src/app/docker-entryp ...   Up      0.0.0.0:3000->3000/tcp
gekko_redis_1   docker-entrypoint.sh redis ...   Up      6379/tcp
root@babatundebusari:~/gekko# docker logs -f gekko_gekko_1
npm info it worked if it ends with ok
npm info using npm@3.10.3
npm info using node@v6.3.1
npm info lifecycle gekko@0.5.6~prestart: gekko@0.5.6
npm info lifecycle gekko@0.5.6~start: gekko@0.5.6

> gekko@0.5.6 start /usr/src/app
> node ./gekko --config config.js --ui


    ______   ________  __    __  __    __   ______
   /      \ /        |/  |  /  |/  |  /  | /      \
  /$$$$$$  |$$$$$$$$/ $$ | /$$/ $$ | /$$/ /$$$$$$  |
  $$ | _$$/ $$ |__    $$ |/$$/  $$ |/$$/  $$ |  $$ |
  $$ |/    |$$    |   $$  $$<   $$  $$<   $$ |  $$ |
  $$ |$$$$ |$$$$$/    $$$$$  \  $$$$$  \  $$ |  $$ |
  $$ \__$$ |$$ |_____ $$ |$$  \ $$ |$$  \ $$ \__$$ |
  $$    $$/ $$       |$$ | $$  |$$ | $$  |$$    $$/
   $$$$$$/  $$$$$$$$/ $$/   $$/ $$/   $$/  $$$$$$/

	Gekko v0.5.6
	I'm gonna make you rich, Bud Fox.


TAlib is enabled
Serving Gekko UI on http://localhost:3000/

  <-- GET /favicon.ico
  --> GET /favicon.ico 404 6ms -
```

![image](https://user-images.githubusercontent.com/6054104/29984033-74cc6998-8f26-11e7-91fc-cdd172d38f0e.png)

![image](https://user-images.githubusercontent.com/6054104/29984019-6599f83c-8f26-11e7-9c3e-1363bdc23730.png)

**Comment by babatundebusari** [comment]
here is what i get with curl

```
root@babatundebusari:~/gekko# curl -s http://10.247.1.10:3000
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Gekko</title>
    <link rel="stylesheet" href="/assets/furtive.min.css">
  </head>
  <body>
    <div id="app"></div>
    <script src='/UIconfig.js'></script>
    <script src='/assets/reconnecting-websocket.min.js'></script>
    <script src='/assets/moment.js'></script>
    <script src='/assets/d3.js'></script>
    <script src='/assets/toml.js'></script>
    <script src='/assets/humanize-duration.js'></script>
    <script src='/dist/build.js'></script>
  </body>
</html>
```

**Comment by babatundebusari** [comment]
@askmike @jonrh @williamcoates @metachris @iceydee 
anyone willing to help here?
urgently will like to check this out
and i am running latest code but with these errors

please help

**Comment by askmike** [comment]
Could you post the docker compose options you used to build?

**Comment by zeroX-tj** [comment]
I could be wrong(never ran it in docker) but shouldn't the UIconfig be updated to use http://10.247.1.10:3000 as the api if you run it on a external server

**Comment by babatundebusari** [comment]
ok tried this passing the HOST and PORT options and now it works

root@babatundebusari:~/gekko# HOST=gekko.com PORT=8080 docker-compose up -d
Creating gekko_redis_1 ...
Creating gekko_redis_1 ... done
Creating gekko_gekko_1 ...
Creating gekko_gekko_1 ... done

![image](https://user-images.githubusercontent.com/6054104/29987893-6a9fff68-8f38-11e7-9468-228479168cb6.png)

**Comment by askmike** [comment]
Great!

@zeroX-tj when using Docker compose the UIConfig is generated using docker :)

**Comment by curlingcowcows** [comment]
I was have the same issue, receiving disconnected error.

 I was able to get gekko running without issue by using docker-compose in the repo.

Dont give up

**Comment by keiranharris** [comment]
Hi @askmike - im getting exactly the same issue - ive been struggling for a few days trying to debug this on my own - but its time to ask for help as im getting nowhere! 
1/ i did a git clone of your full repo (probably unnecessary as im running the docker instance of your app- but at least i get the docker-compse.yml!) 
2/ followed the instructions here  https://gekko.wizb.it/docs/installation/installing_gekko_using_docker.html
3/ hit the GUI on port :3000  (from either localhost, or over my local network to the machine IP)
4/ straight away get bounced with the "Disconnected" popup. 

my docker-compose is this: 
```
keiran@vm-ubuntu:/_LOCALDATA/CONTAINERS/gekko$ cat docker-compose.yml 
version: '3'
services:
  gekko:
    restart: always
    build: ./
    volumes:
      - ./volumes/gekko/history:/usr/src/app/history
      - ./config.js:/usr/src/app/config.js
    links:
      - redis
    environment:
     - HOST
     - PORT
    ports: 
      - "${PORT}:${PORT}"
  redis:
    image: redis:latest
    volumes:
      - ./volumes/redis:/data

```
my docker ps and logs output is: 
```
keiran@vm-ubuntu:/_LOCALDATA/CONTAINERS/gekko$ docker ps
CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS              PORTS                    NAMES
5d6bcb3f1769        gekko_gekko           "/usr/src/app/docker…"   17 minutes ago      Up 17 minutes       0.0.0.0:3000->3000/tcp   gekko_gekko_1
afa3e9a3f696        redis:latest          "docker-entrypoint.s…"   17 minutes ago      Up 17 minutes       6379/tcp                 gekko_redis_1
fce76f9dc816        portainer/portainer   "/portainer"             About an hour ago   Up About an hour    0.0.0.0:9000->9000/tcp   cocky_feynman


keiran@vm-ubuntu:/_LOCALDATA/CONTAINERS/gekko$ docker logs -f 5d6bcb3f1769

    ______   ________  __    __  __    __   ______
   /      \ /        |/  |  /  |/  |  /  | /      \
  /$$$$$$  |$$$$$$$$/ $$ | /$$/ $$ | /$$/ /$$$$$$  |
  $$ | _$$/ $$ |__    $$ |/$$/  $$ |/$$/  $$ |  $$ |
  $$ |/    |$$    |   $$  $$<   $$  $$<   $$ |  $$ |
  $$ |$$$$ |$$$$$/    $$$$$  \  $$$$$  \  $$ |  $$ |
  $$ \__$$ |$$ |_____ $$ |$$  \ $$ |$$  \ $$ \__$$ |
  $$    $$/ $$       |$$ | $$  |$$ | $$  |$$    $$/ 
   $$$$$$/  $$$$$$$$/ $$/   $$/ $$/   $$/  $$$$$$/

	Gekko v0.6.8
	I'm gonna make you rich, Bud Fox. 


Serving Gekko UI on http://localhost:3000/

Something went wrong when trying to open your web browser. UI is running on http://localhost:3000/

```
not quite sure how to debug any further. 
I did get it running in docker on my mac easily BTW - but this is the perm install on a more perm ubunto box i have running always. 

grateful for your help!! 
Keiran

**Comment by keiranharris** [comment]
^ ignore me, found thew solution (AND you did already have it documented! sorry). Running with the command line args of setting HOST and PORT did it for me - sorry i misread your docs thought you only needed those params if accessing over the internet to the cloud (where you would plug in a FQDN DNS).... didnt think it would be needed when running over the same home LAN. Spelling the docker-compose out below for anyone else that stumbles into this same problem (so my internal server machine is 10.1.5.10, and therefor i hit the gekko UI on http://10.1.5.50:3001/)  
`$ HOST=10.1.5.10 PORT=3001 docker-compose up -d`
