### ISSUE TITLE
what Gekko can and cannot do

### ISSUE THREAD

**Issue by jon85j** [askmike/gekko#1067]
Hey,

this is more for my own education really, so i'm grateful for any quick explanations here, having read all the documentation.

I am interested in getting Gekko to run backtests for strategy testing, as well as analyzing live market data, then sending a ping when it thinks i should trade looking at current day market (according to my strategy settings) 
Can gekko do both these thing at the same time?

If not, do you need to have seperate instances of gekko?

thanks

**Comment by askmike** [comment]
Hey! If you use the UI you can run a live gekko, while at the same time doing some backtests (under the hood Gekko will start multiple instances).

As for the "ping" Gekko has some plugins that can email on advice, but the plugin system requires you to run Gekko in CLI mode. If you want that you need to run one Gekko UI (`node gekko --ui`) to use for backtesing and one instance in CLI mode to ping you `node gekko --config config.js`).

**Comment by jon85j** [comment]
So by saying a live gekko, I can have an advice based trading notification, that is reading and analysing live market data, based on what I set?

**Comment by askmike** [comment]
Yes!

**Comment by askmike** [comment]
If you have more questions, feel free to ask them here :)
