### ISSUE TITLE
Have Gekko UI be able to trigger a Portfolio Balance Update

### ISSUE THREAD

**Issue by KevTheRev13** [askmike/gekko#1070]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[X ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Started a Live trading gekko so data could gather. Then a couple weeks later, add some USD and/or Coin to the same exchange account.

* **Expected result** (what you hoped would happen)
The gekko live trader would allow for a "refresh account parameters" button, which I could press after modifying account balances and it would update these within the live trader without having to kill it.

* **Actual result** (unexpected outcome)
Haven't tried it with real money yet, but I only see it pulling the portfolio details at startup. Correct me if I'm wrong, but I don't think it will pull portfolio details again.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Disclaimer: I think gekko has really a lot of potential to be a great tool for automated trading, and these suggestions are meant to improve it. I'm a developer myself and a big believer in open-source code.

I've spent the last several days running hundreds of backtests on about 2.5 years of data with a few of the most common strategies/parameters used in Forex trading. The results I have show that it is very possible to beat the market in downward trends, and nearly match the market in bitcoin's ridiculous 1700% increase of the last 2.5 years with gekko ( I got 1090% with a standard strategy that ran about 50 trades over that time)   - assuming that gekko doesnt have any bugs or errors.

But the deciding factor ? Longer Candle and History sizes. The most successful trading strategies, both in a short term scope (1-3 months) and long term (1-2 years) all require at least a couple weeks worth of data. 

It seems, like most investing, successful trading with gekko is a long term game. However, it's tough to not be able to move around a balance for several months if you are actively trading. Having an "on-demand" account refresh option (just asset and currency) would go a long way into increasing the usability of gekko. 

I appreciate your work on the project. Thanks!

**Comment by KevTheRev13** [comment]
![image](https://user-images.githubusercontent.com/19419989/29991866-2dc163a0-8f5d-11e7-9278-97606b188618.png)


The awesome potential of gekko :D 

The hardest thing about long term holding is managing downturns - gekko can help navigate the bubbles (and minimize losses on crashes) with only a small hit in an overly positive market. Would love a balance refresh button to move this closer to a long term tool. Thanks for hearing my input.

**Comment by decoye** [comment]
but your gekko made loss there, whats the point of following a strategy when it is not profitable over buy and hold?

**Comment by askmike** [comment]
Hey @KevTheRev13,

> The gekko live trader would allow for a "refresh account parameters" button, which I could press after modifying account balances and it would update these within the live trader without having to kill it.

Gekko actually always pull your fresh balance from an exchange before making a trade, so there is no need to manually press a button.

----

But note that the bigger problem lays in calculating profit statistics: Right now Gekko calculates profit by measuring your current portfolio against how it looked when you started Gekko. So if you start depositing or withdrawing money these numbers are not correct anymore.

**Comment by KevTheRev13** [comment]
@decoye Oh my gosh, lots :-) It is a tradeoff between profit and risk. If I bought and hold for those 2.5 years, there is no mathematical strategy (at least moving average based like DEMA, MACD, or PPO) that could have possibly have matched it. I think technical trading algorithms will almost always be less profitable in a super positive trending market (like bitcoin) because most rely on lagging indicators. Everything is reactive vs proactive. The benefit lies in a downturn - if the market crashes 60% in a few hours then an algorithm may save your butt compared to if you bought and hold. With buy and hold, you might lose 60% and never know if your investment is going back up. With an algorithm, you might only lose 25% and have some funds left to make use of the downturn with strong buying power at a low point. The idea is that with an algorithm in this type of market you reduce your risk, at the expense of some of the overall profit of a buy and hold strategy if it does recover sharply like bitcoin has.

Also to note, when I run this same strategy on a shorter timeframe that has a negative overall return, it often produces a small positive one. But long term bitcoin has rose like 2000%... no algorithm would have guessed that.

@askmike Oh I see - I misunderstood a comment on the Discord server I saw. If it is only the profit calculations that become inaccurate, then that is just fine :-) Thanks for your reply and for closing the issue.

**Comment by decoye** [comment]
Okay i see your point. Enjoy your technical trading time. Gekko is an amazing tool. I think you are at the right time at the right place doing the right thing.

**Comment by decoye** [comment]
"at the expense of some of the overall profit of a buy and hold strategy if it does recover sharply like bitcoin has."

Buy and hold is not a strategy.

**Comment by KevTheRev13** [comment]
@decoye  Thank you, you too! Happy Trading.

(this does not constitute formal trading advice and the user assumes all risks.)
