### ISSUE TITLE
Unable to create ssl while depolying application on google cloud 

### ISSUE THREAD

**Issue by gauravkhrnr** [askmike/gekko#1071]
**bug report**
Unable to create ssl while depolying application on google cloud .we are getting below error
DNS problem: SERVFAIL looking up A for crypcash.com

![dns-error](https://user-images.githubusercontent.com/20242899/29994117-850045cc-8fe5-11e7-841e-c84b0a953571.png)

**Comment by askmike** [comment]
So you own the domain you are trying to get a cert for and it's connected to the server you are running this on?

**Comment by askmike** [comment]
It seems there was a problem with the DNS records for crypcash.com, unfortunately I don't know enough about troubleshooting DNS issues to fix this. If you have a problem running certbot, I'd suggest posting an issue here: https://github.com/certbot/certbot
