### ISSUE TITLE
can't find Kraken among exchange markets

### ISSUE THREAD

**Issue by kalzso** [askmike/gekko#1073]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Wanted to start a new bot

* **Expected result** (what you hoped would happen)
I expected to find Kraken in the list

* **Actual result** (unexpected outcome)
Kraken is missing from the list

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
pic:
http://tinypic.com/r/mubonp/9

**Comment by askmike** [comment]
Make sure you have the latest version of the kraken dependency, you can force this by running:

    npm install kraken-api-es5@1.0.0
