### ISSUE TITLE
Log file...

### ISSUE THREAD

**Issue by rlbewick** [askmike/gekko#1077]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Nothing but run the PaperTrader....

* **Expected result** (what you hoped would happen)
I hoped there would be a log file of trades but nothing.

* **Actual result** (unexpected outcome)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
How do I run the PaperTrader or Live Trader in the UI with a log file?  I feel this should be done by default myself but if I have to invoke it no worries.  Thanks Mike.

**Comment by askmike** [comment]
When you run a paper trader logs will automatically be stored in the logs folder!

**Comment by decoye** [comment]
is it possible that only with the paper trader logs are written?
because when i run the live trader im not getting any logs.

**Comment by askmike** [comment]
@decoye soon, see #978.

**Comment by decoye** [comment]
im sorry, but i dont get the reason for it.
