### ISSUE TITLE
Debugging the script

### ISSUE THREAD

**Issue by AlfredoBB** [askmike/gekko#1080]
Bug report.

I'm writing a complex multi indicator script. At this point I spend much more time debugging it than writing it. A misplaced quotation mark or missing semicolon introduced by mistake is not told by the program and one has to place console.log() everywhere.

* **Action taken** (what you did)i

node debug gekko --ui

* **Expected result** (what you hoped would happen)
Breakpoint everytime a debugger; word appeared in the script.

* **Actual result** (unexpected outcome)
Program froze when reading the database. It shows the following outcome 6 times, hangs (as if it was infinitely scanning local data) and spawns 6 nodejs processes that put processor at 100%

< Error: listen EADDRINUSE :::5858
<     at Object.exports._errnoException (util.js:1020:11)
<     at exports._exceptionWithHostPort (util.js:1043:20)
<     at Agent.Server._listen2 (net.js:1258:14)
<     at listen (net.js:1294:10)
<     at net.js:1404:9
<     at _combinedTickCallback (internal/process/next_tick.js:83:11)
<     at process._tickCallback (internal/process/next_tick.js:104:9)

these processes persist after closing the main program.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Platform: Ubuntu 16.04 LTS; jsnode 6, talib installed.

**Comment by AlfredoBB** [comment]
If I use 
node --inspect gekko ui
when opening the database it says
"Unable to open devtools socket: address already in use"

**Comment by AlfredoBB** [comment]
maybe I should go for jsnode 8

**Comment by zeroX-tj** [comment]
If you run gekko with the ui it will fork a new process to run the backtest, and it inherits the debug port from the master process. You can work around it by passing a new debug port to the child but meh :)

Easiest way to debug strategies is to run/debug them on the command line without the ui, when it works use the ui

**Comment by askmike** [comment]
Like @zeroX-tj said, depending on what you are trying to debug we could advice you to run what you want to test without running everything else. The only time I run the UI is when I am working on deverlopment of the UI or I am actually using Gekko. All my time in developing everything of core (or strategies) is done using either the commandline interface or simply running isolated components of Gekko.

**Comment by AlfredoBB** [comment]
thank you
I'm still figuring out how to run from the command line in backtest mode and I'm having lots of problems

gekko.js gave an error that disappeared when I removed the caution message in the line 53 (maybe it "config.enabled" was being evaluated before "config" object was available?

now it gives an error: if(mode === 'backtest' && config.backtest.daterange === 'scan')
                                                                                                   ^
"Cannot read property 'daterange' of undefined"

maybe daterange is an object {from: "", to ""} instead of a property?

FInally, what is the batchSize property of config.backtesting in config.js?

thank you

**Comment by askmike** [comment]
> batchSize

It's an internal setting you can leave per default (unless you have memory problems), it indicates how many candles Gekkos should fetch at once before piping them into your strategy.

---

Can you post the config file you were trying?

**Comment by AlfredoBB** [comment]
```
var config = {};

config.debug = true; // for additional logging / debugging

config.trader = {
  enabled: false,
  key: '',
  secret: '',
  username: '', // your username, only required for specific exchanges.
  passphrase: '' // GDAX, requires a passphrase.
}


config.watch = {

  exchange: 'poloniex',
  currency: 'USDT',
  asset: 'BTC'
}



config.paperTrader = {
  enabled: true,
  reportInCurrency: true,
  simulationBalance: {
    asset: 1,
    currency: 100,
  },
  verbose: false,
  feeMaker: 0.15,
  feeTaker: 0.25,
  feeUsing: 'maker',
  slippage: 0.001
}


config.tradingAdvisor = {
  enabled: true,
  method: 'LosNardosv3',
  candleSize: 1,
  historySize: 3,
  adapter: 'sqlite',
  talib: {
    enabled: true,
    version: '1.0.2'
  }
}



config.adviceLogger = {
  enabled: false
}

config.performanceAnalyzer = {
  enabled: true,
  riskFreeReturn: 5
}



config.adapter = 'sqlite';

config.sqlite = {
  path: 'plugins/sqlite',

  dataDirectory: 'history',
  version: 0.1,

  dependencies: []
}

config.backtest = {
    daterange: {from: '2017-07-01', to: '2017-08-01'},
    batchSize: 50
}

**Comment by askmike** [comment]
Does your config has this at the end?

> module.exports = config;

**Comment by AlfredoBB** [comment]
That was exactly my problem.
Thank you very much.

**Comment by askmike** [comment]
Great! So now you are able to backtest using the commandline. This should be a lot easier to debug, if you have any questions feel free to ask them!
