### ISSUE TITLE
No trade with RSI strategy on bitfinex

### ISSUE THREAD

**Issue by evseevnn-zz** [askmike/gekko#1082]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Just set up RSI strategy for trage on pair USD/OMG
with configuration
```
{
    "interval": 17,
    "thresholds": {
        "low": 50,
        "high": 70,
        "persistence": 1
    }
}
```

* **Expected result** (what you hoped would happen)
New order on bitfinex

* **Actual result** (unexpected outcome)
No result after 9 hours, but if i use backtest that work!

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
Can you share the logs? If you were running via the UI those can be found in the `logs` folder inside the gekko directory.

**Comment by evseevnn-zz** [comment]
https://drive.google.com/open?id=0B4o83Yoe5JRFYXpxZXYwTHA2ZDA
@askmike 
Pls say me when you download it. I will lock access to file.

**Comment by askmike** [comment]
@evseevnn downloaded it, will try to fix asap.

**Comment by evseevnn-zz** [comment]
@askmike Thank you, Mike

**Comment by decoye** [comment]
also not able to trade on bitfinex, not trading with rsi. but any strategy will not trade.

unfortunately i have no logs, running cli.

**Comment by evseevnn-zz** [comment]
@decoye I successfully trade on bitfinex with CCI

**Comment by decoye** [comment]
okay, i've tested dema, macd, rsi. they dont work for me.

**Comment by askmike** [comment]
@decoye without any logs or reproducible situation there is no way we can help you!

**Comment by decoye** [comment]
Yes i know. But how am i supposed to provide any feedback to it?All i can tell you is that gekko sends out mail with advice but does not carry out the advice on the exchange.So tell me how to debug it?
null

**Comment by askmike** [comment]
@decoye please open a new issue since you have a different problem. And if you use the CLI mode please post the output of the CLI (these are identical to the logs).

**Comment by decoye** [comment]
Im using screen. That means i only have a limited amount of log available.

**Comment by evseevnn-zz** [comment]
@askmike 
Any news about problem with RSI strategy?
May be you can say me where i should search the problem and i can try fix it my self?

**Comment by evseevnn-zz** [comment]
@askmike Very strange. I try it again. And... that work!
I see more not stability at gekko. I write about this to your in private message.
Now that work, without any update. I think i can close the issue.

**Comment by evseevnn-zz** [comment]
Got it again.
Bot buy but never sale.

**Comment by infohoard** [comment]
Same issue... can't get it to run reliably for more than a day. My bot fails during the 2nd day of live trading. Here's the output

```
2017-09-12 12:30:30 (DEBUG):    Requested LTC/USD trade data from Bitfinex ...
2017-09-12 12:30:32 (DEBUG):    Processing 6 new trades. From 2017-09-12 04:30:14 UTC to 2017-09-12 04:30:29 UTC. (a few seconds)
2017-09-12 12:30:37 (INFO):     SELL order was not (fully) filled, cancelling and creating new order
2017-09-12 12:30:40 (INFO):     Attempting to SELL X.XXXXXXXX LTC at Bitfinex price: XX.XX
2017-09-12 12:30:41 (ERROR):    unable to sell Error: Invalid order: not enough exchange balance for -X.XXXXXXXX LTCUSD at XX.XX
    at Request._callback (/home/trader/gekko/node_modules/bitfinex-api-node/rest.js:66:23)
    at Request.self.callback (/home/trader/gekko/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/trader/gekko/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/trader/gekko/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7) undefined
/home/trader/gekko/exchanges/bitfinex.js:126
        return this.retry(this.submit_order, args);
                    ^

TypeError: this.retry is not a function
    at /home/trader/gekko/exchanges/bitfinex.js:126:21
    at Request._callback (/home/trader/gekko/node_modules/bitfinex-api-node/rest.js:66:20)
    at Request.self.callback (/home/trader/gekko/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/trader/gekko/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/trader/gekko/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)

```

Note that I definitely had enough balance to trade. This is the second time this issue occured. 

Also, it seems to cease trading activity entirely at some point of time hours before this error occurred. I know because I was outside monitoring the exchange but my bot were not doing any buying/selling at very obvious signals. However as i was using 'screen' command I was unable to view the log outputs as it was too far back and was cut away by 'screen'.

**Comment by evseevnn-zz** [comment]
@askmike  
Any news?

**Comment by askmike** [comment]
@evseevnn do you remember which trader did not work? This one did a succesfull buy: `2017-09-04-19-16-UTC-tradebot.log`. This one as well: `2017-09-04-13-30-UTC-tradebot.log`.

**Comment by evseevnn-zz** [comment]
@askmike Yes! not work when i trade on bitfinex. And yes, only one trade, but that work different than the backtest. Strange but with RSI  trade only one time and stop. Im just wait long time and later try run backtest on data what i get, and result so much different

**Comment by evseevnn-zz** [comment]
@askmike this look like can buy but never sell. two times already i had same problem.

**Comment by askmike** [comment]
Do you have a specific case of this problem (in the log zip for example)?

**Comment by evseevnn-zz** [comment]
@askmike i'm already gave log for you before.
https://drive.google.com/open?id=0B4o83Yoe5JRFYXpxZXYwTHA2ZDA

**Comment by evseevnn-zz** [comment]
@askmike Can i remove log?

**Comment by askmike** [comment]
@evseevnn yes you can remove it, though: In your zip I cannot find any gekko that even tried to sell, are you sure your strat signalled to sell in any of the gekkos in the zip?

**Comment by evseevnn-zz** [comment]
@askmike I'm traced all orders, what create the bot in trading period. But never got sell order, only one for buy. But when i trying use backtesting for test this strategy in same period i see more actions. That problem.

**Comment by evseevnn-zz** [comment]
@askmike any news?

**Comment by sarperhorata** [comment]
I am also unable to start trading with BTC - USD. 
I have 0.09 BTC in my account o go with the bot, it is open since for a while but there is no trade.
Screenshot of my configuration is provided below, what am I missing? Please let me know.
![screen shot 2017-11-25 at 23 09 48](https://user-images.githubusercontent.com/21296738/33234332-0a7d0dba-d236-11e7-8e09-1e12eece4fce.png)

**Comment by sarperhorata** [comment]
Can anyone help, please let me know what is wrong regarding with my message above?
