### ISSUE TITLE
Trading data available for download

### ISSUE THREAD

**Issue by thegamecat** [askmike/gekko#1084]
I've put up a very basic site and will be adding trading data and other bits and pieces for people to download / read etc. 

5 + year btcusd btce data is on there as well as a large set of poloniex data.

If anyone has data they want to share, let me know and I'll add it. 

http://gekkowarez.com/download-category/trading-data/

**Comment by askmike** [comment]
Awesome!

**Comment by CptanPanic** [comment]
Thanks
