### ISSUE TITLE
SQLITE_CORRUPT error 11, on Bash on Windows 10

### ISSUE THREAD

**Issue by OleAd** [askmike/gekko#1086]
* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** 
Normal operation

* **Expected result**
No database errors

* **Actual result**
When performing various operation I will occasionally run into SQLITE_CORRUPT error.

* **Error message**
{ Error: SQLITE_CORRUPT: database disk image is malformed
    at Error (native) errno: 11, code: 'SQLITE_CORRUPT' }
  xxx POST /api/backtest 500 17s -

  Error: non-error thrown: Child process has died.
      at Object.onerror (/mnt/c/Users/oHap1/Desktop/BOT/gekko/node_modules/koa/lib/context.js:105:40)
      at process._tickCallback (internal/process/next_tick.js:109:7)

* **Other information** 

I saw a similar issue marked as close, which suggested deleting the database and starting over. I'm going to try the same, unless you would like a copy of the database for review.

**Comment by askmike** [comment]
Just a quick question: where you running a lot of Gekkos at the same time? Or did anything else strange happen?

@thegamecat have you ever had this problem before?

**Comment by OleAd** [comment]
No, just importing some data from poloniex. On a related note, I just set up a paper trader Gekko, which gives me this error:

Gekko 3651863886035835 started
  --> POST /api/startGekko 200 77ms 438b
  <-- POST /api/getCandles
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: SQLITE_IOERR: disk I/O error
    at Error (native)
RECEIVED ERROR IN GEKKO 27610659009441
Child process has died.


Will try deleting the database later/tomorrow, and see if that helps. Thanks for the quick reply!

**Comment by thegamecat** [comment]
Yep, it's almost certainly the pragma.
Instructions to fix are here: http://gekkowarez.com/running-gekko-sqlite-in-windows-10-bash/

**Comment by OleAd** [comment]
Forgot to say, I already set it to "DEL" as per the instructions.

**Comment by OleAd** [comment]
Tried on a new system, different computer, still Win 10 with Bash. Followed the instruction re: DEL. Still get similar errors.

{ Error: SQLITE_CORRUPT: database disk image is malformed
    at Error (native) errno: 11, code: 'SQLITE_CORRUPT' }
  xxx POST /api/backtest 500 6,047ms -

  Error: non-error thrown: Child process has died.
      at Object.onerror (/home/MYNAME/gekko/node_modules/koa/lib/context.js:105:40)
      at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by thegamecat** [comment]
Hrm, try and download one of these dbs and see what happens:
http://gekkowarez.com/download-category/trading-data/

Which version of bash are you running, 14 or 16?

**Comment by OleAd** [comment]
Running 16. Downloaded the poloniex one, but having some troubles getting gekko to recognize there's data in the history folder (copied it in using bash). Will test again bit later next week. Thanks for your replies!

**Comment by ftamminga** [comment]
I had this exact same problem. I even tried the developer branch, but it did not help. And yes, I also changed the pragma to "DEL".
After some searching I found that using the value "TRUNCATE" could work better.
So, I changed the value, and it seems to work. 
Can anyone confirm that this is the proper solution?

**Comment by Dennuzzz** [comment]
Thanks @ftamminga , that fixed my problem. Exactly the same error.

**Comment by askmike** [comment]
great stuff, maybe we should add this to the docs?

**Comment by YuriyTigiev** [comment]
@ftamminga  
Could you share how did you change pragma?

**Comment by ftamminga** [comment]
> Instructions to fix are here: http://gekkowarez.com/running-gekko-sqlite-in-windows-10-bash/
