### ISSUE TITLE
Add support for yunbi.com

### ISSUE THREAD

**Issue by j0x3n** [askmike/gekko#1087]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[* ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)

* **Expected result** (what you hoped would happen)
hope support yunbi api
here's the api url: https://yunbi.zendesk.com/hc/zh-cn/articles/115005892327-API-%E5%BC%80%E5%8F%91%E8%80%85%E6%8E%A5%E5%8F%A3

* **Actual result** (unexpected outcome)
does't support

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
Hey! Unfortunately I don't have time to add new exchanges at the moment. But anyone can, the documentation you need is here:

https://gekko.wizb.it/docs/extending/add_an_exchange.html

If you (or someone else) can add it and create a pull request I will merge it :)
