### ISSUE TITLE
[Feature Request] buystoplimit and sellstoplimit percent

### ISSUE THREAD

**Issue by jaguar666** [askmike/gekko#1093]
I might say that this buystop and sellstop limit is very useful to implement. 

For example:
buystoplimit: 0.5%
sellstoplimit: 0.5%
>> gekko will stop buying if the current bid price exceeded the 0.5% from the original price that gekko wanted to buy.
>> gekko will stop selling if the current ask price is lower of 0.5% from the original price.

**Comment by askmike** [comment]
This is something you can implement in your own strategies! Read more information on how to create strategies here: https://gekko.wizb.it/docs/strategies/creating_a_strategy.html

**Comment by pushkarnagle** [comment]
@jaguar666 I have created a strategy like this. Try it at (https://github.com/pushkarnagle/gekko-buyatsellat)

**Comment by epepper** [comment]
I posted on the r/gekko about this, I wasn't able to figure out how to do it, my JavaScript skills are weak  

https://redd.it/6z5s2d

If someone could help that'd be great.

**Comment by pushkarnagle** [comment]
@epepper Can you please elaborate in detail what you want to do in your strategy which you have posted on Reddit?

**Comment by epepper** [comment]
@pushkarnagle First off, thank you for your help with everything. Second I was hoping to finish it up, so I could add it as a custom strat. 

Maybe I am making a noob mistake, but when I load it into custom, the my_custom_setting = 10 is still there (yes I know this isn't handled by the custom strat file), but it doesn't work in paper trader.

**Comment by thegamecat** [comment]
This is the guide to making a stop loss in your strat where imo it belongs:

http://gekkowarez.com/how-to-put-a-stop-loss-into-your-gekko-strategy/

**Comment by jaguar666** [comment]
@pushkarnagle i will try your strategy. thank you

**Comment by askmike** [comment]
great stuff! Feel free to add this to the docs in a PR!
