### ISSUE TITLE
buys and sells not showing up in the UI when using Poloniex 

### ISSUE THREAD

**Issue by CloudStrife28492** [askmike/gekko#1097]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
I've started a live trading bot after backtesting my strategy under different szenarios. In the chart, it always loocked like the bot was buying and selling "all in" with quite some profit :)

* **Expected result** (what you hoped would happen)
I thought, that when I start this live bot, it will also trade with everything on the wallet. I used the RSI strategy by the way.

* **Actual result** (unexpected outcome)
The Bot actually bought and sold twice. And even the buy-trades are not shown in the chart but on poloniex.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
![trading_bot](https://user-images.githubusercontent.com/7949469/30197751-0cb9b5e2-946a-11e7-80f0-bdbfe453f840.jpeg)
![actual_trading](https://user-images.githubusercontent.com/7949469/30197752-102ff268-946a-11e7-9cd6-9a354a627519.jpeg)

**Comment by greenbigfrog** [comment]
Maybe add a extra column with `actual price/Share`, like Bittrex has it.
