### ISSUE TITLE
Suggestion - multiple instances, one database

### ISSUE THREAD

**Issue by djmuk** [askmike/gekko#110]
As I understand it a gekko instance can only run one trading method.  At present if I wanted to use 2 trading methods I would have to run 2 completely separate instances of gekko each collecting it's own candle data?
Is it feasible/sensible to have the option of pointing a gekko instance at the database/candle files being generated by another? I suppose this is almost like doing a backtest against the database file but not exiting and continuing to monitor for new live data?? Or is there a plan to allow multiple trading methods to run within one instance?

**Comment by askmike** [comment]
Currently you just run multiple Gekko instances. Open for pulls!
