### ISSUE TITLE
[Bugfix] talib macdfix option does not match the requires one

### ISSUE THREAD

**Issue by oktapodia** [askmike/gekko#1105]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Try to use talib macdfix

* **Expected result** (what you hoped would happen)
working

* **Actual result** (unexpected outcome)
impossible to pass the good parameter to the talib strategy

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by oktapodia** [comment]
https://github.com/askmike/gekko/pull/1104

**Comment by askmike** [comment]
fixed!
