### ISSUE TITLE
Poloniex importing not working

### ISSUE THREAD

**Issue by roneetshaw** [askmike/gekko#1106]
I'm relatively new to gekko trading bot, I just installed the bot yesterday after reading the documentation and seeing the installation video. I followed the exact step to get three month historical data from Poloniex so that I backtest the strategies. 
When I start the import from Poloniex, I instantly get import done as soon as I start the import and I don't get any data, I know it's not able to pull any result from Poloniex. However, when I repeat the same steps with Gdax, it works fine.
I also see the db files in `\history\` where poloniex_0.1.db does get created but it's only of 4KB. I'm using the stable branch of gekko. 
Do I have to config anything to get Poloniex start importing data?

**Comment by oktapodia** [comment]
Which pair did you want to import?

**Comment by roneetshaw** [comment]
USDT/BTC (FROM : 2017-06-10 10:59 TO: 2017-09-10 10:59)

**Comment by roneetshaw** [comment]
![image](https://user-images.githubusercontent.com/19503905/30248443-9cc35882-9645-11e7-86c6-705032c02b10.png)
This I get everytime. Poloneix one doesn't complete ever

**Comment by matthew-restaff** [comment]
similar issue here. import from poloniex does not work. bittrex is not available as an option.

**Comment by logicappsource** [comment]
yes same issue here

**Comment by askmike** [comment]
For anyone who has this issue: I am pretty sure poloniex has banned your IP address. See #1055 for defails. If that is not the case please reopen and post the output of following the instructions in that issue.

**Comment by roneetshaw** [comment]
https://pastebin.com/cppNVFeK is broken

**Comment by askmike** [comment]
What happens when you go to this URL? https://poloniex.com/public?command=returnTradeHistory&currencyPair=BTC_NXT&start=1410158341&end=1410499372 (Do you see a captcha or not?)

**Comment by roneetshaw** [comment]
Yes,I get a "I'm not a robot window".
Trying to fix. Thanks for the help!

**Comment by battlezone100** [comment]
I'm having the same issue where I can't reliably import data, regardless of currency pair.
I just get the message "Import done" yet it only imported like 5 minutes to a week or anything in between. It's a nightmare to get a few months of data imported.

I do not see any captcha when visiting the above page.

**Comment by ghost** [comment]
Im having this issue on binance
