### ISSUE TITLE
Quick guide for making a Stop Loss in your Strategy

### ISSUE THREAD

**Issue by thegamecat** [askmike/gekko#1107]
I've written up a quick guide on how to add a stop loss to your strategy:
http://gekkowarez.com/how-to-put-a-stop-loss-into-your-gekko-strategy/

**Comment by imkane** [comment]
You rock! And you aint no "noob" ;)

**Comment by epepper** [comment]
This is pretty cool, can this be used by it's self?

**Comment by thegamecat** [comment]
You can add it to any strategy you like.

**Comment by jaguar666** [comment]
if(logic that determines a sell ||  -- is this a code or we need to replace it with something? can you please revise your stop loss script that is applicable to current RSI strategy? Thank you

**Comment by thegamecat** [comment]
yes that's your sell logic :)

**Comment by score1more4me** [comment]
Stop loss always seems like a good idea....  But wouldn't a well-defined strategy automatically trigger a sell based on market conditions?

Also, would this work only on candles?  So if you use a 15 minute or 60 minute candle, would it trigger when upon candle formation?  What about candle persistence?

I'd be interested to see a use case and how it works with/without the stop loss trigger.  It doesn't have to be your strategy, but perhaps one that wins big, but also loses big.

**Comment by askmike** [comment]
> Also, would this work only on candles? So if you use a 15 minute or 60 minute candle, would it trigger when upon candle formation? What about candle persistence?

That is correct, so it doesn't trigger near as fast as a stoploss. In the future I will add different signals your strat can signal (like: advice buy: TP @ 4100 SL @ 4050).

**Comment by gianni76** [comment]
While I appreciate the basic ideas of the thegamecat logic, I am finding a bit complicated to implement it reliably on many strategies. Also I find a bit daunting having to change the strategy (and each single strategy differently) based on what is effectively a money management tool. 
So if I have 20 strategies under test, I have to rewrite them all in order to have a stop loss...

What I would ideally like is a different and more centralised approach in one of the core functions rather than in each and every one of the strategies. Has anyone given any thought as to what could be changed in order to have a stop loss (and maybe also a trailing stop) reliably working on each strategy and without having to recode and retest each strategy?

**Comment by WildcatKSS** [comment]
I tried to implement the code but i got stuck. Do you have a sample of the code implemented in the basic DEMA strategy?

**Comment by oikonen** [comment]
Is there anyone who knows how to implement this code and could give a sample code?

**Comment by storshun** [comment]
@thegamecat do you still monitor this thread? Unfortunately a lot of us don't have sufficient coding experience to drive this from the code snippet you provided to completion, but would love to take advantage of the guidelines you setup. Can you provide insight? Perhaps a simple example strategy that integrates the code you've written?

**Comment by ghost** [comment]
Hi I have tried to add my sell logic into the place indicated however Im getting Gekko crashing when I try to run the strat.


Im simply trying to implement this stop loss into the boilerplate RSI Strat

.js is not my strong point and Im sure its just a syntax issue, has anyone got a code example with this actually working?

**Comment by gaud13** [comment]
would love to see this in the RSI myself i jst dont know how to plug it in :(

**Comment by askmike** [comment]
Proper stop losses coming soon! See this thread: https://forum.gekko.wizb.it/thread-57314.html

**Comment by askmike** [comment]
Closing this issue, up until this is integrated in Gekko this is better suited on the forum.
