### ISSUE TITLE
Order too small to buy error at Bitfinex

### ISSUE THREAD

**Issue by pushkarnagle** [askmike/gekko#1108]
I was getting 'Order too small to buy at Bitfinex' when I was testing a strategy with 30$ in my account. I got surprised when I was able to execute the order manually at Bitfinex portal.

Then I changed below line in `bitfinex.js` which is sits in `/gekko/exchanges` folder.
`{ pair: ['USD', 'BTC'], minimalOrder: { amount: 0.01, unit: 'asset' } },`

I changed `0.01` to `0.0001` and now I am getting no error. Though minimum order FAQ at Bitfinex says that for BTC, it should be at least 0.01, but I dont think they have restrictions in place for it.

**Comment by askmike** [comment]
Open for a PR for this :)
