### ISSUE TITLE
Coding ...Greater than > last

### ISSUE THREAD

**Issue by godfrey68** [askmike/gekko#1110]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)

* **Expected result** (what you hoped would happen)

* **Actual result** (unexpected outcome)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
How would I code an indicator to show greater than last....? Specifically obv

**Comment by godfrey68** [comment]
Simple code
..Obv greater than Obv 1 tick ago

**Comment by godfrey68** [comment]
Or is anyone available to create one indicator robot for bittrex? For a fee...Contact me directly @ gscollman68@yahoo.com

**Comment by askmike** [comment]
see #844 for a implementation of what you want :)
