### ISSUE TITLE
Kraken buy/sell order problem

### ISSUE THREAD

**Issue by obie73** [askmike/gekko#1111]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)

The problem happens the first time you try to buy / sell.
Every time Gekko tries to launch an order he stays in a loop of errors

Out log:

> 2017-09-10 22:50:58 (DEBUG):	calculated CCI properties for candle:
> 2017-09-10 22:50:58 (DEBUG):		 Price:			 undefined
> 2017-09-10 22:50:58 (DEBUG):		 CCI tp:	 255.98000000
> 2017-09-10 22:50:58 (DEBUG):		 CCI tp/n:	 256.09086997
> 2017-09-10 22:50:58 (DEBUG):		 CCI md:	 2.06157216
> 2017-09-10 22:50:58 (DEBUG):		 CCI:	 -3.59
> 2017-09-10 22:50:58 (DEBUG):	Trend:  nodirection  for  6
> 2017-09-10 22:52:18 (DEBUG):	calculated CCI properties for candle:
> 2017-09-10 22:52:18 (DEBUG):		 Price:			 undefined
> 2017-09-10 22:52:18 (DEBUG):		 CCI tp:	 255.80000000
> 2017-09-10 22:52:18 (DEBUG):		 CCI tp/n:	 256.03714521
> 2017-09-10 22:52:18 (DEBUG):		 CCI md:	 2.06653630
> 2017-09-10 22:52:18 (DEBUG):		 CCI:	 -7.65
> 2017-09-10 22:52:18 (DEBUG):	Trend:  nodirection  for  7
> 2017-09-10 22:52:58 (DEBUG):	calculated CCI properties for candle:
> 2017-09-10 22:52:58 (DEBUG):		 Price:			 undefined
> 2017-09-10 22:52:58 (DEBUG):		 CCI tp:	 255.65333333
> 2017-09-10 22:52:58 (DEBUG):		 CCI tp/n:	 255.97975512
> 2017-09-10 22:52:58 (DEBUG):		 CCI md:	 2.07506257
> 2017-09-10 22:52:58 (DEBUG):		 CCI:	 -10.49
> 2017-09-10 22:52:58 (DEBUG):	Trend:  oversold  for  1
> 2017-09-10 22:52:58 (INFO):	Trader Received advice to go long. Buying  ETH
> 2017-09-10 22:53:32 (INFO):	Attempting to BUY 0.046016816581931956 ETH at kraken price: 255.57
> 2017-09-10 22:53:32 (ERROR):	no data
> 2017-09-10 22:53:32 (DEBUG):	kraken returned an error, retrying..
> 2017-09-10 22:53:50 (ERROR):	no data
> 2017-09-10 22:53:50 (DEBUG):	kraken returned an error, retrying..
> 2017-09-10 22:54:03 (ERROR):	no data
> 2017-09-10 22:54:03 (DEBUG):	kraken returned an error, retrying..
> 2017-09-10 22:54:25 (ERROR):	no data
> 2017-09-10 22:54:25 (DEBUG):	kraken returned an error, retrying..
> 2017-09-10 22:54:32 (ERROR):	no data
> 2017-09-10 22:54:32 (DEBUG):	kraken returned an error, retrying..
> 2017-09-10 22:54:53 (ERROR):	no data
> 2017-09-10 22:54:53 (DEBUG):	kraken returned an error, retrying..
> 2017-09-10 22:55:05 (ERROR):	no data
> 2017-09-10 22:55:05 (DEBUG):	kraken returned an error, retrying..
> 2017-09-10 22:55:12 (ERROR):	no data
> 2017-09-10 22:55:12 (DEBUG):	kraken returned an error, retrying..
> 2017-09-10 22:55:18 (ERROR):	no data
> 2017-09-10 22:55:18 (DEBUG):	kraken returned an error, retrying..
> 2017-09-10 22:55:30 (ERROR):	no data
> 2017-09-10 22:55:30 (DEBUG):	kraken returned an error, retrying..
> 2017-09-10 22:55:38 (DEBUG):	calculated CCI properties for candle:
> 2017-09-10 22:55:38 (DEBUG):		 Price:			 undefined
> 2017-09-10 22:55:38 (DEBUG):		 CCI tp:	 255.65666667
> 2017-09-10 22:55:38 (DEBUG):		 CCI tp/n:	 255.92822112
> 2017-09-10 22:55:38 (DEBUG):		 CCI md:	 2.07872535
> 2017-09-10 22:55:38 (DEBUG):		 CCI:	 -8.71
> 2017-09-10 22:55:38 (DEBUG):	Trend:  nodirection  for  0
> 2017-09-10 22:55:38 (DEBUG):	calculated CCI properties for candle:
> 2017-09-10 22:55:38 (DEBUG):		 Price:			 undefined
> 2017-09-10 22:55:38 (DEBUG):		 CCI tp:	 255.70000000
> 2017-09-10 22:55:38 (DEBUG):		 CCI tp/n:	 255.87947921
> 2017-09-10 22:55:38 (DEBUG):		 CCI md:	 2.08030413
> 2017-09-10 22:55:38 (DEBUG):		 CCI:	 -5.75
> 2017-09-10 22:55:38 (DEBUG):	Trend:  nodirection  for  1
> 2017-09-10 22:55:52 (ERROR):	no data
> 2017-09-10 22:55:52 (DEBUG):	kraken returned an error, retrying..
> 2017-09-10 22:55:58 (DEBUG):	calculated CCI properties for candle:
> 2017-09-10 22:55:58 (DEBUG):		 Price:			 undefined
> 2017-09-10 22:55:58 (DEBUG):		 CCI tp:	 255.57000000
> 2017-09-10 22:55:58 (DEBUG):		 CCI tp/n:	 255.82796106
> 2017-09-10 22:55:58 (DEBUG):		 CCI md:	 2.08467193
> 2017-09-10 22:55:58 (DEBUG):		 CCI:	 -8.25
> 2017-09-10 22:55:58 (DEBUG):	Trend:  nodirection  for  2
> 2017-09-10 22:55:59 (ERROR):	no data
> 2017-09-10 22:55:59 (DEBUG):	kraken returned an error, retrying..
> 2017-09-10 22:56:17 (ERROR):	no data
> 2017-09-10 22:56:17 (DEBUG):	kraken returned an error, retrying..
> 2017-09-10 22:56:24 (ERROR):	no data
> 2017-09-10 22:56:24 (DEBUG):	kraken returned an error, retrying..
> 2017-09-10 22:56:30 (ERROR):	no data
> 2017-09-10 22:56:30 (DEBUG):	kraken returned an error, retrying..
> 2017-09-10 22:56:36 (ERROR):	no data
> 2017-09-10 22:56:36 (DEBUG):	kraken returned an error, retrying..
> 2017-09-10 22:56:53 (ERROR):	no data
> 2017-09-10 22:56:53 (DEBUG):	kraken returned an error, retrying..
> 2017-09-10 22:57:00 (ERROR):	no data

* **Expected result** (what you hoped would happen)

Kraken should be able to buy/sell orders

* **Actual result** (unexpected outcome)

Gekko is not able to open an order in Kraken

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

I have updated the kraken.js file from the exchange directory from the develop branch, but it does not solve anything.

Any ideas?

Cheers!

**Comment by zeroX-tj** [comment]
Try to place an order at kraken these days, impossible.... Their api is down like 99.999% of the time (it feels like that, no real numbers :p) Maybe you can open a support ticket on their side?

**Comment by icb088** [comment]
Hi,
First of all I have to say that this is the only trading robot that is working for me - great work!!!
I have exactly the same issue and do not guess that this is an API issue. As well, I installed the develop branch and even increased the timeout from 5000 to 20000 (as my PHP script - see below - took more that the original 5 sec. to place an order).
At the same time the Kraken trading platform is working as expected using the same API (?).
For further investigation I developed a small PHP script that just places a market order ('pair' => 'XXBTZEUR', 'type' => 'buy', 'ordertype' => 'market', 'volume' => '0.01') and this worked like a charm.
As I want to occupy oneself with defining some good strategies I kindly ask you to take a look at this issue and keep me informed about the reason and prior how to solve it.
Many thanks for you support and best regards!

**Comment by ftamminga** [comment]
Same here. 

A piece of my tradebot.log:

2017-09-15 18:58:35 (DEBUG):	calculated DEMA properties for candle:
2017-09-15 18:58:35 (DEBUG):		 long ema: 40.62401239
2017-09-15 18:58:35 (DEBUG):		 short ema: 40.75079582
2017-09-15 18:58:35 (DEBUG):		 diff: 0.31160
2017-09-15 18:58:35 (DEBUG):		 DEMA age: 47 candles
2017-09-15 18:58:35 (DEBUG):	we are currently in uptrend @ 42.28000000 (0.31160)
2017-09-15 18:58:35 (INFO):	Trader Received advice to go long. Buying  LTC
2017-09-15 18:58:38 (INFO):	Attempting to BUY 1.8687638072855466 LTC at kraken price: 42.51
2017-09-15 18:58:38 (ERROR):	no data
2017-09-15 18:58:38 (DEBUG):	kraken returned an error, retrying..
2017-09-15 18:58:44 (ERROR):	no data
2017-09-15 18:58:44 (DEBUG):	kraken returned an error, retrying..
2017-09-15 18:58:50 (ERROR):	no data
2017-09-15 18:58:50 (DEBUG):	kraken returned an error, retrying..
2017-09-15 18:58:56 (ERROR):	no data
2017-09-15 18:58:56 (DEBUG):	kraken returned an error, retrying..
2017-09-15 18:59:03 (ERROR):	no data
2017-09-15 18:59:03 (DEBUG):	kraken returned an error, retrying..
2017-09-15 18:59:10 (ERROR):	no data
2017-09-15 18:59:10 (DEBUG):	kraken returned an error, retrying..
2017-09-15 18:59:16 (ERROR):	no data
2017-09-15 18:59:16 (DEBUG):	kraken returned an error, retrying..
2017-09-15 18:59:22 (ERROR):	no data
2017-09-15 18:59:22 (DEBUG):	kraken returned an error, retrying..
2017-09-15 18:59:28 (ERROR):	no data
2017-09-15 18:59:28 (DEBUG):	kraken returned an error, retrying..
2017-09-15 18:59:34 (ERROR):	no data
2017-09-15 18:59:34 (DEBUG):	kraken returned an error, retrying..
2017-09-15 18:59:41 (ERROR):	no data 
...

**Comment by askmike** [comment]
@ftamminga What market was this? Will start a trader at kraken to try and debug on my end.

**Comment by ftamminga** [comment]
EUR/LTC

**Comment by icb088** [comment]
In my case it was EUR/BTC
Pls find attached my logfile - maybe it can help to verify this issue...

[2017-09-14-08-22-UTC-tradebot.zip](https://github.com/askmike/gekko/files/1308895/2017-09-14-08-22-UTC-tradebot.zip)

**Comment by asociadoC** [comment]
Any update here ? Thought it was insufficient permissions or so., but I checked everything, its just not working. How can I increase logging or so to see whats happening ? 

2017-09-20 17:28:20 (DEBUG):    In uptrend since 3 candle(s)

2017-09-20 17:28:20 (INFO):     We have new trading advice!
2017-09-20 17:28:20 (INFO):              Position: long
2017-09-20 17:28:20 (INFO):              Market price: 81.88
2017-09-20 17:28:20 (INFO):              Based on market time: 2017-09-20 17:27:00

2017-09-20 17:28:20 (INFO):     Trader Received advice to go long. Buying  XMR
2017-09-20 17:28:20 (INFO):     Slack Message Sent
2017-09-20 17:28:21 (INFO):     Attempting to BUY 7.947181807066878 XMR at kraken price: 81.5
2017-09-20 17:28:21 (ERROR):    no data
2017-09-20 17:28:21 (DEBUG):    kraken returned an error, retrying..
2017-09-20 17:28:27 (ERROR):    no data
2017-09-20 17:28:27 (DEBUG):    kraken returned an error, retrying..
2017-09-20 17:28:33 (ERROR):    no data
2017-09-20 17:28:33 (DEBUG):    kraken returned an error, retrying..

A tradebot which cannot trade is less of use ..

**Comment by xerix32** [comment]
News? It's really important BUG.........

As @asociadoC said: > A tradebot which cannot trade is less of use ..

**Comment by askmike** [comment]
> A tradebot which cannot trade is less of use ..

Gekko is a lot more than a tradebot, and it supports a whole lot more exchanges than Kraken. That said, I'd love to see this fixed.

**Comment by ebrulato** [comment]
Hi,

On my system, the "no data" error message came from the method
Trader.prototype.getPortfolio (kraken.js)

This method is called in the function Manager.prototype.trade (PortFolioManager.js) :

...
  async.series([
    this.setTicker,
    this.setPortfolio,
    this.setFee
  ], _.bind(act, this));
...

**Comment by ebrulato** [comment]
I have deactivated this call and I had a new error
"unable to get ticker {}" which came from setTicker
I will try to investigate more... but I'm a new user... I don't know this code :)

**Comment by ebrulato** [comment]
It is strange, because these calls work fine during the initialiation phase of the PortFolioManager.

**Comment by ebrulato** [comment]
I removed the 2 call and fix a little issue with the precision.
then I was able to create BUY or SELL order.
As I changed the portfoliomanager I can't submit this fix.
I will purpose a fix for the precision.

**Comment by ebrulato** [comment]
I have restored the setTicker call and now it works fine.... very strange...
but more important, I think I have found a strange bug. The portFolioManager uses the ticker.ask attribute for selling, instead of the ticker.bid value. I'm testing this change.

**Comment by ebrulato** [comment]
In my opinion, the main solution is to reduce the the refresh rate.
If you use the command line, then you can fix it by yourself here in the configuration :

  // You can set your own tickrate (refresh rate).
  // If you don't set it, the defaults are 2 sec for
  // okcoin and 20 sec for all other exchanges.
  tickrate: 20

I understand that the UI interface uses 2s by default.
that is the main issue I think. Kraken generates different kind of errors instead of 'API Call Rate Limit' : 
https://www.kraken.com/help/api#api-call-rate-limit

Note: kraken user should indicates some different delay based on their level. but I try to set some compliant value with the lowest one.

But there is others issues and improvement:
- precision (fix on kraken.js/roundAmount)
- precision of the price (fix)
- a longest delay for retry to avoid rate limit issues.
- use bid when selling
- 'no data' error message improvement

I'm trying to send a pull request :)

**Comment by ebrulato** [comment]
Hi,

I've submitted this pull request : https://github.com/askmike/gekko/pull/1192
Note I've seen that a change have already be done on the portfoliomanager for bid and ask. I'm testing this version.

regards,

**Comment by metodi-yanev** [comment]
After a month this issue is still present. I've tried the fixes that @ebrulato suggested, but got the same "no data" - "error" loop. Please take a look at this. Thanks!

**Comment by sealightPT** [comment]
Still having the issue on "stable" branch

2017-10-15 09:39:11 (INFO):     Trader Received advice to go long. Buying  ETH
2017-10-15 09:39:13 (ERROR):    Kraken did not return portfolio for ETH, assuming 0.
2017-10-15 09:39:13 (INFO):     Attempting to BUY xxxxx ETH at kraken price: 275.83000
2017-10-15 09:39:13 (ERROR):    no data
2017-10-15 09:39:13 (DEBUG):    kraken returned an error, retrying..
2017-10-15 09:39:20 (ERROR):    Kraken did not return portfolio for ETH, assuming 0.
2017-10-15 09:39:20 (ERROR):    no data
2017-10-15 09:39:20 (DEBUG):    kraken returned an error, retrying..
2017-10-15 09:39:27 (ERROR):    Kraken did not return portfolio for ETH, assuming 0.
2017-10-15 09:39:27 (ERROR):    no data
2017-10-15 09:39:27 (DEBUG):    kraken returned an error, retrying..

While this isn't fixed the bot is useless for those which trade with Kraken :(

**Comment by VinceBT** [comment]
Keeping this alive because I get ```unable to get ticker {}``` too

**Comment by greenbigfrog** [comment]
Can anyone of you confirm that this has been fixed?

**Comment by Moun1r1** [comment]
Nop its not got the same issue right here :)

**Comment by VinceBT** [comment]
It's fixed now
