### ISSUE TITLE
MACD plugin not doing it right

### ISSUE THREAD

**Issue by raffus** [askmike/gekko#1113]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x ] bug report

* **Action taken** (what you did)
I've added MACD plugin into my strat using:

short: 12,
long: 26,
signal: 15,
thresholds: {
    down: -0.015,
    up: 0.015,
    persistence: 1
  }

Today the bot bought and when I checked the graph, the averages didn't cross to buy.

* **Expected result** (what you hoped would happen)
Not supposed to buy.

* **Actual result** (unexpected outcome)
Earlier buyer

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

<img width="556" alt="captura de tela 2017-09-11 11 47 49" src="https://user-images.githubusercontent.com/4713763/30281684-72e3833a-96e9-11e7-8fd6-5d40d6d1ddf7.png">

**Comment by askmike** [comment]
Note that Gekko doesn't calculate candles based on new hours (1 hour candle is calculated at the time you start it). Can you post all logs so we can investigate?

**Comment by raffus** [comment]
Sure!! I had that doubt but now you've cleared it out.
Thanks as usual.

**Comment by askmike** [comment]
Ah cool! If you spot something strange feel free to ask :)
