### ISSUE TITLE
[REQUEST] Additional Function of portfolioManager.js

### ISSUE THREAD

**Issue by jaguar666** [askmike/gekko#1116]
Gekko default function on placing an order is that it will follow the current price in either bid or ask price and gekko will stop re-adjusting the price until the transaction is completed.

Based on my observation nowadays, there are some bogus seller/buyer (maybe it's a bot also did this) that placing an oder with a very small (minimum) amount and has a big price difference on the 2nd highest bid or lowest ask.

My concern is, how to avoid this thing that gekko will not place an order based on the order with very small amount which i consider as a bogus order (almost same price on both ask and bid). In this case I want gekko will place an order based on the 2nd lowest/highest order with normal amount of asset/currency. In short gekko will not follow the price on order with minimum amount.

This is always happened on a slow moving pairs.

Anyone has this function please share your code or email me at k3jaguar66@gmail.com

Thank you very much.

**Comment by askmike** [comment]
You bring up a good point, which is that the execution strategy of Gekko is very basic and limited.

> how to avoid this thing that gekko will not place an order based on the order with very small amount which i consider as a bogus order (almost same price on both ask and bid).

This is very hard, because it means making assumptions on which orders are bogus and which ones are not. Which is hard to quantify (since it depends on how much liquidity & volume a market has). Do you have an idea how you would separate "bogus" orders from real orders?

**Comment by Guceri** [comment]
One Idea is to use a min aggregate quantity filter. so for example, all orders will be placed at the bid/ask that provide X amount of liquidity. So if you set a filter to a minimum size of 25 contracts, it will work its way up the orderbook and place your order where a min. of 25 contracts would have to trade to get to that price.

On a side note, or similar to this in some ways, is there a way to specify a limit price that stays in the market and refreshes on candle refresh (if the order does not fill).   so if I want to place a limit order at a price of (Moving Average + X ), that this limit price will cancel and refresh every bar if the order does not fill (and the logic is still true for the trade).
