### ISSUE TITLE
Bug in StockRSI

### ISSUE THREAD

**Issue by pprados** [askmike/gekko#1117]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
this.requiredHistory = config.tradingAdvisor.historySize; // line 28

Fix : this.requiredHistory = this.tradingAdvisor.historySize; // line 28

* **Expected result** (what you hoped would happen)
config not found.

* **Actual result** (unexpected outcome)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
Revealed by strategies unit test.

**Comment by askmike** [comment]
Thanks, fixed in develop!
