### ISSUE TITLE
Error after Windows 10 Installation "Error: Cannot find module 'moment'"

### ISSUE THREAD

**Issue by yehdawg** [askmike/gekko#1119]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
I'm trying to install Gekko using the windows 10 instructions.

* **Expected result** (what you hoped would happen)
I followed the steps and hoped that it would work at the end.

* **Actual result** (unexpected outcome)
I get an error message when running node gekko --ui that reads

module.js:471
     throw err;
     ^

Error: Cannot find module 'moment'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/yehdawg/gekko/core/util.js:1:76)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

Any Idea of what might have went wrong?

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
You need to run `npm install` before you start Gekko! See the installation docs for details:

https://gekko.wizb.it/docs/installation/installing_gekko.html

If that failed, please post the error :)

**Comment by yehdawg** [comment]
hey so it gives me this message when I run the installer

npm WARN enoent ENOENT: no such file or directory, open '/home/yehdawg/gekko/node_modules/bl/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/yehdawg/gekko/node_modules/cheerio/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/yehdawg/gekko/node_modules/htmlparser2/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/yehdawg/gekko/node_modules/jsprim/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/yehdawg/gekko/node_modules/nock/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/yehdawg/gekko/node_modules/resolve-path/package.json'
npm ERR! Linux 4.4.0-43-Microsoft
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--only=production"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! path /home/yehdawg/gekko/node_modules/.staging/har-validator-f90112f1
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/home/yehdawg/gekko/node_modules/.staging/har-validator-f90112f1' -> '/home/yehdawg/gekko/node_modules/sqlite3/node_modules/har-validator'
npm ERR! enoent ENOENT: no such file or directory, rename '/home/yehdawg/gekko/node_modules/.staging/har-validator-f90112f1' -> '/home/yehdawg/gekko/node_modules/sqlite3/node_modules/har-validator'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /home/yehdawg/gekko/npm-debug.log

**Comment by askmike** [comment]
Very strange, can you delete the folder `/home/yehdawg/gekko/node_modules` and try to install again?
