### ISSUE TITLE
bash error on windows

### ISSUE THREAD

**Issue by orkobar** [askmike/gekko#1121]
I had a problem like 

install bash on windows 10 64bit ok
install nodejs ok
install gekko ok
install dependencies ok
install git ok
edit handle.js ok
remove talip ok
install talip 1.0.2 ok
starting gekko (seems ok but give some error and nothing happened)(cannot open localhost:3000)

    ______   ________  __    __  __    __   ______
   /      \ /        |/  |  /  |/  |  /  | /      \
  /$$$$$$  |$$$$$$$$/ $$ | /$$/ $$ | /$$/ /$$$$$$  |
  $$ | _$$/ $$ |__    $$ |/$$/  $$ |/$$/  $$ |  $$ |
  $$ |/    |$$    |   $$  $$<   $$  $$<   $$ |  $$ |
  $$ |$$$$ |$$$$$/    $$$$$  \  $$$$$  \  $$ |  $$ |
  $$ \__$$ |$$ |_____ $$ |$$  \ $$ |$$  \ $$ \__$$ |
  $$    $$/ $$       |$$ | $$  |$$ | $$  |$$    $$/
   $$$$$$/  $$$$$$$$/ $$/   $$/ $$/   $$/  $$$$$$/

        Gekko v0.5.6
        I'm gonna make you rich, Bud Fox.

TAlib is enabled
Serving Gekko UI on http://localhost:3000/

(node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Exited with code 3

Maybe i am missing something, also i am not sure how to open localhost:3000 manually

thanks for help

regards

orko

**Comment by askmike** [comment]
Open a browser and browse to the address http://localhost:3000 (or just click this link).
