### ISSUE TITLE
Show --config started gekko in UI

### ISSUE THREAD

**Issue by krieghof** [askmike/gekko#1122]
* **I'm submitting a ...**
[ ] bug report
[ x] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
1. node gekko.js --ui
2. node gekko.js --config config

* **Expected result** (what you hoped would happen)
See the started gekko in the webinterface under live gekko

* **Actual result** (unexpected outcome)
No gekko in the ui

* **Other information**
UIconfig
// This config is used in both the
// frontend as well as the web server.

// see https://github.com/askmike/gekko/blob/stable/docs/installing_gekko_on_a_server.md

const CONFIG = {
  headless: true,
  api: {
    host: '0.0.0.0',
    port: 3000,
  },
  ui: {
    ssl: true,
    host: 'example.duckdns.org',
    port: 443,
    path: '/'
  },
  adapter: 'sqlite'
}

if(typeof window === 'undefined')
  module.exports = CONFIG;
else
  window.CONFIG = CONFIG;

Maybe I'm doing something wrong.

**Comment by askmike** [comment]
> See the started gekko in the webinterface under live gekko

Where you expecting to see the gekko run under `node gekko.js --config config` to show up in the UI? That's unfortunately not how Gekko works:

- By running `node gekko.js --ui` you start the UI through which you can start running Gekkos (via the webinterface).
- By running `node gekko.js --config config` you run a standalone gekko via the commandline (and you don't use the UI).
