### ISSUE TITLE
Candle Time's

### ISSUE THREAD

**Issue by Guceri** [askmike/gekko#1123]
If I understand it correctly, when you run a gekko, for example on 15 min bars, the 15 minute window references when your gekko starts and not  00,15,30,45 to the hour.  

When running backtests, I assume it DOES use the 00,15,30,45 logic?  or does it use the time at which you backtested (and then go back in time 15 minutes at a time)?

This becomes a standardization problem with research and backtesting, no?

**Comment by askmike** [comment]
> When running backtests, I assume it DOES use the 00,15,30,45 logic? or does it use the time at which you backtested (and then go back in time 15 minutes at a time)?

When you start a backtest Gekko starts it from the beginning of your dataset (=from the first minute Gekko can find data - until the last minute Gekko has data, regardless of the time when you start backtest).

---

If you start a live Gekko it will store and use data from the minute it gets data. This means that if you start a live Gekko now with a strategy the data stored (which can be used for backtesting) is the same data that you will have available later for backtesting. If you import data you have more data available, but in this case you never had a live trader running at time of the historical data you are importing.

**Comment by metodi-yanev** [comment]
Hey, Mike! 

Does this mean that every new live gekko starts to write a new dataset of his own? Does a new live gekko have access to previously stored data from the same exchange? And if you want to get candles 00, 15, 30 (as on an exchange's chart) on the live gekko you have to start it precisely on that minute?

And thank you for the great job. Much appreciated!

Matt

**Comment by askmike** [comment]
> And if you want to get candles 00, 15, 30 (as on an exchange's chart) on the live gekko you have to start it precisely on that minute?

Yes, I would be open to a PR that makes this configurable. But I want the current behaviour to be the default behaviour.

> Does this mean that every new live gekko starts to write a new dataset of his own? Does a new live gekko have access to previously stored data from the same exchange?

These questions depends on how you run the Gekko:

**if you run Gekko via the commandline**

Gekko will try to stitch locally stored data (from an import, or from a previous run of Gekko) from live exchange data. If this works your strategy won't notice a thing but gets data from however long it needs (as specified in `historySize`).

**If you run Gekko via the UI**

When you start a live gekko under the hood we actually start two things: a "market watcher" that will fetch new market data and pump it into the database (to be used by whatever wants it). and a "stratrunner" which simply pulls stuff out of the database and gives it to the strat. Though if you start a new Gekko that already had a market watcher running, that one can be reused.

So to answer your question: If you start a new live Gekko for a market you were not already watching, you currently do not have access to older data. If you start one that already has a watcher the new gekko has access to all data from the other watcher.
