### ISSUE TITLE
websocket communication error / Disconnected

### ISSUE THREAD

**Issue by 1024kilobyte** [askmike/gekko#1138]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**
My setup is:
gekko installed on a vps, nginx, lets encrypt and basic authentication (using the detailed description on the website). The setup was working fine with version 0.5.6, but does not work anymore with 0.5.7.

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
I updated from version 0.5.6 to 0.5.7 (I also tried a clean "install" with 0.5.7 with the same effect).

* **Expected result** (what you hoped would happen)
Gekko should be accessible via the webinterface.

* **Actual result** (unexpected outcome)
Gekko shows the "Disconnected"-message and cannot be used at all (Testet with Chrome and Safari). 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

I get two messages. First on the console on startup via 'node gekko --config config.js --ui':
```
(node:30763) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Exited with code 3
(node:30763) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

And the second in the js console of the browser:
```
WebSocket connection to 'ws://localhost:3000/api/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
OPTIONS http://localhost:3000/api/imports net::ERR_CONNECTION_REFUSED
OPTIONS http://localhost:3000/api/gekkos net::ERR_CONNECTION_REFUSED
OPTIONS http://localhost:3000/api/gekkos net::ERR_CONNECTION_REFUSED
OPTIONS http://localhost:3000/api/apiKeys net::ERR_CONNECTION_REFUSED
OPTIONS http://localhost:3000/api/exchanges net::ERR_CONNECTION_REFUSED
Uncaught TypeError: Cannot read property 'forEach' of undefined
```

and after that a lot more:
```
WebSocket connection to 'ws://localhost:3000/api/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
```

@askmike Did you change something regarding the websocket communication? Maybe something only affecting the hosted / nginx setup?

**Comment by askmike** [comment]
I think both issues can be fixed by properly configuring the UIconfig.js:
the first warning says that Gekko could not open your browser (which is
okay since a VPS does not have one).

The browser errors indicate that your UIconfig is configured so that it
tries to connect to localhost:3000 to access the server (but as you stated
you are running it externally on a VPS).

For both issues: please see the installing Gekko on a server doc page.

**Comment by 1024kilobyte** [comment]
Sorry for that. I saved and restored all settings from 0.5.6 EXCEPT the UIconfig. My bad!
Thanks for the quick reply!
