### ISSUE TITLE
CCI Reference Missing

### ISSUE THREAD

**Issue by Jyck** [askmike/gekko#1139]
https://github.com/askmike/gekko/blob/20599af2bb5e382b70efb9fdd37d53c7cfe32134/strategies/CCI.js#L11

this.requiredHistory = config.tradingAdvisor.historySize;
change to
this.requiredHistory = this.tradingAdvisor.historySize;

**Comment by askmike** [comment]
Nice find! Can you propose a PR for this (towards the develop branch)? Thanks :)

**Comment by krieghof** [comment]
Can we close this now?

**Comment by askmike** [comment]
This is now fixed in develop, but not in stable yet. Once I release a new version this issue will automatically close :)
