### ISSUE TITLE
BTC-E closed

### ISSUE THREAD

**Issue by krieghof** [askmike/gekko#1140]
BTC-E was closed and now it is called WEX.
The API works the same but with a new domain. (https://wex.nz/api)

Info:
The btc-e.js requires the btce npm https://www.npmjs.com/package/btc-e.
But the npm uses the old API.

**Comment by askmike** [comment]
Good point, the easiest would be to copy the `btc-e` package and create a new one (with the new domain) and publish that to NPM. Than we can simply switch the imported module and everything should work again :)

**Comment by krieghof** [comment]
Alright, I'll do this tomorrow. Is there any way to claim an issue?

**Comment by askmike** [comment]
This has since been merged (into develop)!
