### ISSUE TITLE
TypeError when deploying to Heroku

### ISSUE THREAD

**Issue by isbkch** [askmike/gekko#1144]
I'm deploying to Heroku.
My Procfile has : `worker: node gekko --config sample-config.js`

My UIconfig.js : 

```
const CONFIG = {
  headless: true,
  api: {
    host: 'nameOfApp.herokuapp.com',
    port: process.env.PORT || 3000,
  },
  ui: {
    ssl: false,
    host: 'nameOfApp.herokuapp.com',
    port: 3000,
    path: '/'
  },
  adapter: 'sqlite'
}

if(typeof window === 'undefined')
  module.exports = CONFIG;
else
  window.CONFIG = CONFIG;

```

After deployment, logs show that gekko is working correctly: [https://imgur.com/dRCGgJY](https://imgur.com/dRCGgJY)

But trying to access the web version nameOfApp.herokuapp.com gives an error:

`2017-09-21T01:15:28.223869+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/favicon.ico" host=nameOfApp.herokuapp.com request_id=801424d7-5ae5-4b32-83d0-972ad5ba7f00 fwd="173.177.135.4" dyno= connect= service= status=503 bytes= protocol=https`

Anyone is able to run the UI version on Heroku ?

**Comment by score1more4me** [comment]
https://github.com/askmike/gekko/blob/b940767faebb3d3684a3e97edb6e2d74c9cc2652/docs/installation/installing_gekko_on_a_server.md#configuring-gekko-to-run-in-the-cloud

What happens when you set the config to the following..

`const CONFIG = {
  headless: true,
  api: {
    host: '0.0.0.0',
    port: process.env.PORT || 3000,
  },
  ui: {
    ssl: false,
    host: 'nameOfApp.herokuapp.com',
    port: 3000,
    path: '/'
  },
  adapter: 'sqlite'
}

if(typeof window === 'undefined')
  module.exports = CONFIG;
else
  window.CONFIG = CONFIG;`

This obviously opens it up to anyone... but perhaps through the heroku site you could set it so only your computer can access the web server of gekko?

**Comment by askmike** [comment]
@isbkch I probably need to explain this more clearly in the docs but if you run:

> node gekko --config sample-config.js

You are running a standalone commandline instance of Gekko (without a server) - and the UIconfig is ignored. If you want to run the Gekko UI, run it like so: 

    node gekko --ui

(note that you cannot pas a config to the UI).

**Comment by isbkch** [comment]
Alright, I tried `node gekko --ui` and `host: '0.0.0.0',` and at least it doesn't explode now. But I still can't access the app through the browser. 

Logs say:
`2017-09-21T18:58:17.969602+00:00 app[worker.1]: TAlib is disabled
2017-09-21T18:58:18.151740+00:00 app[worker.1]: Serving Gekko UI on http://nameOfApp.herokuapp.com:3000/` but chrome gives an "ERR_CONNECTION_REFUSED" when I go there.

I also tried doing `ssl: true` and using the https url but no luck

**Comment by rluckez** [comment]
@isbkch Any news? I'm facing same issues triyng to run gekko --ui.
In Procfile i'm using web: node gekko --ui.
Did you try that?

**Comment by AurelienMassiot** [comment]
@isbkch @rluckez Did you figure it out ? I am still trying and it doesn't work with the above suggestions.

**Comment by askmike** [comment]
I don't use Heroku but I'm inclined to say this is an issue with configuring their service as to how Gekko will listen for new web connections. If anyone figures it out feel free to post.

**Comment by jeaimetu** [comment]
I successfully launch gekko UI on Heroku. But generated page said "Disconnected". 
I do not know how to check "connectivity".

Heroku assign random port when user request the HTTP connection. So I changed the source slightly as 
follows on server.js.

//server.listen(config.api.port, config.api.host, '::', () => {
server.listen(process.env.PORT, () => {
  const host = `${config.ui.host}:${process.env.PORT}${config.ui.path}`;

When I put "process.env.PORT to UIconfig.js, then Chrome browser console said "parse error". So I changed the source code, itself.

followings are console log from Heroku. Do you have any idea to resolve this issue?

2018-03-05T02:19:24.273100+00:00 app[web.1]: -   $$ \__$$ |$$ |_____ $$ |$$  \ $$ |$$  \ $$ \__$$ |
2018-03-05T02:19:24.273103+00:00 app[web.1]: -    $$$$$$/  $$$$$$$$/ $$/   $$/ $$/   $$/  $$$$$$/
2018-03-05T02:19:24.273104+00:00 app[web.1]: - 
2018-03-05T02:19:24.347515+00:00 app[web.1]: - 	Gekko v0.5.12
2018-03-05T02:19:24.347699+00:00 app[web.1]: - 	I'm gonna make you rich, Bud Fox. 
2018-03-05T02:19:24.347701+00:00 app[web.1]: - 
2018-03-05T02:19:24.347703+00:00 app[web.1]: - 
2018-03-05T02:19:24.716914+00:00 app[web.1]: - Serving Gekko UI on http://murmuring-dawn-73902.herokuapp.com:9921/
2018-03-05T02:19:24.716940+00:00 app[web.1]: - 
2018-03-05T02:19:25.047553+00:00 heroku[web.1]: - State changed from starting to up

**Comment by alvarheras** [comment]
I'm trying to deploy a gekko in heroku, I'm currently encountering several errors. Has anyone managed to configure gekko for heruko? Thanks

**Comment by JohannesFerner** [comment]
As a sidenote, if you're going to use heroku' postgres you will need to adapt the handle.js, scanner.js to conform (a) to use SSL /solved on local (b) to use database name correctly /working on that currently

**Comment by kiskinvlad** [comment]
Still no fix?

**Comment by johnmerced-ks** [comment]
I started looking at this as well. Any updates?

**Comment by iskanderIt** [comment]
I was able to run Gekko on Heroku.
Just followed the @jeaimetu hack + remove port number in UIConfig.js like the following

const CONFIG = {
  headless: true,
  api: {
    host: 'myapp.herokuapp.com',
    port: '',
    timeout: 120000 // 2 minutes
  },
  ui: {
    ssl: true,
    host: 'myapp.herokuapp.com',
    port: '',
    path: '/'
  },
  adapter: 'sqlite'
}

Hope it helps

**Comment by R0r71z** [comment]
I solved it by using @iskanderIt's approach, deleting the `.env` file in the root directory, then building the Vue app again:
`cd web/vue`
`npm run build`
