### ISSUE TITLE
Telegram Bot not working in UI mode

### ISSUE THREAD

**Issue by 1024kilobyte** [askmike/gekko#1146]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[X] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
I configured the telegram bot in the config.js and am using gekko on a vps via the webinterface, starting the process with:
```
node gekko --config config.js --ui
```

* **Expected result** (what you hoped would happen)
Receiving telegram messages on buy and sell signals from papertraders started via the webinterface.

* **Actual result** (unexpected outcome)
No messages are received. It seems the telegram bot is not started in "UI"-Mode.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
There are no error messages on startup or during runtime.

**Comment by askmike** [comment]
Yes: you are currently unable to use any of these plugins inside the UI. If you want to use the plugins you have to run Gekko over the commandline. The reasoning is:

If you want a telegram (slack, irc, etc) bot you most probably want to run it 24/7 and only one bot. Though the UI is meant for quickly starting and stopping gekkos all the time. I want to add func to add plugins to specific Live Gekkos in the UI but this does not have the highest priority (feel free to add it). Closing this as a dup of #1028.
