### ISSUE TITLE
Retry Rate

### ISSUE THREAD

**Issue by infohoard** [askmike/gekko#1147]
Question: Does the buy/sell retry rate occur once a minute?

If yes, it would be great if we could configure the retry rate.
This is because I noticed at times when the market starts moving, the order gets pushed down by other orders very quickly within seconds, and 1 minute retry intervals doesn't seem to cut it. So it can take 5++ retries (meaning 5++ minutes) to successfully fill your order, but by then the price may have already moved significantly.

**Comment by askmike** [comment]
Yes, it's hardcoded for 1 minute now: https://github.com/askmike/gekko/blob/stable/plugins/trader/portfolioManager.js#L266

You are free to add a PR for this, you can make add a parameter (to the trader plugin) that specifies the time in seconds :)

**Comment by jaguar666** [comment]
putting 0.05 timeout will make 3 seconds retry intervals and change the 10seconds delay to 1sec to be more competitive from other bots.

**Comment by jaguar666** [comment]
How to change this into hour instead of minutes? 

     minToMs: function(min) {
       return min * 60* 1000;

Is this correct?

     minToMs: function(min) {
       return min * 1440 * 1000;  //1440=24hours

     setTimeout(this.checkOrder, util.minToMs(120)); //120=2hours

**Comment by askmike** [comment]
> putting 0.05 timeout will make 3 seconds retry intervals and change the 10seconds delay to 1sec to be more competitive from other bots.

Just so you know, you don't need to outbid all other bots in order to have an order executed.

> How to change this into hour instead of minutes?

Note that the function is called `minToMs` which implies to convert X minutes into X milliseconds. If you change that you might change a bunch of other timers within Gekko..

**Comment by Shrike998** [comment]
Is there a way to change the retry rate for unfilled orders? 

I cant work out how to do it..

I would like to only have the bot cancel an order and retry with a different price after 3 minuites rather than 1.. 

could someone point me to where this is coded in the develop branch?

thanks!
