### ISSUE TITLE
Running gekko on Node.js server with pm2 process manager

### ISSUE THREAD

**Issue by villearo** [askmike/gekko#1152]
* **Action taken** (what you did)
Tried to start Gekko with this command
`pm2 start gekko.js --node-args="--ui"`

* **Expected result** (what you hoped would happen)
Gekko process would be running with pm2 and without the need of ssh connection.

* **Actual result** (unexpected outcome)
Gekko did not start and pm2 gives an error
`node: bad option: --ui`

Without pm2 gekko starts normally and the web UI is useable trough nginx reverse proxy setup.

**Comment by askmike** [comment]
You can start it like so with pm2:

    pm2 start gekko -- --ui

**Comment by villearo** [comment]
Thanks! This worked :)
