### ISSUE TITLE
Canceling current order when new opposite trend started

### ISSUE THREAD

**Issue by jaguar666** [askmike/gekko#1156]
basically gekko will cancel the current order when opposite trend started.
in my opinion this method is not applicable to some of the low value coins like SC and DOGE.

i tried disabling this line to make sure that my current order will not be canceled on new trend and setting the timeout to 60mins  
> //return this.cancelLastOrder(() => this.trade(what));
> setTimeout(this.checkOrder, util.minToMs(60));
- it works but after few hours the bot will be crashed due the error when setting the portfolio.
  > Gekko encountered an error and can't continue. 
  > Error:
  > Gekko was unable to set the portfolio
- this is probably by changing 1minute (default) to 60minutes.

How to fix this error that my purpose will still be applied? no canceling order on new trend, it will be canceled only after the setTimeout (30minutes or 60minutes) had finished.

**Comment by askmike** [comment]
> Canceling current order when new opposite trend started

Is this what you want? Why not signal the opposite signal once the trend reverses?

**Comment by navarrojava** [comment]
If I try to sell 1 coin at $ 100.00 and sell only 0.5 per cent, there is no logic that cancels this sale, since it can drop to 99.00
So I paid the fee for two operations, and I try to sell 1 coin at 99.00 for example.

**Comment by sparkes25** [comment]
i need the same fault fixed. 
seems every time people ask about this they are just told its not what they want and are not given an answer. 

for trading coins like DOGE, TEL or other coins that have a very low value per coin then it is common for the price to only flick in a 1 sat spread.  right now DOGE is bouncing between 54 and 55 sat and it has been for the last 2 hours. 

if i buy at 54 and sell at 55 then i can make a profit of around 1.8% before fees. 

but the markets are very slow, today my orders have taken about 2 hours to fill for each buy/sell. 

but if my bot put in an order it takes it down within a few min, so it never has any change to fill. 

it would just be nice to be able to let the bot put in an order and then that order stays on the order book  for a few hours
