### ISSUE TITLE
run gekko with pm2

### ISSUE THREAD

**Issue by isbkch** [askmike/gekko#1157]
I'm doing `$ pm2 start gekko.js --ui` and I'm getting `error: unknown option `--ui'`
Anyone was able to run the UI version with pm2 ? Or any other option to run a gekko instance forever (even when the shell is closed)

I'm able to run it with `$ node gekko --ui > stdout.txt 2> stderr.txt &` but looking to actually make it work with pm2

**Comment by gweedobtc** [comment]
```
$ pm2 start gekko.js -- --ui

**Comment by imkane** [comment]
I like to use:

`pm2 start gekko.js -f --name ui -x -- --ui --config config.js`

The 'name' param allows you to name it in pm2, so you can run other stuff, like the trader:

`pm2 start gekko.js -f --name trade -x -- --config config.js`

And it's easy to view the logs, stop, or delete them
