### ISSUE TITLE
Adding TechanJS dashboard for BackTesting

### ISSUE THREAD

**Issue by laredoza** [askmike/gekko#1159]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[X ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)

* **Expected result** (what you hoped would happen)

* **Actual result** (unexpected outcome)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Hi,

I'd like to add the following chart to gekko for BackTesting:

http://bl.ocks.org/andredumas/edf630690c10b89be390
http://techanjs.org/

![techjs](https://user-images.githubusercontent.com/5489412/30800322-e675cd66-a1df-11e7-9aaf-9fd5b6f423a6.png)

The data required to make the chart work seems to map back to your stored data:

Date,Open,High,Low,Close,Volume

Would this be a worth while exercise? Any thoughts on this?

**Comment by askmike** [comment]
Yes definitely, other people have also replaced the default charts, see here: #793

As for how to go about it, you can simply replace this with your own chart: https://github.com/askmike/gekko/blob/stable/web/vue/src/d3/chart4.js

When you are working on the frontend (the UI) of Gekko, be sure to set up the frontend environment. Instructions can be found here: https://gekko.wizb.it/docs/internals/gekko_ui.html

**Comment by laredoza** [comment]
Thanks

**Comment by bbjay** [comment]
@laredoza I've started an implementation with TechanJS, see over here: #793

**Comment by laredoza** [comment]
@bbjay,  Brilliant thanks I'll check it out
