### ISSUE TITLE
Request: Utilize the github release tag

### ISSUE THREAD

**Issue by CptanPanic** [askmike/gekko#1163]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[x] question about the decisions made in the repository

I know that you do keep track of version by updating the version field in the code, but it would be helpful and more obvious if you also tagged that commit with the version number to make an official github release.  This way it is easier to see if version has changed, and there are tools that will notify you if threre is a new release.

Thanks.

**Comment by askmike** [comment]
Great idea, done now for the fresh release of v0.5.8! You can find it here:

https://github.com/askmike/gekko/releases/tag/v0.5.8

I will have to see if I will add old releases (for the last few months I have been using PRs to bump version with changelogs), but for now I will make a new release for every version bump!
