### ISSUE TITLE
Fetching OHCL for 24 hours api

### ISSUE THREAD

**Issue by streetbits** [askmike/gekko#1165]
Are there any api included that grabs OHCL data for the last 24 hour from different exchanges?

**Comment by askmike** [comment]
What kind of API do you mean? An API exposed by Gekko or?

**Comment by streetbits** [comment]
I mean, implemented by Gekko and can be used inside a custom strategy.

**Comment by streetbits** [comment]
@cmroche Do we have this implemented for Bitfinex?

**Comment by askmike** [comment]
You can never download from within a strategy: a strategy only has access
to candles. You can import via the importer and then run your strategy over
this imported data.

**Comment by streetbits** [comment]
So I can add a side table besides candles for OHCL data and then read from there.
Ok, I'll give it a try
