### ISSUE TITLE
Available tool - data downloader from haxus

### ISSUE THREAD

**Issue by thegamecat** [askmike/gekko#1167]
Haxus wrote a cool shell script and asked that I add it to GekkoWarez so here it is:
http://gekkowarez.com/download/data-downloader-for-gekko/

Should allow you to download large 1m candle datasets for use in Gekko.

**Comment by outpoints** [comment]
`Saved to: C:/Users/USER/AppData/Local/Temp/bitcoin-scraper/data/bitcoin-history.json

Preparing ...

Fixing DB holes,- This could take a long time!

converting Data to sqldump format ...

cat: /tmp/bitcoin-scraper/data/bitcoin-history.tmp2: No such file or directory

Creating Gekko Sqlite3 DB ...

Error: near line 15: near ")": syntax error

... done`

Any fix?

**Comment by greenbigfrog** [comment]
This script isn't related to gekko. Why is it being discussed here?

**Comment by outpoints** [comment]
@greenbigfrog it's meant to allow us to import data from GDAX without waiting for their API since this site logs every transaction already.
I've tried importing the DB but it never works

**Comment by ecomkings** [comment]
@askmike Do you have convertToDB.sh ? Looked everywhere for it, can't seem to find it.

**Comment by greenbigfrog** [comment]
@askmike this can be close

**Comment by LinoxBE** [comment]
You can find convertToDB.sh at https://www.dropbox.com/s/wxa9vx206rp5sli/convertToDB.sh?dl=0#convertToDB.sh
