### ISSUE TITLE
Importer candles interval for backtests

### ISSUE THREAD

**Issue by streetbits** [askmike/gekko#1168]
I'm experimenting with the importer and tried importing some data for a month.
However, I was wondering what's the interval used for the imported data, i.e. per minute,hour or day?
and where's the database file stored?

**Comment by askmike** [comment]
The database files are sqlite files. They are stored in the history folder.

As for the interval, what exchange did you import?

**Comment by streetbits** [comment]
Great, it's Bitfinex, I found it's a per minute data from cmroch commit.
