### ISSUE TITLE
exchange support - adding exchanges

### ISSUE THREAD

**Issue by erice1984** [askmike/gekko#1171]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[x ] feature request
[x ] question about the decisions made in the repository

* **Action taken** (what you did)
Noticed lack of exchange support.

* **Expected result** (what you hoped would happen)
made a suggestion in hopes it would make the devs' lives easier and expand the reach of the bot.

* **Actual result** (unexpected outcome)
nothing yet.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

https://github.com/ccxt-dev/ccxt

**Comment by zartrade** [comment]
Is this suggestion dead ? It seems like a very logical library to use in gekko to have more/better exchange support.

**Comment by askmike** [comment]
It's a very big library with a lot of overhead, Gekko has supported a standard way of communicating with exchanges for a few years now. This is a completely different way, see [here](https://gekko.wizb.it/docs/extending/add_an_exchange.html). I have seen this project before but know nothing about the people behind them, if they stop supporting that library after Gekko relies on it we would have a big problem.

**Comment by zartrade** [comment]
I understand, that said the project looks extremely active with multiple updates a day. I was under the impression that gekko exchange support is limited due to being hard/messy to get extra exchange support added thus figured this library would ease that up.
