### ISSUE TITLE
API documentation?

### ISSUE THREAD

**Issue by micahscopes** [askmike/gekko#1175]
Hey, I noticed that there's supposed to be a REST API, but I can't find documentation anywhere.  What's the status of this?

**Comment by askmike** [comment]
Unfortunately it has been changing a lot. And there are currently no docs available. Apologies! Adding docs and stabilising the API is pretty high on my list..

The only thing I can recommend at this stage is use the UI and inspect network calls..

**Comment by generalectric** [comment]
thegamecats genetic algorithm is a really good example

**Comment by micahscopes** [comment]
@askmike where would I look in the code if I wanted to understand the API?  [here](https://github.com/askmike/gekko/tree/stable/web/routes) ?

**Comment by askmike** [comment]
Yes! Those are all the calls. You can see them implemented (wether you need to POST or GET) here:

https://github.com/askmike/gekko/blob/stable/web/server.js#L45-L64

Note: There is also a websocket API one needs to subscribe for async actions: Starting a live gekko or an import does not return data via the rest API. But will push events over the websocket API. 90% of these events come from live Gekko instances, you can find all these events here: https://github.com/askmike/gekko/blob/stable/core/cp.js
