### ISSUE TITLE
Unable to run live tradebot from UI

### ISSUE THREAD

**Issue by mfaz** [askmike/gekko#1180]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
I try to run livebot from UI but couldn't make it work.
If I use the UI do I need to setup configure.js and etc as mentioned in the command line documentation?

* **Expected result** (what you hoped would happen)
Live tradebot running

* **Actual result** (unexpected outcome)
No trade done. I think the tradebot ran in papertrader mode.
Here are the output when i ran node gekko --ui 

<-- GET /api/gekkos
  --> GET /api/gekkos 200 9ms 2b
  <-- GET /api/exchanges
  --> GET /api/exchanges 200 1,633ms 58.66kb
  <-- GET /api/apiKeys
  --> GET /api/apiKeys 200 1ms 12b
  <-- GET /api/gekkos
  --> GET /api/gekkos 200 0ms 2b
  <-- GET /api/configPart/candleWriter
  --> GET /api/configPart/candleWriter 200 3ms 47b
  <-- GET /api/configPart/performanceAnalyzer
  --> GET /api/configPart/performanceAnalyzer 200 1ms 144b
  <-- GET /api/configPart/paperTrader
  --> GET /api/configPart/paperTrader 200 1ms 132b
  <-- GET /api/strategies
  --> GET /api/strategies 200 3ms 1.49kb
  <-- POST /api/startGekko
Gekko 00249000362622 started
  --> POST /api/startGekko 200 17ms 147b
  <-- POST /api/startGekko
Gekko 236225066374927 started
  --> POST /api/startGekko 200 20ms 442b
  <-- GET /api/imports
  --> GET /api/imports 200 1ms 2b 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by John1231983** [comment]
@mfaz : I also have same problem. I cannot auto trade from UI (`node gekko --ui`. I only can trade from terminal by 
```
node gekko --config config.js
```
Could you trade from UI?

**Comment by mfaz** [comment]
@John1231983 : In my case, it didn't trade because it was waiting for enough data (history) as configured in Strategy to get the advice i.e long or short. 

When running from UI, gekko wouldn't use your local historical data - the one you downloaded for backtest. But in CLI it is configured to do so, CLI it will automatically stitch historical data with exchange data.

So in UI, if your candle size is 1 hour and warmup period 90, the bot will need to run for min 90 hours before it starts trading. 

Yes i am able to trade from UI now but I'm using CLI. With UI you wouldn't be able to use other plugins like send email notification and telegram which I like.

**Comment by John1231983** [comment]
You mean CCI, instead of CLI. I did not find the CLI option. 
This is my setting for CCI . From this log, it can trade now without waiting 90 hours, right?

```

Strat runner
Market
Exchange
bittrex
Currency
BTC
Asset
BCC
Runtime
Watching since
2017-10-13 06:09
Received data until
2017-10-13 06:34
Data spanning
25 minutes
Amount of trades
0
Strategy
Name
CCI
Parameters
{
    "constant": 0.015,
    "history": 90,
    "thresholds": {
        "up": 100,
        "down": -100,
        "persistence": 0
    }
}
Profit report
Waiting for at least one trade..

This strat runner gets data from this market watcher.

Market graph
```

**Comment by John1231983** [comment]
Thanks. it worked now

**Comment by mfaz** [comment]
CLI is Command Line Interface i.e using command from terminal.
Read the #943 for more info

**Comment by mfaz** [comment]
Glad it works for you.
