### ISSUE TITLE
Manipulating imported data from terminal

### ISSUE THREAD

**Issue by n25an74** [askmike/gekko#1181]
I have a quick series of questions...
very new...
I cannot manipulate the imported data when it breaks...4
so I would like to access it from terminal... in ubuntu
How do I access the imported database from imported terminal?
How do I delete imported data in database from terminal?
If this info is already answered... please point me in the right direction...

**Comment by askmike** [comment]
Hey!

Gekko stores all data inside sqlite databases. These are stored on disk in the `/history` folder. Gekko does not offer anyway to access this data directly. I usually use the application sqlitebrowser (see here: http://sqlitebrowser.org/).

Deleting data would be as simple as deleting files inside the history folder, databases, tables or just records (if you want to delete 1 week of data for whatever reason).

As for CLI interfaces, I am not aware of any. But some quick googling brought me to a utility from sqlite: https://sqlite.org/cli.html

---

Documentation on where the data goes is poor. I am very open to the idea of putting some stuff in the documentation :)

**Comment by askmike** [comment]
Additionally: Gekko supports a few different databases (called adapters), if you are more familiar with postgresql or mongodb you can use those as well (documentation on this is also a bit poor).
