### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by Berndinox** [askmike/gekko#1182]
You have to expose the Port in the Dockerfile..
Like: https://github.com/Berndinox/gekko/blob/stable/Dockerfile#L22

BR

**Comment by askmike** [comment]
Strange, docker compose is working fine for me. What does this solve?

**Comment by Berndinox** [comment]
Hej @askmike, on Docker in Swarm Mode it's mostly necessary to expose ports, so to be able to access them within same docker swarm network. It's like you announce this port to be available..

-> Not a bug, more over a simple Feature! :)
BR

**Comment by askmike** [comment]
sounds great, would you mind creating a PR (against the develop branch)?

**Comment by Berndinox** [comment]
Sure i can... sec plz

**Comment by askmike** [comment]
Thanks! I'm closing this since it will be in stable in the next release :) You can use the develop branch for now ;)
