### ISSUE TITLE
[question] Docker Compose & Docker in generel

### ISSUE THREAD

**Issue by Berndinox** [askmike/gekko#1184]
Hy, me again

related on running Gekko on Docker there are some missunderstandings, aswell as the Docu could need a little Update.

Something i stumbled over the first 30 minutes lookin at it:

 - In the Compose File there is used: `build: ./` - This is not supported anymore with Compose V3, Images have to be prebuilt. `restart` has to be specified under "deploy" Tag.
- When using a SSL Terminating Proxy (Traefik) - reconnectiong--.....js seems to got some strange problems with that

If you want me to, i could a little Update related to Docker.
Goal: Everybody should be able to fire up Gekko+SSL-Rev-Proxy with a one-liner within 1 minute..

.... may my English need some corrections.. :)

**Comment by askmike** [comment]
ping @cassvail, he added this functionality in #947.

Note sure what you mean with:

> When using a SSL Terminating Proxy (Traefik) - reconnectiong--.....js seems to got some strange problems with that

What is wrong with the current docker?

**Comment by Berndinox** [comment]
try `docker stack deploy -c docker-compose.yml gekko` will throw some errors cause as you can see above eg. build is not supported with v3

**Comment by cassvail** [comment]
Hi @Berndinox if you want to deploy on a swarm/stack service, yes! the configuration needs an update... I think you can feel free to move the needed configs under deploy
I only used the config on local servers, so I didn't test cloud configs... if also the build tag is not allowed, probably a separated bash script for building could be created and separated from the docker-compose (I still see the build config in the v3 docs though https://docs.docker.com/compose/compose-file/)
At this point the image will still be built locally, if needed publishing on docker hub would be also a possibility I guess
Hope this helps
