### ISSUE TITLE
[Request] Adding vipbitcoin exchange

### ISSUE THREAD

**Issue by bitkominer** [askmike/gekko#1186]
Hi guys,

Can anyone help to add [vipbitcoin ](https://vip.bitcoin.co.id) exchange? It's an Indonesian-based crypto exchange and provides 0% fee for market maker. _(Should be interesting for those who like to set up frequent trades in their strategies)._

Here's the [APIdocumentation](https://vip.bitcoin.co.id/downloads/BITCOINCOID-API-DOCUMENTATION.pdf) provided by the exchange.

Really appreciate if it could be done shortly. Thanks!

**Comment by danKHUU** [comment]
Waiting for vipbitcoin to get back to me on the test account.

**Comment by bitkominer** [comment]
Great! Hopefully you can get it soon.
Otherwise, you might register a regular trade account. As far as I know, the registration only use phone verification (sms) unless we want to connect the account into our local Bank account. First time I registered, I was using non-Indonesian phone number and it was enough to register an account.

Thanks for your effort so far @danKHUU.

**Comment by danKHUU** [comment]
O., I registered for an account. 

Working on it, should be ready for testing in couple of days. 

I will let you know soon.

**Comment by bitkominer** [comment]
Waiting for good news from @danKHUU . Have you been able to start testing?

**Comment by danKHUU** [comment]
Hi,

Yes i am running live bot testing now. wont be too long...

**Comment by bitkominer** [comment]
Good...
Happily waiting for it.

**Comment by danKHUU** [comment]
Hey,

Sorry for taking a bit, have been busy with works. I am about to put in a pull request.

**Comment by bitkominer** [comment]
Wow... great news then. :)

**Comment by askmike** [comment]
You can try this out by downloading the develop branch of gekko here: https://github.com/askmike/gekko/tree/develop

It will be part of the next stable release. As such I am closing this issue :)
