### ISSUE TITLE
After last release (5.8) Kraken live data watcher / Tradebot doesn't work anymore

### ISSUE THREAD

**Issue by xerix32** [askmike/gekko#1188]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Try to start a kraken "Live market watcher"/traderbot.

* **Expected result** (what you hoped would happen)
Live kraken watcher collect last trades and Tradebot works correctly

* **Actual result** (unexpected outcome)
Live watcher retrieve bad data from not correct date (1970), and after initial import of 21 hours in the starting of 2017, freeze.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by xerix32** [comment]
I noticed now that there is a solution in current "develop" branch.

Sorry for the duplication...
If anyone have hurry as me :) , the  solution is changing in kraken.js, method "getTrades":

[117] var startTs = since ? moment(since).valueOf() : null;

and

[150] if(since) {

**Comment by askmike** [comment]
that has since been released (v0.5.9)!
