### ISSUE TITLE
StochRSI on 0.5.8 not working propertly for backtest (maybe also for real trades)

### ISSUE THREAD

**Issue by hmavrodiev** [askmike/gekko#1190]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)

* **Expected result** (what you hoped would happen)

* **Actual result** (unexpected outcome)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by generalectric** [comment]
Stochrsi and rsi were both changed from rsi.rsi to result.rsi to allow for simple easy export to api for ui charting. You can do a simple find replace in your strat and change rsi.rsi to result.rsi

**Comment by allbinmani** [comment]
Well, actually, it seems it should be `rsi.result`, I was about to submitt a patch, but found this: https://github.com/askmike/gekko/pull/1172/commits/f6e293c60708920ae63d636697dc0b87cd0f797e

**Comment by generalectric** [comment]
Ahhhh yes.. Sorry a tad bit of dyslexia on my part... rsi.result is correct thanks @allbinmani

**Comment by askmike** [comment]
If you are still having issues please comment here what the issue is :)
