### ISSUE TITLE
candelHistory / warmup buggy in general, fatal on UI

### ISSUE THREAD

**Issue by LooOOooM** [askmike/gekko#1194]
* **I'm submitting a ...**
[X] bug report

I am running my strat using MA, EMA, MACD based on tablib on a 5min/15min candles size. The Commandline works fine, UI gives just about a 1-3 day result saying "NAN%", even I gave a timerange of a month. As already saied commandline works fine.
I noticed that no matter what "historySize" I give my debugging always gives me the first some candles (depending on the indecator . i.e MA20 = 20 candles or MA40 = 40 candles) as result undefined.

The same happens on UI with "warmup period" which is from my understanding point of view the same as "historySize" - No matter what I give  i.e 20 candles for MA20 or 40 for MA40,- The first 20, 40 or whatever the indecator needs to calculate correctly, the result is always "undefined"

From my understaning point of view this should not happen if I give the correct minimum of "historySize" or for UI "warmup period".
However, the commandline is obversly more robust as it runs anyway through the whole period of given time, while the UI simply showing crap: "NAN%"; graph is showing just few days.

Anyway, if I am not working in Xmin based UI calculation UI pass through. In addition the whole thing gets very wired if I do the following. 

1.) I have a line like this:
if ( this.position === 'out' && this.VOTE === 'BUY' && macd_tradevalue >= 4 ){
... Which works for the first run. If I replace that line by:
if ( this.position === 'out' && this.VOTE === 'BUY' && macd_tradevalue >= 4 EMA20 > EMA40){
UI sucks. ... So I replace it back and would expect that the UI run should work again, However it does not showing still crap : NAN% bla bla
I belive this meight have to do with caching maybe (browser, kernel, do not know)
However the core to this whole storry is i beleve the candelHistory/warmup period storry.

I am running gekko on Kalilinux (latest) accessing via Firefox 52.3, but the problem occures as well on IE and on chrome.
No strange behalvier on debug mode to see:

![buggyresult](https://user-images.githubusercontent.com/31613349/31335700-fdbb6dae-acf3-11e7-86c7-a03d839d7467.PNG)

please fix candelHistory/warmup for Xminute Tranings

**Comment by askmike** [comment]
I know the UI isn't stable over longer periods of time, will look into this when I have the time! Thanks for the precise debug information!
