### ISSUE TITLE
Korbit API for tradebot

### ISSUE THREAD

**Issue by John1231983** [askmike/gekko#1197]
Hello all, I am using Korbit (Biggest in Korea) for buy and sell the coins. It also provides the API at https://apidocs.korbit.co.kr/

Do you have any plan to support the Korbit? Thanks all

**Comment by danKHUU** [comment]
is there are sandbox or test api?

**Comment by danKHUU** [comment]
Hey @John1231983 

I am working on the Korbit's js wrapper.

Just completed the public API part, see if i can find out if korbit have a sandbox or some source of test account for testing the Private API.

**Comment by John1231983** [comment]
Yes. It supports the API. You can find it in the link that I was given. Did you incorporate it in Gekko?

**Comment by danKHUU** [comment]
No not yet, I need a test account. 

I tried to register for a Korbit account but can't verify my account. I don't have a korean mobile no to complete verification process lol...

**Comment by John1231983** [comment]
I see. So, Could you try to contact the support info@korbit.co.kr? I guess they have test API

**Comment by danKHUU** [comment]
Got a respond from Korbit

Thank you for contacting us.

To verify your account or use Korbit API(except public), These are the requirements.

1) Korean mobile phone number under your name 
2) Korean bank account under your name. 

If you do not have them, you cannot verify your account.
We are sorry there is no testing environment now.

Best regards,
Korbit

So...I would say its will not be possible for me to implement it for you. Unless you can provide a test account and deactivate it once I am done.

**Comment by bitkominer** [comment]
Hi @danKHUU, it would be very nice if you're able to do similar request of mine in this [link](https://github.com/askmike/gekko/issues/1186). It's the biggest crypto exchange in Indonesia and giving 0% fee for market maker.

Thanks!

**Comment by danKHUU** [comment]
Hi @bitkominer,

I can looks into that for you but I got to first find out if they have a test environment. Otherwise I cant test it.

**Comment by danKHUU** [comment]
Unable to get test account for korbit. I am guessing we can close this request.

**Comment by John1231983** [comment]
@danKHUU could you share your work with korbit api. I will use my account and test it. The reason i cannot share my account beacuse korbit only provides 1 api for each user
