### ISSUE TITLE
Ubuntu 14 or16 installing

### ISSUE THREAD

**Issue by metin02oktay** [askmike/gekko#1200]
Hello there. when I installed the gekko bot to my vps server(The same error in both ubuntu 14 and 16 LTS)   I compared it with an error like this:

root@ubuntu:~# certbot certonly --standalone -d example.com -d gekko.example.com

Saving debug log to /var/log/letsencrypt/letsencrypt.log
Obtaining a new certificate
Performing the following challenges:
tls-sni-01 challenge for example.com
tls-sni-01 challenge for gekko.example.com
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. example.com (tls-sni-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Incorrect validation certificate for tls-sni-01 challenge. Requested 0bc5b2042f3a165890141f639398042c.9742e28ceba767d599a712dbc3698f7d.acme.invalid from [2606:2800:220:1:248:1893:25c8:1946]:443. Received 2 certificate(s), first certificate had names "example.com, example.edu, example.net, example.org, www.example.com, www.example.edu, www.example.net, www.example.org", gekko.example.com (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: DNS problem: NXDOMAIN looking up A for gekko.example.com

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: example.com
   Type:   unauthorized
   Detail: Incorrect validation certificate for tls-sni-01 challenge.
   Requested
   0bc5b2042f3a165890141f639398042c.9742e28ceba767d599a712dbc3698f7d.acme.invalid
   from [2606:2800:220:1:248:1893:25c8:1946]:443. Received 2
   certificate(s), first certificate had names "example.com,
   example.edu, example.net, example.org, www.example.com,
   www.example.edu, www.example.net, www.example.org"

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.
 - The following errors were reported by the server:

   Domain: gekko.example.com
   Type:   connection
   Detail: DNS problem: NXDOMAIN looking up A for gekko.example.com

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.

root@ubuntu:~#

please help me :(

**Comment by askmike** [comment]
You can only use SSL and the certbot if you own a domain, you unfortunately do not own the domain example.com. I emailed you what instructions to follow (not these ones).
