### ISSUE TITLE
Add documentation on supported databases and how to configure to those databases

### ISSUE THREAD

**Issue by franz-see** [askmike/gekko#1207]
* **I'm submitting a ...**
[ ] bug report
[/] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
I searched in https://gekko.wizb.it/docs details on changing the database (i.e. to postgresql)

* **Expected result** (what you hoped would happen)
Would be able to find details on how to configure gekko to use another database.

* **Actual result** (unexpected outcome)
Could not find any

**Comment by askmike** [comment]
Great idea! Very open to PRs for this.

The idea is that you configure which adapter you want in the config (`config.js` for CLI users and `UIconfig` for UI users). I am open to PRs for this :)
