### ISSUE TITLE
[request] CEX.io Live Trading and Backtest importing support.

### ISSUE THREAD

**Issue by zartrade** [askmike/gekko#1208]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)

Looked at Supported Exchanges list and found CEX.io only listed with live monitoring support.

* **Expected result** (what you hoped would happen)

Since CEX.io seems to be the only exchange with 0% maker fee, it seems only logical to add live trading and importing for backtesting.

* **Actual result** (unexpected outcome)

CEX.io have no Live trading or importing for backing testing support.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

https://cex.io/cex-api

**Comment by askmike** [comment]
Very open to a PR! I won't have time for this.

**Comment by serial77** [comment]
Please bring back Cex.io as an exchange option in Gekko
