### ISSUE TITLE
candleSize GUI vs Command

### ISSUE THREAD

**Issue by Kirbylix** [askmike/gekko#1209]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[X ] question about the decisions made in the repository

i started a tradeBot in the GUI with candleSize 1 Hour, now i want to do this in a config with the CommandLine. Here is the question, which default value does the candleSize?

**Comment by Kirbylix** [comment]
one candleSize = one minute

**Comment by askmike** [comment]
:)
