### ISSUE TITLE
Kraken: Maket watcher begin fetching data from the wrong date

### ISSUE THREAD

**Issue by topolittle** [askmike/gekko#1210]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Launch a paper trader on Kraken with the USD/LTC pair.

* **Expected result** (what you hoped would happen)
The data should start fetching from the required period of time. E.g. if we are running the DEMA strategy with a long at 30, it should fetch the 30 last days.

* **Actual result** (unexpected outcome)
When launching a paper trading, the market watcher doesn’t start fetching data from the right time period. In fact, as of October 2017 it starts fetching from 2013.I am seeing this issue with any strategies and it doesn’t fetch more than 5 weeks from sometime in 2013.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
Gekko version: 0.5.8 (stable branch, commit 78d682dc)
NodeJs Version 6.11.4 LTS build with GCC-4.9.4
CentOs 7 (i386)
Gekko installed as a server (launched via systemd)
Trade pair: USD/LTC

**Comment by askmike** [comment]
The main Gekko pipe is not designed to fetch enormous amounts of data all at once. If your strategy needs 30 days warmup you should import some data first. For kraken this is now supported.

Note that when you are using the UI whether this local historical data can be used or not depends on a few different factors. This will be addressed in a future release. You can use the CLI version if you desire this behaviour.
