### ISSUE TITLE
Difference between kraken data and kraken charts

### ISSUE THREAD

**Issue by krem06** [askmike/gekko#1213]
Hi there,

First thanks for this nice project ! As I was diving in my strategy I realised that gekko database entries are different from the kraken chart and different from backtest log:

Gekko database:
Kraken XBT/USD - Entry: 2017-10-16 22:00 
unix timestamp:1508191200 
open:5704.1	
high:5708.0
low:5704.0
close:5708.0

Kraken chart ([view chart](https://dwq4do82y8xi7.cloudfront.net/widgetembed/?symbol=KRAKEN%3AXBTEUR&interval=D&symboledit=1&toolbarbg=f1f3f6&hideideas=1&studies=&theme=White&style=1&timezone=exchange)):
Kraken XBT/USD - Entry: 2017-10-16 22:00
open:5704.1	
high:5711.9
low:5704.0
close:5704.0

Backtest log:
Kraken XBT/USD - Entry: 2017-10-16 22:00
open:5708.1	
high:5719.7
low:5702.2
close:5719

Why are the results different ? Thanks in advance ;)

**Comment by askmike** [comment]
A candle is a representation of trade activity within a certain timespan. They will only be identical if measured over the same time frame. In the backtest: what "candle size" did you select (size of the timewindow).

When I click on the link to the chart it loads a chart with 1 day candles. I am not sure what their daily candle refers to (what timezone), etc. Besides the entry, would you be able to specify the timespan of the candle you are comparing?

**Comment by zartrade** [comment]
Id suggest to stay away from automated trading on kraken.

Their API is beyond slow and useless and during peak trading times it generally  returns 502 gateway error over and over thus missing any good trade signals.

**Comment by krem06** [comment]
@askmike, thanks for the quick reply !

+ I used 5min candle size in backtest
+ About the kraken chart, I selected 5min candles (Must be set in my session or cookie)
+ "Would you be able to specify the timespan of the candle you are comparing?" Still very new and I may not understand it well but you are refering to the candle size no ? I selected 5min in the chart

I have to say my concern was mainly about local db that did not correspond to any values in visual charts on kraken. BUT I realised 2 things this morning after a good night sleep:
1. The gekko database is set to 1min candleSize so totally normal it doesn't correspond to my 5min candleSize backtest. 
2. Based on above statement I checked chart on tradingview WITH candleSize 1min and yes they match

Now I understand how it works and results are consistent between tradingView and gekko database thank you for your answer that unblocked my brain !

BUT I am still confused why kraken chart beta, accessible from kraken account, does not give me the same results.... But looking at @zartrade comment it might be better to just look the other way...

If Kraken is not a good platform, what should I use ?

Thanks again for the great comments

**Comment by zartrade** [comment]
I would have loved to reliably use Kraken but as noted before, they are far too unreliable during the best trading times with gateway timeouts , dead api etc. They need to upgrade their trading engine or something before it is at all a safe exchange to use.

Right now until we can get CEX.io added (0% maker fee), I am using bitfinex,poloniex and bittrex(mainly for altcoins and not very high trade activity due to their 0.25% fee which is not ideal)

**Comment by krem06** [comment]
Thanks mate ;)
