### ISSUE TITLE
localhost connection refused for paper trading

### ISSUE THREAD

**Issue by VigSim** [askmike/gekko#1214]
Hello, I am very new to gekko. I'm trying to run paper trader on BTC/ETH pair and the strategy is DEMA.

The process of running UI and choosing appropriate parameters goes smoothly. However, when I click 'run' I get an error "Connection refused" in bash. I turned off firewall, but that did not help.

If this may help, I am running windows 10 and the server is not my computer.

**Comment by askmike** [comment]
Strange, could you post what is visible in the commandline prompt?

**Comment by VigSim** [comment]
Bash screenshot - 
![image](https://user-images.githubusercontent.com/29207334/31835561-12814b4e-b5e3-11e7-9372-550db1f67eb9.png)

Just in case. 
![image](https://user-images.githubusercontent.com/29207334/31835546-0231da38-b5e3-11e7-8707-1b6eb0325869.png)
