### ISSUE TITLE
A possible adjustment to RSI?

### ISSUE THREAD

**Issue by Vamby** [askmike/gekko#1216]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[X] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)

I've tried using the indicator RSI (in backtest and trading bot)

* **Expected result** (what you hoped would happen)

It did what i asked.

* **Actual result** (unexpected outcome)

Some trades are profitable and others are not.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Is there a way to add some scripts in the indicator so the bot won't sell my currency with loss?
For example: it buys BTC with LTC and a day later it wants to sell the LTC again for BTC with a loss of 5%. Is there any way to prevent that order and only sell those LTC with a minimum profit of 5%?

**Comment by Momohime** [comment]
I don't think default RSI has this hard coded, however, you can always code your strategy and extend the RSI indicator.

**Comment by DeBelserArne** [comment]
I was thinking about logging the buy price somewhere, and then every time before a script tries to sell. 
It woul compare the logged buy price, with the sell price, if the sell price is lower as the buy price, just don't sell.

But I can't really seem to find where the buy price is logged in the scripts.

**Comment by askmike** [comment]
In order to do this you need to adjust the strategy "RSI" (that simply implements a single RSI indicator).

- Here is the documentation you need: https://gekko.wizb.it/docs/strategies/creating_a_strategy.html
- Here is the file you need to adjust: https://github.com/askmike/gekko/blob/stable/strategies/RSI.js
- Here is an example of similar functionality: #502 

:)
