### ISSUE TITLE
Attempt at sounds alerts

### ISSUE THREAD

**Issue by Guceri** [askmike/gekko#1218]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[X] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
I am attempting to create sounds alerts by using the npm package 'play-sound'.
I created a few short mp3 clips using a text to speech website (there are quite a few out there)
I was able to successful configure the node package and test it to work.  I created a sound folder which holds all the audio clips and a module.exports file which has a list of functions which run the audio clips.  I was able to run a test script which called on the functions and the audio clips would fire.

* **Expected result** (what you hoped would happen)
I embedded the audio functions into my strategy and also in the portfolioManager.js and was hoping that upon a buy/sell signal, that I would get an alert and addtionally a couple more alerts that were embedded into the portfolioManager.js (Order Cancelled and Order filled alerts).

* **Actual result** (unexpected outcome)
There was no sound that was generated.  I am not sure why.  I have run test scripts in several folders and they work just fine when I run them directly from the command line, but when gekko is running, it does not fire the audio.  

I am sure what is going on.....

Any thoughts on how this could be achieved?  I think it would be a good feature for others 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
That should work, can you post some code so that we can try to reproduce?

**Comment by Guceri** [comment]
Mike,
  Here is what I did.  I just created folder called 'sound' within Gekko with 4 sound bites (let me know if you want me to send them to you, they won't attach to the post).  They are mp3 format.

1. 'A new buy signal was generated'
2.'A new sell signal was generated'
3. 'Order not filled, cancelling and sending new order'
4. 'Order filled'

I created soundAlert.js with the follow code:

```
var player = require('play-sound')();

module.exports = {
  BuySignal: function(){
    player.play('./BuySignal.mp3');
  },
  SellSignal: function(){
    player.play('./SellSignal.mp3');
  },
  OrderNotFilled: function(){
    player.play('./OrderNotFilled.mp3');
  },
  OrderFilled: function(){
    player.play('./OrderFilled.mp3');
  }
}
```
I also created a test script within the sound folder to make sure it worked.  I called it soundTest.js

```
var soundAlert = require ('./soundAlert.js');

soundAlert.BuySignal();
```

Then, in my strategy code, which is in the strategy folder I put the appropriate buy and sell signal sound clips

```
//At the top of the code
var soundAlert = require ('../sound/soundAlert.js');
//Inside the strat.check function right below this.advice(buy)
soundAlert.BuySignal();
```

I also went into the portfolioManger.js code and I inserted sound bite #3 and #4 into the Manager.prototype.checkOrder function.  PLEASE NOTE THE CHECK ORDER FUNCTION WILL LOOK DIFFERENT THEN THE CURRENT GEKKO SETTINGS AS I USE LIMIT ORDERS THAT ARE GENERATED OFF AN EMA, AND ONLY UPDATE ON A NEW CANDLE.  The handleCheckResult function below is within the checkOrder function.  

orderCount (see in below code) is just a counter that identifies how many 1 minute checks have been done.  It will keep checking the order up to the size of the candles you are using (based on the config file settings) and then cancel the order and update it.  

I also included at the top of portfolioManager.js:
`var soundAlert = require ('../sound/soundAlert.js');`

  ```
var handleCheckResult = function(err, filled) {
    if(!filled && this.orderCount == config.tradingAdvisor.candleSize) {
      log.info(this.action,'order was not filled, cancelling and creating new order');
      sound.OrderNotFilled();
      this.exchange.cancelOrder(_.last(this.orders), _.bind(handleCancelResult, this));
      this.orderCount = 1;
    } else
    if(!filled && this.orderCount < config.tradingAdvisor.candleSize) {
      log.info('waiting for',this.action,'order to fill...');
      this.orderCount = this.orderCount + 1;
      setTimeout(this.checkOrder,util.minToMs(1));
    } else{
      //if the order is filled, then the below actions take place
      //reset order count since order filled
      this.orderCount = 1;
      log.info(this.action, 'order was filled');
      sound.OrderFilled();
      this.relayOrder();
      }
  }
```

In order for the 'play-sound'  package to work, you have to have one of the command line audio players that are listed in the requirements of the package.  The player also needs a PATH in the environmental variables (windows 10) in order to work on the command line.

Also, for disclosure, I am using Atom as my IDE if it makes any difference.  It uses windows Powershell as the command line.
