### ISSUE TITLE
[bug] Wrong gekko version shown in the UI after updating to latest changes - Docker Image

### ISSUE THREAD

**Issue by dpsarrou** [askmike/gekko#1221]
**I'm submitting a ...**
[x ] bug report

**Action taken** (what you did)
- Cloned latest stable version v0.5.8
- Installed using Docker following the instructions on https://github.com/askmike/gekko/blob/stable/docs/installation/installing_gekko_using_docker.md

**Expected result**
UI should show Gekko version 0.5.8 at the footer

**Actual result**
UI shows Gekko version 0.5.2 at the footer

**Other information**
I've noticed that this is happening because:
- The UI is prebuilt for version 0.5.2 and committed to the repo as shown here:
https://github.com/askmike/gekko/tree/stable/web/vue/dist even though the latest stable is 0.5.8
- Docker build will not run the build process for the UI

To avoid rebuilding and commiting a new build.js file every time a new version of gekko is released, I can create a PR that does the following:
- Remove the web/vue/dist/build.js file from the repository since it can (and should) be rebuilt when installing from source
- Include a UI build step in the Dockerfile
- Update the documentation to notify people that they need to build the frontend as well

**Comment by askmike** [comment]
This has since been fixed in v0.5.9. Let's keep the rest of the discussion going in the PR.
