### ISSUE TITLE
Calculate a 4h macd every minute

### ISSUE THREAD

**Issue by krem06** [askmike/gekko#1224]
I would like to get every minute the macd for the last 4h, how can it be done ? I may also want to get other macds based on different candle size in the same strategy.

Found #893 which talk about it, and the following comment is interesting to me:
> Note that with MACD you can easily create a strategy that registeres two different MACDs:
> 
> one with the short and long quite far apart (results in a "sensitive" diff signal)
> one with the short and long quite closer together (results in a "less sensitive" diff signal).
> This mimics the behaviour you are looking for, however this is not possible with all indicators.

I don't know how to implement that concept, somebody could explain or point me to some code ?

Thanks

**Comment by krem06** [comment]
#1075 also gives some interesting details:
> The addIndicator method is just a helper function that actually does a few things under the hood:
> 
> register an indicator object to this.indicators for easy access.
> whenever there is new market data (=when there are new candles) pump them into the indicator.

So if every minute I want to "pump" the new 1min candle in my 4h macd and get the corresponding values, how should I do it in 'method.update' ?

Thanks in advance

**Comment by askmike** [comment]
Why do you want this?

You need to create your own indicators (what Gekko does behind the scene when you call `this.addIndicator` and resize candles and pipe those in yourself. And in your case you need to store and manage a bunch of candles.

This is not an easy strategy anymore, you need to build a lot of code on top of the stratrunner to get this working.

This is pretty complex to do and will probably be too slow to do with Gekko. I am not sure why you would want this but I am afraid Gekko is not the right tool for the job (at the moment).

**Comment by krem06** [comment]
The goal is to use 2 different macd values within 1 unique strategy. I first thought about having 2 macd indicators in the strategy but it seems to be problematic (Could you confirm ?) that's why I thought to have 1 indicator but 2 ways to calculate macd...

Second your comments it seems to be too tricky to achieve first scenario and if you confirm 2 indicators in 1 strategy is also complicated then I guess I need to search for another solution... Maybe 2 virtual machines in parralel with Gekko connecting to same account ?

Or may be I just need to rethink the strategy ;)

**Comment by krem06** [comment]
Hi again,

Closing this ticket as I have read again your #1075 post:

> If you want more complex functionality, like different indicators on different intervals the best way right now is to just calculate them yourself: in your strat's update function you can update them yourself (every Nth candle for example). 

I got it I think, thanks !

**Comment by krem06** [comment]
Hi again,

reopening the ticket as I have made some advance in getting 2 different candle size in 1 strategie... but getting wrong indicator values.

So far I am able to import ta-lib directly in strategy, save every candle close price in a custom object array (this.mycandle.prices) and then use those values to calculate macd with ta-lib instead of gekko indicator (which is set to 1 minute).

First I want to verify my results so I do the following to check 1min macds for each candle:
```
var macd = talib.execute({
    name: "MACD",
    inReal: this.mycandle.prices,
    startIdx: 0,
    endIdx: this.mycandle.prices.length -1,
    optInFastPeriod: 12,
    optInSlowPeriod: 26,
    optInSignalPeriod: 9
}, function (err, result) {
    if(err){ console.log(err); }

    console.log("MACD Function Result:"  + candle.start._d);
    console.log("outMACD: " + result.result.outMACD[result.result.outMACD.length - 1]);
    console.log("outMACDSignal: " + result.result.outMACDSignal[result.result.outMACDSignal.length - 1]);
    console.log("outMACDHist: " + result.result.outMACDHist[result.result.outMACDHist.length - 1]);
});
```
The great thing is that it returns results so the call to macd function is working but not getting the right values.

Why is my custom 1min macd different from the 1min macd from gekko ? My first guess is that I am not using right the array of closing prices to generate macd.

So my question is, how could I monitor the closing price array that gekko uses to calculate macd ? As I understand it's "under the hood" but I would like to see how the macd get calculated and generate some console log to compare with my custom values.

I hope it makes sense, thank you for the great support ;)

**Comment by krem06** [comment]
I managed to compare and verify results of my custom macd adding some debug log to the execute function in /core/talib.js file.

Great but I think I am having a callback problem...

Current result: 
DEBUG: Candle id 1
DEBUG: Candle id 2
DEBUG: Candle id 3
DEBUG: Candle 1 MYMACD: xxxx
DEBUG: Candle 2 MYMACD: xxxx
DEBUG: Candle 3 MYMACD: xxxx

Expected result: 
DEBUG: Candle id 1
DEBUG: Candle 1 MYMACD: xxxx
DEBUG: Candle id 2
DEBUG: Candle 2 MYMACD: xxxx
DEBUG: Candle id 3
DEBUG: Candle 3 MYMACD: xxxx

How to make sure that update method waits for my custom macd result ?

**Comment by askmike** [comment]
> How to make sure that update method waits for my custom macd result ?

It won't, you have to create another method and use that instead. You can
register a new function in your init method.

**Comment by krem06** [comment]
> It won't, you have to create another method and use that instead. You can register a new function in your init method.

Ok but do you refer to create a new method to add a step between method.update and method.check (like method.mycandle) or just to add a new indicator in baseTradingMethod.js and call it normally in my init method ?

Am I right to think that baseTradingMethod.js is the only file that needs to be modified apart of my strategy ?

Thank you for your time, really appreciate it

**Comment by krem06** [comment]
Closing the ticket as I think I have found a way to go around my problems within gekko capabilities so no need for now to hack another indicator with different candle size ;) 
Anyway some guidance on doing such modification would be great but I guess you have plenty in your plate so keep up the good work ! Thank you Mike.

**Comment by askmike** [comment]
Ah great! And apologies for that.
