### ISSUE TITLE
Using high history count

### ISSUE THREAD

**Issue by zartrade** [askmike/gekko#1226]
Any idea how to speed up the calculation when using high history count ? My history is set to 91 for CCI tradebot and when I restart the gekko instance it takes roughly 12hours to get to 91 history country.

Candlesize 16
Warmup period 10

(will use 2 hours, 40 minutes of data as history)

Is this just normal behaviour or am I doing something wrong that I could improve on so after restarting it doesnt take so long. I would think it would continue using the history already stored from the previous instance run but the way the restart looks its as if it continously thinks its a fresh start and need to build that 91 history count from scratch.

**Comment by askmike** [comment]
Yes: Use the commandline interface. The UI works a bit differently and right now the commandline version can stitch local data (assuming Gekko has it) a lot better with than the UI version.

See the docs here: https://gekko.wizb.it/docs/commandline/about_the_commandline.html

**Comment by zartrade** [comment]
I am using the cmd version as like you said the UI is not as informative.

Right now its takes me 16mins x 91 in order to warmup from a restart. Ive enabled storing candles in the config but still it seems at restart it does not use any of my stored history. Am I overlooking anything , from what I can see I have configured it correctly.
