### ISSUE TITLE
[BUG] Kraken tries to import 190 years of trades and crashes

### ISSUE THREAD

**Issue by metodi-yanev** [askmike/gekko#1230]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Running a headless bot on a server in paper mode (due to prior bug with placing real orders). 

* **Expected result** (what you hoped would happen)
Collecting data from market, receive advice

* **Actual result** (unexpected outcome)
After 5-6 requests it tries to fetch 190 years of data (see log) which leads to server overload and node crash.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
0|gekko    | 2017-10-20 22:26:05 (INFO):	Setting up Gekko in realtime mode
0|gekko    | 2017-10-20 22:26:05 (INFO):	
0|gekko    | 2017-10-20 22:26:05 (INFO):	Setting up:
0|gekko    | 2017-10-20 22:26:05 (INFO):		 Candle writer
0|gekko    | 2017-10-20 22:26:05 (INFO):		 Store candles in a database
0|gekko    | 2017-10-20 22:26:06 (INFO):	
0|gekko    | 
0|gekko    | 2017-10-20 22:26:06 (INFO):	Setting up:
0|gekko    | 2017-10-20 22:26:06 (INFO):		 Trading Advisor
0|gekko    | 2017-10-20 22:26:06 (INFO):		 Calculate trading advice
0|gekko    | 2017-10-20 22:26:06 (INFO):		 Using the strategy: talib-macd
0|gekko    | 2017-10-20 22:26:06 (INFO):	
0|gekko    | 
0|gekko    | 2017-10-20 22:26:06 (INFO):	Setting up:
0|gekko    | 2017-10-20 22:26:06 (INFO):		 Telegram bot
0|gekko    | 2017-10-20 22:26:06 (INFO):		 Telegram module lets you communicate with Gekko on Telegram.
0|gekko    | 2017-10-20 22:26:06 (INFO):	
0|gekko    | 
0|gekko    | 2017-10-20 22:26:06 (INFO):	Setting up:
0|gekko    | 2017-10-20 22:26:06 (INFO):		 Advice logger
0|gekko    | 2017-10-20 22:26:06 (INFO):		 
0|gekko    | 2017-10-20 22:26:06 (INFO):	Setting up:
0|gekko    | 2017-10-20 22:26:06 (INFO):		 Paper Trader
0|gekko    | 2017-10-20 22:26:06 (INFO):		 Paper trader that simulates fake trades.
0|gekko    | 2017-10-20 22:26:06 (INFO):	
0|gekko    | 
0|gekko    | 2017-10-20 22:26:06 (INFO):	Setting up:
0|gekko    | 2017-10-20 22:26:06 (INFO):		 Performance Analyzer
0|gekko    | 2017-10-20 22:26:06 (INFO):		 Analyzes performances of trades
0|gekko    | 2017-10-20 22:26:06 (INFO):	
0|gekko    | 
0|gekko    | 2017-10-20 22:26:06 (INFO):	Starting to watch the market: Kraken XBT/EUR
0|gekko    | 2017-10-20 22:26:06 (DEBUG):	scheduling ticks
0|gekko    | 2017-10-20 22:26:06 (DEBUG):	Requested XBT/EUR trade data from Kraken ...
0|gekko    | 2017-10-20 22:26:06 (DEBUG):	Processing 1000 new trades. From 2017-10-20 21:35:36 UTC to 2017-10-20 22:26:03 UTC. (an hour)

0|gekko    | 2017-10-20 22:26:26 (DEBUG):	Requested XBT/EUR trade data from Kraken ...
0|gekko    | 2017-10-20 22:26:27 (DEBUG):	Processing 6 new trades. From 2017-10-20 22:26:09 UTC to 2017-10-20 22:26:26 UTC. (a few seconds)
0|gekko    | 2017-10-20 22:26:46 (DEBUG):	Requested XBT/EUR trade data from Kraken ...
0|gekko    | 2017-10-20 22:26:46 (DEBUG):	No new trades.
0|gekko    | 2017-10-20 22:27:06 (DEBUG):	Requested XBT/EUR trade data from Kraken ...
0|gekko    | 2017-10-20 22:27:07 (DEBUG):	Processing 7 new trades. From 2017-10-20 22:26:49 UTC to 2017-10-20 22:27:05 UTC. (a few seconds)
0|gekko    | 2017-10-20 22:27:26 (DEBUG):	Requested XBT/EUR trade data from Kraken ...
0|gekko    | 2017-10-20 22:27:27 (DEBUG):	Processing 19 new trades. From 2017-10-20 22:27:11 UTC to 2017-10-20 22:27:29 UTC. (a few seconds)
0|gekko    | 2017-10-20 22:27:46 (DEBUG):	Requested XBT/EUR trade data from Kraken ...
0|gekko    | 2017-10-20 22:27:46 (DEBUG):	No new trades.
0|gekko    | 2017-10-20 22:28:06 (DEBUG):	Requested XBT/EUR trade data from Kraken ...
0|gekko    | 2017-10-20 22:28:06 (DEBUG):	No new trades.
0|gekko    | 2017-10-20 22:28:26 (DEBUG):	Requested XBT/EUR trade data from Kraken ...
0|gekko    | 2017-10-20 22:28:26 (DEBUG):	Processing 17 new trades. From 2017-10-20 22:28:10 UTC to 2017-10-20 22:28:28 UTC. (a few seconds)
0|gekko    | 2017-10-20 22:28:46 (DEBUG):	Requested XBT/EUR trade data from Kraken ...
0|gekko    | 2017-10-20 22:28:46 (DEBUG):	Processing 4 new trades. From 2017-10-20 22:28:29 UTC to 2017-10-20 22:28:39 UTC. (a few seconds)
0|gekko    | 2017-10-20 22:29:06 (DEBUG):	Requested XBT/EUR trade data from Kraken ...
0|gekko    | 2017-10-20 22:29:06 (DEBUG):	Processing 3 new trades. From 2017-10-20 22:28:56 UTC to 2017-10-20 22:29:07 UTC. (a few seconds)
0|gekko    | 2017-10-20 22:29:26 (DEBUG):	Requested XBT/EUR trade data from Kraken ...
0|gekko    | 2017-10-20 22:29:26 (DEBUG):	Processing 1 new trades. From 2017-10-20 22:29:24 UTC to 2017-10-20 22:29:24 UTC. (a few seconds)
0|gekko    | 2017-10-20 22:29:46 (DEBUG):	Requested XBT/EUR trade data from Kraken ...
0|gekko    | 2017-10-20 22:29:46 (DEBUG):	Processing 5 new trades. From 2017-10-20 22:29:29 UTC to 2017-10-20 22:29:45 UTC. (a few seconds)
0|gekko    | 2017-10-20 22:30:06 (DEBUG):	Requested XBT/EUR trade data from Kraken ...
0|gekko    | 2017-10-20 22:30:06 (DEBUG):	Processing 5 new trades. From 2035-12-27 12:20:53 UTC to 2226-05-02 01:30:02 UTC. (190 years)

I've tried a couple restarts, changed the config file to not request history for the strat and deleted the contents of the history folder but it still behaves the same way.

I was just about to try the fix suggested for real trades and saw this. :(

Any ideas?

**Comment by staugaard** [comment]
Yeah I'm seeing the exact same issue (also using kraken).

```
2017-10-20 16:18:05 (DEBUG):    Requested XBT/USD trade data from Kraken ...                                                                                                                                                         
2017-10-20 16:18:06 (DEBUG):    Processing 8 new trades. From 2017-10-20 16:18:01 UTC to 2017-10-20 16:18:07 UTC. (a few seconds)                                                                                                    
2017-10-20 16:18:25 (DEBUG):    Requested XBT/USD trade data from Kraken ...                                                                                                                                                         
2017-10-20 16:18:25 (DEBUG):    Processing 6 new trades. From 2017-10-20 16:18:13 UTC to 2017-10-20 16:18:25 UTC. (a few seconds)                                                                                                    
2017-10-20 16:18:45 (DEBUG):    Requested XBT/USD trade data from Kraken ...                                                                                                                                                         
2017-10-20 16:18:45 (DEBUG):    Processing 6 new trades. From 2035-04-30 22:18:22 UTC to 2102-05-08 10:47:12 UTC. (67 years)                                                                                                         
```

**Comment by zartrade** [comment]
Might be related to the same bug bitcoinwisdom is showing where kraken trade price is sitting at 27089151782788.00 EUR/BTC :)

Their API is more than likely broken or changed drasticly overnight.

**Comment by Guceri** [comment]
I signed up for Kraken, and after seeing how horrendous their connection is and the poor quality of imported data (among all the other issues people are reporting here), I think it would be best to stay away unless you really want to use Kraken for some reason.  

Just using their site was a god awful experience....

**Comment by metodi-yanev** [comment]
Seems to be a problem with Kraken API that has been resolved. I have the bot running with no crashes for several hours now, so i'm closing the issue.
