### ISSUE TITLE
Received error in import

### ISSUE THREAD

**Issue by wpb279** [askmike/gekko#1233]
Hi

I'm new to code, but tried to install your program (also followed your YouTube tutorial).

It seems everything installs ok, but when I open the program in the browser, and try to import data, I get the following error:

IMPORT ERROR: Gekko encountered an error and can't continue

It also seems to give the same error when I try to use any of the other functions.

Any help would be appreciated.

Thanks

**Comment by unitycoder** [comment]
check console/command prompt window for errors..

i had import error with this console message:
`Error: The plugin sqlite adapter expects the module sqlite3 to be installed. However it is not, install it by running:  npm install sqlite3@3.1.4`

running that install command fixed it

**Comment by askmike** [comment]
> IMPORT ERROR: Gekko encountered an error and can't continue

There should be something under there in your command prompt (the actual error), could you post that?

**Comment by AHorihuela** [comment]
Actual error:

```
RECEIVED ERROR IN IMPORT 807134222724414
Gekko encountered an error and can't continue
Gekko encountered an error and can't continue

Error:
The plugin sqlite adapter expects the module sqlite3 to be installed. However it is not, install it by running: 

 	npm install sqlite3@3.1.4

Meta debug info:

Gekko version: v0.5.11
Nodejs version: v9.3.0
```

**Comment by greenbigfrog** [comment]
@AHorihuela all you gotta do, is run `npm install sqlite3@3.1.4` as it tells you.

@askmike this can be closed. this is fixed in develop (or master?)

**Comment by greenbigfrog** [comment]
@AHorihuela all you gotta do, is run `npm install sqlite3@3.1.4` as it tells you.

#1518 fixes this.
