### ISSUE TITLE
Different types of candles (e.g. Heiken ashi)

### ISSUE THREAD

**Issue by alterdaemon** [askmike/gekko#1234]
Hi, I have a simple question (couln't find it in documentation) - does Gekko support different types of candles? Like Heiken-ashi?

**Comment by askmike** [comment]
Unfortunately these are not natively supported, the good thing is that you can easily calculate them based on normal candles. It would be very easy to add a function inside your strategy that calculates them on the fly.

**Comment by alterdaemon** [comment]
I have already tried that **but** to calculate _open price_ with heiken-ashi you need recursive function because for each iteration it needs to refer to the previous candle.
Any idea how to start with that under gekko?

**Comment by askmike** [comment]
Looking at these calculations: http://stockcharts.com/school/doku.php?id=chart_school:chart_analysis:heikin_ashi

It seems you only need access to:

- current candle
- previous candle

The `update` function of your strategy runs whenever there is a candle, inside this function you can cache the "current" candle which will be the previous candle the next time it runs. Example:

    var calculateHeikin = function(previous, current) {
      // your magic
    }


    method.update = function(candle) {
      if(this.previousCandle) {
        var heikin = calculateHeikin(this.previousCandle, candle);

        // do something with heikin
      }

      this.previousCandle = candle;
    }

**Comment by alterdaemon** [comment]
thx, I will try that! much appreciated.

So it seems that for the first HA candle I need to take the standard candle _Open_.

**Comment by askmike** [comment]
ah great, if you run into any problems let me know :)
