### ISSUE TITLE
Installation for ubuntu 16.06

### ISSUE THREAD

**Issue by ahmethakandd** [askmike/gekko#1235]
Hello to everyone. I am using ubuntu 16.04LTS (from aws). I want to setup gekko, every time I'm doing wrong because I'm not pro user

Is there anyone who wants to take video about the installation on ubuntu 16.04? For installation video, I will share the vps server information and he can share this video on your own YouTube channel ...

email for communication: aliminik12345678@gmail.com

As soon as I wait for the return. Best regards.. (sorry bad english, just google translate :)

**Comment by ahmethakandd** [comment]
It can also be an automated script for installation. :)

**Comment by askmike** [comment]
Unfortunately Gekko is a technical tool, if you have trouble installing it you won't get very far in using it.

If you have specific errors you don't know how to solve, please post them so we can see what might be wrong.

**Comment by venturaEffect** [comment]
Hi every to one,

Well I'm having the same problem, can't install it in ubuntu 16.04. 

Has someone found a way to do it?

Thanks and specially thanks to @askmike for his work

**Comment by born2hate** [comment]
installed on ubuntu 16.04, no problems
