### ISSUE TITLE
[REQUEST] hitbtc.com exchange support

### ISSUE THREAD

**Issue by zartrade** [askmike/gekko#1242]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[x ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)

looked at supported exchanges, hitbtc.com exchange not supported.

* **Expected result** (what you hoped would happen)

hitbtc.com exchange support.

* **Actual result** (unexpected outcome)

no hitbtc.com exchange support. :)

**Comment by askmike** [comment]
Open for Pull requests, I won't have time to add this. Documentation required is here: https://gekko.wizb.it/docs/extending/add_an_exchange.html
