### ISSUE TITLE
amount is too small at Kraken

### ISSUE THREAD

**Issue by Kirbylix** [askmike/gekko#1255]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[X] question about the decisions made in the repository

* **Action taken** (what you did)
trading on kraken with XBT <-> EUR

* **Expected result** (what you hoped would happen)
buy or sell

* **Actual result** (unexpected outcome)
ERROR "Wanted to buy XBT but the amount is too small (0.022...) at Kraken"

what is the minimum amount?

**Comment by askmike** [comment]
It should be 0.01 XBT, how much did you have (0.022 XBT or EUR)?

**Comment by Kirbylix** [comment]
at the moment i have ~109 € in my kraken wallet
and my Gekko want to buy Bitcoins

**Comment by askmike** [comment]
That's a bug in gekko, kraken integration has been anything but stable,
will have a look asap!

**Comment by Kirbylix** [comment]
that would be wonderful, I've been trying to get my geko to work for about a month now....

**Comment by askmike** [comment]
closing as a dup of #1259.

**Comment by hilkoc** [comment]
I'm having the same problem on Kraken running the latest commit of develop branch today.
