### ISSUE TITLE
Loop with unable to cancel order XXX (Error: Order:Unknown order: XXX...

### ISSUE THREAD

**Issue by pprados** [askmike/gekko#1258]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Trade with Kraken

* **Expected result** (what you hoped would happen)
Cancel order, and if Unknown order, ignore and continue

* **Actual result** (unexpected outcome)
A loop to retry to cancel order.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

I propose to add in kraken.js, method cancelOrder :
`
    if (err.message.startsWith("Order:Unknown order:")) 
        log.warn("Ignore unknown order")
      else return this.retry(this.cancelOrder, args);
`

**Comment by askmike** [comment]
ping @cmroche

**Comment by ebrulato** [comment]
I have the same issue.
but I'm not sure this is the best solution to fix it :)

**Comment by cmroche** [comment]
Yeah this one makes a lot of sense. HTTP 8xx series errors will tend to lead to this issue, which will then eventually fill the rate limiter.

I'll take a look at implementing a fix for this over the upcoming weekend.

No promises as my schedule this week will be a bit tight. But it shouldn't take too long to get something for testing.

**Comment by askmike** [comment]
@cmroche has proposed a fix which is now available in the develop branch, would you mind checking whether this solves the issue?
