### ISSUE TITLE
Redownloaded gekko and encoutering an issue

### ISSUE THREAD

**Issue by DeBelserArne** [askmike/gekko#1267]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Redownloaded Gekko

* **Expected result** (what you hoped would happen)
Run Gekko

* **Actual result** (unexpected outcome)
I got an eroor, cannot finde module.

https://i.gyazo.com/66fb539cc126e5f909f376bb753fbe75.png
See screenshot

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
you need to run `npm install` after downloading, see the installation docs for details.
