### ISSUE TITLE
Import more then 3 months of data

### ISSUE THREAD

**Issue by Vamby** [askmike/gekko#1268]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X ] help request

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

I want to import more then 3 months of data. I think I read something about it somewhere, but I'm not managing to find out where.

I've tried loading three months of data, then for the same currency and assets load another 3 months of data, but that doesn't seem to do the trick.

**Comment by Kirbylix** [comment]
simply specify the date range when importing.
I have been importing successfully for 4 months.

**Comment by Vamby** [comment]
Oh really? I taught the maximum was 3 months! my bad. I'll try your solution!

**Comment by askmike** [comment]
:)
