### ISSUE TITLE
UnhandledPromiseRejectionWarning - Cannot start

### ISSUE THREAD

**Issue by brainfoolong** [askmike/gekko#1269]
Hi, i have a bug and cannot start gekko.
I am running ubuntu 16.04 server.

I have the current git version of this repos

    git status
    On branch stable
    Your branch is up-to-date with 'origin/stable'

Versions of nodejs and npm

    ~/gekko$ node -v
    v6.11.5
    ~/gekko$ npm -v
    5.5.1

Installed tested with both production and development dependencies. 
No errors during that installation

    npm install
    up to date in 8.029s

The output log when i want to start with

           ~/gekko$ node gekko --ui
		______   ________  __    __  __    __   ______
	   /      \ /        |/  |  /  |/  |  /  | /      \
	  /$$$$$$  |$$$$$$$$/ $$ | /$$/ $$ | /$$/ /$$$$$$  |
	  $$ | _$$/ $$ |__    $$ |/$$/  $$ |/$$/  $$ |  $$ |
	  $$ |/    |$$    |   $$  $$<   $$  $$<   $$ |  $$ |
	  $$ |$$$$ |$$$$$/    $$$$$  \  $$$$$  \  $$ |  $$ |
	  $$ \__$$ |$$ |_____ $$ |$$  \ $$ |$$  \ $$ \__$$ |
	  $$    $$/ $$       |$$ | $$  |$$ | $$  |$$    $$/
	   $$$$$$/  $$$$$$$$/ $$/   $$/ $$/   $$/  $$$$$$/

			Gekko v0.5.9
			I'm gonna make you rich, Bud Fox.

	TAlib is disabled
	Serving Gekko UI on http://localhost:3000/

	(node:30340) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Exited with code 3

**Comment by brainfoolong** [comment]
Oh, ok solved my own issue.
A server needs this

https://gekko.wizb.it/docs/installation/installing_gekko_on_a_server.html

and `headless` true.

Anyway, one dependency is missing when using emails. 

    npm install emailjs@1.0.5

Maybe add this to the package.json.

**Comment by askmike** [comment]
awesome :)

if you enable the email plugin Gekko will check and warn you to install the dependency if you did not have it before!
