### ISSUE TITLE
Talib 1.0.2

### ISSUE THREAD

**Issue by Freddysback** [askmike/gekko#1270]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[1 ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
cd ~/gekko
npm remove talib
npm install talib@1.0.2

* **Expected result** (what you hoped would happen)
I edit line 53 from WAL to DEL using nano and went to the next step to remove talib and install talib 1.0.2.  Got an error so I couldn't move on and start up Gekko in the next step.

* **Actual result** (unexpected outcome)
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:14:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:69:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:81:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:90:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Linux 4.4.0-43-Microsoft
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /home/Freddysback/node_modules/talib
gyp ERR! node -v v6.11.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/home/Freddysback/package.json'
npm WARN Freddysback No description
npm WARN Freddysback No repository field.
npm WARN Freddysback No README data
npm WARN Freddysback No license field.
npm ERR! Linux 4.4.0-43-Microsoft
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "talib@1.0.2"
npm ERR! node v6.11.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! talib@1.0.2 install: `node ./src/lib/build.js && node-gyp configure && node-gyp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the talib@1.0.2 install script 'node ./src/lib/build.js && node-gyp configure && node-gyp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the talib package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./src/lib/build.js && node-gyp configure && node-gyp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs talib
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls talib
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/Freddysback/npm-debug.log

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
What should I do now?

**Comment by askmike** [comment]
where did you find these steps? what is your OS?

**Comment by Freddysback** [comment]
I solve it.  I would like to thank you for building such a wonderful piece of art.  Where can I learn how to build the best strategies for Gekko?

**Comment by Freddysback** [comment]
I found the steps https://gekko.wizb.it/docs/installation/installing_gekko_on_windows_with_bash_on_windows_10.html.  OS is Windows 10

**Comment by cmroche** [comment]
This is bash on windows based on the output.

It's telling you at the top that it cannot find 'make'. You need to install build essentials.

 sudo apt-get update
 sudo apt-get install build-essential

Note that it is build-essential, not build-essentials. IIRC I also had to restart bash after doing this to pick up all the update environment variables that this modified.

**Comment by Tibitester** [comment]
Hello, Could you please help me with a solution for bellow blocking point, I used a several hours allready to get to this point this weekend, I don't know how to continue. 

After I have installed Gekko directly on Windows 10, and could not use Talib, I have observed the steps from here :https://gekko.wizb.it/docs/installation/installing_gekko_on_windows_with_bash_on_windows_10.html. 

So I got through them, I could not install the gekko at the begining, but finally I could install it.
And after folowing the next steps: I could update the file and uninstalled the talib, but I cannot install talib@1.0.2. 
I have the next errors:
npm Err! Linux 4.4.0-43-Mircosoft
npm Err!  argv "usr/bin/nodejs" "/usr/bin/npm" "install" "talib@1.0.2"
npm Err!  node v4.2.6
npm Err! npm v 3.5.2
npm Err! path .../gekko/node_modules/.stagin/talib-a70ea0a6
npm Err! code EACCES
npm Err! errno -13
npm Err! syscall rename
and so on, I don't know how to copy paste the error description from Bash to Windows :))

**Comment by cmroche** [comment]
Oh I forgot to respond to this....

code EACCES

You don't have access to that file, a permissions issue? This might suggest that you've run npm with sudo at some point corrupting the setup.

In any case this problem is probably going to come down to your file system, try deleting the folder and restarting the setup.
