### ISSUE TITLE
Stop bots/processes & Labels

### ISSUE THREAD

**Issue by mechanicalfluff** [askmike/gekko#1276]
Just a few questions/feature ideas for some of the experienced folks in here ---

Is there a way to create labels for strat runners? Sort of 'comment' them in a way? 

(I've been doing it myself with inspect element and naming them temporarily so i don't forget which is which when i'm away). Maybe an ability to label the live strats if they're paper, or live bots.

Would there happen to be a way to cancel a live bot without having to ctrl-c out of the process; losing all the data?

sorry if this is the wrong place - if so, please let me know :)

**Comment by askmike** [comment]
This is exactly what is planned next! Though hard to find the time to work on this..

See more details here: #911

**Comment by mechanicalfluff** [comment]
Great! Wonder if there's a way to tooltip the "current strategy" code (rsi: 14/30/70/1) on each-- been working my way on trying to learn - maybe my self learning project once labels are in to reference from
