### ISSUE TITLE
No WebUI

### ISSUE THREAD

**Issue by ghost** [askmike/gekko#1284]
I'm submitting a
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Installed SSL and Login system from the tutorial on your site.

* **Expected result** (what you hoped would happen)
Working Gekko with ssl and login

* **Actual result** (unexpected outcome)
No webUI, Blank page, Showing page title as "Gekko" but nothing on the page itself

![screenshot_3](https://user-images.githubusercontent.com/22941699/32351392-80969dd4-c01d-11e7-8af9-24f87a44a972.png)

**Comment by askmike** [comment]
I have never seen these errors before. A lot of people (including me) are running the same setup successfully. 

Do you have access to another server?

**Comment by ghost** [comment]
Wha OS are you running? and in wich order do you install? SSL->Gekko->Login?

**Comment by ghost** [comment]
and yes i have

**Comment by ghost** [comment]
Solution: API_Host to 0.0.0.0
