### ISSUE TITLE
GUI, Backtesting does not complete, Random Duration

### ISSUE THREAD

**Issue by just-ak** [askmike/gekko#1285]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Backtesting 1 Minute for 3 Months Data.

* **Expected result** (what you hoped would happen)
3Months of data processed

* **Actual result** (unexpected outcome)
25,23,13 Days.  Random Timespan covered.

![wrong duration1](https://user-images.githubusercontent.com/3976536/32357172-cf3b2690-c06c-11e7-8d04-6582d449951b.png)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

I have worked through the problem, and created a simplified example of the  problem https://github.com/akentigernfox/node-child-process-fork .

I have worked through most of a fix and am testing it now.

**Comment by askmike** [comment]
Can you tell more about your OS, your computer (type of disk) and your strategy?

And could you explain what your solution changes? I only see 3 similar scripts that ping messages between a child/parent.

**Comment by just-ak** [comment]
Mike,  sorry I'm a bit slow. getting the code into it's own commit block and re-testing it.   I ended up with loads of comments everywhere and two other changes in the same commit so i'm splitting them up.

I'm running your gekko, on Digital Ocean Ubuntu 16 Droplet.  I have 3 users with 3 installs, trading 2 poloniex accounts.  BTC/VRC  BTC/VTC , and a Test Account.

Additional code pieces are for   
      1) UIConfig  put into home/.gecko/ so settings are different per user, and pull's don't affect it.
      2) Assigning the --inspect/--debug port for the child_process fork's.

**Comment by askmike** [comment]
> Assigning the --inspect/--debug port for the child_process fork's.

I don't use these tools haha.

Anyway the comments around the scripts you posted indicate windows, does this mean you have the same problem on both ubuntu and windows? And where were you able to implement a fix (also both platforms)?

**Comment by just-ak** [comment]
OK, reviewing on both Ubuntu & Windows.  

I've tidied up the example scripts,  I forgot the ``` to indicate the code blocks.   From going through the code, I think that the backtest  parent/child messaging is working as shown in Test2.   That because of it having console.log/log statements inside it.  The messaging appears to work correctly,  however if you where to remove all the console.log/log then the messaging would work as in Test1, and nearly all the messages are lost.

Working on testing a fix.

**Comment by just-ak** [comment]
Mike,
I've made up a change, and followed it through with the other core/workerts/..../parent & child  processes. To eliminate the possibilities of other lost messages between the parent/child when the child exits before the parent has managed to process everything.

https://github.com/just-ak/gekko/tree/chld-p-fork

## I've also made up:
### UIConfig to home folder
Putting UIconfig.js into separate config settings file  under the ~/.gecko/  folder.  (Tested Windows & Unix)  Although does not have merge for new properties yet.
https://github.com/just-ak/gekko/tree/uicfile

### node --inspect
Inspect / Debug ports, for Node.js Debugging through VisualSudio Code & Chrome
https://github.com/just-ak/gekko/tree/inspect-debug-ports

### Backtest Progress Bar
I am going to have a go at putting the import progress bar into the backtest screen now, since I've been looking around that area of code a lot, not to sure how successful I will be, as it's my first venture into web/vue.  It's a great project, and I have some extra time at the moment.

**Comment by askmike** [comment]
Could you point me in the direction of what you actually changed to fix your issue? I just see a bunch of commits with "No commit message": https://github.com/just-ak/gekko/commits/chld-p-fork

**Comment by just-ak** [comment]
Mike,  I've been running with my changes, and splitting off the code as much as I can.  I still have not managed to prove to myself that I have got the fix working across all the parent/child processes links,   and again last night I had a paper trader running, and it just exited after 8 hours.    
![image](https://user-images.githubusercontent.com/3976536/32593362-350eb9e0-c55a-11e7-98dd-ea0d965d62f5.png)

The idea is to stop the exit firing before the last message has actually arrived from the child.

1) Parent Starts Child, 
2) Child sends messages,  
3) Last message from child.  process.send("Backtest Finished")   (core/markets/backtest.js : 80) instead of process.exit();
4)  the Handler waits for the message and not the exit.  message==='Backtest Finished'  (core/workers/pipeline/messageHandlers/backtestHandler.js :26)  instead of exit.
5) Once the message is received, process the end details, then it sends the "Exit-Child" message to the child.
6) Child processes waits for Exit-Child message before exiting.  
7) If a child exit's without this then a problem has occurred.

I will keep trying to find the bug that I'm hitting with the process just stopping, as I think they are related.   I work UTC +7  from around 6am,  I've joined the discord group if you want to have a chat, about this problem.

When I've got the fix pinned down I will update some more.    I foolishly used git to move between my work area and the server, hence the commits without comments. (my bad)

**Comment by askmike** [comment]
@just-ak I am quite busy at the moment, will try to join the discord but no promises. But the screenshot you post is not about backtesting, but it's a live stratrunnner. It might be the same underlying issue (child process communication), but could you please limit your research / fixes to as much of an isolated problem as possible?

With this I mean, would you mind keeping your research and results limited like:

- stick to one specific OS where you can reproduce specific bugs, so please don't jump between windows and linux and have logs from both/either all over the "reproduce" repo.
- stick to one specific feature (preferably backtest, since that's super easy to reproduce), and don't jump between different features. The code surface for all these features is huge, we should try to isolate code that is causing the problem.
- try to create a test case where you can reproduce it based on the stable gekko release. If you play around with different Gekko instances run by different users with all their own uiconfig stored inside their own homefolder you are creating situations that I can never reproduce (unless that is literally the only way to reproduce this bug).

**Comment by askmike** [comment]
I am very thankful for all your hard work in research and going through all the code and testing everything out, but let's please do it in a way that we can all slowly get towards the bug and fix it :)

**Comment by askmike** [comment]
> I am going to have a go at putting the import progress bar into the backtest screen now, since I've been looking around that area of code a lot, not to sure how successful I will be, as it's my first venture into web/vue. It's a great project, and I have some extra time at the moment.

About this: currently there are two communication channels between the UI and the gekko server: a REST API and a websocket API. If you want to show a backtest progress bar we would have to move the backtest code over to the websocket API. Releated discussion: https://github.com/askmike/gekko/issues/744#issuecomment-301243317

**Comment by just-ak** [comment]
Yes the screen shot is from the live part, I have tested the backtesting bug and it 'appears' to be working correctly,  I ventured into the other parent/child sections to make sure that the fix I was proposing would work across each style.  I want to recommend a fix that works across the different styles of parent/child processes. It may take me a little longer but the result will be better.

**Comment by just-ak** [comment]
Working, on this random bug, which is todo with the parent/child relationship.  I think I have managed to narrow it down and get the consol.log propagated upwards to the parent nicely now.  But am a little unsure of what the error means, and if It is actually a fatal error.  does this EPIPE error make sense to you ?

```LOG      : 2017-11-10 11:13:26 (DEBUG): Trend:  nodirection  for  1
LOG      :   <-- POST /api/getCandles
LOG      : core/workers/loadCandes/Parent.js   About to Fork 9247
LOG      :   --> POST /api/getCandles 200 584ms 1.89kb
LOG      : loadCandles Child Exited
ERROR   : loadCandles had error{"code":"EPIPE","errno":"EPIPE","syscall":"write"}
"loadCandles had error{\"code\":\"EPIPE\",\"errno\":\"EPIPE\",\"syscall\":\"write\"}"
LOG      : 2017-11-10 11:13:42 (DEBUG): Requested BTC/USDT trade data from Poloniex ...
LOG      : 2017-11-10 11:13:42 (DEBUG): Processing 1 new trades. From 2017-11-10 04:13:34 UTC to 2017-11-10 04:13:34 UTC. (a few seconds)
LOG      : 2017-11-10 11:14:02 (DEBUG): Requested BTC/USDT trade data from Poloniex ...
```

**Comment by askmike** [comment]
in my experience most EPIPE errors have to do with you trying to pipe node output into something else, eg. `echo "AAA" | echo` but into something that does not support piping. But I don't know what you've changed and what you are trying to do. In your case it might have to do a misconfiguration between child/process IPC.

**Comment by just-ak** [comment]
Thanks, that was the pointer that was needed.  Just been running more tests. I've got a VPS Ubuntu 16 happily running 3 paper traders live,  and backtesting 3 months (BTC-VTC) of data consistently.  I will keep repeating to make sure the same results are being returned.
