### ISSUE TITLE
Command to install TULIB via terminal

### ISSUE THREAD

**Issue by DeBelserArne** [askmike/gekko#1286]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[X ] feature request
[ ] question about the decisions made in the repository

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

I know the command for installing talib is : npm install talib@1.0.2

But what is the command for TULIB(p)?

**Comment by generalectric** [comment]
sample-config.js tells us that it needs version 0.8.7 so it would be `npm i tulind@0.8.7`

    tulind: {
      enabled: true,
      version: '0.8.7'
    }

Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)

**Comment by askmike** [comment]
We should add this to the docs!
