### ISSUE TITLE
Telegram bot commands missing / prefix

### ISSUE THREAD

**Issue by uipko** [askmike/gekko#1297]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Sending commands to Telegram bot starting with a / like "/advice"

* **Expected result** (what you hoped would happen)
A response message with the advice.

* **Actual result** (unexpected outcome)
A message containing "Hello!". This is the default response when a command isn't regonized.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
The commands defined for the Telegram bot are missing the leading / . By convention Telegram bot commands start with a / .
Following this convention makes it possible to define a list of commands via Telegram BotFather. This command list results in an extra button to easily select a command instead of typing it every time.

Simple fix would be adding / to the commands in plugins/telegrambot.js like this:
```javascript
this.commands = {
  '/advice': 'emitAdvice',
  '/price': 'emitPrice',
  '/donate': 'emitDonation',
  '/real advice': 'emitRealAdvice',
  '/help': 'emitHelp'
};
```

**Comment by magicdude4eva** [comment]
Shouldn't "/real advice" be "/realadvice" - i.e. without the space

**Comment by greenbigfrog** [comment]
@magicdude4eva feel free to create a PR.
@cmroche this issue can be closed.
