### ISSUE TITLE
Sell when overbought and Buy when oversold for StochRSI?

### ISSUE THREAD

**Issue by John1231983** [askmike/gekko#1299]
* **I'm submitting a ...**
[ ] bug report
[v ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Sell when overbought and Buy when oversold

* **Expected result** (what you hoped would happen)

The image below shows the RSI clearly breaking above the 70 level resulting in an overbought reading, but we do not want to immediately sell because we do not know how far price could continue to rally. We want to wait until the RSI falls back below 70 and then place our sell trade. This gives us a better entry and a higher probability trade.
When the RSI falls below 30, same rules apply. We want to wait until the RSI crosses back above 30 before we place a buy trade.

* **Actual result** (unexpected outcome)
![image](https://user-images.githubusercontent.com/24875971/32540596-84fb0864-c4b0-11e7-9412-603e5d4c0f22.png)

How could I modify code in RSI or StochRSI? The current StochRSI just based on the low or high level. Thanks

**Comment by sandrodz** [comment]
Maybe this pseudocode will help:

```
let overbought = false;
if ( rsi > 70 ) { overbought = true; }
if ( rsi < 70 && overbought === true ) { sell; overbought = false; }
```

don't forget to share your strategy ^_^

**Comment by John1231983** [comment]
Thanks so much. How about opposite side? 
"When the RSI falls below 30, same rules apply. We want to wait until the RSI crosses back above 30 before we place a buy trade."

This is my current code based on your suggestion
https://gist.github.com/John1231983/13930f6af2f586a820c3e7e6e7a1b65b

**Comment by hmavrodiev** [comment]
Also do you know how to compare current stochrsi with the previous? With this you can avoid loss when you enter in Buy signal Stochrsi >20 but dont get sell signall. (Stochrsi never reach level 80, and get down again under 20). Also to calculate moving average of the Stochrsi ( to add smoothing K and D)

**Comment by uzielroy** [comment]
@John1231983 can you please upload the final version?

**Comment by okonon** [comment]
@john1231983 that would be nice

**Comment by thisisloze** [comment]
I think if you make it so that if you:

If ownCoin = 1 && moveCoin = 0 && overbought == true && rsiVal <= this.settings.thresholds.high
 {
moveCoin = 2;
ownCoin = 0;
lastLongPrice = 0;
overbought = false;
this.advice('short');
}

Ignore moveCoin and ownCoin. Its my own functions.

**Comment by Webunity** [comment]
There is a GIST here, but that doesn't work (yet) for me:
https://gist.githubusercontent.com/John1231983/13930f6af2f586a820c3e7e6e7a1b65b/raw/4d404a364dec4213c7baaa83e009466d26623669/RSI_customer.js

**Comment by gvdhoven** [comment]
I came to this, but it isn't ideal yet: https://gist.github.com/Webunity/04ce2a1a8cb34da726b9fd111db12717

It runs in the commandline but not in the web interface. Don't know why yet.

**Comment by mauroprojetos** [comment]
Friend ,
create file in  gekko/config/strategies/RSI-overbought.toml

interval = 14
[thresholds]
low = 30
high = 70
persistence = 1

**Comment by askmike** [comment]
Great stuff! If further questions come up please ask them [here on the forum](https://forum.gekko.wizb.it/forum-12.html).

**Comment by thisisloze** [comment]
None of these fixes really work.
