### ISSUE TITLE
Depencies error on my RaspberryPi (sqlite3)

### ISSUE THREAD

**Issue by doepat** [askmike/gekko#1304]
Hello,

on my win10 machine it always worked fine. now i wanted to setup also a raspberry pi. i encountered an error during dependencies install in regards to a package download of sqllite. since i am still a rookie - can i just use other sources? qhat's wrong here?

![image](https://user-images.githubusercontent.com/17652038/32605315-4eb20bee-c551-11e7-8385-37ffd9a25818.png)

edit: Tried to install sqlite3 manually. also with SUDO it failed?

![image](https://user-images.githubusercontent.com/17652038/32605816-40c1f77c-c553-11e7-9f17-06d1b8ca14bd.png)

this is also not helping :-/
 
sudo npm install --unsafe-perm --verbose -g sqlite3@3.1.4

this part looks better now

![image](https://user-images.githubusercontent.com/17652038/32606173-9626d6dc-c554-11e7-847b-41e1e701d7c0.png)

but....

![image](https://user-images.githubusercontent.com/17652038/32606131-5ecdbc00-c554-11e7-86c4-972720379f82.png)

**Comment by doepat** [comment]
this is also not helping :-/
 
sudo npm install --unsafe-perm --verbose -g sqlite3@3.1.4


this part looks better now

![image](https://user-images.githubusercontent.com/17652038/32606173-9626d6dc-c554-11e7-847b-41e1e701d7c0.png)

but....

![image](https://user-images.githubusercontent.com/17652038/32606131-5ecdbc00-c554-11e7-86c4-972720379f82.png)

**Comment by askmike** [comment]
Weird, it was working fine on my raspberry, I am traveling at the moment so cannot test. Could you try out some things suggested here? https://github.com/mapbox/node-sqlite3/issues/726

**Comment by klemensh** [comment]
Hi, I solved this on my raspberry by reinstalling sqlite3 via: sudo npm install sqlite3 --unsafe-perm
[source](https://forum.pimatic.org/topic/1824/solved-error-installing-sqlite3/2)

**Comment by askmike** [comment]
👍
