### ISSUE TITLE
import of data extremely slow

### ISSUE THREAD

**Issue by Lah123** [askmike/gekko#1305]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Importing data which these characteristics:
Market: bitfinex:USD/BTC

From:
2017-05-09 10:45:00
To:
2017-11-09 11:45:00

* **Expected result** (what you hoped would happen)
To import the data.

* **Actual result** (unexpected outcome)
I waited 2 hours and only got data for 3 hours up untill now. How can I speed things up?

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by Ali1** [comment]
Is it happening with other exchanges?

**Comment by cmroche** [comment]
@Lah123 This is a limitation of Bitfinex's API. They rate limit queries to about 1 query every 2.5 seconds and only return a max of 500 trades per query. Bitfinex also has immense volume compared to other exchanges when it comes to BTC and ETH. So yes, it is very normal that it takes several hours to import the amount of data you are requesting, and unfortunately there is not much we can do about it.
