### ISSUE TITLE
Feature request: Strategy parameters listed in individual drop downs

### ISSUE THREAD

**Issue by bryanbeck** [askmike/gekko#1308]
***I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository

I have been working on making some changes to the Gekko UI for my personal use,  I would like to have drop down menus to select the parameters for each individual strategy.  I am a novice with VUE but have some javascript experience so I was wondering if anyone would help point me in the right direction to accomplish this task.  

I found the strategies.js file and can see that this appears to be where the parameters are being written to the web app.

strat.params = yield fs.readFile(stratConfigPath + '/' + strat.name + '.toml', 'utf8'

Problem is I am not sure how to parse these individually and store them for later use.  Any help would be appreciated.  If there is anything I should be reading (or another forum I should be posting this in, please let me know). 

thanks for any help or advice

**Comment by askmike** [comment]
Right now TOML is used so users can adjust the parameters, in the next UI we will be moving away from that: strategies have to provide meta information including a javascript object containing the parameters. See this thread: https://forum.gekko.wizb.it/thread-57723.html

**Comment by askmike** [comment]
You can see a demo of the next UI here: https://app.gekkoplus.com/

**Comment by askmike** [comment]
(closing this out of inactivity but feel fee to comment).
