### ISSUE TITLE
Websocket throws 'not opened' error

### ISSUE THREAD

**Issue by maxgomes92** [askmike/gekko#1309]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Server running (develop branch) on Linode using docker.

* **Expected result** (what you hoped would happen)
To keep running until it is shut down.

* **Actual result** (unexpected outcome)
Once in a while Websocket throws the error below:

> gekko_1  | 2017-11-10T16:27:33.090153618Z /usr/src/app/node_modules/ws/lib/WebSocket.js:219
gekko_1  | 2017-11-10T16:27:33.090257685Z     else throw new Error('not opened');
gekko_1  | 2017-11-10T16:27:33.090268004Z          ^
gekko_1  | 2017-11-10T16:27:33.090273145Z
gekko_1  | 2017-11-10T16:27:33.090277599Z Error: not opened
gekko_1  | 2017-11-10T16:27:33.090282420Z     at WebSocket.send (/usr/src/app/node_modules/ws/lib/WebSocket.js:219:16)
gekko_1  | 2017-11-10T16:27:33.090287566Z     at _.each.client (/usr/src/app/web/server.js:30:22)
gekko_1  | 2017-11-10T16:27:33.090292367Z     at Function.forEach (/usr/src/app/node_modules/lodash/dist/lodash.js:3298:15)
gekko_1  | 2017-11-10T16:27:33.090297300Z     at data (/usr/src/app/web/server.js:28:5)
gekko_1  | 2017-11-10T16:27:33.090302162Z     at pipelineRunner (/usr/src/app/web/routes/startGekko.js:141:5)
gekko_1  | 2017-11-10T16:27:33.090306977Z     at Object.message.message (/usr/src/app/core/workers/pipeline/messageHandlers/realtimeHandler.js:15:9)
gekko_1  | 2017-11-10T16:27:33.090311892Z     at ChildProcess.<anonymous> (/usr/src/app/core/workers/pipeline/parent.js:21:12)
gekko_1  | 2017-11-10T16:27:33.090336371Z     at emitTwo (events.js:106:13)
gekko_1  | 2017-11-10T16:27:33.090343937Z     at ChildProcess.emit (events.js:191:7)
gekko_1  | 2017-11-10T16:27:33.090348796Z     at process.nextTick (internal/child_process.js:719:12)
gekko_1  | 2017-11-10T16:27:33.090373681Z     at _combinedTickCallback (internal/process/next_tick.js:67:7)
gekko_1  | 2017-11-10T16:27:33.090379758Z     at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by askmike** [comment]
What browser are you using?

**Comment by maxgomes92** [comment]
I'm sorry for taking too long.

Google Chrome latest version.

**Comment by askmike** [comment]
Hmm very strange, Gekko uses a normal websocket connection between the server and the web UI.

Are you very from away from where the sever is hosted? What kind of computer do you use?

**Comment by Gujs** [comment]
It happened to me also. After this error Gekko stopped working.

`/opt/gekko/node_modules/ws/lib/WebSocket.js:219
    else throw new Error('not opened');
         ^

Error: not opened
    at WebSocket.send (/opt/gekko/node_modules/ws/lib/WebSocket.js:219:16)
    at _.each.client (/opt/gekko/web/server.js:28:22)
    at Function.forEach (/opt/gekko/node_modules/lodash/dist/lodash.js:3298:15)
    at broadcast (/opt/gekko/web/server.js:26:5)
    at pipelineRunner (/opt/gekko/web/routes/startGekko.js:141:5)
    at Object.message (/opt/gekko/core/workers/pipeline/messageHandlers/realtimeHandler.js:15:9)
    at ChildProcess.<anonymous> (/opt/gekko/core/workers/pipeline/parent.js:29:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:787:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
`

**Comment by c0mrade69** [comment]
Any solution to this bug? Got it also in IE.

**Comment by turricum** [comment]
Raspian (newest version) with Raspberry 3. Access over SSH Tunnel. I have several Raspberries. After ~ 10 days and three live bots I have a restart of the UI today in one of my gekkos.

<snip syslog)
May  7 13:17:06 gekko-03 gekko[307]: /usr/local/gekko/gekko.20180424/node_modules/ws/lib/WebSocket.js:219
May  7 13:17:06 gekko-03 gekko[307]:     else throw new Error('not opened');
May  7 13:17:06 gekko-03 gekko[307]:          ^
May  7 13:17:06 gekko-03 gekko[307]: Error: not opened
May  7 13:17:06 gekko-03 gekko[307]:     at WebSocket.send (/usr/local/gekko/gekko.20180424/node_modules/ws/lib/WebSocket.js:219:16)
May  7 13:17:06 gekko-03 gekko[307]:     at _.each.client (/usr/local/gekko/gekko.20180424/web/server.js:28:22)
May  7 13:17:06 gekko-03 gekko[307]:     at Function.forEach (/usr/local/gekko/gekko.20180424/node_modules/lodash/dist/lodash.js:3298:15)
May  7 13:17:06 gekko-03 gekko[307]:     at broadcast (/usr/local/gekko/gekko.20180424/web/server.js:26:5)
May  7 13:17:06 gekko-03 gekko[307]:     at pipelineRunner (/usr/local/gekko/gekko.20180424/web/routes/startGekko.js:141:5)
May  7 13:17:06 gekko-03 gekko[307]:     at Object.message (/usr/local/gekko/gekko.20180424/core/workers/pipeline/messageHandlers/realtimeHandler.js:15:9)
May  7 13:17:06 gekko-03 gekko[307]:     at ChildProcess.<anonymous> (/usr/local/gekko/gekko.20180424/core/workers/pipeline/parent.js:29:12)
May  7 13:17:06 gekko-03 gekko[307]:     at ChildProcess.emit (events.js:180:13)
May  7 13:17:06 gekko-03 gekko[307]:     at emit (internal/child_process.js:783:12)
May  7 13:17:06 gekko-03 gekko[307]:     at process._tickCallback (internal/process/next_tick.js:178:19)
May  7 13:17:06 gekko-03 systemd[1]: gekko.service: Main process exited, code=exited, status=1/FAILURE
May  7 13:17:06 gekko-03 systemd[1]: gekko.service: Unit entered failed state.
May  7 13:17:06 gekko-03 systemd[1]: gekko.service: Failed with result 'exit-code'.
May  7 13:17:16 gekko-03 systemd[1]: gekko.service: Service hold-off time over, scheduling restart.
May  7 13:17:16 gekko-03 systemd[1]: Stopped gekko.service.
May  7 13:17:16 gekko-03 systemd[1]: Started gekko.service.
</snap syslog>

Maybe i switch now to CLI ..

**Comment by askmike** [comment]
fixed in latest develop!
