### ISSUE TITLE
Which strategy determine buy and sell signal? 

### ISSUE THREAD

**Issue by John1231983** [askmike/gekko#1310]
Hello all, we have many strategies that implemented in gekko. I want to know which strategy can determine the buy or sell signal. Could you suggest to me?

The reason is that I want to make a better decision. Even a signal below the middle BB, if it is selling signal, then it is better to sell, and otherwise, if it is buying signal, then it is better to buy.

**Comment by askmike** [comment]
The only thing any strategy can do in Gekko is (try to) determine buy and sell signals.

Which ones work well depends on a lot of factors: the timescale you run it on (candle size), type of market, type of trend. I would suggest using the backtester to simulate running different strategies over different markets. You can see an example in the installation video here: https://youtu.be/R68IwVujju8

As for a discussion about good strategies, see here: #610.

**Comment by askmike** [comment]
Though Gekko is aimed to be a tool for people familiar with automated strategies and TA, it's not an completely automatic bot that you can turn on and it will make money for you.
