### ISSUE TITLE
SQLITE_BUSY: database is locked

### ISSUE THREAD

**Issue by phr34k0** [askmike/gekko#1320]
> events.js:183
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: SQLITE_BUSY: database is locked
> RECEIVED ERROR IN GEKKO 179687258670191
> Child process has died.

Looking at past issues, seems no one came to any conclusion of fixing this matter https://github.com/askmike/gekko/issues/1290

- What kind of system (computer, SSD, server, etc)?
Sager NP8672 / Clevo P670SG Laptop. http://forum.notebookreview.com/threads/official-sager-np8671-clevo-p670se-sager-np8672-clevo-p670sg-owners-lounge.766559/

- What markets where you watching?
POLONIEX USDT/BTC

- What OS?
Windows x64 Pro

- Were you doing other things at the same time (backtest / import)?

No, just 1 instance of live Gekko trading which by default starts both process of Market watcher and Strat runner

***Action taken** (what you did)

Restart Market Watcher? Or should I CTRL+C on the terminal running node gekko --ui and restart live Gekko all over again? Isn't there a way like implementing , if busy; try/catch exception; insert delay; try again? Now my worry is does the bot even "remember" the last thing it did.

Any ideas on what's the best method on handling such errors in the future?

--------------------------------------

**Comment by tomand285** [comment]
Databased locked sounds to me like some other part of the program is also using the data and SQLITE has a lock or mutex that is preventing the 2nd write/read attempt to the DB until the 1st releases the lock. If you are trading then we will have 2 processes that will access the DB and I would recommend trying to add our own lock and just wait until our lock gets released before the 2nd program will access.

**Comment by phr34k0** [comment]
Maybe I give that WAL to DEL change a try 

![image](https://user-images.githubusercontent.com/13272249/32763849-323e63d2-c93d-11e7-906c-7d0cab4b3481.png)

References /sample-config.js and /plugins/sqlite/handle.js

**Comment by askmike** [comment]
ping @thegamecat

**Comment by thegamecat** [comment]
Typically happens when multiple requests are hitting the same sqlitedb. 

I've moved to postgresql now  because it seems to allow way more flexibility.

**Comment by phr34k0** [comment]
Hmm. Weird. I just set it up as normal on Windows following the documentation (https://gekko.wizb.it/docs/installation/installing_gekko_on_windows.html) and started 1 bot instance as per default. Have not had any problems on Windows after changing WAL to DELETE in line 52

> db.run("PRAGMA journal_mode = DELETE");

How do you switch to postgresql instead of them default sqlite in --ui mode? Edit the general.toml in config folder?

**Comment by thegamecat** [comment]
web/vue/UIconfig.js
and
web/routes/baseconfig.js

**Comment by phr34k0** [comment]
@thegamecat Thanks guys! Hope this helps somebody else too!

**Comment by Jamyye** [comment]
I am getting this same error. Have not found a workaround yet. @thegamecat can you give me a brief tutorial on how you switched to postgresql?

**Comment by phr34k0** [comment]
@Jamyye https://github.com/askmike/gekko/issues/1320#issuecomment-344148626

**Comment by phr34k0** [comment]
Change that config adapter to postgres if u plan to use it

**Comment by 123qweas** [comment]
I had the same problem. The reason was that I had the exchange website open in the background...
Took quite a while for me to realise that this was the problem multiple requests.
