### ISSUE TITLE
Error with no code.

### ISSUE THREAD

**Issue by dem1g0d** [askmike/gekko#1333]
Getting an error with no explanation.

Sorry for the noob question but I try to start a live tradebot and after initializing gekko pops an error, but there is no error code or explanation. any ideas?

**Comment by dem1g0d** [comment]
nvm found the error, gekko was unable to set the portfolio. how to fix?

**Comment by askmike** [comment]
Delete your API keys and generate new ones.

**Comment by jnorthrup** [comment]
this does not resolve cci on poloniex.  the api keys persist beyond redis purge and reinstall where is the db on ubuntu?
