### ISSUE TITLE
algos on order depth..

### ISSUE THREAD

**Issue by klh** [askmike/gekko#1337]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[x ] feature request
[ ] question about the decisions made in the repository

Is there any possibilities of adding other than candle data to both backtesting and trading.

For instance watching depth on Book orders and comparing the weight of the top 10 positions in dollar amounts etc. for a trend indicator.
?

**Comment by askmike** [comment]
The book is very interesting, however dealing with book data is very hard:

- Gekko aims to behave 100% the same in simulation environments as over the live market. The amount of bandwith required to stream all orderbook data & the amount of space to store it all on disk are extreme compared to what Gekko is storing now (only minutely candles).
- The type of strategies Gekko is designed for (slow trendwatching or momentum reversal) look more at marco patterns and ignore low level noise like the orderbook and market micro structures.
- Right now all data is transformed into minutely candles, as soon as you want to do something with the orderbook you probably want to change this as well (to per trade ticks for example). Right now Gekko cannot even react realtime.

Unfortunately this is out of scope for Gekko. Read more about some of Gekko's current limitations which make this hard / unfeasible: https://gekko.wizb.it/docs/introduction/scope.html
