### ISSUE TITLE
Help for the beginners / Scalping bot set up

### ISSUE THREAD

**Issue by regandunstan** [askmike/gekko#1343]
Hi, 

Please delete this post if it isn't allowed here. 

I'm pretty new to Gekko and I'm slowly learning a little more each day :) I've just been playing around with different parameters using the RSI & MACD indicators, but haven't really had any great success. I'm just using the UI as I have no coding experience what so ever. 

A lot of the time I'm only getting 5% profits over the back testing period when I could have easily just bought and held for say 40% profits. Looking at my back testing results the buys / sells are quite sporadic. Buys are at price peaks and sells are followed shortly after when they could have let it run a little longer. See image below (data was for 17/NOV - 19/NOV using NEO/USD).

![capture](https://user-images.githubusercontent.com/33804343/32990816-f70b39b0-cd7f-11e7-9209-2d68df27fc3f.JPG)

Can anyone please post a few indicators & parameters they have been using with some success to point me in the right direction? My ideal plan would be to run a scalping bot, buying after the price increases a little and selling after it has peaked. Rinse and repeat. This should return a lot more than what the market would. 

I also believe that for a bot to be successful, shouldn't it be earning more percentage for the back testing period than what the market earns (such as buying and holding for that period). What percentage profits are you getting? 

Any information on this would be greatly appreciated. 

Thank you!

**Comment by thegamecat** [comment]
In my opinion at least Gekko should be treated as a framework to allow you to study and write combinations of indicators. It's why I don't believe there is a place for the UI until such time as it outputs graphs similar to tradingview. 

To get the most out of it, take a look at how to write your own strategy using the built in indicators, and then look at writing your own.

Gekko is a great tool. But you do need to treat it as such.

**Comment by dem1g0d** [comment]
Does anybody have any parameter recommendations for someone with a little amount of USDT to trade against XRP?

**Comment by regandunstan** [comment]
Or does anyone have any code at all they wish to share? Would be good to get a bit of a forum going to help each other out. 

Not asking to be handed working strategies, but would be good to get some support for the beginners :)

**Comment by chemica** [comment]
People in general seem to guard successful strategies. The reason is obvious: if everyone knows it, it stops working.

**Comment by askmike** [comment]
We might add a forum at some point, a huge number of people are asking for it.

**Comment by meidays** [comment]
Scalping bot set up PLZ~
