### ISSUE TITLE
Docker headless install with --config

### ISSUE THREAD

**Issue by blastbeng** [askmike/gekko#1352]
Hello,
i am new to Gekko, and i'm having some trouble installing it with npm, 
i finally ended with a successful install using docker but i have some questions

i want to run gekko headless, without --ui, but just by specifying my conf.js , how to do that using the docker install ? I haven't found the .sh or the config where the startup command is specified for docker installation

Thanks

**Comment by askmike** [comment]
ping @DeviaVir

**Comment by DeviaVir** [comment]
@blast1987 docker simply uses `npm start`, which refers to the command here https://github.com/askmike/gekko/blob/stable/package.json#L14

If you change that and rebuild + restart your dockers you'll see it is using your changed version.
