### ISSUE TITLE
data + indicator to csv

### ISSUE THREAD

**Issue by AntiLopa** [askmike/gekko#1358]
Been working on writing RNN for stock prediction. Now I'm looking for valid stock data source and indicators data..
Gekko looks like good platform to get the data and the indicators.
I've been playing a bit with gekko, the stock data is easy enough to get..

My question is there a way to run few indicators simultaneously and output its tick/candle result with the tick/candle data itself into csv file or any other file/db?

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ x] question about the decisions made in the repository

* **Action taken** (what you did)
There is the backtest flag which 

* **Expected result** (what you hoped would happen)
csv file / db rows with indicators data per tick/candle

**Comment by thegamecat** [comment]
Come to the discord channel (https://discord.gg/26wMygt) and message me (.zuki!).

**Comment by askmike** [comment]
On top of that: I am working on the flow of events between different plugins in the pipeline. Very soon[tm] you can create a tiny [plugin](https://gekko.wizb.it/docs/extending/add_a_plugin.html) that listens to these events and logs them to CSV.

**Comment by thegamecat** [comment]
This is one way of writing csvs for now:
http://gekkowarez.com/adding-all-gekko-backtest-tick-data-and-indicators-to-csv/

**Comment by H256** [comment]
@askmike will it be possible to get this data from within th UI client? (websocket-events) This could be used to do live-charting during a backtest or on trading. :)

**Comment by askmike** [comment]
Yes, I am working on exposing all that data, see #1850 for details.
