### ISSUE TITLE
Gekko UI with postgresql

### ISSUE THREAD

**Issue by blastbeng** [askmike/gekko#1361]
Hello,
i am currently and succesfully running gekko in background mode using postgresql as DB

Now i want to be able to run gekko with --ui option with postgresql and not sqlite, how should i configure it? I found nothing in the docs

do i need to add the adapter and postgresql config to web/vue/UIConfig.js?

I tried adding this but it's not working:

> adapter = 'postgresql';
postgresql: {
    path: 'plugins/postgresql',
    version: 0.1,
    connectionString: 'postgres://user:pw@localhost:5432',
    database: 'db',
    schema: 'public',
    dependencies: [{
      module: 'pg',
      version: '6.1.0'
    }]
  }

**Comment by hmavrodiev** [comment]
you have to type : npm install pg
 in gekko folder

**Comment by hmavrodiev** [comment]
Edit \web\vueUIconfig.js 
set adapter

**Comment by hmavrodiev** [comment]
\web\routes\baseconfig.js


  // Postgres adapter example config (please note: requires postgres >= 9.5):
config.postgresql = {
  path: 'plugins/postgresql',
  version: 0.1,
  connectionString: 'postgres://YOURUSERNAME HERE:PASSWORD HERE@localhost:5432', // if default port
  database: 'gekko', // if set, we'll put all tables into a single database.
  schema: 'public',
  dependencies: [{
    module: 'pg',
    version: '6.1.0'
  }]

**Comment by blastbeng** [comment]
Done thanks! you're my hero!

**Comment by jfima** [comment]
very important info. Thanks guys!
It would be nice if someone added this information to the documentation.

I do not see the difference between the --ui mode and
gekko/config / general.toml
gekko/config/adapters/postgresql.toml
in which case these settings files are used?
