### ISSUE TITLE
The importer stops at 1.59%

### ISSUE THREAD

**Issue by focamonca** [askmike/gekko#1367]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** 
If I go to the importer, it doesn't matter what date to date I put, It will stops at 1.59%

* **Expected result** 

It fetchs the datas..

* **Actual result** (unexpected outcome)
stucked at 1.59%

**Comment by cmroche** [comment]
Which exchange and currency pair? What output, if any, is in the log. And can you try rerunning the import with debug logging enabled.

**Comment by cmroche** [comment]
Well since I am unsure which exchange you are trying to use:

If it is kraken PR #1396 should fix this
If it is GDAX PR #1397 should fix this

If you do sync the develop branch and merge the PR please let me know if it addresses your issue.

:)

**Comment by askmike** [comment]
assuming this is fixed.
