### ISSUE TITLE
Google Cloud Deployment not working

### ISSUE THREAD

**Issue by kitkat14** [askmike/gekko#1371]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Deployed docker to Google Cloud App Engine with the following config.ui

```
const CONFIG = {
  headless: true,
  api: {
    host: '0.0.0.0',
    port: 3000,
    timeout: 120000 // 2 minutes
  },
  ui: {
    ssl: true,
    host: 'example.appspot.com',
    port: 443,
    path: '/'
  },
  adapter: 'sqlite'
}

if(typeof window === 'undefined')
  module.exports = CONFIG;
else
  window.CONFIG = CONFIG;
```

* **Actual result** (unexpected outcome)
UI works but it shows a dialog stating:

_Disconnected
Something happened to either Gekko or the connection. Please check the terminal where Gekko is running or your network connection._

```
**console.log:**
webSocket connection to 'wss://example.appspot.com/api/' failed: Error during WebSocket handshake: Unexpected response code: 501
```

In the network tab in chrome I can see the api call
 
```
Request URL:wss://example.appspot.com/api/
Request Method:GET
Status Code:501 Not Implemented

```

**Comment by cmroche** [comment]
Your API is configured on port 3000, but your secure websocket is trying to connect on port 443 in the console log. Looking at the source, the API settings are for the server to listen, and the UI settings are for the web to establish a connection to the server, the port number in these two configurations should match in that case.

Try changing API.port to 443, that might do it.

**Comment by kitkat14** [comment]
@cmroche thanks for your reply. After updating it to port 443 even the UI is not showing up anymore and I am getting a 502 Bad Gateway
