### ISSUE TITLE
Problem importing backtesting data

### ISSUE THREAD

**Issue by stece** [askmike/gekko#1373]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[* ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Clean install of Gekko on Windows 10 following the tutorial on the documentation page

* **Expected result** (what you hoped would happen)
Importing backtesting dataset. Would expect data to be imported correctly.
I was importing GDAX dataset for EUR-ETH.
Date range 1st november until 28th november

* **Actual result** (unexpected outcome)
Application acts as if importing data, but nothing actually is. After the progressbar I can't find "installed" datasets. During import I see following errors in batch:

> Error: SQLITE_IOERR: disk I/O error
>     at Error (native)
>   --> POST /api/scansets 200 815ms 82b
>   <-- POST /api/import

> Error: SQLITE_IOERR: disk I/O error
>     at Error (native)
> { Error: SQLITE_IOERR: disk I/O error
>     at Error (native) errno: 10, code: 'SQLITE_IOERR' }
>   --> POST /api/scansets 200 822ms 133b

also:

> Import 8516125173072542 started
>   --> POST /api/import 200 62ms 146b
>   <-- GET /api/configPart/performanceAnalyzer
>   --> GET /api/configPart/performanceAnalyzer 200 4ms 144b
>   <-- GET /api/strategies
>   <-- GET /api/configPart/paperTrader
>   --> GET /api/configPart/paperTrader 200 2ms 132b
>   --> GET /api/strategies 200 17ms 1.76kb
>   <-- POST /api/scansets
>   xxx POST /api/scansets 500 18ms -

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
Not that I know could be relevant. If more information is needed, I can provide.

**Comment by stece** [comment]
I notice that during boot of Gekko I get an exception, I don't know if it's related:

```
TAlib is enabled
TULIP indicators is enabled
Serving Gekko UI on http://localhost:3000/

**(node:128) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Exited with code 3**
  <-- GET /api/imports
  --> GET /api/imports 200 4ms 2b
  <-- GET /api/gekkos
  --> GET /api/gekkos 200 1ms 2b
  <-- GET /api/gekkos
  --> GET /api/gekkos 200 2ms 2b
  <-- GET /api/exchanges
  <-- GET /api/apiKeys
  --> GET /api/apiKeys 200 2ms 2b
  --> GET /api/exchanges 200 2,691ms 60.95kb
```

**Comment by stece** [comment]
On the UI I now see the warning that some datasets were not found.
![capture](https://user-images.githubusercontent.com/419559/33331500-12726d48-d462-11e7-8c94-5d1399042f38.PNG)

**Comment by stece** [comment]
I also tried to do a chmod 777 on the entire Gekko folder in order to rule out permissions. It did not solve my issue. Currently out of ideas and potential input.

**Comment by patjk** [comment]
Having the same issue.

**Comment by stece** [comment]
@patjk  seems to be duplicate of: https://github.com/askmike/gekko/issues/1375

**Comment by stece** [comment]
duplicate of: #1375 I will close this one.
