### ISSUE TITLE
Data importing fails over and over again.

### ISSUE THREAD

**Issue by jasurakk** [askmike/gekko#1374]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Trying to import BTC-LTC data from for a few different 4 month time periods. Repeated a dozen times with different time periods, and from all possible BTC-LTC exchanges.

* **Expected result** (what you hoped would happen)
To get data for 4 months time period.

* **Actual result** (unexpected outcome)
Sometimes importing does not start at all, sometimes I get data just for few days or weeks and then the importer stops. No errors on a screen.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
Latest Gekko + Windows 10.

**Comment by rkostevka** [comment]
I have the same issue. Importing doesn't work from poloniex for me.

**Comment by jasurakk** [comment]
There seems to be many users having problems with data importing currently, with all exchanges. Is there anything I could do to help solving this problem? Any logs, debug information somewhere etc.?

**Comment by rkostevka** [comment]
IMPORT ERROR: Child process has died.

**Comment by rkostevka** [comment]
Error: SQLITE_BUSY: database is locked
RECEIVED ERROR IN IMPORT 18736884981060076
Child process has died.

**Comment by jasurakk** [comment]
Could anyone help with this?? It's quite frustrating that I cannot do anything with Gekko since I cannot get the data to test with :-(

Rkostevka; where exactly did you find those messages?

**Comment by LooOOooM** [comment]
import does not work for me at all -- at least not from command line plz fix. Import seems to happen but DB gets not created, nor writen too

**Comment by jasurakk** [comment]
Actually, now that I tried once again, all imports from Poloniex seem to work just fine! :-o  But all other exchanges fail every time with every pair.

**Comment by vincent-vermeulen** [comment]
I'm very new to this. I'm running bash on windows 10. The manual says you should change WAL to DEL in handle.js , however, I found the solution in changing to DEL as described in "add journalmode to sqlite plugin config #1185"  in sample-config.js with nano sample-config.js
