### ISSUE TITLE
How to import new strategies? Fork it!

### ISSUE THREAD

**Issue by AidasK** [askmike/gekko#1379]
The issue is, that if you want to create your own strategy, you have to fork it, make the changes and push them to your own repo. But what if I want to pull the newest changes from the original repo? As we can see, there are more than 1182 forks for 3571 stars and its a lot IMO.
 
Some solutions that came to mind:
1. Allow to upload a strategy through the UI. It is the simplest, because you can clone the repo on your own server without forking it.
2. Allow to load strategies from an external location. This way I could create a repo with my own strategies and just point to its location.

Currently, if you want to add a strategy, you have to:
1. Create a .js file at plugins/strategies/....js
2. Create a config file at config/strategies/...toml
3. Add strategy default params to config.js file

**Comment by krebbi** [comment]
or new stategies have to be placed in /strategies/custom/ and this directory is listet in gitignore?

also all the config-files (/web/vue/UIconfig.js and others) should be listet in gitignore. otherwise you can never do a git pull without killing your settings.

**Comment by cvasiliu2001** [comment]
Small (and silly) question: It is enough to create a new <strategy>.js file in strategy director and to add the <strategy>.toml file into the config directory? I have did already that (also by copying an already existing strategy and the new strategy is not shown in gekoo interface... Am I missing someting?

**Comment by askmike** [comment]
This better belongs in the forum, but a quick note:

You can create your own files inside the strategy directory, and when updating Gekko they won't be overwritten.
