### ISSUE TITLE
I have install gekko and I would like to be able to stop a live running strat using gekko UI.

### ISSUE THREAD

**Issue by Shootle** [askmike/gekko#1384]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)

* **Expected result** (what you hoped would happen)

* **Actual result** (unexpected outcome)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by Shootle** [comment]
I s there any feature to stop a live running strat in gekko using the UI without shutting down gekko?

**Comment by cometbus** [comment]
From what I've read it hasn't been implemented, just stop the process and reboot to clear the list.

**Comment by Shootle** [comment]
@commetbus ok, thanks

**Comment by Shootle** [comment]
I think is an important feature to have in gekko in order to stop loss when doing live trade because of the volatility of the market

**Comment by Shootle** [comment]
Has anyone implemented this on their own, who can share with me?

**Comment by cometbus** [comment]
http://gekkowarez.com/how-to-put-a-stop-loss-into-your-gekko-strategy/
https://github.com/askmike/gekko/issues/550

**Comment by cometbus** [comment]
https://github.com/askmike/gekko/issues/550

**Comment by jfima** [comment]
Do you know how to stop a running strat through the command line?
without shutting down gekko --ui process

**Comment by askmike** [comment]
@jfima @Shootle stopping a running Gekko via the interface will be part of the next release. See #911.
