### ISSUE TITLE
No Auto-Trade on Bitfinex?

### ISSUE THREAD

**Issue by sarperhorata** [askmike/gekko#1385]
Discord link is not working, hence I'm providing my problem here below.

I have set up the config for tradebot; changed the config files as asked, however, there is no trade even though there are enough balance at my bitfinex account (there is 0,1 BTC, almost no usd balance)

Can you please check and let me know what is wrong?

![33234332-0a7d0dba-d236-11e7-8e09-1e12eece4fce](https://user-images.githubusercontent.com/21296738/33422249-1cfaa798-d5c6-11e7-8d27-30df5bf520cf.png)

**Comment by HaziqDan** [comment]
I have same problem
I did set candle size with 3 hours and warm up period with 24 hours.
After 3 days, trade bot did not any trade.

**Comment by ms121** [comment]
Mine is working fine, take a look at your tradebot logs within the gekko/logs section it should be able to tell you what is happening. It will most likely have an error like this one - 03:06:31 (ERROR):	Wanted to buy USD but the amount is too small (0.000057732210) at Bitfinex. Without further info it is hard to tell why your bot is not trading.

Also make sure you have given the correct Bitfinex API permissions.

If you are using a config and understand that Gekko only automates your own trading strategies chenge the following to true  config['I understand that Gekko only automates MY OWN trading strategies'] = true;

**Comment by sarperhorata** [comment]
Hello,

Thank you for the feedback. It seems that it wants to buy first, although there are 0,09 BTC in the balance but no USD.

2017-11-25 00:29:36 (ERROR):	Wanted to buy BTC but the amount is too small (0.000014116509) at Bitfinex
2017-12-01 11:29:29 (ERROR):	Wanted to buy BTC but the amount is too small (0.000011634454) at Bitfinex

Would there be both BTC and USD balances at the same time for optimum performance?
@askmike would it be great if selling is the first option in such cases, to be able to buy in the next move?

**Comment by askmike** [comment]
@sarperhorata your strategy is responsible for signaling either LONG or SHORT. If the strategy signals a LONG and you don't have euro it will simply not buy this signal. This doesn't matter at all, because after the buy a sell will come (depending on the strategy) to which Gekko will sell.

Your logs indicate 2 errors where Gekko tried to buy but couldn't, is there a sell in between? There should be. Also let me know what strategy your using.

**Comment by sarperhorata** [comment]
Hello @askmike 
I'm using DEMA, with almost default settings. When I also deposited USD, it started working. 
But it is not showing it's second and third transactions on the Gekko UI. (SELL, SELL, BUY)
