### ISSUE TITLE
module.js:471 error

### ISSUE THREAD

**Issue by tridoan** [askmike/gekko#1389]
So im installing this on Digitalocean (with a domain name) and tried to start Gekko through the command line, but i get this error:

soduuser:/var/www/html/gekko$ node gekko --ui

    ______   ________  __    __  __    __   ______
   /      \ /        |/  |  /  |/  |  /  | /      \
  /$$$$$$  |$$$$$$$$/ $$ | /$$/ $$ | /$$/ /$$$$$$  |
  $$ | _$$/ $$ |__    $$ |/$$/  $$ |/$$/  $$ |  $$ |
  $$ |/    |$$    |   $$  $$<   $$  $$<   $$ |  $$ |
  $$ |$$$$ |$$$$$/    $$$$$  \  $$$$$  \  $$ |  $$ |
  $$ \__$$ |$$ |_____ $$ |$$  \ $$ |$$  \ $$ \__$$ |
  $$    $$/ $$       |$$ | $$  |$$ | $$  |$$    $$/
   $$$$$$/  $$$$$$$$/ $$/   $$/ $$/   $$/  $$$$$$/

module.js:471
    throw err;
    ^
Error: Cannot find module 'moment'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/html/gekko/core/util.js:1:76)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

I have PM2 setup, and after i start the gekko process, a few minutes later the status says error.

Any idea what this could be? Let me know what info you need to help, i can provide it...
thanks!!

**Comment by askmike** [comment]
you need to install gekko's dependencies. Do this by running `npm install` in the Gekko directory :)

**Comment by tridoan** [comment]
I did do that, it was working for a little while until I enabled the http authentication

**Comment by askmike** [comment]
This error: `Error: Cannot find module 'moment'` has to do with Gekko not finding dependencies that should be installed after running `npm install`. Not sure what you mean with http authentication, do you mean using BasicAuth via nginx?

**Comment by tridoan** [comment]
hey @askmike , thanks for your response.

Hm, im pretty sure i installed all the dependencies with 'npm install --only=production', but i'll check and run it again.

Yes, http auth means the BasicAuth via nginx. Im a LAMP guy, so...
