### ISSUE TITLE
Telegram bot not sending advices

### ISSUE THREAD

**Issue by foux** [askmike/gekko#1390]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)

I've launched gekko with the command `node gekko.js --config config-bitcoin.js`

The Telegram config part is as follows : 
```
config.telegrambot = {
  enabled: true,
  emitUpdates: true,
  token: 'my_bot_token',
  botName: 'gekkobc_bot'
}
```

* **Expected result** (what you hoped would happen)

Gekko running and sendinc advices to my telegram account

* **Actual result** (unexpected outcome)

Gekko is running well, and giving me advices. But when a trading advice is printed on the console, it's not sent to my telegram.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

I don't quite understand how this could work. In any other Telegram associations I've set up on other programs, I've had to input my bot token, but also my own ID so that the bot knows to which user it has to send the message. How can this telegram bot know it has to send the message to me?

Thanks in advance!

**Comment by greenbigfrog** [comment]
It's not explained anywhere properly. Only found how to do it by doing some testing. Without knowing anything more about how telegram bots work, I think you have to tell them to `/start`.

To start getting updates, you'll have to send the bot `/start` after each time you restart the bot. (At least this is how it's been working for me)

**Comment by amaanr** [comment]
@greenbigfrog is there any way to send additional information with the advice? Say for example I wanted to send the price when the buy signal was made...?

I can't figure out how to send additional parameters from my strategy file to the Telegram bot (or any other plugin for that matter).
