### ISSUE TITLE
Is there any way to import data from Bitstamp for backtesting. I can not find this in Gekko UI

### ISSUE THREAD

**Issue by Shootle** [askmike/gekko#1391]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)

* **Expected result** (what you hoped would happen)

* **Actual result** (unexpected outcome)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by greenbigfrog** [comment]
If it isn't available as option in the imported, it's not possible.

**Comment by LooOOooM** [comment]
actually there is. 
http://gekkowarez.com/download-category/trading-data/

**Comment by askmike** [comment]
Gekko can import by automatically downloading historical trades from the exchange API, the problem is that some exchange like bitstamp do not offer historical trades via their API.

See here for more info: https://www.bitstamp.net/api/#transactions

**Comment by askmike** [comment]
@LooOOooM that works, but note that you are not downloading the trade data from an exchange but a third party.
