### ISSUE TITLE
Basic Trading Strategy Buy/Sell at a specific price

### ISSUE THREAD

**Issue by Gordoo** [askmike/gekko#1392]
Good Morning,

I discovered Gekko the last days. The problem is, I do not have any knowledge with Java. The point is, I need a very basic trading strategy. In the documentation is already an example for a strategy like described in the title. But you still need to add some code.

Would you help me with the code? I just need it very basic. No analysis just buy/sell at a specific price?

Is it possible to use the custom strategy in the UI?

Thank you

**Comment by askmike** [comment]
Note that if you want to buy at a price higher than the market price you can simply use limit orders directly at the exchange (I want to buy when the price hits 15,000). However if you want to buy after the price goes down that's another story (some exchanges support stop limit orders), you can use this strategy that buys once the price goes below 5,000.

    var strat = {};

    // don't need those:
    strat.init = function() {}
    strat.update = function(candle) {}

    strat.check = function(candle) {
      if(candle.close < 5000) {
        this.advice('long');
      }
    }

    module.exports = strat;

In this case it will keep advising to go long every candle (every 10 minute if you configured Gekko to use 10 minute candles). But Gekko won't act on any advice after the first one (until your strategy advices to go `short`, which the one above will never do). Unfortunately this is a technical issue tracker, not the best place to ask basic programming questions :(
