### ISSUE TITLE
two errors 

### ISSUE THREAD

**Issue by David202** [askmike/gekko#1402]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)fresh install didnt work then turned to others with issue followed steps from this post and corrected files Probably a duplicate of #1375 and #1373, sync the develop branch and try testing with Pull Request #1369.
files are on a empty ssd drive 

* **Expected result** (what you hoped would happen)
it would work 

* **Actual result** (unexpected outcome)
still getting same errors "events.js:160
                                                  Throw er; // Unhandled 'error' event"
and "Error: SQLITE_IOERR: disk i/o error at error native

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by David202** [comment]
also getting errors when using watcher 
-Error sqlite_ioerr: disk i/o error at error (native)
XXX post /api/getcandles 500 281ms
-error: non-error thrown: error unable to load candles, please check the console.
at object.onerror (/mnt/d/gekko/node_modules/koa/lib/context.js:105:40)
at process_tickcallback (internal/process/next_tick.js:109:7)

also error for child process has died 
forgot to mention this is running on bash windows 10 thanks for any help

**Comment by cmroche** [comment]
Did you delete the history files and re-import after applying the fixes?

**Comment by David202** [comment]
i deleted it after i will restart from beginning is there only one history folder that the files need to be deleted?

**Comment by cmroche** [comment]
You can specify the history folder in the config files, but assuming you didn't change this then there should only be the 1.

**Comment by David202** [comment]
ok thank you just got done fixing the files again deleted history files will try it now sorry a little new to this

**Comment by David202** [comment]
still same errors and it crashed with segmentation fault (core dumped) looks like it isnt going to work for me must be doing something wrong
