### ISSUE TITLE
Failed to access http://127.0.0.1:3000 with default docker-compose.yml

### ISSUE THREAD

**Issue by hysci** [askmike/gekko#1406]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[* ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
git clone the latest repo, and then run
docker-compose up

* **Expected result** (what you hoped would happen)
I can access 127.0.0.1:3000

* **Actual result** (unexpected outcome)
I got the following error:
Something happened to either Gekko or the connection. Please check the terminal where Gekko is running or your network connection.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
The terminal does not show anything error:

gekko_1  |      I'm gonna make you rich, Bud Fox. 
gekko_1  | 
gekko_1  | 
gekko_1  | TAlib is enabled
gekko_1  | TULIP indicators is enabled
gekko_1  | Serving Gekko UI on http://localhost:3000/
gekko_1  | 

I also tried another branch  "stable", it also did not work.

**Comment by cmroche** [comment]
What is the output of `docker --version` and `docker inspect gekko_gekko` assuming that is the name of the docker container you created.

**Comment by hysci** [comment]
[docker --version]
Docker version 17.09.0-ce, build afdb6d4

[docker inspect gekko_gekko]
[
    {
        "Id": "sha256:99ae23e39cce782981e55720165fb83d85bec63e50f603068c6805db266caa41",
        "RepoTags": [
            "gekko_gekko:latest"
        ],
        "RepoDigests": [],
        "Parent": "sha256:9f4a1ceadfcf7e2fa2db08fcde43c16dcd11b717e79999febb01afba99519ecb",
        "Comment": "",
        "Created": "2017-11-28T22:52:53.790570647Z",
        "Container": "4ec25403b63ee4bb0eac4b9cc279d3167eb34c1cb3fe2e8d2aeca7ed3833f39b",
        "ContainerConfig": {
            "Hostname": "2da0903ff372",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "3000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NPM_CONFIG_LOGLEVEL=info",
                "NODE_VERSION=6.3.1",
                "HOST=localhost",
                "PORT=3000"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "CMD [\"npm\" \"start\"]"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:9f4a1ceadfcf7e2fa2db08fcde43c16dcd11b717e79999febb01afba99519ecb",
            "Volumes": null,
            "WorkingDir": "/usr/src/app",
            "Entrypoint": [
                "/usr/src/app/docker-entrypoint.sh"
            ],
            "OnBuild": [],
            "Labels": {}
        },
        "DockerVersion": "17.09.0-ce",
        "Author": "",
        "Config": {
            "Hostname": "2da0903ff372",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "3000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NPM_CONFIG_LOGLEVEL=info",
                "NODE_VERSION=6.3.1",
                "HOST=localhost",
                "PORT=3000"
            ],
            "Cmd": [
                "npm",
                "start"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:9f4a1ceadfcf7e2fa2db08fcde43c16dcd11b717e79999febb01afba99519ecb",
            "Volumes": null,
            "WorkingDir": "/usr/src/app",
            "Entrypoint": [
                "/usr/src/app/docker-entrypoint.sh"
            ],
            "OnBuild": [],
            "Labels": {}
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 768077716,
        "VirtualSize": 768077716,
        "GraphDriver": {
            "Data": {
                "DeviceId": "3965",
                "DeviceName": "docker-253:6-2684573752-fbf2ab6192e485ce12abcf24fcae52d5af69e5996b4549928f174d7fe7d64c08",
                "DeviceSize": "10737418240"
            },
            "Name": "devicemapper"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:2f71b45e4e254ddceb187b1467f5471f0e14d7124ac2dd7fdd7ddbc76e13f0e5",
                "sha256:66d8e5ee400cb0660c8c0ad51d30d822365a995eb90d35750a1e641cae7c887c",
                "sha256:1050aff7cfff31f37ff91f26ebe8583521a9329da5a7d179400228551b1506cf",
                "sha256:04dc8c446a384974754388c0f906520e6f332d6d7afe0d3734a8feed7472a831",
                "sha256:80c332ac5101def4d5e0be589704ae16ddb5f3a2bf783c995e837ca9bfe44a08",
                "sha256:7156e1b76a3e8bf5757d53cbf409a09fc031d8d41462bfe7730b3d99cdb448e6",
                "sha256:d42304ba6267ebe61f66288406c018dfe70df818f60967711e196d5a858575be",
                "sha256:94acd9641c3f6d37f3582206a808c6902b87f40f402507bf194e5c15845426f6",
                "sha256:6da8615cce98665b7464a593f9d26ea42d4f9d89c043f9ca163afe3dd533fdfe",
                "sha256:78b772a0369ff84bc9fbf69f1c9fbedfdb4deb60d0a9766b3bcdd200673ddfac",
                "sha256:b72e2d807e1586c75a1e4c231b5672f5d542ec510ff468837ac31e032f56e79a",
                "sha256:173573a5e25da162ba1dba388915a128b9ce3162c17d34a27b558d514f8c13ea",
                "sha256:f1c0ce5fae3b5d49e279ecf59860d3db7aa675e444dfe2c39d6c8481b85aaf20",
                "sha256:81ad52c55bc0b4748d2aa52bb56ccc6a199ef00579664095bfe339f9c9a55331"
            ]
        },
        "Metadata": {
            "LastTagTime": "2017-11-29T06:52:57.946416477+08:00"
        }
    }
]

**Comment by cmroche** [comment]
It looks to be configured correctly, I think this is going to come down to a configuration issue on your PC that is potentially blocking to docker container from binding or being accessible on that port.

**Comment by hysci** [comment]
The port was accessible because:
1) I opened the port using the command:
sudo firewall-cmd --zone=public --add-port=3000/tcp --permanent
2) I have other tens of dockers using other ports, all of those dockers ran OK.

**Comment by hysci** [comment]
Besides, if the port was blocked, I should not be able to see that page showing "Something happened to either Gekko or the connection. Please check the terminal where Gekko is running or your network connection."

**Comment by askmike** [comment]
> Besides, if the port was blocked, I should not be able to see that page showing "Something happened to either Gekko or the connection.

You are right.

> Something happened to either Gekko or the connection. Please check the terminal where Gekko is running or your network connection.

This means Gekko is unable to setup a websocket connection, can you try navigating to `http://localhost:3000/api/gekkos` in your browser? If you see `[]` that means your browser can connect to the rest API (in this case something is preventing your browser from setting up a websocket connection). If you see something else please let us know (that means Gekko is not running properly).

**Comment by hysci** [comment]
I got the following page with several buttons:
JSON RawData Headers Save Copy,
When I clicked RawData, I got []
When I clicked Headers, I got: 

Access-Control-Allow-Methods | GET,HEAD,PUT,POST,DELETE
-- | --
Access-Control-Allow-Origin | *
Connection | keep-alive
Content-Length | 2
Content-Type | application/json; charset=utf-8
Date | Fri, 08 Dec 2017 11:11:28 GMT

**Comment by gdomod** [comment]
have same problems 
i have try it with external IP Adress but, no success because cant reach Error: listen EADDRNOTAVAIL:
`const CONFIG = {
  headless: true,
  api: {
    host: 'IPADDRESS',
....
  ui: {
    ssl: false,
    host: 'IPADDRESS',
...
}`
with Emtpy String I got full response, but white page ...
`const CONFIG = {
  headless: true,
  api: {
    host: '',
....
  ui: {
    ssl: false,
    host: '',
...
}`

with 0.0.0.0, i got html page but no access to /api and BAM disconnected
`const CONFIG = {
  headless: true,
  api: {
    host: '0.0.0.0',
....
  ui: {
    ssl: false,
    host: '0.0.0.0',
...
}`

**Comment by ne0c0de** [comment]
@gdomod did you find a solution to your problem?
