### ISSUE TITLE
Request to merge hedging clients for Bitstamp and Ripple

### ISSUE THREAD

**Issue by codedot** [askmike/gekko#141]
There are available two hedging bots: [one for Bitstamp](https://gist.github.com/codedot/7547987) and [one for Ripple](https://gist.github.com/codedot/7733540), the Ripple network being considered as another exchange for Bitcoin (among other currencies). This issue is to request them both to be adapted and merged into Gekko. Also, it would be good to modify the Bitstamp version such a way that the [observer program](https://gist.github.com/codedot/8201934) or similar software would not be able to easily identify a user's wallet using solely the public order book of Bistamp.

**Comment by askmike** [comment]
open for pulls, but closing as it's currently not an issue.
