### ISSUE TITLE
twitter+ detect percentage down

### ISSUE THREAD

**Issue by gelinger777** [askmike/gekko#1410]
Sorry for trivial question. 
I want to unserstand how to realize following approach(es)

1) Twitter stream or custom signal monitoring. 
I want to monitor  twitter timeline of a given account and in case any new tweet happens purchase given coin. And right after purchase happens I want to put a limit sell with buyPrice + X% to order book

2) I want to detect   price decrease of the coin to a given % in a last given time range. Lets say I want to detect if price has decreased 7% on last 5-10 candles (basically a big player has dumped  a big quantity of coins ) and step in and make a purchase. 

How to achieve those two things in gekko? Any hints to start with?

**Comment by askmike** [comment]
1. is really out of scope for Gekko, Gekko is focussed on TA strategies. You could hack this in, but it's a lot easier to start from scratch.
2. is very easy: just make a strategy that monitors the volume of candles, details can be found here: https://gekko.wizb.it/docs/strategies/creating_a_strategy.html

**Comment by Ali1** [comment]
@askmike I was think about something like this just today. Could Gekko check for the presence of a signal generated by an external program, for example by the presence of a file, after every candle and switch trading method if the signal exists? This way an external program can pass on a signal for a more bearish or bullish trading method by doing it's own social analysis for example.

**Comment by askmike** [comment]
This is not hard: you can code this in your strategy. However it means you
cannot ever backtest the strategy, at which point it does not make a lot of
sense to use gekko anymore.

**Comment by JasLin** [comment]
I have an idea that if the market is robotically trading, then the general trend of the stock price may be weakly related to the social media information, but a big change in the stock price may have a strong relationship with the social information, and I do not know Has anyone done any research on the correlation between the two?

**Comment by cryptokoningen** [comment]
In cryptotrading price is strongly related to social media. Mainly the pump and dump activity on telegram and the social buzz on twitter from OG traders and big data analysts.
It would be very nice to have an ability to read signals from these external sources. When ahead of the manual buyers there's an easy profit opportunity. Or maybe if Gekko could read from google doc spreadsheet to act as a intermediate. 
@askmike, thanks for Gekko, it's really cool.
