### ISSUE TITLE
live trading with Gekko UI

### ISSUE THREAD

**Issue by ghost** [askmike/gekko#1413]
- Gekko UI setting
I did config gekko bot using gekko UI for live trading.
Is this possible to trade real?
- My setting as follow
exchange : bitfinex.js
currency: USD
assets: BTC
type: tradebot
strategy: stochRSI.js
candle size: 4 hours
history size: 6
- I did run 3 days
but there is not any action in trade.
Could you help me?
Thanks

**Comment by yuripinto** [comment]
Yes, it's possible to trade real. You have to setup your strat runner as tradebot. 
You can try run a backtest using this setup over market watcher created with your gekko instance and see if there's something difference from your result.

**Comment by yuripinto** [comment]
Well.. I tried to use it with bitfinex under RSI alg this week and I got that same problem now.
 (running backtest with this market watcher, I got 6 trades). Maybe could be a bug or something about bitfinex.

**Comment by yuripinto** [comment]
@IllyaWeb ,
I got this error on tradebot log:

> Bitfinex did not provide BTC amount, assuming 0
> Bitfinex did not provide USD amount, assuming 0

Any ideas? I think it's all ok on bitfinex API keys permissions.

**Comment by yuripinto** [comment]
@IllyaWeb 
I moved my BTC amount to "exchange wallet" today on bitfinex and done! bitfinex trade js just look to this wallet.

**Comment by askmike** [comment]
On top of that, please post the logs as found in the `logs` folder.
