### ISSUE TITLE
typo @ core/tulind.js: 140 arronosc or aroonosc?

### ISSUE THREAD

**Issue by jmbartho** [askmike/gekko#1416]
typo @ core/tulind.js: 140 arronosc or aroonosc?

**Comment by cmroche** [comment]
https://tulipindicators.org/list

Should be aroonosc, good catch, pushing a fix.

**Comment by askmike** [comment]
This fix will be part of the next release, until then you can use the develop branch located here: https://github.com/askmike/gekko/tree/develop

**Comment by askmike** [comment]
Closing this already :)
