### ISSUE TITLE
Recovering from errors

### ISSUE THREAD

**Issue by VinceBT** [askmike/gekko#1424]
Right now Kraken suffers timeout issues and Gekko suffers trying to get the history data and call the API after that and throw an "irrecoverable error" and shuts the script.

Could it retry multiple times instead by waiting for a longer interval each time ?

**Comment by cmroche** [comment]
It doesn't wait for a longer interval each time. Retry in kraken is hard coded to 10 seconds, irrecoverable errors are not recoverable and so they don't retry, can you please indicate the whole error message so we can determine if that was designated correctly.

**Comment by VinceBT** [comment]
Everything goes well until the error "unable to get ticker {}" appears and then the script exits suddenly without any retry

**Comment by cmroche** [comment]
Are you the stable, or the develop branch?

**Comment by VinceBT** [comment]
I'm on the stable one, is it fixed in develop ?

**Comment by cmroche** [comment]
A lot of Kraken's issues are fixed in develop, and one hopefully final fix in the PR.

**Comment by VinceBT** [comment]
It's better in develop branch
