### ISSUE TITLE
Papertrader & Market Watched do not work through the UI (develop branch)

### ISSUE THREAD

**Issue by cmroche** [askmike/gekko#1429]
I found a bug this evening, changes to the buffering to improve import performance breaks papertrading when started from the UI due to the way the market leecher works.

I'm investigating a fix and should have something for tomorrow.

**Comment by greenbigfrog** [comment]
@cmroche you fixed this in #1428 ? In that case this could be closed.

**Comment by cmroche** [comment]
Forgot I opened this :)
