### ISSUE TITLE
Marketwatcher of poloniex not working

### ISSUE THREAD

**Issue by TonyStark** [askmike/gekko#1430]
Statistics is loading only. no performance/chart shown
![tmp](https://user-images.githubusercontent.com/5529450/33657450-6d234db4-da9f-11e7-94a3-f2b4d335a3ab.png)

**Comment by cmroche** [comment]
Duplicates #1429, and fixed in PR #1428

**Comment by TonyStark** [comment]
i tried both pull request [https://github.com/askmike/gekko/pull/1428/files/c6111627e21e5bf8ce6a9c163d4e66e5258cd040..65921892aa40a24498056d3efeafe97ddf42750d] 
[https://github.com/askmike/gekko/pull/1451/commits/8df8ba0c0259752edd3ec09dcc8f50f4953447de]
but still market watcher loading
