### ISSUE TITLE
Has anyone implemented ACX

### ISSUE THREAD

**Issue by felipecaldas** [askmike/gekko#1437]
Hi all,

This is not an issue, I am just wondering if anyone has implemented the ACX exchange in Gekko? I've been trying for the last 3 hours using the ccxt library, but I have not been lucky yet. Javascript is not my forté.

Currently getting the error:

```
                    let partial = async params => this[methodName] (url, type, uppercaseMethod, params || {})
                                        ^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
```

When starting up, so it makes me think I have not implemented one or more required functions for the functioning of this particular exchange.

Thanks all

**Comment by kroitor** [comment]
@felipecaldas hi! What's your Node version? Is it older than 8.* ? Update it then )

**Comment by felipecaldas** [comment]
Ohhhh! It's v6. 
What's the difference, if you don't mind asking? Thanks mate

**Comment by kroitor** [comment]
@felipecaldas v6 does not support modern async/await ES6 syntax, you should really upgrade it, because your version is outdated. Otherwise you will have trouble running newly designed code in it.

**Comment by felipecaldas** [comment]
Copy that sir, let me upgrade it now!

**Comment by felipecaldas** [comment]
Ta-da! It works now. Thanks @kroitor 
I don't think my `acx.js` file is going to work, but I will give it a go for a few more hours. Cheers !
