### ISSUE TITLE
[BUG] gekko backtesting will be Interrupted on random duration

### ISSUE THREAD

**Issue by howie50417** [askmike/gekko#1444]
If I select a long dataset for backtest,

It's hardly to run all dataset completely,

always finish on a few day backtest. (maybe few hours to a few days)

Is anyone else has the same problem?

How to fix that?

**Comment by austinlangdon** [comment]
Howie, there's a quickfix for this - increase node's memory limit. 

More info here
[http://gekkowarez.com/avoid-memory-issues-when-running-long-backtests/](http://gekkowarez.com/avoid-memory-issues-when-running-long-backtests/)

**Comment by howie50417** [comment]
@austinlangdon 
Many thanks again~
