### ISSUE TITLE
Gekko strategy not running on one year data UST/BTC

### ISSUE THREAD

**Issue by roneetshaw** [askmike/gekko#1447]
I have imported one year Bitcoin data from Poloniex and had implemented one of my custom strategy with 10 minutes candle but when I see the result and graph after back-testing completes, I see it doesn't runs on 1 year data but on 4-5 months of data and it also trades only at the beginning of the time-span after than it doesn't trade at all.
Dataset
![image](https://user-images.githubusercontent.com/19503905/33803841-30a4cad4-ddbf-11e7-9bbb-d575b248349c.png)

![image](https://user-images.githubusercontent.com/19503905/33803727-90399cfc-ddbc-11e7-9ffc-3699c5f0600a.png)

Also, In the roundtrips details I see only one trade has been executed but still my net return is showing over 40% up. I think there is a bug in calculating the profits
![image](https://user-images.githubusercontent.com/19503905/33803834-062c90b6-ddbf-11e7-8c94-4d623ea49379.png)

**Comment by askmike** [comment]
We recently fixed a bug that has to do with how Gekko communicates internally, that should fix this problem. The bug was fixed here: #1363.

If you download the latest version of Gekko (0.5.11, released 5 minutes ago) this should be fixed :)

If not please reopen.
