### ISSUE TITLE
GDAX Import Error 

### ISSUE THREAD

**Issue by blastbeng** [askmike/gekko#1450]
Hello,
i am trying to import GDAX ltc eur combo to do some backtesting but i get this error log...

`2017-12-10 12:30:19 (DEBUG):	Scanning backwards...2017-11-13T12:49:52.819Z
/home/user/gekko/exchanges/gdax.js:248
                if (moment.utc(last.time) < moment.utc(since)) {
                                    ^

TypeError: Cannot read property 'time' of undefined
    at Trader.<anonymous> (/home/blast/gekko/exchanges/gdax.js:248:37)
    at Request._callback (/home/blast/gekko/node_modules/gdax/lib/clients/public.js:45:7)
    at Request.self.callback (/home/blast/gekko/node_modules/gdax/node_modules/request/request.js:187:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/blast/gekko/node_modules/gdax/node_modules/request/request.js:1044:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/blast/gekko/node_modules/gdax/node_modules/request/request.js:965:12)
    at emitNone (events.js:111:20)
`

**Comment by BradzTech** [comment]
I am having the same issue with GDAX USD/BTC.

**Comment by austinlangdon** [comment]
Having this issue as well.

**Comment by dsbaha** [comment]
We're hitting a rate limit it seems.  I've put a bunch of "sleeper" statements around getProductTrades to confirm this.  Its working for me, but it is not optimal.

**Comment by PepeAnguita** [comment]
Not working for me either

**Comment by dsbaha** [comment]
Add the following in line 242 in exchanges/gdax.js

`if(_.last(data) == null) { 
  setTimeout(() => { 
    console.log("retrying...");
  }, 900); 
  return this.retry(this.getTrades, args);
}`

Then it works fine for me.

**Comment by blastbeng** [comment]
thanks, but this doesn't solve the problem.. it's the same as making the gekko import process loop forever until it finish,..... but in this case there's always an error and it always restart the import from the beginning

**Comment by dsbaha** [comment]
That's odd, works for me.  I was able to import 24 hours worth of data.

**Comment by tdsticks** [comment]
Having this issue as well and fix didn't solve it.  Seems to work fine for the other exchanges, except GDAX.

**Comment by dsbaha** [comment]
The way I found this out is when I was receiving error 429 Rate Limit Exceeded.  Are you getting that error on your data pulls?  Or is there another error happening?

**Comment by askmike** [comment]
@blast1987 @BradzTech @austinlangdon @dsbaha @tdsticks we published a new version of gekko (0.5.11) that includes some GDAX importing fixes. Can you try the latest version of Gekko again?

**Comment by blastbeng** [comment]
@askmike it works, but like the fix described by @dsbaha , it just starts retrying from the beginning when an error occurs

In my case i am trying to import from 2017-08-01, but it crashes when doing "Scanning backwards... 2017-11-29" and keeps restarting the process forever

**Comment by tdsticks** [comment]
It seems to be running based on the watcher.log, not getting the retry message in the console like I did with the previous fix.  Trying GDAX USD/LTC with a range from 2017-12-01 00:00:00 - 2017-12-11 13:58:00.  Not seeing a progress bar though, just the loading gif.

**Comment by blastbeng** [comment]
Same, I think you can close this. I re-download ed gekko and not it is working, may be I had some local changes
