### ISSUE TITLE
Bitstamp Tradebot - Order Prices are off.

### ISSUE THREAD

**Issue by Krautshooter** [askmike/gekko#1454]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
I'm testing Gekko with XRP - trading on Bitstamp. I'm applying a modified RSI strategy. The Bitstamp API is properly set up. When using the paper trader with real-time bitstamp data I get the expected buy/sell signals. So far so good. 

* **Expected result** (what you hoped would happen)
I am expecting Gekko to place simple real-time market orders (that actaully have a chance of getting executed). So unless I'm completely mis-interpreting the bot rules, something is off. Any ideas how to resolve this? 

* **Actual result** (unexpected outcome)
Now I hooked up the trade bot to apply the strategy with real money and ran into the following issue: Gekko places an order with a price that's way off the real-time data. Example: XRP is at 0.24750. Gekko places a sell order at 0.24000. The same happened just this morning with a buy order: real-time price was at 0.24500. Gekko placed a buy order at 0.25000 ... which didn't get executed and eventually timed out as XRP never made it up to 0.25000.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
Do you have logs? They are stored inside the `logs` folder.

**Comment by Krautshooter** [comment]
[logs.zip](https://github.com/askmike/gekko/files/1548689/logs.zip)
Here we go. Just check the .zip. 
Ignore the others.

[Uploading 2017-12-11-02-51-UTC-tradebot.log…]()



[Uploading 2017-12-11-01-55-UTC-tradebot.log…]()


[Uploading 2017-12-11-00-51-UTC-tradebot.log…]()
