### ISSUE TITLE
ERR_CONNECTION_REFUSED when I change the 3000 port

### ISSUE THREAD

**Issue by pirmax** [askmike/gekko#1457]
Hi,

I want use your project.
I have change the port 3000 to 3003 for UI.
And, the interface (http://127.0.0.1:3003/) doesn't works : **ERR_CONNECTION_REFUSED**

Thanks for help.

**Comment by greenbigfrog** [comment]
Share your config

**Comment by pirmax** [comment]
It's default config purpose by repository. I have just changed the 3000 port by 3003 because I use already the 3000 port.

**Comment by greenbigfrog** [comment]
What and where did you edit?

**Comment by askmike** [comment]
Could you post your UIconfig, it's most likely a configuration issue as @greenbigfrog suspected.
