### ISSUE TITLE
feature request to get cxxt integration

### ISSUE THREAD

**Issue by jjhesk** [askmike/gekko#1459]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)

* **Expected result** (what you hoped would happen)

* **Actual result** (unexpected outcome)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
I think it is nicer to have Cxxt library to get all the tickers from the world.

**Comment by mattS00** [comment]
Hey @jjhesk
there is currently a pull request for exactly that;

https://github.com/askmike/gekko/pull/1365

**Comment by jjhesk** [comment]
great, any updates for this?

**Comment by greenbigfrog** [comment]
@jjhesk did you even read @mattS00 's message?

**Comment by franz-see** [comment]
@greenbigfrog i read @mattS00 ‘s comment as well but i dont quite get it, so apologies :) I checked the PR and it’s status is Open. 

So does that mean:
a.) it’s still a work in progress,
b.) it’s done but wont be available until the next release, or
c.) ...something else?

Thanks!
