### ISSUE TITLE
 retryHelper(fn, options, callback);       ReferenceError: options is not defined

### ISSUE THREAD

**Issue by wupeng1211** [askmike/gekko#1465]
retryHelper(fn, options, callback);                    ^

ReferenceError: options is not defined

**Comment by tdsticks** [comment]
I just ran into this, change the variable from "options" to "operation", the variable above.
`retryHelper(fn, operation, callback);`  
I was getting this same error when enabling the config.mailer.

**Comment by wupeng1211** [comment]
@tdsticks tks

**Comment by greenbigfrog** [comment]
@askmike this is fixed/done/can be closed

**Comment by askmike** [comment]
:+1: thanks

**Comment by Jabbaxx** [comment]
I think it needs to be reopened and fixed the other way around:
util.js:187
    retryHelper(fn, operation, callback);
ReferenceError: operation is not defined

If I change it back to "Options" it works...
