### ISSUE TITLE
Create PAMR strategy

### ISSUE THREAD

**Issue by vladeta** [askmike/gekko#1466]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[X] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)

* **Expected result** (what you hoped would happen)

* **Actual result** (unexpected outcome)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
It would beneficial for everyone if we had implemented Passive Aggressive Mean Reversion (PAMR) strategy for trading. I've been reading that it gives really good results with volatile market such as cryptocurrency. Is there anyone who implemented this strategy and willing to contribute?

**Comment by kifirkin** [comment]
I've found PAMR strategy implemented in python
[Marigold/universal-portfolios/pamr.py](https://github.com/Marigold/universal-portfolios/blob/master/universal/algos/pamr.py)

**Comment by kifirkin** [comment]
@vladeta could you provide more info on that strategy? I could try to implement it with gekko

**Comment by vladeta** [comment]
@alexmironof I think this is the best resource: https://link.springer.com/article/10.1007%2Fs10994-012-5281-z
