### ISSUE TITLE
Windows 10 install errors

### ISSUE THREAD

**Issue by livingearth2012** [askmike/gekko#1467]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
installed according to install bash on windows 10 64bit ok
install nodejs ok
install gekko ok
install dependencies ok
install git ok
edit handle.js ok
remove talib ok
install talib 1.0.2 ok

then made edit: (from [#890](https://github.com/askmike/gekko/issues/890) 
cd ~/gekko/plugins/sqlite
nano handle.js
changed below to as seen:
db.run('PRAGMA journal_mode = DEL');  // it was db.run('PRAGMA journal_mode = ');

* **Expected result** (what you hoped would happen)
in my gekko dir,  node gekko --ui would launch browser and run.

* **Actual result** (unexpected outcome)
these errors:
module.js:471
    throw err;
    ^

Error: Cannot find module 'moment'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/deepocean/gekko/core/util.js:1:76)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

nothing to add

**Comment by Goro2030** [comment]
Similar error here... installing on windows 10 without bash : 
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.11/node-v59-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.11 and node@9.3.0 (node-v59 ABI) (falling back to source compile with node-gyp)

Looks like the source file in amazonws.com is not available ( it's returning a "Access denied" )

**Comment by cmroche** [comment]
@livingearth2012 Your error usually means you didn't run `npm install` as a side note it is no longer required to modify the handle.js file if you have the latest stable.

@Goro2030 You will need to build it from source, SQLITE has not provided a prebuilt module for your setup yet. To do this you will also need certain build tools on your system. If you are running windows 10 you may want to simply consider using BASH on Win10.

https://github.com/mapbox/node-sqlite3/wiki/Building-on-Windows

or

https://gekko.wizb.it/docs/installation/installing_gekko_on_windows_with_bash_on_windows_10.html

**Comment by cmroche** [comment]
@Goro2030 Found the solution to your problem, we're out of date on sqlite3, run `npm i sqlite3@3.1.13` and it will work.

**Comment by Goro2030** [comment]
@cmroche That solved my issue! You should update the documentation and close this issue.

**Comment by cmroche** [comment]
@Goro2030 PR #1518 should resolve this once merged. The current documentation should then be correct.
