### ISSUE TITLE
Fails installation on Windows Server

### ISSUE THREAD

**Issue by Goro2030** [askmike/gekko#1468]
* **I'm submitting a Installation issue**
[X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Installing according to tutorial

* **Expected result** (what you hoped would happen)
Installed package

* **Actual result** (unexpected outcome)
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.11/node-v59-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.11 and node@9.3.0 (node-v59 ABI) (falling back to source compile with node-gyp)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Looks like the amazonws.com file is not available : 
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>62691D66225060E0</RequestId>
<HostId>
7VN8x2XXBiSRdOXetAP2rLeo5gXCypHl+LOLonKKXP7aSok6eFvYN0pfroGcorCJ+nlv6/+iynY=
</HostId>
</Error>

**Comment by JacktarTrader** [comment]
Same problem here on Debian 9:

node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.11/node-v59-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.11 and node@9.3.0 (node-v59 ABI) (falling back to source compile with node-gyp)

wget https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.11/node-v59-linux-x64.tar.gz  also gives a 403.
