### ISSUE TITLE
ID verification won't go through. required parameter missing: back image

### ISSUE THREAD

**Issue by farhanbaiyat** [askmike/gekko#1474]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**
I've tried to upload my passport image and selfie multiple times yesterday but it kept saying to try again in a while. When I tried uploading them today, I got the "required parameter missing: back image" error multiple times.
* **I'm submitting a ...**
[ x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)

* **Expected result** (what you hoped would happen)

* **Actual result** (unexpected outcome)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
I've tried to upload my passport image and selfie multiple times yesterday but it kept saying to try again in a while. When I tried uploading them today, I got the "required parameter missing: back image" error multiple times.

**Comment by askmike** [comment]
Gekko is a small tool that you can download for free. It never asks for your password.

It sounds like you are having issues with an exchange instead. As such I am closing this issue.

If you do think Gekko asked you for a copy of your password please let me know where you downloaded it from. The official Gekko does not do this.
