### ISSUE TITLE
automating trades on multiple coins per exchange?

### ISSUE THREAD

**Issue by SeAlgoAsoma** [askmike/gekko#1475]
I have a few different coins on Bittrex - OMG, ETH, BTC, etc. 

I have a pretty simple use case... while I'm asleep at night, I want the bot to observe fixed prices that I set for each coin, selling if the coin dips below that, buying back if it goes above. That's all. It's easy enough to do this if I only have one coin, but, I have several.

I've searched everywhere and asked on the discord, and I just can't find any clear explanation how to tell Gekko how much money to spend on each coin. 

For instance, if I have $1000 USDT in my account, I don't want it to spend all $1000 on the next Long signal on BTC, because then there would be no money left over for the next Long on ETH or OMG. If I was only trading BTC this wouldn't be a problem, but what trader puts all their eggs in one basket? Plus, I need to be able to allocate profits from selling coins into buying other coins as things become overbought and oversold, so I have to have the a single pool of USDT to buy and sell from, otherwise I get hit with USDT transfer fees and wait times every time I sell an overbought coin to put the profits into an oversold one. So the coins all have to be in the same account on the same exchange. I've consolidated from having accounts on 5 different exchanges to just 2 because of this. 

So, how do I get it to trade multiple coins on the same exchange, without spending my entire USDT balance on the first coin it goes Long on?

**Comment by askmike** [comment]
Sounds interesting, but that's really out of scope for Gekko, Gekko is a merely designed to trade on single markets using custom TA strategies.

> I have a pretty simple use case... while I'm asleep at night, I want the bot to observe fixed prices that I set for each coin, selling if the coin dips below that, buying back if it goes above. That's all. It's easy enough to do this if I only have one coin, but, I have several.

This would most likely be easier to do without using Gekko at all. The biggest two things you want that Gekko doesn't do:

- fixed amount per trade
- multiple markets per exchange (one the same account)

Gekko is tool to solve a specific and narrow problem, and what you want is something different. Read more about exactly what the scope for Gekko is here: https://gekko.wizb.it/docs/introduction/scope.html

**Comment by efij** [comment]
i really don't get it. If its suppose to be a generic platform, Why limiting the scope of the project to support ONLY one market per exchange..?

**Comment by uipko** [comment]
@SeAlgoAsoma if you realy want to make this work with Gekko, bitstamp could
be a solution (workaround) to this problem. Bitstamp supports subaccounts
which can be used as account in Gekko. And it's easy to move assets between
main and sub accounts.

**Comment by erasmuswill** [comment]
Otherwise you could look at a custom implementation using https://github.com/ccxt/ccxt
