### ISSUE TITLE
GDAX importing

### ISSUE THREAD

**Issue by gigirk** [askmike/gekko#1482]
error is still present :( Using Gekko v0.5.11 and Gekko UI v0.2.0.

Importing data..
Market:
gdax
Currency/Asset:
BTC/LTC
From:
2017-12-11 11:29:00
To:
2017-12-14 12:29:00

error in line 251
canot read property 'time' of undefined

`if (moment.utc(last.time) < moment.utc(since)) {`

[http://prntscr.com/hnknh2](http://prntscr.com/hnknh2)
I do not know how to do the log, I will not copy from windows cmd but if I try to import you with the same configuration the error should come out

**Comment by holeyness** [comment]
@gigirk see: https://github.com/askmike/gekko/issues/1473
