### ISSUE TITLE
Buying a specefic amount of cryptocurrency 

### ISSUE THREAD

**Issue by ghost** [askmike/gekko#1488]
* **I'm submitting a question**
[ ] bug report
[ ] feature request
[x] question about the decisions made in the repository

If you want to use the tradebot, how can you decide what your openings offer is.
Lets say you want to buy 100 dollar as BTC nothing more.

**Comment by Ali1** [comment]
Currently, Gekko will use all your fiat and asset balance for trading. In your case, just have 100 USD in your exchange balance and it will trade back and forth when the algorithm provides trading advice.

**Comment by greenbigfrog** [comment]
Note, that you should have a total of $100 USD and BTC and your wallet though, since it will start trading using both of the currencies configure in your trading pair

**Comment by jaimevisser** [comment]
Having Gekko invest only x amount of currency into asset and everything back would also make it possible to run multiple gekko's off of one base currency. Even if this would be a fixed amount, set from Gekko run start it would already offer a lot more flexibility then gekko currently has.

So this would be a feature request for me.
