### ISSUE TITLE
[request]multiple watcher in config.js

### ISSUE THREAD

**Issue by ghost** [askmike/gekko#1490]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[* ] feature request
[ ] question about the decisions made in the repository
============================================================
thanks guys for hard work but if possible to support multiple watcher in one config.js file

thanks

**Comment by Ali1** [comment]
not now but you can run multiple instances of gekko

**Comment by ChrisCalzaretta** [comment]
Can we please have multiple watchers in the config.. I dont really want to setup 10 instances. That is 10 points of manageability.. I really really like 1 point to manage 10 watchers from a config standpoint. 
Would this be hard to change?
