### ISSUE TITLE
No trades made yet PLEASE HELP ASAP

### ISSUE THREAD

**Issue by clownfish44** [askmike/gekko#1491]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
I started a live Gekko using doker on ubuntu and it has not made any trades.

* **Expected result** (what you hoped would happen)
It making a trade

* **Actual result** (unexpected outcome)
Nothing, no trades have occurred or anything.
https://gyazo.com/9897eace412885fee9c3c2afd43d0070
https://gyazo.com/e7e6750c567a27a7a162e97c1739ab12

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by greenbigfrog** [comment]
Congrulations on making it impossible to even help you slightly, by blurring out your strategy and parameters. Depending how you configured your trader, you might never ever make a trade...

**Comment by ms121** [comment]
Binance is currently not working. Check your Log files and you can check the errors. Currently, the person working on it has given an ETA for Monday / Tuesday for a fix.
