### ISSUE TITLE
Calling leech from within a strategy

### ISSUE THREAD

**Issue by bilaljhavary** [askmike/gekko#1494]
Hi ,

I would like to monitor other markets from within a strategy and I'm guessing that:
a) I would have to run a market watcher for the other markets that I want to monitor
b) Call the leech.js module from within my strategy 
However i am still learning to code java - could any one point me in the right direction as to how I could read the candles of another market watcher from within my strategy?

Thanks,
Bilal

**Comment by greenbigfrog** [comment]
gekko is written in javascript, not java!

**Comment by bilaljhavary** [comment]
Yep new to Java script too :-) 
Surely there must be a way to read the candles from a running market watcher - maybe using node to read the sqlite dB?
