### ISSUE TITLE
Spelling mistake in tulind.js

### ISSUE THREAD

**Issue by magicdude4eva** [askmike/gekko#1501]
https://github.com/askmike/gekko/blob/a80879d4e372a231df2a118165fb5f53c5a08cd7/core/tulind.js#L714

Should be:
```
            results: ['stochK', 'stochD'],
```

**Comment by keustma** [comment]
Created PR for this. #1502

**Comment by greenbigfrog** [comment]
@magicdude4eva You are aware that you can use the online editor to create PRs like this one, without having git etc. installed on your local machine?

**Comment by magicdude4eva** [comment]
@greenbigfrog - no I didn't. Since I am starting to use this project, I will just fork it and then do proper PRs.
