### ISSUE TITLE
TULIP indicators could not be loaded

### ISSUE THREAD

**Issue by Mexxwelll** [askmike/gekko#1505]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Running headless Gekko (also tested with developer), dong backtest with Tulip-* strat. Comes back with error: 2017-12-17 21:18:31 (WARN):     TULIP indicators could not be loaded, they will be unavailable.

npm install tulip
└── tulip@0.0.0

* **Expected result** (what you hoped would happen)
Just some backtest results

* **Actual result** (unexpected outcome)
 2017-12-17 21:18:31 (WARN):     TULIP indicators could not be loaded, they will be unavailable.

* **Other information** 
I was also having issue's with the Talib indicators, i fixed this part by running this command:
npm install talib@1.0.2

**Comment by EdTheProfet** [comment]
Also have this issue. Win 10 bash. Installed as per: https://gekko.wizb.it/docs/installation/installing_gekko_on_windows_with_bash_on_windows_10.html

**Comment by cmroche** [comment]
@Mexxwelll @EdTheProfet  `npm install tulind` not tulip.

**Comment by alieonsido** [comment]
Also have this issue with `npm install tulind`  
my environment is WSL.
Gekko version: v0.5.13
Nodejs version: v8.9.4

**Comment by cmroche** [comment]
What is wsl?

**Comment by cmroche** [comment]
What is the issue?

**Comment by alieonsido** [comment]
@cmroche 
WSL = Windows Subsystem for Linux, sorry for the words you aren't used to & bad description m(_ _)m
my issue is that I can't use my customize strategy, the log record `tulip indicators is not enabled`

**Comment by askmike** [comment]
Please follow the instructions here:

https://gekko.wizb.it/docs/strategies/tulip_indicators.html

@alieonsido if you have trouble installing tulind please create a new issue (as it's different from the one described here). And please post the output of the npm installation command as well! Thanks.

**Comment by alieonsido** [comment]
@askmike 
okay.

**Comment by seyedsaeedmortazavi** [comment]
my error is :
Traceback (most recent call last):
  File "transys_ts_test.py", line 6, in <module>
    from tulip import transys as trs
ImportError: cannot import name transys

**Comment by askmike** [comment]
That's a python error, that cannot come from gekko as it is not written in
python.
