### ISSUE TITLE
UI Error CentOS 7

### ISSUE THREAD

**Issue by mstofflett** [askmike/gekko#1506]
When I start Gekko on CentOS 7 64Bit I receive the following error in the WebUI:

Disconnected
Something happened to either Gekko or the connection. Please check the terminal where Gekko is running or your network connection.

I am running Gekko on a VPS. I have modified the UIconfig to allow for access from outside IP.

I dont get any errors in the SSH console... Any ideas

**Comment by Cavain** [comment]
@mstofflett hey your issue has been resolved ?

**Comment by kaydream** [comment]
hi
i found a solution
if you use your gekko from external ip you must use your external ip address instead of internal ip address
in your web/vue/dist/UIconfig.js
i hope this will be a solution for you
kaydream

**Comment by askmike** [comment]
yep!
