### ISSUE TITLE
Does anyone want historical btc-e data?

### ISSUE THREAD

**Issue by Jonahss** [askmike/gekko#151]
I have btc-e ticker data since Nov. 24th to a resolution of ~3ms. Could provide an api endpoint or just a dump. Is this something people could use?

**Comment by bugron** [comment]
Hi @Jonahss. Do you still have any relevant historical data? If so would you mind to share it here? Otherwise, @askmike, I think this issue can be closed.

**Comment by Jonahss** [comment]
hm yeah. i think I lost all the data long ago :(
