### ISSUE TITLE
Traefik reverse proxy results in Bad Gateway

### ISSUE THREAD

**Issue by Want100Cookies** [askmike/gekko#1516]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Changed UIconfig.js to:
```
const CONFIG = {
  headless: false,
  api: {
    host: '0.0.0.0',
    port: 3000,
    timeout: 120000 // 2 minutes
  },
  ui: {
    ssl: true,
    host: 'some.domain.com',
    port: 443,
    path: '/'
  },
  adapter: 'sqlite'
}

if(typeof window === 'undefined')
  module.exports = CONFIG;
else
  window.CONFIG = CONFIG;
```
This is my traefik config:
``` 
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
[acme]
email = "actual_email"
storage = "acme.json"
entryPoint = "https"
OnHostRule = true
[file]
[backends]
[backends.gekko_backend]
    [backends.gekko_backend.servers.server1]
    url = "http://127.0.0.1:3000"
    weight = 10
[frontends]
[frontends.gekko]
  backend = "gekko_backend"
  passHostHeader = true
    [frontends.gekko.routes.rule]
    rule = "Host:some.domain.com"
```

* **Expected result** (what you hoped would happen)
Working GUI.

* **Actual result** (unexpected outcome)
Bad Gateway

Log from traefik:
`time="2017-12-18T22:27:45Z" level=warning msg="Error forwarding to http://127.0.0.1:3000, err: dial tcp 127.0.0.1:3000: getsockopt: connection refused"`

Gekko gives no errors

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by bspeice** [comment]
Should the rule on the frontend be [frontends.gekko.routes.route0] (instead of [frontends.gekko.routes.rule])? I had a similar spelling issue recently that led to a "Bad Gateway" error.
