### ISSUE TITLE
No Log file exist while config.debug set to true in CLI mode

### ISSUE THREAD

**Issue by Gebrax** [askmike/gekko#1522]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Running both papertrade and realtime trade on CLI mode

* **Expected result** (what you hoped would happen)
Trading log created for respected event and be used for taking decision in strategy

* **Actual result** (unexpected outcome)
No log exist in Log folder eventho folder permission set to write

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Detailed info : 
- Gekko version v0.5.10
- config.debug set to true
- strategy : talib-macd with additional check to ensure sell price > lastLongPrice (that is why i need log)
- log.debug exist in check function
- asset and currency : btc/usd ltc/usd

[strat](https://gist.github.com/Gebrax/acc555e139eb91b586ebb50f4ab897f4)
[config](https://gist.github.com/Gebrax/6ac46abcba5e26bbc3176fb949d24284)

**Comment by hilkoc** [comment]
DId you manage to get the logging working?
I've got the same problem now. I did an update to latest of develop branch and now the UI does not produce log files anymore!
