### ISSUE TITLE
ERROR LOADING DEPENDENCY SQLITE3

### ISSUE THREAD

**Issue by mongoosek** [askmike/gekko#1527]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
I am been trying to setup Gekko and Gekkoga on my laptop. Upon running server.js in Gekko and your-new.js in Gekkoga, I get the error above along with a notification that the child process has died.

* **Expected result** (what you hoped would happen)
I was expecting to see a successful run.

* **Actual result** (unexpected outcome)
The actual result was the error: 'ERROR LOADING DEPENDENCY SQLITE3'

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

I saw another person post a similar issue and one of the contributors referred them to change the name of the history folder. I can't seem to find this folder. Any help is much appreciated and let me know if this is not the right place to report this issue.

**Comment by cmroche** [comment]
Run this on command line

`npm uninstall sqlite3`
`npm install sqlite3@3.1.13`

This should fix your issue. There is a PR request #1518 to fix this.

**Comment by mongoosek** [comment]
I ran those two commands and I still seem to getting the issue.

**Comment by mongoosek** [comment]
I also tried running it on my Mac and I get this output:

`  Error: non-error thrown: Child process has died.
      at Object.onerror (/Users/rdk/gekko/node_modules/koa/lib/context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)`
With no real error above. Should I open another issue for this or are these problems rooted in the same error on my part?

**Comment by cmroche** [comment]
It's hard to say if they are the same or not, back to the machine with the original issue, can you run 

`npm uninstall sqlite3`
`npm i sqlite3@3.1.13` 

and copy and paste the output to this issue please. I suspect it is failing on you.

**Comment by mongoosek** [comment]
Now, I get this error without the notice about the sqlite dependency.

`Error: non-error thrown: Child process has died. at Object.onerror (/Users/rdk/gekko/node_modules/koa/lib/context.js:105:40) at <anonymous> at process._tickCallback (internal/process/next_tick.js:188:7)`

**Comment by cmroche** [comment]
Well it looks like you progressed to the next problem. Is this happening only when you use gekkoga, or does it happen if you try to backtest from the UI?

**Comment by YannSuissa** [comment]
i had to to this to make it works on ubuntu : ln -s /usr/bin/nodejs /usr/bin/node

**Comment by mongoosek** [comment]
Hi, 
Thanks for your comments. Gekko works, but gekkogo doesn't. @Yannuth I ran that command and got this result "ln: failed to create symbolic link '/usr/bin/node': File exists"

**Comment by mongoosek** [comment]
I just manually removed /usr/bin/node and ran that command. Now, I seem to get further along but am getting this same error.

`  Error: non-error thrown: Child process has died.
      at Object.onerror (/home/rdhesika/Gekko/node_modules/koa/lib/context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
`

**Comment by cmroche** [comment]
In baseConfig.js set `config.debug = true` and restart the server, it will help you debug problems from gekkoga.

**Comment by mongoosek** [comment]
I can't seem to find baseConfig.js file. Could you direct me to where I can find it?

**Comment by cmroche** [comment]
`web/routes/baseConfig.js` this is a base config file used when running the UI (or server as the case might be for gekkoga).

**Comment by mongoosek** [comment]
It was already set to true. Also, I got it working on my Mac! I had misimported some of the data. I think it is the same issue on the Ubuntu machine. I have been running it for about ten minutes, still my top strategy involves zero trades. Is this normal?

**Comment by tomma100** [comment]
i went to root with 

sudo -i

navigated to the directory with gekko in 

chmod -R a+rwX gekko/

then 

npm update

(on mac)
