### ISSUE TITLE
Please can you add HITBTC or can i use the API on any selection?

### ISSUE THREAD

**Issue by markymarkjhb** [askmike/gekko#1530]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[ XXX] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)

* **Expected result** (what you hoped would happen)

Please can you add HITBTC or can i use the API on any selection? 
* **Actual result** (unexpected outcome)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by Daakko** [comment]
Did anyone responded yet? Can some please add hitbtc? maybe @askmike

**Comment by mark-sch** [comment]
There are some partial implementations but except data import it is not working, no candle writing no private api use for trading: https://github.com/anhpha/gekko/
Maybe it is time to raise a Bounty for this on https://gitcoin.co - I am wiling either to contribute or spend ETH on this too. Some promising tokens are waiting on HitBtc to get traded ;-D #MTC #BEZ #NEXO #LATX
