### ISSUE TITLE
npm install --only=production eror 

### ISSUE THREAD

**Issue by asemaniko** [askmike/gekko#1531]
npm install --only=production

 nodejs -v
v0.6.19

npm -v
1.1.4

npm ERR! Error: No compatible version found: bitexthai@'^0.1.0'
npm ERR! No valid targets found.
npm ERR! Perhaps not compatible with your version of node?
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:488:10)
npm ERR!     at /usr/share/npm/lib/cache.js:375:15
npm ERR!     at saved (/usr/share/npm/lib/utils/npm-registry-client/get.js:147:7)
npm ERR!     at Object.oncomplete (/usr/lib/nodejs/graceful-fs.js:230:7)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /root/gekko/npm-debug.log npm
npm ERR!
npm ERR! System Linux 2.6.32-042stab120.5
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "--only=production"
npm ERR! cwd /root/gekko
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.4
npm ERR! message No compatible version found: bitexthai@'^0.1.0'
npm ERR! message No valid targets found.
npm ERR! message Perhaps not compatible with your version of node?

npm ERR! TypeError: Object.keys called on non-object
npm ERR!     at Function.keys (native)
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:477:24)
npm ERR!     at /usr/share/npm/lib/cache.js:375:15
npm ERR!     at saved (/usr/share/npm/lib/utils/npm-registry-client/get.js:147:7)
npm ERR!     at Object.oncomplete (/usr/lib/nodejs/graceful-fs.js:230:7)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /root/gekko/npm-debug.log npm
npm ERR!
npm ERR! System Linux 2.6.32-042stab120.5
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "--only=production"
npm ERR! cwd /root/gekko
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.4
npm ERR! type obj_ctor_property_non_object
npm ERR! arguments [ 'keys' ]
npm ERR! message Object.keys called on non-object
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/gekko/npm-debug.log
npm not ok

**Comment by DangerNoodle42** [comment]
> npm ERR! message No compatible version found: bitexthai

This error is related to a repo cache problem. When was the last time you ran an update/upgrade?

**Comment by billymcintosh** [comment]
bitexthai requires node version 4 or higher. 

v0.6.19 is rather old and isn't being supported any more. 

I recommend updating to version 6 or 8 if you can.
