### ISSUE TITLE
Manual install of talib and tulind modules necessary. Not documented.

### ISSUE THREAD

**Issue by belemaire** [askmike/gekko#1533]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[X] question about the decisions made in the repository

* **Action taken** (what you did)

Installed Gecko headless on a box (Ubuntu) following the [proper instructions](https://gekko.wizb.it/docs/installation/installing_gekko_on_windows.html) and launched it.

* **Expected result** (what you hoped would happen)

After configuring Gekko properly, when I try to run a back test using preset TULIP or TALIND strategies, it shoud work correctly.

* **Actual result** (unexpected outcome)

The gekko process fails as it cannot find some directories.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

I actually solved the issue by quickly looking into the repo and finding this line in the DockerFile https://github.com/askmike/gekko/blob/stable/Dockerfile#L17
(`npm install --production redis@0.10.0 talib@1.0.2 tulind@0.8.7`)

Please note that I did not use Docker. It just hinted me toward the right path for fixing the issue. I actually manually ran `npm install --production redis@0.10.0 talib@1.0.2 tulind@0.8.7` and the problem went away.

Any reason why not to include these dependencies in the package.json (maybe because of Windows) ? If they should be kept out of the package.json, then it might be a good idea to add instructions in the documentation to install them manually to get access to the associated strategies.

**Comment by belemaire** [comment]
Just noticed that a PR was opened a few days ago to address this issue in documentation.
Will be closed by https://github.com/askmike/gekko/pull/1511

**Comment by cmroche** [comment]
@belemaire Came here to tell you I pushed a request for this a few days ago :) In the mean time

`npm i talib tulind` in case anyone needs to know the answer.

**Comment by ghost** [comment]
try this if you encounter an error
 npm i talib tulind --no-save

**Comment by askmike** [comment]
not sure what the status was when this issue got opened, but now:

It should be documented: if you run a tulip and talib based strat Gekko will give an error message saying you need to install it! 

On top of that it's documented here: https://gekko.wizb.it/docs/strategies/talib_indicators.html
