### ISSUE TITLE
'Slack/client' is not in the npm registry

### ISSUE THREAD

**Issue by express21** [askmike/gekko#1535]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Ran the `npm install --only=production` via terminal in the Gekko directory.

* **Expected result** (what you hoped would happen)
Gekko dependencies to install.

* **Actual result** (unexpected outcome)
got a slack/client' is not in the npm registry error.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

# **Terminal**

pi@raspberrypi:~ $ cd gekko
pi@raspberrypi:~/gekko $ npm install --only=production
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'slack/client' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'gekko'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.9.59-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "--only=production"
npm ERR! cwd /home/pi/gekko
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/gekko/npm-debug.log
npm ERR! not ok code 0

# **npm-debug.log**

1274 verbose addNamed [ '2.3.0', '2.3.0' ]
1275 silly lockFile dc997df9-chai-2-3-0 chai@2.3.0
1276 verbose lock chai@2.3.0 /home/pi/.npm/dc997df9-chai-2-3-0.lock
1277 silly lockFile 66b6315c-slack-client-3-10-0 slack/client@^3.10.0
1278 silly lockFile 66b6315c-slack-client-3-10-0 slack/client@^3.10.0
1279 error 404 Not Found
1279 error 404
1279 error 404 'slack/client' is not in the npm registry.
1279 error 404 You should bug the author to publish it
1279 error 404 It was specified as a dependency of 'gekko'
1279 error 404
1279 error 404 Note that you can also install from a
1279 error 404 tarball, folder, or http url, or git url.
1280 error System Linux 4.9.59-v7+
1281 error command "/usr/bin/nodejs" "/usr/bin/npm" "install" "--only=production"
1282 error cwd /home/pi/gekko
1283 error node -v v4.8.2
1284 error npm -v 1.4.21
1285 error code E404
1286 verbose exit [ 1, true ]

**Comment by express21** [comment]
Reinstalled dependencies and it worked like a charm afterwards.

**Comment by jxsl13** [comment]
how?

**Comment by Tigel** [comment]
I am having the same issue, which dependencies did you reinstall? Are those listed somewhere?

**Comment by baswientjes** [comment]
Same question here.

**Comment by Tigel** [comment]
Try (worked for me):
sudo apt-get install curl
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs

found here: https://github.com/askmike/gekko/wiki/How-to-setup-VPS-on-Vultr.com-and-run-Gekko

**Comment by baswientjes** [comment]
Yep, just tried it myself, works like a charm. Thanks!
