### ISSUE TITLE
Killing trader action when new advice gets received.

### ISSUE THREAD

**Issue by erasmuswill** [askmike/gekko#1536]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X] bug report
[X] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
I started a bot on ccxt-luno. Trading advice was received and the order could not be excecuted so it was cancelled and retried.

* **Expected result** (what you hoped would happen)
The bot should stop trying to redo the order when new advice is received.

* **Actual result** (unexpected outcome)
The bot continued trying to sell for hours on end and eventually sold for about 80000ZAR below the market rate. I haven't checked why the price is wrong and I will submit another issue if this is a bug.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

I'm thinking that possibly a time limit of the period setting could be placed on the trader function.

**Comment by Yoyae** [comment]
Related to #1365 
I'm working on improved error handling like done in kraken exchange. It might solve the bug you experienced.

**Comment by erasmuswill** [comment]
@Yoyae see https://github.com/ccxt/ccxt/issues/961. It might be implemented soon. However, I don't know how it will handle trading. It wouldn't be logical to keep on retrying because of price volatility. I assume trading will have a retry limit, which would also solve this issue.

**Comment by JohannesHoppe** [comment]
To summarise this, the unwanted spending only did occur when using the ccxt-wrapper (https://github.com/askmike/gekko/pull/1365) because of an unfortunate error-handling OR is this a general issue?
