### ISSUE TITLE
Bot continues to sell at a loss even if the strategy requires this.candle.close > this.lastLongPrice to sell

### ISSUE THREAD

**Issue by ms121** [askmike/gekko#1537]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
tried the following strategy to test this.candle.close > this.lastLongPrice:
https://gist.github.com/askmike/2c4b8e9201c380503ac347ff69c199d5/revisions

Created my own strategy and tested the following both continue to sell lower than the buy price even if I set;
```
 if(this.candle.close > this.lastLongPrice) {  
 this.advice('short');
```

* **Expected result** (what you hoped would happen)
    Gekko should only sell if this.candle.close > this.lastLongPrice

* **Actual result** (unexpected outcome)
     Gekko continues to sell even though the this.candle.close is less than the purchase price

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
Using v 0.5.11 with ui 0.2.0
used stable as well same thing.

**Comment by magicdude4eva** [comment]
Are you actually setting `this.lastLongPrice = this.candle.close;` to adjust for the short/long?

**Comment by ms121** [comment]
@magicdude4eva Yep that is placed under the long advice e.g. in Mikes custom strat it does the same thing and sells under the buy price (added below): [link to full strat](https://gist.github.com/askmike/2c4b8e9201c380503ac347ff69c199d5/3bbc4695ddb6746727c351ce896c9ea329dfa19e)
```
  if(macd1>0 && macd2>0 && macd3>0 && ema21>ema34 && ema21>ema144) {
    this.advice('long');
    // save the long price
    this.lastLongPrice = this.candle.close;
  log.debug('buy price:', this.lastPrice.toFixed(8));
  } 
  
  if(macd1<0 && macd2<0 && macd3<0 && ema21<ema34 && ema21<ema144 && this.candle.close > this.lastLongPrice) {  
    this.advice('short');
  log.debug('sell price:', this.lastPrice.toFixed(8));
  } 
```

**Comment by Gebrax** [comment]
are u sure lastLongPrice is actually executed buy price rather than just opportunity to buy?
have you ever try to log each trade to see this?

**Comment by mattS00** [comment]
@ms121 @Gebrax After logging it the lastlongprice Seems to be updating buy price whenever there is a long advice, Probably best off getting actual buy price.
