### ISSUE TITLE
Postgre not working

### ISSUE THREAD

**Issue by tg44** [askmike/gekko#1540]
https://github.com/askmike/gekko/blob/1766fb032ac2751130fe17472e9f944280167703/plugins/postgresql/handle.js#L51

This line will be always false. If you run `count(*)` that will return exactly one line.
So the query is `select * ` or the if needs to read the count value.

**Comment by tg44** [comment]
BTW I think the table exist function or the table create is failing too. I still try to find the errors...

**Comment by greenbigfrog** [comment]
You're right about the row count part :+1:
