### ISSUE TITLE
ui and cli backtests don't match

### ISSUE THREAD

**Issue by chrisdenley** [askmike/gekko#1548]
UPDATE: I had quotes around number values in the config. You can delete this.

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
I'm trying to run a backtest in the command-line, then repeat the same backtest in the UI.

* **Expected result** (what you hoped would happen)
I expected the backtest results to match.

* **Actual result** (unexpected outcome)
Th results are completely different.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
I'm using the same paper trader settings, strategy parameters (PPO), candle size, and candle history.

**Comment by greenbigfrog** [comment]
Below the box where you can input a commen, there's a button that says `close`. just press it!
