### ISSUE TITLE
The small number format is scientific notation not decimal notation

### ISSUE THREAD

**Issue by emsit** [askmike/gekko#1556]
* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **LOG**
2017-12-25 18:56:35 (INFO): Attempting to SELL 11550.00942 XDG at kraken price: 0.000000730
2017-12-25 18:56:35 (DEBUG):    [kraken.js] (addOrder) SELL 11550.00942 XDG @ **7.3e-7** XBT
2017-12-25 18:56:36 (ERROR):    [kraken.js] (addOrder) returned an irrecoverable error: Order:Invalid price:Invalid price argument.

* **Temporary solution (TESTED)**
**Just for **dogecoin**!!! -> https://blog.kraken.com/post/1278/announcement-reducing-price-precision-round-2**
/gekko/exchanges/kraken.js
`- price = this.roundAmount(price);`
`+ price = this.roundAmount(price).toFixed(8);`

* **Temporary solution 2 ? (NOT TESTED!!!)**
/gekko/exchanges/kraken.js
`- { pair: ['XBT', 'XDG'], minimalOrder: { amount: 3000, unit: 'asset' } },`
`+ { pair: ['XBT', 'XDG'], minimalOrder: { amount: 3000, unit: 'asset' }, precision: 8 },`

**Comment by cmroche** [comment]
The issue seems to actually be that kraken's addOrder was writing the amount as a string, and not a number. I posted a potential fix to PR #1550, please test if you can.
