### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'date' of undefined with Kraken

### ISSUE THREAD

**Issue by acidos** [askmike/gekko#1557]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Imported Kraken EUR/XBT data for backtesting for last 1 month

* **Expected result** (what you hoped would happen)
To import data

* **Actual result** (unexpected outcome)
Error in console
**(node:1007) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'date' of undefined**

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

First I cloned default git branch. Then I've seen number of issues fixed recently for Kraken, such as retry mechanism and cloned develop branch, but still got the error.

**Comment by greenbigfrog** [comment]
What you shared, is most likely not the full error. Mind sharing the full error?

**Comment by acidos** [comment]
This is what I see in terminal when running gekko in --ui mode. Before that I see only few GET/POST lines. Log folder is empty. In baseConfig.js debug is true. I would appreciate for hint on how to collect logs.

**Comment by acidos** [comment]
I was running it on Windows Bash. Today I tried to run develop branch on OS X and the error is much verbose here indeed:

```
Import 25675033919433377 started
  --> POST /api/import 200 6ms 149b
(node:4789) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'date' of undefined
    at handleFetch (/Users/aaa/gekko/importers/exchanges/kraken.js:38:42)
    at Trader.processResults (/Users/aaa/gekko/exchanges/kraken.js:145:21)
    at bound (/Users/aaa/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at /Users/aaa/gekko/core/util.js:28:7
    at /Users/aaa/gekko/exchanges/kraken.js:137:12
    at response.then.catch.error (/Users/aaa/gekko/node_modules/kraken-api-es5/index.js:132:70)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:4789) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4789) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

So I just imported some data from kraken, this time much less, for just around 3 weeks.

**Comment by cmroche** [comment]
@acidos The changes in the develop branch do not cause the importer to be fully robust against Kraken's service problems, PR #1549 has some additional fixes which

1) Correct the retry delays on error (currently they fire too fast)
2) If retries fail for too long report a proper error and end the import instead of crashing it.

**Comment by cmroche** [comment]
@acidos Please try downloading or fetching this branch https://github.com/cmroche/gekko/tree/bitfinex_retry

Even though the branch name is bitfinex_retry, it has some kraken fixes in there. Please try with that branch directly. If you still have problems paste the entirety of your debug log from the console.

I suggest an `npm update` after syncing too, just in case.

Thank you.

**Comment by acidos** [comment]
@cmroche It went quite far this time, up to 55% and...
```
Import 766286580733972 started
  --> POST /api/import 200 6ms 147b
Deprecation warning: moment().add(period, number) is deprecated. Please use moment().add(number, period). See http://momentjs.com/guides/#/warnings/add-inverted-param/ for more info.
  <-- GET /api/imports
  --> GET /api/imports 200 0ms 182b
  <-- GET /api/gekkos
  --> GET /api/gekkos 200 1ms 2b
  <-- GET /api/gekkos
  --> GET /api/gekkos 200 0ms 2b
  <-- GET /api/apiKeys
  --> GET /api/apiKeys 200 2ms 2b
  <-- GET /api/exchanges
  --> GET /api/exchanges 200 6ms 64.46kb
  <-- GET /api/configPart/performanceAnalyzer
  <-- GET /api/strategies
  <-- GET /api/configPart/paperTrader
  --> GET /api/configPart/performanceAnalyzer 200 2ms 144b
  --> GET /api/configPart/paperTrader 200 2ms 132b
  --> GET /api/strategies 200 9ms 2.02kb
(node:6479) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'date' of undefined
    at handleFetch (/Users/aaa/gekko/importers/exchanges/kraken.js:38:42)
    at Trader.processResults (/Users/aaa/gekko/exchanges/kraken.js:145:21)
    at bound (/Users/aaa/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at /Users/aaa/gekko/core/util.js:28:7
    at /Users/aaa/gekko/exchanges/kraken.js:137:12
    at response.then.catch.error (/Users/aaa/gekko/node_modules/kraken-api-es5/index.js:132:70)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:6479) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6479) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by acidos** [comment]
@cmroche The new branch imported perfectly fine from Kraken, without single crash, though extremely slow. But this is due to errors on their service I guess. I hope your changes will be pulled and merged...

**Comment by cmroche** [comment]
@acidos It is partly because of the errors, partly because importing is just slow. In the last few months most exchanges have seen their volume explode by an order of magnitude at least, this slows the import process. Kraken is still one of the fastest importers available in Gekko.
