### ISSUE TITLE
market graph wrong (Buy/Sell) plot

### ISSUE THREAD

**Issue by deadheadtn** [askmike/gekko#1558]
* **I'm submitting a bug report concerning the graph market**
[X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Traderbot on poloniex POT/BTC pair

* **Expected result** (what you hoped would happen)
The buy and sell marks should be on top of the market graph

* **Actual result** (unexpected outcome)
Buy/sell are deviated from the market graph

![screenshot_2017-12-25_21-21-56](https://user-images.githubusercontent.com/4282705/34342999-4873418e-e9ba-11e7-864c-66b94bb20f49.png)

**Comment by smamet** [comment]
I am having the same issue on Poloniex (didn't try other market places). 

I compared data in Poloniex and noticed a 5h delay between real order execution and the dot displayed on graph.

If I do -5h on dots in graph it matched the price line which confirms the 5h delay.

TImezones config on my side are as follows : 

- My local pc - GMT+4
- Server (with gekko) - America/Montreal

Any idea ? 

Thanks

![image](https://user-images.githubusercontent.com/1436778/35104422-3bc54380-fc82-11e7-8393-15cad6f6c45c.png)

**Comment by smamet** [comment]
Maybe it come's from this : 
-> exchanges/poloniex.js L216

![image](https://user-images.githubusercontent.com/1436778/35106468-b83c52a0-fc87-11e7-8290-437e0dc8b271.png)

**Comment by christhecanadien** [comment]
Hello... I don't have any dot (buy or sell) plotted in the graph when I'm using the tradebot live.
Nevertheless they appear in the backtest mode.... Any idea ?
Thanks
