### ISSUE TITLE
can't get webserver running

### ISSUE THREAD

**Issue by cykedev** [askmike/gekko#156]
I don't really understand the webserver code, so I'm not sure if and how it's working, but I can't get it running ...

**Comment by Sebring** [comment]
What is status of this webserver?
I know its an old issue, buy it seems the frontend/css and frontend/js files where never pushed. All I get is:

`Gekko V0.0.0.1!

{{MARKET}}`

**Comment by askmike** [comment]
I'm not sure if I still have the code for that, but it would not be super hard to create something like this.. (the screenshot you see used just pushed all candle data into a [chart from this library](http://nvd3.org/examples/linePlusBar.html)).

What exactly would you use the webserver for? Just monitoring markets / trading advice is easy, but I imagine you actually want to configure / backtest.
