### ISSUE TITLE
Add limitation for negative proffit

### ISSUE THREAD

**Issue by matbogdan79** [askmike/gekko#1560]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[X ] feature request
[ ] question about the decisions made in the repository

Wold be nice to have a config or a way to stop trading if profit is less than a number.
For example if trading strategy decide is time to buy buy or sell and the profit for that action is less than X than postpone that action till profit will be higher or equal than X.

This procedure will stop the bot selling in loss or in big loss like this maximize profit because the bot will wait till the price to sell/buy will produce a profit higher than the limit.

example: bot decide to sell/buy and my limit for profit is -0.71%
if( profit > -0.71 ) continue action
else postpone

if bot get's stuck because of the market drop is better to stop it before it do so nasty shit and human intervention is preferable in this situation or bot will wait till market recover and it can produce some profit.

This is a must for the bot in order to be used in live environments otherwise we will keep losing money and bot will be almost useless.

Thank you !

**Comment by werkkrew** [comment]
This should be addressed by my PR https://github.com/askmike/gekko/pull/1617
