### ISSUE TITLE
Bittrex Historical Data Importing

### ISSUE THREAD

**Issue by austinlangdon** [askmike/gekko#1561]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[x] question about the decisions made in the repository

* **information** 

I read in another issue on this repo that gekko does not support Bittrex historical data importing because Bittrex does not support importing historical data. Does that still hold true, or has it just not been implemented yet?

If it's the latter, perhaps this endpoint could be leveraged for an implementation. Is there anything i'm missing before I take a swing at this?

https://bittrex.com/Api/v2.0/pub/market/GetTicks?marketName=BTC-WAVES&tickInterval=oneMin&_=1482756152000

The last param, "&_", is the historic timestamp param.

Thanks,
Austin

**Comment by cmroche** [comment]
Bittrex does not support historical trade data, only candles. In theory it might be possible to implement importing using candle data, but you would lose the trade count and the VWP fields that Gekko saves when using the trade data to generate candles.

At current though, Gekko does not have a stream for candle based imports. Someone would need to add this. Or to write a script to create and fill DB tables from this data correctly, outside of Gekko.

**Comment by austinlangdon** [comment]
Thank you for the context @cmroche . Will close this for now.
