### ISSUE TITLE
Unable to store/save strat runner webgui

### ISSUE THREAD

**Issue by Dutchblue020** [askmike/gekko#1562]
Hi, 

I'm running the current version on an windows environment, but I have noticed that when I have made an strat and reboot gekko it will not save this parameters. 
So must always create for the live run an new strat. 

Is it possible to save all the used strategies inside the web gui for live use.

**Comment by finom** [comment]
Guys is there any way to restore all strat runners after a process reboot?

**Comment by davejohnson** [comment]
Would love to find out about this too. There's a sqlite plugin that I would have assumed was for that purpose but I can't see any examples of setting it up.

**Comment by garofas** [comment]
Dear @askmike, congratulation for the work done so far on this framework. 
Is really well done, it's a great gift for a large community.
Regarding the persistence of "Market watchers" and "Strat runners" there are some news?
It would be definitely helpful to have Gekko operative after a restart without having to recreate all manually.
