### ISSUE TITLE
getTicker problem in live trade

### ISSUE THREAD

**Issue by insooneelife** [askmike/gekko#1563]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
started live on binance with command
node gekko --config config.js

* **Expected result** (what you hoped would happen)

* **Actual result** (unexpected outcome)
    ______   ________  __    __  __    __   ______
   /      \ /        |/  |  /  |/  |  /  | /      \
  /$$$$$$  |$$$$$$$$/ $$ | /$$/ $$ | /$$/ /$$$$$$  |
  $$ | _$$/ $$ |__    $$ |/$$/  $$ |/$$/  $$ |  $$ |
  $$ |/    |$$    |   $$  $$<   $$  $$<   $$ |  $$ |
  $$ |$$$$ |$$$$$/    $$$$$  \  $$$$$  \  $$ |  $$ |
  $$ \__$$ |$$ |_____ $$ |$$  \ $$ |$$  \ $$ \__$$ |
  $$    $$/ $$       |$$ | $$  |$$ | $$  |$$    $$/
   $$$$$$/  $$$$$$$$/ $$/   $$/ $$/   $$/  $$$$$$/

        Gekko v0.5.11
        I'm gonna make you rich, Bud Fox.

2017-12-27 23:56:55 (INFO):     Setting up Gekko in realtime mode
2017-12-27 23:56:55 (INFO):
2017-12-27 23:56:55 (INFO):     Setting up:
2017-12-27 23:56:55 (INFO):              Trading Advisor
2017-12-27 23:56:55 (INFO):              Calculate trading advice
2017-12-27 23:56:55 (INFO):              Using the strategy: UO
2017-12-27 23:56:55 (WARN):     TALIB indicators could not be loaded, they will be unavailable.
2017-12-27 23:56:56 (INFO):             The trading method requests 3 minutes of historic data. Chec
king availablity..
Deprecation warning: moment().subtract(period, number) is deprecated. Please use moment().subtract(n
umber, period). See http://momentjs.com/guides/#/warnings/add-inverted-param/ for more info.
2017-12-27 23:56:56 (INFO):

2017-12-27 23:56:56 (INFO):             No usable local data available, trying to get as much as pos
sible from the exchange..
2017-12-27 23:56:56 (DEBUG):            Fetching exchange data since 3 minutes ago
2017-12-27 23:56:56 (DEBUG):            Available exchange data:
2017-12-27 23:56:56 (DEBUG):                    from: 3 minutes ago
2017-12-27 23:56:56 (DEBUG):                    to: 0 minutes ago
2017-12-27 23:56:56 (DEBUG):            Unable to stitch datasets.
2017-12-27 23:56:56 (INFO):             Not seeding locally available data to the trading method.
2017-12-27 23:56:56 (INFO):     Setting up:
2017-12-27 23:56:56 (INFO):              Trader
2017-12-27 23:56:56 (INFO):              Follows the advice and create real orders.
2017-12-27 23:56:56 (DEBUG):    getting ticker, balance & fee from binance
2017-12-27 23:56:56 (INFO):

2017-12-27 23:56:56 (DEBUG):    [binance.js] entering "getTicker" callback after api call, err: null
 data: [ { symbo
l: 'ETHBTC',
    bidPrice: '0.04830400',
    bidQty: '11.66000000',
    askPrice: '0.04831000',
    askQty: '0.88800000' },
  { symbol: 'LTCBTC',
    bidPrice: '0.01730200',
    bidQty: '11.32000000',
    askPrice: '0.01733000',
    askQty: '1.45000000' },
  { symbol: 'BNBBTC',
    bidPrice: '0.00063961',
    bidQty: '45.00000000',
    askPrice: '0.00064147',
    askQty: '44.00000000' },
  { symbol: 'NEOBTC',
    bidPrice: '0.00431100',
    bidQty: '39.77000000',
    askPrice: '0.00432700',
    askQty: '22.11000000' },
  { symbol: '123456',
    bidPrice: '0.00000000',
    bidQty: '0.00000000',
    askPrice: '0.00000000',
    askQty: '0.00000000' },
  { symbol: 'QTUMETH',
    bidPrice: '0.06425400',
    bidQty: '2.45000000',
    askPrice: '0.06457500',
    askQty: '40.00000000' },
  { symbol: 'EOSETH',
    bidPrice: '0.01193500',
    bidQty: '4.58000000',
    askPrice: '0.01194500',
    askQty: '50.40000000' },
  { symbol: 'SNTETH',
    bidPrice: '0.00018363',
    bidQty: '5550.00000000',
    askPrice: '0.00018439',
    askQty: '3483.00000000' },
  { symbol: 'BNTETH',
    bidPrice: '0.00654000',
    bidQty: '517.63000000',
    askPrice: '0.00670000',
    askQty: '56.00000000' },
  { symbol: 'BCCBTC',
    bidPrice: '0.17792700',
    bidQty: '0.67200000',
    askPrice: '0.17800000',
    askQty: '1.29300000' },
  { symbol: 'GASBTC',
    bidPrice: '0.00191100',
    bidQty: '1.58000000',
    askPrice: '0.00194200',
    askQty: '6.00000000' },
  { symbol: 'BNBETH',
    bidPrice: '0.01325426',
    bidQty: '12.00000000',
    askPrice: '0.01326751',
    askQty: '2.00000000' },
  { symbol: 'BTCUSDT',
    bidPrice: '15099.00000000',
    bidQty: '0.43901700',
    askPrice: '15100.00000000',
    askQty: '0.40184100' },
  { symbol: 'ETHUSDT',
    bidPrice: '727.28000000',
    bidQty: '0.06104000',
    askPrice: '730.00000000',
    askQty: '5.16063000' },
  { symbol: 'HSRBTC',
    bidPrice: '0.00181600',
    bidQty: '57.63000000',
    askPrice: '0.00182700',
    askQty: '6.57000000' },
  { symbol: 'OAXETH',
    bidPrice: '0.00097140',
    bidQty: '20.00000000',
    askPrice: '0.00099480',
    askQty: '2509.00000000' },
  { symbol: 'DNTETH',
    bidPrice: '0.00014751',
    bidQty: '69.00000000',
    askPrice: '0.00014800',
    askQty: '75.00000000' },
  { symbol: 'MCOETH',
    bidPrice: '0.02249300',
    bidQty: '2.67000000',
    askPrice: '0.02254500',
    askQty: '0.84000000' },
  { symbol: 'ICNETH',
    bidPrice: '0.00311410',
    bidQty: '4.00000000',
    askPrice: '0.00315940',
    askQty: '456.00000000' },
  { symbol: 'MCOBTC',
    bidPrice: '0.00109000',
    bidQty: '172.05000000',
    askPrice: '0.00109100',
    askQty: '106.39000000' },
  { symbol: 'WTCBTC',
    bidPrice: '0.00068999',
    bidQty: '42.00000000',
    askPrice: '0.00069000',
    askQty: '547.00000000' },
  { symbol: 'WTCETH',
    bidPrice: '0.01426500',
    bidQty: '0.79000000',
    askPrice: '0.01442900',
    askQty: '32.08000000' },
  { symbol: 'LRCBTC',
    bidPrice: '0.00002326',
    bidQty: '120.00000000',
    askPrice: '0.00002327',
    askQty: '153.00000000' },
  { symbol: 'LRCETH',
    bidPrice: '0.00047822',
    bidQty: '11515.00000000',
    askPrice: '0.00048270',
    askQty: '1280.00000000' },
  { symbol: 'QTUMBTC',
    bidPrice: '0.00310900',
    bidQty: '4.62000000',
    askPrice: '0.00311000',
    askQty: '167.78000000' },
  { symbol: 'YOYOBTC',
    bidPrice: '0.00001956',
    bidQty: '13382.00000000',
    askPrice: '0.00001958',
    askQty: '118.00000000' },
  { symbol: 'OMGBTC',
    bidPrice: '0.00096900',
    bidQty: '1115.00000000',
    askPrice: '0.00097000',
    askQty: '34.05000000' },
  { symbol: 'OMGETH',
    bidPrice: '0.01983000',
    bidQty: '276.59000000',
    askPrice: '0.02005900',
    askQty: '130.00000000' },
  { symbol: 'ZRXBTC',
    bidPrice: '0.00004135',
    bidQty: '3100.00000000',
    askPrice: '0.00004214',
    askQty: '546.00000000' },
  { symbol: 'ZRXETH',
    bidPrice: '0.00085100',
    bidQty: '8.00000000',
    askPrice: '0.00085773',
    askQty: '7964.00000000' },
  { symbol: 'STRATBTC',
    bidPrice: '0.00091100',
    bidQty: '2037.19000000',
    askPrice: '0.00091200',
    askQty: '14.05000000' },
  { symbol: 'STRATETH',
    bidPrice: '0.01880000',
    bidQty: '10.63000000',
    askPrice: '0.01886000',
    askQty: '59.25000000' },
  { symbol: 'SNGLSBTC',
    bidPrice: '0.00001383',
    bidQty: '9937.00000000',
    askPrice: '0.00001400',
    askQty: '721.00000000' },
  { symbol: 'SNGLSETH',
    bidPrice: '0.00028502',
    bidQty: '7428.00000000',
    askPrice: '0.00028768',
    askQty: '945.00000000' },
  { symbol: 'BQXBTC',
    bidPrice: '0.00016105',
    bidQty: '828.00000000',
    askPrice: '0.00016324',
    askQty: '467.00000000' },
  { symbol: 'BQXETH',
    bidPrice: '0.00330650',
    bidQty: '1660.00000000',
    askPrice: '0.00340320',
    askQty: '1039.00000000' },
  { symbol: 'KNCBTC',
    bidPrice: '0.00015201',
    bidQty: '65.00000000',
    askPrice: '0.00015267',
    askQty: '1339.00000000' },
  { symbol: 'KNCETH',
    bidPrice: '0.00314300',
    bidQty: '1261.00000000',
    askPrice: '0.00314990',
    askQty: '78.00000000' },
  { symbol: 'FUNBTC',
    bidPrice: '0.00000351',
    bidQty: '285.00000000',
    askPrice: '0.00000353',
    askQty: '280584.00000000' },
  { symbol: 'FUNETH',
    bidPrice: '0.00007237',
    bidQty: '170.00000000',
    askPrice: '0.00007300',
    askQty: '813.00000000' },
  { symbol: 'SNMBTC',
    bidPrice: '0.00002186',
    bidQty: '963.00000000',
    askPrice: '0.00002199',
    askQty: '3508.00000000' },
  { symbol: 'SNMETH',
    bidPrice: '0.00044745',
    bidQty: '358.00000000',
    askPrice: '0.00046705',
    askQty: '8509.00000000' },
  { symbol: 'NEOETH',
    bidPrice: '0.08909100',
    bidQty: '2.07000000',
    askPrice: '0.08985500',
    askQty: '2.73000000' },
  { symbol: 'IOTABTC',
    bidPrice: '0.00025319',
    bidQty: '600.00000000',
    askPrice: '0.00025320',
    askQty: '292.00000000' },
  { symbol: 'IOTAETH',
    bidPrice: '0.00523372',
    bidQty: '4.00000000',
    askPrice: '0.00525493',
    askQty: '557.00000000' },
  { symbol: 'LINKBTC',
    bidPrice: '0.00003221',
    bidQty: '7975.00000000',
    askPrice: '0.00003238',
    askQty: '34.00000000' },
  { symbol: 'LINKETH',
    bidPrice: '0.00066405',
    bidQty: '15530.00000000',
    askPrice: '0.00066798',
    askQty: '506.00000000' },
  { symbol: 'XVGBTC',
    bidPrice: '0.00001148',
    bidQty: '27462.00000000',
    askPrice: '0.00001149',
    askQty: '57305.00000000' },
  { symbol: 'XVGETH',
    bidPrice: '0.00023707',
    bidQty: '6626.00000000',
    askPrice: '0.00023826',
    askQty: '44455.00000000' },
  { symbol: 'CTRBTC',
    bidPrice: '0.00013908',
    bidQty: '25.00000000',
    askPrice: '0.00013968',
    askQty: '1000.00000000' },
  { symbol: 'CTRETH',
    bidPrice: '0.00287010',
    bidQty: '693.00000000',
    askPrice: '0.00289850',
    askQty: '541.00000000' },
  { symbol: 'SALTBTC',
    bidPrice: '0.00082200',
    bidQty: '194.26000000',
    askPrice: '0.00082400',
    askQty: '67.32000000' },
  { symbol: 'SALTETH',
    bidPrice: '0.01690100',
    bidQty: '340.63000000',
    askPrice: '0.01713300',
    askQty: '143.00000000' },
  { symbol: 'MDABTC',
    bidPrice: '0.00014356',
    bidQty: '77.00000000',
    askPrice: '0.00014400',
    askQty: '140.00000000' },
  { symbol: 'MDAETH',
    bidPrice: '0.00288420',
    bidQty: '825.00000000',
    askPrice: '0.00300370',
    askQty: '16.00000000' },
  { symbol: 'MTLBTC',
    bidPrice: '0.00053300',
    bidQty: '467.29000000',
    askPrice: '0.00054400',
    askQty: '210.10000000' },
  { symbol: 'MTLETH',
    bidPrice: '0.01120100',
    bidQty: '60.12000000',
    askPrice: '0.01120300',
    askQty: '569.98000000' },
  { symbol: 'SUBBTC',
    bidPrice: '0.00007480',
    bidQty: '231.00000000',
    askPrice: '0.00007500',
    askQty: '20.00000000' },
  { symbol: 'SUBETH',
    bidPrice: '0.00154088',
    bidQty: '3244.00000000',
    askPrice: '0.00157000',
    askQty: '14.00000000' },
  { symbol: 'EOSBTC',
    bidPrice: '0.00057771',
    bidQty: '258.00000000',
    askPrice: '0.00057772',
    askQty: '500.00000000' },
  { symbol: 'SNTBTC',
    bidPrice: '0.00000888',
    bidQty: '3082.00000000',
    askPrice: '0.00000893',
    askQty: '10099.00000000' },
  { symbol: 'ETCETH',
    bidPrice: '0.03919000',
    bidQty: '16.29000000',
    askPrice: '0.03950900',
    askQty: '18.26000000' },
  { symbol: 'ETCBTC',
    bidPrice: '0.00189900',
    bidQty: '2.62000000',
    askPrice: '0.00190200',
    askQty: '1.62000000' },
  { symbol: 'MTHBTC',
    bidPrice: '0.00002595',
    bidQty: '6848.00000000',
    askPrice: '0.00002602',
    askQty: '499.00000000' },
  { symbol: 'MTHETH',
    bidPrice: '0.00053533',
    bidQty: '934.00000000',
    askPrice: '0.00054470',
    askQty: '1026.00000000' },
  { symbol: 'ENGBTC',
    bidPrice: '0.00017558',
    bidQty: '327.00000000',
    askPrice: '0.00017565',
    askQty: '247.00000000' },
  { symbol: 'ENGETH',
    bidPrice: '0.00354810',
    bidQty: '1544.00000000',
    askPrice: '0.00363600',
    askQty: '50.00000000' },
  { symbol: 'DNTBTC',
    bidPrice: '0.00000715',
    bidQty: '572.00000000',
    askPrice: '0.00000718',
    askQty: '16686.00000000' },
  { symbol: 'ZECBTC',
    bidPrice: '0.03455200',
    bidQty: '0.04000000',
    askPrice: '0.03456000',
    askQty: '0.83600000' },
  { symbol: 'ZECETH',
    bidPrice: '0.71541000',
    bidQty: '0.01600000',
    askPrice: '0.72609000',
    askQty: '3.05900000' },
  { symbol: 'BNTBTC',
    bidPrice: '0.00031903',
    bidQty: '450.00000000',
    askPrice: '0.00032199',
    askQty: '413.00000000' },
  { symbol: 'ASTBTC',
    bidPrice: '0.00002585',
    bidQty: '1034.00000000',
    askPrice: '0.00002598',
    askQty: '699.00000000' },
  { symbol: 'ASTETH',
    bidPrice: '0.00052740',
    bidQty: '297.00000000',
    askPrice: '0.00054320',
    askQty: '708.00000000' },
  { symbol: 'DASHBTC',
    bidPrice: '0.07456400',
    bidQty: '0.39700000',
    askPrice: '0.07485800',
    askQty: '6.76000000' },
  { symbol: 'DASHETH',
    bidPrice: '1.54015000',
    bidQty: '0.14300000',
    askPrice: '1.55011000',
    askQty: '0.21300000' },
  { symbol: 'OAXBTC',
    bidPrice: '0.00004681',
    bidQty: '76.00000000',
    askPrice: '0.00004756',
    askQty: '535.00000000' },
  { symbol: 'ICNBTC',
    bidPrice: '0.00014965',
    bidQty: '883.00000000',
    askPrice: '0.00015348',
    askQty: '1866.00000000' },
  { symbol: 'BTGBTC',
    bidPrice: '0.01792000',
    bidQty: '0.43000000',
    askPrice: '0.01796700',
    askQty: '1.31000000' },
  { symbol: 'BTGETH',
    bidPrice: '0.36330600',
    bidQty: '15.11000000',
    askPrice: '0.37394200',
    askQty: '0.20000000' },
  { symbol: 'EVXBTC',
    bidPrice: '0.00012234',
    bidQty: '45.00000000',
    askPrice: '0.00012330',
    askQty: '1649.00000000' },
  { symbol: 'EVXETH',
    bidPrice: '0.00252340',
    bidQty: '356.00000000',
    askPrice: '0.00257980',
    askQty: '211.00000000' },
  { symbol: 'REQBTC',
    bidPrice: '0.00002010',
    bidQty: '1600.00000000',
    askPrice: '0.00002024',
    askQty: '1210.00000000' },
  { symbol: 'REQETH',
    bidPrice: '0.00041656',
    bidQty: '1235.00000000',
    askPrice: '0.00042251',
    askQty: '384.00000000' },
  { symbol: 'VIBBTC',
    bidPrice: '0.00002821',
    bidQty: '4484.00000000',
    askPrice: '0.00002838',
    askQty: '1573.00000000' },
  { symbol: 'VIBETH',
    bidPrice: '0.00057648',
    bidQty: '741.00000000',
    askPrice: '0.00059819',
    askQty: '4863.00000000' },
  { symbol: 'HSRETH',
    bidPrice: '0.03745600',
    bidQty: '54.94000000',
    askPrice: '0.03774300',
    askQty: '14.36000000' },
  { symbol: 'TRXBTC',
    bidPrice: '0.00000241',
    bidQty: '1624420.00000000',
    askPrice: '0.00000242',
    askQty: '3781521.00000000' },
  { symbol: 'TRXETH',
    bidPrice: '0.00004993',
    bidQty: '9014.00000000',
    askPrice: '0.00004996',
    askQty: '581031.00000000' },
  { symbol: 'POWRBTC',
    bidPrice: '0.00005866',
    bidQty: '847.00000000',
    askPrice: '0.00005880',
    askQty: '5362.00000000' },
  { symbol: 'POWRETH',
    bidPrice: '0.00121029',
    bidQty: '374.00000000',
    askPrice: '0.00122262',
    askQty: '1273.00000000' },
  { symbol: 'ARKBTC',
    bidPrice: '0.00047980',
    bidQty: '97.05000000',
    askPrice: '0.00048000',
    askQty: '339.84000000' },
  { symbol: 'ARKETH',
    bidPrice: '0.00982500',
    bidQty: '10.00000000',
    askPrice: '0.00996300',
    askQty: '103.28000000' },
  { symbol: 'YOYOETH',
    bidPrice: '0.00040374',
    bidQty: '567.00000000',
    askPrice: '0.00041725',
    askQty: '358.00000000' },
  { symbol: 'XRPBTC',
    bidPrice: '0.00007469',
    bidQty: '8104.00000000',
    askPrice: '0.00007470',
    askQty: '7450.00000000' },
  { symbol: 'XRPETH',
    bidPrice: '0.00154461',
    bidQty: '136.00000000',
    askPrice: '0.00154893',
    askQty: '3975.00000000' },
  { symbol: 'MODBTC',
    bidPrice: '0.00021700',
    bidQty: '29.95000000',
    askPrice: '0.00021710',
    askQty: '180.64000000' },
  { symbol: 'MODETH',
    bidPrice: '0.00445300',
    bidQty: '179.00000000',
    askPrice: '0.00450100',
    askQty: '396.62000000' },
  { symbol: 'ENJBTC',
    bidPrice: '0.00001011',
    bidQty: '16775.00000000',
    askPrice: '0.00001016',
    askQty: '904.00000000' },
  { symbol: 'ENJETH',
    bidPrice: '0.00020852',
    bidQty: '53.00000000',
    askPrice: '0.00020967',
    askQty: '11351.00000000' },
  { symbol: 'STORJBTC',
    bidPrice: '0.00009519',
    bidQty: '1372.00000000',
    askPrice: '0.00009635',
    askQty: '75.00000000' },
  ... 129 more items ]
D:\TechnicBank\git\clone\gekko\gekko\exchanges\binance.js:193
    callback(err.message, ticker);
                 ^

TypeError: Cannot read property 'message' of null
    at Trader.setTicker (D:\TechnicBank\git\clone\gekko\gekko\exchanges\binance.js:193:18)
    at bound (D:\TechnicBank\git\clone\gekko\gekko\node_modules\lodash\dist\lodash.js:729:21)
    at Request.request [as _callback] (D:\TechnicBank\git\clone\gekko\gekko\node_modules\binance\lib\rest.js:61:21)
    at Request.self.callback (D:\TechnicBank\git\clone\gekko\gekko\node_modules\request\request.js:188:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (D:\TechnicBank\git\clone\gekko\gekko\node_modules\request\request.js:1171:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (D:\TechnicBank\git\clone\gekko\gekko\node_modules\request\request.js:1091:12)

**Comment by deadheadtn** [comment]
if you're using a version of binance higher than 1.0.2 use this  `npm install binance@1.0.2`
downgrade it, and also as a temporary fix you can replace the line `callback(err.message, ticker);` by `callback(undefined, ticker);`
try taking a look at the pull requests (similar issues) #1550 #1481 #1401
