### ISSUE TITLE
UI do not show anny market

### ISSUE THREAD

**Issue by eivindtj** [askmike/gekko#1564]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
I just installed Gekko on CentOS 7.0 Using the guide: https://gekko.wizb.it/docs/installation/installing_gekko.html

Started the UI, and it Works- Using Firefox

* **Expected result** (what you hoped would happen)
But when I tried to insert an API, there is not showing anything under "Exchange"
The area is just empty.
The same issues if i tried to import data, the area under "Marked" is empty.

I have not change any config files.

* **Actual result** (unexpected outcome)
I expected to se some Exchange/marked, have seen thrue som Youtube Movies, and it seem to be default With markeds in UI mode.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by bitoutshop** [comment]
HAs this been addressed?  Images attached of the issue described still occurring 

No Echanges displaying when trying to Start a live Gekko
![image](https://user-images.githubusercontent.com/36680933/46116630-68fe6c80-c240-11e8-8d78-cf3f50bca698.png)


And none available to select from when adding an API key
![image](https://user-images.githubusercontent.com/36680933/46116639-74ea2e80-c240-11e8-916c-3df4f436d0f3.png)

**Comment by ghost** [comment]
Do you have the Broker Dependancies installed?

![image](https://user-images.githubusercontent.com/36680933/46117545-15425200-c245-11e8-8bfc-1fabcab89524.png)

**Comment by askmike** [comment]
@bitoutshop this issue is old, at the time gekko broker didn't exist. But it can't be an issue anymore!
