### ISSUE TITLE
Built-in strategies with default setting performing terribly in backtesting

### ISSUE THREAD

**Issue by ralekna** [askmike/gekko#1566]
* **I'm submitting a ...**
[*] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
I was making backtesting Kraken (USD/XBT) and Bitfinex (USD/BTC) historical data with almost all built in strategies with default settings that comes with Gekko.

* **Expected result** (what you hoped would happen)
I was expecting even a bit of profit. 

* **Actual result** (unexpected outcome)
I found that all strategies with default settings are generating huge loss in longer time spans. More trades - more loss event if market by itself goes up. Are those strategies intentionally performing badly so no one would use them in real life?

* **Other information** 
I attach a screenshot of Bitfinex backtest settings and results

![Screenshot of Bitfinex backtesting settings and results](https://i.imgur.com/9KEnv5t.png)

**Comment by ddey94** [comment]
From my understanding playing around with Gekko - the built in strategies are more for demonstration purposes. The Gekko bot is the dirty work, such as building code to make trades, connect to exchange API's etc. If you want to "get rich quick", you will need to implement your own custom strategy that you have backtested and you know works. The "brains" of the Gekko bot lies in the strategy and to open source a strategy that "beats the market" would be like giving away free money. The goal is to be able to implement your own custom trading strategy that has higher profit than just B&H.

**Comment by ralekna** [comment]
I suspected that but thanks for clarifying. Just wanted to check if I'm not doing some mistake.
