### ISSUE TITLE
Question - Trading History in Strategy

### ISSUE THREAD

**Issue by werkkrew** [askmike/gekko#1570]
General Question, not a bug:

Is it possible to integrate the trading history into a strategy such that you can set limits so that it will only make profitable trades? 

I am interested in testing out some limits in my strategy for only making profitable trades with a profitability variable to see how it works.

I want to base these decisions on the last actual successful trade (or group of trades on the average price of the batch), and not the last bit of advice in case the trade based on the advice was not successful.

**Comment by werkkrew** [comment]
I suppose I should rephrase what Im asking, after playing with it a bit.

Is it possible for a strategy to subscribe the trade emitter?  I want to get the value to the trade data on a successful trade and use this information in the strategy.

**Comment by haccg** [comment]
You just have to store the trade price in a variable so you can you it again.

e.g.

this.candle.close = this.tradeprice

**Comment by werkkrew** [comment]
Opened PR #1617 which adds this functionality.
