### ISSUE TITLE
"Unknown Watcher" while starting  new gekko

### ISSUE THREAD

**Issue by springrider** [askmike/gekko#1576]
* **I'm submitting a ...**
[ ] bug report
* **Action taken** (what you did)

visit http://localhost:3000/#/live-gekkos/new, set type to "market watcher".  then click "Start"

* **Expected result** (what you hoped would happen)

start a new gekko.
* **Actual result** (unexpected outcome)

it shows error:

> Unknown Watcher
> Gekko doesn't know what whatcher this is...
> 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
using the latest branch "stable"
not setup any database, the default is sqlite I guess.

while click "start", command line console shows:

> Gekko 430672965059296 started
>   --> POST /api/startGekko 200 6ms 148b
> Deprecation warning: moment().add(period, number) is deprecated. Please use moment().add(number, period). See http://momentjs.com/guides/#/warnings/add-inverted-param/ for more info.

no error log in the chrome console.

**Comment by CyborgDroid** [comment]
+1 after updating gekko today (few months old before that). At first it seemed to add the watchers anyways after getting the error, but after the first few watchers they all disappeared from the UI.

```
git pull
npm install --only=production
forever stop ~/gekko/gekko.js --ui
forever start -a ~/gekko/gekko.js --ui
```
