### ISSUE TITLE
VSCode: Debug Strategies

### ISSUE THREAD

**Issue by pharindoko** [askmike/gekko#1581]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Created launch.json in VSCode with following settings 
```
{
    "version": "0.2.0",
    "configurations": [

        {
            "name": "Launch Server",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/gekko.js",
            "cwd": "${workspaceRoot}",
            "preLaunchTask": null,
            "runtimeExecutable": null,
            "args": [
                "--ui",
                "--config", "config.js"
            ],
            "env": {
                "NODE_ENV": "development"
            },
            //"console": "internalConsole",
            "sourceMaps": false,
            "outFiles": []
        }
    ]
}
```
Set a breakpoint 
Start to debug gekko.js and then get deeper into details to debug a strategy

* **Expected result** (what you hoped would happen)
History data (local data) is available in history folder and will be loaded the same way as it does if I start gekko via commandline. 
No difference if I run it in a debug session or via commandline

* **Actual result** (unexpected outcome)
I can debug into gekko.js and even import.js
Issue:
No local data or history data for back testing is available.
When I try to run the importer to add additional data it fails I receive following error in Import.js
```
RECEIVED ERROR IN IMPORT 999433617504825
Child process has died.
```
Assumption - something wents wrong with backend (sqlite)
Can someone else try to replicate and see if it works ?

**Comment by gdomod** [comment]
same here. any help ?

**Comment by Nimrasol** [comment]
I made the same experience. Is there a solution available? Is there an other way to debug gecko with brake points? Thank you for the help!

**Comment by kalitas** [comment]
same here

**Comment by goldistan** [comment]
Same here. 

I came up with this configuration - 

"configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Gekko",
            "program": "${workspaceFolder}/web/server.js",
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Gekkoga",
            "program": "${workspaceFolder}\\gekkoga\\run",
            "args": [
            "-c", "${workspaceFolder}\\gekkoga\\config\\stochRSI.js"
            ]
        }
    ],
    "compounds": [
        {
            "name": "Server/Server2",
            "configurations": ["Gekko","Gekkoga"]
        }
    ]

it works when I run it from the command line, and fails when I do from my code editor with the following exception - 

 Error: non-error thrown: Child process has died.
application.js:186
      at Object.onerror (...\node_modules\koa\lib\context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by goldistan** [comment]
same here

**Comment by mikemichaelis** [comment]
I'm having the same issue, but discovered it has nothing to do with VS Code.  If you execute node 8.10.0 in --inspect mode, gekko will not find any history data.

node --inspect gekko --ui

I also tried node 7.10.1 using the legacy debug protocol and it also fails to load historical data.

node --debug gekko --ui

**Comment by evertondanilo** [comment]
I found the bug:

Go to this file: Gekko\core\workers\dateRangeScan\parent.js

**Original:**
```
module.exports = function(config, done) {
  var debug = typeof v8debug === 'object';
  if (debug) {
    process.execArgv = [];
  }
```
**Changed:**
```
module.exports = function(config, done) {
  var debug = typeof v8debug === 'object';
  if (debug || config.debug) {  //LOOK HERE <<
    process.execArgv = [];
  }
```
So, what I've seen here is that when debugging we need to clear out the execArgv parameter. However the debug variable was set as false.

**Comment by askmike** [comment]
This was added here on purpose: #1666 by @mronus. Note @evertondanilo that this issue was opened before that PR was merged.

I don't use any of these tools in my debug flow and which way is best depends on how you are debugging I guess.
