### ISSUE TITLE
creating a strategy and adding it into my strategies

### ISSUE THREAD

**Issue by mdomeralikhan** [askmike/gekko#1584]
**Note: for support questions, please join our [Discord server](https://discord.g
[ ] feature request

hello mike since past few days iam trying to do coding in .js script but i suck at coding big time can u please help me create a strategy indicator for triple ema crossover where i can buy when short ema crosses the other two long ema and sell when the short ema comes below the two ema with a stoploss of 5 percent from buying rate..please do the needy

* **Expected result** (what you hoped would happen)

* **Actual result** (unexpected outcome)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by mdomeralikhan** [comment]
i tried editing existing formula codes but it led me no where  please explain the process of putting it in strategy folder and in other folders it wid be helpful for the rookies on the platform

**Comment by askmike** [comment]
@mdomeralikhan apologies for the delay, stop losses will be possible very soon but are not yet, see this thread for details: https://forum.gekko.wizb.it/thread-57314.html

**Comment by askmike** [comment]
If this is still an issue please comment and I will reopen :)
