### ISSUE TITLE
Timestamp on db entrys?

### ISSUE THREAD

**Issue by master0044657** [askmike/gekko#1585]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)

* **Expected result** (what you hoped would happen)

* **Actual result** (unexpected outcome)
Hello, is there a way to extract timestamps to db so i can data query in my db client? I am noob and i gess im missing something obvious but cant find the way. Thanks!!!

![io](https://user-images.githubusercontent.com/31035905/34451765-dbbe019e-ed30-11e7-83e6-65349a4bb8ad.png)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by cmroche** [comment]
"start" is the timestamp field for the start of each candle, in seconds epoch time. So `SELECT start from candles_ASSET_CURRENCY`

**Comment by master0044657** [comment]
oh ok i see. Sorry for dumb question

**Comment by cmroche** [comment]
No worries :)
