### ISSUE TITLE
Tradebot in UI and define trading amount

### ISSUE THREAD

**Issue by coralgulf** [askmike/gekko#1588]
Hello to all,

live trading with the bot can be made meanwhile also via the UI. Is it necessary to change the config=false in this case (I assume not)? In paper trader there are some options for fees etc. in the UI available, why not in tradebot mode?

I learned that the bot is using always the maximum available amount for trading. I am on bitstamp and have already deposit in every cryptocurrency and Euro. So if I change some Euro to USD and start live testing with gekko only this amount is used if I define it this way (f. e. 100 USD)? So the deposit before in BTC or Euro is not touched and gekko is just dealing with the 100 USD and leaving everything else like before? Also selling is only made with the comparable amount?

Thanks for additional information, this seems to be clear to everyone else, I found no questions about that.

Happy New Year to everybody!

**Comment by ankasem** [comment]
Merry Christmas
-how many bot can we run on a stock exchange
-can we just define the amount of btc or usd we want
-how to run a bot for 3 coins of 100 usd at binance
I use translation I do not look up
I could have written the wrong place
thank you

**Comment by coralgulf** [comment]
Found most of the questions answered after another intense study of the themes mentioned here...

**Comment by josoroma-zz** [comment]
@coralgulf please share your findings pal.

Does the bot handle the initial purchase, or is it a trader action?

Thanks!
