### ISSUE TITLE
Get the profit report from the IRC bot

### ISSUE THREAD

**Issue by nicocesar** [askmike/gekko#159]
If profit simulator plugin is enabled, it will be nice to have ;;profit report  command that just show the last profit report showed on console.

**Comment by bugron** [comment]
@askmike isn't there an IRC bot implemented as a plugin for this?

**Comment by askmike** [comment]
Yes and this is about adding a command to that plugin..

**Comment by askmike** [comment]
open for pulls, but I am pretty sure no one is actively waiting for this anymore.
