### ISSUE TITLE
Howto import data from Binance ?

### ISSUE THREAD

**Issue by helmuteke** [askmike/gekko#1594]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Install Gekko into a docker container

* **Expected result** (what you hoped would happen)
Import historical data from binance exchange

* **Actual result** (unexpected outcome)
Import hangs

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

_______________________________________________________________________________________

When i try to import historical data from binance then it hangs without progress , when i do this with other exchange like poloniex then it works.

 How to solve or Fixt his ??

**Comment by SICKFREDO** [comment]
Im experiencing the same, I also can run the paper trader against binance it shows under Strat runners
but does nothing. Any help would be greatly appreciated. :) 

UPDATE: seems like is also affecting other markets not just binance

**Comment by trisgne** [comment]
Same issue here. Any help would be highly appreciated.
Thanks.
![binance](https://user-images.githubusercontent.com/31898599/34506240-edd54c3a-f022-11e7-853a-718e6ff3516e.PNG)

**Comment by SICKFREDO** [comment]
This is the error every time i try to import data:

`Import 336089527109014 started
  --> POST /api/import 200 172ms 149b
C:\Users\Zion\gekko-stable\exchanges\binance.js:35
  if (!error || !error.message.match(recoverableErrors)) {
                               ^

TypeError: Cannot read property 'match' of undefined
    at Trader.retry (C:\Users\Zion\gekko-stable\exchanges\binance.js:35:32)
    at Trader.bound [as retry] (C:\Users\Zion\gekko-stable\node_modules\lodash\dist\lodash.js:729:21)
    at Trader.process (C:\Users\Zion\gekko-stable\exchanges\binance.js:70:19)
    at bound (C:\Users\Zion\gekko-stable\node_modules\lodash\dist\lodash.js:729:21)
    at Request.request [as _callback] (C:\Users\Zion\gekko-stable\node_modules\binance\lib\rest.js:52:21)
    at Request.self.callback (C:\Users\Zion\gekko-stable\node_modules\request\request.js:188:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\Zion\gekko-stable\node_modules\request\request.js:1171:10)
    at emitOne (events.js:116:13)
RECEIVED ERROR IN IMPORT 336089527109014
Child process has died.
`

**Comment by Medardas** [comment]
The above error can be solved by replacing OR logic expression ( || ) with AND ( && ) in 
 (C:\Users\Zion\gekko-stable\exchanges\binance.js:35:32) (binance.js: line 35)
That was minor logical issue, could not be bothered to create a PR for this. 
Problem is, even with this solved there is still an issue somewhere. It doesn't show any errors, but doesn't load data either.

**Comment by Medardas** [comment]
I think  the idea in binance.js line 35 was to have this logic:
`if (error.message && !error.message.match(recoverableErrors)) {`

however this solves only above error, import still fails

**Comment by Medardas** [comment]
#1637

**Comment by juanluisbaptiste** [comment]
I'm having the same issue with latest version from develop.

**Comment by andr0s** [comment]
Same issue

**Comment by ghost** [comment]
im experiencing the same issue

**Comment by askmike** [comment]
@joao-roberto which one?

**Comment by askmike** [comment]
This is a very old issue, should be fixed! For anyone who has trouble with the current version, please open a new issue.
