### ISSUE TITLE
Request for basic strategy MACD+RSI+ADX

### ISSUE THREAD

**Issue by talentoscope** [askmike/gekko#1595]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

I've looked at how technical indicators work and trying to learn on-the-fly as it were. Would it be possible to make, or does anyone have a very basic strategy using RSI, MACD and ADX?
I'm using the GA gekkoga for finding parameters, but just multiplying or adding those three together would probably give some sort of assurance on trend identification, I just can't seem to code a strategy together for the life of me.
Even a basic example would really help get us coding n00bs off to a start :)

Thank you for this amazing project!

**Comment by werkkrew** [comment]
We can work together on something, we've already chatted on Discord about it.

**Comment by talentoscope** [comment]
That's true. Well, if it works, it works. It'll be good to see what results
come back across different markets and exchanges.
As with any strategy though, the more that use it, the less well it
performs. Plenty of exchanges and currencies though to go around.
