### ISSUE TITLE
bitcoin.co.id update

### ISSUE THREAD

**Issue by ghost** [askmike/gekko#1596]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[ x] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Day trading at bitcoin.co.id
I have not used Gekko at Bitcoin.co.id because I believe Gekko is not updated for Bitcoin.co.id

* **Expected result** (what you hoped would happen)
Availablity of altcoins. Now it support BTG to IDR, XLM to IDR,NXT to IDR.

* **Actual result** (unexpected outcome)
Some of the altcoins are not available to be traded directly to IDR.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
A statement regarding last update date of supported exchange.

Regards,
Jason

**Comment by bitkominer** [comment]
@jasonongputra , until someone officially gives an update, you might modify the file by yourself.
Go to file "bitcoin-co-id.js" inside folder: \gekko-stable\exchanges

Then modify assets list like this (add the new assets name):
line#257
`assets: [
      'BTC', 'BCH', 'BTS', 'ETH', 'ETC', 'LTC', 'WAVE', 'XRP', 'XZR', 'BTC', 'DASH', 'DOGE', 'BTG', 'NXT', 'STR', 'XEM'
    ],`

After that, modify the market pair in succeeding lines, e.g:

`	  { pair: ['IDR', 'BTG'], minimalOrder: { amount: 0.01, unit: 'asset' } },
	  { pair: ['IDR', 'STR'], minimalOrder: { amount: 5.0, unit: 'asset' } },
	  { pair: ['IDR', 'NXT'], minimalOrder: { amount: 2.0, unit: 'asset' } },`

Note: you might check the minimum trade amount directly in the exchange to modify minimal order. The above sample using minimal order of 2.0NXT, 5.0XLM, etc. (Remember that STR is listed as XLM, but inside the js file you need to mention it as STR).

**Comment by ghost** [comment]
Oh, that's why it didn't work properly. STR and XLM. great!

Thank you.

**Comment by wiamadaya** [comment]
i cant seem to figure out how the minimum order is calculated, i checked for IDR pair the minimum order is IDR 50,000. Does it have something to do with dividing the current price's zeros with priceDivider? 

var priceDivider = 100000000; // one hundred million;

eg. BCH is currently at IDR 40,000,000; hence 10,000,000/100,000,000 = 0.1? and therefore IDR/BTC should be 1?
