### ISSUE TITLE
Use different API keys for sub-accounts

### ISSUE THREAD

**Issue by coralgulf** [askmike/gekko#1601]
[ ] bug report
[X] feature request
[ ] question about the decisions made in the repository

Bitstamp has the possibility to assign different API-keys to sub-accounts. This makes it possible to handle more than one currency and different amounts in the sub-accounts.

So you are able to override the current limitations while using the tradebot.

**Comment by Kirbylix** [comment]
when you run the bot over the console. In the config file, you can specify the API key for your subaccount.

**Comment by coralgulf** [comment]
Thanks, good idea.

So it is possible to run multiple tradebots via the commandline?

Is there any possibility to get informations to the ui when using the console (I assume unfortunately not yet)?

**Comment by Kirbylix** [comment]
yes it is possible to run multiple bots via the console: [Screen](https://wiki.ubuntuusers.de/Screen/)

1. create a new Screen Session
2. create a separate config file for each trade bot (sub-account)
3. for each config file create a window (Screen: CTRL + A -> C)
4. start the trade bot for the window/config file

in the config file you can set an email notification if the bot trades

**Comment by coralgulf** [comment]
Great, thank you! Works in a similar way under windows.

Additionally I try to implement several versions of the same exchange (Bitstamp1, Bitstamp2...) with different sub-accounts and API-keys for the UI.
