### ISSUE TITLE
Gekko Run Error - not yet supported outside strict mode

### ISSUE THREAD

**Issue by crypto-kid** [askmike/gekko#1604]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[* ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Installed Gekko for Bash on windows 10 

when I go to run gekko using 

Node gekko --ui 
or 
nodejs gekko --ui

I get the following error

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

please note that in order to get a successful install I had to used the following symlink fix 
sudo ln -sT /usr/bin/nodejs /usr/bin/node

* **Expected result** (what you hoped would happen)

for Gekko to run 
* **Actual result** (unexpected outcome)
/root/gekko/core/error.js:3
let RetryError = function(message) {
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/gekko/core/util.js:8:14)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by Tazer89** [comment]
I got same problem.

**Comment by crypto-kid** [comment]
I'm very new to this OS so having trouble problem solving, I have tried to install several types of nodejs and that hasn't worked so a bit lost now.

**Comment by crypto-kid** [comment]
Fixed it !!!

do the following 
sudo ln -sf /usr/local/n/versions/node/7.5/bin/node /usr/bin/node

Then 

sudo apt-get update
curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo apt-get install -y build-essential


then run
 cd Gekko
node gekko --ui
 
then open http://localhost:3000. in your browser 
 
Now this has worked for me so only hope it works for you !

**Comment by bubbgee** [comment]
Basically you need to ensure that the node.js version on your OS is node.js ver 6 and above.

On ubuntu, I did the following:

sudo apt-get install npm
npm install n -g 
sudo n latest

Then run 
nodejs gekko --ui

**Comment by seanh1414** [comment]
you can also use NVM which i've used quite a bit ( because I have other projects that depend on different versions) https://github.com/creationix/nvm/blob/master/README.md

**Comment by Tr0j4n9** [comment]
Thanks, @crypto-kid !
