### ISSUE TITLE
Live tradebot on binance tries to sell at incorrect price

### ISSUE THREAD

**Issue by Orwi53** [askmike/gekko#1606]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Started gekko as a live trader (turned off paper trader and used configuration accordingly)

* **Expected result** (what you hoped would happen)
executing buy/sell orders

* **Actual result** (unexpected outcome)
executing sell order at wrong price

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Hi, I am trying gekko as a live trader, on a simple strategy that I made, on binance, with small amounts of cryptocurrency.

Before describing the problem, I will state my current configuration:

    git log -1 

returns:

    commit e7af14932f8ddc79e1568254b18b7cc91acfad65
    Author: Clifford Roche <clifford.roche@gmail.com>
    Date:   Sun Dec 31 20:30:18 2017 -0500

    No longer subtract 1 second
    
    It isn't necessary because we fixed the iterator to 24 hour periods, and no longer use the trade time 
    from the last trade (which has only 1 second resolution).

gekko was not working on binance, so I tried to make it work by also implementing the suggestions described in issue #1563: I made that change `(callback(err.message, ticker);` to `callback(undefined, ticker);` ) not only in that line of the file `exchanges/binance.js,` but also on line 342: `callback(err.message, !stillThere)` to `callback(undefined, !stillThere)`

gekko didn't crash, but, as it tried to act on the "short" advice, the output was this (removed IDs from the pic as they are not necessary):

![1](https://user-images.githubusercontent.com/35005865/34469835-fd515b2e-ef26-11e7-83bc-582866b9f477.png)

When I went to see on binance what happened, it seems that it tried to sell at the price "1", causing the sell to not happen, and consequently cancelling it by itself and retrying.

![2](https://user-images.githubusercontent.com/35005865/34469961-4c144f40-ef28-11e7-965e-627bc4e67b9a.png)

(nevermind the first entry in that list, that's when I manually sold it )

A part from fixing this issue, I would also like to know, how can my custom-made strategy know if the sell was successful? Because if it doesn't know, once the "short" advice is given, my custom-made strategy will switch to buy-mode while gekko is still trying to sell. How can I check if the buy or sell was successful from my custom strategy?

I would like it to try to sell when the "short" advice is given, and, If it can't sell it (for example order hangs or something), my strategy should know it, so that it will wait for the next good occasion to sell, instead of trying to buy.

**Comment by meidays** [comment]
The transaction is reversed.
It is expensive and it sells cheaply.
Please modify the code.  ~~;
