### ISSUE TITLE
Just overall stuck

### ISSUE THREAD

**Issue by deejay100** [askmike/gekko#1607]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Ran a live trading bot then tried a papertrader

* **Expected result** (what you hoped would happen)
 to see results, whether it be a profit or loss

* **Actual result** (unexpected outcome)
Nothing. 
I havent found a way to actually see if my api is working with my gekko account
and ive sat here forever and havent see any progress with my stradegies. it just sits at 'zero trades'
like im not even getting any errors, its just not producing any results

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by haccg** [comment]
What is the commandline output?
How long is "forever"?

**Comment by czubehead** [comment]
You must understand that gekko uses candles, so it won't perform a huge number of transactions. If you run backtests, you can see that there are relatively long periods of doing nothing between transactions.
If 'forever' isn't weeks, this question is irrelevant.
