### ISSUE TITLE
Importing from Kraken freezing on UI and stopping on commandline

### ISSUE THREAD

**Issue by HugoJF** [askmike/gekko#1611]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Tried importing some data from Kraken (any pair seems to do this) on UI and on command line.
Running node v8.9.3 on Windows 7.

* **Expected result** (what you hoped would happen)
Imported the data from a given period without any errors or interruptions

* **Actual result** (unexpected outcome)
After some successfull batches it seems once we get an specific response error, the importer gets and error and closes.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
```
2018-01-02 13:04:47 (DEBUG):    Processing 999 new trades. From 2017-11-14 15:19
:39 UTC to 2017-11-14 16:09:39 UTC. (an hour)
2018-01-02 13:04:52 (DEBUG):    Processing 997 new trades. From 2017-11-14 16:09
:51 UTC to 2017-11-14 18:12:37 UTC. (2 hours)
2018-01-02 13:04:58 (DEBUG):    Processing 999 new trades. From 2017-11-14 18:12
:55 UTC to 2017-11-14 21:04:23 UTC. (3 hours)
2018-01-02 13:05:02 (DEBUG):    Processing 995 new trades. From 2017-11-14 21:04
:29 UTC to 2017-11-14 22:32:15 UTC. (an hour)
2018-01-02 13:05:07 (DEBUG):    Processing 999 new trades. From 2017-11-14 22:32
:33 UTC to 2017-11-14 23:59:13 UTC. (an hour)
2018-01-02 13:05:11 (DEBUG):    Processing 999 new trades. From 2017-11-14 23:59
:18 UTC to 2017-11-15 02:17:56 UTC. (2 hours)
2018-01-02 13:05:28 (ERROR):    [kraken.js] (getTrades) returned an irrecoverabl
e error: Response code 522 (undefined)
(node:25368) UnhandledPromiseRejectionWarning: Unhandled promise rejection (reje
ction id: 1): TypeError: Cannot read property 'date' of undefined
(node:25368) [DEP0018] DeprecationWarning: Unhandled promise rejections are depr
ecated. In the future, promise rejections that are not handled will terminate th
e Node.js process with a non-zero exit code.
```

**Comment by haccg** [comment]
You can try the develop branch. 
There are some fixes published regarding the kraken error retry handler
