### ISSUE TITLE
Kraken UnhandledPromiseRejectionWarning TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by SheppPL** [askmike/gekko#1613]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
livetrading with gekko on trading

* **Expected result** (what you hoped would happen)
place buy order on usd/bch

* **Actual result** (unexpected outcome)
This two errors:
(node:299) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'name' of undefined
(node:299) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
i think this line in kraken.js is causing this problem
    return callback(undefined, portfolio);

**Comment by billymcintosh** [comment]
Line 94 of `core/budfox/marketFetcher.js` has `this.exhange.name` instead of `this.exchange.name` - that's causing the issue. 

Unless fixed elsewhere, I'll create a PR when feeling a bit better.

**Comment by SheppPL** [comment]
thank you for reply and i will try to change it and see if this fix it

**Comment by billymcintosh** [comment]
PR here: https://github.com/askmike/gekko/pull/1629
