### ISSUE TITLE
Beginner and just want some simple answers

### ISSUE THREAD

**Issue by deejay100** [askmike/gekko#1615]
So I have a couple of questions so be patient with me please

So I successfully downloaded the gekko software manually.
I played around with the back test. I did not edit the js code. I just simply played around with differerent parameters on the backtest screen and i like the results it was producing. Again i have not touched any js at this point.

my 1st question would be.
as far as linking my binance account, is the api key and secret all i need to do for it to link to my gekko account? or do i need to do anything extra like download another file or code something, etc.

2nd, when I am running a live trading bot or a live market watch, does it has to be connect to the internet at all times? As in im running gekko on my laptop so im assuming 1. i cant leave the wifi im in so i cant travel with my laptop if i want gekko to run and 2. i cant allow my laptop to go to sleep... is that correct?

so overall i just want to link my binance account and run a live trading bot with the parameters i have chosen and enter on the DEMA strategy in the simplest way whether i gain or lose, i just want to see it actually do something (trades) reflecting on my binance account.

Im a visual learning and prefer like youtube videos and etc and i cant find any outside the ones saying how to install gekko. So reading instructions and implementing it has been a challenge for me

Thank you guys

**Comment by philmodin** [comment]
1. Key and secret is all you need to connect to your Binance. 

2. It definitely requires an active connection to communicate with Binance and read the market data. Also means, that yes, your computer must be fully awake and operational as long as you want Gekko to communicate with an exchange. Backtesting does not require a connection once you have imported your data.

If you want to commit to running Gekko (or any auto trader) for the long term you'd want to set up a dedicated node just for Gekko with reliable power and internet connection.

**Comment by askmike** [comment]
Apologies for the late reply. This is not a great place for asking these questions. Please see this page: https://gekko.wizb.it/docs/introduction/getting_help.html
