### ISSUE TITLE
[Question] Changing settings on live gekko trader

### ISSUE THREAD

**Issue by talentoscope** [askmike/gekko#1618]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[x] question 

Is it possible to change active trader parameters if after backtesting, we find better settings? 
Example:
Trader running with open position on BTC/USD
Through backtesting on newer data, I find settings that work better on my strategy.

How does it work? Do we need to kill gekko and start a new trader again?
What happens to the open position if it isn't closed? 
Does gekko see the changeover in currency as active BTC and close the open order?
Would the same problem occur with an open position if gekko crashed, i.e. would it require manual intervention on an exchange to close out the trade that is in progress?

**Comment by okonon** [comment]
@askmike interested in your insight regarding this

**Comment by askmike** [comment]
Apologies for never getting back on this:

> Do we need to kill gekko and start a new trader again?

Yes.

> What happens to the open position if it isn't closed?

Gekko will resume just fine, keeping your balance as is between restarts.

> Would the same problem occur with an open position if gekko crashed, i.e. would it require manual intervention on an exchange to close out the trade that is in progress?

If Gekko was in the middle of completing a trade while you restart it it might leave an order hanging. In the next version of Gekko we will cancel open orders on restart so this isn't an issue anymore.
