### ISSUE TITLE
ping pong strategy 

### ISSUE THREAD

**Issue by asemaniko** [askmike/gekko#1620]
ping pong strategy do you use ?

can you help me about settings

Thank you

**Comment by bitkominer** [comment]
Perhaps you can check [this #1252](https://github.com/askmike/gekko/issues/1252#issuecomment-358177758).

The strategy uses RSI to generate frequent signals that initiate BUY-SELL. Whatever the signals, it will make BUY & SELL orders at one time, with getting 0.5% price different between BUY & SELL.

![polo-pingpong](https://user-images.githubusercontent.com/21021582/35041504-eb09af5e-fb7c-11e7-9cee-05a3b14f2fdc.jpg)
