### ISSUE TITLE
Official gekko forum

### ISSUE THREAD

**Issue by askmike** [askmike/gekko#1621]
First of all: Happy new year, 2017 was a crazy year for the cryptocurrency markets and they show no way of slowing down.

Apologies for the absence, I have been away from the internet for a while. In order to bring some structure to the project I want to separate the sharing of ideas, discussions basic tech support away from the actual technical progress of the project. In order to do so I have created a new forum where everything (not directly related either new features being coded or bugs being fixed) can be discussed.

**The forum can be found here: https://forum.gekko.wizb.it/**

ping @cmroche @generalectric @thegamecat @djmuk @krieghof @imperator6 @danKHUU.

I want the forum to slowly move in towards a state where some people who like the project can help out and keep the forum clean, so that the project is not solely dependent on me being available.

**Comment by cloggy45** [comment]
Good idea.

**Comment by greenbigfrog** [comment]
Nice idea. I'd still recommend having something like an IRC channel or Discord which is a bit more real time. I'd also recommend setting up a few moderators in the current discord

**Comment by askmike** [comment]
Closing this since it's not an open issue (but please keep on commenting).

**Comment by askmike** [comment]
@greenbigfrog there was an IRC channel at some point and there is a discord channel now: https://discord.gg/26wMygt

However the main problem with realtime channels (for me personally) is that I can almost never be logged in (in realtime), so it's a terrible platform for me personally.

**Comment by greenbigfrog** [comment]
Totally understandable. It would help to have some structure/moderating in the discord though.

**Comment by askmike** [comment]
@greenbigfrog I (think I) made you admin now :)

**Comment by greenbigfrog** [comment]
Please check discord.
