### ISSUE TITLE
Gekko encountered an error and can't continue

### ISSUE THREAD

**Issue by thisledome** [askmike/gekko#1626]
Hi. So I installed Gekko on my mac.
Got it running fine. UI up and running on localhost 3000
anything I do in there is not functioning well it seems
was able to add API keys for poloniex.
importing a data set jus seems to sit there and do not much
If I try and enable a live gekko, it comes up  and says Gekko encountered and error and can't continue.
The market watcher page just has a moving thing in middle of screen and does nothing
backtesting doesn't do anything as no data set yet. but data set is flashing weird thing in middle of screen and seemingly does nothing else.

importing a data set gives the same message that Gekko encountered an error and can't continue.

any ideas please

**Comment by ghost** [comment]
I'm having the same issue each time an attempt to import data is made.

Here is what it looks like on the front-end: https://gyazo.com/c1127640944480ca9709834fc93f4dd3

Checked the console to see what's up and it only states that a non-specific error was encounted:

```
  <-- GET /api/configPart/candleWriter
  <-- GET /api/configPart/performanceAnalyzer
  --> GET /api/configPart/candleWriter 200 16ms 47b
  --> GET /api/configPart/performanceAnalyzer 200 0ms 144b
  <-- GET /api/strategies
  --> GET /api/strategies 200 15ms 2.02kb
  <-- GET /api/configPart/paperTrader
  --> GET /api/configPart/paperTrader 200 0ms 132b
  <-- POST /api/startGekko
Gekko 128975328524597 started
  --> POST /api/startGekko 200 31ms 148b
RECEIVED ERROR IN GEKKO 128975328524597


Gekko encountered an error and can't continue


Gekko encountered an error and can't continue

Error:

{}

Meta debug info:

Gekko version: v0.5.11
Nodejs version: v6.11.1
```

**Comment by thomashzhang** [comment]
+1 Same error here.
 I've tried a few different exchanges and time periods.

**Comment by thomashzhang** [comment]
I'd just like to note that this feature works correctly on the latest release, but not on the "stable" branch.

**Comment by thisledome** [comment]
I got this working also properly on the github clone.

Followed instructions and poof. Magic.

**Comment by ghost** [comment]
Yep. The issue was resolved for me by updating as well.

**Comment by bennycode** [comment]
I have the same issue with gekko. It worked yesterday and since today it's not working anymore.

**Screenshot:**

![image](https://user-images.githubusercontent.com/469989/36355137-fea2f0ea-14de-11e8-96e0-edf2ba2c3cdb.png)


Any solution to this?

**Comment by askmike** [comment]
@bennyn the error states that binance API wasn't working, it might have been a glitch with networking/their api.
