### ISSUE TITLE
Real-time orders through UI?

### ISSUE THREAD

**Issue by MasterJ09** [askmike/gekko#1634]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[x ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Set up live Gekko through "Live Gekkos"- Tradebot in the UI on my configured account on Bitfinex.

* **Expected result** (what you hoped would happen)
Orders being executed in my account on my exchange based upon the strategy and market watcher.

* **Actual result** (unexpected outcome)
In the UI, it displays two trades being done, It displays the graph, so all's well there and works like a charm. However there is no actual order in Bitfinex placed.
Can the UI place automated orders or can this be done solely through the commandline? What is the use case for providing the API key in the UI if orders can not be set in the UI?

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
If required through commandline, how to set up the configs file exactly?

Thanks sirs and great job!

Kind regards
Jochen

**Comment by coralgulf** [comment]
I have the same problem here, but working from the commandline is really no problem. Just copy and configure the sample-config.js to your personal settings (f. e. to config_LTC.js) and start with:

node gekko --config config_LTC.js

You can start several gekkos using different config....js. I made several sub-accounts with different API and inserted them like a new exchange. The advantage from the UI is, that several bots can work in one server window.

But the problem from the UI is for me also:

- No messages (f. e. pushbullet) even when pushbullet.toml is correctly activated
- There are less trades actually done (bitstamp) than reported in the UI
- All trades are not visible on the graph (when backtesting everything is fine)
- The server gives also no additional information for each trade

Backtesting works really fine, Tradebot via UI is not transparent in any way, regardless which strategy you are setting. The same configuration from CLI works.

**Comment by schroempf** [comment]
I think following is happening:

gekko relies on the last price only. Problem is, that in reality trades are happening according to ask and bid prices, you have to take those into account because those are much different from the last price, which is also not updated that often as the actual order prices (ask and bid). That must be the reason why the papertrader gives different results than the live trading bot.

I would think, thats a major issue, because you often cannot buy at the last price because its already not matching the buying price (ask) anymore.

Its the same with selling, but there it is the bid price to which you can actually sell.

also it is necessary to take the order amounts into account, because you can only buy that amount which is being offered. Same is with selling.

**Comment by hilkoc** [comment]
> Can the UI place automated orders or can this be done solely through the commandline? 

I have the same question. I can understand as @schroempf explains that the result of the paper trader and real trading can be different. However, this does not explain why the tradebot in UI does not execute any trades at all. Is there some config that needs to change for this or is it just not possible?

**Comment by schroempf** [comment]
You have to find a combination of  a market, a strategy and options for it which make it possible that the conditions in the strategy for a buy or a sell order are met. That you can find out with backtesting.

**Comment by hilkoc** [comment]
As a test case, I implemented this strategy

```
strat.check = function() {
    this.advice('long');
}
```
for testing, simply to open a long position. So I know for certain it's not an issue with the strategy. Yet it still does not do anything. I'm connecting to Kraken.

**Comment by schroempf** [comment]
Are you absolutely certain that you provided an apikey with sufficient permissions setup in your kraken-account? Also, despite of Kraken claiming to have updated its infrastructure, it is still horribly slow and unstable.

**Comment by hilkoc** [comment]
`Wanted to buy XBT but the amount is too small (0.048766418079) at kraken`

That is what I found in the log. I don't understand what this means. I have left more than 400 euros in my account for testing. It is plenty to put on trades manually.  I thought the 'long' advice would go long with the full amount available. I don't understand?

**Comment by hilkoc** [comment]
The minimum amounts in kraken.js were out of date. This is now fixed.
