### ISSUE TITLE
Trade with other coins

### ISSUE THREAD

**Issue by uzielroy** [askmike/gekko#1640]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[ X] feature request
[ ] question about the decisions made in the repository

*
How can i trade with other coins? i mean for example. btc <-> iota with binance

**Comment by cmroche** [comment]
PR #1550 already provides a solution for this, using a script to generate the market data and load that. IOTA is supported.

**Comment by dmitriz** [comment]
I got it working by uncommenting these lines:

https://github.com/askmike/gekko/blob/develop/core/exchangeChecker.js#L45-L56
