### ISSUE TITLE
Child process has died. Importing data.

### ISSUE THREAD

**Issue by ghost** [askmike/gekko#1642]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Configuring Binance.js to allow BTC trade against XRP.
Importing data.

* **Expected result** (what you hoped would happen)
Imported.

* **Actual result** (unexpected outcome)
Child process has died.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by philmodin** [comment]
How did you end up solving this?
