### ISSUE TITLE
GEKKO ERROR: Child process has died / Error: Cannot find module '/usr/src/app/core/../config.js'

### ISSUE THREAD

**Issue by ScottKane** [askmike/gekko#1643]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Tried to add a new live Gekko, tried to start and then got "GEKKO ERROR: Child process has died."
Looked in docker container to see what was happening, ran node gekko --config config.js and encountered the below error.

* **Expected result** (what you hoped would happen)
Gekko to start up and be able to live trade

* **Actual result** (unexpected outcome)

root@23b6670368a0:/usr/src/app# node gekko --config config.js

    ______   ________  __    __  __    __   ______
   /      \ /        |/  |  /  |/  |  /  | /      \
  /$$$$$$  |$$$$$$$$/ $$ | /$$/ $$ | /$$/ /$$$$$$  |
  $$ | _$$/ $$ |__    $$ |/$$/  $$ |/$$/  $$ |  $$ |
  $$ |/    |$$    |   $$  $$<   $$  $$<   $$ |  $$ |
  $$ |$$$$ |$$$$$/    $$$$$  \  $$$$$  \  $$ |  $$ |
  $$ \__$$ |$$ |_____ $$ |$$  \ $$ |$$  \ $$ \__$$ |
  $$    $$/ $$       |$$ | $$  |$$ | $$  |$$    $$/
   $$$$$$/  $$$$$$$$/ $$/   $$/ $$/   $$/  $$$$$$/

        Gekko v0.5.11
        I'm gonna make you rich, Bud Fox.

module.js:540
    throw err;
    ^

Error: Cannot find module '/usr/src/app/core/../config.js'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.getConfig (/usr/src/app/core/util.js:46:15)
    at Object.<anonymous> (/usr/src/app/core/log.js:13:19)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Wondered if it was file permissions, looked in the gekko root dir and found:
drwxr-xr-x.   2 root root      6 Jan  6 16:21 config.js
tried to read it (as I was root) and got "cat: config.js: Permission denied"

**Comment by ScottKane** [comment]
Also worth noting that even though the node startup gave an error I could still hit the front end and proceed to get the child process has died message.

**Comment by billymcintosh** [comment]
If it is owned by root and if you're running gekko as a regular user it won't be read in normal circumstances.   

It also looks like there's no config in the file... 6 bytes isn't going to do much. 

Try to delete it then copy sample-config.js to config.js and start again.
