### ISSUE TITLE
Paper trader does not perform trades regardless of strategy parameters and candle size.

### ISSUE THREAD

**Issue by ghost** [askmike/gekko#1644]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Adding API keys for my exchange.
Running paper trader with CCI strategy parameters unchanged
Candle Size sets to 1 minutes, 30 minutes, and sometimes 40 minutes.
Warmup period (no idea what is this for) sets to 1, sometimes 10.

* **Expected result** (what you hoped would happen)
Perfoming trades.

* **Actual result** (unexpected outcome)
No roundtrips data for 30 minutes or so.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by billymcintosh** [comment]
Sometimes it can take days for trades depending on your configuration and the trading pair you choose. 

Have a look at this: https://github.com/gekkowarez/gekkoga it can aid in choosing the right parameters for your chosen strategy.
