### ISSUE TITLE
Market watcher wrong time.

### ISSUE THREAD

**Issue by ghost** [askmike/gekko#1645]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Running market watcher on bitcoin-co-id

* **Expected result** (what you hoped would happen)
Show the correct time.

* **Actual result** (unexpected outcome)
It missed the time by 7 hours.
Actual time 2018-01-07 01.14 now, however Last Update 2018-01-06 18:11

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by rezamahesa** [comment]
Gekko based on UTC time

**Comment by cmroche** [comment]
Gekko is largely using UTC internally, so it may not be a bug per-se, however it could be changed to display in your local timezone if someone was willing to make a pass on all the use of dates in Gekko and clean that up.
