### ISSUE TITLE
Data spanning and backtest support for bitcoin-co-id

### ISSUE THREAD

**Issue by ghost** [askmike/gekko#1646]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[x ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Running market watcher

* **Expected result** (what you hoped would happen)
Data spanning can be configured.

* **Actual result** (unexpected outcome)
Data spanning read time randomly. (Data spanning 12 minutes) exactly after running market watcher.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
I don't understand gekko, yet. 

However, I believe those data will help Bot to decide when they need to execute trade, so if I set my candle size to 2 hours with warmup period of 10 (20 hours of history), probably the bot will only decide 1 trade per 2 hours. 

However, since the data spanning starts from 12 minutes ago, it forced me to wait for 2 hours (minus 12 minutes, probably around 1 hour and 48 minutes) for the bot to do a trade, isn't?

I do not use tradebot, yet. atm I am using paper trader (parameters, candlesize 35 minutes, warmup 90, probably around 2 days of history). atm no trade have ever been made.
 
Anyway could you please support bitcoin-co-id for backtest? https://vip.bitcoin.co.id/chart/btcidr it uses tradingview.

**Comment by jasonongputra** [comment]
Anyway could you please support bitcoin-co-id for backtest? https://vip.bitcoin.co.id/chart/btcidr it uses tradingview.

**Comment by rezamahesa** [comment]
u can built a data downloader for Gekko from https://bitcoincharts.com/charts, then copy data to Gekko/history/
see this [article](http://gekkowarez.com/download-category/trading-data/)

**Comment by jasonongputra** [comment]
I do not use Linux anymore, gonna try alternative. cheers mate thanks for the info.

**Comment by mr-standalone** [comment]
up vote this.

need backtest data integration for this exchange.
