### ISSUE TITLE
when add api key, chome conosole: this.apiKeySets.includes is not a function

### ISSUE THREAD

**Issue by northeastsquare** [askmike/gekko#1647]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ 1] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
add poloniex or binance api key

* **Expected result** (what you hoped would happen)
successful add api key for exchanges

* **Actual result** (unexpected outcome)
press add button, not any response
in chrome console:
Uncaught TypeError: this.apiKeySets.includes is not a function

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
Uncaught TypeError: this.apiKeySets.includes is not a function

**Comment by billymcintosh** [comment]
Could you copy and paste the stacktrace around the `Uncaught TypeError: this.apiKeySets.includes is not a function` message. 

Also, at the bottom of the page, what does it say?  

Mine has `Using Gekko v0.5.11 and Gekko UI v0.2.0.` and adding keys work as expected.

**Comment by northeastsquare** [comment]
Update chrome solve it
