### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by josh000111** [askmike/gekko#1651]
I’m in the process of trying to install Gekko. I'm on mac. I am not a developer so finding it a little complicated. I installed nodejs and then git and went through the installation process on the Gekko installation page, but the final installation command "node gekko —ui” produced the following error;

node gekko --ui
module.js:540
    throw err;
    ^

Error: Cannot find module '/Users/JoshSmith/gekko'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
Joshuas-MBP:~ JoshSmith$

Anyone have any suggestions?

**Comment by marleybobby** [comment]
Same problem on Windows 7. 
  

C:\Users\user\Downloads\gekko-develop\gekko-develop>node gecko --ui
module.js:557
    throw err;
    ^

Error: Cannot find module 'C:\Users\user\Downloads\gekko-develop\gekko-de
velop\gecko'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3

**Comment by josh000111** [comment]
Glad to hear I didn't botch the installation! Is this a bug, someone?

**Comment by jforaker** [comment]
@JamieJ1 the `Joshuas-MBP:~ JoshSmith$` bit suggests you might not be in the project directory...

after `git clone` did you change directory into the new gekko directory with `cd gekko`?

**Comment by josh000111** [comment]
thanks for reply. will check this out tomorrow
