### ISSUE TITLE
Child process has died when import data

### ISSUE THREAD

**Issue by zhoujinhai** [askmike/gekko#1654]
![image](https://user-images.githubusercontent.com/20365125/34674562-64fb2f8a-f4c1-11e7-903b-35dfce3ce6d1.png)

**Comment by cloggy45** [comment]
I've been able to recreate this problem, so I will look into it.

**Comment by zhoujinhai** [comment]
thanks

**Comment by cmroche** [comment]
@cloggy45 If you are inclined, please take a look at the new approach for error and retry handling done in Kraken (also in the "Adding an Exchange" documentation). Updating BTCC to this standard would make it much more durable against API errors.

**Comment by cloggy45** [comment]
@cmroche Thanks for the heads up, I've been busy with work, but it seemed the BTCC API implemented isn't working properly, so I will look into. Thanks for the heads up.

**Comment by cloggy45** [comment]
```
jse_shortmsg: 'BTCChina.executeRequest() HTTP status code 404 returned from GET request to url https://api.btcchina.com/data/ticker with parameters {"market":"BTCCNY"}. Status message: Not Found',
  jse_summary: 'BTCChina.executeRequest() HTTP status code 404 returned from GET request to url https://api.btcchina.com/data/ticker with parameters {"market":"BTCCNY"}. Status message: Not Found',
  message: 'BTCChina.executeRequest() HTTP status code 404 returned from GET request to url https://api.btcchina.com/data/ticker with parameters {"market":"BTCCNY"}. Status message: Not Found',
```
Errors are generated when using the default btc-china-fork.
