### ISSUE TITLE
Unexpected behavior. Hardcode of port number detected.

### ISSUE THREAD

**Issue by fshalor** [askmike/gekko#1659]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Standard install 
1. Git clone on an fresh node LTS 8 install from npm. Ubuntu 16.04 all normal current patches.
2.npm install --only=production
3. Change to folder and edit the following two files:
  ~/gekko/.env   # Change 3000 to 9100
  ~/gekko/web/vue/UIconfig.js # Change local host to 0.0.0.0, or IP, and port to 9100
  cd ~/gekko/  ; Launch tmux, execute "node gekko --ui"

 * **Expected result** (what you hoped would happen)
Gekko should now be listening on all ip address on port 9100

* **Actual result** (unexpected outcome)
Actual result: Gekko is still listening on port 3000 localhost only.

root@kira:/etc/nginx/sites-available# lsof -i :3000
COMMAND   PID  USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
node    31378 gekko   12u  IPv4 6371903      0t0  TCP localhost:3000 (LISTEN)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
I am wondering whether one of the layers of config overlaps is being circumvented. 
Gekko reports the correct outcome, but it is not actually doing what it says it is doing. Even though the following is being reported, nothing is listening on port 9100. 

node gekko --ui

    ______   ________  __    __  __    __   ______
   /      \ /        |/  |  /  |/  |  /  | /      \
  /$$$$$$  |$$$$$$$$/ $$ | /$$/ $$ | /$$/ /$$$$$$  |
  $$ | _$$/ $$ |__    $$ |/$$/  $$ |/$$/  $$ |  $$ |
  $$ |/    |$$    |   $$  $$<   $$  $$<   $$ |  $$ |
  $$ |$$$$ |$$$$$/    $$$$$  \  $$$$$  \  $$ |  $$ |
  $$ \__$$ |$$ |_____ $$ |$$  \ $$ |$$  \ $$ \__$$ |
  $$    $$/ $$       |$$ | $$  |$$ | $$  |$$    $$/ 
   $$$$$$/  $$$$$$$$/ $$/   $$/ $$/   $$/  $$$$$$/

	Gekko v0.5.11
	I'm gonna make you rich, Bud Fox. 

Serving Gekko UI on http://0.0.0.0:9100/

**Comment by billymcintosh** [comment]
Change both ports in `UIconfig`.  Unless you're using Docker, you can ignore `.env`

**Comment by fshalor** [comment]
Did that. App still listened on 3000 but reported 9100 in the console.

**Comment by billymcintosh** [comment]
Just tested and although it didn't listen on :3000,  the server part didn't work with `0.0.0.0`. 

When I entered my proper internal IP address instead of `0.0.0.0`, it worked as expected.
