### ISSUE TITLE
Add Pairs Bitttrex ADA, BTG, OMG

### ISSUE THREAD

**Issue by eduardoarn** [askmike/gekko#1660]
[ ] bug report
[x ] feature request
[ ] question about the decisions made in the repository

Just add a few USD trading pairs that I use on Bittrex, the ADA, BTG and OMG 
`
assets: [
      '1ST', '2GIVE', (....) 
      ,'BTG','OMG','ADA'
(....)

      { pair: ['USDT','NXT'], minimalOrder: { amount: 0.00000001, unit: 'asset' }},
      { pair: ['USDT','BTG'], minimalOrder: { amount: 0.00000001, unit: 'asset' }},
      { pair: ['USDT','OMG'], minimalOrder: { amount: 0.00000001, unit: 'asset' }},
      { pair: ['USDT','ADA'], minimalOrder: { amount: 0.00000001, unit: 'asset' }},`

**Comment by billymcintosh** [comment]
Looks like you've done the work already.   Got a pull request?

**Comment by eduardoarn** [comment]
I made a request to pull there.

**Comment by dmitriz** [comment]
But why isn't Gekko supporting all pairs by default?

```sh
 ERROR: Gekko only supports the assets [ BTC, BCC, BCG, BNB, DASH, ETH, ETC, EOS, NEO, OMG, POWR, QTUM, ZEC ]  at Binance (not ARK)
```
 The pair ARK/ETH is on the exchange.

**Comment by dmitriz** [comment]
Just experimented uncommenting those lines in

https://github.com/askmike/gekko/blob/develop/core/exchangeChecker.js#L45-L56

enables the import without any problems. Seems like these guards are pointless.
