### ISSUE TITLE
Disable requesting Trade Data log.

### ISSUE THREAD

**Issue by krieghof** [askmike/gekko#1662]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[x ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Started a live bot in the cli

* **Expected result** (what you hoped would happen)
Only output to the terminal the advice.

* **Actual result** (unexpected outcome)
The terminal is spammed with requesting trade data and have to search for the important logs.

Is it somehow possible to disable the request trade data output.

**Comment by krieghof** [comment]
Here is an example from the output.  

[BCH-USD-out-8.log](https://github.com/askmike/gekko/files/1619485/BCH-USD-out-8.log)

**Comment by billymcintosh** [comment]
`config.debug = false;` in your `config.js` should do it
