### ISSUE TITLE
MinimalOrder at Bitfinex on IOTA/USD

### ISSUE THREAD

**Issue by Daewju** [askmike/gekko#1669]
* **I'm submitting a ...**
[X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
I've started the live trading bot.

* **Expected result** (what you hoped would happen)
It should create only orders above minimalOrder at Bitfinex on IOTA/USD.

* **Actual result** (unexpected outcome)
It creates orders below minimalOrder at Bitfinex on IOTA/USD.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, { change this line => pair: ['USD', 'IOT'], minimalOrder: { amount: 0.01, unit: 'asset' } },
to => { pair: ['USD', 'IOT'], minimalOrder: { amount: 6.00, unit: 'asset' } },
in => exchanges/bitfinex.js

**Comment by cmroche** [comment]
This would likely be fixed by PR #1550 which correct the minimalOrder data for products in Bitfinex.
