### ISSUE TITLE
More then 1 pair at a time?

### ISSUE THREAD

**Issue by MIKEYCRYPTO** [askmike/gekko#1670]
Is it possible to run a Live Gekko in separate nodeJS windows if they are calling another config.js file?

Can you have 1 window running ETH/XRP  looking at config.js
Window # 2 running BTC/SC looking at config2.js 
Window #3 running ETH/ETC looking at config3.js

What I am trying to do is have gekko trade all of my coins during the day.   Not just the 1 pair that it is limited to.

I'm sorry if this was covered before.

**Comment by Momohime** [comment]
Yes, just specify a different config.js file with the -c prefix.

**Comment by billymcintosh** [comment]
I recommend having completely different pairs if running on the same exchange.   

Having both ETH/XRP & ETH/ETC opens up potential to conflict and lose (or gain!) you money in your example above.

**Comment by ivandompe** [comment]
HI guys, I'm new to Gekko and I'd like also to run tradebot on several pairs on the same exchange.
I don't understand which setting and where I have to change. Could someone explain me how to do so? I didn't found the config.js

**Comment by billymcintosh** [comment]
@ivandompe - don't do it unless you're confident with the code and losing doesn't make you angry :)

If you really want to trade several pairs simultaneously on the same exchange...   CLI.

**Comment by ivandompe** [comment]
Thanks billymcintosh, well I was wondering to not have several exchange instead.. but ok I understand why it could lead to bad move with a single exchange. I will then open new account. Thx for your feedback. :-)

**Comment by billymcintosh** [comment]
You're welcome.    It's possible on the same exchange with completely different pairs.   

For example;
ETC/BCH
and
ETH/BTX 

They will not compete with each other and trades will be completely independent.

**Comment by ivandompe** [comment]
Hi Billy,

Ok then I would maybe try. So if I understand correctly, I need for this
(trading on different pairs) use command line?
When yes, what I need to do? How to execute tradebot on these pairs?

Sorry for that question, but I'm using UI for the moment. But not an issue
if I have to run command line ;-)
See in attachment, the documentation is not clear for me.. do I have to
modify that files?
Thanks a lot for your support.

Regards

2018-01-27 14:45 GMT+01:00 Billy McIntosh <notifications@github.com>:

**Comment by ivandompe** [comment]
Hello, I'm sorry to come back again, I'm trying to get a right setup to start with the command line.
Do I have to set my strategy into config.js or somewhere else? I'm confused.
Thx

**Comment by billymcintosh** [comment]
Alright dude.    It's up to you, but I recommend trading completely different pairs on the command line and the UI.  

You need to pass in the argument for your configuration file like so;
`node ./gekko.js --config yourBTCconfig.js` 
`node ./gekko.js --config yourETHconfig.js`

Gekko is reasonably stable but it can die - use pm2 :)

**Comment by ivandompe** [comment]
I was finally able to manage it. :-)
Hope my strategies will work!

**Comment by billymcintosh** [comment]
Good luck!   If they work,  share :)

**Comment by Paulovms** [comment]
I’m running 13 gekko instances with PM2.
![13 gekko instances](https://image.ibb.co/cAVxjG/959_ADD2_F_91_C9_4454_919_A_2_C0975268006.jpg)

**Comment by ivandompe** [comment]
Nice @Paulovms ! I have to explore pm2. My script are running on OS X for the moment ;-)
Thx @billymcintosh , I will share! I was able to set 3 differents tradebot. They are now running, will see what happens. I use ETH/USDT, LTC/XMR & STR/BTC as pairs. All of them with TSI strategy based. They give me +25-35% of profit via back testing. Fingers crossed!

**Comment by billymcintosh** [comment]
Good luck Ivan.   Please change this title from "then" to "than".  That really fucking annoys me and I will kill people.

**Comment by ivandompe** [comment]
I'm unfortunately not the initiator of this issue, I can't change the title. Have a good day.

**Comment by askmike** [comment]
This question should now be answered. If people want to continue this discussion please do so on the forum: https://forum.gekko.wizb.it/
