### ISSUE TITLE
import data from Binance is broken

### ISSUE THREAD

**Issue by gen4sp** [askmike/gekko#1671]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Tryied to import historical data from Binance

* **Expected result** (what you hoped would happen)
Progress should be started at least

* **Actual result** (unexpected outcome)
Only "spinner" or "loading waves" are shown. Importing never done.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by cmroche** [comment]
Importing should be fixed on the develop branch now I think. There was an API change around christmas that broke this.

**Comment by gen4sp** [comment]
@cmroche it works on development branch, thanks

**Comment by jsubirat** [comment]
Could it be that this issue is happening again? I attempted 3 imports right now with the latest gekko version (just pulled it from git), with 3 months of historical data each:

- BTC/ONT: import stuck forever on the "spinner" or "loading waves"
- BTC/POA: import stuck forever on the "spinner" or "loading waves"
- BTC/ADA: works

Any ideas? Thank you in advance!

**Comment by cmroche** [comment]
@jsubirat I'll need to know the precise dates being used for import, also please create a new issue and ping me by adding @cmroche into the post (GitHUB will notify me directly of the issue you created). I'll try to look at the problem over the weekend.

Also if you could enable debug logging by setting debug = true in web/routes/baseConfig.js and check the output once it gets stuck it would help a lot.

Thank you.

**Comment by xFFFFF** [comment]
Tadam: https://github.com/xFFFFF/Gekko-Datasets
Here is ready to use imported db files.

Just download interesing file, copy to history folder in Your Gekko and restart Gekko. Download is faster than import via API. Files are update one time per day.
