### ISSUE TITLE
Gekko in Tor Browser for Safe browsing

### ISSUE THREAD

**Issue by zabavaklubniki** [askmike/gekko#1677]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
I wanted to start the localhost:3000 in the Tor Browser, but it didn`t work. In Chrome it is no problem, what is the reason?

Thank You!

* **Expected result** (what you hoped would happen)

* **Actual result** (unexpected outcome)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by billymcintosh** [comment]
Unless you want to host Gekko as a Tor service, there is absolutely no point running Tor Browser and accessing your localhost.   You have one hop.  Use SSL if you need encryption:   https://letsencrypt.org/

It's not advisable to host Gekko elsewhere and use Tor to access it either.

If you really must use Tor Browser, have a look at this: https://tor.stackexchange.com/questions/11994/how-to-access-local-host-through-tor-browser/11997

**Comment by askmike** [comment]
If you really can't risk running a browser, use the commandline interface (either locally or over ssh). Instructions on how to setup gekko can be found here: https://gekko.wizb.it/docs/commandline/about_the_commandline.html

The UI is way to dynamic and needs to javascript in order to run properly.
