### ISSUE TITLE
Binance new assets

### ISSUE THREAD

**Issue by gen4sp** [askmike/gekko#1678]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Trying to import some assets history data from Binance

* **Expected result** (what you hoped would happen)
All assets list should be present

* **Actual result** (unexpected outcome)
There aren't a few new assets

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
How to add new assets? Or maybe there is a way to fetch and use assets automatically?

**Comment by cryosx** [comment]
edit exchanges/binance.js

add you asset to the list of assets and then add your pair down below it with the rest of the pairs.

Pair info: https://www.binance.com/exchange/public/product
tickSize -> precision
minTrade -> amount

**Comment by askmike** [comment]
I would love a PR once you added some!

**Comment by mronus** [comment]
PR created #1700
