### ISSUE TITLE
Waiting for at least one trade... ???

### ISSUE THREAD

**Issue by zabavaklubniki** [askmike/gekko#1684]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Installed Gekko and Dependencies on Windows 7 with cmd.exe. 
Ui is running and i made config.js enabling trading. 
when i go to livetrading in the browser (localhost:3000) i can config a market, the currency, the asset, the trading method, the intervall, etc.

when i go on start a live market, only the market watcher comes up and the notice: "waiting for at least one trade..." appears where the trading result should come. 

so finally, no trading.

btw, how can i configure the candleinterval (minutes, hours, days) on config.js?

Thank you!

* **Expected result** (what you hoped would happen)

* **Actual result** (unexpected outcome)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
Gekko is not a bot that you can download, turn on and will do a lot of trades. Gekko only trades when your (configured) strategy comes out with an advice. When it says that it has not happened yet.

 If you have more questions please ask them on the forum: https://forum.gekko.wizb.it/

I am closing this as it's a technical bug tracker.
