### ISSUE TITLE
url note working

### ISSUE THREAD

**Issue by Zooman090** [askmike/gekko#1690]
* **I'm submitting a bug report**

* **I tried visit this url https://github.com/askmike/gekko/blob/stable/docs/internals/plugins.md#redis-beacon**

* **I hope read about `Redis beacon`**

* **I can't do that read.**

**Comment by billymcintosh** [comment]
https://github.com/askmike/gekko/blob/develop/docs/commandline/plugins.md

**Comment by askmike** [comment]
I just removed the link from the docs, it was outdated. The Redis Beacon is a plugin that will broadcast Gekko events over redis pub/sub, so these events can be used outside gekko (or nodejs). If you encounter any problems using it let me know :)
