### ISSUE TITLE
[request] option to be a market taker

### ISSUE THREAD

**Issue by redquicksilver** [askmike/gekko#1695]
I have been using your excellent tool for about a month now and have a strategy that I like using, and on paper and for real using charts, however the problem is the latency at which my orders get taken due to the fact that they are makers and not fulfilled quickly.  It can take minutes to fill my buy or sell orders and as such the price has changed drastically and I am not making any money, in fact the vast majority of my round-trips are losses, but they should be wins.

I am trading on GDAX.

For example, I went into a long at 1012 and as such Gekko created a 'buy' which was only completed 4 minutes later when the price was 1020 which is when it started to fall, so a 'short' was created and that only completed a further 4 minutes later and was sold at 1014.

To counter-act this how plausible is it to have an option to make it a taker and hence fulfill immediately, as whilst we will have to pay fees, I think the money we are losing due to not completing when we should will more than cover it.  Or it tries a 'make limit' order, and if that isn't fulfilled, a 'take' is done to close the deal?

I have tried setting the 'post_only' flag to false, and this stops any trades from being made.

I could look at this myself being a software developer, however I thought I would ask the question as I am sure that this has been thought of in the past and that there is a good reason why this hasn't been implemented.

Many thanks for your time looking at my question.
Kind Regards,
Stephen

**Comment by PanoPilot** [comment]
@redquicksilver I am was considering this as well. did u made those changes to the by yourself or did u just skipped your idea?

**Comment by xerviami** [comment]
Dear,

I would also like to have such an option (be a market taker).
Is that possible ?

Thank you in advance
Xavier

**Comment by FreshLondon** [comment]
+1

**Comment by askmike** [comment]
In the future this will be possible through Gekko Broker, see here for details: https://github.com/askmike/gekko/blob/gekko-trader/docs/gekko-broker/introduction.md
