### ISSUE TITLE
Relative Momentum, strategy that switches assets?

### ISSUE THREAD

**Issue by tommiehansen** [askmike/gekko#1698]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository

---

Are there any plans to make it possible to switch assets dynamically within strategies? A very simple one would be a relative momentum aggregate strategy (MOM+AGG) with these rules (short):

1. Have a universe of **A** assets e.g. BTC, ETH, XRP, XMR, BCH etc (one should be able to update this)
2. Every **B** minute/hour/day check past performance of **C** period
3. Invest in top **D** best from the universe

...and a longer version:

**Universe**
https://bitscreener.com/screener/overview?timeframe=1w&f=mkt_gte_1b,e_Binance,ord_perf_1w_desc
_Writing all coins would be tedious so i'll simply refer to a screener with presets._

**Rules**
Timing Period: 7 days _(check past performance of 7 days)_
Trading frequency: 3 days _(check and act upon the data every 3 days)_
Assets to hold: 5 _(invest in top 5 out of X total)_
Risk control: Moving Average; 20 days _(optional, if asset < MA20 discard the asset)_
Out of market asset: USD _(if everything returns 'false' on the rules go 100% 'safe asset')_

With these rules the strategy would currently invest in these coins (16 jan 2017):
NEO, EOS, VEN, USDT, ETC

---

If you would want to get a more detailed idea on how this works visit portfoliovisualizer.com:
https://www.portfoliovisualizer.com/test-market-timing-model

1. Choose 'Relative Strength'
2. Add a bounch of tickers, fix settings etc
3. Run it

---

Why "complicate" things?
Since we simply do not know the future and what assets that will become good in X amount of time in that future. This is basically a way to automate such decisions and making Gekko even more 'hands off'.

**Comment by mronus** [comment]
I totally agree with you. It would be great to have such a feature, but I am not sure whether this can be done without breaking the structure of Gekko.

**Comment by tommiehansen** [comment]
I don't really see a breaking problem?

This is basically what needs to be done:
1. Create a screener that I includes assets a, b, c...
2. Check this screener every X amount of time
3. Buy/sell depending on that screener (and user settings)

Checking for a, b, c... is a core part of the app.
The only thing here not being a core part is basically only the screener?
