### ISSUE TITLE
best  strategy

### ISSUE THREAD

**Issue by wupeng1211** [askmike/gekko#1701]
![screenshot-2018-1-16 gekko 1](https://user-images.githubusercontent.com/6904999/34993527-919918fe-fb0b-11e7-982e-948aad2b1e92.png)

**Comment by aorfevre** [comment]
are you willing to share your strategy ? Or just sharing your result ?

**Comment by mauroprojetos** [comment]
Cool, I'm interested too.
Did you develop this strategy?

**Comment by chopbk** [comment]
Can use share your strategy? Thank you so much

**Comment by Mattiell0X** [comment]
Sincerely in my opinion this profit did not come from the strategy but rather because 2 weeks ago the XRP had a high price history almost tripled, and only fact to have a long that was opened at the right time and closed at the right time depending on the value purchased it would profit easily. So do not be fooled by these data ... this guy is rolling, if it was some real strategy, this guy would have already posted. And dude, what do you have to tell us? !!!

**Comment by wupeng1211** [comment]
@mrrobots @tsuperprince @mauroprojetos @aorfevre ![screenshot-2018-1-18 gekko](https://user-images.githubusercontent.com/6904999/35104037-a23374a0-fca2-11e7-8639-bbd9b98c8bcf.png)

**Comment by wupeng1211** [comment]
![screenshot-2018-1-18 gekko 1](https://user-images.githubusercontent.com/6904999/35104398-af4c31da-fca3-11e7-9ffe-43460e83725a.png)

**Comment by joshtyIN** [comment]
How can I get the Bestone strategy?

**Comment by BenVlodgi** [comment]
@wupeng1211 looks good man, hows it been performing in live paper trading?

**Comment by stfnschfr** [comment]
Very nice! I'm working on a custom strat using RSI + MACD + Bollinger bands but haven't had success like this.

Bravo.

**Comment by federosso** [comment]
it could be that he integrated this:
https://github.com/wupeng1211/convnetjs
 into his strategy ..
Some big mind willing to try?

**Comment by bitkominer** [comment]
Hi @wupeng1211, would you like to share with us how to set it up? It's such a wonderful backtest result. Thanks!

**Comment by wupeng1211** [comment]
![screenshot_20180120-135823](https://user-images.githubusercontent.com/6904999/35180377-1f335a86-fdea-11e7-8c0b-2ba23a5e4e2d.png)

**Comment by chopbk** [comment]
Hi @wupeng1211, would you like to share with us how to set it up? Thanks!

**Comment by Mattiell0X** [comment]
Lets go to what matters! which strategy? Share it!

**Comment by ansonphong** [comment]
Haha, tease. I'd be very impressed if it behaves like this on a live market. Curious to see the methods used.

**Comment by ansonphong** [comment]
This might be a clue:
https://github.com/wupeng1211/convnetjs

**Comment by John1231983** [comment]
Do you want to show that your work is best one and we must pay money to buy it? Please said something instead of showing your result

**Comment by anondontlikepeng** [comment]
I found this:
https://github.com/cloggy45/Gekko_Trading_Resources
it includes a bestone strategy and convnetjs.

Did not tested it yet. Hope you guys here can do somthing big with it.

**Comment by Zamora7** [comment]
@wupeng1211 interested in selling this strat?

**Comment by stfnschfr** [comment]
![covnet](https://user-images.githubusercontent.com/16762976/35641769-18423e10-068f-11e8-823c-9c3c9c0c2958.png)

**Comment by greenbigfrog** [comment]
@askmike do you really want to permit this kind of discussion happen in the github issues? This is sth that would fit into that forum of yours.

**Comment by markvdberg0** [comment]
https://github.com/wupeng1211/gekko/commit/943ae1938be5d876848cb7f5250b98c1931d0572

**Comment by shnonr** [comment]
How Can I add this strategy to my gekko bot? Could you explain it for me?
I'm newbie to nodejs.

**Comment by hugokoopmans** [comment]
hah i am afraid @wupeng1211 has highly overfitted the past two months worth of data, now a run like that on `unseen` (or out of sample) data would be impressive ;-)

**Comment by jamesdio** [comment]
@wupeng1211 awesome strategy! if you don't mind could you explain what kinds of indicators you've applied to your strategy?

**Comment by Forallatlantis** [comment]
Does anyone was able to install convnetjs or Gekko_Trading_Resources or find out what is WuPeng's strategy?

**Comment by githubdavid8** [comment]
@wupeng1211 Your result is good. I download from here.
 https://github.com/cloggy45/Gekko_Trading_Resources and follow instruction, get the beststone listed in stretegy,  and in Parameters, how nothing. also, backbest with no result. Can you share more details ?

**Comment by kifirkin** [comment]
@githubdavid8 This strategy works better when you treat result as `overbought` and `oversold` instead of `uptrend` and `downtrend`, and advice opposite things like when you in downtrend - you buy, uptrend - sell

I've tested it with pair wich in a sideways and got little profit in short periods trading, but for long periods I guess it wont work

**Comment by rafaeldelucena** [comment]
@alexmironof do you got the same results from wupeng's bestone?

**Comment by kifirkin** [comment]
@rafaeldelucena actually I'am playing around with 4$ on my balance at `wex.nz - NMC/USD`, after a week  I've got 5$ so far :sweat_smile: and I continuously improving this strategy. I guess in a few days I'll put it on my own repo

**Comment by Mattiell0X** [comment]
Have you tried the exchange with real money? If so, which exchange? I have
in account bitfinex does anyone know if it works there?

2018-03-13 17:59 GMT-03:00 Aleksei Mironov <notifications@github.com>:

**Comment by FreshLondon** [comment]
I've only been running this strategy for a couple of hours so let's not jump to conclusions yet..

I'll update later on today/tomorrow if it's actually working as expected.
Seems too farfetched although it is making a good percentage in the short term, let's see.

Gekko was configured a little differently than usual, and configured to run fast in bad environments. I got good results, only when switching to a few months trading do I see the below result on a backtest.. thought it was worth sharing, even if only a bug ;)

![screen shot 2018-05-17 at 13 08 12](https://user-images.githubusercontent.com/17095036/40157932-3f99e876-59d4-11e8-9de8-6e16f65de661.jpg)

**Comment by hypery2k** [comment]
can you share your strategy details?

**Comment by xFFFFF** [comment]
In my opinion, a single result does not indicate anything. Show results on 10 pairs or different periods, min. 1 month and candles more than 1 minute. In live and limit order, such results are almost impossible. I could make 10 such results with one of the strategies I know, however, I do not want to waste time on something that exists only in backtests.

**Comment by FreshLondon** [comment]
> can you share your strategy details?

After some testing and confirmation, which i doubt will ever come through, sure.

> In my opinion, a single result does not indicate anything. 

Agreed

> Show results on 10 pairs or different periods, min. 1 month and candles more than 1 minute.

I only use 1min candles, low satoshi currencies.

> such results are almost impossible. I could make 10 such results with one of the strategies I know, however, I do not want to waste time on something that exists only in backtests.

Indeed, as per my "thought it was worth sharing, even if only a bug ;): comment above.

**Comment by xFFFFF** [comment]
> I only use 1min candles, low satoshi currencies.

So good luck in live trading :)

Backtest is filling out orders without any delay. There is a client-server/query-response delay in live, it is difficult to complete the order in 1 minute on pairs with low volume. Sometimes it takes up to 10 minutes. Of course I am talking about LIMIT order, I have not tested what it looks like on MARKET orders. However, if your strategy generates 10 or 100 trades trades per day with a 0.05% profit, it is doubtful that it works well in live. These trades will simply be a loss, not a profit.

**Comment by FreshLondon** [comment]
> However, if your strategy generates 10 or 100 trades trades per day with a 0.05% profit, it is doubtful that it works well in live. These trades will simply be a loss, not a profit.

Agreed, only using an exchange with a 0.05% fee this strategy backtested well  ..and thats not taking into account it's currently reporting badly due to only showing the completed trades, not the partially filled orders.

For example, Gekko sends a buy order thats completed 65%. The order gets adjusted, the order is completed. Gekko then reports the order as bought once it's fully completed and tracks its progress from there (despite balance).

I quite a bit of trading bot experience, I'm very well aware that backtesting is not a true indicator of live results.
I'll keep running it for at least 24hrs and get a good idea of what to adjust, but yes I agree with your points hence my comment on the original post.

**Comment by IAMtheIAM** [comment]
Where did this discussion end up moving to?

**Comment by sepeedar2014** [comment]
@anondontlikepeng bestone strategy is not in the strategy folder.
where should I get it?
