### ISSUE TITLE
Feature question...

### ISSUE THREAD

**Issue by bendake** [askmike/gekko#1707]
I wanted to know if the custom scripts allows you to create your own script that does not depend on any TA, I just want to use it to buy and sell a pair at a set price based on variables calculated in the JS...is that possible with your platform?

i.e. If current market price is 100, then place an order to buy at 90 and if that executes, to sell at 110 (very simplified, but that is the concept)...all of the math and scripting will be inside of JS, just want to use the platform to access the exchanges.

-Thanks!

**Comment by laravellously** [comment]
@bendake You just have to create your own strategy (say, MyStrat.js) and save it to the /strategies folder. Then edit the config.js in the root folder of gekko-stable, to include your strategy (in config.TradingAdvisor.method) and your exchange/currency pair (in config.watch) . To run the bot, use in Bash `node gekko -c config.js`. Hope that helps.

**Comment by bendake** [comment]
@laravellously yes that does help thank you, If the JS is complex and does a lot of API calls, changes things constantly and loops through the code, will gekko handle that, or is it just for TA? Can I do what I described in the original post and buy and place orders and then cancel those orders based on the JS code?

**Comment by askmike** [comment]
@bendake you can script whatever you want in your strategy (does not need to use TA), HOWEVER:

> i.e. If current market price is 100, then place an order to buy at 90 and if that executes, to sell at 110 (very simplified, but that is the concept)

Your strategy cannot control how orders get executed, it can only "advice" when to buy or sell. I am working on modularising Gekko to be able to do other things like what you describe.

> @laravellously yes that does help thank you, If the JS is complex and does a lot of API calls, changes things constantly and loops through the code, will gekko handle that, or is it just for TA? 

Yes: you can put whatever type of js in your strategy, do note: if you put anything in there that relies on anything else than candle data (current system time, external API calls, etc) you cannot backtest the strategy anymore. But you can definitely run it live :)

**Comment by askmike** [comment]
I would love to continue the discussion (on extending Gekko to do things like requested here). However this issue tracker is not the best place. If you want to talk more about extending Gekko please post here: https://forum.gekko.wizb.it/forum-15.html
