### ISSUE TITLE
stochK and stochD returns an undefined error

### ISSUE THREAD

**Issue by ipansensoy** [askmike/gekko#1709]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[* ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
i have this code 
`
  this.addTulipIndicator('myEma', 'ema', this.settings.ema);
  this.addTulipIndicator('myStoch', 'stoch', this.settings.stoch);

}

// What happens on every new candle?
strat.update = function(candle) {

  this.precision = 5;
  this.ema = parseFloat((this.tulipIndicators.myEma.result.result)).toPrecision(this.precision);
  this.stochk = parseFloat(this.tulipIndicators.myStoch.result.stochK).toPrecision(this.precision);
  this.stochd = parseFloat(this.tulipIndicators.myStoch.result.stochD).toPrecision(this.precision);
  this.closingPrice = parseFloat(candle.close).toPrecision(this.precision);
   console.log(this.tulipIndicators);
}

// For debugging purposes.
strat.log = function() {
  log.debug("\tEMA - " + this.ema);
  log.debug("\tStock K - " + this.stochk);
  log.debug("\tStock D - " + this.stochd);
  log.debug("\tClosing Price - " + this.closingPrice)
}`

* **Expected result** (what you hoped would happen)
im expecting a stochK and stochD value

* **Actual result** (unexpected outcome)

`
  this.addTulipIndicator('myEma', 'ema', this.settings.ema);
  this.addTulipIndicator('myStoch', 'stoch', this.settings.stoch);

}

// What happens on every new candle?
strat.update = function(candle) {

  this.precision = 5;
  this.ema = parseFloat((this.tulipIndicators.myEma.result.result)).toPrecision(this.precision);
  this.stochk = parseFloat(this.tulipIndicators.myStoch.result.stochK).toPrecision(this.precision);
  this.stochd = parseFloat(this.tulipIndicators.myStoch.result.stochD).toPrecision(this.precision);
  this.closingPrice = parseFloat(candle.close).toPrecision(this.precision);
   console.log(this.tulipIndicators);
}

// For debugging purposes.
strat.log = function() {
  log.debug("\tEMA - " + this.ema);
  log.debug("\tStock K - " + this.stochk);
  log.debug("\tStock D - " + this.stochd);
  log.debug("\tClosing Price - " + this.closingPrice)
}`
* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Already loade tulind for this and is loaded already why is it im getting an undefined error?

**Comment by ipansensoy** [comment]
`var _ = require('lodash');
var log = require('../core/log.js');

var EMA = require('../strategies/indicators/EMA');

// Let's create our own strategy
var strat = {};

// Prepare everything our strat needs
strat.init = function () {
    // your code!
    log.debug('Initalising Scalping Strategy');
    this.name = 'scalp';
    this.previousaction = 'sell';

    this.trend = {
        direction: 'none',
        condition: 'none',
        duration: 0,
        persisted: false,
        adviced: false
    };


    this.addTulipIndicator('myEma', 'ema', this.settings.ema);
    this.addTulipIndicator('myStoch', 'stoch', this.settings.stoch);

}

// What happens on every new candle?
strat.update = function (candle) {
    this.precision = 5;
    this.ema = parseFloat(this.tulipIndicators.myEma.result.result).toPrecision(this.precision);
    this.stochk = parseFloat(this.tulipIndicators.myStoch.result.stochK).toPrecision(this.precision);
    this.stochd = parseFloat(this.tulipIndicators.myStoch.result.stochD).toPrecision(this.precision);
    this.closingPrice = parseFloat(candle.close).toPrecision(this.precision);
    console.log(this.tulipIndicators);
}

// For debugging purposes.
strat.log = function () {
     log.debug("\tEMA - " + this.ema);
     log.debug("\tStock K - " + this.stochk);
     log.debug("\tStock D - " + this.stochd);
     log.debug("\tClosing Price - " + this.closingPrice)
}

function getCurrentCondition(stochk, stochd, stochSettings) {
    if (stochk > stochSettings.highThreshold && stochd > stochSettings.highThreshold)
        return 'overbought';
    else if (stochk < stochSettings.lowThreshold && stochd < stochSettings.lowThreshold)
        return 'oversold';
    else
        return 'middle';
}

function getCurrentTrendDirection(ema, price) {
    if(ema > price)
        return 'uptrend';
    else if (ema < price)
        return 'downtrend';
    else
        return 'none'
}

function isTrending(previousTrend, currentTrend) {
    return (previousTrend === currentTrend);
}

strat.check = function (candle) {

    var currentDirection = getCurrentTrendDirection(this.ema, this.closingPrice);
    var currentCondition = getCurrentCondition(this.stochk, this.stochd, this.settings.stoch);
    var trending = isTrending(this.trend.direction, currentDirection);

    if(trending)
        this.trend.duration++;
    else
        this.trend.duration = 0;

    this.trend.condition = currentCondition;
    this.trend.direction = currentDirection;

    if(this.previousaction === 'sell'){
        if(this.trend.direction === 'uptrend' && this.trend.condition === 'oversold' && this.trend.duration >= 2) {
            this.advice('long');
            this.previousaction = 'buy';
            console.log('=========================================buying===================================');
        }
    }
    else{
        if(this.trend.direction === 'downtrend' && this.trend.condition === 'overbought' && this.trend.duration >= 2) {
            this.advice('short');
            this.previousaction = 'sell';
            console.log('=========================================selling===================================');
        }
    }

    console.log(this.trend);
};


// Optional for executing code
// after completion of a backtest.
// This block will not execute in
// live use as a live gekko is
// never ending.
strat.end = function () {
    // your code!
    log.debug(this.settings);
}

module.exports = strat;
`

**Comment by ahmedelnahel** [comment]
Hi, it still give me undefined object for this.tulipIndicators.myStoch.result.stochK, what was the solution?
Thanks

**Comment by askmike** [comment]
Would you mind posting code and logs inside a code block or a gist? This is unreadable.

**Comment by askmike** [comment]
@acidrainz Apologies for never getting back to your problem, the issue tracker has been swamped for months. If this is still an issue please open a new ticket.

@cryptoboogy this is an old issue, if you have the same issue please open a new one (with readable logs / code).
