### ISSUE TITLE
Going from minute to second trades

### ISSUE THREAD

**Issue by reuzel** [askmike/gekko#1710]
Hi,

Love what you have been doing!

I'm trying to create a trading strategy that effectively finds the negative spikes in price. From detailed data I found that such spikes sometimes take no longer than 15 seconds. 

From the code and documentation I distilled that the Gekko engine works (hardcoded) on minute candles as a minimum. I was wondering what it would take to reduce that timerange to seconds, allowing strategies to handle on candles of several seconds, instead of minutes. On first sight is seems quite doable, adjusting budfox, and adding seconds to the vue pages (in rendering as well as selection panes). 

Before embarking on an effort to create a pull request: what am I missing? Is there some explicit reasoning behind choosing minute time ranges? E.g. are there exchanges that can't go below?

With kind regards,
Joost

**Comment by cmroche** [comment]
Most exchange APIs won't allow you to query them enough to do this, you would need to implement it via websocket, the framework in Gekko is not well adjusted to this type of high frequency data.

**Comment by reuzel** [comment]
Thanks, that would be quite an effort...
