### ISSUE TITLE
Dumb question (prolly not an Issue)

### ISSUE THREAD

**Issue by coltac** [askmike/gekko#1713]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[X ] question about the decisions made in the repository

* **Action taken** (what you did)
Tried to find logs while running develop branch

* **Expected result** (what you hoped would happen)
Id Find them

* **Actual result** (unexpected outcome)
I cant

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

When i run stable branch of gekkobot, there are market / tradebot logs in the /logs folder.  I like to $tail -f the log files and watch them to see how things are working.  When running the developer branch, the log folder remains empty, and i cant tail the logs.  Whats different?  Any help on finding the files?

**Comment by hilkoc** [comment]
It was a real issue, but now appears to be fixed: #1733 .
