### ISSUE TITLE
Gekko APIs + UI from apache proxy not working

### ISSUE THREAD

**Issue by blastbeng** [askmike/gekko#1715]
I'm referring to this:

https://github.com/askmike/gekko/issues/1049

I am using sgnac config but what i get is:

5/gekko/#/home:1 WebSocket connection to 'wss://myhost:3000/api/' failed: WebSocket is closed before the connection is established.

Gekko connects to the UI but it seem that from external host gekko still tries to go on port 3000 for the APIs...
to make this work it has to go on the same port (and parth+/api) i connect from external host, in my case: https://myhost:443/gekko/api

in my config, port 443 and 80 are open, but port 3000 is closed
here's the completed chrome console log connecting to my gekko using https://myhost:443/gekko

> WebSocket connection to 'wss://myhost:3000/api/' failed: WebSocket is closed before the connection is established.
build.js:16 OPTIONS https://myhost:3000/api/imports net::ERR_CONNECTION_TIMED_OUT
build.js:16 OPTIONS https://myhost:3000/api/gekkos net::ERR_CONNECTION_TIMED_OUT
build.js:16 OPTIONS https://myhost:3000/api/gekkos net::ERR_CONNECTION_TIMED_OUT
build.js:16 OPTIONS https://myhost:3000/api/apiKeys net::ERR_CONNECTION_TIMED_OUT
build.js:16 OPTIONS https://myhost:3000/api/exchanges net::ERR_CONNECTION_TIMED_OUT

How can i solve this? Is there a way to tell gekko to connect to the current port instead of the 3000?

**Comment by davidlimap** [comment]
Did you try to follow the manual? https://gekko.wizb.it/docs/installation/installing_gekko_on_a_server.html

**Comment by blastbeng** [comment]
Yes, i've also tried with nginx and got same result

**Comment by albertabello** [comment]
You can always run it locally and make an SSH tunnel, safer and simple

**Comment by blastbeng** [comment]
@albertabello 
actually i am running it over a VPN, but i'd like to simply access it with apache basic auth using SSL.. simpler and faster

i can't access it using a vpn everywhere, just on my personal machines

**Comment by askmike** [comment]
The hard thing is to upstream websockets through apache, it's probably possible but this bug tracker is not the place to discuss it unfotunately :(
