### ISSUE TITLE
[BUG] Trend reversal with open orders does not cancel them

### ISSUE THREAD

**Issue by talentoscope** [askmike/gekko#1716]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Live gekko trader on Kraken.
Short advice is passed from the strategy. Gekko places a sell order.
Sell order fails to execute and in that time, the next 1 minute candle has passed and a long advice is given.

* **Expected result** (what you hoped would happen)
Gekko should have cancelled the sell order, and either placed a buy order, or if as in this case, there was already a buy executed previously, i.e. funds are in coin and not fiat, then the sell order should again be cancelled and any buy advice ignored to ride the trend again.

* **Actual result** (unexpected outcome)
Gekko does not cancel the sell order, and instead tries to buy again with an open sell order.
Result: Insufficient fund errors and throwbacks from Kraken's API resulting in the gekko instance dying.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
Suggestion: Check open trades. If order is open and not fufilled, yet a trend reversal, or contrary advice has been given, cancel the reversed order (i.e. the sell in this case). If not, check balances and if possible, buy.

**Comment by ghost** [comment]
Exact problem happened to me with binance @cmroche -- If you can tell me how to change the 'LIMIT' order to a 'MARKET' order that'd be extremely appreciated.

**Comment by cmroche** [comment]
See notes in #1714 for Kraken in kraken.js the addOrder function, around line 276 change `ordertype: 'limit',` to `ordertype: 'market',`.

Keep in mind that this will increase your slippage, I'll possibly add a config option for this in the near future, as well as look at  config option to allow orders to stick around a bit longer before cancelling to change the price.

**Comment by talentoscope** [comment]
Thanks for the heads up. I'm not happy about using market orders, so will just go for longer candles. Surprised this issue didn't come up in search. Bad Github! :)

**Comment by cmroche** [comment]
@xteejx Actually I think there is a bug in order management that could still happen with longer candles, especially if using Kraken due to service issues.

I'm going to try to build a fix for this, though I don't have an easy way to test it. I'll post the PR here once it is ready.

**Comment by talentoscope** [comment]
Understandable, gekko trying to cancel orders that weren't created due to exchange issues. Makes sense with what I've been experiencing, even a very short outage could cause problems. Kraken need to sort it out! I can test the PR here if it helps?

**Comment by cmroche** [comment]
That's the plan, but it may take a day or two to sort this out.. it's a tricky problem.

**Comment by talentoscope** [comment]
No problem. If I don't respond here, just give me a shout on discord :)
