### ISSUE TITLE
A question, how does gekko traderbot handle purchases?

### ISSUE THREAD

**Issue by josoroma-zz** [askmike/gekko#1722]
Does the bot handle the initial purchase, or is it a trader action?

Thanks in advance!

**Comment by josoroma-zz** [comment]
Ok, gotcha!

![image](https://user-images.githubusercontent.com/69951/35130348-f98b8db8-fc85-11e7-8028-b91bd1304338.png)

**Comment by ansonphong** [comment]
The `Tradebot` does both buying and selling. You can reference the [documentation](https://gekko.wizb.it/docs/introduction/about_gekko.html) for more details.
