### ISSUE TITLE
Poloniex sell order based on highest buy

### ISSUE THREAD

**Issue by Kakkerlakkie** [askmike/gekko#1725]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
When the bot place a sell order the order is based on the highest sell, I would like to change this to highest buy, but I can't find this in the code. Can some explain where to create this feature? 

* **Expected result** (what you hoped would happen)
Selling based on highest buy

* **Actual result** (unexpected outcome)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by bitkominer** [comment]
Hi, till someone from dev team gives an official answer, you might try by yourself to modify portfolioManager.js (the file is inside folder: \plugin\trader\).

Go to section "var act = function()", then modify as following code:

`
if(what === 'BUY') {

      amount = this.getBalance(this.currency) / this.ticker.ask;
      if(amount > 0){
          price = this.ticker.ask;	  
          this.buy(amount, price);

      }
    } else if(what === 'SELL') {

      amount = this.getBalance(this.asset) - this.keepAsset;
      if(amount > 0){
          price = this.ticker.bid;
          this.sell(amount, price);

      }
    }
`

The bot will place an order as per your request, BUY at lowest ASK price, and SELL at highest BID price.

**Comment by Kakkerlakkie** [comment]
Thanks, very clear explanation and im gonna try this with the bot!
