### ISSUE TITLE
Unable to access /api/backtest

### ISSUE THREAD

**Issue by kazi308** [askmike/gekko#1729]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Enabled headless and api mode as per https://gekko.wizb.it/docs/installation/installing_gekko_on_a_server.html#configuring-gekko-to-run-in-the-cloud
Access the http://127.0.0.1:3000/api/backtest page

* **Expected result** (what you hoped would happen)
Access to the api

* **Actual result** (unexpected outcome)
Received "Method Not Allowed" error

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by grogcw** [comment]
Same here :/
