### ISSUE TITLE
Export csv of assets and currency when backtesting / simulating

### ISSUE THREAD

**Issue by nicocesar** [askmike/gekko#173]
This can be added as part of the wishlist

I'm currently using gekko to backtest (playing with parameters on the current algos)

I need to do a quick graph, in order to do so, I'll need a CSV with the following values:

timestamp;asset;currency

Thanks,
Nico

**Comment by askmike** [comment]
This is very easy to do by [creating a plugin](https://github.com/askmike/gekko/blob/stable/docs/internals/plugins.md). If you need pointers let me know, for nowI am closing.
