### ISSUE TITLE
No logs created when running form UI

### ISSUE THREAD

**Issue by hilkoc** [askmike/gekko#1733]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Start a live trade bot.

* **Expected result** (what you hoped would happen)
A log file to be created in the gekko/logs/ directory.

* **Actual result** (unexpected outcome)
The folder stays empty.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

This problem started when I updated to the latest of the develop branch (da956f9 2018-01-19 fix nodesource installation command for windows 10).

I then checked out tag 0.5.12. There the logging from the UI works. Unfortunately, I can't use the tag, because I need the fixes for some of the issues that were fixed later on develop branch.

Where should I start looking for this problem? I'd like to fix this but need some help.

**Comment by hilkoc** [comment]
@askmike  Looking at log entries between 0.5.12 and develop, I think it may have to do with (one of) these commits
3b5ba93
74ab11a
Could that be possible?

**Comment by wupeng1211** [comment]
https://github.com/fhd/init-script-template  

run gekko ui as service

**Comment by LobodaCrypto** [comment]
Same issue.
I could saw the logs before using gekko in running UI.
But, I have just update for binance( Gekko v0.5.12, Commits on Jan 21, 2018, develop branch),
I can't see log files in logs directory.
Please let me know kindly.
Thanks.

**Comment by coltac** [comment]
Same here, no log files.  I cant find what is different.

**Comment by LobodaCrypto** [comment]
In this commit  3b5ba93, I have just use original code.
Then, generate the log files.

**Comment by askmike** [comment]
Oops! This is now fixed in latest develop, see #1755.

**Comment by askmike** [comment]
Closing this already, I'll push a new release out within the next hour :)
