### ISSUE TITLE
I run gekko, and it starts on the command line but no window

### ISSUE THREAD

**Issue by mactac** [askmike/gekko#1734]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Installed, ran gekko with node gekko --ui

* **Expected result** (what you hoped would happen)

Expected a window to pop up with the UI

* **Actual result** (unexpected outcome)

No window came up.  Last line in the command window was 
Serving Gekko UI on http://localhost:3000/

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by BenVlodgi** [comment]
did you go to the webaddress?
this uses a web ui hosted on your local machine at port 3000 http://localhost:3000/

**Comment by bitkominer** [comment]
Just open your web browser (firefox, chrome, etc.), then type the address: http://localhost:3000/

**Comment by askmike** [comment]
What @BenVlodgi suggested should work, very strange though.

**Comment by mactac** [comment]
I did go to the address, it says not found. 

I realized that I'm using windows 10, and there seems to be different instructions for that.

So, I used a different computer, went through the windows 10 install process & it worked.... until my computer rebooted.   Now I get the same thing - when I go to the address, it says page not found.

**Comment by mactac** [comment]
Also, when I try to restart gekko, I get "cannot find module 'home/gekko/gekko'

But it did work the first time, until I rebooted.

**Comment by askmike** [comment]
> I did go to the address, it says not found.

What browser are you using? Please try this with either Firefox or Chrome.

> So, I used a different computer, went through the windows 10 install process & it worked.... until my computer rebooted. Now I get the same thing - when I go to the address, it says page not found.

Everytime your computer restarts you need to start Gekko manually again.

> Also, when I try to restart gekko, I get "cannot find module 'home/gekko/gekko'

Please post a screenshot or so from your commandline prompt.

----

Note that right now Gekko is very hard to install and manage, I am working on a "hosted" version in the cloud that does not require any setup or installation (for a monthly fee), would this be of interest to you?

**Comment by nccablhoe** [comment]
@askmike I would definitely be interested in the cloud version for a reasonable monthly fee. What is your projected timeline?
