### ISSUE TITLE
Mac Bash : Failed installation

### ISSUE THREAD

**Issue by Pimouskipick** [askmike/gekko#1738]
* **I'm submitting a ...**
[V] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did) 

Hey everyone ! I am new to the community and i am having some trouble installing gekko, im running on OS X Yosemite, and every time i try to install gekko following the https://gekko.wizb.it/docs/installation/installing_gekko.html instructions, i fail to install Gekko's dependencies. The command 

npm install --only=production 
gives me :
-bash: npm: command not found

* **Expected result** (what you hoped would happen)

* **Actual result** (unexpected outcome)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

What i have tried to fix the issue :
-Deleting all gekko files and reinstalling with the command 
git clone git://github.com/askmike/gekko.git -b stable

- downloading gekko from github 
- reinstalling node 
- reinstalling an other version of node
- running node -v : v8.9.4 
- reinstall node using homebrew which i didn't have, so i tried to install it, and i don't know if it is related to my problem installing gekko, but it finally failed : 

Benoits-MacBook-Pro:Homebrew Ben$ bin/brew update --force
==> Downloading https://homebrew.bintray.com/bottles-portable-ruby/portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz
######################################################################## 100.0%
Error: Checksum mismatch.
Expected: 34ce9e4c9c1be28db564d744165aa29291426f8a3d2ef806ba4f0b9175aedb2b
Actual: 
Archive: /Users/Ben/Library/Caches/Homebrew/portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz
To retry an incomplete download, remove the file above.
Error: Failed to install vendor Ruby.

-asking google for possible solution, which didn't lead to anything (i thought for a while that it was a problem with my .bash_profile $PATH being wrongly set, but it didn't fix anything even if, being really new to this world, i am not even sure that i have fixed something)

I am really desperate, not having enough knowledge on the subject, i failed to see where the problem could be, so please, help me ! 
Ps : sorry if i posted my request in the wrong form or the wrong place...          
Thank's

**Comment by askmike** [comment]
Your problem is not having nodejs installed properly. May I suggest installing nodejs via nvm (see [here](https://github.com/creationix/nvm)), run this:

    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash

After that run:

    nvm install 8.9.4
