### ISSUE TITLE
Does not function after reboot

### ISSUE THREAD

**Issue by mactac** [askmike/gekko#1740]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did

I installed gekko on windows 10, It worked fine as far as I could tell.

* **Expected result** (what you hoped would happen)

Rebooted my computer tried to start gekko again.

* **Actual result** (unexpected outcome)

node gekko --ui  results in:
"cannot find module 'home/gekko/gekko'

Yet it worked before I rebooted my computer.

localhost:3000 in my browser brings up a "page not found"

Additionally, on another computer I tried doing the generic (non windows 10) windows install.  I get the same problem when trying to navigate to localhost:3000.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

See this thread - it was closed, but not resolved:
https://github.com/askmike/gekko/issues/1734#issuecomment-359160533

**Comment by askmike** [comment]
See my comment here: https://github.com/askmike/gekko/issues/1734#issuecomment-359248369
