### ISSUE TITLE
Binance.js unable to do market orders

### ISSUE THREAD

**Issue by ghost** [askmike/gekko#1743]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)

Changed Binance.js to use 'MARKET' buys instead of limit (I deleted the price and one other setting I forget but I checked the API -- sorry I'm mobile right now)

  let reqData = {
    symbol: this.pair,
    side: tradeType.toUpperCase(),
    type: 'MARKET',
    timeInForce: 'GTC', // Good to cancel (I think, not really covered in docs, but is default)
    quantity: amount,
    //price: price,
    //timestamp: new Date().getTime()
  };
* **Expected result** (what you hoped would happen)
it works

* **Actual result** (unexpected outcome)
400 error and crash

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
I would love to be able to market orders with binance! <3 halp

RECEIVED ERROR IN GEKKO 5281829835993364

**Comment by askmike** [comment]
@mvanbosc The current execution strategy of Gekko is not supposed to do market orders, see here: https://gekko.wizb.it/docs/introduction/scope.html#Execution-strategy

As for the problem you experienced, can you check if it is fixed in #1737?

**Comment by Jabbaxx** [comment]
@mvanbosc did you ever find out how to make Market order instead of limit orders?

**Comment by ghost** [comment]
No sir but I did make a fast trading strategy that does something similar

**Comment by Jabbaxx** [comment]
OK. What that means ?

**Comment by ghost** [comment]
Have gekko replace orders every ms at the next order book position until
the order is filled. It also makes sure the price doesn’t have extreme
variance from when we said to buy.

**Comment by Jabbaxx** [comment]
Sounds good ;) Is it somewhere to find public ?
Or do you want to share ?

**Comment by ghost** [comment]
No sorry not public

**Comment by Jabbaxx** [comment]
Sad. Wanna share private ? ;)

**Comment by ghost** [comment]
$5k

**Comment by Jabbaxx** [comment]
It is always nice to have a dream ;)
