### ISSUE TITLE
Live Gekko in ui can't load local data?

### ISSUE THREAD

**Issue by wupeng1211** [askmike/gekko#1744]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)

* **Expected result** (what you hoped would happen)

* **Actual result** (unexpected outcome)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
Hey! Can you be a bit more specific?

**Comment by didasy** [comment]
I think he want Gekko tradebot to be able to read local data instead of relying on watcher for data feed. Probably bothered by the "Not enough data" warning in the page.

**Comment by ockimock** [comment]
I think JesusIslam is right. I tried to get the data-stitching to work in the UI for about 2 days before finding #1180 and #943 
Now I've got it up and running in the CLI (which had no problem stitching in the past year of data).

**Comment by H256** [comment]
Stitching in the UI would be sooo cool! 👍

**Comment by askmike** [comment]
Will be supported in the next version of the UI :)

**Comment by wupeng1211** [comment]
Wand

**Comment by OverlordQ** [comment]
Did this actually get fixed? Since it seems to still not stitch in the UI.
