### ISSUE TITLE
Creating Files Strategies Error: EACCES: permission denied open with Windows Bash

### ISSUE THREAD

**Issue by cyow** [askmike/gekko#1745]
Note: for support questions, please join our Discord server

I'm submitting a ...
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

Action taken (what you did)

I am using Windows 10 accessing gekko via Bash.exe, edited the files to configure as indicated in the issue but when I try to run it presents the errors in the files I edited, will I have to update something? how to proceed grateful.

Error: EACCES: permission denied, open ./config/strategies/custom.toml '
Error: EACCES: permission denied, open ./strategies/custom.js'
Error: EACCES: permission denied, open ./strategies/test1.js'
Error: EACCES: permission denied, open ./strategies/test2.js'

**Comment by askmike** [comment]
Can @thegamecat way in maybe? I have little experience with Windows Bash.

**Comment by cyow** [comment]
ok teacher !

**Comment by cmroche** [comment]
Can you try `chmod -R 777 *` from the gekko directory in bash? Does that fix the issue? If not, what was the result of the command, more permission issue?

**Comment by zgwenwen** [comment]
`chmod -R 777 *` works!!!
Thank you!!
