### ISSUE TITLE
Centralized repo for data

### ISSUE THREAD

**Issue by tommiehansen** [askmike/gekko#1746]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository

* **Other information**
Implement the ability to download data sets from a centralized repo such as Github.

* **Why?**
1. Because the idea that each and every person that uses Gekko should download it's own data sets isn't that great. It's a good thing one can but the standard should be to just pull the data from Github.

2. Because importing data from exchanges is tedious and slow at best

3. Sharing of data is simply much more efficient

* **How?**
Write a simple script that appends data each X time (e.g. every 4 hours) and push the files to the Github repo or create a new repo for this specific purpose (that latter in order to not bloat the original repo).

**Comment by cmroche** [comment]
Note that this would likely be against the ToS of most exchanges. They do not allow you to redistribute their market data.

**Comment by tommiehansen** [comment]
I've read a couple of ToS and 'legal' on the relevant sites. Many of them have general copyright rules that are very much a sort of copy-and-paste. In essence one would need a written consent to republish data from the API's so it would seem the solution is just to write E-mails about converting and updating the data to SQLite etc (derivative work).
