### ISSUE TITLE
I made a Heiken-Ashi Indicator

### ISSUE THREAD

**Issue by krieghof** [askmike/gekko#1748]
I made an Indicator that calculates Heiken-Ashi candles, the open, close, high and low.

It could be possible that there is an error in the code, i coded it quickly and dirty.
But I may improve it over time.

In your strat.js
```
var log = require('../core/log.js');

strat.init = function(){

  // Add Heiken-Ashi Indicator
  this.addIndicator('heiken', 'HEIKEN');
}

strat.check = function(){
  var heiken = this.indicators.heiken;

    log.debug('open:', heiken.open);
    log.debug('close:', heiken.close);
    log.debug('high:', heiken.high);
    log.debug('low:', heiken.low);
}
```

Have fun!!
#1747

Hope this is not against the guidelines, if it is so, I will remove this.
But if you want to give me a tip, I would appreciate it.
BTC - 1MgHDnQJ5k2jecnr8gFfbxni5Ajaz8q5fT
BCH - 162vPvhwEKmuBEWTbnCnfSxxWJy21TNxfq
ETH - 0x073D8E7E8531C09Ae85669E57B7716edBD2dc50A

**Comment by askmike** [comment]
Awesome stuff! Let's keep the discussion in #1747 :)
