### ISSUE TITLE
Just stops working

### ISSUE THREAD

**Issue by mactac** [askmike/gekko#1753]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)

Run A tradebot

* **Expected result** (what you hoped would happen)

Expected it to keep running

* **Actual result** (unexpected outcome)
Just silently stops.   "data spanning" continues to increase, but there are no more calls to the poloniex API.

The "market graph" sits there constantly loading & does not show.

"Post" messages in the bash window stop, but no error.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Using windows 10
Chrome
Ubuntu app

**Comment by mactac** [comment]
Here's another thing that I noticed.  When it stops, if I go back to bash, and hit CTRL-C, it's put through a whole bunch (10?) of POSTS... then stop again.  If I hit CTL-C again, it'll do the same.  Then, if I hit it a 3rd time, it'll stop the program.

The program seem unusable if it just keeps dying randomly.

**Comment by askmike** [comment]
Please post screenshots or logs, we can't see your screen from here.

**Comment by mactac** [comment]
There really isn't anything to see.  It just stops doing anything.    Web page looks like it's running, but there is nothing going on in the bash window after a certain period.  If I restart it, it works.. for a while, then stops.

It doesn't seem to be creating a log for some reason.  Do I have to turn on logging?
