### ISSUE TITLE
Does not trade complete Balance

### ISSUE THREAD

**Issue by mactac** [askmike/gekko#1754]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)

Using one of the default strategies, running a tradebot

* **Expected result** (what you hoped would happen)

Expect it to trade out my entire balance with each trade

* **Actual result** (unexpected outcome)

If I have $200 UDS, it will trade out but leave just over $1 in USD and trade the rest instead of trading the entire amount.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Windows 10
Chrome
Ubuntu window app

**Comment by cmroche** [comment]
This isn't really abnormal behaviour due to lot sizing rules in place by most exchanges will generally mean you can not trade everything.

I can confirm that Binance, Bitfinex, Bittrex and Kraken all do this, even if you are trading through a web interface. Are you certain this is not the issue?

**Comment by mactac** [comment]
perhaps I do not understand - When I trade manually, I can trade 100% of a currency.  Does the API have different restrictions with respect to trading?

The issue is that it confuses gekko - I get a whole ton of trades in a row because it trades 98% of my USD, then keeps trading it out because there is still USD left.   It's like it never finishes.  So, instead of 2 trades to do a round trip, it does 16.

**Comment by cmroche** [comment]
@mactac Can you give some information on which exchange and asset pairs, as well as debug output from gekko when it executes a trade incorrectly?

**Comment by hilkoc** [comment]
It could have to do with the precision; Gekko rounds the amounds (down) before posting the order.

**Comment by mactac** [comment]
What would be the point of rounding down?   

Here's what it looks like (log from the exchange, poloniex):


ETH/USDT | Buy | Exchange | 1075.11432238 | 0.00017968 | 0.00000027 ETH (0.15%) | 0.19317654 USDT | 2018-01-22 11:20:02
-- | -- | -- | -- | -- | -- | -- | --
  | ETH/USDT | Buy | Exchange | 1075.11432238 | 0.00100000 | 0.00000150 ETH (0.15%) | 1.07511432 USDT | 2018-01-22 11:20:01
  | ETH/USDT | Buy | Exchange | 1075.11432238 | 0.13409472 | 0.00020114 ETH (0.15%) | 144.16715402 USDT | 2018-01-22 11:20:00
  | ETH/USDT | Sell | Exchange | 1072.47169463 | 0.13589431 | 0.21861420 USDT (0.15%) | 145.52418673 USDT | 2018-01-22 10:58:08
  | ETH/USDT | Sell | Exchange | 1072.47169463 | 0.00004064 | 0.00006538 USDT (0.15%) | 0.04351986 USDT | 2018-01-22 10:58:08
  | ETH/USDT | Buy | Exchange | 1068.70000000 | 0.13613915 | 0.00020421 ETH (0.15%) | 145.49190960 USDT | 2018-01-22 10:18:48
  | ETH/USDT | Sell | Exchange | 1076.36763798 | 0.00083375 | 0.00134613 USDT (0.15%) | 0.89607538 USDT | 2018-01-22 09:40:27
  | ETH/USDT | Sell | Exchange | 1076.36763798 | 0.02900000 | 0.04682199 USDT (0.15%) | 31.16783951 USDT | 2018-01-22 09:40:26
  | ETH/USDT | Sell | Exchange | 1076.36763798 | 0.10529010 | 0.16999628 USDT (0.15%) | 113.16085995 USDT | 2018-01-22 09:40:09
  | ETH/USDT | Buy | Exchange | 1074.00000001 | 0.13389872 | 0.00020085 ETH (0.15%) | 143.80722528 USDT | 2018-01-22 08:55:43
  | ETH/USDT | Buy | Exchange | 1074.00000000 | 0.00142811 | 0.00000214 ETH (0.15%) | 1.53379014 USDT | 2018-01-22 08:54:15

**Comment by mactac** [comment]
@cmroche   I don't have debug output, but I just posted an example above

**Comment by cmroche** [comment]
@askmike Anyone here known to have experience with Poloniex?

**Comment by Volkan80** [comment]
I have the same problem using the Poloniex API.
