### ISSUE TITLE
Newest Merge/Update removed binance on Develop

### ISSUE THREAD

**Issue by ghost** [askmike/gekko#1757]
Binance has been removed (from UI at least) in the latest file moving @askmike @cmroche

**Comment by cmroche** [comment]
Probably due to a script error, there was a big merge a few hours ago. It's late now, but I'll look into this tomorrow.

**Comment by cmroche** [comment]
@mvanbosc Bug also present for Kraken and Bitfinex, would you update the issue title please. Fix is incoming soon.

**Comment by keat84** [comment]
Mean we cannot use Gekko for Binance anymore?!

**Comment by cmroche** [comment]
@keat84 Pull request with the fix is pending, please take a look at the change in #1758. It is very simple and you can fix the issue locally by making the same modification in your system until the PR is merged. :)

**Comment by unstephenk** [comment]
added the changes applied in #1758 but now:
`TypeError: this.binance.startTimeSync is not a function`

Is anyone else experiencing this issue or am I alone?

**Comment by askmike** [comment]
@unstephenk see my comment here: https://github.com/askmike/gekko/pull/1758#issuecomment-359555945

**Comment by unstephenk** [comment]
Success! Thanks @askmike!
