### ISSUE TITLE
Duplicate Runner appears after a couple of hours

### ISSUE THREAD

**Issue by mactac** [askmike/gekko#1760]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)

Ran traderbot

* **Expected result** (what you hoped would happen)

Expected to run normally

* **Actual result** (unexpected outcome)

After a couple of hours, a duplicate runner appears, exactly the same as the first.  Now I have 2 running.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Windows 10, Ubuntu

**Comment by JoeTeglasi** [comment]
had same problem but with papertrader: tried to make just one live papertrader, but THREE strat runners and three market watchers were generated!

**Comment by WebfinityDesign** [comment]
Same here on Ubuntu

**Comment by donkykong017** [comment]
have a similar thing. when i start a marketwatcher, 2 appear right after.
although after refreshing the UI webpage only one remains. running on AWS EC2
