### ISSUE TITLE
A Way To intracandle trading

### ISSUE THREAD

**Issue by gekkouser** [askmike/gekko#1763]
[ x] feature request

Spending a lot of time on writing strategies I noticed that i would like to make use of a special function. Is it possible to set Sell and buy orders for the next candle? Just a function which would place sell and buy orders for a specified price  after every complete candle for the current (not completed one).
Didn't find any topics concerning that, if there is one just let me know.

**Comment by hilkoc** [comment]
If I am not mistaken, all orders are placed as limit orders. So if at the end of a candle you calculate your price and place the order, it can in theory be executed in the middle of the next candle (or never, or any other time in the future).

The only problem is that the strategies you can make can only give a long/short advice. You cannot specify the amount or price form within your strategy. I hope that'll be possible in the future.

**Comment by gekkouser** [comment]
look what i found in /plugins/trader/portfolioManager.js : 
` var act = function() {
    var amount, price;

    if(what === 'BUY') {

      amount = this.getBalance(this.currency) / this.ticker.ask;
      if(amount > 0){
          price = this.ticker.bid;
          this.buy(amount, price);
      }
    } else if(what === 'SELL') {

      amount = this.getBalance(this.asset) - this.keepAsset;
      if(amount > 0){
          price = this.ticker.ask;
          this.sell(amount, price);
      }
    }
  };`

Might work if you modify it and manage it to get a price from the strat. Will look into that with my js mate the next days or weeks :)

**Comment by talentoscope** [comment]
You can modify that to something like this to get orders through quicker, though it means moving away from the orderbook: 
```javascript
if(what === 'BUY') {

  amount = this.getBalance(this.currency) / this.ticker.ask;
  if(amount > 0){
      price = this.ticker.bid * 1.002;
      this.buy(amount, price);
  }
} else if(what === 'SELL') {

  amount = this.getBalance(this.asset) - this.keepAsset;
  if(amount > 0){
      price = this.ticker.ask * 0.998;
      this.sell(amount, price);
  }
}
```
