### ISSUE TITLE
Live Trade Roundtrips is missing

### ISSUE THREAD

**Issue by Profex86** [askmike/gekko#1770]
Hallo,

when i start paper trader, so i can see the roundtrips, but no when i start tradebot with real money?

can i set the timezone?

thanks

**Comment by billymcintosh** [comment]
Has there been more than 2 trades with real money?

**Comment by Profex86** [comment]
No, only 1 Bot is Running. It is only 1 bot possible at the same time on the same market.

**Comment by rcoenen** [comment]
@Profex86 if the bot has not done a 2 trades (1x buy, 1x sale) well then a roundtrip has not happened yet. So there's simply nothing to show. I suppose that's why it's empty. You got to wait till the bot has done 2 trades!

**Comment by Profex86** [comment]
![7bc0f8eb-2069-4cb7-92f2-636ca463422f](https://user-images.githubusercontent.com/35728406/35364792-66bcfc06-0171-11e8-83ab-f59edf2026f6.png)

**Comment by rcoenen** [comment]
@Profex86 looks to me like your bot simply has not executed any trades yet?

**Comment by Profex86** [comment]
Bitstamp Orderbook says he did it. strange thing.

**Comment by kifirkin** [comment]
I have exactly the same problem! Bot trades, gets profit but roundris are empty :worried: 
wex.nz

also there is no errors

**Comment by kifirkin** [comment]
I've  updated from `master`, did `npm i` and problem gone

**Comment by Profex86** [comment]
Did you type npm i in console or what you mean?

**Comment by kifirkin** [comment]
@Profex86 Yes, I installed dependencies with `npm i --only=production`

**Comment by Profex86** [comment]
Ok, I'll try that. Thanks

**Comment by billymcintosh** [comment]
@Profex86 
```
git checkout master
git pull master
npm install
```
...then run gekko as normal.

Any merge requests are very welcome.

**Comment by Profex86** [comment]
@billymcintosh

Sry, I don't understand what u mean with "git checkout master"

i have make here a very simple installer with all u need.

check this out!


[Gekko Installer.zip](https://github.com/askmike/gekko/files/1670199/Gekko.Installer.zip)



(only testet with Win 7 x64)

**Comment by SebFourault** [comment]
I have the same issue with the last stable version (Gekko v0.5.12 and Gekko UI v0.2.0) : after 2 trades on a live tradebot, the html block "Roundtrips" doen't even show. And no errors in logs/console...

I tried to re-install modules and also to pull from develop branch but still same issue.

Will it be fixed in the next version ? Thanks a lot guyz 👍

**Comment by rcoenen** [comment]
This problem still exists on current development branch
