### ISSUE TITLE
Add pair in Bitfinex (USD/USDT)

### ISSUE THREAD

**Issue by PhunkyBob** [askmike/gekko#1774]
* **I'm submitting a ...**
[ ] bug report
[X] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
I wanted to add the pair USD/USDT on Bitfinex.
https://coinmarketcap.com/exchanges/bitfinex/
I modified the "bitfinex.js" file with:
`assets: ['BTC', 'LTC', 'ETH', 'SAN', 'IOT', 'BCH', 'OMG', 'XMR', 'DSH', 'ZEC', 'EOS', 'ETC', 'XRP', 'NEO', 'ETP', 'USDT'],`
and
`{ pair: ['USD', 'USDT'], minimalOrder: { amount: 0.0001, unit: 'asset' } },`
I restarted Gekko UI.
In the importer, I chose "Bitfinex" / "USD" / "USDT" / selected 5 days.
The importer says it's OK (whereas no progress bar is displayed).

* **Expected result** (what you hoped would happen)
I would expect to see this pair available in my data.

* **Actual result** (unexpected outcome)
I don't see this pair in my data.

I wonder what I missed.
Maybe the code is not "USDT" (like Kraken where it's "USDTZUSD") ?

**Comment by askmike** [comment]
There is no USDT/USD market on bitfinex as far as I know. Could you point to a link or so?

**Comment by askmike** [comment]
I think I am right, If I turn out to be wrong please reopen this!

**Comment by PhunkyBob** [comment]
In CoinMarketCap
https://coinmarketcap.com/currencies/tether/#markets
it says that there is $67M in the USDT/USD pair on BitFinex for the last 24h.
