### ISSUE TITLE
Send trade events to Telegram 

### ISSUE THREAD

**Issue by rcoenen** [askmike/gekko#1775]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[x ] feature request
[ ] question about the decisions made in the repository

One great feature that Zenbot has but is not available in Gekko: updates on Telegram.
It would be great to get a notification on buy/sale actions and an overview of the performance made and/or roundtrip performance.

Alternatively Slack could work - but Telegram is better

**Comment by ghost** [comment]
It would be nice to be able to config this from the UI for those of us who aren't running console based as well! Or at least have some sort of config file that supports this.

**Comment by rcoenen** [comment]
OK update: so it's possible apparently from the CLI. Not from the WebUI? Confusing this dual cli/web ui approach. I am not sure what applies when and where
