### ISSUE TITLE
Live traderbot doesn’t plot buy or sell on the graph. Which part of the code i should be looking at?

### ISSUE THREAD

**Issue by slimelec** [askmike/gekko#1780]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
I lunched a live gekko UI (v0.5.11), everything works find buy and sell orders is working. 

* **Expected result** (what you hoped would happen)
Show buy and sell orders(green and red dots) on the graph.

* **Actual result** (unexpected outcome)
Dots are not showing, and the balance and Current Balance is not updated. 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by SebFourault** [comment]
I have the same problem (running on raspberry pi 3, gekko stable branch)
For my case, some random SELL points are on the plot but no buy points. And also the hour is not the good one (1 hour late). Would you know how to fix the problem ? I have no error message so far.

![image](https://user-images.githubusercontent.com/1742621/35540066-6218fef2-0554-11e8-9f77-71d9bef680e7.png)

Thanks a lot :smiley: !

**Comment by dmuzizian** [comment]
i have the same problem to
