### ISSUE TITLE
Strategy: simple trailing stopp loss

### ISSUE THREAD

**Issue by der-seemann** [askmike/gekko#1783]
I'm missing a very simple but basic strategy: a trailing stopp loss

What the strategy should to:

monitor the selected market, and as soon as the price drops below (the highest price since starting the bot - defined %) all or a defined percentage of my coins will be sold.

For example:

Sell 100% at -10%

in my account I have 100 NEO
Current price is: 0.010000 btc
current stopp loss is: (0.010000 - 10%) 0.009

if price drops below  0.009 > sell ; end

if price goes up to 200 > new stopp loss is: (200 - 10%) 180

if then price goes back to 150 > all coins will be sold at 180; end     :-)

so if I set this up for all my trades (that i started manually) I have a max loss of 10% but endless up side, as long as the coin keeps mooning and never dips more than 10 %

**Comment by bvanhou** [comment]
I would review the issues within this repo before you post. Someone has already put in a merge request a few months back with this functionality, however it has not been merged

https://github.com/askmike/gekko/pull/1317

**Comment by talentoscope** [comment]
This is the kind of thing we discuss on Discord.
Feel free to join us there to discuss strategies, etc.
https://discord.gg/26wMygt

**Comment by lambodance** [comment]
sounds like a nice idea. when does gekko should make a new "buy in"?

**Comment by askmike** [comment]
Trailing Stop losses are now native to Gekko! Check the docs here: https://gekko.wizb.it/docs/strategies/creating_a_strategy.html#check-function
