### ISSUE TITLE
Back Test Entry and Exit Points not accurately matching with Exchange

### ISSUE THREAD

**Issue by bvanhou** [askmike/gekko#1785]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[X ] question about the decisions made in the repository

* **Action taken** (what you did)
I have been using basic sample strategies and backtesting to test some logic with BTC and XRP.

* **Expected result** (what you hoped would happen)
The entry points would be where the RSI is low or the MACD crosses. 
The exit points would be where the RSI is high or the MACD crosses. 

* **Actual result** (unexpected outcome)
The entry and exit points are extremely far off by an hour or two, sometimes more. I am curious if I am doing something wrong. I have been cross referencing the entry and exit points with the exchange historical data and it doesnt seem to line up. Is there something Im not accounting for?

**Comment by greenbigfrog** [comment]
What is your configuration? And also gekko can't predict the future, but act on indicators

**Comment by bvanhou** [comment]
The configuration is out of the box and utilizing an MFI strategy I put together. The logic is simple however, the entry and exit points are delayed. 

This is like this on every strategy, even the out of the box ones.

```
  if(this.mfi <= this.settings.oversold){
    log.debug('OverSold | In buy trend');    
    this.advice('long');
    console.log('buyy');
    console.log(candle.start.toDate());
  } else if(this.mfi >= this.settings.overbought){
    console.log('sellllll ');
    console.log(candle.start.toDate());

    log.debug('OverBought | In sell trend');
    this.advice('short');
  }else{
    log.debug('In no trend');    
    this.advice();   
  }
```

### Entry Point from Trade View:
<img width="1072" alt="screen shot 2018-01-26 at 8 14 02 pm" src="https://user-images.githubusercontent.com/8975445/35466851-df3a4c00-02d5-11e8-9d1e-22b9321d77d1.png">

### BackTest Results
<img width="965" alt="screen shot 2018-01-26 at 8 20 09 pm" src="https://user-images.githubusercontent.com/8975445/35466902-5df1e76a-02d6-11e8-97d2-b1192ea4f4a6.png">


### What should be the Exit Point from Trade View:
<img width="1082" alt="screen shot 2018-01-26 at 8 22 24 pm" src="https://user-images.githubusercontent.com/8975445/35466922-aac2d3e2-02d6-11e8-9306-591275aaf9ce.png">

**Comment by bvanhou** [comment]
It seems the candle data from the importer in binance is some how different than looking at tradeview.

I have checked the timezone and currency and everything. The entrypoints do not make sense to me. 

Can anyone help clarify the entrypoints?

**Comment by PanoPilot** [comment]
Hi there, I've similiar issues with GDAX.
Have you checked that the candle.close price from the trade is actually matching with the prices directly at the exchange at that point of time and have you checked that candle.start is matching to the actual time. I've noticed that the candle.close market time is 1.5h earlier than the real time, at least in my case.

thx & best,
chris

**Comment by thisisloze** [comment]
I have the same problem with EVERY exchange. Gekko's inaccuracy is off by so much its impossible to work with :/

**Comment by askmike** [comment]
> I have the same problem with EVERY exchange. Gekko's inaccuracy is off by so much its impossible to work with :/

Thanks for your constructive feedback with detailed information. A lot of people are using Gekko successfully without any issue. 

----

Keep in mind that Gekko creates candles based on start time, it doesn't round to clock times (if you have hourly candles and Gekko starts at :35 the candles might start at :35 every hour).

@bvanhou @PanoPilot are you guys experiencing this with the paper trader (including backtests) or live trader?

**Comment by thisisloze** [comment]
You built the thing didn't you? Well heres a bit more information. Take ANY timeframe on trading view. Then put a simple sma fast and sma slow on it. Look at the cross overs. ( do a small time frame of a day ) count how many times sma goes above the slow sma. Then do it on gekko. And notice the inaccuracy. Try it for 5 exchanges. Notice them all being inaccurate. If you want more information I can provide it. But I'm sure you already know all this its your baby. I have tried 8 exchanges with 8 days of information. All of them inaccurate. Price. Volume. Time. Everything. Which causes the sma crossovers to be wrong. So what more information do you need?

**Comment by thisisloze** [comment]
Lots of people using it without issues? Can you point me in the direction of one ?
