### ISSUE TITLE
[BUG] Talib indicator return empty result

### ISSUE THREAD

**Issue by carlosatta** [askmike/gekko#1787]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Use a strategy with an Talib Indicator (ex.: BBands).
ex.: this.addTalibIndicator('mybbands', 'bbands', this.settings.bbands);

* **Expected result** (what you hoped would happen)
Every candle I expect calculated result inside "this.talibIndicators.mybbands.result".

* **Actual result** (unexpected outcome)
Some time this.talibIndicators.mybbands.result result empty and i have to restart strategy until it's works. In baktest this problem is not present, only in real trading.

* **Other information**

**Comment by askmike** [comment]
Could you post a sample strategy I could test?

**Comment by carlosatta** [comment]
Of course. This is the strategy I use for debug purpose.

`
var log = require('../core/log');

var strat = {};

strat.init = function() {
  this.name = 'BBand MACD';
  this.last_position = null;

  this.requiredHistory = this.tradingAdvisor.historySize;
  this.addIndicator('macd', 'MACD', this.settings.macd);
  this.addTalibIndicator('mybbands', 'bbands', this.settings.bbands);

}

strat.update = function(candle) {  
  this.candle.trend = this.candle.open < this.candle.close ? 'bullish' : 'bearish';
}

// For debugging purposes.
strat.log = function() {  
}

strat.check = function() {
  var mybbands = this.talibIndicators.mybbands.result;  

  log.info('-------------------------');
  log.info(JSON.stringify(this.candle));
  log.info(JSON.stringify(this.talibIndicators.mybbands));
  log.info(JSON.stringify(this.indicators.macd.signal));
  log.info('-------------------------');

  this.advice();

}

module.exports = strat;
`

The variable "this.talibIndicators.mybbands" some times is empty and I have to restart  the script until it's work.

P.s.: I use forever, ex.: forever start --uid bittrex-bbmacd-BTC_XVG  gekko.js -c bittrex-bbmacd-BTC_XVG.js

**Comment by wupeng1211** [comment]
var outRealUpperBand = this.talibIndicators.mybbands.result['outRealUpperBand']

**Comment by wupeng1211** [comment]
https://github.com/oransel/node-talib/blob/master/src/lib/src/ta_func/ta_BBANDS.c

**Comment by talentoscope** [comment]
BBands outputs 3 variables, therefore it wouldn't just be bbands.result. There's where the error is coming from :)

**Comment by carlosatta** [comment]
In this line I print all the object 'log.info(JSON.stringify(this.talibIndicators.mybbands));'
In output I have this result:
data:    gekko.js:3145 - 2018-01-26 16:04:18 (INFO):	{"result":{}}

But, if i restart the script few times i got something like this:
data:    gekko.js:3145 - 2018-01-26 16:04:18 (INFO):	{"result":{"outRealUpperBand":0.0011877744861648158,"outRealMiddleBand":0.0011691264761904796,"outRealLowerBand":0.0011504784662161433}}

Maybe I don't have understand your comment, but why result is empty sometimes?

**Comment by carlosatta** [comment]
I've found this https://github.com/okibcn/gekko/blob/patch-2/strategies/indicators/BB.js, so I've decided to give a try. Seems to work, so I decide to leave talib indicator.
