### ISSUE TITLE
[BUG] Binance error 400 while trying to trade ETH-ENJ

### ISSUE THREAD

**Issue by blastbeng** [askmike/gekko#1788]
Hello,
i am trying to trade on binance with eth enj coins but i am getting this error:

[binance-error.log](https://github.com/askmike/gekko/files/1664893/binance-error.log)

the same config on GDAX using EUR\LTC is working fine

do you need my config.js ?

Thanks

**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)

Trying to trade eth\enj on binance

* **Expected result** (what you hoped would happen)

background gekko trader working

* **Actual result** (unexpected outcome)

response code 400

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by talentoscope** [comment]
Would you update your issue with the version of gekko you're using please? Develop or stable branch?
Possibly related to #1786

**Comment by blastbeng** [comment]
I am actually on develop branch

**Comment by askmike** [comment]
@xteejx that's a seperate issue for Kraken.

@blast1987 I am having this as well, posted an upstream issue here: https://github.com/aarongarvey/binance/issues/34

**Comment by askmike** [comment]
@blast1987 after double checking: make sure your API is correct and working. If that does not fix your problem please let me know.

**Comment by blastbeng** [comment]
I solved that, i regenereted my config , also checked api and now it is working

the only thing that changed is that now i'm on stable branch
