### ISSUE TITLE
Integrate Chalk for Colored Logging

### ISSUE THREAD

**Issue by ansonphong** [askmike/gekko#1789]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[ x ] feature request
[ ] question about the decisions made in the repository

I integrated [Chalk](https://www.npmjs.com/package/chalk) on a fork of Gekko and it works really nicely.

**Chalk on Custom Gekko Strategy in Backtest**
![image](https://user-images.githubusercontent.com/4825055/35461135-6073a554-029b-11e8-9448-9a2df86cf308.png)

@askmike  I can make a PR to integrate into Gekko core, though before going ahead with the work on that I wanted to see your opinion, if it would be merged, if you have any thoughts on any other libraries to use for coloring, etc, or if that was desirable.

**Comment by ansonphong** [comment]
I noticed that `Colors` is already integrated, closing for now. https://github.com/askmike/gekko/issues/56

**Comment by GO1984** [comment]
I do like your clean cli output very much. Is there any chance, that you share the code with me?
