### ISSUE TITLE
GEKKO ERROR: Gekko encountered an error and can't continue - Binance trading

### ISSUE THREAD

**Issue by gkkorr** [askmike/gekko#1792]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Running tradebot under UI 

* **Expected result** (what you hoped would happen)
Would initiate buy/sell orders on live market

* **Actual result** (unexpected outcome)
Initiated a sell order, but gives "GEKKO ERROR: Gekko encountered an error and can't continue" under UI popup. I was able to successfully buy back into it as I caught the problem shortly after it happened, and retried running a live gekko after reopening the problem. It then happened again, but didn't take a buy/sell to execute to get the error again. Instead it just, seemingly, happened randomly. 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

"RECEIVED ERROR IN GEKKO 680966230964747 
Gekko encountered an error and can't continue 

Gekko encountered an error and can't continue 
Error: 

[binance.js] Response code 400

Meta debug info: 

Gekko version: v0.5.12
Nodejs version: v8.9.4
C:\Users\X\Desktop\gekko-0.5.13\web\routes\startGekko.js:86
 if(event.log) 
         ^ 
TypeError: Cannot read property 'log' of undefined 
      at pipelineRunner (C:\Users\X\Desktop\gekko-0.5.13\web\routes\startGekko.js:86:14)
       at Object.message (C:\Users\X\Desktop\gekko-0.5.13\core\workers\pipeline\messageHandlers\realtimeHandler.js:10:9) 
        at ChildProcess.<anonymous> (C:\Users\X\Desktop\gekko-0.5.13\core\workers\pipeline\parent.js:29:12) 
        at emitTwo (events.js:126:13) 
        at ChildProcess.emit (events.js:214:7) 
        at emit (internal/child_process.js:772:12) 
        at _combinedTickCallback (internal/process/next_tick.js:141:11) 
        at process._tickCallback (internal/process/next_tick.js:180:9)"

Was in the log. I've searched and found similar errors of "GEKKO ERROR: Gekko encountered an error and can't continue" coming up, and binance errors, but none seem to be giving an error that I've received log wise. This is my first attempt posting here so please let me know if I need to fix anything.

**Comment by HOllarves** [comment]
Make sure to be on the most recent stable version and try `npm uninstall binance && npm install binance@1.3`. That solved the problem for me.

**Comment by FreshLondon** [comment]
applied the above fix, no change:
![screen shot 2018-06-16 at 02 59 38](https://user-images.githubusercontent.com/17095036/41485004-63cf13c0-7111-11e8-9011-fc9efef518ce.jpg)

Any advice / updated fix?

**Comment by askmike** [comment]
I've since released a major upgrade with vastly improved binance integration. As such I am quite confident these specific issues are fixed. If you encounter anything again, feel free to create a new issue :)

**Comment by askmike** [comment]
See here: https://github.com/askmike/gekko/releases
