### ISSUE TITLE
bitstamp.js Rounding - Missed trades.

### ISSUE THREAD

**Issue by ewewerethefool** [askmike/gekko#1798]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
I set my strategy to sell on bitstamp. I have set my BUY price = ask, and SELL price = bid to ensure orders fulfill quickly.

* **Expected result** (what you hoped would happen)
I hoped the orders would be fulfilled quickly.

* **Actual result** (unexpected outcome)
Multiple canceled orders, reorders. I first noticed it in xrp/usd. In my log it showed an attempted purchas price of 1.18231, the market price. as I looked on in my bitstamp account at the order being placed, repeatedly and canceled, I noticed it was rounded to the nearest cent. Nowe, when tryint to trade btc/eth, it rounds to .01  . essentially trades will never go through with this rounding issue, and if they do, it could be not good.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
here is the problematic line. while I understand the need for trading in BTC/USD, this approach not take into consideration the value of other coins.

2018-01-27 11:33:41 (INFO):	Attempting to SELL 0.03278971 BCH at Bitstamp price: 0.14334071

0.03278971 | 22.1.2018 | 0.15000000

as you can see, the price was rounded up. way up. same for all pairs except for BTC/USD, ETH/USD, LTC/USD, BCH/USD

if more examples are needed i have them

 // prevent:
  // 'Ensure that there are no more than 2 decimal places.'
  price *= 100;
  price = Math.floor(price);
  price /= 100;

-- | -- | --

**Comment by billymcintosh** [comment]
Can you create a PR and we check?

**Comment by ewewerethefool** [comment]
As soon as I test, most definitely. Testing now
