### ISSUE TITLE
Error 400 on Binance live trade / 

### ISSUE THREAD

**Issue by padder1992** [askmike/gekko#1800]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
I want to create an live trade with ETH / DGD on Binance and get an 400 error. 

* **Expected result** (what you hoped would happen)
That i could trade on Binance :)

* **Actual result** (unexpected outcome)

RECEIVED ERROR IN GEKKO 509264336552564

Gekko encountered an error and can't continue

Gekko encountered an error and can't continue

Error:

[binance.js] Response code 400

Meta debug info:

Gekko version: v0.5.12
Nodejs version: v8.9.4

{"url":"https://api.binance.com/api/v1/aggTrades?symbol=DGDETH","timeout":15000}{"url":"https://api.binance.com/api/v1/aggTrades?symbol=DGDETH","timeout":15000}{"url":"https://api.binance.com/api/v1/aggTrades?symbol=DGDETH","timeout":15000}{"url":"https://api.binance.com/api/v1/aggTrades?symbol=DGDETH","timeout":15000}{"url":"https://api.binance.com/api/v1/aggTrades?symbol=DGDETH","timeout":15000}{"url":"https://api.binance.com/api/v1/aggTrades?symbol=DGDETH","timeout":15000}{"url":"https://api.binance.com/api/v1/aggTrades?symbol=DGDETH","timeout":15000}{"url":"https://api.binance.com/api/v1/aggTrades?symbol=DGDETH","timeout":15000}{"url":"https://api.binance.com/api/v1/aggTrades?symbol=DGDETH","timeout":15000}{"url":"https://api.binance.com/api/v1/aggTrades?symbol=DGDETH","timeout":15000}{"url":"https://api.binance.com/api/v1/aggTrades?symbol=DGDETH","timeout":15000}{"url":"https://api.binance.com/api/v1/aggTrades?symbol=DGDETH","timeout":15000}{"url":"https://api.binance.com/api/v1/aggTrades?symbol=DGDETH","timeout":15000}{"url":"https://api.binance.com/api/v1/aggTrades?symbol=DGDETH","timeout":15000}{"url":"https://api.binance.com/api/v1/aggTrades?symbol=DGDETH","timeout":15000}{"url":"https://api.binance.com/api/v1/aggTrades?symbol=DGDETH","timeout":15000}{"url":"https://api.binance.com/api/v1/aggTrades?symbol=DGDETH","timeout":15000}{"url":"https://api.binance.com/api/v1/aggTrades?symbol=DGDETH","timeout":15000}{"url":"https://api.binance.com/api/v1/aggTrades?symbol=DGDETH","timeout":15000}{"url":"https://api.binance.com/api/v1/aggTrades?symbol=DGDETH","timeout":15000}^C

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

I tested it with the stable and dev version. I also updated Binance (npm uninstall binance - npm install binance), set up my PC time to an atomic time server, put the time interval to 60 sec. in reg
Hard- and Software Details: Win10 32bit VM, Node.js 8.9.4, Gekko 0.5.12 (stable) and Gekko 0.5.13 (develop), Binance 1.3.2 

[2018-01-27-21-12-UTC-tradebot.log](https://github.com/askmike/gekko/files/1670557/2018-01-27-21-12-UTC-tradebot.log)

**Comment by werkkrew** [comment]
Are you sure your API key isn't set up with an IP whitelist that your current computer is not on?

**Comment by padder1992** [comment]
Yes the IP restriction is set to unlimited. But thanks for answer! :)

**Comment by werkkrew** [comment]
I am running against Binance with the 1.3.2 module right now without too much trouble.

**Comment by off7** [comment]
Hi,
I Have the same error.
I am running Binance with the 1.3.3 module.
The Error occurs when there is an attempt to buy or sell below the minimum value allowed by Binance.
When the purchase or sale is total has worked well. Unfortunately there is no way to create a minimum for buying or selling ...

**Comment by K2** [comment]
I got a 400 related perhaps.... also binance everything -current/stable from git/node

RECEIVED ERROR IN GEKKO 557870227285749


Gekko encountered an error and can't continue


Gekko encountered an error and can't continue

Error:

[binance.js] Response code 400

Meta debug info:

Gekko version: v0.5.13
Nodejs version: v6.11.4
/home/ubuntu/gekko/web/routes/startGekko.js:86
    if(event.log)
            ^

TypeError: Cannot read property 'log' of undefined
    at pipelineRunner (/home/ubuntu/gekko/web/routes/startGekko.js:86:13)
    at Object.message (/home/ubuntu/gekko/core/workers/pipeline/messageHandlers/realtimeHandler.js:10:9)
    at ChildProcess.<anonymous> (/home/ubuntu/gekko/core/workers/pipeline/parent.js:29:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:787:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
disconnect
disconnect

**Comment by unstephenk** [comment]
I'm getting this error as well. It happens after a while. I have my candlesize set to "0.5".

Same bug as #1792
