### ISSUE TITLE
DEMA indicator is not DEMA

### ISSUE THREAD

**Issue by AidasK** [askmike/gekko#1812]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
I have looked at dema indicator implementation and it is wrong.

* **Expected result** (what you hoped would happen)
It should be implemented as:
https://www.investopedia.com/ask/answers/121814/what-double-exponential-moving-average-dema-formula-and-how-it-calculated.asp

* **Actual result** (unexpected outcome)
https://github.com/askmike/gekko/blob/develop/strategies/indicators/DEMA.js

I suggest renaming current DEMA strategy. It currently calculates percentage of price change.

**Comment by askmike** [comment]
> I suggest renaming current DEMA strategy.

We can also fix it, it shouldn't be too hard to implement what is suggested on that page. Does anyone feel like fixing it?

**Comment by askmike** [comment]
I have offered a bounty of 0.003 BTC to whoever can fix this. See here for details and specific requirements: https://forum.gekko.wizb.it/thread-93.html

**Comment by cloggy45** [comment]
@askmike Do you have the excel sheet that you used to originally calculate the formulas?

**Comment by rkingy** [comment]
@askmike I've also created a new indicator here which from my back tests seems to be accurate. #1846
