### ISSUE TITLE
Tulind Issue

### ISSUE THREAD

**Issue by hansixxxx** [askmike/gekko#1815]
Hi,

everytime i get the same error when testing a strategy:
**Gekko was unable to configure Tulip Indicators:
        adx requires optInTimePeriod.**

When i try to install tulind i get this error:
gekko# npm install tulind

> tulind@0.8.9 install /mnt/c/Windows/System32/gekko/node_modules/tulind
> node-pre-gyp install --fallback-to-build

**node-pre-gyp ERR! Tried to download(404): https://tulipnode.s3.amazonaws.com/tulind/v0.8.9/Release/tulind-v0.8.9-node-v59-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for tulind@0.8.9 and node@9.4.0 (node-v59 ABI, glibc) (falling back to source compile with node-gyp)**
make: Entering directory '/mnt/c/Windows/System32/gekko/node_modules/tulind/build'
  CXX(target) Release/obj.target/tulind/tulind.o
../tulind.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE startbyindex(Nan::NAN_METHOD_ARGS_TYPE)’:
../tulind.cpp:72:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (ind->options != options->Length()) {
                      ^
../tulind.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE callbyindex(Nan::NAN_METHOD_ARGS_TYPE)’:
../tulind.cpp:127:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (ind->inputs != inputs->Length()) {
                     ^
../tulind.cpp:134:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (ind->options != options->Length()) {
                      ^
  CC(target) Release/obj.target/tulind/external/tiamalgamation.o
  SOLINK_MODULE(target) /mnt/c/Windows/System32/gekko/node_modules/tulind/lib/binding/Release/node-v59-linux-x64/tulind.node
  COPY Release/tulind.node
make: Leaving directory '/mnt/c/Windows/System32/gekko/node_modules/tulind/build'
+ tulind@0.8.9
added 49 packages in 13.636s
root@DESKTOP-1MSI8IQ:/mnt/c/Windows/System32/gekko#

Somebody can help me please

**Comment by askmike** [comment]
Unfortunately this is an issue with a different project.

Can you try post the issue here? https://github.com/TulipCharts/tulipnode

Thanks!
