### ISSUE TITLE
[FEATURE REQUEST] Update Dataset

### ISSUE THREAD

**Issue by ansonphong** [askmike/gekko#1816]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[X] feature request
[ ] question about the decisions made in the repository

Hey guys, great work on Gekko. One of things that is a very redundant aspect of operating backtesting is constantly having to import the datasets up to present moment to compare against current market conditions.

Under `Local Data` in the UI, it would be extremely helpful to have an `Update` button/link on each of the "Available datasets" which would automatically update from the latest point in the dataset up to the current time.

This would save a lot of time / redundant clicking. Curious to hear your thoughts, I'm happy to help make it happen.

**Comment by dcworldwide** [comment]
Agree that importing delta data would be ideal.
