### ISSUE TITLE
After refresh of Live bot instance information inconsistent

### ISSUE THREAD

**Issue by mladenmilev** [askmike/gekko#1820]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ * ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Did reload the Gekko webpage
I had noticed one tradeline missing as fro 0.650 ETH next line starts with 0.634 ETH (significant loss!)
That corresponds to graphic and my account on Kraken.

* **Expected result** (what you hoped would happen)

* **Actual result** (unexpected outcome)
Refreshed data got inconsistent. The missing trade did not appear.
Information in table got confusing. Reloading did not help. 

Decimal point disappeared in Trade columns. P & L got like a clock and actual values missing. 
The only value that is consistent is the %.

On the bottom of the image, you can see Gekko version. 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

![image](https://user-images.githubusercontent.com/18348943/35593034-b42f8c80-0606-11e8-8ec6-990c4f519510.png)

**Comment by askmike** [comment]
This will be taken up in the new UI, see here for details: https://forum.gekko.wizb.it/thread-1429.html
