### ISSUE TITLE
Last commit docker error

### ISSUE THREAD

**Issue by celoibarros** [askmike/gekko#1825]
Hi there,

I think there is an error on docker on the develop branch.

![screenshot from 2018-01-31 10-28-20](https://user-images.githubusercontent.com/16102901/35618094-d21650ec-0671-11e8-823b-9eac19803b3f.png)

**Comment by askmike** [comment]
Apologies! This has since been fixed here: https://github.com/askmike/gekko/commit/eeddec2c2fc163cd013fdd934d8bd5f2df86ab1b.
