### ISSUE TITLE
GDAX Prices in Gekko not matching Price in GDAX Exchange

### ISSUE THREAD

**Issue by PanoPilot** [askmike/gekko#1826]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
After backtesting my new strategy I run it in live mode to test the strategy. I've noticed that the candle.close values are different to the actual GDAX price.

Running Gekko in UI mode. Livetrade on GDAX with ETH/EUR pair and Candle = 30 min 

* **Expected result** (what you hoped would happen)

This picture shows GDAX price of ETH/EUR on 31st Jan at 12:00pm CET which is 883.29€ Candle = 30 min
![bildschirmfoto 2018-01-31 um 12 10 48](https://user-images.githubusercontent.com/35403186/35620227-ce36ff08-0680-11e8-9bfa-ffb394e1c404.png)

* **Actual result** (unexpected outcome)

With my new start running gekko on gdax ETH/EUR pair and Candle = 30 min the debugger log shows value for candle.close of 867.12€. see picture. 2nd value. the other ";" separated values are ema long, ema short etc.. at the end it shows the candle.start market time. which is surprisingly 1.5 hours earlier than the actual time. I've checked the price at this time as well on GDAX but this also do not fit.
![bildschirmfoto 2018-01-31 um 12 09 29](https://user-images.githubusercontent.com/35403186/35620345-3704f940-0681-11e8-8ace-5048148b6d2e.png)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
Note that 30 min candles from Gekko are not guaranteed to start at the :00 or :30 minute mark every hour.

> see picture. 2nd value. the other ";" separated values are ema long, ema short etc.. at the end it shows the candle.start market time

Can you post the code that generated these logs? Also provide some gekko logs (depending on the version of Gekko you are running these might be stored in the `gekko/logs` folder).

**Comment by PanoPilot** [comment]
Ya sure. please see below the code sniplet from my strategyX.js
It is spread across update(candle) and check (candle) function using a global var in the startegy.js file

In addition I added the papertrader and wachter log files. I set to 1 min Candle with History=1 min in Papertrade mode to directly compare prices between exchange and logged candle prices. I figured out the gekko is processing trading data which are 1h too late resp. lagging. And the delay gap seems to get greater the longer the bot is running.

Maybe i mad a mistake in setup or used a wrong way to log the values..  

thanks for yr help in advance!

`
method.update = function(candle) {
  // nothing!
}

// for debugging purposes: log price and ema short and ema long
method.log = function() {
  var dema = this.indicators.dema;

   message = '' + dema.short.age + sep;
   message += dema.long.result.toFixed(4) + sep 
   message += dema.short.result.toFixed(4) + sep ; 

}

method.check = function(candle) {
  var dema = this.indicators.dema;

  var price = candle.close;
  var marketTime = {format: function() {return 'N/A'}};
  marketTime = candle.start;
  
  message += price.toFixed(4) + sep;
  message += diff + sep;

  // strategy code ... taken out to show logging code only

  log.debug(message + sep + marketTime.format('YYYY-MM-DD HH:mm:ss'));
  message = '';
`

[2018-01-31-14-57-UTC-watcher.log](https://github.com/askmike/gekko/files/1682211/2018-01-31-14-57-UTC-watcher.log)

[2018-01-31-14-57-UTC-papertrader.log](https://github.com/askmike/gekko/files/1682212/2018-01-31-14-57-UTC-papertrader.log)

**Comment by PanoPilot** [comment]
ooh wair

**Comment by PanoPilot** [comment]
accidently closed

**Comment by PanoPilot** [comment]
Hi mike, thx for getting back to me.

well i checked the code of the logging. So first of all it was a timezone issue explaning the 1h diff. additional i set the canlde size to 30 minutes and took the candle.start time so in total this explanins the 1.5 hourse lag. 

the price diff were also my mistake. converting issue.

so apologies for bothering your! it was issue 47. the issue were 47 cm in front of the screen ;-)

anyway i just want to thank you for this great project which you share with us. 

especially the back testing capability is so valuable!!

thanks a lot
