### ISSUE TITLE
Error when starting the bot

### ISSUE THREAD

**Issue by SxmickY** [askmike/gekko#1828]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Hi, I tried to start the trade bot, with binance and I got this error out. BNB - WABI

* **Expected result** (what you hoped would happen)

* **Actual result** (unexpected outcome)
{ Error: SQLITE_BUSY: database is locked errno: 5, code: 'SQLITE_BUSY' }
RECEIVED ERROR IN GEKKO 704751192682212

Gekko encountered an error and can't continue

Gekko encountered an error and can't continue

Error:

DB error at `get`

Meta debug info:

Gekko version: v0.5.12
Nodejs version: v8.9.4

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by SxmickY** [comment]
Now i have this error:

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: SQLITE_BUSY: database is locked
RECEIVED ERROR IN GEKKO 109348705405975
Child process has died.

**Comment by corcoranp** [comment]
@SxmickY 
Have you Googled the error? 
Have you reviewed: https://github.com/askmike/gekko/issues/414
Are you running multiple instances of gekko from the same folder?
