### ISSUE TITLE
Developers For strategies in Gekko

### ISSUE THREAD

**Issue by gabrielomana** [askmike/gekko#1833]
**1) BB + RSI + MACD:**
 
- Buy decision must satisfy three conditions:
  *  The signal is below the bottom line of Bollinger Bands
  *  The MACD in uptrend and has a cross intersection
  *  The Relative Strength Index is in uptrend
 
- Sell decision must satisfy three conditions:
  *  The signal is above the upper line of Bollinger Bands,
  *  The MACD in downtrend and has a cross intersection,
  *  The Relative Strength Index is in downtrend
 
- Additional Parameters :
  *  Standard parameters for BB
  *  Standard parameters for RSI
  *  Standard parameters for RSI
  *  Time Frame: Must be able to run on any time frame (M1, M5, M15, M30 etc )
  *  Buy Money Management: Be able to use% of account for each buy trade
  *  Sale Money Management: Be able to use% of account for each sale trade
  *  Stop Loss:%
 
**2) 2 MA + SAR + RSI :**

- Buy decision must satisfy three conditions:
  *  The Relative Strength Index is in uptrend
  *  The MA makes a Golden Cross: Crossover involving a short-term moving average breaking above the long-term moving average
  *  The Parabolic SAR dots, begin to be hanging above the candles
 
- Sell decision must satisfy three conditions:
  *  The Relative Strength Index is in downtrend
  *  The MA Makes to Death Cross: C rossover RESULTING from a l ong-term moving average breaking above the short-term moving average or support level.
  *  The Parabolic SAR dots, begin to be hanging bellow the candles
 
- Additional Parameters :
  *  Number of periods for Short-term moving average
  *  Number of periods for Long-term moving average
  *  Standard parameters for SAR
  *  Standard parameters for RSI
  *  Time Frame: Must be able to run on any time frame (M1, M5, M15, M30 etc )
  *  Buy Money Management: Be able to use% of account for each buy trade
  *  Sale Money Management: Be able to use% of account for each sale trade
  *  Stop Loss: %

I'm looking for someone who can develop these strategies and negotiate a cost for them. my email is gabrielomana@gmail.com

**Comment by ansonphong** [comment]
@gabrielomana Not a problem to implement. Feel free to send me an email and we can discuss. phong@phong.com

**Comment by askmike** [comment]
You can also post this in the forum:

- here for general discussion: https://forum.gekko.wizb.it/forum-12.html
- here to request the strategy and offer a bounty reward: https://forum.gekko.wizb.it/thread-71.html
