### ISSUE TITLE
[i18n] Language adaption

### ISSUE THREAD

**Issue by talentoscope** [askmike/gekko#1836]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[x] feature request
[x] question about the decisions made in the repository

@askmike Is there any way of, or any plans to internationalise gekko at all for different languages? Had a few people talking about it on Discord. Community could bundle in, if that's something you'd be up for?

**Comment by askmike** [comment]
Hey,

I was off the grid for a few days, besides that it is hard for me to keep
track of the discord. So thanks for bringing this discussion to my
attention.

I think this is a great idea, however I feel it should be limited to the
web UI (else way to complex to implement). This means that it can be
implemented completely in the Vue frontend layer. Unfortunately I won't
have time to do this, it won't be high on my list. Is there anyone who
wants to work on this?

**Comment by talentoscope** [comment]
I'll ask around.

**Comment by askmike** [comment]
Note that since I am working on a new UI it probably makes more sense to only implement it there, as it will be a major rewrite.

**Comment by talentoscope** [comment]
Sounds good. Look forward to it :)

**Comment by GO1984** [comment]
I would be willing to help translate to German.
