### ISSUE TITLE
Running Gekko live on Raspberry 3B

### ISSUE THREAD

**Issue by Sarremans** [askmike/gekko#1838]
Hi all,

I'm running Gekko 0.5.12 live. Trading ETH/BTC on the GDAX exchange with  a Raspberry 3b for about 4 days with the DEMA 10/21 strategy. Any other members doing this or am i an early adatpter? I'm curious if there are some better settings to run the Gekko.

**Comment by AS2RAL** [comment]
No single indicator strategy should be considered viable. Combine it with something else.

I have great success with BB + Stoch + MACD.

**Comment by ferdiesletering** [comment]
@stfnschfr do you have an example snippet of combining the indicators?

**Comment by Kirbylix** [comment]
hi,

my Gekko's are also running on a PI.
I'm one of them:
1x UI
3x TradeBots

**Comment by askmike** [comment]
as @stfnschfr said, watch out with the default strategies, they are meant as examples.

When it comes to successful strategies, it will be hard to find people sharing their profitable secrets. But you might have more luck on the forum here: https://forum.gekko.wizb.it/forum-12.html

**Comment by Sarremans** [comment]
I did use one stategy that I've tested. But on your advice I changed to a triple stategy found the github somewhere called RSI Bull Bear. It works perfect but the other way around! It is working to get more EUR but i want more BTC. How can i change that?
