### ISSUE TITLE
Buy and Sell Events Logging Failure

### ISSUE THREAD

**Issue by LilBifi** [askmike/gekko#1842]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Started a paper trader and a trade bot with the exact same settings at around the same time.

* **Expected result** (what you hoped would happen)
The market graph of the paper trader and the trade bot should look similar.

* **Actual result** (unexpected outcome)
The trade bot's market graph is missing entries. Only the first two buy/sell events are logged. Roundtrips are not logged at all.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

To illustrate my point I took two pictures. 

The paper trader:
https://gyazo.com/bf91dda4e5d924df172ca96b4f73bdea

The trade bot:
https://gyazo.com/77f02e75ff207ea1eb621aa0b213370f

**Comment by greenbigfrog** [comment]
This is expected. The paper trader always assumes all trades it places get filled vs in the real world not all orders get filled

**Comment by askmike** [comment]
@greenbigfrog they should get filled eventually, and while they sometimes might not

@LilBifi can you post logs of the real trader (stored in `gekko/logs`)?
