### ISSUE TITLE
Feature request: Date Picker in backtest screen

### ISSUE THREAD

**Issue by rkingy** [askmike/gekko#1845]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[X] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Spending a lot of time backspacing the default dates and times on the backtest screen everytime I refresh. Would love a basic datepicker UI.

* **Expected result** (what you hoped would happen)
A quick way to set the date for backtesting.

* **Actual result** (unexpected outcome)
Slow and annoying.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
Recommend Install JS datepicker or something similar https://www.npmjs.com/package/js-datepicker

**Comment by askmike** [comment]
The UI is anything but user friendly at the moment. You make a great point and I want to tackle this with the big UI redesign, see here for more details: https://forum.gekko.wizb.it/thread-65.html

**Comment by askmike** [comment]
I'll keep this in mind and will do this with the new UI. But feel free to add it to the discussion above :)
