### ISSUE TITLE
[DOCS] talib-macd strat links to outdated doc page

### ISSUE THREAD

**Issue by dmitriz** [askmike/gekko#1847]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Read the code here:
https://github.com/askmike/gekko/blob/develop/strategies/talib-macd.js#L5

* **Expected result** (what you hoped would happen)
The link should give more information as suggested

* **Actual result** (unexpected outcome)
The link is broken, file does not exist

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
Ah! That doc is a bit outdated, instead you probably want:

- this for what a strategy is: https://gekko.wizb.it/docs/strategies/creating_a_strategy.html
- this for specific information regarding talib indicators: https://gekko.wizb.it/docs/strategies/talib_indicators.html

I am open to a PR for this (else I'll try to do it asap).
