### ISSUE TITLE
No trades made in binance

### ISSUE THREAD

**Issue by Daakko** [askmike/gekko#1849]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Ive followd all the instructions on installing GEkko

* **Expected result** (what you hoped would happen)
Ive did a backtest over the last 24 hour with the assumed stategy. Outcome is 9 trades and a gain of 54%

* **Actual result** (unexpected outcome)
There were no actual transactions made. ive runned gekko for 24 hours but no result. After this a dit the backtest and resulted in 9 transactions. I am new to this programming and have no idea what went wrong. Api is set right and i believe everything should work just fine. 

Can some help me?

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
Inside the `gekko/logs` folder there should be some logs, can you upload the one somewhere and link to it here? (maybe check that there is no personal information like the amount of money on the account).

**Comment by Daakko** [comment]
[2018-02-03-02-12-UTC-tradebot.log](https://github.com/askmike/gekko/files/1691385/2018-02-03-02-12-UTC-tradebot.log)
[2018-02-03-02-12-UTC-watcher.log](https://github.com/askmike/gekko/files/1691386/2018-02-03-02-12-UTC-watcher.log)

**Comment by Daakko** [comment]
These are both form the last few hours. Again i did a backtest on them and again there were trades made. Except in real life then.  Glad your taking the time the help me out

**Comment by askmike** [comment]
It appears you where running the CCI strategy over 10 minute candles. Looking at your tradebot.log:

    2018-02-03 05:14:48 (DEBUG):	Insufficient data available. Age:  17  of  90
    2018-02-03 05:14:48 (DEBUG):	ind:  false   17   90
    2018-02-03 05:14:48 (DEBUG):	Trend:  undefined  for  0

The CCI indicator requires at least 90 historical candles, in your case this means 90 * 10 minutes = 900 minutes of data (=15 hours of data) while the Gekko only ran for around 2 hours. For as long as your indicator is not ready it won't calculate any numbers, for as long as that happens your strategy won't spit out any trading advice. Gekko only trades on trading advice.

We are aware that this information should be visible better in the UI, right now you had no idea what was wrong and why nothing is happening. For now I can only advice to check the tradebot log every once in a while. Meanwhile we are working on a new version of the UI that will display such information better, see here: https://forum.gekko.wizb.it/thread-65.html

**Comment by Daakko** [comment]
So theoretical, if i let the cci indicator run voor 900 minutes it should be working after that?

Thanks for all the help !!!
