### ISSUE TITLE
Pump Scanner

### ISSUE THREAD

**Issue by Mix1986** [askmike/gekko#1853]
Hi, is there any plugin for gekko that allows you to run the software as a scanner to intercept and make a purchase by naturally setting a stoploos?

**Comment by askmike** [comment]
Unfortunately that's out of scope: stop losses are not naturally supported (you can define some in your strategy but it will be too slow, smallest check is once every minute). On top of that Gekko doesn't scan all markets of an exchange.

See here what Gekko is meant to do and what it isn't: https://gekko.wizb.it/docs/introduction/scope.html
