### ISSUE TITLE
Fail to Install tulind on ec2

### ISSUE THREAD

**Issue by ghost** [askmike/gekko#1854]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[*] question about the decisions made in the repository

* **Action taken** (what you did)
**not a native speaker, excuse my poor english.**
I wanna install tulind for my amazon ec2.

* **Expected result** (what you hoped would happen)

I already build up my Gekko on the server, but I can't use any strategies with tulind function, so I just realize I forgot to install it on server. I even created another new ec2 so I can make sure it's clean, but I always got stuck in the tulind installing part.

* **Actual result** (unexpected outcome)
https://i.imgur.com/Ozq65ti.jpg
>>node-pre-gyp ERR! Pre-built binaries not found for tulind@0.8.9 and node@9.5.0 (node-v59 ABI, glibc) (falling back to source compile with node-gyp)<<

Is that mean I have missed something? I noticed windows-build-tools is needed when setting up on windows, but there is no such thing to install on linux right? Or just I am being stupid, plz tell me.

attached is the error log.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
[2018-02-04T03_11_34_437Z-debug.log](https://github.com/askmike/gekko/files/1692417/2018-02-04T03_11_34_437Z-debug.log)

**Comment by SamuraiWaffle** [comment]
Try these commands then try to reinstall Tulind. 


sudo apt-get update     
sudo apt-get install python2.7

sudo npm install -g node-gyp

**Comment by ghost** [comment]
I re-intalled python and do what you ask, but it turns out the same  :(

**Comment by askmike** [comment]
@h4xon can you try again after installing the LTS version of nodejs (8.9.4)? Tulind comes with precompiled binaries for most platforms, but only for specific nodejs versions.

**Comment by ghost** [comment]
@askmike  Actually  , I installed the LTS version of nodejs since the begining. And I also tried v6.9.0 according to https://github.com/askmike/gekko/issues/1273 , But it still shows error.

**Comment by askmike** [comment]
tulind is an external project, would you mind posting the issue here?

https://github.com/TulipCharts/tulipnode

**Comment by ghost** [comment]
OK, I'll post it. Thanks!

**Comment by ghost** [comment]
I figured it out... , it needs a c++ environment but when I use `sudo yum install build-essential`  to install the kit it always fail. So I find another way to do it :  

`sudo yum groupinstall "Development Tools"`

then `npm install tulind` finally worked out!

Hope someone encountered the same problem can understand what I am trying to say with my bad english.

**Comment by askmike** [comment]
Great stuff! Stuff in this issue tracker usually ranks pretty good on Google, but you can also post it to the forum if you feel like it: https://forum.gekko.wizb.it/forum-22.html

**Comment by bogdangoie** [comment]
@h4xon that worked for me, it was missing the c++ enviroment. Thanks a lot :+1: 

FYI I am running OpenSuse Tumbleweed so I went in Yast and installed patterns-devel-C-C++-devel_C_C++ . Just searched for C/C++ Development.

Also only tulind@0.8.4 worked for me, for the other versions I would get a 404 through npm.
