### ISSUE TITLE
Error: Cannot find module '/core/../plugins/postgres/writer'

### ISSUE THREAD

**Issue by Kirbylix** [askmike/gekko#1857]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
import Data with postgres adapter

* **Expected result** (what you hoped would happen)
Data in the Database -> postgres

* **Actual result** (unexpected outcome)
Error: Cannot find module '/core/../plugins/postgres/writer'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.Module._load (module.js:463:25)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at load (/home/pi/gekko-stable/core/pluginUtil.js:90:25)
    at /home/pi/gekko-stable/node_modules/async/dist/async.js:1156:9
    at replenish (/home/pi/gekko-stable/node_modules/async/dist/async.js:1030:17)
    at /home/pi/gekko-stable/node_modules/async/dist/async.js:1034:9
    at _asyncMap (/home/pi/gekko-stable/node_modules/async/dist/async.js:1154:5)
    at /home/pi/gekko-stable/node_modules/async/dist/async.js:1240:16
RECEIVED ERROR IN IMPORT 162636698413086
Child process has died.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
Branch: stable

**Comment by askmike** [comment]
Please post your config.

**Comment by Kirbylix** [comment]
which config ?
i try this from the GUI

**Comment by askmike** [comment]
In that case the UIConfig, or whichever config you used to configure postgresql :)

**Comment by manditz** [comment]
// This config is used in both the
// frontend as well as the web server.

// see https://github.com/askmike/gekko/blob/stable/docs/installing_gekko_on_a_server.md

const CONFIG = {
  headless: true,
  api: {
    host: '0.0.0.0',
    port: 3000,},
  ui: {
    ssl: false,
    host: '144.217.12.216',
    port: 3000,
    path: '/'
  },
  adapter: 'sqlite'
}

if(typeof window === 'undefined')
  module.exports = CONFIG;
else
  window.CONFIG = CONFIG;

**Comment by askmike** [comment]
I am not sure how you're trying to load postgresql, did you configure anything else?

> adapter: 'sqlite'

Your UIConfig is configured to use sqlte, not postgresql.

**Comment by Kirbylix** [comment]
UiConfig:
```
const CONFIG = {
  headless: true,
  api: {
    host: '0.0.0.0',
    port: 3000,
    timeout: 120000 // 2 minutes
  },
  ui: {
    ssl: false,
    host: 'xxx.xxx.xxx.xxx',
    port: 3000,
    path: '/'
  },
  adapter: 'postgres'
}

if(typeof window === 'undefined')
  module.exports = CONFIG;
else
  window.CONFIG = CONFIG;
```

baseConfig.js:

```
config.postgresql = {
  path: 'plugins/postgresql',
  version: 0.1,
  connectionString: 'postgres://postgres:postgres@localhost:5432', // if default port
  database: 'gekko', // if set, we'll put all tables into a single database.
  schema: 'public',
  dependencies: [{
    module: 'pg',
    version: '6.1.0'
  }]
}
```

the candle write from the command line works great....
But i can´t do any backtest from the GUI
