### ISSUE TITLE
get confirmation of trade

### ISSUE THREAD

**Issue by aapsoftware** [askmike/gekko#1858]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[ x] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)

* **Expected result** (what you hoped would happen)
when the strategy decides to trade it issues an advice ('long' or 'short'). Is the a way for the strategy to get confirmation for the placed order? 
What is happening is that the strategy issues an order cu buy say @0.172 but that only places an order in a queue and you need to know when the trade executed so you can issue a sell order. 
Is there a way to achieve that?

* **Actual result** (unexpected outcome)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by werkkrew** [comment]
This was added in a recent PR in the dev branch.

https://github.com/askmike/gekko/pull/1810

**Comment by aapsoftware** [comment]
hmm, reading the comments I'm not sure I understand the whole thing; does this provide a way for the strategy to know when the trade has executed? Mind that you can be in a trade for many hours, days even...

**Comment by askmike** [comment]
Yep! Once the trade is fully completed (however many hours later) your strat can listen to an event by creating an `onTrade` method. However there are currently a few known bugs with it, for example see #1852, don't expect this to be super stable yet. We are actively working on this. There are a few github issues that have discussions about this kind of func, see for example #1834). As such I am closing this.
