### ISSUE TITLE
NGINX setup trouble on vps

### ISSUE THREAD

**Issue by monkeybizness** [askmike/gekko#1860]
guys,i'm having lot of trouble for setting up gekkko on my vps, i followed the guide 

https://gekko.wizb.it/docs/installation/installing_gekko_on_a_server.html#configuring-nginx-as-a-reverse-proxy

and work fine if i run the configuration in trust environment, but when i try to set up nginx my browser (firefox) is unable to connect, i've tried many configuration but nothing.

my UIconfig file is this: 

onst CONFIG = {
    headless: true,
    api: {
        host: '127.0.0.1',
        port: 3000,
    },
    ui: {
        ssl: true,
        host: 'xx.xx.xx.xx', // my VPS public IP
        port: 443,
        path: '/' // change this if you are serving from something like `example.com/gekko`
    },
    adapter: 'sqlite'

while my  default config file for niginx is 👍 

       

server {
    listen 80;
    listen [::]:80;
    server_name xx.xx.xx.xx;  // my VPS public IP
     return 301 https://$server_name$request_uri;
}

upstream websocket {
    server localhost:3000;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    root /var/www/html;

    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;    

    location / {
            proxy_buffers 8 32k;
            proxy_buffer_size 64k;

            proxy_pass http://websocket;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-NginX-Proxy true;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_read_timeout 86400s;
            proxy_send_timeout 86400s;

            auth_basic "Restricted Content";
            auth_basic_user_file /etc/nginx/.htpasswd;

where do i am wrong?

**Comment by askmike** [comment]
I am not sure what "unable to connect" means, but this is most likely a DNS issue I am guessing. Would you mind asking this on the forum instead? When you do that please come with detailed information with what you mean with "cannot connect" (is there an error? which one? does nginx logs any errors?). Thanks!

https://forum.gekko.wizb.it/forum-19.html
