### ISSUE TITLE
The Backtest show real results?

### ISSUE THREAD

**Issue by iquirino** [askmike/gekko#1863]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[X] question about the decisions made in the repository

* **Action taken** (what you did)
I got more than 3000 % in 3 days in paper trader.
When i start a live trader with real money, i will get more than 3000 % again?
If yes, i will do it as soon as possible. ^^

Anyone know if has any difference on backtest and real results?

* **Expected result** (what you hoped would happen)
Yes

* **Actual result** (unexpected outcome)
I dont know

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
It's only accurate if you properly configured the paper trader, see here for some details: https://gekko.wizb.it/docs/features/backtesting.html#Simplified-simulation

If you have more questions feel free to ask them on the forum: https://forum.gekko.wizb.it/

:)

**Comment by iquirino** [comment]
My graph is very similar to your image, so its more closer to 3000 % or not?
Candle size: 1 minute
Using: RSI
```
{
    "interval": 5,
    "thresholds": {
        "low": 40,
        "high": 50,
        "persistence": 1
    }
}
```

Thank you by your fast answer!
You got some points with me... I will try it with real money...

**Comment by iquirino** [comment]
Using: RSI
{
    "interval": 5,
    "thresholds": {
        "low": 40,
        "high": 50,
        "persistence": 1
    }
}

**Comment by askmike** [comment]
I wouldn't run it with real money if you're not sure what's happening. But this is not the place to discuss this, please use the forum.

**Comment by iquirino** [comment]
I'm not using backtesting, i'm using the paper simulation.
Has any difference about profit or it consider only OHCL?
