### ISSUE TITLE
Can't import coinfalcon data

### ISSUE THREAD

**Issue by jk-85** [askmike/gekko#1867]
* **I'm submitting a ...**
[*] bug report
[ ] feature request
[ ] question about the decisions made in the repository

I tried the following: I reinstalled the newest gekko through git on my xubuntu 16.04 and tried to import coinfalcon data for backtesting, but it fails. Binance for example works. Some days ago with some earlier versions of gekko I was able to import coinfalcon-data without problems, but now gekko says "Some markets were unscannable, click here for details". Unable to find datasets in the following markets: - coinfalcon:BTC:LTC - coinfalcon:EUR:BTC Seems like some bugs or changes in the coinfalcon API and therefore problems with actual node-package if you will ask me?

I can't provide log-files, becuse they were only written when running in live-mode, and I can't run live-mode to the prior import-failure for coinfalcon.

**Comment by askmike** [comment]
Can you delete your history folder and try again?

**Comment by jk-85** [comment]
I just deleted the entire content, history and tried to import about 1-2 days of coinfalcon-data. It downloaded successfully, then I went to backtest-tab and he showed me "No Data found Lets add some".  If I click on this link he said me that coinfalcon-data-import is currently running and showed me the asset and currency pair, but when I click on this he jumps back to the importer. I quit node gekko --ui with CTRL+C, started it again, clicked on "Local data" tab -> Scan markets and when the same error came up again: "Some markets were unscannable, click here for details. - coinfalcon:BTC:LTC"

**Comment by minyor** [comment]
Hi, same problem.
@jk-85 can you please tell, which last version you tried works with coinfalcon?

**Comment by jk-85** [comment]
I don't remember, some version bigger than 0.5.8 I think (0.5.8 has no coinfalcon support).

**Comment by dano000** [comment]
Same problem for me.

**Comment by splus2** [comment]
I encountered with the same problem as well. Windows deployment, Poloniex.
