### ISSUE TITLE
The fastest adapter

### ISSUE THREAD

**Issue by iquirino** [askmike/gekko#1869]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[X] question about the decisions made in the repository

* **Action taken** (what you did)
Should i install postgres or mongodb?
What about performance and compatibility?
Thank you!

**Comment by askmike** [comment]
This is another question better suited for the forum, personally I use postgres a lot. Though it's a bit harder to setup and manage. Please ask all further questions on the forum.
