### ISSUE TITLE
Bash on Windows can't enable tulind lib.

### ISSUE THREAD

**Issue by alieonsido** [askmike/gekko#1870]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[X] question about the decisions made in the repository

* **Action taken** (what you did)
use customize strategy. 

* **Expected result** (what you hoped would happen)
It can works such as others.

* **Actual result** (unexpected outcome)
log poped up `tulip indicators is not enabled.`

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

My environment is WSL (Windows Subsystem for Linux).

This is log for using tulip lib:

2018-02-06 13:44:44 (INFO):	Setting up Gekko in realtime mode
2018-02-06 13:44:44 (INFO):	
2018-02-06 13:44:44 (INFO):	Setting up:
2018-02-06 13:44:44 (INFO):		 Candle writer
2018-02-06 13:44:44 (INFO):		 Store candles in a database
2018-02-06 13:44:44 (INFO):	

2018-02-06 13:44:44 (INFO):	Setting up:
2018-02-06 13:44:44 (INFO):		 Trading Advisor
2018-02-06 13:44:44 (INFO):		 Calculate trading advice
2018-02-06 13:44:45 (INFO):		 Using the strategy: tulip-adx
2018-02-06 13:44:45 (WARN):	TALIB indicators could not be loaded, they will be unavailable.
2018-02-06 13:44:45 (WARN):	TULIP indicators could not be loaded, they will be unavailable.

and, this is my document [screenshot](https://imgur.com/a/P0B59).

and, I'm sure that I installed tulind and install all step by step. Furthermore, node_module was deleted and reinstall.
tulip, tulind, ta-lib also installed by `npm install tulind` , `npm install talib` , `npm install tulip`
or, I still lose something?

Tks for your help.

**Comment by alieonsido** [comment]
Note:
In Windows10 cmd, tulind can works.

**Comment by askmike** [comment]
Unfortunately I don't know anything about Windows Bash. ping @thegamecat.

**Comment by cmroche** [comment]
`npm i tulind` is the correct command line to install it, pay attention to the output because it probably failed. We'll need to know why it failed.

If there isn't a pre-built tulind package available for your specific set of versions than you may also need to install build-essentials in order to rebuild the library.

`sudo apt-get install build-essential`

**Comment by thak777** [comment]
I've got build-essential installed.  It still fails for me:

```
thak@DESKTOP-3SPPG79:~/gekko$ npm install tulind

> tulind@0.8.9 install /home/thak/gekko/node_modules/tulind
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://tulipnode.s3.amazonaws.com/tulind/v0.8.9/Release/tulind-v0.8.9-node-v57-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for tulind@0.8.9 and node@8.9.4 (node-v57 ABI, glibc) (falling back to source compile with node-gyp)
make: Entering directory '/home/thak/gekko/node_modules/tulind/build'
  CXX(target) Release/obj.target/tulind/tulind.o
../tulind.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE startbyindex(Nan::NAN_METHOD_ARGS_TYPE)’:
../tulind.cpp:72:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (ind->options != options->Length()) {
                      ^
../tulind.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE callbyindex(Nan::NAN_METHOD_ARGS_TYPE)’:
../tulind.cpp:127:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (ind->inputs != inputs->Length()) {
                     ^
../tulind.cpp:134:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (ind->options != options->Length()) {
                      ^
  CC(target) Release/obj.target/tulind/external/tiamalgamation.o
  SOLINK_MODULE(target) /home/thak/gekko/node_modules/tulind/lib/binding/Release/node-v57-linux-x64/tulind.node
  COPY Release/tulind.node
make: Leaving directory '/home/thak/gekko/node_modules/tulind/build'
+ tulind@0.8.9
added 33 packages and updated 2 packages in 13.808s
```

**Comment by cmroche** [comment]
@thak777 Actually that succeeded to install, the error you are seeing is just saying that it could not download a pre-built library, the result being that it fell back to compilation which succeeded.
