### ISSUE TITLE
Tradebot errors out on first trade attempt (Binance)

### ISSUE THREAD

**Issue by Red-Maximus** [askmike/gekko#1872]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Started new live tradebot.

* **Expected result** (what you hoped would happen)
Tradebot would trade on my behalf.

* **Actual result** (unexpected outcome)
Errored out on the first trade attempt.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

C:\...\gekko\plugins\performanceAnalyzer\performanceAnalyzer.js:112
    duration: this.roundTrip.exit.date.diff(this.roundTrip.entry.date)
                                       ^
TypeError: this.roundTrip.exit.date.diff is not a function
    at PerformanceAnalyzer.handleRoundtrip (C:\...\gekko\plugins\performanceAnalyzer\performanceAnalyzer.js:112:40)
    at PerformanceAnalyzer.bound [as handleRoundtrip] (C:\...\gekko\node_modules\lodash\dist\lodash.js:729:21)
    at PerformanceAnalyzer.logRoundtripPart (C:\...\gekko\plugins\performanceAnalyzer\performanceAnalyzer.js:94:10)
    at PerformanceAnalyzer.bound [as logRoundtripPart] (C:\...\gekko\node_modules\lodash\dist\lodash.js:729:21)
    at PerformanceAnalyzer.processTrade (C:\...\gekko\plugins\performanceAnalyzer\performanceAnalyzer.js:72:8)
    at Trader.bound 
(C:\...\gekko\node_modules\lodash\dist\lodash.js:729:21)
    at emitOne (events.js:121:20)
    at Trader.emit (events.js:211:7)
    at Trader.bound [as emit] 
(C:\...\gekko\node_modules\lodash\dist\lodash.js:729:21)
    at Manager.Trader.manager.on.trade 
(C:\...\gekko\plugins\trader\trader.js:24:10)

**Comment by askmike** [comment]
This should have been fixed, can you verify what version of gekko you are running? If you downloaded it via git let me know the output of `git log | head`?

**Comment by Red-Maximus** [comment]
I cloned the repo I believe on Saturday and did a pull just to be sure Sunday or Monday, so I should be up to date, but let me know if I've made an error. Thanks for the response!

`git log | head` output:

commit 09f96d531c9375c110e0bd520bd06781ab075646
Author: Paulovms <paulovms@gmail.com>
Date:   Sat Feb 3 10:47:16 2018 -0200

    Fix Dema (#1822), fix #1812

    Fix DEMA

commit d0f94cbec5106773d7a78f64e5d7474af41c2bcf
Author: Richard King <richard.king@rocketspark.com>

**Comment by askmike** [comment]
Your version is too old. 2 commits after the one you have the bug was fixed :)

**Comment by Red-Maximus** [comment]
Thanks for the help. Sorry that I missed it. Keep up the great work!

**Comment by sky9662** [comment]
Hello @askmike,
I'm currently using Gekko v0.5.13 and Gekko UI v0.2.0, a dev version I downloaded a week ago,
and I have the exact same problem when using Live Trade. 
Can I ask what version has this bug fixed?
Thanks!
