### ISSUE TITLE
Machine learning strategy by Mark

### ISSUE THREAD

**Issue by markvdberg0** [askmike/gekko#1873]
It does work but is nowhere consistent. Would love to discuss the code and make it better. Reference: https://github.com/askmike/gekko/issues/789

```
// npm install neataptic --save
const neataptic = require('neataptic')
const _ = require('lodash');
const config = require ('../core/util.js').getConfig();
const async = require ('async');
const log = require('../core/log.js');

// let's create our own method
var method = {};

// prepare everything our method needs
method.init = function() {
    this.name = '007';
    this.requiredHistory = config.tradingAdvisor.historySize;
    this.price = 0;
    this.open_order = false;

    // preprate neural network
    this.network = new neataptic.architect.LSTM(1,9,1);
    this.trainingData = [];
    this.obj = {};
}

// what happens on every new candle? 
method.update = function(candle) {

    this.obj['input'] = [candle.open/20000]; // divide with 20k, normalizing our input and output
    this.obj['output'] = [candle.close/20000];

    // train the neural network
    this.trainingData.push(this.obj);
    this.network.train(this.trainingData, {
        log: 0,
        iterations: 1000,
        error: 0.03,
        rate: 0.005,
        clear: true
    });
   
}


method.log = function() {

}

// check is executed after the minimum history input
method.check = function(candle) {

    /* Candle information
    { id: 103956,
      start: moment("2018-02-04T00:00:00.000"),
      open: 9080.49,
      high: 9218.98,
      low: 9022,
      close: 9199.96,
      vwp: 9097.252446880359,
      volume: 802.5146890000001,
      trades: 8086 }
    */

    //let's predict the next close price on the current close price;
    var predicted_value = this.network.activate(candle.close/20000)*20000;

    // % change in current close and predicted close
    var percentage = ((predicted_value-candle.close)/candle.close)*100;

    if(percentage > 1 && !this.open_order)
    {
        log.info("Buy: $"+candle.close);
        this.price = candle.close;
        this.open_order = true;
        return this.advice('long');

    }else if(this.open_order){
        this.open_order = false;
        log.info("Sold: $"+candle.close);
        return this.advice('short');

    }

    return this.advice();
}

module.exports = method;
```

![test](https://user-images.githubusercontent.com/34721184/35868297-63297b4c-0b5c-11e8-992d-b94c56ffab72.PNG)

**Comment by DrappierTechnologies** [comment]
Check out the gekko discord https://discord.gg/26wMygt specifically discuss-strategies channel.

**Comment by talentoscope** [comment]
Look promising. I know @DustinJSilk is playing with algorithms with reactive-trader. This may be something he would interested in :thinking:

**Comment by tmvnk** [comment]
Which candle size do you use here? Which exchange and pair?

**Comment by askmike** [comment]
Awesome stuff! May I ask you to post this on the forum (or as @DrappierTechnologies suggested on discord)? This would be a good place to post this: https://forum.gekko.wizb.it/forum-12.html

I am trying to only have bugs and issues on here :)

**Comment by quangtho2910** [comment]
@markvdberg0 What is your discord id dude? I would like to ask something. Thanks a lot

**Comment by xFFFFF** [comment]
Strat have bad work on my backtests:
btc-fuel, 2 last months - PROFIT REPORT) simulated profit:         -394.69783106 BTC (-98.67445776%)
btc-vive, 2 last months - PROFIT REPORT) simulated profit:		 -392.75026188 BTC (-98.18756547%)

**Comment by SLTrades** [comment]
I'm working on my own machine learning script similar to to this one. In mine I manipulated the OHLC data in a way that I believe will find patterns better. I have been struggling for ideas on how to measure the systems performance relative to the volatility of the set up. Thanks for sharing it has given me some goof ideas.
