### ISSUE TITLE
--backtest config select dataRange?

### ISSUE THREAD

**Issue by tmvnk** [askmike/gekko#1874]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Want to select a dataRange when --backtest via the terminal. Now there is not such an option in config.js files

* **Expected result** (what you hoped would happen)

* **Actual result** (unexpected outcome)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
Yes there is, you can configure the daterange like so:

    config.backtest = {
      daterange: {
        from: "2017-08-16 04:00:00",
        to: "2017-08-17 00:00:00"
      }
    }
