### ISSUE TITLE
strategy cancel/update order

### ISSUE THREAD

**Issue by aapsoftware** [askmike/gekko#1878]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ x] question about the decisions made in the repository

* **Action taken** (what you did)
n/a

* **Expected result** (what you hoped would happen)
n/a

* **Actual result** (unexpected outcome)
n/a

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

is there a way for a strategy to cancel an order or update an order (instead of cancelling and placing a new one should send an update message to the exchange)

**Comment by askmike** [comment]
Strategies cannot do anything with orders unfortunately.

But you are right: this is something that should be improved: some exchanges natively support to move an order, which would be better. And of course Gekko shouldn't cancel an order to create a new one at the same height..

**Comment by askmike** [comment]
There is a proposal to improve this, see this dicussion https://github.com/askmike/gekko/pull/1834#issuecomment-362974808.

I will make sure improvements you want will be included in the new functionality :) Closing this as a dup for now, if you want to continue the discussion please do so in the above link.
