### ISSUE TITLE
How Can I start gekko?

### ISSUE THREAD

**Issue by tiwirld** [askmike/gekko#1881]
Hello, i don't know how start gekko.

I drag the gekko.js on node.exe but it doen't run.

There are some newbie tutorial? Thank you!

**Comment by dcworldwide** [comment]
I'd follow this https://gekko.wizb.it/docs/installation/installing_gekko.html

**Comment by tiwirld** [comment]
thank you so much! i Can install it, but when I try to acces for http://localhost:3000 the page reject my connection

**Comment by tiwirld** [comment]
ERR_CONNECTION_REFUSED

**Comment by dcworldwide** [comment]
Have you started the gekko server and UI as per the documentation? 

If yes, make sure that port 3000 is not already in use and that you do not have a firewall blocking access.

**Comment by tiwirld** [comment]
Yes node gekko --ui

I try another ports (30002,30005) with windows firewall desactivated, and all time ERR_CONECTION_REFUSED

**Comment by askmike** [comment]
Unfortunately at this stage Gekko is quite technical to run, I am working on a hosted version which is simpler for people without a technical background to use. Read more about that here: https://forum.gekko.wizb.it/thread-1435.html

I have to close this since this is a bug tracker and not a support forum. You can try posting in the forum here: https://forum.gekko.wizb.it/index.php

**Comment by tiwirld** [comment]
Hi! I found the problem, API an UI must have the same port!

But now, when I press star (after input API Key), if i show the console on Chrome I have this message:

Uncaught TypeError: Cannot read property 'start' of undefined
    at s.gekkoConfig (build.js:16)
    at Ri.get (build.js:6)
    at Ri.evaluate (build.js:6)
    at s.gekkoConfig (build.js:6)
    at startGekko (build.js:16)
    at s.n [as startGekko] (build.js:6)
    at start (build.js:16)
    at Proxy.n (build.js:6)
    at click (build.js:16)
    at HTMLAnchorElement.e (build.js:6)
