### ISSUE TITLE
Baiance API has changed. 

### ISSUE THREAD

**Issue by tristanjo** [askmike/gekko#1888]
I am interested in purchasing your program.

I think the Baiance API has changed. Is it possible to trade?

https://github.com/binance-exchange/binance-official-api-docs/blob/master/wapi-api.md

![20180209_182247](https://user-images.githubusercontent.com/32695020/36020857-6921e904-0dc7-11e8-83f0-d0a9777e6d2f.jpg)

**Comment by Red-Maximus** [comment]
I'm interested if this is what's causing Binance errors now. I've been trying to restart Gekko for Binance trading since their outage and I keep getting an error 400 with no other information. However, the Binance page is still not appearing even though trading on the mobile app is working, so that might be it.

**Comment by ERR1R** [comment]
https://us.binance.com works.. is there a way to change the url in gekko to this url?

edit: nvm.. the url is https://api.binance.com/ but that just shows an nginx page..

**Comment by Red-Maximus** [comment]
I don't trust any URL that isn't https://www.binance.com unless Binance announced others on an official channel.

**Comment by ERR1R** [comment]
Thats from the official twitter account lol

https://twitter.com/cz_binance/status/961888554224726017

**Comment by sparkes25** [comment]
binance is not up and running yet, many people cant log in or even open the trading exchange, i would avoid trading on there for a day or to while they sort there stuff out

**Comment by souljaecker** [comment]
Are you sure? No data import and no trades possible. Binance posted that they have changed something with their api...i refreshed the api key but the issue stays.

**Comment by askmike** [comment]
Binance is still experiencing a ton of problems, quickly changing some URL is not the way to go I think.

If you have a workaround by hotpatching Gekko to use a different URL please discuss that here: https://forum.gekko.wizb.it/forum-7.html

I'm closing this as I don't think the API changed (it's just not working right now). If someone has active information about some breaking API change please comment and we can reopen.
