### ISSUE TITLE
StochRSI_MACD_BB start no trades

### ISSUE THREAD

**Issue by johnnash95** [askmike/gekko#1891]
Note: for support questions, please join our Discord server

I'm submitting a ...
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

Action taken (what you did)
Tried using StochRSI, MACD and BBands with Binance.

Expected result (what you hoped would happen)
Automatic trades.

Actual result (unexpected outcome)
No trades at all using StochRSI, MACD and BBands with Binance.

Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
My strat settings:
 interval: 14,
  short: 12,
  long: 26,
  signal: 9, 
  bbands: {
    TimePeriod: 20,
    NbDevDn: 2,
    NbDevUp: 2,
    persistence_upper: 10,
    persistence_lower: 10,  
  }, 
  thresholds: {
    low: 20,
    high: 80,
    down: -0.1,//-2,//-0.1,
    up: 0.1,//1.5,//0.25,   
    // How many candle intervals should a trend persist
    // before we consider it real?
    persistence: 2

**Comment by johnnash95** [comment]
update: Strat works with no error but it makes only 0 or 1 trade

**Comment by askmike** [comment]
Without a strategy and logs we can't help you. I don't think this is a bug but more likely a strategy at fault (being ran over a market it isn't designed for for example). Please post more details (the strat, logs) in the forum here so we can have a look: https://forum.gekko.wizb.it/forum-12.html

**Comment by johnnash95** [comment]
i've posted it on your forum man ;)
https://forum.gekko.wizb.it/thread-1462-post-1805.html#pid1805

2018-02-10 6:33 GMT+01:00 Mike van Rossum <notifications@github.com>:
