### ISSUE TITLE
[Date format and exposure error] bug report

### ISSUE THREAD

**Issue by elaarabi** [askmike/gekko#1892]
Hello Everyone,

I would like to submit a bug report concerning date format and erroneous exposure in Strat runners.
Please check the joined picture.

PS : Data spanning 3 days.

![gekko](https://user-images.githubusercontent.com/5952221/36047108-092b8bc0-0dd3-11e8-80dd-d762cb418e6e.png)

**Comment by askmike** [comment]
This is fixed in the latest develop! I'll push out a new release asap.
