### ISSUE TITLE
Windows VPS strat runner issue

### ISSUE THREAD

**Issue by manditz** [askmike/gekko#1894]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Setup Gekko on a Windows VPS
Without header settings and loaded UI through ip
Started a Binance Live trader

* **Expected result** (what you hoped would happen)
Starts trading

* **Actual result** (unexpected outcome)
Live trader would not start on UI and below error on node.js

Gekko 958447490367624 started
  --> POST /api/startGekko 200 334ms 146b
(node:4436) UnhandledPromiseRejectionWarning: Error: ETIMEDOUT
    at Timeout._onTimeout (C:\Users\Administrator\Desktop\Gekko\gekko-develop\gekko-develop\node_modules\request\request.js:846:19)
    at ontimeout (timers.js:458:11)
    at tryOnTimeout (timers.js:296:5)
    at Timer.listOnTimeout (timers.js:259:5)
(node:4436) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4436) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
Are you able to do other things like import and backtest?

**Comment by manditz** [comment]
Same error when i tried importing
