### ISSUE TITLE
poloniex buy order confirmation not received

### ISSUE THREAD

**Issue by aapsoftware** [askmike/gekko#1897]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
I have a strategy running and have noticed a few times this happening; and buy order is placed, the orders is executed on the exchange but the confirmation never comes.
17:29:16 (DEBUG):	In uptrend since 2 candle(s): @ 0.01817225
2018-02-10 17:29:16 (DEBUG):	BUY@  0.01817225  ( 0.018217680625 )
2018-02-10 17:29:16 (INFO):	Trader Received advice to go long. Buying  LTC
2018-02-10 17:29:18 (INFO):	Attempting to BUY 0.2526270007627706 LTC at Poloniex price: 0.01817771

I did change something in the code but this should not influence this:
```
--- a/plugins/trader/portfolioManager.js
+++ b/plugins/trader/portfolioManager.js
@@ -253,9 +253,9 @@ Manager.prototype.noteOrder = function(err, order) {
   }
 
   this.orders.push(order);
-  // if after 1 minute the order is still there
+  // if after 20 minute the order is still there
   // we cancel and calculate & make a new one
-  setTimeout(this.checkOrder, util.minToMs(1));
+  setTimeout(this.checkOrder, util.minToMs(20));

```
there is no error message; sometimes I see "Poloniex returned an error, retrying.." but it's not the case now.
* **Expected result** (what you hoped would happen)
I expect the order confirmation to be received  every time

* **Actual result** (unexpected outcome)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
exchange poloniex
Gekko v0.5.12

**Comment by askmike** [comment]
Could you format the code that you changed?

**Comment by askmike** [comment]
It looks like you added a new timeout for noteOrders, so there are now 2. Why did you do this?

**Comment by aapsoftware** [comment]
reformated to code now. I changed the timeout to be 20 min.
I did this a a quick way to make gekko not cancel the sell orders it was placing and keep them at the original sell price for at least 20 min.

I had a better look at the logs and it looks like I do get the BUY order execution confirmation, but after 20 min, which makes sense given the changes I made.

But this raises another question - since this is not the right way to do it, how do I achieve what I was looking for: stop gekko from canceling the orders it places after 1 min. I want it to place an order at a given price (even if for now I can't specify the price and can only issue an advice once the price is reached) and keep it there until executed.

**Comment by askmike** [comment]
Right now it's a bit hard to hack that in, but it won't be for long. I'm working on the concept of "execution strategies", where how a trade gets executed (we need to sell X BTC into USD) will be managed outside the portfolioManager. See here for the idea: https://github.com/askmike/gekko/pull/1834#issuecomment-362974808

> stop gekko from canceling the orders it places after 1 min

This is current behaviour, in the future Gekko won't cancel if the order is still at the top of the book.
