### ISSUE TITLE
Strat does not identify the 'trend'.

### ISSUE THREAD

**Issue by johnnash95** [askmike/gekko#1904]
* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
starting my strategy I noticed that in the .check phase the variable 'trend' always returns 'in no trend'.
so strat ignore all the settings if 'trend.up' and 'trend.down'. the only one that works is 'in no trend'

* **Expected result** (what you hoped would happen)

* **Actual result** (unexpected outcome)
![schermata 2018-02-11 alle 12 23 01](https://user-images.githubusercontent.com/35278831/36072793-65b62176-0f26-11e8-9192-afd2d974bc59.png)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
this is part of code where var trend is configured:

if(MACDsaysSELL && StochRSIsaysSELL) {
		// new trend detected
		if(this.trend.direction !== 'high')
			this.trend = {
				duration: 0,
				persisted: false,
				direction: 'high',
				adviced: false
			};

		this.trend.duration++;

		log.debug('In high since', this.trend.duration, 'candle(s)');

		if(this.trend.duration >= this.settings.thresholds.persistence )
			this.trend.persisted = true;

		if(this.trend.persisted && !this.trend.adviced) {
			this.trend.adviced = true;
			this.advice('short');
		} else
			this.advice('short');

	} 
	//buy when stochRSI in high and MACD in low	
	else if(MACDsaysBUY && StochRSIsaysBUY && BBsayBUY) {

		// new trend detected
		if(this.trend.direction !== 'low')
			this.trend = {
				duration: 0,
				persisted: false,
				direction: 'low',
				adviced: false
			};

		this.trend.duration++;

		log.debug('In low since', this.trend.duration, 'candle(s)');

		if(this.trend.duration >= this.settings.thresholds.persistence)
			this.trend.persisted = true;

		if(this.trend.persisted && !this.trend.adviced) {
			this.trend.adviced = true;
			this.advice('long');
		} else
			this.advice();

	} else {
		// trends must be on consecutive candles
		this.trend.duration = 0;
		log.debug('In no trend');

		this.advice('long');
	}

**Comment by askmike** [comment]
Hey! Unfortunately this is not the place to get strategy support. This is the perfect place for it: https://forum.gekko.wizb.it/forum-12.html
