### ISSUE TITLE
API:Invalid nonce Kraken

### ISSUE THREAD

**Issue by gugol2** [askmike/gekko#1907]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ * ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Start live gekko.

* **Expected result** (what you hoped would happen)
Trading.

* **Actual result** (unexpected outcome)
Error: `[kraken.js] (getPortfolio) returned an error, retrying: API:Invalid nonce`.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
It keeps logging that error because it tries to do the operation again and again.

**Comment by cmroche** [comment]
This is generally related to network instability either on your side, or also with Kraken who is continuing to have issues servicing requests. You can help reduce this by going into your kraken api settings and changing the none windows to 15000 (to allow 15 seconds of out of order requests).

**Comment by gugol2** [comment]
Thank you.
Initially I did that, but any changes in the API keys takes some time to propagate. That is why I opened this issue.
I set it to 10000 (something between 3000 and 15 said the docs of the API) and now it works.

**Comment by cmroche** [comment]
A minor clarification for others, since it has come up a bit in the past, the Kraken API suggest that you set a 3 to 15 second window for the nonce. The actual value you input in the settings will depend on the software implementing the API. In our case (and in most cases) the nonce will be milliseconds epoch time, so the correct entry is 3000 - 15000, not 3 - 15 :)

**Comment by cmroche** [comment]
@gugol2 Thank you for confirming, if everything is still working well please mark the issue as closed.
