### ISSUE TITLE
Binance Trading Error

### ISSUE THREAD

**Issue by Red-Maximus** [askmike/gekko#1910]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Trade with Gekko using Binance exchange and API

* **Expected result** (what you hoped would happen)
Trades to execute

* **Actual result** (unexpected outcome)
Trades did not execute

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)\

It keeps saying it cannot read "statusCode" which I believe is what was added after Binance shut down the other day, but I created a new API yesterday and it still won't trade.

Error below:

C:\...\Gekko\gekko\node_modules\binance\lib\rest.js:78
                    if (response.statusCode === 400 && payload.code === -1021 &&
                                 ^

TypeError: Cannot read property 'statusCode' of undefined
    at Request.request [as _callback] (C:\...\gekko
\node_modules\binance\lib\rest.js:78:34)
    at self.callback (C:\...\gekko\node_modules\req
uest\request.js:186:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at ClientRequest.<anonymous> (C:\...\gekko\node
_modules\request\request.js:816:16)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at ClientRequest.emit (events.js:208:7)
    at TLSSocket.emitTimeout (_http_client.js:708:34)
    at Object.onceWrapper (events.js:313:30)
RECEIVED ERROR IN GEKKO 451813398613006
Child process has died.
(node:6204) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 1): Error: ESOCKETTIMEDOUT
(node:6204) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

`git log | head`:

commit 5e502a97d041940af24c5a3b5257c3b8d7be65f6
Author: Clifford Roche <clifford.roche@gmail.com>
Date:   Sat Feb 10 14:13:40 2018 -0500

    Fix providesHistory property for Bitfinex

commit df62ec032f6337cd3e0c5c320aef9295798ea85c
Author: Paulovms <paulovms@gmail.com>
Date:   Sat Feb 10 17:12:22 2018 -0200

**Comment by askmike** [comment]
Could you download the latest development branch version and try again?

**Comment by Red-Maximus** [comment]
I pulled and restarted. I'll have to wait for the bot to make a trade before I know.

**Comment by Red-Maximus** [comment]
Still receiving the same error.

C:\...\gekko\node_modules\binance\lib\rest.js:78
                    if (response.statusCode === 400 && payload.code === -1021 &&
                                 ^

TypeError: Cannot read property 'statusCode' of undefined
    at Request.request [as _callback] (C:\...\gekko
\node_modules\binance\lib\rest.js:78:34)
    at self.callback (C:\...\gekko\node_modules\req
uest\request.js:186:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Timeout._onTimeout (C:\...\gekko\node_module
s\request\request.js:849:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
RECEIVED ERROR IN GEKKO 23385387433787486
Child process has died.

**Comment by Daakko** [comment]
ive been using gekko for binance, no problem here. Just letting you know

**Comment by cmroche** [comment]
Try `npm install` please, to make sure your binance module is up to date.

**Comment by Red-Maximus** [comment]
Still receiving this problem. Ran `npm install`. Nothing updated.
