### ISSUE TITLE
Exchange blinktrade support

### ISSUE THREAD

**Issue by mauroprojetos** [askmike/gekko#1913]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository

* ** Action taken ** (what you did)

* ** Expected result ** (what you hoped would happen)
Need to deploy exchange blinktrade
If you have someone interested I give a reward of 0.003 BTC
Follow the API
https://www.npmjs.com/package/blinktrade
Link forum:https://forum.gekko.wizb.it/thread-1475.html

* ** Current result ** (unexpected outcome)

**Comment by askmike** [comment]
Dup of https://forum.gekko.wizb.it/thread-1475.html
