### ISSUE TITLE
How to implement my strategie

### ISSUE THREAD

**Issue by samsagat** [askmike/gekko#1914]
Hi, 

I would like to implement a multi-indicators strategie that would go like this:

Buy:
RSI: the RSI 12 was < the 35/40 bar in the last hour
BBand: crypto price chart has hit the lower band in the last hour
MACD: the trigger, upward crossover

Sell:
RSI: If the RSI 12 was > the 35/40 bar in the last hour
BBand: crypto price has hit the higher band in the last hour
MACD: the trigger, downward crossover

I was wandering if it's possible to have indicator signals to stay activated for a given period of time and to trigger the buy/sell signal when a 3rd signal occur?

And I was wondering if it's possible to put a minimum %gain before a short signal?

**Comment by samsagat** [comment]
Oups, sell is when RSI 12 > 60/65
Sorry

**Comment by samsagat** [comment]
And when I say in the last hour, it's for 5 min candlesticks, so a ration of 12/1.

**Comment by askmike** [comment]
Hey! Awesome that you want to build your own strat. Though unfortunately this is a bug tracker for the main project. Your question is better asked here: https://forum.gekko.wizb.it/forum-12.html
