### ISSUE TITLE
Know filled buy price inside a strategy

### ISSUE THREAD

**Issue by marconline** [askmike/gekko#1919]
Hello, is there any way to know, inside a custom strategy, the filled buy price - if any?

Thanks
Marco

**Comment by zappra** [comment]
Yes +1

This would be really useful.

**Comment by ianwaldrop** [comment]
I too have been looking for a way to access this information from within a strategy. it seems like something they should get from traders. you should get something like a position object encapsulating the price and volume of a position to be used for future decision making, or the current positions should be accessible somehow.
