### ISSUE TITLE
Strategy should know if it runs in backtesting or not

### ISSUE THREAD

**Issue by bennycode** [askmike/gekko#1925]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository

**Action taken**

I built a strategy which caches calculations to reuse certain parameters after restart. When running my strategy using historical data (backtesting), then my strategy doesn't work anymore because it uses cached data from the last live trade (which was not in the past, so when doing backtesting afterwards the data is not accurate anymore). To be able to reevaluate my strategy with historic data, my strategy would need to know if it runs in a backtesting environment. Is there such a flag that I could query?

**Expected result**

I would like to be able (from within a Strategy) to know if I am running in a backtesting environment or not.

**Actual result**

Backtesting environment and live trades are treated the same.

**Comment by zappra** [comment]
I think util.gekkoMode might be what you're after

**Comment by bennycode** [comment]
> I think util.gekkoMode might be what you're after

This worked like a charm! Thanks @zappra.

**Sample:**

```js
var util = require('../core/util');
var mode = util.gekkoMode();
if (mode === 'backtest') console.log('In backtesting mode.');
```
