### ISSUE TITLE
Backtesting to good to be true

### ISSUE THREAD

**Issue by josepgomes** [askmike/gekko#1926]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Run a custom strategy

* **Expected result** (what you hoped would happen)
23% profit

* **Actual result** (unexpected outcome)
166% profit

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

What i can see here is a backtesting with some type of bug. The results are to good to be true. In tradingview simulator, the profit it's only 23%. Same strategy in gekko says 166% profit.

Backtesting is working properly?

Thank you.

**Comment by GO1984** [comment]
Which strategy do you run?

**Comment by josepgomes** [comment]
I develop myself a custom strategy.

**Comment by GO1984** [comment]
You mind to share it here to see if everything is correct?

**Comment by celwell** [comment]
Lol during what time period?

**Comment by josepgomes** [comment]
From 1 January 2018 to today.

I was testing and can't find any "bug" but is a little bit strange.

My check function is pretty simple:

if (candle.close <= buyline && vrsi <= 30){
        this.advice("long");
}   
else if (candle.close >= sellline)
	this.advice("short");
}

Maybe just a good strategy?

**Comment by AS2RAL** [comment]
Backtesting provides you a best-case scenario. When you backtest and paper trade, the system assumes every trade is a success at the moment your buy/sell parameters are met.

When you live trade, it would be unlikely that every trade would be successful for various reasons -- there has to be an opposing order in the book to fill your trade, trades are made first come first serve, etc.

You might just have a sweet spot with the particular strategy you are testing against the candle interval and date range selected. I have strategies that get 250%, 500%, 2600% in certain datasets. Try your strategy against various coins, date ranges/intervals, and strategy settings to get a real idea of how good your strategy is. If the data you're testing is a primarily bullish market, try testing some data from a bearish market, you probably won't get 166%, and if you still do, congrats.

Edit: Also try setting the "Asset" in backtesting settings to 0, unless you plan on starting with some of the asset. This can throw off the results.

**Comment by Red-Maximus** [comment]
I would adjust your slippage higher. The standard 0.05 (%) is incredibly low even trading on very high volume markets. I've been doing some testing with live trading on a medium-volume market and slippage is sometimes 0% but often trades slip between 0.3% and 0.9%.

I prefer to test in "worst case scenario" mode. So, I just set my slippage to 1%. If it makes a solid profit, then I know the strategy can hold up (at least to some degree)
