### ISSUE TITLE
TradingView source code implemented in gekko

### ISSUE THREAD

**Issue by ghost** [askmike/gekko#1927]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[x ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
As of right now I watched the bot decision in TradingView and buy bitcoin manually. Is there a way to implement the source code (it's an indicator) into gekko strategy? I have a Binance account.

* **Expected result** (what you hoped would happen)
Bot book order with TradingView's strategy

* **Actual result** (unexpected outcome)
Manual book order.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by rafaeldelucena** [comment]
It's possible, but you will need to rewrite your Pine code to JavaScript :o)

**Comment by ghost** [comment]
Is there any link where I can start with? I am eager to do it.

**Comment by rafaeldelucena** [comment]
I don't think so, do you have any knowledge in Pine script or JavaScript?


I've already port some strategies to gekko, isn't complex, but you will need some extra packages for some functions.

**Comment by askmike** [comment]
Here is the documentation you need to write Gekko strats: https://gekko.wizb.it/docs/strategies/creating_a_strategy.html

Note that pine allows for drawing lines and graphs which Gekko doesn't (yet): in Gekko the only thing your strategy can do is signal to go either short or long.

**Comment by askmike** [comment]
Here is an example of a bounty where someone wants to get a pine strat converted to a gekko strat: https://forum.gekko.wizb.it/thread-92.html
