### ISSUE TITLE
Binance - Live Tradebot error

### ISSUE THREAD

**Issue by Nielswindey** [askmike/gekko#1928]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
I downloaded the latest version of Gekko. I opended CMD, and started node gekko —ui. Did al the config etc.

* **Expected result** (what you hoped would happen)
I hoped they’ll make me rich 😉 No, I hoped for a good working tradebot (live).

* **Actual result** (unexpected outcome)
When I started the tradebot, in less then 1 minute I got an error. It said:

Gekko Error
Gekko encountered an error and can’t continue. 

(In 10 hours I can post the error in CMD). 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by SilentMF** [comment]
I'm having the same issue as of 2/14/2018

```
RECEIVED ERROR IN GEKKO 925294213428716


Gekko encountered an error and can't continue


Gekko encountered an error and can't continue

Error:

[binance.js] undefined

Meta debug info:

Gekko version: v0.5.12
Nodejs version: v8.9.4
```

**Comment by Nielswindey** [comment]
Hi SilentMF,
Do you use an apple or windows pc?

**Comment by SilentMF** [comment]
I'm using Windows 10 64-bit.

I'm guessing Binance changed something with their API? The error doesn't say what is undefined in the binance.js file so I'm not sure how to determine what the exact issue is.

**Comment by SilentMF** [comment]
I dug a bit deeper and found the debug log: 

```
2018-02-15 10:08:08 (DEBUG):	[binance.js] entering "setBalance" callback after api call, err: null, data: [object Object]
2018-02-15 10:08:08 (INFO):	Attempting to BUY 0.000051665954537685867 ETH at binance price: 936
2018-02-15 10:08:08 (DEBUG):	[binance.js] (addOrder) BUY 0.00005 ETH @936 USDT
2018-02-15 10:08:08 (ERROR):	[binance.js] (addOrder) returned an irrecoverable error: undefined
2018-02-15 10:08:08 (DEBUG):	[binance.js] entering "setOrder" callback after api call, err: [binance.js] undefined data: {"code":-1013,"msg":"Filter failure: MIN_NOTIONAL"}
```

**Comment by Nielswindey** [comment]
Now, my gekko is working fine!
Also binance, windows 10...

So, what I can understand is that you get this while your tradebot is on?

**Comment by SilentMF** [comment]
Yes, this is a live tradebot. Did some research and I think the problem might be that the tradebot is trying to buy too little of the asset. In my log it tries to buy 0.00005 ETH. I found this description of the error: "price * quantity is too low to be a valid order for the symbol."

I edited the binance.js file under "Exchanges" folder and changed the minimum order to 0.001. Hoping that will fix my issue.

**Comment by Nielswindey** [comment]
I was just selling and buying manual, and I saw the minimum buying and selling is 0,01 ETH. So if it doesn’t work, I think u need to change this. If it works at 0,001 would be great too 😅

**Comment by Nielswindey** [comment]
☝️ talking about Binance, i don’t know about the other platforms ...

**Comment by difelice** [comment]
According to `Binance` documentation the minimum order should be in fact `0.001` (sauce: https://support.binance.com/hc/en-us/articles/115000594711-Trading-Rule)

I have seen the many other pairs with wrong minimum order [here].(https://github.com/askmike/gekko/blob/develop/exchanges/binance-markets.json)

I can update that file but not sure if I'm right.

**Comment by difelice** [comment]
~@cmroche I changed Binance order thresholds on my local and seems to fix this issue. I left a comment [here](https://github.com/askmike/gekko/commit/7d3acf40b5e4ef60653a5ff4bf9b36e720fe9d18).~

Update: I think that's unrelated.

I pulled latest `develop` branch and Binance works fine now.

**Comment by jmenares** [comment]
Binance - Error de Tradebot en vivo
Hola estoy iniciando en vivo y me arroja errores de base de datos...
![2018-03-04 2](https://user-images.githubusercontent.com/36050083/36946164-80703b2e-1fb0-11e8-842b-b068e4dbf3a3.png)
![2018-03-04](https://user-images.githubusercontent.com/36050083/36946166-8814a3b0-1fb0-11e8-87ee-0f1f1589d126.png)
