### ISSUE TITLE
Overlapping buy/sell orders

### ISSUE THREAD

**Issue by djmuk** [askmike/gekko#193]
I will look into it, but when I get a quick reversal (eg from up to down and back to up so gekko places a sell followed by a buy on the next candle) and the original order is not completed gekko seems to 'forget' about the original order and only track the new one - I then have to go in and manually cancel the orphaned order.  Using 1 minute candles probably doesn't help!

I think it should cancel the original rather keep tracking it and attempting to re-price it and fill it.

**Comment by askmike** [comment]
This should be fixed in the new portfoliomanager!
