### ISSUE TITLE
how to limit % of portfolio to trade

### ISSUE THREAD

**Issue by rmrezai** [askmike/gekko#1931]
how to limit % of portfolio to trade?

**Comment by JoeTeglasi** [comment]
short of having some gekko guru like @askmike doing it for you, you could create your own plugin. 
let's say you wanted to trade a certain percentage based on the deviation from an RSI above/below 70/30 respectively. you could have it listen for the buy signal and monitor the RSI and design a funciton to calculate how much percentage you want to buy/sell, and send the buy/sell signals using the api of whatever exchange you want as well as your api key info for your account on that exchange.

see plugin docs for more info

**Comment by dewulfbart** [comment]
This is more a hack than a real solution, but you can alter the code in portfoliomanager.js at line 162:
change "this.sell(amount, price);" to "this.sell(0.4*amount, price);" to only use 40% of your portfolio for example.

**Comment by ansonphong** [comment]
There is a pull request for this in the works: https://github.com/askmike/gekko/pull/1834
