### ISSUE TITLE
slack/client missing

### ISSUE THREAD

**Issue by paja93** [askmike/gekko#1932]
Hi, i have some problems with installing it on debian.

npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'slack/client' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'gekko'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.14.0-parrot2-amd64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/***myusername***/gekko
npm ERR! node -v v8.9.3
npm ERR! npm -v 1.4.21
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/***myusername***/gekko/npm-debug.log
npm ERR! not ok code 0

So i can't install dependencies, i installed them manually, but still i'm not sure what i have to do with slack/client, how to install it?
Thanks

**Comment by phood** [comment]
Ditto.. same issue installing on Raspberry Pi 3.. clean install.
 excerpt from npm-debug.log

1335 silly lockFile fbb3910a-cexio-0-0-5 cexio@0.0.5
1336 silly lockFile fbb3910a-cexio-0-0-5 cexio@0.0.5
1337 error 404 Not Found
1337 error 404
1337 error 404 'slack/client' is not in the npm registry.
1337 error 404 You should bug the author to publish it
1337 error 404 It was specified as a dependency of 'gekko'
1337 error 404
1337 error 404 Note that you can also install from a
1337 error 404 tarball, folder, or http url, or git url.
1338 error System Linux 4.9.59-v7+
1339 error command "/usr/bin/nodejs" "/usr/bin/npm" "install" "--only=production"
1340 error cwd /home/pi/gekko
1341 error node -v v4.8.2
1342 error npm -v 1.4.21
1343 error code E404
1344 verbose exit [ 1, true ]

**Comment by PastaGringo** [comment]
@phood exact same issue

**Comment by valourus** [comment]
I had this issue too. I'm not sure how I solved it..

I though I updated npm using:
npm install -g npm-check-updates

**Comment by marcoblancas** [comment]
Same here with raspberry pi 2 in a clean install.

**Comment by marcoblancas** [comment]
I have solved it installing the last LTS version nodejs  v8.11.1. https://www.w3schools.com/nodejs/nodejs_raspberrypi.asp

Maybe I didn't installed nodejs correctly.
