### ISSUE TITLE
Kraken now supports XLMUSD & XLMEUR  yet Gekko throws an error

### ISSUE THREAD

**Issue by VinceBT** [askmike/gekko#1937]
Kraken now supports again XLMUSD and XLMEUR

https://www.reddit.com/r/Stellar/comments/7y4m61/kraken_now_trading_xlm_usd/
https://api.kraken.com/0/public/AssetPairs
https://api.kraken.com/0/public/Ticker?pair=XLMUSD
https://api.kraken.com/0/public/Ticker?pair=XLMEUR

The API says that it's ok and yet the asset is not tradeable I get this error:
![image](https://user-images.githubusercontent.com/1362505/36340057-c269cee8-13d3-11e8-9757-bfc5fa5e4f47.png)

https://github.com/askmike/gekko/blob/cmroche-origin/product_updates/exchanges/kraken-markets.json

**Comment by askmike** [comment]
On your own risk (meaning we have not tested Gekko on these pairs), you can manually run the following to update Gekko:

    cd gekko/util/genMarketFiles/
    node update-kraken.js

In the next release we will have updated markets (assuming they work in our testing).
