### ISSUE TITLE
Paper trading history not working properly

### ISSUE THREAD

**Issue by BaptisteOrieux** [askmike/gekko#1938]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
I tried using my strategy or any other strategies setting a warmup period of 144 (tried also 200, 500, 1000) and 5 mins candle

* **Expected result** (what you hoped would happen)
Gekko would get 144 candles as a warmup then start strategy

* **Actual result** (unexpected outcome)
Gekko is taking way less than 144 candles as history. It was supposed to be a 12h warmup, but data spanning is never 12h, only between 1 & 3h. It never gets all the data i'm asking for. I even tried to import 1 week of data before starting paper trade, but nothing more happend.
I'm on UI. Tried MACD, RSI, and my own strategies.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
![image](https://user-images.githubusercontent.com/15614684/36340814-3f58eb2c-13e4-11e8-963f-f037de91315e.png)
![image](https://user-images.githubusercontent.com/15614684/36340819-58f9f31e-13e4-11e8-8bc5-4c85a571579a.png)

**Comment by BaptisteOrieux** [comment]
It does work using CLI, but not using UI
Maybe it's not a bug but a new feature ?

**Comment by JoeTeglasi** [comment]
as a safety feature, I've programmed my strategy to keep track of the candles and not give any advice until the minimum number of candles have actually been passed through the functions. I think that normally gekko adds the history to the indicators but might not actually pass it through your update or check functions. By hard-coding this feature, I know that I am certain it won't execute any trades until it has actually processed the minimum number of candles.

i make candleNumber a global variable = 0 at top of strat.js,
the last line of my update function is candleNumber++;
and in my check function, it starts with 

if(candlenumber>this.requiredHistory){
//do check function stuff
//figure out what to "advice"
//this.advice(advice);
} 
else {} //do nothing

I know the 'else' is unnecessary as written, i actually have other code running for that, and depending on your strat, you might too

**Comment by JoeTeglasi** [comment]
also helps to keep track of the progress of the backtest by logging the candleNumber to the console followed by a new Date() object, so I can see how long it's taking to get through however many candles (and you can do some math with the date-range you picked to figure out how many candles are in it), but maybe I'm the only impatient person here who wants to know exactly how far along my backtests are. But anyways, that's how I do it.

**Comment by BaptisteOrieux** [comment]
Thanks for this advice, but my issue is different.
If i start a papertrade at 10:10 with 1mins candle and 10 history, it'll start my strategy with candle from 10:00
If i do the same with 60 history, it'll not start with candles from 9:10 but somewhere around 10:00
If i do the same using CLI, it'll work perfecly

History seems not to matter when papertrading on UI

**Comment by askmike** [comment]
@BaptisteOrieux Gekkos tries to pump in older candle data so you don't have to wait as long. Please provide debug logs so we can see what you mean.
