### ISSUE TITLE
Gekko is running for 12 hours , no trade

### ISSUE THREAD

**Issue by feloeri** [askmike/gekko#1939]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Restarted Gekko  installed current version node and latest Gekko, followed the instruction given on the Gekko page.

* **Expected result** (what you hoped would happen)
Actual trading....

* **Actual result** (unexpected outcome)
No trades occur....
![gekko](https://user-images.githubusercontent.com/32708051/36341347-1b89ca50-13ed-11e8-9fd3-76bfaf6c719f.PNG)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
This depends on your own strategy, read this: https://gekko.wizb.it/docs/strategies/example_strategies.html
