### ISSUE TITLE
TypeError: _.get is not a function at Trader.cancel

### ISSUE THREAD

**Issue by elaarabi** [askmike/gekko#1940]
* **I'm submitting a ...**
[ x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)

Created a new live runner after child died.

* **Expected result** (what you hoped would happen)

The child restarts and continue trading !

* **Actual result** (unexpected outcome)

The runner is removed and i have to create a new one.

0|ui       | TypeError: _.get is not a function
0|ui       |     at Trader.cancel (/exchanges/binance.js:304:12)
0|ui       |     at bound (/node_modules/lodash/dist/lodash.js:729:21)
0|ui       |     at /core/util.js:28:7
0|ui       |     at /exchanges/binance.js:75:12
0|ui       |     at Request.request [as _callback] (/node_modules/binance/lib/rest.js:90:25)
0|ui       |     at Request.self.callback (/node_modules/request/request.js:186:22)
0|ui       |     at emitTwo (events.js:126:13)
0|ui       |     at Request.emit (events.js:214:7)
0|ui       |     at Request.<anonymous> (/node_modules/request/request.js:1163:10)
0|ui       |     at emitOne (events.js:116:13)
0|ui       | RECEIVED ERROR IN GEKKO 732782279988403
0|ui       | Child process has died.

**Comment by askmike** [comment]
This is fixed in the latest develop version, please use that one! I will push out a new release asap.
