### ISSUE TITLE
Binance live tradebot not working

### ISSUE THREAD

**Issue by dwarda** [askmike/gekko#1941]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
I started Binance live tradebot today trading BTC/TRX

* **Expected result** (what you hoped would happen)
Start trading as it usually does

* **Actual result** (unexpected outcome)
-Was running for few hours and didn't start trading. 
-The watcher was displaying incorrect duration and start time.
-strat runner did not display any information.
-Market Graph displayed was for 8 min only
-everytime i start live tradebot it gives me the same start time and duration (which are not correct) and the same graph.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
I have been using gekko without any problem. this happened today and since then I am not able fix it. i tried reinstalling it again and the same issue is happening. and here are some screenshot of what is happening. 
Thank you in advance 

<img width="992" alt="screen shot 2018-02-18 at 2 06 59 am" src="https://user-images.githubusercontent.com/35301016/36349290-1f029784-1451-11e8-81a5-b902a5618539.png">
<img width="769" alt="screen shot 2018-02-18 at 2 07 21 am" src="https://user-images.githubusercontent.com/35301016/36349291-214b7fc4-1451-11e8-9e15-e60ff4af69e0.png">
<img width="1279" alt="screen shot 2018-02-18 at 2 07 36 am" src="https://user-images.githubusercontent.com/35301016/36349292-2309271c-1451-11e8-87cc-ee867244a9df.png">
<img width="1276" alt="screen shot 2018-02-18 at 2 07 51 am" src="https://user-images.githubusercontent.com/35301016/36349293-2822eaa8-1451-11e8-8c67-13d8b8226ac2.png">
[2018-02-18-07-06-UTC-tradebot.log](https://github.com/askmike/gekko/files/1734498/2018-02-18-07-06-UTC-tradebot.log)
[2018-02-18-07-06-UTC-watcher.log](https://github.com/askmike/gekko/files/1734499/2018-02-18-07-06-UTC-watcher.log)

**Comment by ansonphong** [comment]
I've had this issue only with the BTC/TRX pair, it is not working properly since 13:05 last night, I think the issue is on the Binance API side, and unrelated to Gekko.

**Comment by dwarda** [comment]
@ansonphong thank you for your reply. 
so, there is nothing to be done at the moment to fix this?

**Comment by microoxi** [comment]
I have similar problem with BNB/LTC pair. The date of received data until is also similar- 2018-02-17 13:03. If you have this problem i see too, then i think possible is a  binance side. Sorry for my English.

**Comment by microoxi** [comment]
I have this problem parallel on 3 independent computers. Same date, same hour.

**Comment by Red-Maximus** [comment]
I'm having the same issue and when it tries to make a trade the child process dies. (#1910)

**Comment by ghost** [comment]
ETH ICX same thing

**Comment by microoxi** [comment]
Now It seems to be ok with bnb/ltc. Check this guys.
