### ISSUE TITLE
Discrepancies between gekkos backtest and other tool

### ISSUE THREAD

**Issue by goldistan** [askmike/gekko#1943]
First of all, a lot of respect for all the work you've put into this project.
I've played around with Gekko and run backtests in parallel to which trades should occur in different scenarios on different strategies. It seems like Gekko isn't preforming the same trades as one would expect to occur for the built in strategies.

Here's an example of a RSI strategy with the same parameters -  

![real-rsi](https://user-images.githubusercontent.com/10022117/36354577-740b9fe8-148b-11e8-90be-90eebd35dc5a.png)

Here's what Gekko did - 
![fakel-rsi](https://user-images.githubusercontent.com/10022117/36354582-7bf81470-148b-11e8-8b7b-8eacb48f654d.jpg)

Using RSI there should have been around ~8 trades, not a hundred. 

Could it be that I'm missing something ?

**Comment by ansonphong** [comment]
Top image is RSI 14 on daily candles, is Gekko set to the same settings?

**Comment by askmike** [comment]
Gekko's daily candles don't start at midnight (what midnight? UTC, EST?). There are a number of different reasons why the final output is different, the first one being that Gekko calculates different candles, the second one being that the RSI strategy does a few things more than check wether the RSI result crosses a threshold (it needs to persist, etc).

> Here's an example of a RSI strategy with the same parameters -

That's not an RSI strategy, that's a plot of the calculated indicator.

---

We're going to need more data to figure out why this is happening, we can start by forcing Gekko to calculate the exact same candles as depicted in the chart.

**Comment by goldistan** [comment]
Askmike, you brought up some good points.
I was comparing apples to oranges, i.e - not the same candlesticks. Moreover, I looked into the strategy code and indeed it checks for signal strength (this.trend.duration >= this.settings.persistence).
I didn't update the start time, but for now let's assume it's not the root cause for the discrepancies in this year long backtest. The new graph does resemble a lot more to what I would expect. (both daily / rs14, 30/70 and persistence is 1)

![d1](https://user-images.githubusercontent.com/10022117/36362120-95c707a2-14e6-11e8-988f-f6d33061ece9.jpg)

![d2](https://user-images.githubusercontent.com/10022117/36362121-9869f5dc-14e6-11e8-86be-1a7ab0ab2533.jpg)

Nevertheless, between May and June and again Dec to Feb there were two very strong spikes that indicate BTC was overbought and the RSI should have promoted a PUT. However, this is not the case.
Thanks for your reply btw.

**Comment by askmike** [comment]
You can run the backtest over the commandline with some debug information enabled (you might have to add that in the strategy), this way you can compare raw RSI values from both Gekko and the other tool you are using.

Unfortunately simply comparing the charts visually won't get us to why there is a discrepancy.

**Comment by askmike** [comment]
I don't know what results you are getting now? Is it hundreds of trades or one trade?

One other thing: Are you sure the other tool is calculating RSI over the price and not over the volume?

**Comment by goldistan** [comment]
Yes, it's now doing the one trade (screenshot above), which is closer than before.
I'll compare the logs and keep you posted. It would be probably better to compare a few hours vs a year.
Also, It would be really helpful if Gekko shows the RSI graph which I already saw that is in development
[draw indicator results in the U](https://github.com/askmike/gekko/pull/793).

Were you able to cross reference Gekko's built-in strategies with any third party site and see if they match ? (minus the persistence)

**Comment by askmike** [comment]
Gekko allows you to use two external libraries that calculate indicators. TA-lib is well tested and an industry standard, that library is also used in the sofware projects EclipseTrader, JForex and NexTick. Alternatively there is also a newer but well documented and tested library called Tulip indicators, see here: https://tulipindicators.org/

Though the RSI indicator used by the RSI strategy is written for Gekko specifically, the result values are tested and compared with those of another library, see here for details: https://github.com/askmike/gekko/blob/develop/test/indicators/rsi.js

----

Can I request we move this to the forum? That's a better place to figure out where the discrepancies come by slowly debugging different numbers and comparing them to other tools. Only if we know exactly what is different AND it's a big and not the result of a different implementation wen can call it a bug pursue it further.

**Comment by goldistan** [comment]
Sounds good, thanks Askmike.
