### ISSUE TITLE
Unable to set up tradebot in Kraken 

### ISSUE THREAD

**Issue by lazywhale** [askmike/gekko#1947]
I have set up gekko in kraken with all the permissions on my API key for trading. However everytime i Run the tradebot i get the below : 

Error:

[kraken.js] General:Permission denied

Paper trader is working fine. I have entered the API + Secred key in the web tab at http://localhost:3000 so I thought that would be sufficient 

Not a developer so im not sure whether I should configure the .js file in the folder. Please help

**Comment by dablat** [comment]
Hello,

I have the same issue, did you solve your problem ?

Thank you.

**Comment by dablat** [comment]
Hello,

Solution is to add "query funds" in the Api key options.
