### ISSUE TITLE
BB strategy 

### ISSUE THREAD

**Issue by mohdalsaqqal** [askmike/gekko#1949]
i using this strategy and its always work
using the BB indicator , LTC\USTD , 1 min chart .
i choose the last price that the candle touch the lower BB line , and open buy order and wait the price to come down to it , then when the buy already done , i see where BB upper line where and open sell order and wait while the price go up .

your method work as soon as the candle hit the upprBB you will sell , but sometimes the candle hit the upperBB with lower price than the buying price . so you have to compare prices ,

so the code have to check when the price hit the lower bb line to buy , then save the upper bb band on that point , then when the if ( price = upper bb for the previous buying price) { sell ; } 
im sorry about my bad english .

this strategy always work for me , the problem is i dont know how to automate it .
![untitled](https://user-images.githubusercontent.com/31498794/36404162-db4bb226-15f1-11e8-83b3-03e9e093b724.png)

* **Expected result** (what you hoped would happen)

* **Actual result** (unexpected outcome)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by rEVOLV3r** [comment]
Hello,

I already used only BB strategy and the outcomes can be great if the btc was not so volatile.
If you use BB to buy, when the dump comes, you will buy very, very, very high. 
Trust me, that was my first mistake when in my beginings.
However, BB is great to trigger another stragegy if your threshold is reached like -10/25% of low BB. 
You can play with the variance too if you want to trigger it less.

Personnaly i mixed MACD indicators with BB and other indicators to be sure not to buy when i'm not sure that will come up.

You can find the BB strategy in the Pull Request. Somebody had already coded it for us.

Bye

**Comment by mohdalsaqqal** [comment]
thank you for the advice , as u said im beginner , i will be thankful if you help me to develop good bot

**Comment by askmike** [comment]
great stuff! Would you mind posting this in the forum instead? Thanks! 

https://forum.gekko.wizb.it/

**Comment by gubo8** [comment]
I think I can help. Do you still need it? Contact me at gubo.crypto@gmail.com
