### ISSUE TITLE
Fetch time slips - results in 2 candles generated simultaneously

### ISSUE THREAD

**Issue by djmuk** [askmike/gekko#195]
At least on my system the candle fetch / process / method loop takes just over 60 seconds (around 62), this means that the candle fetch time slips by 2 seconds a minute.
So what?
This means that every so often the process generates 2 consecutive candles simultaneously, as I am acting on 1 minute candles this can result in a significant delay in placing orders - Just now I had a fetch at 12:40:58 - so this generated the candle for 12:39, fetch at 12:42:00 which generated the candle for 12:40 and then a fetch at 12:43:02 which generated the candles for both 12:41 and 12:42...
Can we make the candle fetch interval <60 seconds (say around 50 secs) - if it is a prime number would it spread the fetches more evenly - how about 53?

**Comment by askmike** [comment]
this is fixed!
