### ISSUE TITLE
Postgresql reader.js is outdated.

### ISSUE THREAD

**Issue by kevinxh** [askmike/gekko#1950]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[x] question about the decisions made in the repository

* **Action taken** (what you did)
Clone the repo, spin up my own server, use postgresql as my db.

Import data ok, issue happens when i try to scan data.

* **Expected result** (what you hoped would happen)
Reader scans db.

* **Actual result** (unexpected outcome)
Reader returns no result from db, even thou I have successfully imported data.

Because `query.on` is deprecated in pg v7, the reader will not work.
Read [deprecation guide](https://node-postgres.com/guides/upgrading#client-query-on).

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

### Please advise people to use pg v6 or update reader so people don't run into the same issue.
I want to make a PR but I have never worked with postgresql nor pg, thus help needed.

**Comment by askmike** [comment]
Thanks for bringing this issue up! Rewriting Postgresql integration is actually pretty high on my list.

Gekko should have prompted you to install pg@6.1.0 which should work relatively stable. That is the only thing I can recommand for now:

    npm remove pg
    npm install pg@6.1.0
