### ISSUE TITLE
Tradebot “forbidden” on Gdax

### ISSUE THREAD

**Issue by JoeTeglasi** [askmike/gekko#1951]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Tried to use a Tradebot on gdax using my api key info

* **Expected result** (what you hoped would happen)
Trades would be submitted to gdax and I would make some money

* **Actual result** (unexpected outcome)
No trades were submitted, got an error in the UI: “Gekko can’t continue”

And in the console it said “[Gdax.js] forbidden”

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by difelice** [comment]
Looks like you're not authorized to access the account via API.

Make sure to check `View`, `Trade` and `Manage` options, and don't forget to provide: `Key`, `Secret` and `Passphrase`.

If you whitelisted an IP address when creating the API info, check if it hasn't changed since then.

**Comment by JoeTeglasi** [comment]
I did that, and now it has a new error: 

"[gdax.js] The header content contains invalid characters"

this is definitelt a bug, because I had it log the (config) that was being passed to gdax.js, and it had spaces (" ") put before my api key and secret. 

I triedto fix by inserting the following code into gdax.js:
while(this.key[0]==" "){
      this.key = this.key.slice(1);
    }
    while(this.secret[0]==" "){
      this.secret = this.secret.slice(1);
    }
    while(this.passphrase[0]==" "){
      this.passphrase = this.passphrase.slice(1);
    }

...but it still did not fix the problem, as i am still getting the error about invalid chars. please help!

**Comment by askmike** [comment]
when you copy the api key and secret make sure there are no trailing spaces or any other symbols not part of the key/secret.

**Comment by ptbosean** [comment]
I can report that GDAX trading is working for me via command line.

**Comment by JoeTeglasi** [comment]
I haven’t set up the Gekko CLI, I was just using the UI, and there were definitely no trailing characters, unless the “==“ at the end of the secret counts as trailing, but I’ve always thought those were part of the secret. The secret should be verbatim what gdax posted when I made the api key right? Cuz that’s what I did and it’s still giving me the error. I will try setting up the CLI and try it from there when I get a chance

**Comment by JoeTeglasi** [comment]
Same error using CLI, the error was returned when it tried to (getPortfolio). The api key was def typed correctly (it was copied and pasted, so really not a lot of room for error), and it had all the permissions except “transfer”.

**Comment by JoeTeglasi** [comment]
I wrote a short script using the gdax npm package to try to find out where the issue is, and I got the same error directly from gdax. I’m going to try to contact their support to find out why it’s not working. In the past I’ve used the same code (albeit with a different api key) and it worked fine to set trades

**Comment by askmike** [comment]
Yea Gekko isn't doing anything special with the key and secret, when it works with the gdax npm package it will work with Gekko to. I hope you get it resolved soon, you can also just try to create a new key (with the same priveleges) and see if that one works!
