### ISSUE TITLE
Disconnected error: Basic authentication on Nginx blocks web socket.

### ISSUE THREAD

**Issue by halilkaya** [askmike/gekko#1952]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
My whole configuration is exactly the same as in https://gekko.wizb.it/docs/installation/installing_gekko_on_a_server.html. I have enabled basic authentication.

* **Expected result** (what you hoped would happen)
It must be working on all desktop and mobile browsers.

* **Actual result** (unexpected outcome)
When I open my app on Chrome and Firefox on **desktop**, it works. But, when I try to open on Safari on desktop and Chrome/Safari on **mobile**, it doesn't work.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
When I comment out basic authentication on my Nginx configuration, it works on all environments correctly.

I have also tried following change that @nibarulabs said from https://github.com/askmike/gekko/issues/698

> I even went into the ./web/vue/src/tools/api.js file and made the following changes:
>
> // ws API path
> if(config.ssl) {
>   var wsPath = `wss://username:basicauthpass@{host}`;
> } else {
>   var wsPath = `ws://username:basicauthpass@${host}`;
> }

However, it didn't work, too.

**Comment by askmike** [comment]
Can you be a little bit more specific than:

> it doesn't work.

Do you get an error? Which one? If not what else? etc.

**Comment by halilkaya** [comment]
It doesn't give an error on logs. It just opens a popup with:

**Disconnected**
Something happened to either Gekko or the connection. Please check the terminal where Gekko is running or your network connection.

**Comment by askmike** [comment]
can you open the chrome dev tools, go to the console tab and post a
screenshot of that here?

EDIT:

I now see this problem is only seen on mobile, unfortunately I have no way to debug or give support for this. I don't have any smartphone that has a safari browser unfortunately. For now mobile is not supported I am afraid :(
