### ISSUE TITLE
binance amount too small

### ISSUE THREAD

**Issue by Erasss** [askmike/gekko#1955]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Tradebot SELL'ing neo.

* **Expected result** (what you hoped would happen)
to sell neo:
2018-02-19 06:18:37 (DEBUG):    ------**SELL**-------
2018-02-19 06:18:37 (INFO):     Trader Received advice to go short. **Selling  NEO**
....
2018-02-19 06:18:40 (DEBUG):    [binance.js] entering "setBalance" callback after api call, err: null, data: [object Object]
2018-02-19 06:18:40 (INFO):     **Attempting to SELL 0.15 NEO** at binance price: 0.138263
2018-02-19 06:18:40 (DEBUG):    [binance.js] (addOrder) SELL 0.15 NEO @0.138263 ETH

* **Actual result** (unexpected outcome)
why bot on selling neo, says that he want to buy **2018-02-21 14:08:25 (WARN):     Wanted to buy ETH** ?
--------------
2018-02-21 14:08:22 (DEBUG):    ------SELL-------
2018-02-21 14:08:22 (INFO):     Trader Received advice to go short. Selling  NEO
..
2018-02-21 14:08:25 (DEBUG):    [binance.js] entering "setBalance" callback after api call, err: null, data: [object Object]
2018-02-21 14:08:25 (WARN):     **Wanted to buy ETH but the amount is too small**  (0.14077000 @ 0.14195100 ) at binance

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by Shrike998** [comment]
Correct me if im worng here.. but could this be due to Binance trade rules?

https://support.binance.com/hc/en-us/articles/115000594711-Trading-Rule

If you wernt trading with enough balence then you may get that error.

Also if you are trading NEO with ETH and you sell NEO then you are buying ETH.. for NEO

**Comment by Erasss** [comment]
I used android application and i sell the neo, maybe problem that bot want to sell 0.14077000 too many parameters after dot.

**Comment by Erasss** [comment]
With Jason config it must be 0.14

**Comment by Shrike998** [comment]
Did you sell via market order or limit? Gekko will be using limit by default unless you have chaged that in your strat, and in that case the minimum trade rules will apply, however when using market order you are able to sell less than binance trade rules:

```
NO  | Pair    | Min Amount | Unit | Min Price   | Unit | Min Order Value | Unit    
19  | NEO/ETH | 0.01       | NEO  | 0.00000001  | ETH  | 0.01            | ETH
```
Also check the min order size in the binance-markets.Json - as mine is set to min order 0.02 by default

      "pair": [
        "ETH",
        "NEO"
      ],
      "minimalOrder": {
        "amount": 0.01,
        "price": 0.000001,
        "order": 0.02

It should be 0.01 according to binance website.

Hope that helps

**Comment by Erasss** [comment]
From android application i sell via limit order (one time used market limit, maybe from that i have strange balance **neo 0.14077000**), app showed to sell 0.14 . In Gekko jason files not changed
      "pair": [
        "ETH",
        "NEO"
      ],
      "minimalOrder": {
        "amount": 0.01,
        "price": 0.000001,
        "order": 0.02
      }

 I found in https://gekko.wizb.it/docs/introduction/scope.html#Strategies, tradebot try to sell all NEO, and then error aper from binance:
> _When you are using Gekko for a real tradebot Gekko will create orders at the exchange whenever your strategy signials an advice (long or short). If your strategy signal a long advice Gekko will try to buy as much **"asset" as it can get with all your "currency"**_

**Comment by Shrike998** [comment]
Try changing your Json file to:

>   "pair": [
>     "ETH",
>     "NEO"
>   ],
>   "minimalOrder": {
>     "amount": 0.01,
>     "price": 0.000001,
>     "order": 0.01

and see if that helps.

**Comment by Erasss** [comment]
Ok, i will try, and reply. Thanks
all rules from binance
https://support.binance.com/hc/en-us/articles/115000594711-Trading-Rule

**Comment by Erasss** [comment]
Now works well. Thanks
