### ISSUE TITLE
NaN result using StochRSI and 5 min candel size

### ISSUE THREAD

**Issue by Shrike998** [askmike/gekko#1956]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report

* **Action taken**
Setup config.js to run a livetrading bot on binance ETH/FUEL with a 5 min candel size using the StochRSI strat

* **Expected result** (what you hoped would happen)

The tradebotlog file would show a result when calculating the RSI similar to this:

> 
> 2018-02-21 14:52:41 (DEBUG):	calculated StochRSI properties for candle:
> 2018-02-21 14:52:41 (DEBUG):		 rsi: 72.72727273
> 2018-02-21 14:52:41 (DEBUG):	StochRSI min:		0.00000000
> 2018-02-21 14:52:41 (DEBUG):	StochRSI max:		72.72727273
> 2018-02-21 14:52:41 (DEBUG):	StochRSI Value:		100.00
> 2018-02-21 14:52:41 (DEBUG):	In high since 1 candle(s)
> 

* **Actual result** (unexpected outcome)

> 
> 2018-02-21 16:24:02 (DEBUG):	calculated StochRSI properties for candle:
> 2018-02-21 16:24:02 (DEBUG):		 rsi: 0.00000000
> 2018-02-21 16:24:02 (DEBUG):	StochRSI min:		0.00000000
> 2018-02-21 16:24:02 (DEBUG):	StochRSI max:		0.00000000
> 2018-02-21 16:24:02 (DEBUG):	StochRSI Value:		NaN
> 2018-02-21 16:24:02 (DEBUG):	In no trend

The issue only seems to happen when I change the candel size in config.js to 5, on 1 it is fine.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Is this normal or have I edited a file wrong?

**Comment by askmike** [comment]
Does this persist for many candles? The RSI is only populated after n candles, where n is the period you configure your RSI with. In that case please set a higher requiredHistory (called warmup in the UI).

If that is not your problem pleas reopen :)
