### ISSUE TITLE
Error when live trading on binance

### ISSUE THREAD

**Issue by zzmike76** [askmike/gekko#1959]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Trading live on binance

* **Expected result** (what you hoped would happen)
trading working properly

* **Actual result** (unexpected outcome)
getting error with all trading pairs
[binance.js] (getTrades) returned an error, retrying: Error: getaddrinfo ENOTFOUND api.binance.com api.binance.com:443

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by funSoftwareProjects** [comment]
Did you ever find a solution? I'm having that same message with Kraken right now.

**Comment by askmike** [comment]
@aramsichord 

> Error: getaddrinfo ENOTFOUND 

Is a DNS issue, make sure your internet connection is good, make sure your DNS servers are working fine, etc. It's not a Gekko issue and this will most likely impact other stuff running on that same machine.

**Comment by funSoftwareProjects** [comment]
Thank you!
