### ISSUE TITLE
documentation needed to write strategies more easily

### ISSUE THREAD

**Issue by scidran** [askmike/gekko#1960]
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository

* **Action taken**
I'm learning how to write strategies and I become able to write simple strategies also with two indicator.
But I wasn't able to find some info about gekko ability into documentation and also into issues. 

* **Expected result**
I had understand what every function of strategies do and when every one is called:
- strat.init - to set up datas for strategies executed on startup only one time
- strat.update - used to update indicator datas and executed every new candle
- strat.check - used to put a logic about buy and sell actions and executed every new candle
- strat.log - used to log datas about result into console and executed every new candle.
I also understand that to buy and sell there is a function called this.advice('long') and this.advice('short').
I saw that into talib and tulip documentation there is a list of input parameter to set using up via .toml file info config didectory.

* **Actual result** (unexpected outcome)
I have some question:
I saw that into some strats example's, the update logic and the buying and selling logic are written into check function. Are this only a notation conjecture?

And there is a function or a way to set a buy order at a specific price and verify into the next candle if it was executed? So, if it wasn't executed, I can cancel the first order and place an other one at a different price.

I haven't found a documentation about how to write and read correctly the .toml file into config/strategies directory. I have understood only by looking example. So if i have a lot of indicator to set, i must use different [parameter...] section to identify the right one for an indicator. A few of documentation will be appreciated.

Into documentation about talib and tulip, there is only the input parameter needed explained. Maybe I'm not so able with javascript to understand... but without the output parameter name, I'm not able to ave some datas from some indicator.
The same thing also for sell orders.
I understood that 'this.tulipIndicators.mystrat.result.result' work with indicator that have only an output result. but with other kind of indicator. If i use 'this.tulipIndicators.mystrat.result' with indicator that have more that one output, into console log i have an '[object] result and i can't access the data.
For example with 'fisher' indicator into tulip, use 'this.tulipIndicators.mystrat.result.fisher and an other output that i'm not able to get. I deduced it from the official documentation of tulip lib (https://tulipindicators.org/fisher). Also MACD have more than one output but with the example strat i was able to obtain them.

* **Other information**
It would be appreciate to understand also the structure of the file that gekko uses to do the various things.
For example, I would try to write a function to display a output graph of indicators (I know that it was a work in progress but maybe i can help into some way) ... but I'm not able understand where I must watch to find the right file.
The same thing to manage portfolio into my exchange (an other work in progress).

**Comment by JoeTeglasi** [comment]
you Can always check where the result is by using 

console.log(JSON.stringify(this.indicators.myTulipIndicator));

It will print to console the indicator and you can see where the result is, and whether it’s under “result”, “result.result”, “result.foobar”, etc. then you can just use that info to access it
