### ISSUE TITLE
Console output could use some COLOR!🌈

### ISSUE THREAD

**Issue by JoeTeglasi** [askmike/gekko#1964]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
There whole console output is just basic white on Black 

* **Expected result** (what you hoped would happen)
It would be so nice if there was a color-coded system of output for things like “errors”, “buy/sell orders”, “general log info”, and if there was color-code support for people writing their own strategies to color-code whatever they log to the console too. 

* **Actual result** (unexpected outcome)
no color in current version

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

there’s a really neat npm package called “colors” that would make adding color really easy. I use it in my own strat, and it makes the output look snazzy and highly readable. It has a solid variety of colors to choose from, and also supports changing the background color of text (which has a highlighting sort of effect).

It has two “modes”: if you use require(“colors”) then it modifies the string prototype so that you can write things like log(“I want this to be red”.red); and it comes out red. Log(“there was a trade at this price”.cyan) comes out cyan. 

And then there’s “safe mode”, accessed via var colors = require(“colors/safe”) which *doesn’t* modify the string prototype and can be used like log(colors.red(“this string will be red”));

I’d be willing to work on this with someone/s with solid experience with GitHub and pull requests and such. I haven’t ever worked on a GitHub project before, but I really like and appreciate Gekko and would like to contribute to the project.

**Comment by askmike** [comment]
It wouldn't be that hard, this is the file that processes everything that gets logged to stdout (in console): https://github.com/askmike/gekko/blob/develop/core/log.js

Note that this functionality should be behind a config flag (not enabled on default) as a lot of people don't read the logs in the console but inside pipe them into a log file (for example by running `node gekko -c config.js > gekko-log.txt`). Unless there is no effect on the text if it is written to disk (not to sure).

**Comment by JoeTeglasi** [comment]
I tested it and there is a major affect on the text if its written anywhere but the console, so it def will need to be in the config. Which config file does the UI use (for paper/live trading and for backtesting)? I know in the CLI you specify the config, so it would be easy to add a line like:

`config.useColors=false //set to true only if logging only to console and NOT to disc/txt file`

also, I added it to the log file here: (it wouldn't let me upload the .js file so I just copied and pasted)

```
/*

  Lightweight logger, print everything that is send to error, warn
  and messages to stdout (the terminal). If config.debug is set in config
  also print out everything send to debug.

*/

var moment = require('moment');
var fmt = require('util').format;
var _ = require('lodash');
var util = require('./util');
var colors = require('colors');
var config = util.getConfig();
var debug = config.debug;
var silent = config.silent;

var sendToParent = function() {
  var send = method => (...args) => {
    process.send({'log': args.join(' ')});
  }

  return {
    error: send('error'),
    warn: send('warn'),
    info: send('info'),
    write: send('write')
  }
}

var Log = function() {
  _.bindAll(this);
  this.env = util.gekkoEnv();

  if(this.env === 'standalone'){
    this.output = console;
  }
  else if(this.env === 'child-process')
    this.output = sendToParent();
};

Log.prototype = {
  _write: function(method, args, name) {
    if(!name)
      name = method.toUpperCase();

    var message = moment().format('YYYY-MM-DD HH:mm:ss');
    message += ' (' + name + '):\t';
    message += fmt.apply(null, args);
    
    if (config.useColors) {
      var color;
        switch(method){
          case 'error': 
          color = 'red';
          break;
          case 'warn':
          color = 'yellow';
          break;
          case 'debug':
          color = 'cyan'; //or magenta? or orange?
          break;
          case 'info':
          color = 'white';
          break;
        }
      message = message[color];
  }
    this.output[method](message);
  },
  error: function() {
    this._write('error', arguments);
  },
  warn: function() {
    this._write('warn', arguments);
  },
  info: function() {
    this._write('info', arguments);
  },
  write: function() {
    var args = _.toArray(arguments);
    var message = fmt.apply(null, args);
    this.output.info(message);
  }
}

if(debug)
  Log.prototype.debug = function() {
    this._write('info', arguments, 'DEBUG');  
  }
else
  Log.prototype.debug = _.noop;

if(silent) {
  Log.prototype.debug = _.noop;
  Log.prototype.info = _.noop;
  Log.prototype.warn = _.noop;
  Log.prototype.error = _.noop;
  Log.prototype.write = _.noop;
}

module.exports = new Log;
```

The colors npm package would also need to be added to the node-modules folder right?

**Comment by askmike** [comment]
Looks like a good start.

> The colors npm package would also need to be added to the node-modules folder right?

It won't be a default plugin, so only people who want to enable it need to install it manually. Usually this situation occurs with plugins, in which case Gekko has a way to prompt the user to install the package on the plugin/feature is enabled. That should be done here as well.

> `var colors = require('colors');`

According to the color docs this extends the string prototype, which I really don't think we should do.

----

If you want to post more code please put it in a gist and link to it instead, this is not really readable.

**Comment by JoeTeglasi** [comment]
[log.js as a gist](https://gist.github.com/JThobbyist/f96f366a49065d80a62d9cb4fe8bc37e)

**Comment by askmike** [comment]
I'm open to a PR for this :)
