### ISSUE TITLE
Volume Weighted Moving Average Indicator

### ISSUE THREAD

**Issue by GitNitneroc** [askmike/gekko#1975]
Hi, this is not an issue, but I can't fill a pull request atm.
I found myself needing vwma. Here's my implementation, in case anyone is interested.
```
// Volume Weighted Moving Average

var Indicator = function(windowLength) {
    this.input = 'candle';
    this.windowLength = windowLength;
    this.prices = [];
    this.volumes = [];
    this.result = 0;
    this.age = 0;
    this.getId = function(id){
        return (this.age + id )%this.windowLength;
    };
};

Indicator.prototype.update = function(candle) {
    this.prices[this.age] = candle.close;
    this.volumes[this.age] = candle.volume;
    let pricesSum = 0;
    let volumesSum = 0;
    for (let i = 0; i < this.windowLength; i++){
        let id = this.getId(i);
        pricesSum += this.prices[id]*this.volumes[id];
        volumesSum += this.volumes[id];
    }
    this.result = pricesSum/volumesSum;
    this.age = (this.age + 1) % this.windowLength;
};

module.exports = Indicator;
```

**Comment by askmike** [comment]
Hey! instead of the close property you can also use the `vwp` property of the candle. This the vwp price inside every candle. Wouldn't that be a closer representation of vwma?

Another thing: this currently memory leaks since the volumes and price array will always grow without limit.

**Comment by askmike** [comment]
If anyone else wants to turn this (including fixing the nits above) into a PR be my guest :)

**Comment by GitNitneroc** [comment]
You're right about vwp! But this shouldn't leak memory unless I overlooked something...

**Comment by askmike** [comment]
Ah now I see, you are rewriting elements in the existing array, neat!

**Comment by GitNitneroc** [comment]
It's actually reusing your code from other indicators :)

2018-02-28 8:43 GMT+01:00 Mike van Rossum <notifications@github.com>:

**Comment by askmike** [comment]
Cool, that code is at least 4 years old so and my memory is a bit rusty haha.
