### ISSUE TITLE
History data when live trading

### ISSUE THREAD

**Issue by sky9662** [askmike/gekko#1978]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository

I have done a lot of backtest and trying few strategy live recently, one of the best strategies I have tried is RSI_BULL_BEAR_ADX on the forum, in the default setting this strategy uses 1000 candles to calculate long term MA, in this case, if candle size set to 6 mins then it takes around 6000 mins(100 hours) to make the long-term MA calculated properly, I'm thinking since Gekko has the ability to get historical data from exchange, is it possible Gekko can get the warm up data it needs before the time it start live trading?

Sometimes server or network die randomly, it's very long time to wait until it finishes warm up again!
Thanks!

**Comment by donkykong017** [comment]
i am wondering about the same thing. i fetched the backtest data for the given pair i want to livetrade later on but it did not use it. just the data from a marketwatcher.
also when you update gekko or the strat parameters it would be very convenient. i use 15 min candles this takes 1.5 weeks

**Comment by askmike** [comment]
If you use the commandline interface Gekko will stitch the data from local and exchange data. Meaning if you require a 1000 candles and you have them locally Gekko will start your strat right away.

This will be supported in the UI as well in the next major UI release.

closing as dup of #1744.

**Comment by sky9662** [comment]
That's good to know, I'll learn to use CLI and looking forward to the next version of UI comes out :) 
Thanks!
