### ISSUE TITLE
gdax false minimum trade amount

### ISSUE THREAD

**Issue by xerviami** [askmike/gekko#1979]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Launch a tradebot on btc/eur/gdax

* **Expected result** (what you hoped would happen)
Buy and sell BTCs according to my strategy

* **Actual result** (unexpected outcome)
"2018-02-28 02:06:37 (INFO):	Trader Received advice to go long. Buying  BTC
2018-02-28 02:06:37 (ERROR):	Wanted to buy BTC but the amount is too small (0.003015963807) at GDAX"
It considers 0.003 too small wheras gdax has a 0.001 BTC minimum trade rule.
cf. https://support.gdax.com/customer/en/portal/articles/2426595-gdax-limits-for-deposits-withdrawals-trades-and-balances

In order to test the 0.001BTC rule, I tried to place on gdax website an order to buy 0.003BTC an it accepted the order (I did not wait for the site to fill the order)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Thank you in advance !:-)
Xavier

**Comment by askmike** [comment]
Thanks for the report, I've fixed this now :)

You need to download the latest development build in order to have access to the fix until I do a new release.

**Comment by H256** [comment]
Same problem exists on Bitstamp exchange - I don't know the exact limits for USD but an order must have at least a value of 5.00 € (US$ is probably the same)

**Comment by askmike** [comment]
@H256 ah yes, Gekko recently started supporting the lot calculations required to figure out whether this is the case. Though they are not implemented for bitstamp yet.

Mind opening a new issue so that we can track it? Thanks!
