### ISSUE TITLE
How to query to get the last filled Buy price

### ISSUE THREAD

**Issue by jaguar666** [askmike/gekko#1983]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[X] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)

* **Expected result** (what you hoped would happen)
I need a query code to get the last filled "BUY" price which to be added in portfolioManager as an option for my "SELL" strategy (sell when it reach the desired profit).

* **Actual result** (unexpected outcome)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by JoeTeglasi** [comment]
Go to plugins/trader/portfoliomanager.js

You’ll find the value of the buy/sell price there, and you can set a property of the portfoliomanager as this.lastTradePrice = [the buy/sell price]

Then you can access that value by using event listeners to relay it to your strategy (I’m not sure of all the steps, but it would go something like trader.js => ? => tradingAdviser.js => your strategy ( accessed via this.method in TradingAdviser)
