### ISSUE TITLE
Pause and resume import

### ISSUE THREAD

**Issue by rclai** [askmike/gekko#1990]
Is it possible to pause and resume data import? Or will it just get screwed up if I stop the instance?

**Comment by rclai** [comment]
Never mind, the gdax import isn't so bad after all, I'm 23% done importing 1 year's worth of data.

**Comment by IAMtheIAM** [comment]
Can you reopen this issue? @rclai I would like the pause and resume feature as well. But I am unfamiliar with how the data is being stored. Can anyone chime in?

**Comment by eugenius1** [comment]
@IAMtheIAM yes I would also like to know how to pause or cancel an import
