### ISSUE TITLE
error: getTrades() returned duplicate results

### ISSUE THREAD

**Issue by grigio** [askmike/gekko#1993]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)

Im trying to import data from Bitfinex

* **Expected result** (what you hoped would happen)

* **Actual result** (unexpected outcome)

./zenbot.sh backfill bitfinex.XMR-BTC --days 300

```
bitfinex.XMR-BTC saved 1431 trades 73 days left
.
error: getTrades() returned duplicate results
{ product_id: 'XMR-BTC', to: 1500560393000 }
{ product_id: 'XMR-BTC', to: 1500560393000 }
```

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
Wrong repo! This is not zenbot ;)
