### ISSUE TITLE
Cannot get Gekko to work when invoked via a code editor | debugger

### ISSUE THREAD

**Issue by goldistan** [askmike/gekko#1994]
Hello fellow Gekkoers!

I've been stuck on an obscure issue and I would really love to learn if anyone has seen it or was able to solve it.
I'm using Gekko in conjunction with Gekkoga for GA. When I run them both from the command line, i.e - gekko - node server.js and gekkoga node run -c config/something.js it works fine. Unfortunately when I try to debug different startegies from my code editor and start the debugger, gekko always throws exceptions for the very same code -

 Error: non-error thrown: Child process has died.
application.js:186
      at Object.onerror (c:\Users\moo\Desktop\projs\barnOwl\node_modules\koa\lib\context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

I know there's nothing wrong with the configuration as it runs fine from the command line. 
This is how I configured it in VS Code - 

"configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Gekko",
            "program": "${workspaceFolder}/web/server.js",
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Gekkoga",
            "program": "${workspaceFolder}/gekkoga/run",
            "args": [
            "-c", "${workspaceFolder}/gekkoga/config/something.js"
            ]
        }
    ],
    "compounds": [
        {
            "name": "Server/Server2",
            "configurations": ["Gekko","Gekkoga"]
        }
    ]

   I saw some other users were getting similar exceptions, but couldn't find a solution for it.
   Any ideas ? Thanks in advance btw.

**Comment by askmike** [comment]
I am not sure about VS Code, never used it before.

The only thing I can recommend is using the commandline interface when developing the strategy (see [here](https://gekko.wizb.it/docs/commandline/about_the_commandline.html)), that makes it a lot easier to debug what is happening (since no child processes are created).

**Comment by askmike** [comment]
If that doesn't work please reopen :)
