### ISSUE TITLE
Are gekko-strategies.com a good resurces site or is a scam?

### ISSUE THREAD

**Issue by scidran** [askmike/gekko#1997]
* **I'm submitting a question**
[ ] bug report
[ ] feature request
[X] question about the decisions made in the repository

* **Action taken**
Hi. i was searching into the web for information about gekko strategies. There is this site that have some strategies that you can bought: gekko-strategies.com. I think this site is not an official site but it was made by some programmers.
I understand that they post the result about the strategies that they sell into back-test not into real market. 

* **Expected result**
I'm interested to bought one of this strategies to see if there are some tech about programming that i can learn to write a better strategies or, at last, use directly the bought strategie.  

* **Actual result** (unexpected outcome)
Have some one bought one of this strategies and tested to see the functions into real market?
Have those strategies a high level code or are simple strategies that can be created by a simple programmers? 

* **Other information**

**Comment by joseanrt** [comment]
I would like to know also. I´m not a programmer to set up a strategies and I´m limited only tu use the include basics, one by one.

BR

**Comment by 11mkapadia** [comment]
This has got to be spam

**Comment by joseanrt** [comment]
The screenshots are done while BTC rise up to 19K on December, so it´s easy to make profitable any strategic...

**Comment by scidran** [comment]
Yes i saw that most of the strategies are tested in December 2017... but there is one that is tested on January that use a BB and a "complex stoploss mechanism with a differential trigger"...

**Comment by askmike** [comment]
This is someone that is profiting from the work I (and other people) have been doing for the last 5 years. I have no clue who this is.

I am closing this issue as I don't want to give any exposure to that person.

**Comment by aisiekjoe** [comment]
Gekko-Strategies.com is a complete SCAM-website. I was so stupid to buy a script from them and apparently this script only generates a "profit" in the backtest for the month and exchange and trading pair they show on their site. They recommend this script for EUR/BTC and USD/BTC but on that certain exchange EUR is not available. If you try the script for the same period EUR/BTC on other exchanges it only generates losses. Also in other months, where the market just went up without doing any trade, the script only generates losses in the backtests. They don't offer any support and if you complain they offer you a "40% discount" on your next purchase... ;-) 
Just to rip you off once again.... so stay away from this site!
