### ISSUE TITLE
[Backtesting] Error in roundtrip entry balance

### ISSUE THREAD

**Issue by zappra** [askmike/gekko#2002]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken**

Running backtests via Gekko UI

* **Expected result** (what you hoped would happen)

Roundtrip entry point should reflect portfolio balance before exchange fees

* **Actual result** (unexpected outcome)

Roundtrip entry point is calculated as the portfolio asset value, in other words excluding the exchange fees/slippage calculated in the paper trader. This skews the profitability calculation on individual roundtrips. This is relevant to me as I have other hacks to calculate and display the number of profitable roundtrips, and the average profit/loss for all roundtrips, which I think are useful stats. The roundtrip exit value is calculated correctly.

My local fix for this is to use the portfolio balance for the entry point, and in the paper trader set the balance equal to the total currency before simulating the 'buy'

**Comment by askmike** [comment]
Very good point, this is definitely a bug. Will make sure this gets in at #1850 so we can fix this (this requires the trader to send more data to the performanceAnalyzer).

**Comment by zappra** [comment]
As well as % profitable roundtrips, and average profit/average loss, max drawdown % would be another useful stat for comparing strategy performance
