### ISSUE TITLE
gekko into android tablet with dory-node app

### ISSUE THREAD

**Issue by scidran** [askmike/gekko#2003]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken**
I state that I am a newbie of javascipt, node and npm but I try otherwise to do something with gekko software. 
I installed dory-node into my tablet samsung A10 from google play. I also installed gekko with gitclone and i saw that `npm install --only=product` doesn't work fine without the `--no-bin-link` argument (this argument was recommended from dory app page using an SD to store packages; I haven't used an SD but without this argument npm doesn't work).
After this, I was amazed to saw that `node gekko --ui` start and that I can saw a node server with gekko into my tablet at localhost:3000!

* **Expected result**
But there is a problem: i tried to store a few of local data.
When I started to download the datas, I founded that sqlite3 wasn't installed...
I don't know if it's an error of npm but i founded that npm wrote into the shell that I must install sqlite3 with: npm install sqlite3@3.1.4.

* **Actual result**
But the command `npm install sqlite3@3.1.4` stop at the command node-pre-gyp install.
I try to install node-pre-gyp manually without success.
From the gekko directory of the tablet I also tried this commands:
`npm install sqlite3@3.1.4`
`npm install sqlite3@3.1.4 --no-bin-link`
`npm install node-pre-gyp -g`
`npm install node-pre-gyp -g --no-bin-link`
and also
`npm install  --only=product` without `--no-bin-link`
No way: I wasn't able to install node-pre-gyp.

* **Other information**

**Comment by scidran** [comment]
Hi guys.
I tried to do something to solve this issue.
I try to root my tablet without succeeding.
I try to contact the sqlite3 developers and dory-node developer without succeeding to.
I try in understand a wiki that I found to install sqlite3 into android but I haven't understand the procedure.
My newbie state into npm and node make me very frustrating.
So I post the actual state: gekko into android tablet but without the ability to read, store market data; so it can't do live action, test and download local data.
I understand that the problem is about the sqlite3 library that I'm not able to install locally.

**Comment by thegamecat** [comment]
Install postgres on a server then connect to that in gekko on your tablet.

**Comment by scidran** [comment]
> Install postgres on a server then connect to that in gekko on your tablet.

Sorry thegamecat but your solution is too difficult for me to understand.
I don't know how to install a postgres server and also how to connect it to gekko into  my tablet
