### ISSUE TITLE
Disconnected Error on Webserver

### ISSUE THREAD

**Issue by ghost** [askmike/gekko#2006]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Followed the instructions on how to create cloud-based UI along with other guides.

* **Expected result** (what you hoped would happen)
Web server connects and is functional.

* **Actual result** (unexpected outcome)
Disconnected.

Something happened to either Gekko or the connection.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
I'm running Ubuntu 16.04 LTS. 
I have configured the UIConfig using the instructions, except I changed 127.0.0.1 to 192.168.1.100 because the former does not work for some reason and it's a simple workaround, and I placed my URL.
I have configured the nginx file using the instructions by deleting what was inside the file and pasting the code and changing the URL.
All other steps I have taken.
Ports 22, 443, and 3000 are all open and checked.
I am able to connect from outside the network, but with same error.
Tested on Ubuntu laptop using Firefox, iPhone using Safari, and Windows 10 PC using Chrome.
Using my public IP along with No-IP to create a URL that adapts with my IP.

**Comment by ghost** [comment]
I have just tried again with a fresh machine (much, much faster this time to do) with the same result. Only difference is that I used Ubuntu 17.10.1.

I have also just checked the SSL just in case using sslshopper.com and the only caution sign I get is from having the self-created SSL.

**Comment by askmike** [comment]
If you see the message "Disconnected. Something happened to either Gekko or the connection." that means Gekko is able to connect via standard http calls but not via websocket connections. Usually one of the following:

- your browser does not support websockets (ie)
- you don't have nginx configured properly
- your network does not allow for websocket connections (some 3g connections)

**Comment by ghost** [comment]
I changed the host to "example" from my actual one in the code below.

My UIConfig

const CONFIG = {
    headless: true,
    api: {
        host: '192.168.1.100',
        port: 3000,
    },
    ui: {
        ssl: true,
        host: 'example.myddns.me',
        port: 443,
        path: '/' // change this if you are serving from something like `example.com/gekko`
    },
    adapter: 'sqlite'
}


if(typeof window === 'undefined')
  module.exports = CONFIG;
else
  window.CONFIG = CONFIG;




My Nginx config.

server {
    listen 80;
    listen [::]:80;
    server_name example.myddns.me;
    return 301 https://$server_name$request_uri;
}

upstream websocket {
    server localhost:3000;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    root /var/www/html;

    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;    

    location / {
            proxy_buffers 8 32k;
            proxy_buffer_size 64k;

            proxy_pass http://websocket;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-NginX-Proxy true;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_read_timeout 86400s;
            proxy_send_timeout 86400s;

            auth_basic "Restricted Content";
            auth_basic_user_file /etc/nginx/.htpasswd;
    }
}





Do you or anyone else see a problem with the code? Maybe something I forgot to configure or something that needs to be updated.


Update:
I changed the port to 3005 and that seemed to get me slightly closer as now the SSL is being used and I could login using the .htpasswd info. Now the only problem I have is a 502 Bad Gateway once I sign in. I'm also able to ping the URL from inside the network, but once I try going off the network it drops every packet.

**Comment by ghost** [comment]
I just found out that my ISP blocks all inbound traffic from port 80. Is there a way to not use port 80 or remap it to a port that would allow for an inbound signal like 8080?

**Comment by ghost** [comment]
I have managed to be able to connect to the server on the internal side after changing the port to 8080. However, the external is still experiencing disconnections after I sign in. What can this be attributed to?

Update
Nevermind. I guess it's just my phone that can't connect to it no matter what. It works fine on PCs and laptops. I'm assuming the problem was completely reliant on my ISP blocking port 80, so I changed all listens on port 80 to port 8080, forwarded that, then was able to connect by using :8080 at the end of my URL.
