### ISSUE TITLE
implement a technicalindicators library

### ISSUE THREAD

**Issue by myBytesCom** [askmike/gekko#2008]
Hi guys,
I try to implement a technicalindicators library from npmjs. This library is able to find all bullish or bearisch candlepatterns and also it includes some good technical indicators.
I do not know the arcitecture of gekko enough, to do this job from one to the next day. But I like gekko and want to engage a little bit. So as an experienced coder, my way is it, to jump into cold water and just want to start and lern by doing. So exactly what I need to know:

I want to require the library correctly like gekko needs, to have the methods available everywhere, when a decision for or against a trade happens. I think this will be in the strategies.
It should be able to check incoming market data in realtime for upcoming candlestick formations as well as safe the candlestick formations of imported data. 

The library is able to do things ike this:

```
var downsidetasukigap =require('technicalindicators@1.0.5').downsidetasukigap;
//var drawCandleStick = require('draw-candlestick');
//var canvas = require('canvas');

var threeDayInput = {
open: [45.00, 33.45, 30.20],
high: [46.20,34.70,36.63],
close:[41.20,29.31,36.28],
low: [38.56,28,29.80],
}

//var imageBuffer = drawCandleStick(threeDayInput);
//console.log(imageBuffer);
var result = downsidetasukigap(threeDayInput);
console.log('Is DownsideTasukiGap Pattern? :' +result);
```

It would be useful to fluently have the one, two, three and four day input available at strategys level. There we could make decisions like if MACD is crossing up after a bearish pattern, don't buy, wait for bullish pattern and other things like this. The library is able to indicate bullish or bearish pattern also in one action.

From my opinion it should be wise to implement this, for better strategies.

My questions:
Where and how can I make the last 4 candles available, the best way?
How can we make this functionallity in paper, marketwatch, trading, backtest etc available.
Could we compute the results btw the pattern recognition for imported data, incoming data and realtime data that way, that we can mark the candles as part of pattern x,y,z and wheater it is a bullish or a bearish pattern?

Then I think it could be a nice approach to have a candlestick chart view in the webpage, marking the patterns eventually. But this can and is no must have.

If anybody thinks that this is a good thing to have, plz lets work together. This could be a good extensions at all.

**Comment by myBytesCom** [comment]
I forgot to link the library:
https://github.com/anandanand84/technicalindicators   (MIT License and well maintained)

Plz have a look and scroll to "Pattern Detection" headline.

**Comment by askmike** [comment]
Hey,

Gekko supports 3 types of indicators right now:

- native gekko indicators, see [here](https://github.com/askmike/gekko/tree/develop/strategies/indicators).
- talib indicators, see [here](https://gekko.wizb.it/docs/strategies/talib_indicators.html)
- tulip indicators, see [here](https://gekko.wizb.it/docs/strategies/tulip_indicators.html)

Everything is managed here, if you want to add another one you basically need to make sure strategies can register them and than calculate the correct values every candle: https://github.com/askmike/gekko/blob/develop/plugins/tradingAdvisor/baseTradingMethod.js

> Where and how can I make the last 4 candles available, the best way?
> How can we make this functionallity in paper, marketwatch, trading, backtest etc available.
> Could we compute the results btw the pattern recognition for imported data, incoming data and realtime data that way, that we can mark the candles as part of pattern x,y,z and wheater it is a bullish or a bearish pattern?

If you do it in that file above everything will be handled automatically for backtests, paper traders and real traders. Gekko handles all of that :)

**Comment by myBytesCom** [comment]
The baseTradingMethods.js iis the place I was looking for, thx.

SO I can do anything like that:

var candleformation = require('path_to_technical_library');
if(candleformation == null) {
  log.warn('My library could not be loaded, functions will be unavailable.');
}

and then do anyhow the job, to analyse each time the last 2-3-4 canldes for a candle formation?
I have to check out how this might become to a permanet information on the time, when a new candle comes in. To check candle formations it is neccessary to have temporary the information of the 4 candles before available.

Best would be, if a kind of backward looking function could check the last 3-4 candles or more, to define the actual status. bullish or bearish by candle "three towers" or such things. 
Good to know. Last formation, upcoming formation, general trend or more of those signal supporters

Maybe possible to create some "signal supporters by candle". 

Think of strategies where MACD gives a clear signal, but candles tell about a bearish dip. So a wait for bullish signal could block a buy with a latency until the next candle prediction is more bullish.

You know, same like experienced human trader would decide. 


But it should be overview the data of the last 4 candles of actual history. Is that possible?

Think A database funktion is needed here?

**Comment by askmike** [comment]
> to analyse each time the last 2-3-4 canldes for a candle formation?

If you need these you need to store them as them come in, the basTradingMethod gets candle events like so:

1. candle 1 -> run `Base.prototype.tick()`
2. candle 2 -> run `Base.prototype.tick()`
3. candle 3 -> run `Base.prototype.tick()`
4. candle 4 -> run `Base.prototype.tick()`

If you want to have candle 1, 2 and 3 available when 4 comes around you need to store them when you see them (in 1, 2 and 3). Than at candle 4 you have them all. You can see this already being done for the other libraries here:

https://github.com/askmike/gekko/blob/36f361210cc941b68af1579dffc173ef67bc1139/plugins/tradingAdvisor/baseTradingMethod.js#L122-L140
