### ISSUE TITLE
[Feature] Slack message after trades, profits and roundtrip reports

### ISSUE THREAD

**Issue by VinceBT** [askmike/gekko#2010]
I expose my case:

I have many bots running on containers that I can only see the first 100 lines of log and I also like to see the debugging lines to ensure the bot is running well but sometimes when the bots trade, the trade logs gets drowned in the mass of debug log. 

That's where the Slack plugin is helpful for me, I see when there is an advice and I check the logs directly but it's not very practical.

Right now the slack plugin only shoots advice and I think triggering it for trades, profit and roundtrip reports could be a great addition to the plugin.

What do you think ?

**Comment by askmike** [comment]
Great idea! I am just working on a big update which is required to make this possible. Right now there are only a few things plugins (like the slack plugin) can subscribe to (so they can slack it to you). Here is what I am working on: https://github.com/askmike/gekko/pull/1850

Unfortunately we can't do this yet until that PR is completed, it's a big refactor so it might take a while.
