### ISSUE TITLE
Gekko Serving UI but can't connect. Running on AWS EC2 instance without NGINX as an upstream.

### ISSUE THREAD

**Issue by srich36** [askmike/gekko#2014]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Here is the UIConfig file:

const CONFIG = {
  headless: true,
  api: {
    host: '127.0.0.1',
    port: 3000,
    timeout: 120000 // 2 minutes
  },
  ui: {
    ssl: false,
    host: 'domain.com', //Public DNS of my EC2 instance
    port: 3000,
    path: '/'
  },
  adapter: 'sqlite'
}

if(typeof window === 'undefined')
  module.exports = CONFIG;
else
  window.CONFIG = CONFIG;

* **Expected result** (what you hoped would happen)

I just want to set up gekko to run from an EC2 instance without NGINX as a reverse proxy. I know this is not recommended but I have no experience with servers and just want to make this as simple as possible.

* **Actual result** (unexpected outcome)
Output of the node gekko --ui command:

node gekko --ui

    ______   ________  __    __  __    __   ______
   /      \ /        |/  |  /  |/  |  /  | /      \
  /$$$$$$  |$$$$$$$$/ $$ | /$$/ $$ | /$$/ /$$$$$$  |
  $$ | _$$/ $$ |__    $$ |/$$/  $$ |/$$/  $$ |  $$ |
  $$ |/    |$$    |   $$  $$<   $$  $$<   $$ |  $$ |
  $$ |$$$$ |$$$$$/    $$$$$  \  $$$$$  \  $$ |  $$ |
  $$ \__$$ |$$ |_____ $$ |$$  \ $$ |$$  \ $$ \__$$ |
  $$    $$/ $$       |$$ | $$  |$$ | $$  |$$    $$/ 
   $$$$$$/  $$$$$$$$/ $$/   $$/ $$/   $$/  $$$$$$/

	Gekko v0.5.12
	I'm gonna make you rich, Bud Fox. 

Serving Gekko UI on http://DNS.compute.amazonaws.com:3000/                    
Something went wrong when trying to open your web browser. UI is running on DNS.compute.amazonaws.com:3000/.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

This may be something simple because I do not have any server experience, but I have security groups inbound on TCP 3000 for my IP address (and everywhere).

Any and all help is appreciated, again this stuff is very new to me. Thanks.

**Comment by askmike** [comment]
I am pretty sure this has to do with the security group settings on AWS, by default all ports are blocked (except ssh and maybe port 80 and such).

**Comment by askmike** [comment]
if that doesn't solve it please reopen :)

**Comment by srich36** [comment]
Hi Mike, attached are my securtiy group settings for my AWS instance. Port 3000 (from anywhere), 80 (from my local machine), and 22 (from my local machine)  all allowed. 
![gekko help](https://user-images.githubusercontent.com/25950716/37167993-75edc79c-22d1-11e8-82f9-d6e0cc419b7e.png)
