### ISSUE TITLE
Missing Trade Logs when using CLI

### ISSUE THREAD

**Issue by Kris191** [askmike/gekko#2016]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Running Gekko from CLI however no logs for trades are being created, the bot has made 5 trades but still no output log, AdviceLogger is active also. System is kunbuntu over a server.

* **Expected result** (what you hoped would happen)
Log output in the log folder

* **Actual result** (unexpected outcome)
Empty folder

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
All logs are piped to stdout! If you want a log file simply do `node gekko -c your-config.js > logs/my-log-file.txt`. This means that if you use docker logs are found by using `docker logs`.
