### ISSUE TITLE
Adding new pairs to binance

### ISSUE THREAD

**Issue by Daakko** [askmike/gekko#2019]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[x ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Trying to update according all the help given

* **Expected result** (what you hoped would happen)
i would like to add 

41 | BLZ/BNB | 0.01 | BLZ | 0.00001 | BNB | 1 | BNB
-- | -- | -- | -- | -- | -- | -- | --
42 | AE/BNB | 0.01 | AE | 0.00001 | BNB | 1 | BNB
43 | RPX/BNB | 0.01 | RPX | 0.00001 | BNB | 1 | BNB
44 | NCASH/BNB | 0.01 | NCASH | 0.00001 | BNB | 1 | BNB
45 | POA/BNB | 0.01 | POA | 0.00001 | BNB | 1 | BNB
46 | ZIL/BNB | 0.01 | ZIL | 0.00001 | BNB | 1 | BNB
47 | ONT/BNB | 0.01 | ONT | 0.00001 | BNB | 1 | BNB

added them to >exchanges>binance.

* **Actual result** (unexpected outcome)
ive got an all error when running an binance market

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

can someone give me a step by step walktrough on how to do it? or can some update the exchange>binance files

**Comment by weeder** [comment]
You doing it in /exchanges/binance-markets.json file
First add asset in list like:
 "ONT",
After that add somewhere down:
{
      "pair": [
        "BNB",
        "ONT"
      ],
      "minimalOrder": {
        "amount": 0.01,
        "price": 0.00001,
        "order": 1
      }
    },
After that restart gekko
GL

**Comment by Daakko** [comment]
Geez, i forgot the last , pfffffff. Thanks bud for you assistance. Do you also know a thing or 2 about stratagies? i want to set up my own strategy but need some help
