### ISSUE TITLE
How to disable debug logging?

### ISSUE THREAD

**Issue by mboremski** [askmike/gekko#2020]
I am using gekko as a service and using gekkoga to find good trading-values.
I found gekko driving my deamon.log-file to GB size.
I already changed config.debug = false in my config.js.

But gekko still trows a lot of DEBUG log events.

Any hints what I can do to fully disable DEBUG-Logs?

**Comment by askmike** [comment]
If you are running the gekko server (gekko ui), open up this file:

https://github.com/askmike/gekko/blob/develop/web/routes/baseConfig.js#L10

And set debug to false and silent to true (will mute all output).
