### ISSUE TITLE
Centos 7 Installation

### ISSUE THREAD

**Issue by Cavain** [askmike/gekko#2021]
Hello,

How can i install Gekko on Centos 7 , i didn't found any information about Centos installation on linux server.

Thank you !

**Comment by askmike** [comment]
You can follow the normal instructions here: https://gekko.wizb.it/docs/installation/installing_gekko.html]

If you run into more issues, please post them on the forum here: http://forum.gekko.wizb.it/

You posted this on a bug tracker.
