### ISSUE TITLE
Issue with Gekko not retrieving QuadrigaCX balances

### ISSUE THREAD

**Issue by larathydo** [askmike/gekko#2022]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
When I turn on the trader after configuring my key/secret/username for QuadrigaCX, I see the following messages with debug turned on:

2018-03-11 14:53:26 (INFO):	Setting up:
2018-03-11 14:53:26 (INFO):		 Trader
2018-03-11 14:53:26 (INFO):		 Follows the advice and create real orders.
2018-03-11 14:53:26 (DEBUG):	getting ticker, balance & fee from quadriga
2018-03-11 14:53:26 (INFO):	

2018-03-11 14:53:27 (DEBUG):	Unable to find "CAD" in portfolio provided by exchange, assuming 0.
2018-03-11 14:53:27 (DEBUG):	Unable to find "LTC" in portfolio provided by exchange, assuming 0.
2018-03-11 14:53:27 (INFO):	trading at quadriga ACTIVE
2018-03-11 14:53:27 (INFO):	quadriga trading fee will be: 0.5%
2018-03-11 14:53:27 (INFO):	quadriga portfolio:
2018-03-11 14:53:27 (INFO):		 CAD: 0.000000000000
2018-03-11 14:53:27 (INFO):		 LTC: 0.000000000000

* **Expected result** (what you hoped would happen)
Gekko would have been able to retrieve my CAD/LTC balance from the API.

* **Actual result** (unexpected outcome)
Gekko assumes the balance is zero given it's inability to determine account balance.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
I have double checked my API settings on Quadriga and it is set with the following options enabled:

-> List Balances Enabled (Display all of your account's fiat and crypto balance data.)
-> List Transactions Enabled (Display all of your account's trade, funding and withdrawal data.)
-> List Open Orders Enabled (Display list of Open Orders from your account.)
-> Lookup Order Enabled (Query an Order to fetch more details.)
-> Cancel Open Order Enabled (Ability to cancel an Open Order.)
-> Trading Enabled (Allow API to create Buy or Sell orders.)
-> Funding DISABLED (Display the current funding address.)
-> Withdrawal DISABLED (Initiate a withdrawal.)

Also, I see reference to this error in Issue #1923, perhaps related to some recent code changes perhaps? Thanks in advance for any help you can provide.

**Comment by cmroche** [comment]
Could you add a line to quadriga.js which prints out the returned result of the api call to Quadriga in the getPorfolio function please?

`console.log(JSON.stringify(data));` or something of this sort.

I'll need to see the result to know how to make the correct here, thank you.

**Comment by ve6btc** [comment]
Same issue honestly not a coder not sure how to fix but know the problem quad uses all lowers in their stupid api 

https://www.quadrigacx.com/api_info

"The current order books on QuadrigaCX are:

    btc_cad
    btc_usd
    eth_cad
    eth_btc
    ltc_cad
    ltc_btc
    bch_cad
    bch_btc
    btg_cad
    btg_btc

*Note that Bitcoin is considered the "minor" currency in the Ether/Bitcoin order book.

The currencies are specified with the following 3 letter codes

    Canadian Dollars = cad
    US Dollars = usd
    Bitcoin = btc
    Litecoin = ltc
    Bitcoin Cash = bch
    Bitcoin Gold = btg
    Ether = eth
"



2018-03-25 20:35:49 (DEBUG):    Unable to find "CAD" in portfolio provided by exchange, assuming 0.
2018-03-25 20:35:49 (DEBUG):    Unable to find "BTC" in portfolio provided by exchange, assuming 0.
2018-03-25 20:35:49 (INFO):     trading at quadriga ACTIVE
2018-03-25 20:35:49 (INFO):     quadriga trading fee will be: 0.5%
2018-03-25 20:35:49 (INFO):     quadriga portfolio:
2018-03-25 20:35:49 (INFO):              CAD: 0.000000000000
2018-03-25 20:35:49 (INFO):              BTC: 0.000000000000
2018-03-25 20:35:49 (INFO):     Setting up:
2018-03-25 20:35:49 (INFO):              Performance Analyzer
2018-03-25 20:35:49 (INFO):              Analyzes performances of trades

**Comment by larathydo** [comment]
Hey, sorry for the delay in responding. I’m in the same boat of ve6btc - not super familiar how to do what you’re asking cmroche.

If you wouldn’t mind elaborating with more guidance I’d be happy to do whatever you’d like me to try!

**Comment by ve6btc** [comment]
I notice in quad ha file changes have been made actually to set to lower after a quick review so at this point I’m not sure where the issue lays but would also be happy to help provide any info I can to make gekko work with quad  at this point

**Comment by cmroche** [comment]
Thanks for the info, ill take a look in the next few days.

**Comment by larathydo** [comment]
Hi cmroche,

Have you made any headway on this issue? Just curious if there is anything I can to to help...

**Comment by cmroche** [comment]
Not yet no, hoping to have some time this weekend though.

**Comment by larathydo** [comment]
No worries. It goes without saying your assistance is much appreciated!

**Comment by cmroche** [comment]
@larathydo Fix is waiting in PR #2081

**Comment by larathydo** [comment]
Awesome! Thanks. I'll let you know how I make out once it is available.

**Comment by jcoder76** [comment]
There are more issues than just this.  I have been trying to trade with Quadriga as well even with the above mentioned patch applied it still fails to make trades.  I will get you my logs later when I get home.

**Comment by jcoder76** [comment]
There is also a problem with rounding handling in the `roundAmount` prototype function.  You can't expect to get the correct `this` object passed into the function closure unless you assign it to another variable.  That and you can't define precision by multiplying a number by 10, it needs a power of 10.
It was causing problems whenever it tried to round the values because:
1. it never found the market (invalid object, not a number)
2. even if it did it wouldn't round properly.

Correct code:
```javascript
Trader.prototype.roundAmount = function(amount) {
  var precision = 100000000;

  var parent = this;
  var market = Trader.getCapabilities().markets.find(function(market){ return market.pair[0] === parent.currency && market.pair[1] === parent.asset });

  if(Number.isInteger(market.precision))
    precision = Math.pow(10, market.precision);

  amount *= precision;
  amount = Math.floor(amount);
  amount /= precision;
  return amount;
};
```

**Comment by jcoder76** [comment]
Besides this, the minimum order amounts in the profile is wrong anyhow.  I am planning to offer a better pull request once I get all the patches figured out.  I have the market working perfectly now.  It has been working non-stop for over a week.

**Comment by cmroche** [comment]
Great! Thanks for your work. Just ping me into the pull request when you send it and I’ll do a review.

**Comment by jcoder76** [comment]
Looks like I spoke too soon.  The market hit an edge case this morning.  Apprently it can get into a position where it tries to buy less than $1.00 CAD of an asset.  Not sure the correct way to fix this.  Will be testing more to see what works.  In the meantime it will work MOST of the time with the patches so I'll try to get something together soon.

**Comment by daflame76** [comment]
This bug is probably more relevant to this issue.  In the `getOrder` method it incorrectly uses `"lookup_oder"` instead of `"lookup_order"`.  Somewhat easy to miss, but if you look in the `checkOrder` method it is correct.

The offending code:
```javascript
  this.quadriga.api('lookup_oder', {id: order}, get);
```

**Comment by daflame76** [comment]
Oops, I meant to post that in another issue.

**Comment by jcoder76** [comment]
I am running into another issue now with my recent patches.  It seems to think a buy was successful all the time even though it is still waiting, so I will keep working on it.

**Comment by larathydo** [comment]
Thanks @daflame76!

**Comment by larathydo** [comment]
Has anyone made any headway on this by chance? I've honed in on a strategy i'd like to start using but as soon as I enable the trader I am still encountering the "**Unable to find "CAD" in portfolio provided by exchange, assuming 0.**" error message.

**Comment by larathydo** [comment]
I am so sorry - I just realized I wasn't using the most recent comitted changes to the quadriga.js file as illustrated in #2081!

I just updated the file and it's now picking up asset/currency values via the API! Thanks @cmroche 

That said, i'll let gekko run for a few days and see if I encounter the other problems/errors @daflame76 said he was encountering and see if I get them too...

**Comment by larathydo** [comment]
Hello Folks,

While I am now successfully able to get balances through the API, it seems that I was unable to actually place a buy order through Gekko - below are the only entries I have in my logs (sorry, debug mode was not turned on at the time of buy advice - i've turned it on for future logging):

> 2018-05-09 05:11:41 (INFO):	trading at quadriga ACTIVE
> 2018-05-09 05:11:41 (INFO):	quadriga trading fee will be: 0.5%
> 2018-05-09 05:11:41 (INFO):	quadriga portfolio:
> 2018-05-09 05:11:41 (INFO):		 CAD: 50.000000000000
> 2018-05-09 05:11:41 (INFO):		 ETH: 0.000000000000
> 2018-05-09 05:11:41 (INFO):	Setting up:
> 2018-05-09 05:11:41 (INFO):		 Performance Analyzer
> 2018-05-09 05:11:41 (INFO):		 Analyzes performances of trades
> 2018-05-09 05:11:42 (INFO):	
> 
> 2018-05-09 05:11:43 (INFO):	Starting to watch the market: Quadriga ETH/CAD
> 
> 2018-05-09 08:23:04 (INFO):	We have new trading advice!
> 2018-05-09 08:23:04 (INFO):		 Position: long
> 2018-05-09 08:23:04 (INFO):		 Market price: 950
> 2018-05-09 08:23:04 (INFO):		 Based on market time: 2018-05-09 11:20:00
> 
> 2018-05-09 08:23:04 (INFO):	Trader Received advice to go long. Buying  ETH
> 2018-05-09 08:23:04 (INFO):	Attempting to BUY 0.05235656917873485 ETH at quadriga price: 950.00

I checked my history on Quadriga and no buy orders actually took place. Any ideas?

**Comment by jcoder76** [comment]
This is probably related to the issues I have run into as well.

I solved most of them, but I have been unsuccessful getting any trading on the development version of gekko.

Only on the stable branch. I just cherry picked a few changes and fixed the errors mentioned above to make it work.

**Comment by jcoder76** [comment]
I have the patches almost prepared.  I'll be able to push out some fixes this week/weekend.

**Comment by jcoder76** [comment]
In the meantime you can checkout the changes in my fork https://github.com/daflame76/gekko/tree/fix-quadriga-bugs-develop

**Comment by larathydo** [comment]
hey @daflame76, is the only file i'd need to pull from your fork the quadriga.js file, or are there any other files i'd need to facilitate your changes?

Also, you mentioned you solved most of the problems - are you aware of which type of problems are still outstanding (and i'd need to keep an eye out for)?

**Comment by jcoder76** [comment]
It depends at what point you pull it.  If you include the market refactoring you'll need `quadriga-markets.json` as well.

**Comment by jcoder76** [comment]
I mentioned earlier in this thread I'm having trouble with the system failing to detect an order is still waiting so it thinks the trade already happened and throws off the trading advisor and trades hang on the books.

**Comment by jcoder76** [comment]
I aim to get a few proper PRs up this weekend if possible.

**Comment by jcoder76** [comment]
I released all the patches except one.  I am still working on the issue where it tries to buy/sell less than $1 which Quadriga doesn't like.  Not sure how to prevent it from trying to make limit trades so low.

**Comment by zgwenwen** [comment]
@daflame76 get some ideas

`
if (buyAmount < $1) {buyAmount = $1};
if (sellAmount < $1) {
    sellAmount = $1;
} else if (totalCurrency - sellAmount < $1) {
    sellAmount = totalCurrency;
}
`

**Comment by jcoder76** [comment]
The QuadrigaCX exchange is dead and all references should be removed.  https://www.quadrigacx.com/
