### ISSUE TITLE
Live trading Binance Error 400

### ISSUE THREAD

**Issue by Alex-hash1** [askmike/gekko#2025]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Red all here about error 400 without succes

**Expected result** (what you hoped would happen)
settled up my strategy, Gekko didn't want to trade live. worked perfectly in backtesting and in paper wallet

**Actual result** (unexpected outcome)
RECEIVED ERROR IN GEKKO 8114923222326054
Gekko encountered an error and can't continue
Gekko encountered an error and can't continue
Error:
[binance.js] Response code 400
Meta debug info:
Gekko version: v0.5.12
Nodejs version: v8.9.4
Fedora 27
Binance 1.3.3

OTHER Info:

Hi guys, first off all thanks for the amazing work and support you provide, as you can read i'm in trouble with live trading on binance using Gekko. Tryed to create new api key but no changes. What should i do with my actual version to solve the problem?
If anyone could help?
Thanks a lot for reading.
Cheers

**Comment by Alex-hash1** [comment]
Hi guys,
installed dev version instead and no errors shown so far, trading live working on binance.
results are very different as in backtesting as market dont answer every time, resulting in much more less trade. I also wonder why it sometimes stop working for hours, i mean by that not trying to buy or sell.
Regards.

**Comment by devinat1** [comment]
I had the same issue of live trading not working when using the stable version from ETH/USDT w Binance. It would be great if this were fixed.
