### ISSUE TITLE
CPU high to 99% when run a market watcher with adapter set to 'postgresql'

### ISSUE THREAD

**Issue by ghost** [askmike/gekko#2026]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[X] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
1.Run gekko on Windows10. (use `git pull` to get the newest code )
2.Install postgresql10 ,run with default configuration.
3.Change adapter to 'postgresql'  in these files:
     config/general.toml
     config/plugins/candleWriter.toml
     web/vue/UIconfig.js
4.Live Gekkos ->Start a new gekko:
   Market: Exchange = poloniex; Currency=USDT; Asset=BTC
   Type:market watcher

**Expected result** (what you hoped would happen)
   Everything goes right like it did when adapter = sqlite

**Actual result** (unexpected outcome)
   The CPU  went high to 99%.  The Computer got blocked.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
![cpu](https://user-images.githubusercontent.com/3690826/37335092-8f82d24a-26e8-11e8-962d-b5495ee6698c.png)

I've no idea where to debug. One thing I did is check the postgresql query:
![postgre](https://user-images.githubusercontent.com/3690826/37335353-3d965078-26e9-11e8-8cda-8e3a8fb1335c.png)

**Comment by askmike** [comment]
Very strange, will try to investigate!

**Comment by askmike** [comment]
Apologies for never getting back to this. Postgre support had some major updates from @mark-sch and me. Please try a recent version!
