### ISSUE TITLE
Live trading Binance - no trade - no error message

### ISSUE THREAD

**Issue by yann2305** [askmike/gekko#2027]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
- Uninstall the stable branch
- Install the develop branch
- Uninstall binance.js
- Reinstall binance.js
- Delete API Binance key
- Set a new API Binance key

**Expected result** (what you hoped would happen)
That gekko places orders, makes some trades.

**Actual result** (unexpected outcome)
No order, no trade for almost 12 hours.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Hi !
I'm very new at this so I'll can not help a lot. 
Almost everything worked fine (importing data, backetsting, paper trader, etc).
I didn' try to trade on the others exchanges.

Configuration : 
- Hardware : HPE Gen8 - Xpenology
- Nodejs : v8.2.1 (Synology package)
- Gekko : v0.5.13

Thank you for your help and for your amazing work here !

**Comment by xbromy** [comment]
Please check in gekko/logs/ xyz -tradin.... .log for messages. I think you have the problem with minimalOrder amounts. There is a fixed bug in development branch...
What is the coin you want to trade?

**Comment by yann2305** [comment]
Thoses messages appear repeatedly : 

2018-03-13 14:59:44 (DEBUG):	Requested NULS/BNB trade data from Binance ...
2018-03-13 14:59:45 (DEBUG):	Processing 1 new trades. From 2018-03-13 13:59:32 UTC to 2018-03-13 13:59:32 UTC. (a few seconds)
2018-03-13 15:00:04 (DEBUG):	Requested NULS/BNB trade data from Binance ...
2018-03-13 15:00:05 (DEBUG):	No new trades.

No message about minimalOrder amounts.

As you see, I want to trade the BNB/NULS pair.
I allready installed the development branch.

**Comment by xbromy** [comment]
Okay, that's not the issue I had. Sorry

**Comment by askmike** [comment]
Gekko only trades when the strategy you are using signals that it should trade. It doesn't seem like a any signal happened which means you haven't waited long enough or the the strategy is not configured correctly.

This doesn't seem like a bug, please see the [getting help](https://gekko.wizb.it/docs/introduction/getting_help.html) for getting help on using Gekko, this is the bug tracker.

**Comment by yann2305** [comment]
Hi Askmike, 

Thanks for your answer. I tried this strategy in backtesting mode and in paper trader mode, and it worked well. Why does it couldn't work in tradebot mode then ?
