### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by kryptofun** [askmike/gekko#2030]
Hello,
I do not know if this is a bug or not but after following the installation guide (for windows 10 in bash) I have the follwing errors: 
module.js:545
throw err;
^
error: cannot find module moment'

Is it a bug or did I do something wrong in the installation?

Thanks,

**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)

**Expected result** (what you hoped would happen)

**Actual result** (unexpected outcome)

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
Hey,

Thanks for your interest in Gekko. Unfortunately this is the bug tracker used to discuss things of a technical nature related to the project. Gekko is definitely not the easiest piece of software to set up, however there is a community of people who might be able to help you. Have a look at the [getting help page](https://gekko.wizb.it/docs/introduction/getting_help.html).

Happy trading!
