### ISSUE TITLE
Live trading stop working

### ISSUE THREAD

**Issue by Alex-hash1** [askmike/gekko#2033]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Settled up live trading, ran fine for few hours, than it stopped trading despite the fact that data still coming in, i can see in the log file that it warned me "Wanted to buy BTC but the amount is too small  (52.00000000 @ 0.00003361 ) at binance" pair is still the same and i didn't take anything out. It Also continue predicting moves as i can see in the log. Any idea why?

**Expected result** (what you hoped would happen)
Trading and earning a bit :-) 

**Actual result** (unexpected outcome)
continuing getting data but not able to trade

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Regards

Pili

**Comment by jose-camilo** [comment]
Im also having the same issue with Binance XMR/ETH. I also have issues with DGD/ETH on the same exchange, but the error is another one.

2018-03-15 13:35:39 (INFO):	Attempting to BUY 0.001798365817091454 DGD at binance price: 0.66519
2018-03-15 13:35:39 (ERROR):	[binance.js] (addOrder) returned an irrecoverable error: undefined
