### ISSUE TITLE
Backtest percentage profit changes with each test

### ISSUE THREAD

**Issue by slowestmonte** [askmike/gekko#2034]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[X ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)

**Expected result** (what you hoped would happen)
The backtest reliably show a percentage profit or loss

**Actual result** (unexpected outcome)
The backtest shows a different number every time you do a backtest with the same values

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Every time I try to run a backest with the same strategy and same candle amount, it spits out a different number. Should I try re-installing certain files to remedy this, or try ending the process and turning it back on again? I'm running on windows 7, and I'll attach some images of the backtests and the strategy, etc that I am using. 

![capture](https://user-images.githubusercontent.com/37448622/37528146-3c87d62a-290a-11e8-8786-5d572fe2bc58.PNG)
![capture1](https://user-images.githubusercontent.com/37448622/37528147-3c9adedc-290a-11e8-9b3b-a053879e8256.PNG)
![capture2](https://user-images.githubusercontent.com/37448622/37528148-3cd9ff5e-290a-11e8-8634-5ca9104dfef7.PNG)
![capture3](https://user-images.githubusercontent.com/37448622/37528149-3ce9df8c-290a-11e8-9873-c08e91da77a3.PNG)

**Comment by genopsyism** [comment]
What was the exchange and asset being traded?  Do you only see variable results with this custom strategy?  If you use MACD, do your results also vary?

**Comment by askmike** [comment]
The default custom strategy does "random" trades, eg. they will be different every time you run them. It's example code meant as a starting point for you to start writing custom strategies. See the comments in the strategy.

If you have edited the custom strategy with other logic please specify what you changed.
