### ISSUE TITLE
Supporting Limit Orders with leverage on Kraken

### ISSUE THREAD

**Issue by PanoPilot** [askmike/gekko#2036]
**I'm submitting a ...**
[ ] bug report
[ ] question about the decisions made in the repository
[X] Cry for help ;-)
**Action taken** (what you did)

With the current bear Market I recently did some nice profits on Kraken by using limit orders with leverage. Well I just risk the money I have so I am not really trading on margin but putting it simply I am selling short at a high price and buy back on low price when my tech indicator signals me to do it.

Now I like to adapt gekko to do this for automatically and ask for some help pointing me to the right direction / line of code. Therefore I want to enhance the TradingAdvisor and the Kraken.js to handle the following things:

Trading Advisor
- Handle / differentiate between advice Long/Short with and without leverage

Kraken.js
- Handle new order types and therefore adapt API Calls

If I see this too simple any feedback is also highly appreciated. I checked out already Issue #335 but I do not want to over complicate things. But i have to admit I am new to this kind of trading strategy and might not have the full picture yet ;-) At least I want to give it a shot.

Thanks for any help/comment
Best,
Chris

**Comment by F3nryll** [comment]
Exactly what I want to do and was about to ask :)

Thinking to implement it myself and need some guidance on how to start and to do it in a proper "sharable" way.

**Comment by fjpedrosa** [comment]
Hi! @PanoPilot by "with a without leverage" you mean that, if you set a limit to sell, and the price is increasing, you don't sell until the price decrease a percentage of the maximum value achieved? If so, I was playing around a couple of days ago with https://github.com/cloggy45/Gekko-Bot-Resources using the stop Loss option. To perform what you want to do, I just implemented the stop loss when selling so instead of sending the advice "short", the stop loss limit was updated with a %, so below that price it is automatically triggered the sell action.

On the other hand, It would be interesting to know the indicators you are using to know when is time to buy. My backtest results are not very good... using XRP from 2018-1-1 to 2018-03-19 I get around 27% profit, which is not bad considering the market decreases a -67% aprox, but I guess it can be improved.

**Comment by PanoPilot** [comment]
HI @bokeauss, sounds interesting. However I meant a margin trade. Meaning i want to open a position to go short when the prices are high and close the position when the price has dropped.

Check out: 
https://support.kraken.com/hc/en-us/sections/200559303-Trading-Leverage-and-Margin

or to have a better view on this, check this out. I am not going for a blackbird abitrage strategy but this explains the shorting postion quite well. 
https://github.com/butor/blackbird/issues/100

So Iam using a combo of MACD , RSI and Fibonacci Retracement. I am at 48% for your timeframe but with ETH/EUR on gdax

**Comment by PanoPilot** [comment]
Hi there,

just found some time to work on this one. I did some few modification to the code and now Gekko can margin trade on kraken. What I did so far:

1. Added a new Exchange "kraken_margin"
   - copied kraken.js to kraken_margin.js
   - using cli to start. if u want to use the webui u need to rebuild the ui based on mike's guide in the doc
2. Modified function Trader.prototype.addOrder in kraken_margin.js


` 
    let reqData = {

    pair: this.pair,

    type: tradeType.toLowerCase(),

    ordertype: 'limit',

    price: price,

    volume: amount.toString(),

    leverage: 5,

    trading_agreement: 'agree'

  };`

So i just needed to add the leverage and trading agreement parameter for the API call to Kraken.

Now it opens a margin long or short position with leverage. Works nicely.

However I still have issues with the trading volume, since gekko sets the portfolio values based on the amount of asset / currency which is different to the margin trade volume of the position.
For now i did hardcode the volume to a fixed value in the same function to make sure that I fully close the position. I know this is very wild style but for now it is ok. I will work on this the next days, to query the ledger and query the open positions to set the proper trading volume.

**Comment by jordanbates** [comment]
@PanoPilot, have you happened to make anymore progress on this? I'd like to implement something like this myself

**Comment by askmike** [comment]
This is an old issue, for people (@jordanbates) stumbling across this:

Gekko right now only supports spot without leverage (meaning plain buying and selling). Margin trading requires a lot more data than Gekko currently tracks, read this for more info: https://forum.gekko.wizb.it/thread-1516-post-57452.html#pid57452
