### ISSUE TITLE
 Error: SQLITE_BUSY: database is locked errno: 5, code: 'SQLITE_BUSY'

### ISSUE THREAD

**Issue by INGUeS** [askmike/gekko#2042]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
i set up the bot nd push start

**Expected result** (what you hoped would happen)
waiting for the first trade to be made

**Actual result** (unexpected outcome)
poup message saying Error: SQLITE_BUSY: database is locked

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
how to make sure the api key is working?

**Comment by shufps** [comment]
You probably have two instances of processes working on the same sqlite database.

Try to stop one.

**Comment by spakombat** [comment]
error: sqlite_busy: database is locked
received error in gekko
help me
