### ISSUE TITLE
Invalid currency balance in backtest

### ISSUE THREAD

**Issue by ghost** [askmike/gekko#2049]
**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)

I have write something to not sell less than my buy price.
But when i backtest my strategy i see some little negative trade.
When i log everything i buy at a price, sell higher and see a negative trade.
I have use 0 for fees.

**Expected result** (what you hoped would happen)

Normaly i will not see negative value for a trade.

**Actual result** (unexpected outcome)

When i backtest i see that : 
I buy 1.33648186 btc at 7669.68 (note currency is 0) : 
{ action: 'buy',
  price: 7669.68,
  portfolio: { asset: 1.33648186, currency: 0, balance: 5000 },
  balance: 10250.374827186199,
  date: moment("2018-02-25T17:00:00.000") }

And the next trade is to sell the 1.33648186 btc at 7673.41 : 
{ action: 'sell',
  price: 7673.41,
  portfolio: { asset: 0, currency: 10250.2455827, balance: 5000 },
  balance: 10250.2455827,
  date: moment("2018-02-25T18:00:00.000") }

After the sell currency is 10250.2455827.
But if you made 1.33648186 * 7673.41 = 10255.373269343
so currency display in the backtest after the sell is different than normaly the real :(
10250.2455827 != 10255.373269343

I don't know if it s the asset which wrong or the currency or a calculation for the profit but something is wrong :(

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Note i have not try it in live mode i hope the live mode is not affect !

**Comment by zappra** [comment]
What are your settings for fees and slippage in the paper trader?

**Comment by ghost** [comment]
feeMaker = 0
feeTaker = 0
feeUsing = 'maker'
slippage = 0.05

**Comment by zappra** [comment]
Yes the difference is down to the slippage, which defaults to 0.05%

10255.37 * 0.0005 is about $5

Think about the values you're using when you're backtesting. In a real trading environment, you'd be very unlikely to make a profit selling at such a small price difference. Even on exchanges with zero maker fees (eg. GDAX) you could expect some serious movement in price while trying to fill limit orders.

**Comment by ghost** [comment]
So the difference is down the slippage thanks @zappra
