### ISSUE TITLE
Feature - Export data in a file to ease strategy optimization

### ISSUE THREAD

**Issue by fjpedrosa** [askmike/gekko#2050]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

*I'm submitting a ...
[ ] bug report
[X] feature request
[ ] question about the decisions made in the repository

*Action taken (what you did)
Since it is interesting to plot the evolution of indicators during the backtest, and as far I see it is something under development at the moment, I would like to know if it is possible to export the data in a .csv or .txt file in order to later get the representation of them (both, data and indicators) using other software such as Matlab or OriginLab. Thanks in advance.

**Comment by thegamecat** [comment]
This is how you can do that. 
http://gekkowarez.com/adding-all-gekko-backtest-tick-data-and-indicators-to-csv/
