### ISSUE TITLE
Gekko on docker - Dictonnected on startup

### ISSUE THREAD

**Issue by btcmusty** [askmike/gekko#2055]
Hello, I am a beginner. I install gekko on my synology (DS218+) in docker. The installation it's ok.
when I open gekko on my webbrowser, I receive this message : " Disconnected
Something happened to either Gekko or the connection. Please check the terminal where Gekko is running or your network connection" 

![image](https://user-images.githubusercontent.com/37767074/37872816-81252fa6-300f-11e8-8114-2dd34ba882d2.png)

I find a lot of solution to modify uiconfig.js but when I search this file in my synology, I find many directory with this file. I do not know which one is the correct one.

Path to this directories is : 
Volume1/@docker/btrfs/subvolumes/b024a91131a66f2b8c6aaf839b49403a112ddf5d22ea7c9384be0762e1fa170d/usr/src/app/web/vue/UIconfig.js

/volume1/@docker/btrfs/subvolumes/38e52b23f5d02c89d67301044f843e71edc6b448dd476cc7776c88d8ca61f0f6/usr/src/app/web/vue/UIconfig.js

/volume1/@docker/btrfs/subvolumes/77b1102fdcf29e96ef8bcb07c37e2ed4aa9a7187e85988cc70cc1edb4920b613/usr/src/app/web/vue/UIconfig.js

Could you help me please :) Thanks 

PS : Sorry for my english

**Comment by wimamp** [comment]
Hi @btcmusty ,

Did you find the solution already? 

I tried all kind of items discussed in other topics and cant get it to work. Lets join in the quest for the answer. Cant find a proper form that helps with, Gekko, Docker and Synology. 

Thanks.

Cheers,
Wim

**Comment by kaydream** [comment]
hi 
i found a solution 
if you use your gekko from external ip you must use your external ip address instead of internal ip address
in your web/vue/dist/UIconfig.js
i hope this will be a solution for you
kaydream

**Comment by askmike** [comment]
> in your web/vue/dist/UIconfig.js

Yep you need this file! I am unfortunately not familiar with synology so I hope that's enough information!
