### ISSUE TITLE
How to run gekko in google cloud VM.

### ISSUE THREAD

**Issue by davidgoen** [askmike/gekko#2056]
I'm trying to start gekko in a google cloud VM but I can not connect to the home page of geko.
I have tried with the configuration indicated at: https://gekko.wizb.it/docs/installation/installing_gekko_on_a_server.html, 

```
const CONFIG = {
    headless: true,
    api: {
        host: '0.0.0.0',
        port: 3000,
    },
    ui: {
        ssl: false,
        host: 'x.x.x.x', // Set this to the IP of the machine that will run Gekko
        port: 3000,
        path: '/'
    },
    adapter: 'sqlite'

}

```
Changing x.x.x.x to the external IP of my GoogleCloud MV, I have also tried to change x.x.x.x with the internal IP of the MV but without positive result.

I've also tried with the configuration of: 
```
const CONFIG = {
    headless: true,
    api: {
        host: '127.0.0.1',
        port: 3000
    },
    ui: {
        ssl: true,
        host: 'gekko.example.com',
        Port: 443
        path: '/' // change this if you are serving from something like `example.com / gekko`
    },
    adapter: 'sqlite'
}
```
but it does not work.

I have also tried to change the routing of the machine so that any incoming request served from localhost but has not yielded any results. What is the solution to this problem?

**Comment by kayahasan** [comment]
Ben de aynı problemi yaşıyorum

**Comment by askmike** [comment]
> without positive result.

What result are you getting? It's hard to help you figure this out without knowing what errors and probelms you encounter. Unfortunately this is the issue tracker and not the best place for installation support, see here for better places: https://gekko.wizb.it/docs/introduction/getting_help.html
