### ISSUE TITLE
Gekko not running, produces the following errors:

### ISSUE THREAD

**Issue by 54zartdtuzu** [askmike/gekko#2058]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Installed nodejs on Windows 7 and then did 'npm install --only=production' within the nodejs/node_modules/npm folder (no errors), then cd'd into the gekko-develop folder (latest version), and tried to launch gekko with 'node gekko --ui'

**Expected result** (what you hoped would happen)
Expected gekko to run

**Actual result** (unexpected outcome)
Gekko did not run, this is what the cmd.exe window showed me (without the browser window to open up):
`C:\Program Files\nodejs\node_modules\npm>npm install --only=production
npm notice created a lockfile as package-lock.json. You should commit this file.
up to date in 2.236s

C:\Program Files\nodejs\node_modules\npm>cd C:\Users\User\gekko-develop

C:\Users\User\gekko-develop>node gekko --ui

_(I removed the startup ascii artwork from this post)_

**module.js:545
    throw err;
    ^**

**Error: Cannot find module 'moment'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\User\gekko-develop\core\util.js:1:76)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)**

C:\Users\User\gekko-develop>`

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by generalectric** [comment]
npm i moment

in your gekko folder. if you have any similar errors its the same just npm i `modulename`

**Comment by 54zartdtuzu** [comment]
@generalectric Ok that made the errors go away. Tried it out with the gekko stable and develop version by the way. With the stable your command didn't solve the problem. With the develop version it did solve a bit of errors.
Doing your command with stable returns this:

C:\Users\User\gekko-stable>npm i moment
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\User\gekko-sta
ble\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\User\gekko-stable
\package.json'
npm WARN gekko-stable No description
npm WARN gekko-stable No repository field.
npm WARN gekko-stable No README data
npm WARN gekko-stable No license field.

+ moment@2.21.0
added 1 package in 3.447s

**Not as usually, it didn't open the browser window. Had to manually enter http://localhost:3000.**

With develop version it returns just the same errors of your command as with the stable. Following problems are from the develop version since I still can't launch the stable version:
 

Also trying to enter an API Key fails: Pushing the button "Add" results in nothing. The button shows the link to http://localhost:3000/# and clicking it does not load the next page, nothing happens. Update: Adding the API key now worked, but it took ages to send me to the next page, which is unusual. Very weird.

**Also the cmd.exe window shows (when I only have a market watcher active) this:**

events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: SQLITE_BUSY: database is locked
Emitted 'error' event at:

events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: SQLITE_BUSY: database is locked
Emitted 'error' event at:

  xxx POST /api/getCandles 500 2,300ms -

  Error: non-error thrown: ERROR, unable to load candles, please check the console.
      at Object.onerror (C:\Users\User\gekko-develop\node_modules\koa\lib\context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:118:7)

  xxx POST /api/getCandles 500 2,278ms -

  Error: non-error thrown: ERROR, unable to load candles, please check the console.
      at Object.onerror (C:\Users\User\gekko-develop\node_modules\koa\lib\context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:118:7)

  <-- POST /api/getCandles
  <-- POST /api/getCandles
  <-- GET /api/configPart/candleWriter
  <-- GET /api/configPart/performanceAnalyzer
  <-- GET /api/strategies
  <-- GET /api/configPart/paperTrader
  --> GET /api/configPart/candleWriter 200 18ms 47b
  --> GET /api/configPart/performanceAnalyzer 200 37ms 144b
  --> GET /api/configPart/paperTrader 200 39ms 132b
  <-- GET /api/configPart/candleWriter
  <-- GET /api/configPart/performanceAnalyzer
  <-- GET /api/strategies
  --> GET /api/configPart/candleWriter 200 8ms 47b
  --> GET /api/configPart/performanceAnalyzer 200 22ms 144b
  <-- POST /api/addApiKey
  --> POST /api/addApiKey 200 11ms 15b
  <-- POST /api/addApiKey
  --> POST /api/addApiKey 200 4ms 15b
  <-- POST /api/addApiKey
  --> POST /api/addApiKey 200 4ms 15b
  <-- GET /api/configPart/paperTrader
  --> GET /api/configPart/paperTrader 200 4ms 132b
  --> GET /api/strategies 200 123ms 2.13kb
  --> GET /api/strategies 200 75ms 2.13kb
  --> POST /api/getCandles 200 1,110ms 13.8kb

 
**When starting a live gekko as a Tradebot, it returns this after some time (refreshing the live-gekkos page just removes the market watcher and leaves the strat running tradebot there):**

  xxx POST /api/getCandles 500 2,041ms -

  Error: non-error thrown: ERROR, unable to load candles, please check the console.
      at Object.onerror (C:\Users\User\gekko-develop\node_modules\koa\lib\context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:118:7)

events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: SQLITE_BUSY: database is locked
Emitted 'error' event at:

RECEIVED ERROR IN GEKKO 18378062576905
Child process has died.

**Restarting gekko and only creating a tradebot without a market watcher instantly results in "Child process has died again, refreshing the page shows no bots active. Sometimes it leaves the automatically added Market Watcher active, and sometimes it kills this process too.**

**Comment by 54zartdtuzu** [comment]
And just now after a few times of trying the strat runner and market watcher stays open.
But the 'SQLITE_BUSY database is locked' errors still are there.
 
This is what is being showed by the cmd.exe window:

 <-- GET /api/imports
 --> GET /api/imports 200 2ms 2b
 <-- GET /api/gekkos
 --> GET /api/gekkos 200 1ms 1.34kb
 <-- GET /api/gekkos
 --> GET /api/gekkos 200 1ms 1.34kb
 <-- GET /api/apiKeys
 --> GET /api/apiKeys 200 2ms 10b
 <-- GET /api/exchanges
 --> GET /api/exchanges 200 12ms 98.9kb
 Error: SQLITE_BUSY: database is locked errno: 5, code: 'SQLITE_BUSY' }
 <-- POST /api/getCandles
 --> POST /api/getCandles 200 590ms 149b
 <-- POST /api/getCandles
 --> POST /api/getCandles 200 570ms 149b
 <-- GET /api/imports
 --> GET /api/imports 200 2ms 2b
 <-- GET /api/gekkos
 --> GET /api/gekkos 200 0ms 1.38kb
 <-- GET /api/gekkos
 --> GET /api/gekkos 200 1ms 1.38kb
 <-- GET /api/apiKeys
 --> GET /api/apiKeys 200 0ms 10b
 <-- GET /api/exchanges
 --> GET /api/exchanges 200 7ms 98.9kb
 <-- POST /api/getCandles
 --> POST /api/getCandles 200 1,055ms 149b
 <-- POST /api/import
Import 3484916824300086 started
 --> POST /api/import 200 30ms 148b
 <-- GET /api/imports
 --> GET /api/imports 200 2ms 183b
 <-- GET /api/gekkos
 --> GET /api/gekkos 200 1ms 1.37kb
 <-- GET /api/gekkos
 --> GET /api/gekkos 200 1ms 1.37kb
 <-- GET /api/apiKeys
 --> GET /api/apiKeys 200 1ms 10b
 <-- GET /api/exchanges
 --> GET /api/exchanges 200 8ms 98.9kb

**Comment by generalectric** [comment]
@54zartdtuzu Sqlite is great for easy out of the box operation of gekko it makes getting up and running a breeze which is why it's the default on a fresh install. BUT it is not the right choice for advanced use (multiple gekkos or parallel backtesting etc) postgresql is highly recommended! Sorry for the late response hope this solves things for you, if so you can close this up.

*edit* also if you're running on windows try changing the journal mode in the sqlite config settings choices are WAL or DEL

*another edit* scratch that I think @cmroche addressed this in a PR... Use postgresql it's best!
