### ISSUE TITLE
how to stop a trader bot (strategy rsi)

### ISSUE THREAD

**Issue by twiiix** [askmike/gekko#2059]
I started a live gekko bot trader and I want to stop it. How to do?

**Comment by CyborgDroid** [comment]
The only way I have found is the command line. You kind of have to know what time you started your "child" worker or at least know the order. So here I wanted to kill the last worker I started which is the trading bot so I picked the one with 00:00 in the time. The other workers can be market watchers, paper traders, etc.

ps -ax | grep node
kill -9 [pid]

example:

```
ubuntu:~$ps -ax | grep node
11888 ?        Ssl    0:01 /home/ubuntu/.nvm/versions/node/v6.11.2/bin/node /home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/forever/bin/monitor /home/ubuntu/gekko-nn/gekko.js
11898 ?        Sl     0:17 /home/ubuntu/.nvm/versions/node/v6.11.2/bin/node /home/ubuntu/gekko-nn/gekko.js --ui
11908 ?        Sl     2:43 /home/ubuntu/.nvm/versions/node/v6.11.2/bin/node /home/ubuntu/gekko-nn/core/workers/pipeline/child
21850 ?        Sl     0:00 /home/ubuntu/.nvm/versions/node/v6.11.2/bin/node /home/ubuntu/gekko-nn/core/workers/pipeline/child
22117 pts/0    S+     0:00 grep --color=auto node
ubuntu:~$ kill -9 21850
```

**Comment by twiiix** [comment]
thx :)

**Comment by rheos** [comment]
I really hope a button for this is added at some point.

**Comment by hilkoc** [comment]
I'd really like to see this fixed and don't mind to code this myself.
Hi @askmike  , could you provide some guidance on what would be the best way to implement this?

**Comment by hilkoc** [comment]
Finally, a working stop button to stop any running gekko; tradebot, marketwatcher or paper trader. If interested feel free to merge in [my branch](https://github.com/hilkoc/gekko/commits/2028-pnl-reporting) .

The UI button was taken from [this pull request](https://github.com/askmike/gekko/pull/1577). I fixed the back-end in the last commit on my branch.

**Comment by askmike** [comment]
- update gekko to 0.6
- click the stop button

:)
