### ISSUE TITLE
Abstracting a talib indicator

### ISSUE THREAD

**Issue by myBytesCom** [askmike/gekko#2061]
Hi askmike,

This is the provided way, we shall go, to implement a ta-lib indicator into our strategies.

```
method.init = function() {
  var customMACDSettings = {
    optInFastPeriod: 10,
    optInSlowPeriod: 21,
    optInSignalPeriod: 9
  }

  // add the indicator to the strategy
  this.addTalibIndicator('mymacd', 'macd', customMACDSettings);
}

method.check = function() {
  // use indicator results
  var result = this.talibIndicators.mymacd.result;
  var macddiff = result['outMACD'] - result['outMACDSignal'];

  // do something with macdiff
}
```

is there a possibility to outsource this to a subfolder in `gekko/strategies/indicators/somehow/`
that way, that in `method.init = function () ` the indicator can be involved by including or callbacking the file. 
This could clean up my code a lot, because I need to do some computation to several ta-lib indicators
and would like to have the resultdata in `method.check = function(candle)` that way,
that a new element  in `candle` can collect the results or anyhow.

Like this:
```
candle.mytalibresults=[]
candle.mytalibresults.push({"indicatorname": result})
```
Can this be done in a separate file for each indicator, this would be a solution which makes it easier to understand and maintain the code afterwards.
 
I need an array of objects with all the results at the time of the actual candle in `method.check = function(candle)` to get the idea to work.

If I use 10 or more ta-lib indicators and do this in a strategy file, it will become a very long file and a desaster ;-)

Any hint for me how to do this would help a lot, without breaking the architecture and doing it best way?

Kind regards

`

**Comment by askmike** [comment]
Keep in mind that usually these lines:

    var customMACDSettings = {
      optInFastPeriod: 10,
      optInSlowPeriod: 21,
      optInSignalPeriod: 9
    }

you'd usually already outsource to a config file (such as a TOML file if you are using the UI). So what you are left with is 3 lines in your strategy: one to register the indicator (don't see a way around this one) and 2 to parse the results.

> I need an array of objects with all the results at the time of the actual candle in method.check = function(candle) to get the idea to work.

If you want we can also expose the last x (such as 10) results of your indicator in an array, such that `this.talibIndicators.mymacd.results;` is an array with the last 10 values.

But before we implement that, can you tell me more about why you need the last X values?
