### ISSUE TITLE
MarketWatcher use imported data for warmup period?

### ISSUE THREAD

**Issue by jamieishere** [askmike/gekko#2065]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ ] bug report

**Action taken** (what you did)
Set Gekko running.

**Expected result** (what you hoped would happen)
Would use my imported (Bitfinex) data for warmup period & thus 'immediately' (as soon as a trading signal occurred) send me alerts.

**Actual result** (unexpected outcome)
Warmup period did not appear to use imported data (for all time periods, it took the minimum number of candles set as 'requiredHistory' before advice was 'sent' (email & slack)) - for the daily charts, if we needed 20 candles, that's 20 days. Not so useful! Presumably, I'm doing something wrong?
Note - I amended our strategy to set requiredHistory to 0 (as we populate a candlearray in the strategy and don't send advice until that array is a set number of bars (so any non-0 value for requiredHistory just increased the number of bars).... could this be why it's not using imported data? Do we need to refactor the strategy? 

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by ripley** [comment]
Looks like this issue still persists ...
I tried to import very recent data for BSV/USD in bitfinex, it's finished sucessfully as:
https://farm5.staticflickr.com/4904/31033103017_e18fbf0a8e_b.jpg
But in the startrunner page, it's still saying:
https://farm5.staticflickr.com/4835/32101001888_c40740d0da_b.jpg

The downloaded history data were not used for warm up somehow.
