### ISSUE TITLE
Vastly Different Backtesting Results

### ISSUE THREAD

**Issue by 0xPBIT** [askmike/gekko#2068]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Used various date range start times varying by only a few seconds at a time.

**Expected result** (what you hoped would happen)
Backtesting profits would be very close considering start time is being offset by only a few seconds

**Actual result** (unexpected outcome)
High amounts of variance in backtesting profits. Incrementing the backtesting range by one second can make the difference for profit or loss

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by generalectric** [comment]
Possibly same issue as #1254

**Comment by 0xPBIT** [comment]
@generalectric Are there any solutions to the problem I'm experiencing? All the threads related to the tagged issue have been dead for more than 4 months. I remember reading something awhile back about having start and end times match candle intervals, but I can't find anything.

**Comment by askmike** [comment]
Please provide information so we can reproduce, I have no clue how to even answer this question. Information such as: your strategy, your indicators, your settings, your gekko version, your system (os), your adapter, how you are running the backtest, etc.

**Comment by askmike** [comment]
We can reopen as soon as we have some information so anyone else can reproduce :)

**Comment by generalectric** [comment]
@askmike to reproduce pick any strat in the gekko strategies folder and set the start TIME in daterange object... I believe that's what he is saying exactly though I haven't tested it I have a 12 hour drive back home today. @prestonbrown there was an issue I saw recently about candle start times... Also probably related to this I'll have to get back to a computer after my drive to dig for it. Possible solution?? Make start time seconds hard coded?

**Comment by 0xPBIT** [comment]
Confused why this was closed.

Backtest any strategy with a specific date range. Then increase the start time by one second. You should have totally different bactesting results. 

I don’t know what other info you could need. I think the issue comes from candles being processed relative to the start time rather than some other absolute time.

**Comment by 0xPBIT** [comment]
For me this is a cause of concern for the start time of a live trader. Will my results also be impacted so greatly with such a minuscule change in start time?

I’ll be testing this with paper traders shortly.

**Comment by 0xPBIT** [comment]
Were you able to reproduce the error?
