### ISSUE TITLE
Candle size units in config.js

### ISSUE THREAD

**Issue by Kralg** [askmike/gekko#2072]
**I'm submitting a ...**
[ ] bug report
[x] question about the decisions made in the repository

**Action taken** (what you did)
Checked the sample-config.js

**Expected result** (what you hoped would happen)
Description of what are the units of candle size

**Actual result** (unexpected outcome)
No description

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

I was trying to setup config.js file, there is candleSize parameter but it is unclear what are the units, is it minutes?

**Comment by H256** [comment]
Candlesize is measured in minutes. If you work with the UI, gekko parses hours and days to minutes as well ;)

**Comment by Kralg** [comment]
I see, thanks :)
