### ISSUE TITLE
BUY/SELL buttons from UI

### ISSUE THREAD

**Issue by ghost** [askmike/gekko#2074]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a 
Feature Request

Hi, if anyone knows how to add buy/sell buttons from the web ui that would be great - although strategies can be developed to eliminate the need for these - it would be nice to be able to manually have the bot buy/sell based on some personal TA.
I took a look and didn't see any API endpoints that allows access to this ability.
Thanks!

**Comment by ansonphong** [comment]
I like this idea, although it would take some development of the concept of "bot augmented trading" which I would very much like to see possible with Gekko.

Along with this I suggest a method to detect if a buy order was filled on the given pair manually on the exchange. This would mean you could manually buy and sell on the exchange and the bot would continue to execute your strategy based on your actual current position.
