### ISSUE TITLE
tulind and talib available with docker and not with node.

### ISSUE THREAD

**Issue by twiiix** [askmike/gekko#2075]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)

**Expected result** (what you hoped would happen)

**Actual result** (unexpected outcome)

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

hello .
As said in the title ..

**Comment by 0xPBIT** [comment]
Not a lot of info here. Have you installed the packages with npm yet?

**Comment by ericterpstra** [comment]
@twiiix What happens when you run `npm install talib tulind` in your gekko folder?
