### ISSUE TITLE
Resume Watchers and Strategies after docker restart

### ISSUE THREAD

**Issue by ghost** [askmike/gekko#2076]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x] bug report
[x] question about the decisions made in the repository

**Action taken** (what you did)
installed docker
runs fine

**Expected result** (what you hoped would happen)
after docker restart - resume strat runners / Live gekkos

**Actual result** (unexpected outcome)
after docker restart gekko doesnt resume watchers and strategies

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by xFFFFF** [comment]
Gekko havent 'resume' feature. All strat runners data is gone after stop. I recommend using CLI instead UI - with one command You are back to game.
