### ISSUE TITLE
FR to have access to the price at which gekko completes a buy/sell order

### ISSUE THREAD

**Issue by ghost** [askmike/gekko#2082]
**I'm submitting a
Feature Request

Hello,
During my time with strategy development - I haven't seem to have found a way to return the final price at which an order was completed from within the strategy code. I need this functionality when working with smallcap coins that take a long time to get buy/sell orders through.

For example - I tell gekko to short at a candle close price of 2. Gekko actually gets the order through at a price of 1.8 (or in some cases we would need to average the price at which the final amount was completely sold). From the strategy code this would be nice when working with percentage gain and for stop/loss features.
Thanks for your time :)

**Comment by 0xPBIT** [comment]
I've been trying to figure this out too. I'd like to make a stop loss that acts on the price at purchase rather than trying to calculate it.

**Comment by nichdiekuh** [comment]
You have to use the onTrade callback to get the price and action (buy/sell). 

Look at this strategy, it's a good example for using the onTrade function:
https://github.com/SirTificate/gekko-neuralnet/blob/master/strategies/neuralnet.js

**Comment by 0xPBIT** [comment]
@nichdiekuh Awesome thanks a ton for this.
