### ISSUE TITLE
Reference Error -> minimum is undefined (trader crashes)

### ISSUE THREAD

**Issue by H256** [askmike/gekko#2083]
**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
From command-line
Start live trading @bitstamp using current develop version (incl. new Trade-Class)

**Expected result** (what you hoped would happen)
It trades...

**Actual result** (unexpected outcome)
Errormessage and process crashes.
```
C:\gekko\plugins\trader\trade.js:310
      return minimum = this.minimalOrder.amount / price;
                     ^

ReferenceError: minimum is not defined
    at Trade.getMinimum (C:\gekko\plugins\trader\trade.js:310:22)
    at Trade.buy (C:\gekko\plugins\trader\trade.js:140:22)
    at act (C:\gekko\plugins\trader\trade.js:83:18)
    at C:\gekko\node_modules\async\dist\async.js:3853:9
    at C:\gekko\node_modules\async\dist\async.js:484:16
    at replenish (C:\gekko\node_modules\async\dist\async.js:1025:25)
    at iterateeCallback (C:\gekko\node_modules\async\dist\async.js:1015:17)
    at C:\gekko\node_modules\async\dist\async.js:988:16
    at C:\gekko\node_modules\async\dist\async.js:3850:13
    at apply (C:\gekko\node_modules\async\dist\async.js:41:25)
```

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
This seems to happen on the first advice, the trader gets (regardless of being a short/long).
It happened only at BitStamp so far, I have other instances running where no crash occured.

I have also tried it with a fresh clone of the repo - the result is the same.

**Comment by askmike** [comment]
ah nice catch! ping @ansonphong

**Comment by dmuzizian** [comment]
Error. How to FIX? i'm using BITTREX ... BTC-DOGE
![screenshot_1](https://user-images.githubusercontent.com/15715474/38730717-d7492662-3f41-11e8-9887-ee9d1e88b197.png)

**Comment by H256** [comment]
@dmuzizian I have just temporarily altered the line to this: 
`return this.minimalOrder.amount`
This seems to work.

**Comment by dmuzizian** [comment]
where i can find this line ? @H256

**Comment by H256** [comment]
The first line of the error states the path, which in your case would be `/root/gekko/plugins/trader/`. in the file, the line number to change in the file trade.js would be line 312 ;)

**Comment by dmuzizian** [comment]
like this ?

`  getMinimum(price) {`
`    if(this.minimalOrder.unit === 'currency')`
`      return minimum = this.minimalOrder.amount / price;`
`    else`
**`      return minimum = return this.minimalOrder.amount;`**
`  }`

**Comment by H256** [comment]
```
getMinimum(price) {
if(this.minimalOrder.unit === 'currency')
return  this.minimalOrder.amount / price;
else
return this.minimalOrder.amount;
}
```
should do ;)

**Comment by wizmanza** [comment]
workaround worked for me....Thanks!

**Comment by askmike** [comment]
Please download the latest develop, this has been fixed on that branch already.
