### ISSUE TITLE
Bestone parameters

### ISSUE THREAD

**Issue by DevCode01** [askmike/gekko#2084]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ ] bug report
[x ] question about the decisions made in the repository

**Action taken** (what you did)
Hi, I new on this platform and I need some advice. 
Recently, I was downloaded Gekko on my Mac. I find a strategy entitled Bestone.
I'm lost when I see the different parameters and I need to see different examples to understand who used the Bestone strategy.

**Actual result** (unexpected outcome)
I tried to test with different parameters  : 
![capture d ecran 2018-04-04 a 19 31 51](https://user-images.githubusercontent.com/36292698/38323876-d7d66a7c-383e-11e8-8a27-095f290593ad.png)
![capture d ecran 2018-04-04 a 19 31 55](https://user-images.githubusercontent.com/36292698/38323883-db514cd0-383e-11e8-8391-430b704faa3b.png)

I use the platform entitled Binance (ETH / XRP) during 14 days.
And the results do not match my expectations.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Sorry for my vocabulary, I'm a teen French and I have lot of difficulties to wrote English.
Thank you in advance

**Comment by 0xPBIT** [comment]
You should learn how the strategies and indicators work, and how to derive a long or short action from them. These strategies use technical analysis methods for this kind of decision making. You can use the preexisting ones, or you can write your own strategy and backtest it with the tool. There are more discussions based around strategy development on the forum. 

https://forum.gekko.wizb.it

**Comment by xFFFFF** [comment]
The way described by phbprogramming is the best to have full control over what is happening. However, without such knowledge you can use Gekko with successes.

To find the best strategy parameters, I recommend: https://github.com/Gab0/japonicus
You do not need to know what MACD means, for example, to use Japonicus.

Examples of different strategies can be found on my repo: https://github.com/xFFFFF/Gekko-Strategies
All of them working/trade without parameter change.
