### ISSUE TITLE
binance.js error 500

### ISSUE THREAD

**Issue by twiiix** [askmike/gekko#2085]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository
![error](https://user-images.githubusercontent.com/22472519/38352275-f5c1a6cc-38b2-11e8-8aad-f7312f995d30.png)

Error with binance.js

**Comment by askmike** [comment]
Can you try to download the latest develop branch and run it again? Thanks!

**Comment by twiiix** [comment]
ok mike i try when i have a moment.. thx for your reply.. nice day man.

Le jeu. 5 avr. 2018 à 11:33, Mike van Rossum <notifications@github.com> a
écrit :
