### ISSUE TITLE
binance: event not emit after a trade occure

### ISSUE THREAD

**Issue by ghost** [askmike/gekko#2086]
**I'm submitting a ...**
[ x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)

I use the most recent version of develop branch of gekko live.
gekko has buy but when i have wake up i have see than bought price was not set at all.

**Expected result** (what you hoped would happen)

I was expecting when a trade occure event, event.action, event.portfolio['asset'] and event.price was set but event has not be emit.

**Actual result** (unexpected outcome)

event has not be emit after a buy order :( 

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

In my start i use this : 
strat.onTrade = function(event) {
  switch (event.action) {
    case 'buy': {
      console.log(event);
      this.boughtPrice = event.price;
    }
    case 'sell': {
      console.log(event);
      this.soldPrice = event.price;
    }
  }
}

When the buy order has been filled event has not be emit because this.boughtPrice has not be set at all.
The same code was working well on bitfinex but not on binance :( 
Please make a fix i cannot trade anymore.

**Comment by ghost** [comment]
Note that i have the last version with the last update of gekko.
For me event has not be emit but for a friend who has not the last upgrade but his gekko is on develop branch but with not the last upgrade event has been emit.
We use same strategy and same exchange binance so i don't know if it s the last change or if it s happen sometime and this time it s has work for my friend.
A fix will be great because i really need event.price !

**Comment by ansonphong** [comment]
@askmike This may have been a result of my PR for the Trade Class, can you verify that the emit event is configured properly?

**Comment by H256** [comment]
I'm experiencing the same problem even without #1968 . The Adviser advises to go 'short' as the first trade. After that no other trades are executed, even though there were plenty of chances to go 'long'. (tried with bitstamp and binance) Maybe something else is wrong with the event :(

**Comment by ghost** [comment]
i have not use last upgrade by doing:
git checkout 07a4d67892cc5a956b4c333f0428a6cc2d7b4e44
and on the 2 last trade i have made event.price was set ...
