### ISSUE TITLE
Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by Abrelaboca-zz** [askmike/gekko#2091]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
A copy of any example strats.

**Expected result** (what you hoped would happen)
Running bot.

**Actual result** (unexpected outcome)
![capture](https://user-images.githubusercontent.com/9082490/38460050-95dd5768-3ab2-11e8-988b-d1bccce78b8d.PNG)

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by xFFFFF** [comment]
Have You correct config strat's file in config/strategies? File name must be this same like .js file. And notice if the extension of the configuration file is .toml. Often when downloading from Github, the browser saves this file as .txt

EDIT
Try change strat's file name to something without '+' or '-'.

**Comment by Abrelaboca-zz** [comment]
Yep, I copied them directly from the strategies folder, same happens for any custom strat.

**Comment by Abrelaboca-zz** [comment]
For some reason everything is working fine now, whatev.
