### ISSUE TITLE
Is it possible to use market order by editing source code?

### ISSUE THREAD

**Issue by nwhnbg** [askmike/gekko#2094]
Hello. I’m very new to the gekko.
l realized that the gekko doest’t have market order function; Only limited order is possible on the gekko.
I think this is really big weakness point among other bots.
Is it possible to use market order by editing source code?
Plus, is there any plan to apply market order function someday? Thanks.

**Comment by weeder** [comment]
For binance is possible to change to MARKET order.
in /gekko/exchanges/binance.js line 237-238 change to following:
type: 'MARKET',
//    timeInForce: 'GTC', // Good to cancel (I think, not really covered in docs, but is default)
Idk about other exchanges
