### ISSUE TITLE
Genetic Algorithm implementation failure

### ISSUE THREAD

**Issue by nwhnbg** [askmike/gekko#2097]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ ] bug report
[V] question about the decisions made in the repository

**Action taken** (what you did)
root@DESKTOP:~/gekko/web# node max-old-space-size=8192 server.js

**Expected result** (what you hoped would happen)
Success of Genetic algorithm implementation

**Actual result** (unexpected outcome)
module.js:549
    throw err;
    ^
Error: Cannot find module '/root/gekko/web/?max-old-space-size=8192'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
---------------------------------------------------------
I am following the GA(Genetic Algorithm) instruction to implement it.
I typed following command at the gekko/web/ folder.
node –max-old-space-size=8192 server.js
But I have the error message.
How can I solve this problem? Please help me.

**Comment by xFFFFF** [comment]
You are ran command without `--` before `max-old-space`. For gekkoga I use `node gekko --ui` instead Your command and all is working fine.

**Comment by nwhnbg** [comment]
@xFFFFF Many thax!
