### ISSUE TITLE
I'm submitting a bug report concerning an error in Gekko 

### ISSUE THREAD

**Issue by Spliffymushroom** [askmike/gekko#2098]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ ] bug report
Child process has died.

**Action taken** strategy RSI exchange Binance, Parameters 
{
    "interval": 2,
    "thresholds": {
        "low": 30,
        "high": 70,
        "persistence": 3
    }
}

**Expected result** some dank trades 

**Actual result** throw er; // Unhandled 'error' event

**Comment by SirTificate** [comment]
Try running your strat in cli (backtesting) mode to see the the exact error message. Gekko UI spawns the strat runner as child processes and can't capture the error output atm. So the error message you provided won't help to track down the issue at all.
