### ISSUE TITLE
Fetch data appears from the future

### ISSUE THREAD

**Issue by cimm** [askmike/gekko#210]
I am trying to get gekko running but can't get past the initial database building.

I start gekko and it runs for a few hours or even a day before it crashes with the following error:

`FATAL: Fetch data appears from the future, don't know how to process`

The node process hangs after this and I have to manually restart it. A few hours later it runs into the same problem.

I never got past this point and have no idea how to get around this. I have gekko configured to use Kraken.

I am thinking Kraken might send trades with a date that is a few seconds ahead of my system clock or there might be some timezone mix up here?

**Comment by r1979** [comment]
Hi Mike! Thanks your work so far! Any news/developments on the Kraken side?

**Comment by donttrustem** [comment]
Hi Mike,
Is there any update on this issue?

Thanks

**Comment by albuckley** [comment]
bump

+1 year...

**Comment by n4ru** [comment]
+1

**Comment by niklasrichardson** [comment]
+1 bump!

**Comment by beinbruch** [comment]
+1. Any news?

**Comment by askmike** [comment]
fixed in 0.2.
