### ISSUE TITLE
Gekko Live Trade Run (success Buy and Sell), But no showing indicator on Gekko UI (v0.5.14 and Gekko UI v0.2.0.)

### ISSUE THREAD

**Issue by dmuzizian** [askmike/gekko#2107]
Succes order on Poloniex Market, this also happens when i'm using other markets (binance, bittrex)

![1](https://user-images.githubusercontent.com/15715474/38787966-674e5e9c-415b-11e8-888b-4280527d442e.png)

But....

![2](https://user-images.githubusercontent.com/15715474/38788013-9697ba2c-415b-11e8-904c-360094d9ee9f.png)

![3](https://user-images.githubusercontent.com/15715474/38788018-9ea1825c-415b-11e8-9ac2-bbc21295b8af.png)

please help me to fix this Bug!....thanks before

**Comment by deadheadtn** [comment]
Same here but on binance

**Comment by ghost** [comment]
same here

**Comment by aheadzen** [comment]
Same here on Bittrex, but Binance seems to be working fine.

**Comment by deadheadtn** [comment]
@aheadzen which version please ?

**Comment by ghost** [comment]
Same here on Gekko v0.5.13 and Gekko UI v0.2.0.

Raspberry Pi2
Linux raspberrypi 4.14.34-v7+ #1110 SMP Mon Apr 16 15:18:51 BST 2018 armv7l GNU/Linux

It trades but the webui never shows any trades.

poloniex
kraken
bitstamp

**Comment by aheadzen** [comment]
Gekko v0.5.14 and Gekko UI v0.2.0.

My best guess is that price values get screwed up somewhere and gekko plots them off the charts.

**Comment by ghost** [comment]
I wish I could look for more logs.

Reboot, start gekko with and without sudo.. now i just leave it on and it still trades.

I use "cat /gekko/logs/ * trade * " to look for any changes.

**Comment by ghost** [comment]
Could it be folder permission?

Something is not allowed to write/log?

**Comment by homer12d** [comment]
Same bug with Bitstamp... I can monitor what gekko does through the log but I can't really visualize profits/losses (it's been running for more than 2 days and already has done a few trades)

**Comment by H256** [comment]
Same problem here on the current dev-branch. Binance and Bitstamp - both are logging OK, but the gui doesn't catch any changes.

**Comment by ghost** [comment]
Weeks now with trading.

UI still empty.

**Comment by zgwenwen** [comment]
Same here on Quadriga

**Comment by ghost** [comment]
Same with Kraken

**Comment by nicolasbonnici** [comment]
Same behavior here using Gekko v0.5.14 and Gekko UI v0.2.0 on Binance exchange.

**Comment by hilkoc** [comment]
Same here. Also with paper trading. @askmike  Any idea what the cause is or how to fix it?

**Comment by askmike** [comment]
This specific bug in 0.5 was fixed. Please use the new 0.6.

@hilkoc please open a new issue since it is cocerning 0.6 and post logs!
