### ISSUE TITLE
Bittrex - MIN_TRADE_REQUIREMENT_NOT_MET

### ISSUE THREAD

**Issue by aheadzen** [askmike/gekko#2109]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[X] bug report
[ ] question about the decisions made in the repository

**Action taken**
Bittrex tradebot

**Expected result** (what you hoped would happen)
Have good balance on account. Bot should respect exchange min. trade requirements. Bot should make limited number of API calls to prevent account suspension.

**Actual result** (unexpected outcome)

5000+ such errors

> 2018-04-18 06:15:33 (DEBUG):	Bittrex returned an error, retrying. [ 1.8586006821659593, 0.25696799, [Function: bound] ]
> 2018-04-18 06:15:43 (DEBUG):	buy called { amount: 1.8586006821659593, price: 0.25696799 }
> 2018-04-18 06:15:43 (ERROR):	unable to buy: { err: 
>    { success: false,
>      message: 'MIN_TRADE_REQUIREMENT_NOT_MET',
>      result: null },
>   result: null }
> 

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by aheadzen** [comment]
I believe adding this to buy function within bittrex.js file will fix it? -

```
else if (err && err.message === 'MIN_TRADE_REQUIREMENT_NOT_MET') {
        callback(null, 'dummyOrderId');
        return;
      }
```

**Comment by austinlangdon** [comment]
I have an open PR for this #1486

**Comment by aheadzen** [comment]
@askmike commented this on the fix, so perhaps above isn't the solution -

> would mind calling the callback function with the error here? Else Gekko never completes tracking the order.

**Comment by GO1984** [comment]
any news to this?

**Comment by mxiia** [comment]
I am still having this issue on 9.5.1... any news?

**Comment by askmike** [comment]
I have done a massive upgrade to the trader, see #2216. It's almost ready
for primetime but as of now it does not include bittrex, will add that asap!
