### ISSUE TITLE
gekko live windows eror

### ISSUE THREAD

**Issue by asemaniko** [askmike/gekko#2113]
C:\Users\----\OneDrive\Desktop\gekko\gekko\plugins\trader\trade.js:312
      return minimum = this.minimalOrder.amount;
                     ^

ReferenceError: minimum is not defined

note: ubuntu no problem

**Comment by H256** [comment]
see here https://github.com/askmike/gekko/pull/2108  and here https://github.com/askmike/gekko/issues/2083 - maybe this fixes it ;)
