### ISSUE TITLE
Invalid options for Gemini exchange assets -- ETC instead of ETH

### ISSUE THREAD

**Issue by 151henry151** [askmike/gekko#2115]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Chose USD as currency and ETC as asset option, instead of ETH

**Expected result** (what you hoped would happen)
Expected to have ETH as an asset option, because Gemini has USD/BTC, USD/ETH, and BTC/ETH pairs

**Actual result** (unexpected outcome)
Saw only USD/BTC, USD/ETC, and BTC/ETH pairs, no USD/ETH pair

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
This was in "live gekkos" when trying to set up a market watcher.

**Comment by 0xPBIT** [comment]
Just noticed I have the same issue. Looking for a quick fix and will update if I can figure out a solution.

**Comment by askmike** [comment]
fixed in #2124.
