### ISSUE TITLE
[kraken.js] minimum is not defined

### ISSUE THREAD

**Issue by simpsus** [askmike/gekko#2116]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[X] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
launched a trade bot with kraken

**Expected result** (what you hoped would happen)
trades

**Actual result** (unexpected outcome)
gekko console output:

Gekko encountered an error and can't continue

Gekko encountered an error and can't continue

Error:

[kraken.js] minimum is not defined

Meta debug info:

Gekko version: v0.5.14
Nodejs version: v6.14.1

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by dreammaker** [comment]
Does this fix your issue?  #2108

**Comment by simpsus** [comment]
thx for the hint. Have patched the file manually. I need to run a bot and wait a trade to test it. will report back

**Comment by MysticSands** [comment]
Hey, did you ever get this problem fixed?
If so, what did you do?

I'm new to Gekko and don't know much about coding.  I can probably implement code fixes that I search for if I know where to do it.  If you don't mind, can you answer these for me if you've figured it out?

1.  How do I get to where I need to go to implement code changes?
2.  Less importantly - Do you know how to constantly have gekko set limit buy and sell orders...for example, buy or sell at 10% change from the current price at all times?  If so, how?  What strategy?

Thanks!  I really appreciate it!

**Comment by askmike** [comment]
Fixed in 0.6!
