### ISSUE TITLE
[Suggestion] Use Stale bot to close inactive issues

### ISSUE THREAD

**Issue by kifirkin** [askmike/gekko#2127]
I think it would be nice to use [Stale Bot](https://github.com/apps/stale) to close inactive issues to force people rethink them

**Comment by askmike** [comment]
great idea! (as proven by this issue) it's hard for me to manage this issue tracker.

**Comment by kifirkin** [comment]
@askmike Yeah! it works perfect, if people subscribed to notifications for their issues. Also it would be awesome to add "Good first issue" label, for simple issues that could be resolved by newcomers.

**Comment by askmike** [comment]
Added it! Let's see what happens!

> Also it would be awesome to add "Good first issue" label,

I will add this one, I already have "help-wanted" and "open-for-pulls", but the more we can do to help new comers the better :)

**Comment by kifirkin** [comment]
👍 nice @askmike!

already see some good activity from `stale bot` 😄

**Comment by askmike** [comment]
The unfortunate consequence is that everyone who is watching the repo will get hundreds of notifications (now and maybe in 7 days when they all get closed as well?)
