### ISSUE TITLE
Is Gekko able to run in sell only mode?

### ISSUE THREAD

**Issue by CryptowithDylan** [askmike/gekko#2129]
Just wondering is Gekko able to run in Sell only mode?

**Comment by stereohelix** [comment]
If your strategy never says
`this.advice('long');`
gekko will never buy.

Is this what you mean by sell only mode?

**Comment by CryptowithDylan** [comment]
yes as in i would just want it to sell what i have in the exchange at a percent gain

**Comment by stereohelix** [comment]
Assuming you'd be using some other method to buy what you have in the exchange, gekko would not normally not be able automate this. 

You could set it to sell what you have when the ticker goes over a particular price, but there's no advantage to this over just setting a limit order, as far as I can see.

**Comment by askmike** [comment]
I am assuming this is answered, if not please reply :)
