### ISSUE TITLE
Is the trader still working with GDAX?

### ISSUE THREAD

**Issue by YEMEAC** [askmike/gekko#2136]
updated the repose (last time was in January) to the last release and I don't see GDAX in the select list. Went to an older release and it appears but is not able to load data

**Comment by Gatherer2154** [comment]
It seems that the current Branch: develop gdax.js file isn't compatible with Gekko V0.5.14. I am rather new to coding. So I am not sure where the error happens in the gdax.js file. I did find a work around by changing the Branch: develop gdax.js to the Branch:stable gdax.js I am also new to gekko so I dont know if this work around works for live trading. I havent used gekko to trade yet. Though it will work for market watch , importer, and backtesting.

**Comment by H256** [comment]
gdax still works in the current development branch - at least when you import your data via commandline.
It should work from the UI as well, if yout fix the exchange-file beforehand. The file from this commit should do the job:
https://github.com/askmike/gekko/pull/2126/commits/99fe185015503f2d9957a48f9a01dbb6580e3f71

**Comment by TellCraig** [comment]
It's not that it does not work. In the latest Gekko download it does not even show up in the list of exchanges as an option on the UI.

**Comment by H256** [comment]
Yes, it doesn't show up because there's a missing quotaion mark in the exchange file. After it is added, everything works again. @askmike do you mind merging #2126 , so that gdax works again? ;)

**Comment by TellCraig** [comment]
Thanks! Your my Hero!

**Comment by askmike** [comment]
fixed!

**Comment by YEMEAC** [comment]
thank you!
