### ISSUE TITLE
Does the gekko get a new ask/bid price when placing an order?

### ISSUE THREAD

**Issue by xFFFFF** [askmike/gekko#2141]
I'm asking because I'm thinking how I've calibrated tickrate well. If gekko make a new order to exchange or use a cancel & retry order, gets a new ask / bid price from exchange or uses the one that was downloaded when downloading the last tick?

In other words: if I use candlesize 10 minutes, orderDelay = 20 seconds I can set tickrate 600 seconds and it will work good? If not, does setting: candlesize 10 minutes, orderDelay = 20 seconds, tickrate 20 seconds will work well?

**Comment by xFFFFF** [comment]
@askmike You should know it :) heeelp! :)

**Comment by askmike** [comment]
Answered these questions in #2194!
