### ISSUE TITLE
Need help please Streategy

### ISSUE THREAD

**Issue by Shahid7001** [askmike/gekko#2142]
Hello i am new to this plateform and dont know much i need to ask a question i.e can we create a strategy in whic the Gekko follows the trend downward trend and see if its going down and let it go when the prices starts to rise it will buy it and when the prices goes up it will moniter it and when they starts to fall and is greater then our buy it should sell it??

**Comment by askmike** [comment]
Hey, this is the bug tracker, please see here what a good place is to ask these kind of questions: https://gekko.wizb.it/docs/introduction/getting_help.html
