### ISSUE TITLE
sell if price>x or sell if price<y

### ISSUE THREAD

**Issue by MoneyNeverSleeps** [askmike/gekko#2144]
I know a minimal amount of coding and I'm basically trying to set up simultaneous stop loss and take profit orders. So for example, if the price of BTC becomes higher than 9500 USDT, I want to market sell my BTC position. Likewise, if it drops to below 8500, I also wanna sell it at market price as well. I want to keep my position as long as the price stays in this range. The below code I attempted to use gives the 'child process has dies' error. What's wrong with it? Can somebody help?

var strat = {};

// Prepare everything our strat needs
strat.init = function() {
  // setting take profit price
  this.proPrice = 9500;

  // setting stop loss price
  this.losPrice = 8500;
}

strat.check = function(candle) {
    if(candle.close <= this.losPrice) {
        this.advice(“short”);
        return;
    }
    if(candle.close >= this.proPrice) {
        this.advice(“short”);
        return;
    }
}

module.exports = strat;

**Comment by B41LSY** [comment]
There's an example strategy that does just what you want on the gekko document pages

https://gekko.wizb.it/docs/strategies/creating_a_strategy.html

**Comment by MoneyNeverSleeps** [comment]
Yes, I know. I tried to modify that example strategy to sell when price rises or sell when price falls. That’s how I ended up with the code above. But I get an error for some reason. The example strategy buys when price falls instead of selling. That’s not quite what I want.

**Comment by B41LSY** [comment]
What's the error message? This kind of question is best asked on the forum.

**Comment by MoneyNeverSleeps** [comment]
‘child process has died’ is the error. I posted it on the forum yesterday. no replies yet

**Comment by B41LSY** [comment]
If you download the strategies from https://github.com/xFFFFF/Gekko-Strategies/blob/master/README.md

There's a buyatsellat strategy included in the zip file

**Comment by MoneyNeverSleeps** [comment]
https://forum.gekko.wizb.it/thread-57049.html   —> link of my post

**Comment by B41LSY** [comment]
Above that on the cli it should say what's causing the child process to die?

**Comment by B41LSY** [comment]
I tried to comment on that but my account hasn't been verified so I can't reply

**Comment by MoneyNeverSleeps** [comment]
i will try the code from the strategies link, thank you. I try to set up the strategy on the website. There, it doesnt specify the source of the error.

**Comment by B41LSY** [comment]
I'm just a very beginner at coding and from what I can remember I couldn't get that file to work either.
The strategy in the folder is slightly more advanced than just buyat-sellat but it's easy enough to follow.

**Comment by askmike** [comment]
Closing this out of inactivity.
