### ISSUE TITLE
Is it possible to combine strategies within current code base?

### ISSUE THREAD

**Issue by freezepro** [askmike/gekko#2145]
I would like to try to add strategies such as StochRSI and Bollinger combined. Is it doable within your code base, also question is it possible to implement Bollinger Bands without slight modification of code base?

**Comment by B41LSY** [comment]
Yes it is possible, check here for some strategies that includes a "BBRSI" strategy I'm sure. If that's not exactly what you're looking for it will give you an idea of how to combine strats. (https://github.com/xFFFFF/Gekko-Strategies/blob/master/README.md)

Note, I hope it's ok to provide links on here. Link above isn't mine.

Oh and this kind of question would be better asked on the forum pages?

**Comment by askmike** [comment]
> Oh and this kind of question would be better asked on the forum pages?

Yes it is. Note that you have to glue strategies together yourself. An easier approach would be to create one strategy with multiple indicators. Here is a video where I go over that: https://youtu.be/6-74ZhrG0BE
