### ISSUE TITLE
Re-read .toml File

### ISSUE THREAD

**Issue by imayen** [askmike/gekko#2148]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[] bug report
[X] question about the decisions made in the repository

**Action taken** (what you did)
I would like gekko to re-read the .toml files after candle function run.  Would this be possible? if so, which file would i have to edit?

**Expected result** (what you hoped would happen)
This would allow more control over the decision made and maybe even make it possible for new functions. 

**Actual result** (unexpected outcome)

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
The biggest problem with this is that you can't tell much about the results after running it for a month if the config changed 100 times and nobody knows when exactly. That means it's impossible to reproduce the exact trading signals (or study them). So: if you want to change the config unfortunately you need to restart Gekko!
