### ISSUE TITLE
Anyone have a simple Buy/Sell % Strategy?  

### ISSUE THREAD

**Issue by MysticSands** [askmike/gekko#2151]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
INSTALLED GEKKO

**Expected result** (what you hoped would happen)
TRADE VERY SIMPLY

**Actual result** (unexpected outcome)
GREAT PROGRAM....BUT I CANT FIND A SIMPLE BUY/SELL STRATEGY

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

I JUST WANT TO BUY AT 90% OF CURRENT PRICE, SELL FOR 5% PROFIT...
SIMPLE ENOUGH....BUT I CAN'T SEEM TO DO IT.  WHAT AM I DOING WRONG?  IS THERE SUCH A STRATEGY?

**Comment by 151henry151** [comment]
I think you would need to create your own strategy. Gekko doesn't really come with any strategies that are ready to use out-of-the-box, you have to write your own or find ones that others have written and figure out how to get them working. A couple pieces of advice: 
1. Use lowercase. Your use of caps lock may have had something to do with your question going 11 days without an answer.
2. Check out the simple example strategy here: https://gekko.wizb.it/docs/strategies/creating_a_strategy.html#basic-strategy-example which could be modified to suit your description.
3. Consider asking these sorts of questions in the Strategy Development board at https://forum.gekko.wizb.it/

**Comment by askmike** [comment]
This is indeed the bugtracker! With those links you should be good.
