### ISSUE TITLE
How to incorporate CRYPTOCURRENCY SIGNAL FINDER from TRADEVIEW?

### ISSUE THREAD

**Issue by John1231983** [askmike/gekko#2161]
Hello all, this a feature request, any discussions are useful

As you know, CRYPTOCURRENCY SIGNAL FINDER from TRADEVIEW gives us strong buy and strong sell signal ( https://www.tradingview.com/cryptocurrency-signals/) . However, it does not have autotrade, while gekko did it very well. Hence, I hope gekko can incorporate or use the information from CRYPTOCURRENCY SIGNAL FINDER to make a good strategy. Is it possible?

Thanks so much

**Comment by xFFFFF** [comment]
Looking difficult. Can You enable e-mail notification on signals change? Is way to display this subpage without clicking mouse? If not: im not expert, but You can do with some perl modules, which using Firefox engine and "clicking" in place defined by You. Then easiest part: download page, parse/some regex work and finally You can start bots with advice. Easiest way is record macro to clicking, and download/copy-paste to excel and parse/start bots by simple script. But its use GUI so You will need free PC to work or Virtual Machine.

Its one of perl modules: http://search.cpan.org/~corion/WWW-Mechanize-Firefox-0.79/lib/WWW/Mechanize/Firefox/Examples.pm
Easy macro reader/recorder for Firefox (in Chrome not all works): https://imacros.net/
If this page generate sound on update, it can be useful: https://www.voicebot.net/
Web testers: https://medium.com/@briananderson2209/best-automation-testing-tools-for-2018-top-10-reviews-8a4a19f664d2

Its calling web scraping if You read more :)

**Comment by John1231983** [comment]
Thanks. For web scrapping, I am using this one but nothing in output https://github.com/DorukKorkmaz/tradingview-scraper

**Comment by xFFFFF** [comment]
Its doing exacly this wat i wrote in first part. Using selenium. Have You installed these libraries?

Out of curiosity: did you do any tests as to the accuracy of these signals in the context of mid term (1-3 days)? It's hard for me to believe it would be profitable ...

**Comment by John1231983** [comment]
Yes, i installed and ran it. You can check the issue that I reported in the repo

I did not test the accuracy. How about you? I found that you are using neural network, do you get some profit?

**Comment by xFFFFF** [comment]
I checked too but had connection refused after page start. I'm still learning gekko, there is a lot tips and tricks, but yes. In last 2 months I have profit on all my fourth accounts with NNv2 strategy

**Comment by John1231983** [comment]
Good job. Which coin do you investegate? Could you share setting for the coin?

**Comment by bpsi-staim** [comment]
hope this help to scrape the signal,
`curl 'https://scanner.tradingview.com/crypto/scan' -H 'Origin: https://www.tradingview.com' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: id,en;q=0.9' -H 'User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36' -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -H 'Accept: text/plain, */*; q=0.01' -H 'Referer: https://www.tradingview.com/cryptocurrency-signals/' -H 'Connection: keep-alive' -H 'DNT: 1' --data '{"filter":[{"left":"name","operation":"nempty"}],"symbols":{"query":{"types":[]},"tickers":[]},"columns":["name","close","change","change_abs","high","low","volume","Recommend.All","exchange","description","name","subtype","pricescale","minmov","fractional","minmove2"],"sort":{"sortBy":"name","sortOrder":"asc"},"options":{"lang":"en"},"range":[0,150]}' --compressed`

**Comment by askmike** [comment]
You can use Gekko to execute on signals coming from other sources:

- Right now: fetch your signal inside a "gekko strategy".
- In the future: you can use Gekko's execution library called Gekko Broker to control this on a lower level without the rest of Gekko's codebase (backtester, UI, etc).

See this forum post for more information (as well as an example for a gekko strategy that uses an external indicator): https://forum.gekko.wizb.it/thread-57189.html

Can we please move the discussion to the forum? I'm trying to keep the issue tracker dedicated to bugs. Thanks!
