### ISSUE TITLE
Gekko on Azure with MongoDB (CosmosDB)

### ISSUE THREAD

**Issue by Tizr0ck** [askmike/gekko#2165]
Ive configured a cloud instance on Azure with MongoDB. Imports seem to run fine and data is produced. However, after a while of running ive seen it fail and then "Scan available Data" will produce this:

binance
/home/username/gekko/node_modules/mongodb/lib/utils.js:123
    process.nextTick(function() { throw err; });
                                  ^

TypeError: Cannot read property 'forEach' of undefined
    at handle.collection.distinct (/home/username/gekko/plugins/mongodb/scanner.js:22:30)
    at /home/username/gekko/node_modules/mongojs/lib/collection.js:68:21
    at handleCallback (/home/username/gekko/node_modules/mongodb/lib/utils.js:120:56)
    at /home/username/gekko/node_modules/mongodb/lib/db.js:314:20
    at /home/username/gekko/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Im using the UI on UBUNTU.

Any help by chance :) ?

Besides, thanks for the great stuff, gekko rocks!

**Comment by askmike** [comment]
I'm working on stabalizing mongo DB support, there are some bugs. Is this working on other environments besides azure for you?

**Comment by Tizr0ck** [comment]
i have to be honest - i didnt try in other variants. and yes, it looks like it is just down to the stability of the mongodb adapter. the problem mainly is, at some point it stops writing correctly to the database and creates nullvalued entries, after that, displaying the data produces an instant error like the one above.

**Comment by Tizr0ck** [comment]
i could setup an instance on AWS and test there too, would that help?
