### ISSUE TITLE
Importing Data does never start on Binance when a "From" Data before Oct 2017 used

### ISSUE THREAD

**Issue by Tizr0ck** [askmike/gekko#2166]
On Binance when using a date before Oct 2017 is used the Imports never start:

![grafik](https://user-images.githubusercontent.com/12861298/39945919-7f3dd724-556c-11e8-8463-c242629f8d0b.png)

**Comment by askmike** [comment]
Ah will try to catch that, I am not sure how many markets where live on binance before that date, would you (or anyone else) know this?

**Comment by Tizr0ck** [comment]
for the specific coins the best i found is this. but it doesnt come in a list, its just a bunch of posts but in the details you see the publishing date. https://support.binance.com/hc/en-us/sections/115000106672-New-Listings
