### ISSUE TITLE
XLM, MITH support on Bitfinex?

### ISSUE THREAD

**Issue by FreshLondon** [askmike/gekko#2168]
Hey team, any interest in adding newer listed currencies to the Bitfinex importer?

Would be cool!

**Comment by askmike** [comment]
Gekko has a script that can update the supported markets for some exchanges. You can run this file yourself:

    cd gekko/util/genMarketFiles/
    node update-bitfinex.js

Note that compatibility between Gekkos and new markets is not verified to work properly. If you find bugs please report them. If you find them to be super stable you can also report that to have them added to the next release :)
