### ISSUE TITLE
Gekko knows how to do trade between exchange or I have to code it ?

### ISSUE THREAD

**Issue by ArthurTavaresBezerra** [askmike/gekko#2174]
I saw the sample-config.js store only one api key and secret following so where can I trade between exchanges ? 

config.trader = {
  enabled: false,
  key: 'key',
  secret: 'secret',
  username: '', // your username, only required for specific exchanges.
  passphrase: '', // GDAX, requires a passphrase.
  orderUpdateDelay: 1, // Number of minutes to adjust unfilled order prices
}

**Comment by askmike** [comment]
You cannot trade between exchanges using Gekko, read this page: https://gekko.wizb.it/docs/introduction/scope.html

If you have further (non technical) questions please ask in the forum!
