### ISSUE TITLE
Expanding IRC bot

### ISSUE THREAD

**Issue by Kris191** [askmike/gekko#2176]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...** Request or help
[ ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Started using the IRC bot

**Expected result** (what you hoped would happen)
Further functions

**Actual result** (unexpected outcome)
Works as expected

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
Hi, i'm wanting assistance on expanding the IRc bots functionality, could some help me add a advice emit for successful trades and if possible an ability to check balances. I'm not sure how difficult this would be.

thanks

**Comment by askmike** [comment]
Hey! I think the best thing is to wait for the new event system to hit Gekko, see this PR for more details: #1850

In the meanwhile: If you post something on the forum we can have a discussion about a specific set of features to implement after #1850!
