### ISSUE TITLE
multi-gekko, trade multi assets with gekko

### ISSUE THREAD

**Issue by bettimms** [askmike/gekko#2177]
Just published multi-gekko. Generate multiple config files and monitor multiple currencies and exchanges using gekko.

[multi-gekko](https://github.com/bettimms/multi-gekko)

**Comment by askmike** [comment]
Awesome! This is definitely something a ton of people have been asking.

Feel free to create a PR to fix this doc and add multi-gekko to it: https://github.com/askmike/gekko/blob/develop/docs/extending/other_software.md

Also feel free to post on the Gekko forum :)

Unfortunately I am closing this issue as I'm trying to clean up the issue tracker a little bit.
