### ISSUE TITLE
No new trades after long time 

### ISSUE THREAD

**Issue by zgwenwen** [askmike/gekko#2183]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** 

_I tried both paper trader and live trading bot.
When I check the log, I can see GEKKO is trying to request trade data from Kraken, but it usually takes about an hour to get a new trade._

**Expected result**

_My candle size is 10mins, and I'm using  strategy neuralnet_v2 
My expectation is getting new trade more often._

**Actual result** 

_Following is the log_

```
2018-05-15 11:24:30 (DEBUG):	Processing 3 new trades. From 2018-05-15 18:24:31 UTC to 2018-05-15 18:24:33 UTC. (a few seconds)
018-05-15 11:24:50 (DEBUG):	Requested ETH/CAD trade data from Kraken ...
2018-05-15 11:24:50 (DEBUG):	No new trades.
:
:
:
:
:
:
:
2018-05-15 12:31:11 (DEBUG):	No new trades.
2018-05-15 12:31:31 (DEBUG):	Requested ETH/CAD trade data from Kraken ...
2018-05-15 12:31:32 (DEBUG):	No new trades.
2018-05-15 12:31:51 (DEBUG):	Requested ETH/CAD trade data from Kraken ...
2018-05-15 12:31:51 (DEBUG):	No new trades.
2018-05-15 12:32:11 (DEBUG):	Requested ETH/CAD trade data from Kraken ...
2018-05-15 12:32:11 (DEBUG):	Processing 3 new trades. From 2018-05-15 19:32:11 UTC to 2018-05-15 19:32:11 UTC. (a few seconds)
```

_As you can see the log has been spinning for a very long time to get a new trade._

**Other information** 

_My assumption is maybe there's something wrong with the Kraken API?_
_Or maybe it is normal behaviour, for all the other exchange's API, they only post new trade data to Gekko from time to time (could be within 5 mins, or more than an hour)?_

**PLEASE HELP
THANK YOU!**

**Comment by Dalekxy** [comment]
This is normal behaviour.
I looked it up on https://www.kraken.com/charts for ETH/CAD. There are periods in which is no trade for over 50min.
Gekko market watcher asks for new trades every 20 seconds. When there is no trade in this time it tells you "No new trades"

**Comment by zgwenwen** [comment]
thank you @Dalekxy 
I guess in that case, Kraken is not that good for a trading bot?

**Comment by Dalekxy** [comment]
Or maybe just choose a pair on Kraken that has more trades.
I would suggest that your neuralnet performs better when it has more data points to learn from it.

**Comment by zgwenwen** [comment]
yes exactly..
I have actually switched to Quadriga now, since it has more trades.
Thank you
