### ISSUE TITLE
Added info to debug log

### ISSUE THREAD

**Issue by FreshLondon** [askmike/gekko#2187]
It would be really useful to have more information in the debug log during a backtest.

I'm not a JS coder but managed to throw together these below edits for RSI and a few on other strategies:
![screen shot 2018-05-17 at 23 11 32](https://user-images.githubusercontent.com/17095036/40186532-e7cee6e2-5a27-11e8-85c2-946b854ebfd3.jpg)

I'd like to be able to add to the above the trade volume, the UTC time your gekko candle starts and finishes, and any trades that it simulates making (plus info on these).

Could anyone please point me in the direction of an API list of calls that can be made? An fruitless google search and a tonne of testing has come up with nothing.

Greatly appreciated, I'd happily share this into the current gekko if anyone is interested in a bit more clarity in their logging.

- Troll disclaimer, I'm well aware that some don't need as much info on the screen. ;)

**Comment by askmike** [comment]
These debugs would slow down a backtests significantly. Are you only talking about live (and paper) trading bots? Or if backtests would you want to see it there or something you can put into excel/google sheets?
