### ISSUE TITLE
Simple web fixes

### ISSUE THREAD

**Issue by ScottEAdams** [askmike/gekko#2189]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ ] bug report
[x] question about the decisions made in the repository

**Action taken** (what you did)
Visit backtesting page

**Expected result** (what you hoped would happen)
More space for parameters etc

**Actual result** (unexpected outcome)
Cannot resize parameters box = squashed parameters

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Please update 
```
<div class="grd-row-col-2-6 px1"><div><h3>Parameters</h3>
```
to
```
<div class="grd-row-col-3-6 px1"><div><h3>Parameters</h3>
```
so that the parameters box fills the right side of the interface and provides more space on smaller screens. Ideally the content area of the page would use 100% width also as at the moment there is a lot of wasted space.

**Comment by askmike** [comment]
Great idea! Note that I am working on a completely different UI, but we can get this change in without impacting anything else.

Are you familiar with doing (and interested in) creating a PR? Or does anyone else want to pick this up?

**Comment by ScottEAdams** [comment]
this should tidy up the page a bit. Basically gives 95% width to everything except header and footer and a bit more space on the strat editing box :)

**Comment by ScottEAdams** [comment]
@askmike Not entirely sure why but my pull request never actually fixed the backtest page :)

I will have a look into it
