### ISSUE TITLE
Adding 2 func to core/util.js

### ISSUE THREAD

**Issue by hiyan** [askmike/gekko#2197]
Hi @askmike, would you mind if I add these 2 function to core/util.js?

- round for rounding off the fractions issue (Eg: 0.145 * 100 = 14.499999999999998)

- getPrecision will return the number of decimal count

```
  round: function(value, decimals = 14) {
    return Number(Math.round(value+'e'+decimals)+'e-'+decimals);
  },

  getPrecision: function(n) {
    if (!isFinite(n)) return 0;
    var e = 1, p = 0;
    while (Math.round(n * e) / e !== n) { e *= 10; p++; }
    return p;
  },
```

**Comment by askmike** [comment]
Hey! This is indeed very handy, but it's almost always used in a context of dealing with exchanges. In that case it would make more sense to make it available through Gekko Broker (see #2118). On top of that: Gekko makes a lot of use of the library Lodash, the version of Lodash used by Gekko is very old, but I want to update it so we can use Lodash' round method, see here: https://lodash.com/docs/4.17.10#round

What do you think?

**Comment by hiyan** [comment]
Yeap, mainly using it for output and fixing issues with the exchange returning errors. 
Having lodash do it would be better. Since you're upgrading, i guess this is not needed.

**Comment by askmike** [comment]
cool!
