### ISSUE TITLE
Docs say Bitstamp supports importing, seems not to be true?

### ISSUE THREAD

**Issue by bald123** [askmike/gekko#2198]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[X] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
I read the docs and checked this in the Gekko application.

**Expected result** (what you hoped would happen)
To find a possibility to import history data from Bitstamp in the data importer.

**Actual result** (unexpected outcome)
You can´t select Bitstamp data importer, although the docs say this is possible.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Looking at the source code for the Bitstamp exchange (in Gekko), download of history data seems not be supported. When looking at the Bitstamp API, this does not seem to be supported as well. I guess that the docs are wrongly stating that importing is possible from Bitstamp.

I´m talking about gekko/docs/introduction/supported_exchanges.md

**Comment by askmike** [comment]
Ah yes this is an error in the docs, it is definitely not possible to do this directly on bitstamp.

**Comment by askmike** [comment]
Fixed the docs, will upload a new version asap!
