### ISSUE TITLE
Cant find the syntax Error

### ISSUE THREAD

**Issue by 123qweas** [askmike/gekko#2209]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page]((https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Modefied the parameters and tried run the config.

**Expected result** (what you hoped would happen)
That the config runs

**Actual result** (unexpected outcome)
Got this error:
SyntaxError: Unexpected token :
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\threi\Gekko\gekko-stable\gekkoga\run.js:16:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

I checked the sytax and see no error

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
This is the code:
const randomExt = require('random-ext');

const config = {
  stratName: 'neuralnet',
  gekkoConfig: {
    watch: {
      exchange: 'kraken',
      currency: 'EUR',
      asset: 'XRP'
    },

//    daterange: 'scan',

    daterange: {
      from: '2018-02-01 00:00',
      to: '2018-05-21 16:55'
    },

    simulationBalance: {
      'asset': 1,
      'currency': 1
    },

    slippage: 0.05,
    feeTaker: 0.25,
    feeMaker: 0.15,
    feeUsing: 'taker', // maker || taker

  },
  apiUrl: 'http://localhost:3000',

  // Population size, better reduce this for larger data
  populationAmt: 20,

  // How many completely new units will be added to the population (populationAmt * variation must be a whole number!!)
  variation: 0.25,

  // How many components maximum to mutate at once
  mutateElements: 8,

  // How many parallel queries to run at once
  parallelqueries: 5,

  // profit || score
  // score = ideas? feedback?
  // profit = recommended!
  mainObjective: 'profit',

  // optionally recieve and archive new all time high every new all time high
  notifications: {
    email: {
      enabled: false,
      receiver: 'destination@some.com',
      senderservice: 'gmail',
      sender: 'origin@gmail.com',
      senderpass: 'password',
    },
  },

  stoploss: [ture,false],
  getProperties: () => ({

    historySize: randomExt.integer(100, 1),
    
    threshold_buy: randomExt.float(25,0).toFixed(2),
    threshold_sell: randomExt.float(0,-25).toFixed(2),
    
    price_buffer_len: randomExt.integer(1000,10),
    hodl_threshold: randomExt.float(1,0).toFixed(2),
    learning_rate: randomExt.float(1,0).toFixed(2),
   
    momentum: randomExt.float(1,0).toFixed(2),
    decay: randomExt.float(1,0).toFixed(2),
    min_predictions: historySize,

    stoploss_enabled:randomExt.pick(config.stoploss),
    stoploss_threshold: randomExt.float(1,0).toFixed(2),

     },

    candleSize: randomExt.integer(1000, 1),
  })
};

module.exports = config;

**Comment by 151henry151** [comment]
Maybe this `stoploss: [ture,false],` should be `stoploss: [true,false],` ?

**Comment by 123qweas** [comment]
There is no difference between `stoploss: [ture,false],`
and                                             `stoploss: [true,false],`

**Comment by 151henry151** [comment]
Not sure what you mean, there is a difference between spelling things correctly and not spelling things correctly. Did you try correcting that error and seeing if you still experience the same problem? The problem you're having is a problem with gekkoGA, not gekko. Maybe you will get better support by using the bug/issue tracker at https://github.com/gekkowarez/gekkoga instead of this one.

**Comment by 123qweas** [comment]
Ohh you are right. I didn't saw the difference.
Thank you!
Now I have one question. How can `min_predictions` and `historySize` use the same random number. 
`historySize: randomExt.integer(100, 1),
min_predictions: historySize,` was my idea but it didn't work.

**Comment by askmike** [comment]
Closing this as it's an issue with GekkoGA!
