### ISSUE TITLE
Connecting to mongodb erroring out again

### ISSUE THREAD

**Issue by whoodat** [askmike/gekko#2210]
Hi Mike,

As with #2204 I am receiving an error after git pulling from the develop branch. I did not upgrade mongo left it at 3.2. Any help is appreciated. Did something change with the mongodb in the latest pull?

Gekko encountered an error and can't continue

Error:

{ MongoError: not authorized on gekko to execute command { find: "gdax_candles", filter: { pair: "USD_ETH" } }
    at Function.MongoError.create (/home/whoodat/gekko/node_modules/mongodb-core/lib/error.js:31:11)
    at queryCallback (/home/whoodat/gekko/node_modules/mongodb-core/lib/cursor.js:212:36)
    at /home/whoodat/gekko/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'MongoError',
  message: 'not authorized on gekko to execute command { find: "gdax_candles", filter: { pair: "USD_ETH" } }',
  ok: 0,
  errmsg: 'not authorized on gekko to execute command { find: "gdax_candles", filter: { pair: "USD_ETH" } }',
  code: 13 } '\n\n'

Meta debug info:

Gekko version: v0.5.14
Nodejs version: v8.10.0

whoodat@whoodatserver:~/gekko$ mongo --version
MongoDB shell version: 3.2.20

**Comment by whoodat** [comment]
[config-backtest.zip](https://github.com/askmike/gekko/files/2041996/config-backtest.zip)


Mike,
My I believe I got it to work again but it is showing me as having:
Gekko encountered an error and can't continue

Error:

History table for gdax with pair USD_ETH is empty. 



Meta debug info:

Gekko version: v0.5.14
Nodejs version: v8.10.0


Yet I have 2 years worth of data scanned for history?

**Comment by whoodat** [comment]
Mike,
I realize now I can run backtests on SQlite as that is how I'm importing, is there a way to move the data to mongodb so that I can run backtests or live on mongodb?

**Comment by georgezouq** [comment]
@whoodat  I got the same problem. How to fix this?
