### ISSUE TITLE
Rate limit exceeded / Gdax

### ISSUE THREAD

**Issue by chris-sta** [askmike/gekko#2211]
Hi guys,

I'm running a live bot from console and I believe my configuration is requesting too much data from GDAX, as I am receiving this error : 

[gdax.js] (getTrades) returned an error, retrying: Rate limit exceeded.

The same strategy runs fine from the UI, and it also runs fine live, in console, using paper trader.

I think I have some wrong settings. Does anyone have any ideas 

I am sorry in advance if this is a noob question.

**Comment by askmike** [comment]
Are you running multiple gekkos / other bots from the same account & ip?

**Comment by chris-sta** [comment]
Just one instance from the command line. No backtests, no importing, nothing. Just the one

**Comment by askmike** [comment]
Can you try the new 0.6 release? I've been trading a lot on gdax without any problems. If that does not fix it please comment here, assuming this has been fixed.
