### ISSUE TITLE
Adding backtest data changes scan backtest start time

### ISSUE THREAD

**Issue by thegamecat** [askmike/gekko#2217]
I have been running a backtest all day - scan shows the following time window, note 11:37
from: 2017-12-30 11:37:00
to: 2018-05-23 06:37:00

This remained constant all day, then I did an update to the dataset using the gekko importer which I set to start from 2018-05-23 06:00:00.

I now run a back test expecting to start from the exact same point as obviously not data should have been altered before 2018-05-23 06:00:00. 

This is what I get:
from: 2017-12-30 11:55:00
to: 2018-05-28 15:55:00

Seems very odd.

**Comment by askmike** [comment]
Are you using sqlite?

**Comment by thegamecat** [comment]
No, postgres.
