### ISSUE TITLE
performanceAnalyzer.js crashes when calculating roundtrip duration

### ISSUE THREAD

**Issue by rolaru** [askmike/gekko#2218]
**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Hi @askmike!  I created my own strategy and the **performanceAnalyzer.js** crashes at **line 120** because `this.roundTrip.exit.date` and `this.roundTrip.entry.date` are not moment.js objects but numbers (seconds), in some circumstances. I haven't figuired out yet in which cases this happens, but I did some console..log() calls for the exit dates and start dates and the console outputs the following:

    ...
    entry date: 1516130940
    exit date: 1516382940
    entry date: 1516634940
    exit date: 1516886940
    ...

**Expected result** (what you hoped would happen)

The roundtrip durations are calculated correctly.

**Actual result** (unexpected outcome)

`
F:\gekko\plugins\performanceAnalyzer\performanceAnalyzer.js:120
    duration: this.roundTrip.exit.date.diff(this.roundTrip.entry.date)
                                       ^

TypeError: this.roundTrip.exit.date.diff is not a function
    at PerformanceAnalyzer.handleRoundtrip (F:\gekko\plugins\performanceAnalyzer\performanceAnalyzer.js:120:40)
`

**Other information**

I fixed the issue using some extra validations:

    var entryDate = typeof this.roundTrip.entry.date === 'number' ?
        moment.unix(this.roundTrip.entry.date) : this.roundTrip.entry.date;
    var exitDate = typeof this.roundTrip.exit.date === 'number' ?
        moment.unix(this.roundTrip.exit.date) : this.roundTrip.exit.date;
    
    var roundtrip = {
        ...
        entryAt: entryDate,
        ...
        exitAt: exitDate,
        ...
        duration: entryDate && exitDate ? exitDate.diff(entryDate) : 0
    }

Would it be a good idea to add these extra validations also to the official repository?

**Comment by askmike** [comment]
This race condition should not happen in 0.6 anymore. Please update your Gekko.

> Would it be a good idea to add these extra validations also to the official repository?

If the problem persists we should, the code assets certain assumptions which `should` always be true. So I might have a deeper look if it persists. Please comment again if that does not work!
