### ISSUE TITLE
Trading results completely different when starttime is different

### ISSUE THREAD

**Issue by r-schipper** [askmike/gekko#2219]
**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
I change the startdate by 1 minutes, which yields way different results, than a previous trade.
I have used the following settings:

Crypto: usdt-xrp on Poloniex
Trading strategy: RSI bear bull adx (https://forum.gekko.wizb.it/thread-100.html)
Candle size: 200
Warmup period: 300

Settings: 
[SMA]
long = 300
short = 10

[BULL]
rsi = 10
high = 80
low = 60
mod_high = 5
mod_low = -5

[BEAR]
rsi = 15
high = 50
low = 20
mod_high = 15
mod_low  = -5

[ADX]
adx = 3
high = 70
low = 50

----

1st run:
startdate: 2017-12-18 20:49
enddate: 2018-05-24 14:39
result: 43.97553%
Amount of trades: 6

2nd run:
startdate: 2017-12-18 20:50
enddate: 2018-05-24 14:39
result: 29.53513%
Amount of trades: 4

**Expected result** (what you hoped would happen)
Both trades should have the same result, even when you change the startdate.

**Actual result** (unexpected outcome)
1st run:
result: 43.97553%
Amount of trades: 6

2nd run:
result: 29.53513%
Amount of trades: 4

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
This happens both in live trading and in backtesting. 
Why is the startdate influencing the results like this? The trading bot should look at the current date and time to decide if it needs to make a trade or not, the startdate should not have anything to do with that, right?

Hope you can find out whats causing this. Thanks!

<img width="1666" alt="results 1st run" src="https://user-images.githubusercontent.com/38553922/40671914-8ef798e4-636d-11e8-84ac-9d16224b940c.png">
<img width="1661" alt="results 2nd run" src="https://user-images.githubusercontent.com/38553922/40671915-8f17f6b6-636d-11e8-98c8-e0522c476df6.png">

**Comment by askmike** [comment]
When you change the starttime gekko calculates different candles. Candles are the only thing your strategy looks at when deciding when to buy or sell. Different results are expected. As to how different depends on your strategy, what strategy are you using?

**Comment by r-schipper** [comment]
I'm using RSI bear bull adx (https://forum.gekko.wizb.it/thread-100.html).
Hm ok, to me it sounds a bit weird that the results can be different because the starttime is different. 

I think the candles should reflect the situation as it is. That means that if you calculate minute candles, the candle for 20:56 should always be the same. Or I'm I missing something?

If the candles are different each time it's not possible to find a strategy that works and that you can trust, because you will have no idea how it will behave based on your current starttime.

If I for example use the indicator MA Cross on tradingview.com, the crossing of the 2 lines will always be on the same period in time, even when the starttime of the chart changes. I would expect that also to happen with the Gekko.

**Comment by 151henry151** [comment]
@r-schipper if you take a look here: https://forum.gekko.wizb.it/thread-57173-post-58830.html#pid58830 I did a few backtests with start-times varying by one minute, and found that the effect on the results is very small, almost negligible. However, I've found that you can work around this by starting your strategy on the hour, or on the ten-minute mark, i.e. start it at 5:00, not 5:01, or 5:10, not 5:15; and you'll get results that match up with tradingview/etc. The difference is, when you look at a chart on tradingview, if you're looking at ten-minute candles, the candles will be lined up with the ten-minutes-after-the-hour marks, i.e. one candle will be from 5:00 to 5:10, the next from 5:10 to 5:20 -- with gekko, it does not work this way, gekko makes its own candles, so if you start at 5:01, you'll have a ten-minute candle from 5:01 to 5:11, etc. -- it's not a glitch, it's just how this system works.

**Comment by askmike** [comment]
Is it possible to retry this with 0.6? There have been major changes in how
data (events) is passed around betwen plugins, For some background see
[this thread](https://forum.gekko.wizb.it/thread-56579.html). Thanks!

EDIT: @151henry151 was a bit too trigger happy here, only read now you were explaining the behaviour!

**Comment by r-schipper** [comment]
What I'm am doing now is indeed start Gekko at a specific time so that the start time of the candles aligns with my the start time I used in the backtest. I undestand now that it's not a glitch but the way it should work.

So what would be a great feature is a setting where you can define what the start period of a candle should be. Because right now I have a cronjob running the starts the bot every 2 or 4 hours for example. So if I would have to make a change and restart the bot, It could be that I have to wait 4 hours before it is running again.

This settings makes it also more understandable, because I think that not everyone is aware of how important the starttime is. If the starttime is different the actual shape of the chart is different, so the results of the strategie will also be different.

@askmike I'm going to try out version 0.6. And I must say the despite this issue I'm really happy with Gekko! :))

**Comment by thisisloze** [comment]
This has been an ongoing issue for ever. Sirtificste has a candlebatcher fix but it's not being implemented into gekko for unknown reasons. I wish gekko wasn't built like this. No one wants to trade 5:01-5:06 for a 5 min candle. It's completely retarded. @askmike. You should fix this ASAP.

**Comment by askmike** [comment]
@thisisloze 

> Sirtificste has a candlebatcher fix but it's not being implemented into gekko for unknown reasons.

The reasons are listed in the PR #2133, they are:

> - it's currently breaking tests that definitely should work.
> - Can you make this feature optional behind a config flag? The reason it currently does not work like this is to not have all Gekko's submit all orders at :00 every hour (and knowing a lot of people run specific strats very easily anticipated & manipulated upon). We definitely need this but behind a config flag.

Having candles not on clock hours is a design decision:

- Makes it harder for people to abuse and play around default gekko's.
- How do we even though this for candles of a size of say 59 minutes? Gekko is flexible in candle generation so that simple strats do not trade the same signal as everyone else who is looking at charts.

**Comment by r-schipper** [comment]
Right now I'm using the latest stable version of Gekko but what I noticed is, is that the candle start time is changing. When I started Gekko the initial candles are starting every 4 hours , like 00:00, 04:00, 08:00 ... which is good, but it than had to retrieve the next candle 4 hours after starting and that one suddenly starts at 19:52. The same for all the candles after that.

This was the first handle at start:
2018-08-02 20:02:36 (DEBUG):    Processing 427 new trades. From 2018-08-02 15:54:16 UTC to 2018-08-02 19:59:42 UTC. (4 hours)
candle:  { start: moment("2018-05-28T04:00:00.000"),
  open: 0.27500453,
  high: 0.27644114,
  low: 0.25510244,
  close: 0.26000001,
  vwp: 0.2618909710614257,
  volume: 1599197.8307466807,
  trades: 757 }

And this is the one 4 hours after starting:
2018-08-03 00:00:24 (DEBUG):    Processing 1 new trades. From 2018-08-03 00:00:21 UTC to 2018-08-03 00:00:21 UTC. (
a few seconds)
candle:  { start: moment.utc("2018-08-02T19:52:00.000+00:00"),
  open: 0.262999,
  high: 0.26675817,
  low: 0.25930921,
  close: 0.25949991,
  vwp: 0.26344941212698403,
  volume: 438154.72804580996,
  trades: 173 }

How can I make sure that Gekko is always having candles that start every 4 hours? A setting would be great, because right now I have to restart Gekko, wait 4 hours before it is starting again, and than hope the the candles are correct.
Hope this can get some priority, because if that candles are not right the strategy won't work.

**Comment by thisisloze** [comment]
That's just processing the trades. The actual candlesize and start time
should still be 4 hours as long as the first candle was exactly 4 hours and
started on 00:00

**Comment by rkingy** [comment]
I had a lot of trouble with my strat not running right on the minute I need it to with Live Trader. For example a 2min strat must start on a minute past the hour divisible by 2. Not 3mins past or 7 mins past.

I've coded my own fix for this.. 

1. Find dataStitcher.js
2. Locate the endDate line around line 61 ```  var endTime = moment().utc().startOf('minute');```
3. Insert this code below 
``` // Check if we are trading right on the minute of the hour our strategy is designed for.
  // e.g. If we are trading on 5 min candles, we need to wait till we get to the 5th minute
  while(endTime.minute() != 0 && Number.isInteger(endTime.minute() / config.tradingAdvisor.candleSize) == false ){
    endTime.add(1, 'minute').startOf('minute');
    log.info('\t Adding minute to start time to get in sync, New Start:', endTime.format());
  }
