### ISSUE TITLE
[binance.js] Error -1100: Illegal characters found in parameter 'price'

### ISSUE THREAD

**Issue by six101** [askmike/gekko#2222]
**I'm submitting a ...**
[x] bug report

**Action taken** (what you did)
Start a new gekko, settings: binance, BTC-BCN, live tradebot

**Expected result** (what you hoped would happen)
Bot starts trading

**Actual result** (unexpected outcome)
After warmup period gekko gives an error:
"Gekko encountered an error and can't continue"

In console error message:

RECEIVED ERROR IN GEKKO 413305468945839
Gekko encountered an error and can't continue
Gekko encountered an error and can't continue
Error:

[binance.js] Error -1100: Illegal characters found in parameter 'price'; legal range is '^([0-9]{1,20})(\.[0-9]{1,20})?$'.

Meta debug info:
Gekko version: v0.5.14
Nodejs version: v8.11.2

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

I'm new to trading bots. I have no idea if I made a mistake or if I misinterpreted the error message. These settings run cleanly during backtesting but not in live mode.
I run the bot in windows 10 bash with ubuntu.

last lines of the tradebot.log:
2018-06-01 12:58:03 (DEBUG):	[binance.js] (addOrder) BUY 3449 BCN @9.2e-7 BTC
2018-06-01 12:58:04 (ERROR):	[binance.js] (addOrder) returned an irrecoverable error: Error: Error -1100: Illegal characters found in parameter 'price'; legal range is '^([0-9]{1,20})(\.[0-9]{1,20})?$'.
2018-06-01 12:58:04 (DEBUG):	[binance.js] entering "setOrder" callback after api call, err: [binance.js] Error -1100: Illegal characters found in parameter 'price'; legal range is '^([0-9]{1,20})(\.[0-9]{1,20})?$'. data: {"code":-1100,"msg":"Illegal characters found in parameter 'price'; legal range is '^([0-9]{1,20})(\\.[0-9]{1,20})?$'."}

Is it possible that the scientific notation of the price is causing this problem?

**Comment by askmike** [comment]
Apologies for the delayed response, I am confident this bug has been fixed in the new Gekko release 0.6. Please update and try again, if the problem persists please comment here.

**Comment by six101** [comment]
Thanks for the answer. I did a fresh installation of gekko 0.6. Same settings as above. Unfortunately, the error still exists. Am I perhaps doing something wrong since no one else seems to have this error? I have absolutely no idea what I could do wrong as all settings are self-explanatory and very simple.

handleCreate [binance.js] Error -1100: Illegal characters found in parameter 'price'; legal range is '^([0-9]{1,20})(\.[0-9]{1,20})?$'.
RECEIVED ERROR IN GEKKO INSTANCE 2018-07-04-21-48-tradebot-780583332161955
{ name: 'AbortError',
  message: '[binance.js] Error -1100: Illegal characters found in parameter \'price\'; legal range is \'^([0-9]{1,20})(\\.[0-9]{1,20})?$\'.' }
