### ISSUE TITLE
DeprecationWarning: `getProductTrades

### ISSUE THREAD

**Issue by Kris191** [askmike/gekko#2223]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
none, started gekko in papertrader

**Expected result** (what you hoped would happen)
paper trading

**Actual result** (unexpected outcome)
(node:15943) DeprecationWarning: `getProductTrades()` now requires a product ID as the first argument. Attempting to use PublicClient#productID (BTC-EUR) instead.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
can any explain how i get this error to be removed please

**Comment by qisforq** [comment]
+1

**Comment by askmike** [comment]
This is now fixed in 0.6. Please download the latest Gekko version and try again.
