### ISSUE TITLE
new Binance USDT trading pairs

### ISSUE THREAD

**Issue by TradeCrafter** [askmike/gekko#2229]
why the new trading pair IOTA/USDT its not showing on gekko, i cant see my funds by the bot, but the bot works fine with the API, doing trades in profit, works fine and its awesome.

just got thes 2 questions !

**Comment by chopbk** [comment]
you can define this in gekko/exchanges/biance-market.json

**Comment by bald123** [comment]
Go to directory util/genMarketFiles and execute script for your exchange. It will update the exchange definitions in which the trading pairs are defined.

**Comment by askmike** [comment]
These are added to 0.6, please update your Gekko!
