### ISSUE TITLE
Binance - instant trading

### ISSUE THREAD

**Issue by FreshLondon** [askmike/gekko#2232]
Hey folks,

Currently searching the code to find my own way of doing this, in the meantime I thought I'd ask how to make Gekko instantly trade using the taker fee.

I'm on Binance, maker and taker fee are the same so it seems counterproductive not to instantly trade (I've seen trades going in at a slight difference to market price and get constantly adjusted up or down as the price moves, never really being filled on time..).

I understand we'd also need to look at the markup / markdown bid compared to the current price.

Has anyone done this yet?

**Comment by FreshLondon** [comment]
OK, what about the location of where gekko sets its markup / markdown for the buy/sell orders?
I'm editing the ping-pong strategy just because it has these allowances within the script.

Not getting trades placed yet, i'll check in the morning.. :)

**Comment by hiyan** [comment]
check out plugins/trader if you cant wait for the next version.

**Comment by FreshLondon** [comment]
yea thats exactly where I am, didn't see a numerical value/calculation for markup/markdown so took the lines from pingpong and edited.

It reaches it's history in about 25mins, we'll see if there's a trade.

Thanks for your input, was looking for a specific file/line but appreciate you chiming in anyway 👍

**Comment by askmike** [comment]
dup of #2241
