### ISSUE TITLE
What files must I edit to view created stratigies in Gekko?

### ISSUE THREAD

**Issue by Hackertalkz** [askmike/gekko#2233]
what file must I edit so I can run different strategies in gekko??
i thought if I copied and pasted different strategies it would show up in gekkos list, however I am wrong.  Therefore what file must I edit??

I just downloaded gekko and figured out how to install it on ubuntu, had no success in windows
Can someone give me a simple step by step instructio ns please...
I thought it was the config file that I must edit, but the only config file I have is from a strategy file... outside of gekkos installation directory.

**Comment by Hackertalkz** [comment]
after I post different strategies in gekko, it shows up on "gekko's menu", however the parameters are blank "in gekko".    is this normal?  when I try to add parameters I get errors within gekko.

**Comment by Hackertalkz** [comment]
After selecting strategy in Gekko; 
under parameters selection I get this error after pasting this code
------------------------------
ERROR
----------------------------
Expected "=" or Whitespace but "l" found.
-------------------------------------------------------------------
I HAD MORE ERRORS BUT I JUST DELETED A FEW LINES THAT WERE COMMENTS
WITH // IN STARTING

--------------------------------------------------------------------------
CODE
----------------------------------------------------------------------------


var log = require ('../core/log.js');
var config = require ('../core/util.js').getConfig();

// strategy
var strat = {
	
	/* INIT */
	init: function()
	{
		this.name = 'RSI Bull and Bear';
		this.requiredHistory = config.tradingAdvisor.historySize;
		this.resetTrend();		
		
		// debug? set to flase to disable all 
// logging/messages (improves performance)

		this.debug = false;
		
		// performance
config.backtest.batchSize = 1000; // increase performance
config.silent = true;
config.debug = false;
		
		// add indicators
this.addIndicator('maSlow', 'SMA', this.settings.SMA_long );
this.addIndicator('maFast', 'SMA', this.settings.SMA_short );
this.addIndicator('BULL_RSI', 'RSI', { interval: this.settings.BULL_RSI });
this.addIndicator('BEAR_RSI', 'RSI', { interval: this.settings.BEAR_RSI });
		
		// debug stuff
this.startTime = new Date();
this.stat = {
bear: { min: 100, max: 0 },
bull: { min: 100, max: 0 }
		};
		
}, // init()
	
	
	/* RESET TREND */
resetTrend: function()
	{
var trend = {
duration: 0,
direction: 'none',
longPos: false,
};
	
this.trend = trend;
	},
	
    /* get lowest/highest for backtest-period */
lowHigh: function( rsi, type )
	{
let cur;
if( type == 'bear' ) {
cur = this.stat.bear;
if( rsi < cur.min ) this.stat.bear.min = rsi; // set new
if( rsi > cur.max ) this.stat.bear.max = rsi;
		}
else {
cur = this.stat.bull;
if( rsi < cur.min ) this.stat.bull.min = rsi; // set new
if( rsi > cur.max ) this.stat.bull.max = rsi;
	}
	},
	
	
	/* CHECK */
check: function()
	{
		
	// get all indicators
let ind = this.indicators,
maSlow = ind.maSlow.result,
maFast = ind.maFast.result,
rsi;
			
		// BEAR TREND
if( maFast < maSlow )
		{
rsi = ind.BEAR_RSI.result;
if( rsi > this.settings.BEAR_RSI_high ) this.short();
else if( rsi < this.settings.BEAR_RSI_low ) this.long();
			
if(this.debug) this.lowHigh( rsi, 'bear' );
           //log.debug('BEAR-trend');
		}

		// BULL TREND
else
		{
rsi = ind.BULL_RSI.result;
if( rsi > this.settings.BULL_RSI_high ) this.short();
else if( rsi < this.settings.BULL_RSI_low )  this.long();
if(this.debug) this.lowHigh( rsi, 'bull' );
		//log.debug('BULL-trend');
	}
	
	}, // check()
	
	
	/* LONG */
long: function()
	{
if( this.trend.direction !== 'up' ) 
             // new trend? (only act on new trends)
		{
this.resetTrend();
this.trend.direction = 'up';
this.advice('long');
	//log.debug('go long');
		}
		
if(this.debug)
		{
this.trend.duration++;
log.debug ('Long since', this.trend.duration, 'candle(s)');
		}
	},
	
	
	/* SHORT */
	short: function()
	{
		// new trend? (else do things)
if( this.trend.direction !== 'down' )
		{
this.resetTrend();
this.trend.direction = 'down';
this.advice('short');
		}
		
if(this.debug)
		{
this.trend.duration++;
log.debug ('Short since', this.trend.duration, 'candle(s)');
		}
	},
	
	
	/* END backtest */
end: function()
{
let seconds = ((new Date()- this.startTime)/1000),
minutes = seconds/60,
str;
			
minutes < 1 ? str = seconds + ' seconds' : str = minutes + ' minutes';
		
		log.debug('====================================');
log.debug('Finished in ' + str);
		log.debug('====================================');
		
if(this.debug)
		{
let stat = this.stat;
log.debug('RSI low/high for period');
log.debug('BEAR low/high: ' + stat.bear.min + ' / ' + stat.bear.max);
log.debug('BULL low/high: ' + stat.bull.min + ' / ' + stat.bull.max);
		}

	}
	
};

module.exports = strat;

**Comment by ptdev** [comment]
Hi, strategy configs are in: gekko/config/strategies/

**Comment by askmike** [comment]
If you have further questions, please ask them on the forum or in discord. This is a bugtracker. See this: https://gekko.wizb.it/docs/introduction/getting_help.html
