### ISSUE TITLE
Unable to start the app as per the instructions in the documentation

### ISSUE THREAD

**Issue by dhanunjayalakshmi** [askmike/gekko#2234]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[O] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
I have executed the command `node gekko --ui` on my ubuntu 16.04 with node version 10.4.x

**Expected result** (what you hoped would happen)
Open up the UI(I assume this based on the documentation instructions)

**Actual result** (unexpected outcome)
Got the below Error
> gekko/node_modules/promisify-node/utils/args.js:9
  var args = func.toString().match(/function\s.*?\(([^)]*)\)/)[1];
                                                              ^

TypeError: Cannot read property '1' of null

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
Stack Trace:

> TypeError: Cannot read property '1' of null
>     at module.exports (<HOME_PATH>/gekko/node_modules/promisify-node/utils/args.js:9:63)
>     at processExports (<HOME_PATH>/gekko/node_modules/promisify-node/index.js:61:29)
>     at module.exports (<HOME_PATH>/gekko/node_modules/promisify-node/index.js:164:10)
>     at Object.<anonymous> (<HOME_PATH>/gekko/web/routes/scanDateRange.js:4:14)
>     at Module._compile (internal/modules/cjs/loader.js:702:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
>     at Module.load (internal/modules/cjs/loader.js:612:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:543:3)
>     at Module.require (internal/modules/cjs/loader.js:650:17)
>     at require (internal/modules/cjs/helpers.js:20:18)
>     at Object.<anonymous> (<HOME_PATH>/gekko/web/server.js:56:26)
>     at Module._compile (internal/modules/cjs/loader.js:702:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
>     at Module.load (internal/modules/cjs/loader.js:612:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:551:12)

Node Version 10.4.x

**Comment by dhanunjayalakshmi** [comment]
I am more comfortable with python and exploring Gekko to see if I can write my python codes on gekko setup and do backtesting. So, I am not sure what I am missing. May be this can be a small mistake but I am not so much into JS tech stack at the moment. So, please help me with this bug / error.

**Comment by BlackHoleDevs** [comment]
First thing, please downgrade node, second thing please install bot exactly like it is said in the documentation : https://gekko.wizb.it/docs/installation/installing_gekko.html
before starting the bot you need to run  : npm install --only=production

**Comment by askmike** [comment]
This bug has been reported but I have not been able to reproduce. However I think this has been fixed since the 0.6 release. Can you please redownload the latest version and try again? Thanks!
