### ISSUE TITLE
Exchange API keys not persisted outside Docker container.

### ISSUE THREAD

**Issue by bald123** [askmike/gekko#2238]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[] bug report
[*] question about the decisions made in the repository

**Action taken** (what you did)
Installed Gekko in various Docker images using the Dockerfile & docker-compose.yml from the Gekko repository.

**Expected result** (what you hoped would happen)
I expected that the exchange API keys were persisted outside the container (by means of volume mapping in the docker-compose.yml file for example).

**Actual result** (unexpected outcome)
The exchange API keys seems to be gone on container shutdown. 

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
I don't know how the exchange API keys are persisted, but is it an idea to persist this outside the Docker container?

**Comment by hilkoc** [comment]
This is not a bug but normal behavior for Docker containers. They are assumed to be ephemeral.

I'm managing Docker containers with [dokku](https://github.com/dokku/dokku). There the  recommended (and safest) way to setup persistent configuration is using environment variables. Dokku has some convenient commands for managing those.
To make it all work I had to make a few changes in the Gekko code. I can share those if you're interested.

**Comment by bald123** [comment]
I know, but that would mean that Docker containers would not be able to make use of any persistent data at all. Storing persistent data is already being done in the Gekko container by doing volume mappings (see docker-compose.yml). The same thing could be done for the api keys, mapping the file to a folder on the host (/UNC path). The exchange data for example is not lost at container restart, the same mechanism could easily be applied to the api keys. I don’t know where these are stored currently though.

Thank you for your offer btw!

**Comment by askmike** [comment]
I would love to have this being optional: Gekko (without docker) also persists keys, and the docker image does persist some things using a volume.

> To make it all work I had to make a few changes in the Gekko code. I can share those if you're interested.

I'd love a PR!

**Comment by bald123** [comment]
Isn't this fixed with one extra volume mapping? I don't know where the keys are stored though...

**Comment by hilkoc** [comment]
> I don't know where the keys are stored though...

I believe they are in a file called SECRET-api-keys.json in the root of the gekko folder. You (or some malicious user with access)  can also do a grep for the name of the exchange that you trade on and it will print your API keys immediately.

> I'd love a PR!

My change isn't suitable for a PR I think. It can only accommodate one set of keys for one exchange. Just enough for what I need. I've added these lines in web/apiKeyManager.js

```

// Read default keys from environment variables
const key = process.env.API_KEY;
const secret = process.env.API_SECRET;
const default_keys =  (!key || !secret) ? {} : { "kraken": {"key": key, "secret": secret}};

```

and further on, if no apiKeyFile is found,
`    JSON.stringify(default_keys)`
instead of
`  JSON.stringify({})`

**Comment by bald123** [comment]
I tried to add a volume mapping for the file like this:
- ./SECRET-api-keys.json:/usr/src/app/SECRET-api-keys.json

It creates a directory on the host named "SECRET-api-keys.json" instead of a file. The same goes for the already existing "config.js" file (see docker-compose.yml). The issue here is that those files are created runtime, and they don't exist in the container on startup. Docker can't handle this properly so since the file is non-existing in the container, it creates a directory. I've read about two solutions:
- Make sure that the file already exists on built of the container (this can be injected during container build or be a default part of the codebase).
- Move the location of the files to a designated folder, because folder mapping goes well and the files will appear on the host when they are created in the folder of the container.

I'll see if I find another appropriate solution which does not require change of code/file locations.

**Comment by patlachance** [comment]
@bald123 which docker version are you using?
Mounting a file inside a container should work. See example below:

```bash
$ date > /tmp/dummyfile
$ docker run -it --rm -v /tmp/dummyfile:/etc/dummyfile centos cat /etc/dummyfile
Sat Jul 21 12:42:56 CEST 2018
```

**Comment by bald123** [comment]
I’m using docker compose, dont know the version now (can’t check). But when the targetfile and the “local” file do not exist at startup, how should docker know if it is mapping a file or a directory? So by default, it creates a directory locally, for as far as I know (and this is by design).

**Comment by patlachance** [comment]
Indeed if you define a volume in the docker-compose.yml file that points to a non existing file system object, docker has no way to determine if the volume should be mapped to a file or a directory and docker creates a directory.

Here is how to do it.

1. Create an empty JSON configuration file on the docker host prior to start Gekko with docker-compose

```bash
$ mkdir -p ./volumes/gekko/config
$ echo "{}" > ./volumes/gekko/config/SECRET-api-keys.json
```
2. Map the configuration file inside the container using docker volume by changing the gekko container volume key to the following

```yaml
    volumes:
      - ./volumes/gekko/config/SECRET-api-keys.json:/usr/src/app/SECRET-api-keys.json
      - ./volumes/gekko/history:/usr/src/app/history
      - ./config.js:/usr/src/app/config.js
```

3. Start Gekko using docker-compose

```bash
$ docker-compose up
```
4. Add your API key(s) using Gekko's Web UI

5. Open another terminal and check the content of the ./volumes/gekko/config/SECRET-api-keys.json file

```bash
$ cat volumes/gekko/config/SECRET-api-keys.json 
{"poloniex":{"key":"EDITED-EDITED-EDITED-EDITED","secret":"EDITEDEDITEDEDITEDEDITED"}}
```

Your API keys are stored on the docker host, not inside the ephemeral container.
