### ISSUE TITLE
Make this the best Binance bot?

### ISSUE THREAD

**Issue by FreshLondon** [askmike/gekko#2241]
I've used Binance for a long time now due to their low fees, using Gekko on Binance shows a few differences from the live trading.
At present Gekko does not take advantage of the 50% discount when using BNB to pay fees (0.05% of traded amount) .
This makes a huge difference over a timescale, especially when trading multiple times for small profit.
I've seen this option on bots like Zenbot, but they dont have the timestamp isses fixed like Gekko or the sleek UI and clear backtesting.

The next part is the taker and maker fees are the SAME :)
There is no feature to opt for taker fee, to trade directly at market price.
Instead, the bot places an order at a % difference from the current price and then sits there waiting to be filled.
If an order is not filled the bot places again, at a distance (sometimes more than the bid it replaced) from the live price.

I've spent hours searching and modifying code (this is not the language I write in, it's been difficult) to get the bot to trade at closer amounts or at the market price - I cannot find the option.

So, to make the bot better I heavily suggest:
- enabling the use of BNB for trade fees.
- enabling the use of the taker fee and trading at market price.
- enable setting the markup/markdown amount (%) of the market price when placing a bid.

Any thoughts or suggestions to add? 👍

**Comment by askmike** [comment]
> At present Gekko does not take advantage of the 50% discount when using BNB to pay fees (0.05% of traded amount) .

This is not something a bot can configure, this is something you need to enable yourself in your binance account.

> enabling the use of the taker fee and trading at market price.
> enable setting the markup/markdown amount (%) of the market price when placing a bid.

I am working on this! For now Gekko will always use limit orders, but keep in mind that even though the fees are the same you are still paying the spread and slippage.

**Comment by david-does-dazn** [comment]
@askmike any progress on this?
