### ISSUE TITLE
Gekko plus

### ISSUE THREAD

**Issue by thegamecat** [askmike/gekko#2242]
Is the plan to make a working bot with the features and fixes requested a paid for solution only or will these things be resolved and remain open source?

**Comment by askmike** [comment]
I'm working on 0.6 rigt now, it's massive upgrade with a lot of fixes and such. It will be free and fully open source.

> features and fixes requested

Requested where?

**Comment by GO1984** [comment]
@asmike: Thank you for your efford.

**Comment by thegamecat** [comment]
Awesome news, that's great to hear!

Requested here and the forum :)

**Comment by askmike** [comment]
Are you talking about any specific requested features and fixes? A lot will happen but a lot will not, but this is independent of Gekko Plus :)
