### ISSUE TITLE
The price property in the trade object passed to the onTrade method in a strategy is not always set.

### ISSUE THREAD

**Issue by nitramb** [askmike/gekko#2243]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
I am trying to use the onTrade method to get the avg price I got in at on a buy trade and use this price to calculate a target price my strategy can use to know when to get out.
 
method.onTrade = function(trade) {
	if(trade.action == "buy") {
		this.startPrice = trade.price;
		this.targetPrice = this.startPrice * this.settings.percent;
		this.outPrice = this.startPrice * 0.99;
	} else if (trade.action == "sell") {
		this.startPrice = 0;
		this.targetPrice = 0;
		this.outPrice = 0;
		this.startedTrendPrice = 0;
	}
}

from what I have read for the latest release 0.5.14 this should be set on the trade object under price.

**Expected result** (what you hoped would happen)

To get the avg price of the trades done on my buy trade.

**Actual result** (unexpected outcome)

The price property in the trade object is not always set.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

I am using gdax.
Gekko version: 0.5.14
this error happend one second before the onTrade got called.
2018-06-15 11:28:28 (ERROR):    [gdax.js] (getOrder) returned an irrecoverable error: NotFound

**Comment by nitramb** [comment]
Pretty should that this error is causing the issue, and it doesn't happen every trade.

2018-06-15 11:28:28 (ERROR): [gdax.js] (getOrder) returned an irrecoverable error: NotFound

After running the bot for a few hours and doing a few trades, I found that when that error doesn't happen everything works as it should.

**Comment by nitramb** [comment]
On further investigation and after looking at the traffic between Gekko and the exchange, I found that after a buy order has completed Gekko checks the first order it did when starting the buy order again. Even tho it had cancelled it before, so Gdax is returning NotFound since the order has been cancelled.

On another note I noticed the recoverableErrors regexp doesn't match, Gdax returns NotFound instead of NOTFOUND. I have enabled the "i" flag on the regex for now so its not case sensitive.

**Comment by nitramb** [comment]
Any ideas ?

**Comment by askmike** [comment]
Apologies for the late response. I think it's better to not use the current `onTrade` implementation for now... I'll implement a better solution as part of 0.6, see #2216.

**Comment by askmike** [comment]
This should be fixed by now. If it isn't please open a new issue!
