### ISSUE TITLE
Error Message When Starting Live Trading and Market Watcher

### ISSUE THREAD

**Issue by Borrismorris** [askmike/gekko#2247]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did) Tried to start live trading through the UI using a custom strat. I ran a market watcher First to get the same errors.

**Expected result** (what you hoped would happen) i thought the Bot would have run and made trades seeing as i ahve assigned the Binance API and Secret API

**Actual result** (unexpected outcome) Error message

Gekko 291199366217786 started
  --> POST /api/startGekko 200 11ms 146b
  <-- POST /api/getCandles
  <-- POST /api/getCandles
  <-- POST /api/getCandles
{ Error: SQLITE_BUSY: database is locked errno: 5, code: 'SQLITE_BUSY' }
  --> POST /api/getCandles 200 2,074ms 76b
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: SQLITE_BUSY: database is locked
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: SQLITE_BUSY: database is locked
  xxx POST /api/getCandles 500 1,806ms -

  Error: non-error thrown: ERROR, unable to load candles, please check the console.
      at Object.onerror (d:\gekko-develop\node_modules\koa\lib\context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  xxx POST /api/getCandles 500 1,814ms -

  Error: non-error thrown: ERROR, unable to load candles, please check the console.
      at Object.onerror (d:\gekko-develop\node_modules\koa\lib\context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Currently running on windows 10, Latest versions of Node.js installed, latest dependencies also.

IF YOU NEED ANY MORE INFO I WILL GLADLY GIVE IT TO YOU. I really would like to be running my strategy

**Comment by Borrismorris** [comment]
Still getting this when trying to apply the live trader to a Bittrex account
Gekko 8508728504117888 started
  --> POST /api/startGekko 200 8ms 147b
  <-- POST /api/getCandles
  <-- POST /api/getCandles
  <-- POST /api/getCandles
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: SQLITE_BUSY: database is locked
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: SQLITE_BUSY: database is locked
  xxx POST /api/getCandles 500 1,832ms -

  Error: non-error thrown: ERROR, unable to load candles, please check the console.
      at Object.onerror (D:\Gekko\node_modules\koa\lib\context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  xxx POST /api/getCandles 500 1,836ms -

  Error: non-error thrown: ERROR, unable to load candles, please check the console.
      at Object.onerror (D:\Gekko\node_modules\koa\lib\context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: SQLITE_BUSY: database is locked
  xxx POST /api/getCandles 500 1,817ms -

  Error: non-error thrown: ERROR, unable to load candles, please check the console.
      at Object.onerror (D:\Gekko\node_modules\koa\lib\context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by askmike** [comment]
I just released a new version that includes a lot of changes to the sqlite adapter. Can you download that one and see if the error persists?

**Comment by Borrismorris** [comment]
Although not about live trading i have just tried to re update my database by importing new data and i am receiving this error message:

'''D:\Gekko>node gekko --ui

    ______   ________  __    __  __    __   ______
   /      \ /        |/  |  /  |/  |  /  | /      \
  /$$$$$$  |$$$$$$$$/ $$ | /$$/ $$ | /$$/ /$$$$$$  |
  $$ | _$$/ $$ |__    $$ |/$$/  $$ |/$$/  $$ |  $$ |
  $$ |/    |$$    |   $$  $$<   $$  $$<   $$ |  $$ |
  $$ |$$$$ |$$$$$/    $$$$$  \  $$$$$  \  $$ |  $$ |
  $$ \__$$ |$$ |_____ $$ |$$  \ $$ |$$  \ $$ \__$$ |
  $$    $$/ $$       |$$ | $$  |$$ | $$  |$$    $$/
   $$$$$$/  $$$$$$$$/ $$/   $$/ $$/   $$/  $$$$$$/

        Gekko v0.5.14
        I'm gonna make you rich, Bud Fox.


Serving Gekko UI on http://localhost:3000/

  <-- GET /api/imports
  --> GET /api/imports 200 2ms 2b
  <-- GET /api/gekkos
  --> GET /api/gekkos 200 1ms 24b
  <-- GET /api/apiKeys
  --> GET /api/apiKeys 200 1ms 21b
  <-- GET /api/exchanges
  --> GET /api/exchanges 200 333ms 62kb
  <-- GET /assets/select-arrow.png
  --> GET /assets/select-arrow.png 404 2ms -
  <-- POST /api/import
Import 5843628876375115 started
  --> POST /api/import 200 9ms 150b
RECEIVED ERROR IN IMPORT 5843628876375115
{}

![image](https://user-images.githubusercontent.com/40410556/42414839-b67913ce-8236-11e8-956b-33bdbd785315.png)

No idea what has happened

**Comment by Borrismorris** [comment]
Downloaded and re-install latest develop version of gekko after having this error message above, now however the button isnt even present and i cannot import at all
![image](https://user-images.githubusercontent.com/40410556/42414962-5d8cb5ce-8239-11e8-85da-aca5bbe2721f.png)
  <-- GET /api/imports
  --> GET /api/imports 200 2ms 2b
  <-- GET /api/gekkos
  --> GET /api/gekkos 200 0ms 24b
  <-- GET /api/apiKeys
  --> GET /api/apiKeys 200 1ms 2b
  <-- GET /api/exchanges
  --> GET /api/exchanges 200 182ms 8.04kb
  <-- POST /api/scansets
  --> POST /api/scansets 200 36ms 27b
  <-- GET /assets/select-arrow.png
  --> GET /assets/select-arrow.png 404 2ms -
  <-- GET /api/imports
  --> GET /api/imports 200 3ms 2b
  <-- GET /api/gekkos
  --> GET /api/gekkos 200 1ms 24b
  <-- GET /api/apiKeys
  --> GET /api/apiKeys 200 1ms 2b
  <-- GET /api/exchanges
  --> GET /api/exchanges 200 7ms 8.04kb
  <-- GET /api/configPart/performanceAnalyzer
  <-- GET /api/strategies
  --> GET /api/configPart/performanceAnalyzer 200 3ms 144b
  <-- GET /api/configPart/paperTrader
  --> GET /api/configPart/paperTrader 200 1ms 132b
  --> GET /api/strategies 200 6ms 2.13kb
  <-- GET /assets/select-arrow.png
  --> GET /assets/select-arrow.png 404 1ms -
  <-- GET /api/imports
  --> GET /api/imports 200 1ms 2b
  <-- GET /api/gekkos
  --> GET /api/gekkos 200 1ms 24b
  <-- GET /api/apiKeys
  --> GET /api/apiKeys 200 1ms 2b
  <-- GET /api/exchanges
  --> GET /api/exchanges 200 4ms 8.04kb
  <-- GET /api/configPart/candleWriter
  <-- GET /api/configPart/performanceAnalyzer
  --> GET /api/configPart/performanceAnalyzer 200 1ms 144b
  <-- GET /api/strategies
  --> GET /api/configPart/candleWriter 200 7ms 47b
  <-- GET /api/configPart/paperTrader
  --> GET /api/configPart/paperTrader 200 1ms 132b
  --> GET /api/strategies 200 5ms 2.13kb
  <-- GET /api/configPart/performanceAnalyzer
  <-- GET /api/strategies
  <-- GET /api/configPart/paperTrader
  --> GET /api/configPart/performanceAnalyzer 200 4ms 144b
  --> GET /api/configPart/paperTrader 200 2ms 132b
  --> GET /api/strategies 200 6ms 2.13kb
  <-- GET /assets/select-arrow.png
  --> GET /assets/select-arrow.png 404 3ms -
  <-- GET /api/imports
  --> GET /api/imports 200 1ms 2b
  <-- GET /api/gekkos
  --> GET /api/gekkos 200 0ms 24b
  <-- GET /api/apiKeys
  --> GET /api/apiKeys 200 0ms 2b
  <-- GET /api/exchanges
  --> GET /api/exchanges 200 4ms 8.04kb

**Comment by Borrismorris** [comment]
ok now i re-dowloading everything i cannot install it anymore either, not sure what the issue is but here is the err msg.

D:\>cd gekko

D:\gekko>npm install --only=production
module.js:549
    throw err;
    ^

Error: Cannot find module 'D:\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
module.js:549
    throw err;
    ^

Error: Cannot find module 'D:\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

D:\gekko>

**Comment by Borrismorris** [comment]
Your environment has been set up for using Node.js 8.11.3 (x64) and npm.

C:\Windows\System32>npm install windows-build-tools --global --production
module.js:549
    throw err;
    ^

Error: Cannot find module 'D:\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
module.js:549
    throw err;
    ^

Error: Cannot find module 'D:\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

C:\Windows\System32>

**Comment by Borrismorris** [comment]
![image](https://user-images.githubusercontent.com/40410556/42415108-7e5e9350-823c-11e8-9cc9-04777fd138d7.png)

**Comment by Borrismorris** [comment]
![image](https://user-images.githubusercontent.com/40410556/42415113-870ac29e-823c-11e8-84ea-d51f43415d76.png)


2 pictures showing how the button isnt available

**Comment by Borrismorris** [comment]
if theres anything else i can do to help, please let me know

**Comment by Borrismorris** [comment]
After trying all night and multiple things to try and get Gekko ui to come back with the importing etc buttons, its gone from a working program to not working which is really strange????
