### ISSUE TITLE
Gekko UI + Gekko CLI + Redis

### ISSUE THREAD

**Issue by mark-sch** [askmike/gekko#2248]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
One market, one config, one CLI process, this works nice so far, it is importing data and give trade advices. Beside one UI instance is started, the market data from CLI is visible in UI and ready for backtest use. However, the UI is not showing any live data, CLI console output and maybe configured E-Mail notifications is the only way to get informations from the CLI watcher/trader. On all instances Redis is enabled but it was hard to find any info how Redis should help and behave here.

**Expected result** (what you hoped would happen)
Is the Redis pub/sub out of sync in the current devel branch or what is the intended architecture for best CLI integration?

**Actual result** (unexpected outcome)

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
Unfortunately the CLI and UI environment are completely seperated as of right now: All gekkos run in isolation (outside of reading/writing data from the same database). If you want to see a live gekko show up in the UI you have to start it via the UI.

> what is the intended architecture for best CLI integration?

How I (and most people that tell me what they are doing) use Gekko is:

- Use the UI for testing/exploring/simulation/playground.
- Use the CLI interface to run long living real traders (for weeks or months at a time).

A possible solution we could look into is persisting all data from the instance (trades, advices, indicator results) in a DB the UI could simply query. This way it also becomes easier to restart after reboot/crash. What do you think of this?

**Comment by mark-sch** [comment]
Hi Mike, I saw you have some empty functions behind code comments for this already in sqlite plugin. I think it is a very good step to persist important data like backtest and trades into the db. An awsome feature will be to stitch together backtest data from the past with all upcoming (live) trades into a graph. Or to continue backtesting and see how close the live trading was. Or just to see your live trades visually. Even the CLI version could show very useful informations to the user with this persisted data.
