### ISSUE TITLE
emailjs missing in dependencies

### ISSUE THREAD

**Issue by devben-io** [askmike/gekko#2249]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[X] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
- enable mailer  in `config.js` with
  ```
  config.mailer = {
    enabled: true,       // Send Emails if true, false to turn off
    sendMailOnStart: true,    // Send 'Gekko starting' message if true, not if false
  ```
 
- run gekko with `node gekko --config config.js`

**Expected result** (what you hoped would happen)
- sending emails on startup (and in general)

**Actual result** (unexpected outcome)
- got error message on startup:
```
[...]
2018-06-21 10:00:14 (INFO):	Setting up:
2018-06-21 10:00:14 (INFO):		 Mailer
2018-06-21 10:00:14 (INFO):		 Sends you an email everytime Gekko has new advice.
2018-06-21 10:00:14 (ERROR):	ERROR LOADING DEPENDENCY emailjs

 ERROR: The plugin mailer expects the module emailjs to be installed. However it is not, install it by running:

 	npm install emailjs@1.0.5
```

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
- used gekko with docker-compose (current "develop" branch)
- tried to add `"emailjs": "1.0.5",` in `package.json` => also errors

**Comment by askmike** [comment]
Dependencies of plugins are not part of package.json to limit the amount of code that needs to be installed for a default gekko installation (if you need the emailer just follow the message it prints).

If that does not solve it please comment here.

**Comment by devben-io** [comment]
hmmm, but I think a docker image should be "complete" - without installing any packages after starting the container.
Then we should add emailjs in the Dockerfile.
Like this:
```
[...]
# Install app dependencies
COPY package.json /usr/src/app
RUN npm install --production && \
    npm install --production redis@0.10.0 talib@1.0.2 tulind@0.8.7 emailjs@1.0.5 pg && \
    npm cache clean --force
[...]
```
