### ISSUE TITLE
Use ccxt trading library

### ISSUE THREAD

**Issue by bohdanzahurskyi1** [askmike/gekko#2253]
**I'm submitting a ...**
question about the decisions made in the repository
Why you don't use this library for provide unified exchange api, it's very popular
gitHub: https://github.com/ccxt/ccxt?

**Comment by yuripinto** [comment]
@bohdanz1997, look this following issue https://github.com/askmike/gekko/issues/1171

**Comment by askmike** [comment]
dup of #1171.
