### ISSUE TITLE
Issue running Gekko after install.  Is this a node issue?

### ISSUE THREAD

**Issue by waves1280** [askmike/gekko#2254]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[*] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)

Hi all,

I am trying to run gekko on a windows 10 machine using the basic download and install options.  When I try to run the program with the command "node gekko --ui", I get the following.  

![image](https://user-images.githubusercontent.com/39778545/41799037-c21cf790-7624-11e8-81f1-81ba6aff5406.png)

I downloaded the dependencies correctly, so I think I might have downloaded the wrong version of node, or maybe I need to change something in the command prompt to run gekko correctly.  Please help!

**Comment by askmike** [comment]
is there another directory inside `Downloads/gekko-develop` called `gekko-develop`? If so run:

    cd gekko-develop
    node gekko --ui

Note: I just released a new version with a lot of upgrades, you might want to download that one :)
