### ISSUE TITLE
Is not exchanges  directory in pre-v0.6 branch 

### ISSUE THREAD

**Issue by davewang** [askmike/gekko#2255]
https://github.com/askmike/gekko/blob/b9d4c2aa9d52223cc188522d29f19a4718841ee1/web/routes/exchanges.js#L15

**Comment by bohdanzahurskyi1** [comment]
Also in this branch defined plugin childToParent:
  {
    name: 'Child to parent',
    description: 'Relays events from the child to the parent process',
    slug: 'childToParent',
    async: false,
    modes: ['realtime']
  }
but it doesn't exists in plugins directory

**Comment by askmike** [comment]
Yep that was a WIP branch and UI/webserver stuff got fixed last. But everything is in place now :)
