### ISSUE TITLE
Error when installing Gekko

### ISSUE THREAD

**Issue by KorayiDC** [askmike/gekko#2256]
hey there, So I just wanted to install the newest version of Gekko and I got this error message

link to the full error message: [error message](http://textuploader.com/dzrzr)

Does someone know what I did wrong?

**note: I already had some issues with node before and thats why I had to install node again**

**Comment by askmike** [comment]
Can you try with node LTS version 8.11.3? Your system seems unable to compile sqlite, but maybe (depending on your platform) mapbox has a precompiled version for the node LTS.

If that doesn't work, please comment here and I will reopen.
