### ISSUE TITLE
GEKKO ERROR: Child process has died. 

### ISSUE THREAD

**Issue by mahdi-maza** [askmike/gekko#2259]
when i tried to start a live a get this errore ( GEKKO ERROR: Child process has died.) the live is in binance 

Serving Gekko UI on http://localhost:3000/

  <-- GET /api/imports
  --> GET /api/imports 200 4ms 2b
  <-- GET /api/gekkos
  --> GET /api/gekkos 200 2ms 2b
  <-- GET /api/gekkos
  --> GET /api/gekkos 200 1ms 2b
  <-- GET /api/apiKeys
  --> GET /api/apiKeys 200 2ms 11b
  <-- GET /api/exchanges
  --> GET /api/exchanges 200 2,219ms 106.21kb
  <-- GET /api/configPart/candleWriter
  <-- GET /api/configPart/performanceAnalyzer
  --> GET /api/configPart/candleWriter 200 6ms 47b
  --> GET /api/configPart/performanceAnalyzer 200 4ms 144b
  <-- GET /api/strategies
  <-- GET /api/configPart/paperTrader
  --> GET /api/configPart/paperTrader 200 5ms 132b
  --> GET /api/strategies 200 15ms 3.48kb
  <-- POST /api/startGekko
Gekko 999954020320737 started
  --> POST /api/startGekko 200 20ms 146b
  <-- POST /api/startGekko
Gekko 442458707578727 started
  --> POST /api/startGekko 200 6ms 458b
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: SQLITE_BUSY: database is locked
RECEIVED ERROR IN GEKKO 442458707578727
Child process has died.

**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[* ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)

**Expected result** (what you hoped would happen)

**Actual result** (unexpected outcome)

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
Unfortunately there are some limitations on how many Gekkos (live, import & backtest) you can run at the same time using the default sqlite adapter. We'll update documentation on how to use another database.

How many gekkos where you running when this happened?

**Comment by mahdi-maza** [comment]
@askmike ,  i run just one gekko

i did a new installation and tried again and it give me the same error

**Comment by mahdi-maza** [comment]
i tried it again it give me this error 
GEKKO ERROR: 

Gekko encountered an error and can't continue

this is the cmd code 

`C:\Users\Mahdi Maza\Desktop\gekko>node gekko --ui

    ______   ________  __    __  __    __   ______
   /      \ /        |/  |  /  |/  |  /  | /      \
  /$$$$$$  |$$$$$$$$/ $$ | /$$/ $$ | /$$/ /$$$$$$  |
  $$ | _$$/ $$ |__    $$ |/$$/  $$ |/$$/  $$ |  $$ |
  $$ |/    |$$    |   $$  $$<   $$  $$<   $$ |  $$ |
  $$ |$$$$ |$$$$$/    $$$$$  \  $$$$$  \  $$ |  $$ |
  $$ \__$$ |$$ |_____ $$ |$$  \ $$ |$$  \ $$ \__$$ |
  $$    $$/ $$       |$$ | $$  |$$ | $$  |$$    $$/
   $$$$$$/  $$$$$$$$/ $$/   $$/ $$/   $$/  $$$$$$/

        Gekko v0.5.14
        I'm gonna make you rich, Bud Fox.


Serving Gekko UI on http://localhost:3000/

  <-- GET /api/imports
  --> GET /api/imports 200 6ms 2b
  <-- GET /api/gekkos
  --> GET /api/gekkos 200 1ms 2b
  <-- GET /api/gekkos
  --> GET /api/gekkos 200 1ms 2b
  <-- GET /api/exchanges
  <-- GET /api/apiKeys
  --> GET /api/apiKeys 200 1ms 11b
  --> GET /api/exchanges 200 2,161ms 106.21kb
  <-- GET /api/configPart/candleWriter
  <-- GET /api/configPart/performanceAnalyzer
  --> GET /api/configPart/candleWriter 200 9ms 47b
  <-- GET /api/strategies
  --> GET /api/configPart/performanceAnalyzer 200 9ms 144b
  <-- GET /api/configPart/paperTrader
  --> GET /api/configPart/paperTrader 200 2ms 132b
  --> GET /api/strategies 200 18ms 2.84kb
  <-- POST /api/startGekko
Gekko 915159322549672 started
  --> POST /api/startGekko 200 17ms 146b
  <-- POST /api/startGekko
Gekko 7680945150905867 started
  --> POST /api/startGekko 200 9ms 459b
RECEIVED ERROR IN GEKKO 7680945150905867


Gekko encountered an error and can't continue


Gekko encountered an error and can't continue

Error:

[binance.js] Error -1022: Signature for this request is not valid.

Meta debug info:

Gekko version: v0.5.14
Nodejs version: v8.11.3`

**Comment by mahdi-maza** [comment]
i did a 3rd try he give me this error 

GEKKO ERROR: 
 ERROR: Error: SQLITE_BUSY: database is locked

`Microsoft Windows [Version 10.0.17134.112]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\Mahdi Maza>cd desktop

C:\Users\Mahdi Maza\Desktop>cd gekko

C:\Users\Mahdi Maza\Desktop\gekko>node gekko --ui

    ______   ________  __    __  __    __   ______
   /      \ /        |/  |  /  |/  |  /  | /      \
  /$$$$$$  |$$$$$$$$/ $$ | /$$/ $$ | /$$/ /$$$$$$  |
  $$ | _$$/ $$ |__    $$ |/$$/  $$ |/$$/  $$ |  $$ |
  $$ |/    |$$    |   $$  $$<   $$  $$<   $$ |  $$ |
  $$ |$$$$ |$$$$$/    $$$$$  \  $$$$$  \  $$ |  $$ |
  $$ \__$$ |$$ |_____ $$ |$$  \ $$ |$$  \ $$ \__$$ |
  $$    $$/ $$       |$$ | $$  |$$ | $$  |$$    $$/
   $$$$$$/  $$$$$$$$/ $$/   $$/ $$/   $$/  $$$$$$/

        Gekko v0.5.14
        I'm gonna make you rich, Bud Fox.


Serving Gekko UI on http://localhost:3000/

  <-- GET /api/gekkos
  --> GET /api/gekkos 200 16ms 2b
  <-- GET /api/imports
  --> GET /api/imports 200 2ms 2b
  <-- GET /api/gekkos
  --> GET /api/gekkos 200 1ms 2b
  <-- GET /api/exchanges
  --> GET /api/exchanges 200 2,179ms 106.21kb
  <-- GET /api/apiKeys
  --> GET /api/apiKeys 200 2ms 11b
  <-- GET /api/configPart/candleWriter
  <-- GET /api/configPart/performanceAnalyzer
  <-- GET /api/strategies
  <-- GET /api/configPart/paperTrader
  --> GET /api/configPart/candleWriter 200 12ms 47b
  --> GET /api/configPart/performanceAnalyzer 200 12ms 144b
  --> GET /api/configPart/paperTrader 200 11ms 132b
  --> GET /api/strategies 200 31ms 2.84kb
  <-- POST /api/startGekko
Gekko 894607979520289 started
  --> POST /api/startGekko 200 16ms 146b
  <-- POST /api/startGekko
Gekko 992030355615864 started
  --> POST /api/startGekko 200 8ms 458b
RECEIVED ERROR IN GEKKO 992030355615864

 ERROR: Error: SQLITE_BUSY: database is locked



 ERROR: Error: SQLITE_BUSY: database is locked`

**Comment by mahdi-maza** [comment]
it give me those three errors

**Comment by Mahmud1985** [comment]
@askmike Hi how are you ?
I have same problem with @mahdi-maza I did new installed too.

**Comment by askmike** [comment]
database is locked is a hard error to deal with, especially if you are using windows. 

The only thing I can recommend trying is opening this file:

https://github.com/askmike/gekko/blob/b3898555cc7db8e0690c141fea23896594ebc5e5/web/routes/baseConfig.js#L42

And changing that line to:

    journalMode: 'WAL',

If that doesn't work the only thing is to wait for 0.6 (see #2216) where we have better support for other databases.

**Comment by mahdi-maza** [comment]
@askmike i try it and it work 
thank you for your support
