### ISSUE TITLE
Add Lineair regression curve as basic indicator.

### ISSUE THREAD

**Issue by consp** [askmike/gekko#226]
The advantage of a LRC over EMA is that it does not lag (as much or not at all) as EMA. It might be wrong sometimes so you need to carefully look into how to implement this and pick your depth (e.g. history size). Might be drop in replacable for EMA but I do not know sufficient things about market economics to verify this.

I did it in my own repository and I'm running tests now to see how it does work (seems to).
Check consp/gekko@45e108bc156e556b137078d41f837c42e205dca9 for the indicator.

**Comment by micxer** [comment]
@consp  Any news on this? Does it work as expected?

**Comment by consp** [comment]
Yes, and maybe. It works in the sense that it provides a bit more accurate
estimate and doesn't lag as much as the average (EMA) filters if used as
such. Maybe as the code might still contain errors and it relies on the
underlying method for proper functioning.
A linear regression curve does need some form of additional processing to
indicate the up/down trend and is a bit different than other means of
calculating the trend. A implementation example can be found at
http://www.onlinetradingconcepts.com/TechnicalAnalysis/LinRegCurve.html
Some of my code tries this and uses the LRC basic indicator for this.

If you include it, I would clearly mark it as experimental. Though probably
all auto-trading software is anyways. If you combine it with additional
methods (if supported) it would probably be better, though it did give me a
small profit margin compared to some other methods.

Note: Some versions of the code online implementing this might run one time
index too far (it becomes a predictor instead of an estimator).

2015-02-03 13:26 GMT+01:00 Michael Weinrich <notifications@github.com>:

> @consp <https://github.com/consp> Any news on this? Does it work as
> expected?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/askmike/gekko/issues/226#issuecomment-72642136>.
>



-- 
Mvg,

Tristan Timmermans

m: *tristan@famtimmermans.net <tristan@famtimmermans.net>*

**Comment by micxer** [comment]
Sounds good. I want to start with a test anyway, so if it's somewhat working, I will give it a try.

**Comment by askmike** [comment]
I am not sure what kind of testing you are talking about, but: For most
indicators Gekko is using unit tests where it asserts the indicators
calculate the same numbers as pre calculated values (using MS excel). This
is present in the old version, but the new version uses a different testing
framework (mocha instead of node unit). If you are thinking about adding
those kind of tests tests, please take a look at the new branch:

https://github.com/askmike/gekko/blob/candle-rewrite/test/indicators.js

**Comment by bugron** [comment]
@askmike this issue can be closed as you merged those commits.

**Comment by askmike** [comment]
Yes, thanks
