### ISSUE TITLE
Custom Strategy to sell any ALTS based on Bitcoin price breaking support

### ISSUE THREAD

**Issue by Mytechshout** [askmike/gekko#2260]
Hi ,
I downloaded gekko but i cannot trade based on price of btc.
I wanted to create this simple strategy  but i don't know whether this is possible in gekko as gekko trades using signals and not based on price of btc. 
Here is what i need . 
Set a Bitcoin support price example 5000$ 
if price of btc goes below 5000$ sell an Altcoin.
If btc goes back above 5000$ buy the sold altcoin.

I think this will be helpful as all altcoins dump during btc breaking major support. I would have saved 20% today if this was possible. 

I am sure others are looking for the same. Anyone can comeup with this. 

Thanks.

**Comment by Tommixoft** [comment]
your logic is apposite..you sell low and buy high ;D

**Comment by 151henry151** [comment]
I can't help you code this, but I maybe could advise that you should probably take this kind of inquiry to the forum ( https://forum.gekko.wizb.it/ ) instead of using the bug and issue tracker.

**Comment by mark-sch** [comment]
@Mytechshout  You want to buy/sell an altcoin taking the signals from bitcoin?

**Comment by askmike** [comment]
as @151henry151 said, please ask this on the forum. This is the bug tracker of the core software.
