### ISSUE TITLE
Live trade doesn't start setting up from the Gekko UI (Windows 10 - Ubuntu)

### ISSUE THREAD

**Issue by ghost** [askmike/gekko#2262]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[X] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Hi there. I am experiencing a strange behavior from gekko in trade mode. I've installed gekko on ubuntu on windows 10 and patched it with cloggy45/Gekko-Bot-Resources
strategy with its custom parameters. Candle Size 2 hours and warmup to 4 hours. Backtesting is working fine but when i start a live trade, it doesnt show any setup phase and i've waited some times to see if it would be the warmup phase, but no, it has been running for 1 day and 6 hours and it still doesn't trade. API is set correctly, i'm trading on kraken.

Edit: The bot DID trade 4 times but then it crashed and it didn't register the trade in the UI.

**Expected result** (what you hoped would happen)
It should trade and show the outcome in the UI, also it shouldn't crash after a few minutes

**Actual result** (unexpected outcome)

  --> POST /api/backtest 200 14s 117.32kb
  <-- GET /api/configPart/candleWriter
  <-- GET /api/configPart/performanceAnalyzer
  --> GET /api/configPart/candleWriter 200 2ms 47b
  --> GET /api/configPart/performanceAnalyzer 200 2ms 144b
  <-- GET /api/strategies
  --> GET /api/strategies 200 7ms 2.89kb
  <-- GET /api/configPart/paperTrader
  --> GET /api/configPart/paperTrader 200 1ms 132b
  <-- POST /api/startGekko
Gekko 743566464900794 started
  --> POST /api/startGekko 200 21ms 145b
  <-- POST /api/startGekko
Gekko 836178944386288 started
  --> POST /api/startGekko 200 16ms 360b
  <-- POST /api/getCandles
  --> POST /api/getCandles 200 288ms 2b
  <-- POST /api/getCandles
  <-- POST /api/getCandles
  --> POST /api/getCandles 200 326ms 35.31kb
{ Error: SQLITE_ERROR: no such column: NaN errno: 1, code: 'SQLITE_ERROR' }

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Im new to coding so i don't understand fully what is going on in there, maybe someone could clarify all this for me, i'd be glad to learn from it!

**Comment by askmike** [comment]
I thhink this is fixed in 0.6 Please download the latest release, install it and try again :)

**Comment by askmike** [comment]
If that doesn't work just comment here.

**Comment by macktastic** [comment]
I'm trading on Kraken and the bot is saying insufficient funds to fulfill the order even though there is plenty of each asset in the account
