### ISSUE TITLE
Bittrex exchange - Market watcher not keeping up to date - ETH/DGB pair

### ISSUE THREAD

**Issue by Borrismorris** [askmike/gekko#2264]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
tried to start market watcher/live trader for bittrex exchange, ETH/DGB

**Expected result** (what you hoped would happen)
it would update minute for minute

**Actual result** (unexpected outcome)
lagging behind the actual time, considering im trading in minute candles this can happen at up to 20 minutes at a time

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Running on windows, on node.js, running on the develop gekko. Live trading us working, having no error reports there, just the issue is that i cannot seem to connect at a steady rate.

**Comment by askmike** [comment]
This has to do with how Gekko aggregates Data:

1. Gekko watches the markets by checking all historical trades that happened.
2. These trades get aggregated into 1 minute candles.
3. These candles are aggregated into bigger ones (based on what you configure).

In step 2 Gekko can only calculate candles once a trade from another minute comes in: If there is no trade after 12:00 until 12:10 than as soon as Gekko detects the new trade at 12:10 it will generate candles for 12:00 until 12:09, as Gekko can only be sure that no trade happened before 12:10 until this new trade comes in.

You will only really see this as a problem if:

- You are trading on a market without a lot of trades AND
- You are trading on a low resolution (candle size)

NOTE: I just released a new version, it does NOT have bittrex support right now but I'm working on that very soon.

**Comment by askmike** [comment]
This has to do with how Gekko aggregates Data:

1. Gekko watches the markets by checking all historical trades that happened.
2. These trades get aggregated into 1 minute candles.
3. These candles are aggregated into bigger ones (based on what you configure).

In step 2 Gekko can only calculate candles once a trade from another minute comes in: If there is no trade after 12:00 until 12:10 than as soon as Gekko detects the new trade at 12:10 it will generate candles for 12:00 until 12:09, as Gekko can only be sure that no trade happened before 12:10 until this new trade comes in.

You will only really see this as a problem if:

- You are trading on a market without a lot of trades AND
- You are trading on a low resolution (candle size)

NOTE: I just released a new version, it does NOT have bittrex support right now but I'm working on that very soon.
