### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by Kris191** [askmike/gekko#2265]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Tried to start gekko on gdax exchange

**Expected result** (what you hoped would happen)
Normal Trading

**Actual result** (unexpected outcome)
Error report see below code output

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

`(node:17023) DeprecationWarning: `getProductTrades()` now requires a product ID as the first argument. Attempting to use PublicClient#productID (BTC-EUR) instead.
`

**Comment by askmike** [comment]
Thanks for the report! This is already fixed in 0.6 which I will release in a few hours (see #2216 for details).
