### ISSUE TITLE
Dockerfile missing gekko broker deps?

### ISSUE THREAD

**Issue by bald123** [askmike/gekko#2278]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ ] bug report
[x ] question about the decisions made in the repository

**Action taken** (what you did)
I read the upgrade guide on the gekko forum, and inspected the Dockerfile afterwards. It seems that the exchange dependencies are not included in the Dockerfile, as pointed out on the forum. Not able to verify this myself for the coming days though unfortunately, but it might be an issue...

**Expected result** (what you hoped would happen)
That the broker deps would be installed in the Dockerfile (cd exchange, npm install).

**Actual result** (unexpected outcome)
Can not verify IRL now, but by looking at the code I expect that this might be an issue.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

I read the upgrade guide here:
https://forum.gekko.wizb.it/thread-56830-post-59296.html#pid59296

It says:
```
cd gekko
git checkout develop # most stable branch right now
git pull
npm install --only=production
# install gekko broker deps
cd exchange
npm install --only=production
# UIConfig location has moved
# only do this if you had a non default UIconfig:
mv web/vue/UIconfig.js mv web/vue/public/UIconfig.js
```

Seems that this is not included in the Dockerfile.

**Comment by askmike** [comment]
nice catch! I fixed this in the latest develop branch. I will push out a minor release for this fix (and others) asap.
