### ISSUE TITLE
Send notification from my strategy

### ISSUE THREAD

**Issue by thanhlmm** [askmike/gekko#2284]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ ] bug report
[ ] question about the decisions made in the repository
[x] feature request

**Action taken** (what you did)
Sometimes, I need to get more information currently running in my strategy (New advice with additional information, current status of my running strategy,...). So I need a function for send notification to my plugin (Slack, Email, Discord,...).

**Expected result** (what you hoped would happen)
`this.notice('Hello, I can send additional information here!');` and I can see that `notification` in Slack or Email

**Actual result** (unexpected outcome)
None

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
None

**Comment by askmike** [comment]
great idea, discussion on implementation in #2285.
