### ISSUE TITLE
Kraken: "This exchange is not yet supported"

### ISSUE THREAD

**Issue by PhunkyBob** [askmike/gekko#2286]
**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
I run Gekko since 6 months and it worked fine with Binance and Kraken.
I wanted to use new pairs available on Binance, so I updated Gekko from the repository (develop).
I had several issue (not compatible with my NodeJS version, ...) but I succeded to make it work.

But when I use my existing strategy on Kraken, it says:
"
Gekko encountered an error and can't continue
Error:
This exchange is not yet supported
"

I tried to install, delete, reinstall "kraken-api", "kraken-api-es5", run "update-kraken.js", ... nothing works.

Note : if I don't enable the live trade, it works.

**Expected result** (what you hoped would happen)
Be able to trade on Kraken.

**Actual result** (unexpected outcome)
Can't trade on Kraken.

Gekko version: v0.6.1
Nodejs version: v8.11.3

**Comment by askmike** [comment]
Gekko went through a major update, it is now required to install exchange dependencies separately like so:

    cd exchange
    npm install --only=production

See [here](https://gekko.wizb.it/docs/installation/installing_gekko.html#Installing-Gekko-39-s-dependencies) or [here](https://gekko.wizb.it/docs/installation/updating_gekko.html#Updating).

**Comment by PhunkyBob** [comment]
I've obviously done that.
Still, it doesn't work when I'm
`config.trader = {
  enabled: true,
`
But if set "enabled: false", it's OK (but there is no trade made).

**Comment by PhunkyBob** [comment]
Steps to reproduce:
- git clone + all the steps in the documentation
```
git clone https://github.com/askmike/gekko.git
cd gekko/
npm install --only=production
cd exchange/
npm install --only=production
cd ..
```

- edit "sample-config.js" to replace watch with
```
  exchange: 'kraken',
  currency: 'EUR',
  asset: 'ETH',
```
- Run `node gekko --config sample-config.js`
--> it works

- edit "sample-config.js" to replace trader with
```
enabled: true,
```
and 
```
config['I understand that Gekko only automates MY OWN trading strategies'] = true;
```
- Run `node gekko --config sample-config.js`
--> it fails

**Comment by askmike** [comment]
Apologies, it's now fixed in the latest develop. You can pull that or wait for 0.6.2 which I will release tomorrow!

**Comment by PhunkyBob** [comment]
I confirm: after your fix, it works.

Thank you for your reactivity!
