### ISSUE TITLE
Backtest Result Date is always: 1970-01-18

### ISSUE THREAD

**Issue by xbromy** [askmike/gekko#2291]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Doing backtest with 0.6.2

**Expected result** (what you hoped would happen)
Having the right result

**Actual result** (unexpected outcome)
all table entries are of date: 1970-01-18 

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
Entry at (UTC)	Exit at (UTC)	Exposure	Entry balance	Exit balance	P&L	Profit
1970-01-18 16:42	1970-01-18 16:42	10 minutes	100.287	100.148	0.14	-0.14%
1970-01-18 16:43	1970-01-18 16:43	4 hours	99.998	97.923	2.07	-2.07%

**Comment by askmike** [comment]
Oops! Fixed in latest develop.
