### ISSUE TITLE
ETH/EOS pair gone on Binance

### ISSUE THREAD

**Issue by dominik-fr** [askmike/gekko#2294]
Seems like ETH/EOS pair on Binance is gone from .json file - currently there is no way to import/watch/trade ETH/EOS.

**Comment by PhunkyBob** [comment]
```
cd exchange/util/genMarketFiles
node update-binance.js
```

**Comment by dominik-fr** [comment]
Yup, that seems to work :)

**Comment by askmike** [comment]
Will update them again in the main and be sure they'll be included in the next release. Apologies! But as this is an easy local fix I'll close this already.
