### ISSUE TITLE
Where to change default feeMaker and feeTrader

### ISSUE THREAD

**Issue by xbromy** [askmike/gekko#2295]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ ] bug report
[x ] question about the decisions made in the repository

I want to change the fees to have it by default.
I'm running ui version.
Can I do it in UIConfig?
Or in code? Where? How?

**Action taken** (what you did)
Searched the code...

**Expected result** (what you hoped would happen)

**Actual result** (unexpected outcome)

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
In the UI: the UI builds a dynamic config based on this TOML file: https://github.com/askmike/gekko/blob/develop/config/plugins/paperTrader.toml
