### ISSUE TITLE
[BUG] Backetest onTrade not longer working

### ISSUE THREAD

**Issue by julesGoullee** [askmike/gekko#2299]
In startegy, the method onTrade is never call (from dev branch)

**Comment by askmike** [comment]
The event system has totally changed since 0.6. Will fix this asap, the gist is that there is no single trade event anymore, the closest event to it now is [tradeCompleted](https://gekko.wizb.it/docs/internals/events.html#tradeCompleted-event).

**Comment by julesGoullee** [comment]
The doc is not clear, I already try inside strat init: this.on('tradeCompleted', ftc) not working

**Comment by askmike** [comment]
Note that onTrade was an experimental feature never officially part of
Gekko (eg. in the documentation). Could you specify what you don't find
clear about the docs? Events are low level communication objects between
plugins, and your strategy is not a plugin. As such your strategy cannot just
subscribe to all events.

> this.on('tradeCompleted', ftc)

I'm not sure why you though this would work, is there anything in the docs
indicating that it would? If so we should fix that.

-

Instead what we need to do is subscribe to that event in the plugin that
runs the strat (it's called the tradingAdvisor) and pass the event through
to your strat (using the experimental `onTrade` API or create a better
one). After that we should standardize it (make it part of the docs, etc).

**Comment by julesGoullee** [comment]
Ok thx, 
I talking about event, the interface/response are perfect doc but how to use it, example of call, where in the code are missing

**Comment by julesGoullee** [comment]
https://github.com/askmike/gekko/blob/develop/plugins/tradingAdvisor/tradingAdvisor.js#L75 ?

**Comment by askmike** [comment]
That's true. the document doesn't really talk about the fact that events are to be consumed by plugins. I will try to update it (since events now also show up in the UI through the websocket).

I'll take a look at fixing this specific issue, possibly together with figuring out a nice API for information from stoploss orders: https://forum.gekko.wizb.it/thread-57314.html

**Comment by askmike** [comment]
I just pushed some code to Github, I updated internal event references from `trade` to `tradeCompleted`, but your strat still requires a `processTrade` function (for now). Note that the event your strat receives will be something like this:

    TRADE RECEIVED BY processTrade: { id: 'trade-1557',
      adviceId: 'advice-1557',
      action: 'sell',
      cost: 0.08973010309976918,
      amount: 0.10449138745985681,
      price: 571.62929962,
      portfolio: { asset: 0, currency: 59.73033863 },
      balance: 59.73033863,
      date: moment("2016-08-19T12:37:00.000"),
      effectivePrice: 570.7718556705701,
        feePercent: 0.15 }

The legacy trade event does not exist anymore. Closing this for now :)

NOTE: this API might change, consider it experimental until it is part of the docs. The future of this func will depend on implementation of stop losses.
