### ISSUE TITLE
Documentation for candleSize/History

### ISSUE THREAD

**Issue by chevinbrown** [askmike/gekko#230]
There's not a good explanation of exactly how gekko uses candleSize...or at least, I don't have the base understanding to get it. 

Candlesize (in config) means how many candles until it begins trading live? If candleSize is too low, will the trading advisor give poor advice? Will a low candle count skew the actual market conditions? Please advise.

**Comment by askmike** [comment]
There is no recommended setting, Gekko is a tool you can use when you know what settings you want (or you can use it to try a bunch).
