### ISSUE TITLE
Feature request: manual buy/sell option in GUI & strategy pause

### ISSUE THREAD

**Issue by bald123** [askmike/gekko#2300]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x] feature request
[ ] bug report
[ ] question about the decisions made in the repository

I was wondering, now the GUI supports stopping live Gekko's, would it be a nice feature to implement a manual "long" or "short" button for each live Gekko? This would make sense because:

- When I want to stop a live Gekko to adjust a parameter for example, the last action of that strategy might have been a "long". It would be very nice to have the possibility to manual "short", so that you can immediately start your newly configured Gekko again (without having to login at the exchange, and manually sell).
- When SHTF, and your strategy does not react correctly, you can "panic sell" (or FOMO buy) manually.

Now a live Gekko can be stopped, I was expecting a "resume" button or the like as well, but instead the Gekko can only be deleted. When no manual intervention is being done at the exchange, are there any obstacles why a "pause strategy" functionality wouldn't work or doesn't make sense?

My compliments for the software and the way you guys are working on this project.

**Comment by askmike** [comment]
> When I want to stop a live Gekko to adjust a parameter for example, the last action of that strategy might have been a "long". It would be very nice to have the possibility to manual "short", so that you can immediately start your newly configured Gekko again (without having to login at the exchange, and manually sell).

You don't need to do this perse: if your money is in the asset (long) you can restart gekko fine, it will simply not trade on advices if you are already long ("exposed"). In that case you will see a log message saying "'NOT buying, already exposed'".

> When SHTF, and your strategy does not react correctly, you can "panic sell" (or FOMO buy) manually.

The main problem I see is that I really want Gekko to behave deterministically, eg. there should not be any differences in multiple people running exactly the same configuration (or you running live now and later backtesting present). The other big problem is that we are slowly giving more information to strategies regarding trade execution (see [this thread](https://forum.gekko.wizb.it/thread-57314.html) for example), this is going to be very complicated for everyone unless it is very clear when a strategy can receive certain information. For example:

What if there are a buy/sell buttons in the UI and a user keeps pressing them, how should the strategy react on this? If the strat says GO LONG and you sell everytime the strategy might just say GO LONG again (or should it be prevented from doing this? For how long? etc).

------

What about another idea:

Once you stop a live gekko and you are exposed (money in long position), Gekko can ask you whether it should get out of the position by selling the assets. I think that there is a user choice whether SHTF or it's fine to continue, in the second case I think it's better to stop the gekko completely until the user figured out what to do.

**Comment by bald123** [comment]
Thank you! 

> You don't need to do this perse: if your money is in the asset (long) you can restart gekko fine, it will simply not trade on advices if you are already long ("exposed"). In that case you will see a log message saying "'NOT buying, already exposed'".

Ok that's clear. Your strategy and your assets may be out-of-sync for some time (your strategy might react differently when it knows it's long or short), but that is up to the strategy implementation.

> The main problem I see is that I really want Gekko to behave deterministically, eg. there should not be any differences in multiple people running exactly the same configuration (or you running live now and later backtesting present). The other big problem is that we are slowly giving more information to strategies regarding trade execution (see this thread for example), this is going to be very complicated for everyone unless it is very clear when a strategy can receive certain information.

Ok, clear as well.

> Once you stop a live gekko and you are exposed (money in long position), Gekko can ask you whether it should get out of the position by selling the assets

Haha, my request for buttons et al. literally started with this idea, but soon it grew bigger. But this is indeed the reason why I came up with this request. Just to prevent having to manually login at the exchange to sell your assets. I like this idea.

Regarding the resume functionality: I currently have a strategy with quite some parameters. It just became annoying to enter all of the parameters again each time I stopped a Gekko (for whatever reason), but since this is not happening all days, I'm perfectly fine with it.

**Comment by askmike** [comment]
> Regarding the resume functionality: I currently have a strategy with quite some parameters. It just became annoying to enter all of the parameters again each time I stopped a Gekko (for whatever reason), but since this is not happening all days, I'm perfectly fine with it.

In the design for the new UI there exists already another button: start a new gekko based on "this one" (this one can archived, eg. stopped a while ago and not running anymore.

----

So what about these 2 new features:

- When stopping a running Gekko and the funds are in the asset: ask the user whether the sell the assets back as to remove exposure.
- A "copy gekko" button that takes you to the "new live gekko" screen with the same market + strategy + parameters?

**Comment by mark-sch** [comment]
To add a manual buy/sell button into any plugin is basically a one-liner, due to the event nature of Gekko:

this.emit('advice', { recommendation: 'short' });

You need to register emits: ['advice'] in plugin.js. I added this feature yesterday with the same idea in mind: To have a quick option to buy/sell when being on the mobile phone and to have a debugging feature for gekko...but I use it only just before I stop gekko to adjust further things.

 See it in action here with telegram integration:
[Screenshot](https://github.com/mark-sch/gekko/blob/develop/screenshots/Screenshot_2018-07-12-17-56-23.jpg)

**Comment by bald123** [comment]
So just to be sure, when I want to sell when in a long position (regardless of what the strategy wants), I can just sell via the exchange itself and the strategy will reaume “normally” (so when the strategy actually goes short it notices that the asset is already sold and continues until a new long advice is given)?

**Comment by nicolasbonnici** [comment]
You can do it directly with your strategy parameters. Use them to override your strategy default value and directly sell before buy if needed.

**Comment by ampyxx** [comment]
Bump! Will it automatically short or long if you buy/sell manually?
