### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by alexandershalin** [askmike/gekko#2306]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Open https://gekko.wizb.it/docs/installation/installing_gekko.html and click "See the updating Gekko doc." at the bottom of the page.

**Expected result** (what you hoped would happen)

Link should lead to appropriate page.

**Actual result** (unexpected outcome)

Link leads to 404 page.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
Ah yes, nice catch. It should lead to this page: https://gekko.wizb.it/docs/installation/updating_gekko.html.
