### ISSUE TITLE
Errors when starting new trades on CEX w/ LTC/NMC

### ISSUE THREAD

**Issue by chevinbrown** [askmike/gekko#231]
I didn't catch the errors exactly, but I modified the exchanges to work with LTC & NMC. When starting the script with a new CEX account trading either NMC or LTC (the asset value will be 0.00 for either) it throws an error when trying to call `LTC.amount`, etc. I suppose that's an issue from cex?

**Comment by askmike** [comment]
LTC and NMC where never supported with gekko, at this moment. cex.io doesn't work at all.
