### ISSUE TITLE
Unable to use Importer with Kraken

### ISSUE THREAD

**Issue by dcampogiani** [askmike/gekko#2311]
**I'm submitting a ...**
[X] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
- git clone git://github.com/askmike/gekko.git -b stable
- cd gekko
- npm install --only=production
- cd exchange
- npm install --only=production
- edit nano web/baseUIconfig.js and nano web/vue/dist/UIconfig.js (I'm running headless on raspberry Pi 2)
 - node gekko --ui
 - use web UI to add kraken api key
 - select local data
 - select "Go to importer"
 - select Kraken as Exchange, select EUR as Currency, select XRP as Asset and leave date range as is

**Expected result** (what you hoped would happen)
Data being imported in gekko

**Actual result** (unexpected outcome)
 - Popup in browser with message >IMPORT ERROR: [object Object]
 - Log in terminal 
```<-- POST /api/import
Import 3674826382574277 started
  --> POST /api/import 200 22ms 148b
RECEIVED ERROR IN IMPORT 3674826382574277
{ code: 'MODULE_NOT_FOUND' }
```

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

- I can import data using other an other exchange, for example I have no issue using poloniex:USDT/BTC

 - Using Gekko v0.6.2 and Gekko UI v0.2.2.

**Comment by askmike** [comment]
Thanks for the report. 

t took me a while to find this, since NPM did not clean up the kraken dep in the main gekko project for whatever reason. Fixed in latest develop :)
