### ISSUE TITLE
  Error: non-error thrown: [object Object]

### ISSUE THREAD

**Issue by mayank-anuragi** [askmike/gekko#2312]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)

I have made a New Script which combines BOTH MACD and RSI indicators for crypto trading in gekko using java-script. When I ran this script in the GUI interface there is no backtest result produced.
I have given my script below plz see and tell if I have missed something:

[START OF SCRIPT]

    /*
    Combination of MACD and RSI
    */
    //helpers
    var _ = require('lodash');
    var log = require('./core/log.js');
    var RSI = require('./indicators/RSI.js');
    var MACD = require('./indicators/MACD.js');

    // let's create our own method
    
    var strat = {};
    // prepare everything our method needs
    strat.init = function() {
    this.name = 'RSI';

    this.trend = {
    direction: 'none',
    duration: 0,
    persisted: false,
    adviced: false
    };

    this.requiredHistory = this.tradingAdvisor.historySize;

    this.addIndicator('rsi', 'RSI', { interval: RSIinterval });
    this.addIndicator('macd', 'MACD', this.settings);
    }

    //Log funtion For RSI
    strat.log = function(candle) {
   
    var digits = 8;
    var rsi = this.indicators.rsi;

    log.debug('calculated RSI properties for candle:');
    log.debug('\t', 'rsi:', rsi.result.toFixed(digits));
    log.debug('\t', 'price:', candle.close.toFixed(digits));
    }

    //Log Funtion For MACD
    strat.log = function() {   
    var digits = 8;
    var macd = this.indicators.macd;

    var diff = macd.diff;
    var signal = macd.signal.result;

    log.debug('calculated MACD properties for candle:');
    log.debug('\t', 'short:', macd.short.result.toFixed(digits));
    log.debug('\t', 'long:', macd.long.result.toFixed(digits));
    log.debug('\t', 'macd:', diff.toFixed(digits));
    log.debug('\t', 'signal:', signal.toFixed(digits));
    log.debug('\t', 'macdiff:', macd.result.toFixed(digits));
    }

    strat.update = function() {
    //Nothing coz there is nothing in the other two files. 

    }
    

   // Check Function
    strat.check = function() {
    var rsi = this.indicators.rsi;
    var rsiVal = rsi.result;
    var macddiff = this.indicators.macd.result;

    if(rsiVal > this.settings.thresholds.high && macddiff > this.settings.thresholds.up) {
    // new trend detected
    if(this.trend.direction !== 'high')
    	this.trend = {
    	duration: 0,
    	persisted: false,
    	direction: 'high',
    	adviced: false
    };

    this.trend.duration++;

    log.debug('In high since', this.trend.duration, 'candle(s)');

    if(this.trend.duration >= this.settings.thresholds.persistence)
    	this.trend.persisted = true;

    if(this.trend.persisted && !this.trend.adviced) {
    	this.trend.adviced = true;
    	his.advice('long');

    }else
    	this.advice();

    } else if(rsiVal < this.settings.thresholds.low && macddiff < this.settings.thresholds.down) {

    // new trend detected
    if(this.trend.direction !== 'low')
    	this.trend = {
    	duration: 0,
   	persisted: false,
    	direction: 'low',
    	adviced: false
    };
    this.trend.duration++;

    log.debug('In low since', this.trend.duration, 'candle(s)');

    if(this.trend.duration >= this.settings.thresholds.persistence)
    	this.trend.persisted = true;

    if(this.trend.persisted && !this.trend.adviced) {
    	this.trend.adviced = true;
    	this.advice('long');
    } else
    	this.advice();

    } else {

    	log.debug('In no trend');

    	this.advice();
    }
    }

    module.exports = strat; 

[END OF SCRIPT]

[TOML config]

interval = 14
short = 10
long = 21
signal = 9

[thresholds]
low = 30
high = 70
down = -0.025
up = 0.025
persistence = 1

[End of TOML config]

**Expected result** (what you hoped would happen)

The Script should be working.

**Actual result** (unexpected outcome)
[OUTPUT OF THE TERMINAL]

     xxx POST /api/backtest 500 159ms -

       Error: non-error thrown: [object Object]
             at Object.onerror (/home/USER_NAME/gekko/node_modules/koa/lib/context.js:105:40)
             at <anonymous>
             at process._tickCallback (internal/process/next_tick.js:188:7)

[END OF OUTPUT]

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
If there is any script available like this plz do send a link.
Also I have checked https://github.com/xFFFFF/Gekko-Strategies this github also.

Wating for response.
Thank you

**Comment by mayank-anuragi** [comment]
I have user the given MACD and RSI scripts.
>>>>>>>>>MACD.js<<<<<<<<<

/*

  MACD - DJM 31/12/2013

  (updated a couple of times since, check git history)

 */

// helpers
var _ = require('lodash');
var log = require('../core/log.js');

// let's create our own method
var method = {};

// prepare everything our method needs
method.init = function() {
  // keep state about the current trend
  // here, on every new candle we use this
  // state object to check if we need to
  // report it.
  this.trend = {
    direction: 'none',
    duration: 0,
    persisted: false,
    adviced: false
  };

  // how many candles do we need as a base
  // before we can start giving advice?
  this.requiredHistory = this.tradingAdvisor.historySize;

  // define the indicators we need
  this.addIndicator('macd', 'MACD', this.settings);
}

// what happens on every new candle?
method.update = function(candle) {
  // nothing!
}

// for debugging purposes: log the last calculated
// EMAs and diff.
method.log = function() {
  var digits = 8;
  var macd = this.indicators.macd;

  var diff = macd.diff;
  var signal = macd.signal.result;

  log.debug('calculated MACD properties for candle:');
  log.debug('\t', 'short:', macd.short.result.toFixed(digits));
  log.debug('\t', 'long:', macd.long.result.toFixed(digits));
  log.debug('\t', 'macd:', diff.toFixed(digits));
  log.debug('\t', 'signal:', signal.toFixed(digits));
  log.debug('\t', 'macdiff:', macd.result.toFixed(digits));
}

method.check = function() {
  var macddiff = this.indicators.macd.result;

  if(macddiff > this.settings.thresholds.up) {

    // new trend detected
    if(this.trend.direction !== 'up')
      // reset the state for the new trend
      this.trend = {
        duration: 0,
        persisted: false,
        direction: 'up',
        adviced: false
      };

    this.trend.duration++;

    log.debug('In uptrend since', this.trend.duration, 'candle(s)');

    if(this.trend.duration >= this.settings.thresholds.persistence)
      this.trend.persisted = true;

    if(this.trend.persisted && !this.trend.adviced) {
      this.trend.adviced = true;
      this.advice('long');
    } else
      this.advice();

  } else if(macddiff < this.settings.thresholds.down) {

    // new trend detected
    if(this.trend.direction !== 'down')
      // reset the state for the new trend
      this.trend = {
        duration: 0,
        persisted: false,
        direction: 'down',
        adviced: false
      };

    this.trend.duration++;

    log.debug('In downtrend since', this.trend.duration, 'candle(s)');

    if(this.trend.duration >= this.settings.thresholds.persistence)
      this.trend.persisted = true;

    if(this.trend.persisted && !this.trend.adviced) {
      this.trend.adviced = true;
      this.advice('short');
    } else
      this.advice();

  } else {

    log.debug('In no trend');

    // we're not in an up nor in a downtrend
    // but for now we ignore sideways trends
    //
    // read more @link:
    //
    // https://github.com/askmike/gekko/issues/171

    // this.trend = {
    //   direction: 'none',
    //   duration: 0,
    //   persisted: false,
    //   adviced: false
    // };

    this.advice();
  }
}

module.exports = method;







>>>>>>>>>>>>RSI.js<<<<<<<<<<<<

/*

  RSI - cykedev 14/02/2014

  (updated a couple of times since, check git history)

 */
// helpers
var _ = require('lodash');
var log = require('../core/log.js');

var RSI = require('./indicators/RSI.js');

// let's create our own method
var method = {};

// prepare everything our method needs
method.init = function() {
  this.name = 'RSI';

  this.trend = {
    direction: 'none',
    duration: 0,
    persisted: false,
    adviced: false
  };

  this.requiredHistory = this.tradingAdvisor.historySize;

  // define the indicators we need
  this.addIndicator('rsi', 'RSI', this.settings);
}

// for debugging purposes log the last
// calculated parameters.
method.log = function(candle) {
  var digits = 8;
  var rsi = this.indicators.rsi;

  log.debug('calculated RSI properties for candle:');
  log.debug('\t', 'rsi:', rsi.result.toFixed(digits));
  log.debug('\t', 'price:', candle.close.toFixed(digits));
}

method.check = function() {
  var rsi = this.indicators.rsi;
  var rsiVal = rsi.result;

  if(rsiVal > this.settings.thresholds.high) {

    // new trend detected
    if(this.trend.direction !== 'high')
      this.trend = {
        duration: 0,
        persisted: false,
        direction: 'high',
        adviced: false
      };

    this.trend.duration++;

    log.debug('In high since', this.trend.duration, 'candle(s)');

    if(this.trend.duration >= this.settings.thresholds.persistence)
      this.trend.persisted = true;

    if(this.trend.persisted && !this.trend.adviced) {
      this.trend.adviced = true;
      this.advice('short');
    } else
      this.advice();

  } else if(rsiVal < this.settings.thresholds.low) {

    // new trend detected
    if(this.trend.direction !== 'low')
      this.trend = {
        duration: 0,
        persisted: false,
        direction: 'low',
        adviced: false
      };

    this.trend.duration++;

    log.debug('In low since', this.trend.duration, 'candle(s)');

    if(this.trend.duration >= this.settings.thresholds.persistence)
      this.trend.persisted = true;

    if(this.trend.persisted && !this.trend.adviced) {
      this.trend.adviced = true;
      this.advice('long');
    } else
      this.advice();

  } else {

    log.debug('In no trend');

    this.advice();
  }
}

module.exports = method;

**Comment by Err0rs404** [comment]
Hello,
Ever since update im also recieving this error if i want to runy any strategy with error,...(typo, etc,..) on previous version it returned error what and where in strategy file error exists, now it just returns "koa" error so its hard to debug,... In config i have enabled debug,...

Please help?

**Comment by askmike** [comment]
This is the bug tracker, not the perfect place to discuss this.

Also it's very hard to read the strategy if you past it like this.

Please put the strategy in a gist or pastebin and try asking here: https://forum.gekko.wizb.it/forum-12.html

**Comment by askmike** [comment]
See this page for some more context: https://gekko.wizb.it/docs/introduction/getting_help.html
