### ISSUE TITLE
0 Exchanges data available to import

### ISSUE THREAD

**Issue by icet208** [askmike/gekko#2313]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Installed Gekko, run it and tried to import data from a exchange

**Expected result** (what you hoped would happen)
To find a list of available exchange data.

**Actual result** (unexpected outcome)
0 exchanges available 

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
I have made a screenshot wile the exchange button was clicked
![screenshot_4](https://user-images.githubusercontent.com/41271552/42738138-4ddc25ac-8887-11e8-9792-01e2b412973a.png)

**Comment by askmike** [comment]
Install Gekko Broker dependencies, see the installation doc.
