### ISSUE TITLE
any plans to add COINEX exchange?

### ISSUE THREAD

**Issue by shreddy040** [askmike/gekko#2314]
no bugs found.

**Comment by askmike** [comment]
No plans no! Unfortunately I will to busy in the coming time to do this.

Anyone can add an exchange to Gekko, see these docs: https://gekko.wizb.it/docs/extending/add_an_exchange.html

A better place to ask and discuss adding a new exchange would be here: https://forum.gekko.wizb.it/

As this is the bug tracker!
