### ISSUE TITLE
ERROR: Please specify a config file* on UI start

### ISSUE THREAD

**Issue by ialberquilla** [askmike/gekko#2315]
Hello, 

**I'm submitting a ...**
[ x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
I tried to install Gekko on, following the instructions publiseh in 
https://gekko.wizb.it/docs/installation/installing_gekko_on_windows.html  and tried to open the UI after the installation finished, with the command **node gekko --ui**

using both the dev brach and stable branch

**Expected result** (what you hoped would happen)
I want to open the UI for Gekko 

**Actual result** (unexpected outcome)

The UI does not start and shows the errror: **ERROR: Please specify a config file**

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

I tried to use the sample-config.js with the command node gekko --config sample-config.js ui
but it starts the strategies and does not start the UI

How can start only the UI? It is necessary to create other config-file?

Thanks

**Comment by askmike** [comment]
Very strange, can you post the complete output after typing the command `node gekko --ui`?

**Comment by ialberquilla** [comment]
Sorry.. my fault. I was using node gekko ui, following the video instructions, but the correct one is --ui that is in the manual and you provided.

Thanks! and sorry for the misunderstood

**Comment by askmike** [comment]
Great that you figured it out! Can you close this issue?

**Comment by ialberquilla** [comment]
Sure, closed!
