### ISSUE TITLE
No git binary found in $Path

### ISSUE THREAD

**Issue by Shogges** [askmike/gekko#2317]
**I'm submitting a ...**
question about installing Gekko

**Action taken** (what you did)
Tried to install with the instructions given

**Expected result** (what you hoped would happen)
Successful installation

**Actual result** (unexpected outcome)
Error message during exchange>npm install --only=production

This is the log given, I am kinda new to this so I guess its just a small step missing and sorry if this is kind of trivial, but I can´t tell what I have done wrong. This is the report:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--only=production' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose npm-session 39856b99cacb4dac
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall gekko-broker@0.6.2
7 info lifecycle gekko-broker@0.6.2~preinstall: gekko-broker@0.6.2
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 silly install loadShrinkwrap
13 silly fetchPackageMetaData error for poloniex.js@git://github.com/askmike/poloniex.js.git#69f5e254353e66d135070844fc3328efcbe3641c No git binary found in $PATH
14 silly saveTree gekko-broker@0.6.2
14 silly saveTree +-- async@2.6.0
14 silly saveTree | `-- lodash@4.17.10
14 silly saveTree +-- binance@1.3.3
14 silly saveTree +-- bitfinex-api-node@2.0.0-beta.1
14 silly saveTree | +-- bignumber.js@6.0.0
14 silly saveTree | +-- cbq@0.0.1
14 silly saveTree | +-- crc-32@1.2.0
14 silly saveTree | | `-- exit-on-epipe@1.0.1
14 silly saveTree | +-- debug@2.6.9
14 silly saveTree | | `-- ms@2.0.0
14 silly saveTree | `-- lodash.throttle@4.1.1
14 silly saveTree +-- bluebird@3.5.1
14 silly saveTree +-- coinfalcon@1.0.3
14 silly saveTree | `-- babel-runtime@6.26.0
14 silly saveTree |   `-- core-js@2.5.6
14 silly saveTree +-- gdax@0.7.0
14 silly saveTree | +-- @types/request@2.47.0
14 silly saveTree | | +-- @types/caseless@0.12.1
14 silly saveTree | | +-- @types/form-data@2.2.1
14 silly saveTree | | | `-- @types/node@10.1.2
14 silly saveTree | | +-- @types/node@10.1.2
14 silly saveTree | | `-- @types/tough-cookie@2.3.3
14 silly saveTree | +-- bignumber.js@5.0.0
14 silly saveTree | +-- bintrees@1.0.2
14 silly saveTree | `-- ws@4.1.0
14 silly saveTree |   `-- async-limiter@1.0.0
14 silly saveTree +-- kraken-api@1.0.0
14 silly saveTree | `-- got@7.1.0
14 silly saveTree |   +-- decompress-response@3.3.0
14 silly saveTree |   | `-- mimic-response@1.0.0
14 silly saveTree |   +-- duplexer3@0.1.4
14 silly saveTree |   +-- get-stream@3.0.0
14 silly saveTree |   +-- is-plain-obj@1.1.0
14 silly saveTree |   +-- is-retry-allowed@1.1.0
14 silly saveTree |   +-- is-stream@1.1.0
14 silly saveTree |   +-- isurl@1.0.0
14 silly saveTree |   | +-- has-to-string-tag-x@1.4.1
14 silly saveTree |   | | `-- has-symbol-support-x@1.4.2
14 silly saveTree |   | `-- is-object@1.0.1
14 silly saveTree |   +-- lowercase-keys@1.0.1
14 silly saveTree |   +-- p-cancelable@0.3.0
14 silly saveTree |   `-- p-timeout@1.2.1
14 silly saveTree |     `-- p-finally@1.0.0
14 silly saveTree +-- lodash@4.17.10
14 silly saveTree `-- moment@2.22.1
15 verbose stack Error: No git binary found in $PATH
15 verbose stack     at checkGit (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\util\git.js:203:17)
15 verbose stack     at spawnGit (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\util\git.js:182:10)
15 verbose stack     at pinflight (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\util\git.js:114:12)
15 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\promise-inflight\inflight.js:29:24
15 verbose stack     at Promise._execute (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\debuggability.js:303:9)
15 verbose stack     at Promise._resolveFromExecutor (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:483:18)
15 verbose stack     at new Promise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:79:10)
15 verbose stack     at _inflight (C:\Program Files\nodejs\node_modules\npm\node_modules\promise-inflight\inflight.js:28:25)
15 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\promise-inflight\inflight.js:22:14
15 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
15 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
15 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
15 verbose stack     at Promise._settlePromiseCtx (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:606:10)
15 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:138:12)
15 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
15 verbose stack     at Immediate.Async.drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
16 verbose cwd C:\Users\meteo\Downloads\gekko\exchange
17 verbose Windows_NT 10.0.17134
18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--only=production"
19 verbose node v8.11.3
20 verbose npm  v5.6.0
21 error code ENOGIT
22 error No git binary found in $PATH
23 error Failed using git.
23 error Please check if you have git installed and in your PATH.
24 verbose exit [ 1, true ]

**Comment by icet208** [comment]
I have the same problem when trying to add Exchange dependencies.
Don`t know what to do

**Comment by askmike** [comment]
Something is wrong with your git installation. Unfortunately I don't windows so I don't really no how to fix this.

Would you mind posting this on the forum? https://forum.gekko.wizb.it/
