### ISSUE TITLE
"Invalid date" displayed in papertrader roundtrip overview.

### ISSUE THREAD

**Issue by bald123** [askmike/gekko#2318]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[X ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Using Gekko v0.6.2 and Gekko UI v0.2.2. Let several papertraders run for a couple of days against several assets and exchanges. When the first roundtrip is finished, the roundtrip overview does not display a valid entry- and exit date.

**Expected result** (what you hoped would happen)
To see a valid entry and exit date in the roundtrip overview of the paper trader.

**Actual result** (unexpected outcome)
Instead of a valid date, the text "Invalid date" is displayed. The result is (copy pasted):

> Entry at (UTC) | Exit at (UTC) | Exposure | Entry balance | Exit balance | P&L | Profit
> -- | -- | -- | -- | -- | -- | --
> Invalid date | Invalid date | 4 days | 798.700 | 869.156 | 70.46 | 8.82%

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
This issue did not appear in version < 0.6.0.

**Comment by askmike** [comment]
Same as: https://forum.gekko.wizb.it/thread-57365.html

**Comment by askmike** [comment]
Should be fixed now in latest develop, could you verify?

**Comment by askmike** [comment]
It's fixed for me:

<img width="1085" alt="screen shot 2018-07-17 at 16 25 17" src="https://user-images.githubusercontent.com/969743/42805285-05f97d86-89de-11e8-8c7a-5c728624ec79.png">

**Comment by xbromy** [comment]
@askmike it's not working well.. Have a look on the hours and minutes. On my end it looks same. So all have the same date. (Looks like current server time)
