### ISSUE TITLE
Wrong date in trading result table

### ISSUE THREAD

**Issue by xbromy** [askmike/gekko#2319]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Fetched development today and startet live trading on binance.

**Expected result** (what you hoped would happen)
right timings in result table (like the on with the 1970 bug last days...)

**Actual result** (unexpected outcome)
Entry at (UTC)	Exit at (UTC)	Exposure	Entry balance	Exit balance	P&L	Profit
Invalid date	Invalid date	an hour	13.763	13.682	0.08	-0.59%

so something is wrong with the date...

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
dup of #2318.

**Comment by askmike** [comment]
Same as: https://forum.gekko.wizb.it/thread-57365.html
