### ISSUE TITLE
npm ERR! install Couldn't read dependencies

### ISSUE THREAD

**Issue by heikeisn** [askmike/gekko#232]
npm ERR! install Couldn't read dependencies
npm ERR! package.json ENOENT, open '/root/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! System Linux 3.11.0-15-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /root
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! path /root/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0

**Comment by gbhattachan** [comment]
I know is old post but I ran into same error when installing npm in my windows machine. I executed npm init under /nodejs as suggested by <DarshanaPanchal>, and it did the trick. Here is the output of npm init. I hope this helps.

C:\Program Files\nodejs>npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.
Use `npm install <pkg> --save` afterwards to install a package and
save it as a dependency in the package.json file.
Press ^C at any time to quit.
name: (nodejs) package.json
version: (1.0.0)
description:
entry point: (index.js)
test command:
git repository:
keywords:
author:
license: (ISC)
About to write to C:\Program Files\nodejs\package.json:
{
  "name": "package.json",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "npm": "^2.15.1"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
Is this ok? (yes) yes
C:\Program Files\nodejs>

**Comment by askmike** [comment]
What exactly are you having trouble with? If you install a new version of nodejs npm should get installed automatically.

**Comment by flyher** [comment]
hi,i met he same issues, because i set the package,json  

``` json
"name":"aa  bbb"
```

when i change the name to 

``` json
"name":"aabbb"
```

the issues disappear.
i hope it help you!
