### ISSUE TITLE
Docs mention  Poloniex for Bitstamp exchange example

### ISSUE THREAD

**Issue by laisee** [askmike/gekko#2322]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
I was browsing through documentation and read the section on how to build code for a new exchange.
The text refers to Bitstamp but the example folder path mentions Poloniex.

**Expected result** (what you hoped would happen)
Would expect to see folder includes name of the exchange e.g. gekko/exchange/wrappers/bitstamp.js.

**Actual result** (unexpected outcome)
Folder name includes "Poloniex" instead e.g. "gekko/exchange/wrappers/poloniex.js."

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

See below for screen shot:

![screen shot 2018-07-17 at 10 37 07](https://user-images.githubusercontent.com/5905130/42793713-0432c550-89ae-11e8-8e38-c6ae478f98ad.png)

Web page was https://gekko.wizb.it/docs/extending/add_an_exchange.html

**Comment by askmike** [comment]
Nice catch, thanks.

**Comment by askmike** [comment]
Bitstamp used to be the main reference (after it was added after Mt. Gox in 2013). But right now it is not updated for the latest version of Gekko.

**Comment by laisee** [comment]
np.
