### ISSUE TITLE
importer not working 

### ISSUE THREAD

**Issue by sayyes123** [askmike/gekko#2327]
when i open the importer part it is like unable to select anything from exchange and the pairs

i hve screenshot but i don't know how to insert it here 
**Expected result** (what you hoped would happen)

**Actual result** (unexpected outcome)

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by Akthree** [comment]
First i want to say thanks for all the good work done.
Unfortunatly i have the same issue sayyes123 mentioned.
I installed everything according to your supportive video and gekko is up an running but i do not have any possibility to select a market in the importer :/

i am running your latest develop version and fixed some vulnerability issues which node.js informed me of.
now the question that i had to myself was: do i need to enter an API before importing stuff?

![screen](https://user-images.githubusercontent.com/23663859/42969857-d47b1ca8-8ba7-11e8-870c-40d2753e6404.png)

**Comment by Akthree** [comment]
a few minutes later .....
found the answer :D 
for everyone else:
https://forum.gekko.wizb.it/thread-57313.html

EDIT:
if you run into problems that Git cannot be found although its installed > try using the powershell (maybe classic cmd wasnt selected during git-installation)

**Comment by askmike** [comment]
great!
