### ISSUE TITLE
Livetrading result date is always current server time

### ISSUE THREAD

**Issue by xbromy** [askmike/gekko#2332]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Live trading gekko with results

**Expected result** (what you hoped would happen)
right timings in table

**Actual result** (unexpected outcome)

Entry at (UTC) | Exit at (UTC) | Exposure | Entry balance | Exit balance | P&L | Profit
-- | -- | -- | -- | -- | -- | --
2018-07-18 05:40 | 2018-07-18 05:40 | an hour | 13.448 | 13.572 | 0.12 | 0.93%
2018-07-18 05:40 | 2018-07-18 05:40 | 2 hours | 13.559 | 13.639 | 0.08 | 0.59%
2018-07-18 05:40 | 2018-07-18 05:40 | 44 minutes | 13.627 | 13.648 | 0.02 | 0.15%
2018-07-18 05:40 | 2018-07-18 05:40 | an hour | 13.648 | 13.679 | 0.03 | 0.22%

**2018-07-18 05:40 is the current server time.. if i refresh the page it goes up...**

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
Is your server not in UTC? If so in what timezone is it?

**Comment by xbromy** [comment]
Yes it is. It's not the wrong time.. it's about it showes in every row the 
current Servertime from when the table gets rendered. So if you press 
refresh on 5pm it shows 5pm on each row. You got it?

Am 18. Juli 2018 8:16:57 nachm. schrieb Mike van Rossum 
<notifications@github.com>:

**Comment by askmike** [comment]
Oops! fixed in latest develop.
