### ISSUE TITLE
Trading pair not prespecified

### ISSUE THREAD

**Issue by thesantosxen** [askmike/gekko#2333]
Hi all! Im asking myself if its somehow possible to made variable trading pairs. That means starting the bot with a prespecified array or pairs and iterating through all of them, looking for different indicators to get into a trade.

**Comment by askmike** [comment]
Unfortunately this is not possible. Gekko won't do anything until you specify one specific market (2 coins like BTC/ETH) it should watch.

Though some people are creating other software that allows Gekko to do this kind of stuff. Anyway you'll have more luck asking around on the forum: https://forum.gekko.wizb.it/

(as this is the bug tracker - so unfortunately I have to close this)
