### ISSUE TITLE
Couldn't import products from CoinFalcon + Bitfinex.

### ISSUE THREAD

**Issue by bald123** [askmike/gekko#2334]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
New Docker container built of latest develop branch (2018-07-18). To be sure to be up to date regarding exchange currency pairs, I always run the exchange/util/genMarketFiles/*.js files. Execution of two of the files failed, for exchange Bitfinex and Coinfalcon.

Is it necessary to run these scripts when building a container?

**Expected result** (what you hoped would happen)
A successful built.

**Actual result** (unexpected outcome)
Errors for exchanges Bitfinex and Coinfalcon.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

> Step 18/26 : RUN node update-kraken.js
>  ---> Running in 5e3add101b8a
> Done writing Kraken market data
> Removing intermediate container 5e3add101b8a
>  ---> 4984b42b0fb0
> Step 19/26 : RUN node update-coinfalcon.js
>  ---> Running in 2d8a9cb01376
> **Couldn't import products from CoinFalcon**
> TypeError: _.unique is not a function
>     at request.then.body (/usr/src/app/exchange/util/genMarketFiles/update-coinfalcon.js:21:20)
>     at tryCatcher (/usr/src/app/exchange/node_modules/bluebird/js/release/util.js:16:23)
>     at Promise._settlePromiseFromHandler (/usr/src/app/exchange/node_modules/bluebird/js/release/promise.js:512:31)
>     at Promise._settlePromise (/usr/src/app/exchange/node_modules/bluebird/js/release/promise.js:569:18)
>     at Promise._settlePromise0 (/usr/src/app/exchange/node_modules/bluebird/js/release/promise.js:614:10)
>     at Promise._settlePromises (/usr/src/app/exchange/node_modules/bluebird/js/release/promise.js:693:18)
>     at Async._drainQueue (/usr/src/app/exchange/node_modules/bluebird/js/release/async.js:133:16)
>     at Async._drainQueues (/usr/src/app/exchange/node_modules/bluebird/js/release/async.js:143:10)
>     at Immediate.Async.drainQueues (/usr/src/app/exchange/node_modules/bluebird/js/release/async.js:17:14)
>     at runCallback (timers.js:810:20)
>     at tryOnImmediate (timers.js:768:5)
>     at processImmediate [as _immediateCallback] (timers.js:745:5)
> Removing intermediate container 2d8a9cb01376
>  ---> 36f64691ae1c
> Step 20/26 : RUN node update-bitfinex.js
>  ---> Running in a39e2568f8fe
> **Couldn't import products from Bitfinex**
> TypeError: _.unique is not a function
>     at request.then.then.results (/usr/src/app/exchange/util/genMarketFiles/update-bitfinex.js:22:18)
>     at tryCatcher (/usr/src/app/exchange/node_modules/bluebird/js/release/util.js:16:23)
>     at Promise._settlePromiseFromHandler (/usr/src/app/exchange/node_modules/bluebird/js/release/promise.js:512:31)
>     at Promise._settlePromise (/usr/src/app/exchange/node_modules/bluebird/js/release/promise.js:569:18)
>     at Promise._settlePromise0 (/usr/src/app/exchange/node_modules/bluebird/js/release/promise.js:614:10)
>     at Promise._settlePromises (/usr/src/app/exchange/node_modules/bluebird/js/release/promise.js:693:18)
>     at Async._drainQueue (/usr/src/app/exchange/node_modules/bluebird/js/release/async.js:133:16)
>     at Async._drainQueues (/usr/src/app/exchange/node_modules/bluebird/js/release/async.js:143:10)
>     at Immediate.Async.drainQueues (/usr/src/app/exchange/node_modules/bluebird/js/release/async.js:17:14)
>     at runCallback (timers.js:810:20)
>     at tryOnImmediate (timers.js:768:5)
>     at processImmediate [as _immediateCallback] (timers.js:745:5)
>

**Comment by askmike** [comment]
Oops!

**Comment by askmike** [comment]
Unfortunately you need to pull the develop branch for now. I will release a new update asap.

**Comment by bald123** [comment]
Yes, it's working now!
