### ISSUE TITLE
TypeError: Cannot read property 'startTime' of undefined

### ISSUE THREAD

**Issue by lordoski** [askmike/gekko#2337]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Run Backtest with imported data, default settings used.

**Expected result** (what you hoped would happen)
Backtest result without errors 

**Actual result** (unexpected outcome)
TypeError: Cannot read property 'startTime' of undefined
at a.P (summary.vue?a48b:formatted:5)
    at a.t._render (vue.runtime.esm.js:4540)
    at a.r (vue.runtime.esm.js:2784)
    at un.Kw5r.un.get (vue.runtime.esm.js:3138)
    at new un (vue.runtime.esm.js:3127)
    at Ne (vue.runtime.esm.js:2791)
    at a.Kw5r.ur.$mount (vue.runtime.esm.js:7995)
    at init (vue.runtime.esm.js:4133)
    at d (vue.runtime.esm.js:5604)
    at h (vue.runtime.esm.js:5551)

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
Can you share more information? Such as what version of Gekko are you running? What data are you backtesting, where did you get that data? Did you change any config? etc.

**Comment by lordoski** [comment]
**what version of Gekko are you running?**:  Using Gekko v0.6.2 and Gekko UI v0.2.2.

**What data are you backtesting?** Im using USDT XRP  between 2018-05-04 08:11 | 2018-07-19 13:52

**where did you get that data?**: From Binance
**Did you change any config?** : No, all using defaults. Im just changed the host and the headless properties on web/vue/dist/UIconfig.js as mentioned in documentation.

Im using MACD strategy, with the defaults parameters

I installed gekko on Raspbian, raspberry pi 3

Also, with that strategy the error came up and any report was given (Roundtrips Not enough data to display)  but i tried other strategys such RSI and every worked fine and the report and dots over the graph was drawn.

**Comment by askmike** [comment]
Very strange..

- If you try the MACD again? Does it keep happening on a constant basis?
- What browser (+ version) are you using?

**Comment by lordoski** [comment]
Yes, the error is keeping happening on constant basis.

Im using google Chrome Version 65.0.3325.181 (Oficial build) (64 bits)

Note:
The data im using is: binance | USDT | XRP | 2018-05-04 08:11 | 2018-07-19 13:52 | 2 months, 2 weeks, 1 day, 8 hours

The parameters im using are: 
short = 10
long = 21
signal = 9

[thresholds]
down = -0.025
up = 0.025
persistence = 1

the strategy is: MACD.

It is also happening in other strategys (with defaults parameters aswell).

Im starting to believe that the problem is happening when no trades are posible to make based on the data and the parameters of the strategy.

**Comment by moo5e** [comment]
Also experiencing this problem, its not happening because there are no trade possible. I only get this error when i try to run my custom strategy, UI works fine with other strategies.

**Comment by moo5e** [comment]
update: error was from an indicator in my strategy not working properly,
changed rsi paramater settings from {optInTimePeriod : 14} to {interval : 14} and it worked

**Comment by askmike** [comment]
@lordoski is this still happening with the latest version of Gekko?

**Comment by duxor** [comment]
I have the same problem with latest version of Gekko, try to remove collection from database and import data again, working for me...

**Comment by mortezae** [comment]
Same here, with MACD and also CCI (Roundtrips Not enough data to display)
Not tested other strategies but RSI is fine.

**Comment by askmike** [comment]
I'm still having a hard time replicating this. Does this always happen when running a backtest that doesn't include any trades?
