### ISSUE TITLE
"Partial" orders not moved on kraken

### ISSUE THREAD

**Issue by dugu-dugu** [askmike/gekko#2340]
**I'm submitting a ...**
[X ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Live trading on Kraken

**Expected result** (what you hoped would happen)
Working SELL orders

**Actual result** (unexpected outcome)
SELL orders that become partial are no longer recreated or "MOVED" by gekko

**Details**
I have upgraded from version 0.5.14 to 0.6.2 (with git pull).

It seems that partial orders on Kraken are no longer moved. I see this in gekko log:
Code:
'error creating:' 'API:Invalid nonce'

To clarify:
In the old gekko version 0.5.14 a SELL order would get recreated every minute with a new price until the whole sum was sold. That was working even for orders that didn't sell the whole amount and become "partial".

In the new gekko version 0.6.2 a SELL order is being "MOVED" and "OPEN" (these are terms I see in the log). These operations were performed as long as the order was "untouched". When it become "partial", it was no longer "MOVED", it remained "OPEN" forever. That error would show up in log.

**Comment by askmike** [comment]
> 'error creating:' 'API:Invalid nonce'

This is a different problem, I already fixed that in a develop branch I am working on, see here for datails: https://github.com/askmike/gekko/pull/2330

> In the new gekko version 0.6.2 a SELL order is being "MOVED" and "OPEN" (these are terms I see in the log).

The behavior in 0.6 should be roughly similar as in 0.5, but instead of checking once a minute Gekko now checks once a second (to be more competitive in todays markets). It's now all handled by a library called Gekko Broker, and the execution behavior is now part of something called a "sticky order", see here for details: https://gekko.wizb.it/docs/gekko-broker/sticky_order.html

I think the reason this didn't happen for you is because of the nonce error.

**Comment by askmike** [comment]
Did this happen once or is it happening constantly?

**Comment by mark-sch** [comment]
I had the same prob today on Kraken, it happened both on buy and sell orders. The order gets partially filled and the remaining will never complete. This did not happen on v0.5. Unfortunately I have limited debug capabilities during a week holiday trip.

**Comment by askmike** [comment]
@mark-sch & @dugu-dugu if you are able to post logs that would be very helpful!

**Comment by dugu-dugu** [comment]
It happened again for me, I was on 0.6.2 with the fix applied for "nonce" error. The order was being moved when it was "Untouched", until it became "Partial". Then it remained "Open" and nothing happened to it anymore.

I have upgraded to 0.6.4 now, with git pull from development branch.

Logs attached.
[kraken_partial_order_bug.txt](https://github.com/askmike/gekko/files/2253553/kraken_partial_order_bug.txt)

**Comment by dugu-dugu** [comment]
Adding logs for another sell, now with latest "development" branch, git pull from today.

This one looks like it was ok, order was moved even after a partial sale.
[partial_order_kraken.txt](https://github.com/askmike/gekko/files/2254735/partial_order_kraken.txt)
![screenshot_20180802_213516](https://user-images.githubusercontent.com/41471105/43603661-454d65ea-969c-11e8-8a94-acff02059246.png)

**Comment by dugu-dugu** [comment]
Again, problem with a partial order. This time it looks like it didn't detect that some of the order was filled and tried to move the order with the same amount of money. It received an error "insufficient funds" and abandoned everything.

git pull from 2018-08-17 development branch

[gekko-out-0.log](https://github.com/askmike/gekko/files/2320475/gekko-out-0.log)
![screenshot_20180825_114425](https://user-images.githubusercontent.com/41471105/44616686-f6732900-a85c-11e8-80fb-103c7c8a4e78.png)
