### ISSUE TITLE
I do not know the indicator SMA

### ISSUE THREAD

**Issue by mghen4023** [askmike/gekko#235]
I keep getting this error while trying to write a method that will use the SMA indicator and I can't figure out why I am getting this error. If I replace SMA with DEMA, it goes away.

Here is my custom.js:

var _ = require('lodash');
var config = require('../core/util.js').getConfig();
var settings = config.custom;

// Let's create our own method
var method = {};

// Prepare everything our method needs
method.init = function() {
  this.name = 'The gambler';
  
  this.currentTrend;
  this.requiredHistory = config.tradingAdvisor.historySize;

  // define the indicators we need
  this.addIndicator('smaFast', 'SMAFast', config.SMAFast);
  this.addIndicator('smaSlow', 'SMASlow', config.SMASlow);
}

// What happens on every new candle?
method.update = function(candle) {

}

// For debugging purposes.
method.log = function() {
  log.debug('SMAFast:');
  log.debug('\t', smaFast.result.toFixed(8));
  log.debug('SMASlow:');
  log.debug('\t', smaSlow.result.toFixed(8));
}

// Based on the newly calculated
// information, check if we should
// update or not.
method.check = function() {

  
}

module.exports = method;

**Comment by askmike** [comment]
Unfortunately SMA is currently not implemented, see [here](https://github.com/askmike/gekko/blob/0.2/docs/Configuring_gekko.md#automate-trading-advice).
