### ISSUE TITLE
Error when trying to run gekko UI

### ISSUE THREAD

**Issue by jabef** [askmike/gekko#2350]
I successfully installed and setup Gekko on Windows. Now though, when I try to do it on a brand new VPS created on Vultr (running Ubuntu 18.04) I am having isssues. After I clone the repo and follow instructions then cd to the gekko folder then run `npm install --only=production` command, I got some vulnerabilities, which I managed to fix. However, when the same happened in the  `exchange` folder, I  was not able to fix and there are a couple HIGH vulnerabilities (seems that the local qs versions in gekko are older). After I tried and failed to fix the HIGH vulnerabilities in the `exchange` folder, I decided to ignore and try to run gekko anyways. This led to the following error:

```
/root/gekko/web/server.js:13
const app = koa();
            ^

TypeError: Class constructor Application cannot be invoked without 'new'
    at Object.<anonymous> (/root/gekko/web/server.js:13:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/gekko/gekko.js:43:10)
    at Module._compile (module.js:652:30)
```

Any ideas what caused it?

P.S. Btw, these are the two HIGH vulnerabilities found in  the exchange folder.
```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Denial-of-Service Memory Exhaustion                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ qs                                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >= 1.x                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ 9914affc46323804fad606f57a4d88a28c27957c1f30c6968e10a6e08ae… │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ 9914affc46323804fad606f57a4d88a28c27957c1f30c6968e10a6e08ae… │
│               │ > request > qs                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/29                        │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Denial-of-Service Extended Event Loop Blocking               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ qs                                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >= 1.x                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ 9914affc46323804fad606f57a4d88a28c27957c1f30c6968e10a6e08ae… │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ 9914affc46323804fad606f57a4d88a28c27957c1f30c6968e10a6e08ae… │
│               │ > request > qs                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/28   

```

**Comment by askmike** [comment]
That error most likely has to do with you installing a different version of Koa than Gekko expects, Gekko expects exactly version 1.2.0.

-----

> P.S. Btw, these are the two HIGH vulnerabilities found in the exchange folder.

I need to dig through the dependency tree to see where those are from. Given to what Gekko communicates with (exchanges) these vulnerabilities are not that dangerous unless:

- The exchange tries to do something dirty (they already have your money)
- Someone is able to MitM the exchange (they already have access to your money)

We need to fix them nonetheless though!

----

You should not manually install other verisons of the dependencies or things will break. We need to fix all these errors in the gekko project. I'll get around to it at some point (or maybe someone else can do it)!

**Comment by askmike** [comment]
I am assuming installing the correction versions will fix it, easiest is to delete your node_modules folder (in gekko and gekko/exchange) and run the install commands again. If that doesn't fix it please comment here.

**Comment by jabef** [comment]
Ahh, ok. Installing the ccorrect version worked. Just so you know, it creates one related high vulnerability though

```
# Run  npm install koa@2.5.2  to resolve 1 vulnerability
SEMVER WARNING: Recommended action is a potentially breaking change
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ koa > fresh                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/526     
```

Thanks for your help.
