### ISSUE TITLE
ERROR: TALIB ERROR

### ISSUE THREAD

**Issue by Kris191** [askmike/gekko#2353]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Started Strategy DEMA Crossover with additional medium DEMA

**Expected result** (what you hoped would happen)
Start as normal

**Actual result** (unexpected outcome)
Gekko error - ERROR: TALIB ERROR

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

no other info given apart form that debug console is on, i'm guessing is a talib error so installed talib again it updated one package but the error still exists.

**Comment by askmike** [comment]
Please provide more information:

- full error logs
- code snippet of creating the indicator (with parameters)
- your installed version of talib
- etc.

**Comment by Kris191** [comment]
I hang my head in shame!!!! it was early and i should have waited to post, there error was due to me messing with the file and deleting some of the key info. Now closed and lesson learned. @askmike thank you for quick responses even to silly non issues.
