### ISSUE TITLE
Info import error on data

### ISSUE THREAD

**Issue by rud3ls87** [askmike/gekko#2363]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Tried to import data into gekko on an AWS EC2 instance

**Expected result** (what you hoped would happen)
Data to be imported

**Actual result** (unexpected outcome)
Error message

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

![info_import](https://user-images.githubusercontent.com/41364767/43157967-bcc48916-8f7e-11e8-8889-3a5d8891d3e6.jpg)

**Comment by askmike** [comment]
- Did you install Gekko Broker dependencies?
- What exchange are you importing?
- What version are you running (if develop branch please let me know commit)

**Comment by rud3ls87** [comment]
Dependencies are all up to date - Sudo command as well just to be sure
Using Gekko v0.6.3
Importing from Binance (throws the same error on Poloniex)
git clone git://github.com/askmike/gekko.git -b stable

Worked fine on my local Ubuntu Instance, but not working on the cloud, also not able to run to paper trading due to watcher crashing.

Are there any oubound/inbound ports that I need to add in to EC2?

**Comment by askmike** [comment]
Can you try to run it via the commandline and see what output you get? The sample config has binance configured so you can just do:

    node gekko -c sample-config.js -i

**Comment by rud3ls87** [comment]
is there a command to dump the current market watcher data? It seems to have got stuck at 08:15 and is not updating for my live bots.

**Comment by rud3ls87** [comment]
never mind, it fixed itself :) all working!! you can close the issue :)

**Comment by askmike** [comment]
great!
