### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by RezaEjtehadi** [askmike/gekko#2364]
### **Hi, I'm Reza I installed gekko on Windows and Ubuntu Server, but also installs errors. Both manual installation and installing with Decker is a stable version and everything goes well, but when it fits in. The gekko dashboard shows that it is in danger: the photo below is the gekko dashboard on the ibnnet server**

![gekko1-reza ejteh](https://user-images.githubusercontent.com/29352009/43189831-6abdf584-8fac-11e8-8631-db3ddc3ca396.jpg)
![gekko2-rezaejteh](https://user-images.githubusercontent.com/29352009/43189881-8dbc351e-8fac-11e8-8cf5-267dc55bb2c3.jpg)
### **But there's no deal in my binance account**
![ex-rezaejteh](https://user-images.githubusercontent.com/29352009/43189935-b2db4ea2-8fac-11e8-9a74-643791066332.PNG)
🙏  😰  😖😭🙏

**Comment by askmike** [comment]
Your screenshot shows that you started a paper trader, which only simulates trading. Read this: https://gekko.wizb.it/docs/features/paper_trading.html

If you have further questions about Gekko please see this page: https://gekko.wizb.it/docs/introduction/getting_help.html

This is the bug tracker!
