### ISSUE TITLE
New installation can't find  "github.com/askmike/poloniex.js.git"

### ISSUE THREAD

**Issue by rich7** [askmike/gekko#2373]
I followed the instructions on this video  https://www.youtube.com/watch?v=R68IwVujju8
It won't show any exchange when you go to the data importer:
It's also not possible to ad an exchange other then 'bitx' in the configuration tab.
So I tried to followed the steps in the instructions given on the website here: 
https://gekko.wizb.it/docs/installation/installing_gekko.html

This gives an error at this step:

[https://snag.gy/lcJD0q.jpg](url)  <screen dump

debug log:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--only=production' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose npm-session f1220de78d22fadc
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall gekko-broker@0.6.3
7 info lifecycle gekko-broker@0.6.3~preinstall: gekko-broker@0.6.3
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 silly install loadShrinkwrap
13 silly fetchPackageMetaData error for poloniex.js@git://github.com/askmike/poloniex.js.git#69f5e254353e66d135070844fc3328efcbe3641c Error while executing:
13 silly fetchPackageMetaData D:\Program Files (x86)\Git\cmd\git.EXE ls-remote -h -t git://github.com/askmike/poloniex.js.git
13 silly fetchPackageMetaData
13 silly fetchPackageMetaData error launching git: Het systeem kan het opgegeven bestand niet vinden.
13 silly fetchPackageMetaData
13 silly fetchPackageMetaData exited with error code: 1
14 silly saveTree gekko-broker@0.6.3
14 silly saveTree +-- async@2.6.0
14 silly saveTree | `-- lodash@4.17.10
14 silly saveTree +-- binance@1.3.3
14 silly saveTree +-- bitfinex-api-node@2.0.0-beta.1
14 silly saveTree | +-- bignumber.js@6.0.0
14 silly saveTree | +-- cbq@0.0.1
14 silly saveTree | +-- crc-32@1.2.0
14 silly saveTree | | `-- exit-on-epipe@1.0.1
14 silly saveTree | +-- debug@2.6.9
14 silly saveTree | | `-- ms@2.0.0
14 silly saveTree | `-- lodash.throttle@4.1.1
14 silly saveTree +-- bluebird@3.5.1
14 silly saveTree +-- coinfalcon@1.0.3
14 silly saveTree | `-- babel-runtime@6.26.0
14 silly saveTree |   `-- core-js@2.5.6
14 silly saveTree +-- gdax@0.7.0
14 silly saveTree | +-- @types/request@2.47.0
14 silly saveTree | | +-- @types/caseless@0.12.1
14 silly saveTree | | +-- @types/form-data@2.2.1
14 silly saveTree | | | `-- @types/node@10.1.2
14 silly saveTree | | +-- @types/node@10.1.2
14 silly saveTree | | `-- @types/tough-cookie@2.3.3
14 silly saveTree | +-- bignumber.js@5.0.0
14 silly saveTree | +-- bintrees@1.0.2
14 silly saveTree | `-- ws@4.1.0
14 silly saveTree |   `-- async-limiter@1.0.0
14 silly saveTree +-- kraken-api@1.0.0
14 silly saveTree | `-- got@7.1.0
14 silly saveTree |   +-- decompress-response@3.3.0
14 silly saveTree |   | `-- mimic-response@1.0.0
14 silly saveTree |   +-- duplexer3@0.1.4
14 silly saveTree |   +-- get-stream@3.0.0
14 silly saveTree |   +-- is-plain-obj@1.1.0
14 silly saveTree |   +-- is-retry-allowed@1.1.0
14 silly saveTree |   +-- is-stream@1.1.0
14 silly saveTree |   +-- isurl@1.0.0
14 silly saveTree |   | +-- has-to-string-tag-x@1.4.1
14 silly saveTree |   | | `-- has-symbol-support-x@1.4.2
14 silly saveTree |   | `-- is-object@1.0.1
14 silly saveTree |   +-- lowercase-keys@1.0.1
14 silly saveTree |   +-- p-cancelable@0.3.0
14 silly saveTree |   `-- p-timeout@1.2.1
14 silly saveTree |     `-- p-finally@1.0.0
14 silly saveTree +-- lodash@4.17.10
14 silly saveTree +-- moment@2.22.1
14 silly saveTree `-- node.bittrex.api@1.0.0
14 silly saveTree   +-- cloudscraper@1.5.0
14 silly saveTree   +-- jsonic@0.3.0
14 silly saveTree   `-- object-assign@4.1.1
15 verbose stack Error: exited with error code: 1
15 verbose stack     at ChildProcess.onexit (C:\Program Files\nodejs\node_modules\npm\node_modules\mississippi\node_modules\end-of-stream\index.js:39:36)
15 verbose stack     at emitTwo (events.js:126:13)
15 verbose stack     at ChildProcess.emit (events.js:214:7)
15 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
16 verbose cwd D:\Program Files\Gekko-Bot\gekko-stable\exchange
17 verbose Windows_NT 10.0.17134
18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--only=production"
19 verbose node v8.11.3
20 verbose npm  v5.6.0
21 error Error while executing:
21 error D:\Program Files (x86)\Git\cmd\git.EXE ls-remote -h -t git://github.com/askmike/poloniex.js.git
21 error
21 error error launching git: Het systeem kan het opgegeven bestand niet vinden.
21 error
21 error exited with error code: 1
22 verbose exit [ 1, true ]

**Comment by askmike** [comment]
Hello fellow dutch person!

I was recently trying to add an annotation to that video, but it seems youtube doesn't let me anymore.

Gekko has progressed since that video and as such the installation process involves two new steps:

1. Install GIT, see here for example: https://www.atlassian.com/git/tutorials/install-git
2. install Gekko Broker's dependencies (which you tried but did not work).

The second step failed because you didn't do the first one. If you install git and try again it should work fine.

**Comment by rich7** [comment]
OK
Bedankt man! Werkt perfect nu. 

groet,
Richard

    On Friday, 27 July 2018, 16:26:23 CEST, Mike van Rossum <notifications@github.com> wrote:  
 
 
Hello fellow dutch person!

I was recently trying to add an annotation to that video, but it seems youtube doesn't let me anymore.

Gekko has progressed since that video and as such the installation process involves two new steps:
   
   - Install GIT, see here for example: https://www.atlassian.com/git/tutorials/install-git
   - install Gekko Broker's dependencies (which you tried but did not work).

The second step failed because you didn't do the first one. If you install git and try again it should work fine.
