### ISSUE TITLE
PaperTrader Mode vs Live trading

### ISSUE THREAD

**Issue by francoberton** [askmike/gekko#2377]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
I tried a gekko strategy in live trading, setting market order in binance, but I don't know why the papertrader mode got profits, while trading mode got losses, and I have seen that the trade in trading mode are reversed compared to papertrader mode.

**Expected result** (what you hoped would happen)
Papertrader results different from live trading results.

Live trading results:
<img width="1008" alt="schermata 2018-07-27 alle 19 39 46" src="https://user-images.githubusercontent.com/15656988/43340083-7b23486c-91db-11e8-9bab-45715d3d35d0.png">

Papertrader results:
<img width="939" alt="schermata 2018-07-27 alle 19 45 26" src="https://user-images.githubusercontent.com/15656988/43340097-829a0400-91db-11e8-92a0-1a47379eb096.png">

**Actual result** (unexpected outcome)
Papertrader results equal  from live trading results.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by DevCode01** [comment]
I have the same problem ..
![capture d ecran 2018-07-27 a 22 00 06](https://user-images.githubusercontent.com/36292698/43344023-a3a3fdec-91e8-11e8-8493-ca81989642b6.png) --> IN SIMULATION

But in reality .. it's very different

**Comment by askmike** [comment]
Gekko's simulation mode (backtesting & paper trader) works quite well in big markets, but poorly in small ones, from #2375:

> Gekko had to make a choice between a very accurate simulation which requires a lot of very hard to get data (orderbook data) or require little data for a default simulation which works pretty reliable for bigger markets but requires tweaking (to spread and slippage) for smaller ones like the one you tested.

You can read more about what you are seeing here: https://gekko.wizb.it/docs/features/backtesting.html#Simplified-simulation

-----

Since many people are asking questions about this I'll try to explain this better in the UI (besides just the docs).
