### ISSUE TITLE
 ERROR: Your local version of Node.js is too old. You have v6.14.3 and you need atleast >=8.11.2

### ISSUE THREAD

**Issue by nton232** [askmike/gekko#2384]
I installed gekko v0.6.4 . I got  ERROR: Your local version of Node.js is too old. You have v6.14.3 and you need atleast >=8.11.2  when trying to run "sudo node gekko --ui" .

However "node -v" showing v10.7.0 which is new version of nodejs . I ran "which node" which is showing ~/.nvm/versions/node/v10.7.0/bin/node .

i also ran nvm ls . It is showing
       v8.11.3
->      v10.7.0
         system
default -> node (-> v10.7.0)
node -> stable (-> v10.7.0) (default)
stable -> 10.7 (-> v10.7.0) (default)
iojs -> N/A (default)
lts/* -> lts/carbon (-> v8.11.3)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.14.3 (-> N/A)
lts/carbon -> v8.11.3

Clearly, i am using nodejs version of V10.7.0 and V6.14.3 has been uninstalled  

I have no idea where v6.14.3 is coming from ?

**Comment by askmike** [comment]
it's coming from the $PATH of sudo!

You don't need to run Gekko with sudo, and it's better if you don't :)

If that doesn't solve it please comment here. But I'm closing this as this is the bug tracker.

**Comment by nton232** [comment]
when i run Gekko without sudo i got an error like this

      Gekko v0.6.3
        I'm gonna make you rich, Bud Fox. 


fs.js:119
    throw err;
    ^

Error: EACCES: permission denied, open '/home/nton232/projects/crypto1/gekko_new/web/../SECRET-api-keys.json'

**Comment by askmike** [comment]
Apperantly you did run gekko over sudo at some point (without gekko
stopping with the version error). Manually delete that file and everything
inside the history folder (assuming you don't have market history)

**Comment by nton232** [comment]
You are so fast, thanks.  Yes, without sudo i have no version error . Do you mean i have to delete SECRET-api-keys.json ? I can't find that file in gekko directory and its subdir . where is the history folder ?
Thanks a lot

**Comment by askmike** [comment]
If its not in the main gekko folder It might mean gekko does not have write
access to the gekko folder. In that case your sudo stuff messed up file
permissions, you can try to fix it yourself (with chown and chmod) or
simply delete the gekko folder and download again (without using sudo
anywhere).
