### ISSUE TITLE
Custom method access to previous data ?

### ISSUE THREAD

**Issue by Camille92** [askmike/gekko#239]
Hi Mike,

I'm playing with your bot and I wish to customize the MACD method using previous data.

But I don't know how to ask Gekko to use them 
I basically wish to do :
  if(macddiff > settings.thresholds.up)  and (macdiff[-1] > macdiff[-2]) {
Send advice to go long ...

  } else if(macddiff < settings.thresholds.down) and (macdiff[-1] < macdiff[-2]) {
Go short ...

macdiff[-1] and macdiff[-2] being the macdiff H-1 and H-2.

It gets you 10% more than the typical MACD method !

Thank you if you know how to help,

Have a nice Easter

**Comment by 2Ez4Gondor** [comment]
Hi i'm trying to do access previous data as you suggested (using fullHistory.push(candle)) but it returns me that fullHistory is not defined, could you explain better how to access previous data?

**Comment by IAMtheIAM** [comment]
Here's how you do it, as long as you are using a TALib indicator:

`let candleProps = this.asyncIndicatorRunner.candleProps`

This is quoted from [an article](http://gekkowarez.com/tag/candleprops/) which helped me:

> If you want to use the candleprops array in a non talib using Strategy then do the following:
> 
> open plugins/baseTradingMethods.js and commend out the line below and the corresponding close bracket:
> 
> // if(this.asyncTick) {
> 
> Then go to your strategy and write console.log(this); in the update method and look for the candleprops arrays.
> 
> Note: baseTradingMethod is a core Gekko file so you should make this change only if you’re comfortable managing this change yourself.
