### ISSUE TITLE
backtest results vary wildly 

### ISSUE THREAD

**Issue by abmbc** [askmike/gekko#2394]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[X ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
I had a market watcher for GDAX running while I back tested a strategy in the UI several times I changed no settings between the back tests most of the time the result was as expected (no change in profit result). then I stopped and deleted the market watcher and re ran the same backtest without changing anything.

**Expected result** (what you hoped would happen)
no change to results

**Actual result** (unexpected outcome)
before stopping market watcher -37% profit:
![result](https://user-images.githubusercontent.com/41784698/43512412-fbfe0bbc-9572-11e8-9435-d58b4a078490.png)

After stopping market watcher -80% profit: ??
![result2](https://user-images.githubusercontent.com/41784698/43512528-395e18b2-9573-11e8-940d-63601097ad1b.png)

I've no idea what to think, can I trust any backtest result Iv'e had?

**Comment by askmike** [comment]
Will look into your example in details asap, for now see this: #2219.

**Comment by rkingy** [comment]
5min strategy? Make sure it always starts on the 5th minute.

I have the same issue, have put a code fix in https://github.com/askmike/gekko/issues/2219 that you could check out.
