### ISSUE TITLE
Web UI back test timeout

### ISSUE THREAD

**Issue by DavidFricker** [askmike/gekko#2395]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[X] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Installed Gekko on Windows 7
Launched using `node gekko --ui`
Tested with in-built simple strategies - working
Tested with custom strategy (over 1 day back test) - working
Tested same strategy with 30 days back test - here is the issue.
NB: My strategy takes ~.5 seconds to give long/short advice per update. 

**Expected result** (what you hoped would happen)
The usual graph and table should show up in the web UI show how bad I've undoubtedly performed.

**Actual result** (unexpected outcome)
After a few minutes the web UI "Running back test.." notice disappears. The back-testing is still ongoing because I can see my logs in the console. Once the back testing is complete (according to console output) the results do not show up in the web UI. 

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
It seems as if there is a time out caused by my slow strategy? Is there anywhere I can view the results in a log or reconnect to see the results in the web UI?

**Comment by askmike** [comment]
> NB: My strategy takes ~.5 seconds to give long/short advice per update.

: o

So here is what is happening under the hood:

1. The UI (your browser) will ask the Gekko Server to perform a backtest. This is done by a REST call to the API.
2. The server will start a backtest (in a gekko instance running in a child process).
3. Once the child process is done it will give all the data back to the server.
4. The server will pass the data back to your browser.

Though the server will shut the REST call down after a timeout, which defaults to 2 minutes. 

-----

> It seems as if there is a time out caused by my slow strategy? Is there anywhere I can view the results in a log or reconnect to see the results in the web UI?

There are 2 things you can do:

**increase the timeout**

in your UIconfig, increase this:

https://github.com/askmike/gekko/blob/e131819ab4c394460130b68c17dbe22c80371531/web/vue/dist/UIconfig.js#L12

Note that this should work locally, but if you are running the Gekko server somewhere else (in the cloud) there might be a ton of other network layers in between with timeouts. REST calls are not meant to last that long.

**Use the CLI interface**

Anything you can do in the UI you can also do over the commandline, this way are no layers between you and the code that runs your backtest (the gekko instance). And these kind of timeouts are not an issue. Though this also means you don't get a nice chart. Read more here on how to configure the CLI interface (it's a bit more low level): https://gekko.wizb.it/docs/commandline/about_the_commandline.html

Closing this as it's not really a bug, but feel free to keep commenting.

**Comment by DavidFricker** [comment]
Thank you for your prompt and in-depth response, it has helped greatly!
