### ISSUE TITLE
Gekko leaving Dust (Binance)

### ISSUE THREAD

**Issue by cuthulino** [askmike/gekko#2397]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[X] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Long triggered, Gekko bougth. 
Short triggered, Gekko sold.

**Expected result** (what you hoped would happen)
Gekko should sell the whole asset if it is possible from the exchange.
(not leave any dust)

**Actual result** (unexpected outcome)
In this case there were 159 XLM left. (dust)

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
I logged in to Binance and sold it manually -> no problem.
Gekko should be able to sell without dust, if the exchange allows the size of the position.

**Comment by askmike** [comment]
dup of #2393, will comment on selling there :)
