### ISSUE TITLE
Gekko Broker passed an `undefined` orderSummary

### ISSUE THREAD

**Issue by alexandershalin** [askmike/gekko#2399]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Manually added some ETH to Binance when tradebot trading ETH/SNT was running.

**Expected result** (what you hoped would happen)
Tradebot should run without troubles.

**Actual result** (unexpected outcome)
Tradebot finished round and started a new one (at this point with more ETH on my exchange account). Bought SNT with ETH, sold SNT and crashed.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

```
This is an archived Gekko, it is currently not running anymore.
This is Gekko crashed with the following error: {}
```
[2018-07-30-12-20-tradebot-653781870961659.log](https://github.com/askmike/gekko/files/2252481/2018-07-30-12-20-tradebot-653781870961659.log)

**Comment by askmike** [comment]
> 2018-08-01 22:09:41 (INFO):	[ORDER] summary: undefined

Is the problem, will look into this. Might need to add more verbose logging around this. Strange, never seen this before.

> Manually added some ETH to Binance when tradebot trading ETH/SNT was running.

Should only effect profit calculations, shouldn't have this impact on the bot itself (adding capital that is).

**Comment by askmike** [comment]
I was able to reproduce this locally _once_, but I'm really not sure what causes this. I've now added a ton of debug logging that should point me to the culprit once it happens again..

**Comment by askmike** [comment]
Added logging around this situation here: https://github.com/askmike/gekko/commit/2bc2945e22e1324c30774ae6235ecb8bd8677c83

Closing this now, if it pops up again please reopen :)
