### ISSUE TITLE
Gekko will bug when asking bitcoincharts for data older than 150000 seconds

### ISSUE THREAD

**Issue by askmike** [askmike/gekko#24]
When asking for data from over 150,000 seconds ago Gekko will receive candles where the oldest one is a lot newer than the since date. This will cause the first couple of candles to be NaN and all EMA calculations will glitch from that point.

**Comment by wupeng1211** [comment]
node-bitcoincharts
An unofficial node.js client for the bitcoin charts markets api.

Installation

node-bitcoincharts is available as bitcoincharts on npm.

npm install bitcoincharts
Usage

var BitcoinCharts = require('bitcoincharts'),
    bitcoinCharts = new BitcoinCharts();

bitcoinCharts.weightedPrices(function(err, data) {
  if (err) {
    throw err;
  }

  console.log(data);
});

bitcoinCharts.markets(function(err, data) {
  if (err) {
    throw err;
  }

  console.log(data);
});

bitcoinCharts.trades({ "symbol": "mtgoxUSD", "start": 1365670800, "end": 1365670860 }, function(err, data) {
  if (err) {
    throw err;
  }

  console.log(data);
});

**Comment by wupeng1211** [comment]
https://www.npmjs.com/package/bitcoincharts
