### ISSUE TITLE
UI doesn't log tradeError or tradeAbort information

### ISSUE THREAD

**Issue by alexandershalin** [askmike/gekko#2401]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)

Started tradebot

**Expected result** (what you hoped would happen)

Tradebot should place orders

**Actual result** (unexpected outcome)

Tradebot doesn't handle problems with exchange API, e.g. trading permission is turned off. 

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

```
2018-08-02 09:07:29 (ERROR):	[ORDER] Gekko received error from GB: Error -2015: Invalid API-key, IP, or permissions for action.
2018-08-02 09:07:29 (DEBUG):	Error: Error -2015: Invalid API-key, IP, or permissions for action.
    at /home/ubuntu/gekko/exchange/wrappers/binance.js:74:15
    at Request.request [as _callback] (/home/ubuntu/gekko/exchange/node_modules/binance/lib/rest.js:90:25)
    at Request.self.callback (/home/ubuntu/gekko/exchange/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/ubuntu/gekko/exchange/node_modules/request/request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/ubuntu/gekko/exchange/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)
```

**Comment by askmike** [comment]
So Gekko divides exchange errors into two groups:

- generic exchange/network errors -> Gekko will keep on retrying in case they happen
- critical errors -> This is a good example of a critical error.

In this example binance is telling Gekko that there is a problem with the API keys, read:

> Invalid API-key, IP, or permissions for action.

There is nothing Gekko can do about it, you need to fix your keys. Gekko won't be able to trade, but Gekko will keep running and keep trying (and log errors for as long as it happens).

What kind of behavior are you expecting?

**Comment by alexandershalin** [comment]
The reason I reported this issue: Binance turned trading permission automatically because of low trades volume from this IP (or something like this). I received an email from Binance about it. But having ~10 different API keys, it's was hard to understand which particular key I need to renew. I expect Gekko should warn in UI that something's wrong is with API key.

**Comment by askmike** [comment]
Your situation does sound quite complex. But I do agree with:

> I expect Gekko should warn in UI that something's wrong is with API key.

Though this doing this properly is very hard, as we'd need to normalize critical errors into "this has to do with your API key or IP address" over all Gekko supported exchanges.

What we can do for now: Since Gekko generates a [tradeErrored](https://gekko.wizb.it/docs/internals/events.html#tradeErrored-event) event whenever this happens (which is already pushed to the UI but not right now configured to persist).
