### ISSUE TITLE
Exchanges Tab is blank while data importing

### ISSUE THREAD

**Issue by alexanderngeth** [askmike/gekko#2403]
I've followed exactly what the video taught, step by step. Everything was fine until the import data step, the exchanges tab is blank on the Gekko UI, there's nothing for me to select and import data.

Here's a link to the screenshot: https://imgur.com/nztKTBU

**Comment by askmike** [comment]
The video is a bit old and there are now two extra steps in the installation process now. I am unable to add some text to the video unfortunately. Will upload a new one soon.

You need to do 2 more things:

1. install git
2. install gekko broker dependencies.

Find info on both here: https://gekko.wizb.it/docs/installation/installing_gekko.html

**Comment by arnaujunquera** [comment]
I've already ibstalled git but it doesn't work. Could you make another video?

**Comment by bluesammer** [comment]
I have same problem. installed everything

**Comment by Subway4711** [comment]
Had the same problem.
I installed lodash via: npm install lodash@2.x
