### ISSUE TITLE
Kraken, order not moving, fill not detected

### ISSUE THREAD

**Issue by dugu-dugu** [askmike/gekko#2412]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Run gekko

**Expected result** (what you hoped would happen)
Automated moving of buy/sell order, detection of filled order

**Actual result** (unexpected outcome)
Order didn't move, gekko didn't see when the order was filled

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Gekko placed a buy order. It didn't move the order. Eventually, the order was filled, in one transaction. Gekko didn't detect that either. Then Gekko wanted to place a sell order. It couldn't do it, because it said, it's still buying (it wasn't),

Gekko 0.6.4, development branch, git pull from August 2nd.

Logs attached.
[kraken-order-bug.txt](https://github.com/askmike/gekko/files/2263979/kraken-order-bug.txt)
![screenshot_20180806_231449](https://user-images.githubusercontent.com/41471105/43739140-b54d1dd2-99cf-11e8-947d-1089643239e9.png)

**Comment by starkadd3r** [comment]
i experienced the same. gekko placed a sell order and order was filled. on the next buy advice gekko says "ignoring advice: already in the process of selling". closing sell order does not overlap with new buy advice.

so depending on the last order type and the following advice type, gekko says:
- ignoring advice: already in the process to sell/buy
- ignoring advice: already cancelling previous sell/buy order

and all following advices are ignored. to fix it, gekko must be restarted. but this is not a proper solution.

it seems gekko does not get feedback of a closed buy or sell transaction.

Gekko 0.6.4, development branch, git pull from August 3rd

**Comment by dugu-dugu** [comment]
With the current git pull, I have two orders that were properly opened, moved, filled, everything went smoothly. Probably because they were very bad trades that lost me 10% of my money. Everything goes well when that happens. Bugs only show up when I could make a profit. :)
[no_problems.txt](https://github.com/askmike/gekko/files/2270630/no_problems.txt)

**Comment by starkadd3r** [comment]
i guess that this error is due to wrong state and/or wrong set sticky flag in sticky.js so api.cancel is never invoked. this should be an easy task for someone how knows gekko and its design. so setting state and/or sticky flag in the right manner and right place should solve this. i hope this helps a bit.

**Comment by askmike** [comment]
@starkadd3r since people are only having this with Kraken I doubt it's inside the core sticky logic. Most likely a problem with the kraken api wrapper described here: https://github.com/askmike/gekko/blob/develop/exchange/wrappers/kraken.js

This issue is on my list, will try to get around it asap.

**Comment by starkadd3r** [comment]
@askmike ... thx for your reply. because i'm no expert i did a quick and dirty solution to this and it works so far. gekko runs for some days now - even if the order is touched - it cancels it successfully. i set the status and sticky flag outside - in trader.js - if a cancel is needed which is not a good way. i guess - how you mentioned - the order status must be set correctly if the order is touched in kraken.js

-have a nice day!

**Comment by askmike** [comment]
I am working on Kraken stability, keep an eye out on #2502.
