### ISSUE TITLE
Notifications (Mailer/PushBullet) with UI running?

### ISSUE THREAD

**Issue by ampyxx** [askmike/gekko#2415]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
I am trying to enable either PushBullet or Mailer notifications while still having access to the UI, is this at all possible?

**Expected result** (what you hoped would happen)
Expecting to be able to have notifications about trades according to the strategy

**Actual result** (unexpected outcome)
No configuration is working currently to allow notifications with UI running

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
Unfortunately not at the moment :(

The new UI will definitely include this!

**Comment by askmike** [comment]
Closing this as this is the bug tracker. If you want to discuss this further please do so on the forum, read this: https://gekko.wizb.it/docs/introduction/getting_help.html
