### ISSUE TITLE
BITTREX: order succesfully created but checkOrder throws exception

### ISSUE THREAD

**Issue by starkadd3r** [askmike/gekko#2416]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ X] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
- set tradable: true; in bittrex.js
- started gekko CLI@bittrex
- api keys are working fine - no issue here so far
- on sell advice sell order is successfully created
- gekko throws exception: throw 'a'; in bittrex.js - 203 - function checkOrder

**Expected result** (what you hoped would happen)
- gekko can checkOrder and continue

**Actual result** (unexpected outcome)
- gekko crashes

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Gekko 0.6.4, development branch, git pull from August 3rd.

**Comment by askmike** [comment]
Live trading at Bittrex is not supported in 0.6 (because I can't test it, see #2310), it's not supposed to run at all. Did you not get an error when starting it?

**Comment by starkadd3r** [comment]
No errors when starting gekko. I pulled yesterday the latest commits. there was an update regarding bittrex.api. I installed module node.bittrex.api and started gekko again. i'm not sitting in front of that computer. but i can see that an sell order was created but gekko doesnt reply on telegram messages that means gekko crashed again after checkOrder. i will check it tonight.

**Comment by starkadd3r** [comment]
Ah, ok ... i see. checkOrder needs to be further implemented. no properties (open, executed, filledAmount) for callback there.

**Comment by askmike** [comment]
Yes, that's because I am unable to test bittrex as the API keeps complaining about invalid API keys - see #2310.

Live trading won't be possible until that's resolved. As to your other problems: I've addressed them in #2424
