### ISSUE TITLE
Error when opening gekko ui

### ISSUE THREAD

**Issue by moo5e** [askmike/gekko#2419]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ X] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
I installed gekko following the installation processes and opened attempted to open gekko through 'node gekko --ui'

**Expected result** (what you hoped would happen)
Gekkos ui would open in the local host

**Actual result** (unexpected outcome)
I got this error:
"SCRIPT1028: SCRIPT1028: Expected identifier, string or number".

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
Went to debug and the error is from the reduceState.js file.
The exact part:
"  state = {
    ...state,
    latestUpdate: new Date()
  }"
Any help would be much appreciated,
Thank you

**Comment by askmike** [comment]
I think your version of nodejs is too old. What version do you have?

**Comment by moo5e** [comment]
version 10.8.0,
I tried reinstalling everything and still the same error

**Comment by askmike** [comment]
And where are you getting that error? In your browser or on the command line? If browser: what browser & what version?

**Comment by moo5e** [comment]
Sorry for the late response,
The error was from commandline

**Comment by moo5e** [comment]
correction, the error was from microsoft edge, latest version

**Comment by askmike** [comment]
Are you able to try either Chrome or Firefox? I can't run edge since it's windows only.

**Comment by moo5e** [comment]
It runs perfectly on chrome, very simple fix. Thank you very much
