### ISSUE TITLE
Wrong dates in the UI grap

### ISSUE THREAD

**Issue by 123qweas** [askmike/gekko#2420]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Made a backtest in the UI

**Expected result** (what you hoped would happen)
Be able to see the correct dates in the graph.

**Actual result** (unexpected outcome)
The dates are wrong. (see the picture)
This happens with every strategy, history size and candle size I used.
I updated gekko to the newest stable version and still had this problem.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, 
![1](https://user-images.githubusercontent.com/38592482/43856511-03620382-9b49-11e8-8587-9c56f8f49b05.PNG)

links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
Is that a very long backtest from a year/few months? I can't see from the picture what's wrong about it.

**Comment by 123qweas** [comment]
Yes it is like 10 months.

**Comment by askmike** [comment]
I cannot reproduce, can you post the output of the command `node gekko --version`?
