### ISSUE TITLE
API keys in toml

### ISSUE THREAD

**Issue by benjiqq** [askmike/gekko#2425]
be able to read apikeys from .toml file

```
[binance]
key
secret
```

**Comment by askmike** [comment]
Config is messed, and docs are bad apologies:

All the TOML stuff will be deprecated when the new UI goes live. See here for more on that: https://forum.gekko.wizb.it/thread-1429.html

Right now the TOML files are only used to populate default values in the current UI, here:

<img width="772" alt="screen shot 2018-08-10 at 18 59 29" src="https://user-images.githubusercontent.com/969743/43954562-88ec5516-9ccf-11e8-89e5-db420b734abd.png">

Which started as a quick and hacky way of letting users edit JSON values. Though when you edit these files the UI (frontend) will compile that TOML into JSON which is send to Gekko, specifically here: https://gekko.wizb.it/docs/internals/server_api.html#POST-api-backtest

In other words: TOML is not used by Gekko, only by frontend code. And in the next UI TOML won't be used at all.

------

If you are using Gekko over the commandline you need to pass Gekko a javascript file that exposes a config object. You can build this module however you want, if you want to pull api keys from ENV variables (for opsec reasons you can simply change this:

https://github.com/askmike/gekko/blob/01212c2c23adf729c4787b66011798e42afdef1a/sample-config.js#L93-L94

to ENV variables, which in nodejs you can access through `process.env.MY_API_KEY`.

Or if you really want TOML you can put your api keys in a toml parse and parse it before populating the trader object of the config. Something like:

    var toml = require('toml');
    var fs = require('fs')
    var apiKeys = toml.parse(fs.readFileSync('./my-api-keys.toml', 'utf8'));

**Comment by askmike** [comment]
Closing this but feel free to keep commenting!
