### ISSUE TITLE
Live Trading on Binance, Gekko encountered an error and can't continue: no error details 

### ISSUE THREAD

**Issue by genesiscrew** [askmike/gekko#2430]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[tick ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
ran gekko live trading through terminal using this command 
node gekko --config config.js 
**Expected result** (what you hoped would happen)
i expected live trader to start  working

**Actual result** (unexpected outcome)
Gekko encountered an error and can't continue:
** no error message followed so impossible to debug

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

im running it on a linux server, and am using ther terminal to execute the commands.
backtesting works, and papertrading works, however when i disable paper trading, and enable live trading i get the error message but without it specifying what error is...

**Comment by askmike** [comment]
Hey! Thanks for the bug report. I'd need a bit more information to trouble shoot this:

- Please post full output
- Please post the output of `node gekko --version`

**Comment by genesiscrew** [comment]
node gekko --config config.js 

    ______   ________  __    __  __    __   ______
   /      \ /        |/  |  /  |/  |  /  | /      \
  /$$$$$$  |$$$$$$$$/ $$ | /$$/ $$ | /$$/ /$$$$$$  |
  $$ | _$$/ $$ |__    $$ |/$$/  $$ |/$$/  $$ |  $$ |
  $$ |/    |$$    |   $$  $$<   $$  $$<   $$ |  $$ |
  $$ |$$$$ |$$$$$/    $$$$$  \  $$$$$  \  $$ |  $$ |
  $$ \__$$ |$$ |_____ $$ |$$  \ $$ |$$  \ $$ \__$$ |
  $$    $$/ $$       |$$ | $$  |$$ | $$  |$$    $$/ 
   $$$$$$/  $$$$$$$$/ $$/   $$/ $$/   $$/  $$$$$$/

	Gekko v0.6.3
	I'm gonna make you rich, Bud Fox. 



Gekko encountered an error and can't continue

Error:

Do you understand what Gekko will do with your money? Read this first:

https://github.com/askmike/gekko/issues/201 



Meta debug info:

Gekko version: v0.6.3
Nodejs version: v8.11.3

**Comment by genesiscrew** [comment]
i fixed the issue, you can close it now, thanks mike.

**Comment by askmike** [comment]
:+1:

**Comment by jacobpdq** [comment]
@genesiscrew @askmike any idea what the problem is? I'm encountering the same - help!
