### ISSUE TITLE
[DOCKER] SelectBox is Empty - GB deps are not installed

### ISSUE THREAD

**Issue by mehmetaydogduu** [askmike/gekko#2443]
I installed and started via docker.

The api key exchange selectbox or any selecbox are looking empty.

**Comment by askmike** [comment]
That's a problem that usually happens when you haven't installed all dependencies, specifically those for Gekko Broker. What version of Gekko did you download?

You'll need a Dockerfile that comes with this:

https://github.com/askmike/gekko/blob/3f8e26d63175847729e6b9d9ca4f9d52ea26e562/Dockerfile#L20-L25

**Comment by wuzzap** [comment]
i have the same issue with the actually stable version. "npm audit" says there are 11 vulnerabilities that require manual review. but i dont know how to fix them.

example:

┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Denial-of-Service Memory Exhaustion                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ qs                                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >= 1.x                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ 32e991fabf2aec1521df041326702f6f9bdbe9533a43797b7279ea7269d… │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ 32e991fabf2aec1521df041326702f6f9bdbe9533a43797b7279ea7269d… │
│               │ > request > qs                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/29

**Comment by YuriyTigiev** [comment]
I have the same problem

**Comment by askmike** [comment]
> i have the same issue with the actually stable version. "npm audit" says there are 11 vulnerabilities that require manual review. but i dont know how to fix them.

You don't need to fix them, these are not actually security issues. I assume this is fixed, if not: delete your gekko installation and reinstall from scratch. Run commands find in the installation doc and do not run commands npm tells you to run... I'll update all deps asap but Gekko is an old codebase.

**Comment by mbartyzel** [comment]
And that was a protip! Do not run npm suggestions.
