### ISSUE TITLE
How to know in stategy if last order was filled

### ISSUE THREAD

**Issue by nicolasbonnici** [askmike/gekko#2444]
[ ] bug report
[x] question about the decisions made in the repository

**Action taken** (what you did)
My custom strategy was buying asset coins on a minute candle at 15h19, then wanted to sell 2 minutes after at 15h21.

**Expected result** (what you hoped would happen)
Wait until the order is filled then retry the sell.

**Actual result** (unexpected outcome)
Cancel the previous order

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

With Gekko 0.6.3 and Binance Exchange

Log output

2018-08-14 15:21:01 (INFO):     Received advice to sell however Gekko is already in the process to buy
2018-08-14 15:21:01 (INFO):     Canceling buy order first

Is there a way to know if the previous order was correctly filled at a strategy level?

**Comment by askmike** [comment]
> Wait until the order is filled then retry the sell.

Selling and buying has costs, so if your strat said buy and reverted to sell quickly Gekko will try to stop the buy so you don't have to sell as much anymore.

> Is there a way to know if the previous order was correctly filled at a strategy level?

There is an experimental way right now, you can add a function called `processTrade` to your strategy which will be passed a [tradeCompleted event](https://gekko.wizb.it/docs/internals/events.html#tradeCompleted-event). For example:

https://github.com/askmike/gekko/blob/8bb1b23289f5ec9085ca3b6ada01c5684d4074cd/strategies/DEBUG_toggle-advice.js#L17-L19

Note that this exact function and event might change as part of #2429. Keep an eye on that PR :)
