### ISSUE TITLE
candleLoader.js not utilizing 'from' and 'to' config parameters properly

### ISSUE THREAD

**Issue by Shloosh** [askmike/gekko#2445]
**I'm submitting a ...**
[x] bug report

**Action taken** (what you did)
I should preface this by saying that I'm new to both node.js and this codebase. 

I'm experimenting with using a genetic algorithm with gekko, so I have a separate javascript file. In that file, I'm trying to load previously imported candle data to feed to the genetic algorithm.

After taking a look at the server API, I see that there is a call named [getCandles](https://gekko.wizb.it/docs/internals/server_api.html#POST-api-getCandles) that takes a config with a few essential paramters and returns candles. This is the ajax call I make to getCandles:
```
let config = {
  watch: {
    exchange: 'gdax',
    currency: 'USD',
    asset: 'BTC'
  },
  daterange: {
    from: '2018-05-01 07:00',
    to: '2018-05-01 07:10'
  },
  candleSize: 1
}

export let candles = new Promise(function (resolve, reject) {
  post('getCandles', config, (err, res) => {
    if(!res || res.error || !_.isArray(res))
      reject(res);

    candles = res.map(c => {
      c.start = moment.unix(c.start).utc().format();
      return c;
      //resolve(c);
    });
    resolve(candles);
  })
});
```
and then, in a custom vue component I created, I'm logging the candles like so:
```
mounted() {
  var myScript = require('[path to file].js');
  myScript.candles.then(function(res) {
    console.log(res);
  });
}
```

**Expected result** (what you hoped would happen)
I expected to get 10 minutely candles.

**Actual result** (unexpected outcome)
I got 1000 minutely candles.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

The reason I'm getting 1000 candles is because there is a constant called batchSize in gekko/core/tools/candleLoader.js that is set to 1000
`const batchSize = 1000;`
and this is then used to create an iterator in that same file
```
let iterator = {
  from: from.clone(),
  to: from.clone().add(batchSize, 'm').subtract(1, 's')
}
```
which is then sent to the database reader in the getBatch() function.

I'm not sure if I'm incorrectly using the api, or if the candleLoader is an outdated script, or if this is an actual bug. Let me know if there's any other info I can provide.

**Comment by askmike** [comment]
> I expected to get 10 minutely candles.

~~In the payload of your request to gekko's API here:~~

    let config = {
      watch: {
        exchange: 'gdax',
        currency: 'USD',
        asset: 'BTC'
      },
      daterange: {
        from: '2018-05-01 07:00',
        to: '2018-05-01 07:10'
      },
      candleSize: 1
    }

~~You pass a candleSize of 1, this is Gekko slang for "1 minutely candles" - if you want 10 minutely candles set it to 10.~~

Scratch that, I read your issue wrong! Looking into this asap.

**Comment by Shloosh** [comment]
Thanks man. Until an official update, I fixed the issue by making a simple edit to the iterator varaible in candleLoader.js:
```
let iterator = {
  from: from.clone(),
  to: to.clone()
}
```
