### ISSUE TITLE
Import data very slow

### ISSUE THREAD

**Issue by ghost** [askmike/gekko#2448]
Sorry guys, but i've tried to reinstall and i keep with the same issue

**I'm submitting a ...**
[ ] bug report
[x ] question 

**Action taken** (what you did)
I've been trying to improt data from Binance and i can't get anything.

**Expected result** (what you hoped would happen)
Download the data

**Actual result** (unexpected outcome)
Keep stuck import and the file on /history doesn't get more size

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Serving Gekko UI on http://localhost:3000/
Keep stuck at this
  <-- GET /favicon.ico
  --> GET /favicon.ico 404 3ms -
  <-- GET /api/imports
  --> GET /api/imports 200 184ms 2b
  <-- GET /api/gekkos
  --> GET /api/gekkos 200 110ms 24b
  <-- GET /api/apiKeys
  --> GET /api/apiKeys 200 5ms 2b
  <-- GET /api/exchanges
  --> GET /api/exchanges 200 637ms 87.73kb
  <-- GET /api/configPart/performanceAnalyzer
  <-- GET /api/strategies
  <-- GET /api/configPart/paperTrader
  --> GET /api/configPart/performanceAnalyzer 200 156ms 144b
  --> GET /api/configPart/paperTrader 200 633ms 132b
  --> GET /api/strategies 200 648ms 2.13kb
  <-- POST /api/import
Import 2668443677219203 started
  --> POST /api/import 200 92ms 149b
I already reinstalled everything, i should import my API to import data faster ?
Please, help, thanks in advance.

**Comment by askmike** [comment]
The importer is quite old, but nonetheless it's important to realize:

Gekko gets market data directly from exchanges, and exchanges have limits on how much data you can request (per minute). These limits are called rate limits. Also note that Gekko gets market data by collecting trades, and only later bucketing all trades from one minute into a candle (importing periods with a lot of trading will take longer than other periods).

That said, Binance rate limits for importing (the `aggTrades` endpoint Gekko uses) are quite insane, it only has a weight of 1 (meaning you can are allowed to call the endpoint 20 times a sec). Whereas Gekko has a limit of only doing it once per second now..

Dirty hack you can appy yourself: https://forum.gekko.wizb.it/thread-57571-post-59998.html#pid59998 - applying that hack means the importer breaks for all other exchanges and your IP might get banned.

------

Proper solution: we need to change the static 1 second into something different per exchange, best would be a new property like getTradesInterval inside the [getCapabilities](https://gekko.wizb.it/docs/extending/add_an_exchange.html#Capabilities) method per exchange.

I'm a bit busy, would anyone else be willing to pick this up?

**Comment by Draichi** [comment]
hey @askmike i've been working in a tool inspired by your _bud fox_, [here](https://bud-fox.github.io/live/)
It get historical data from a bunch of exchanges pretty fast.
I can try to implement on gekko when i get some time.

idk take a look and tell me if would be a good thing, code [here](https://github.com/Bud-Fox)
(it also do a price prediction using machine learning)
