### ISSUE TITLE
Re-enable back testing feature

### ISSUE THREAD

**Issue by SamThomp** [askmike/gekko#245]
Is the back testing feature coming back in a later release? I've been attempting to add the functionality myself but I'm not sure what would be the best way to add the feature. 

Would modifying the processHistory method in the Market manager, by adding a method to read a candles from file help to achieve having a backtesting feature?

**Comment by randy-jr-olive** [comment]
Is there work going on with the backtester somewhere on github? I'd like to see where it's at and maybe add if I can.
