### ISSUE TITLE
log.debug- does not work anymore with 0.6.5

### ISSUE THREAD

**Issue by jasurakk** [askmike/gekko#2451]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ x  ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
I updated from older 0.5.x Gekko to the newest one (0.6.5), and after that I do not get any log writings on the console from my strategies. And the sample-config.js- file still has a line "config.debug = true; "

**Expected result** (what you hoped would happen)
log.debug- would write to the console.

**Actual result** (unexpected outcome)
There isn't any ouput on the console.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
I'm running Gekko on Windows 10. On Gekko's Discord- channel it was said that this problem has been found also with mac.

**Comment by askmike** [comment]
Can you tell me more what you are doing?

- Are you using the UI?
- What did you try to run?
- Are you running via CLI and have `config.silent` set to true?

**Comment by jasurakk** [comment]
- Yes I'm using UI
- I'm doing backtesting for my own strategies, which should print debug info to the console
- Third question I did not quite understand.... As I said I'm using the UI since I'm doing backtesting for my srategies. Don't know about the config.silent, where shoult it be?

Anyway, I did not change anything on my strategies after updating to the 0.6.5, and with previus Gekko all logs where shown just fine. Could it be that there is some setting in some config file at 0.6.5, which defaults so that the logs are not shown?

**Comment by askmike** [comment]
Are you sure this worked before 0.6.5? It did around 0.6 (or just before) but that was not optimal.

log.debug generates megabytes of logging in any backtest of decent size, this will spam your terminal and slow down your backtest.

The recommended approach is to use the commandline to test and debug strategies. I just wrote a guide for it: https://forum.gekko.wizb.it/thread-57581.html

**Comment by jasurakk** [comment]
I'm sure it worked on 0.5.x since I've been testing my strategies for months with it. And I did not have any problem with the log size or terminal, since I usually I have only a few log.debug- lines at the same time, depending on what parts I'm testing. 

And when I'm backtesting, I really need to see the results on a price chart, so that I can be sure that my strategy did buy & sell on the correct places. And I also use the graph for visually analyzing & improving my traging method. Is this anyhow possible without the UI? Could the CLI version store that graph somewhere?

**Comment by askmike** [comment]
Here is how to get them in the UI (note that this is not recommended):

Inside this function:

https://github.com/askmike/gekko/blob/bc745a2afcebe39695ed9496b7f445d0df6ca4ec/core/workers/pipeline/messageHandlers/backtestHandler.js#L7-L15

Add the following if check:

      if(message.log === 'info') {
        console.log(message.message);
      }

**Comment by askmike** [comment]
> And I also use the graph for visually analyzing & improving my traging method. Is this anyhow possible without the UI? Could the CLI version store that graph somewhere?

I'm working on a new UI that is able to read backtests that are stored on disk by a plugin called the backtestExporter. However that UI is not finished yet, result looks like this: https://gp.mvr.me

**Comment by jasurakk** [comment]
Great, thanks askmike! 

But just to be sure; if that method is not recommended, which one would be??

**Comment by askmike** [comment]
There is no good one right now, best is to wait for that new UI :)

**Comment by jasurakk** [comment]
Ok, thank you! And that new UI looks great, keep up the good work! :=)
