### ISSUE TITLE
Error after starting 

### ISSUE THREAD

**Issue by gr8linux** [askmike/gekko#2453]
**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

I install the last version with 
git clone git://github.com/askmike/gekko.git
follow the standard instruction 
my node version is:
v8.11.4
When I try to do 
`npm install --only=production`
I had to do 
`npm audit fix --force`
I start the project with
`node gekko --ui`
after that I've got below error
```
TypeError: _.last(...).join is not a function
      at exchangesDir.filter.f (/root/src/trade/gekko/web/routes/exchanges.js:17:31)
      at Array.filter (<anonymous>)
      at Object.module.exports (/root/src/trade/gekko/web/routes/exchanges.js:17:6)
      at module.exports.next (<anonymous>)
      at Object.dispatch (/root/src/trade/gekko/node_modules/koa-router/lib/router.js:334:5)
      at dispatch.next (<anonymous>)
      at onFulfilled (/root/src/trade/gekko/node_modules/co/index.js:65:19)
      at <anonymous>

```
I could browse the url and see the web but nothing worked
No exchange list to add it seems there is no data available inside
Please give some help

**Comment by askmike** [comment]
A lot of people are having weird issues with npm related functions. When you cd into the gekko folder. Can you let me know the output of running `npm list | grep lodash`?

**Comment by gr8linux** [comment]
This is the result
```

│ └── lodash@4.17.10
│ ├── lodash@4.17.10
├── lodash@4.17.10
│ │ └── lodash@4.17.10
│ ├── lodash.get@4.4.2

```

**Comment by askmike** [comment]
That middle one is the wrong version. Can you manually delete your node_modules folder, make sure your `package-lock.json` file is the same as on github ([here](https://github.com/askmike/gekko/blob/stable/package-lock.json) if you downloaded the latest stable release) and re install the dependencies with `npm install`?

**Comment by gr8linux** [comment]
I do the installation again and it solve the problem I think the 
`npm audit fix --force`
should raise this issue in this round I skip the security fix but it may cause some issues on the way 
Thank's a lot

**Comment by askmike** [comment]
Great. Strange that npm prompted you to do that though.

**Comment by Remonell** [comment]
@gr8linux What did you reinstall? npm?

**Comment by gr8linux** [comment]
@Remonell  I reinstall because I guess the security update damage the packages.

**Comment by Remonell** [comment]
@gr8linux And what exactly did you reinstall? npm or gekko or something else?

**Comment by askmike** [comment]
I think he re installed all dependencies. I want to fix the packages npm is complaining about (even though there is no security impact in running the current versions). However until then don't let npm update packages, as that will break gekko.

**Comment by essramos** [comment]
I am having the same error. I removed node-modules folder under gekko directory and reinstalled all dependencies. 

This is error I am getting

```
  <-- GET /api/exchanges
  xxx GET /api/exchanges 500 1ms -

  TypeError: _.last(...).join is not a function
      at exchangesDir.filter.f (/home/ella/gekko/web/routes/exchanges.js:17:31)
      at Array.filter (<anonymous>)
      at Object.module.exports (/home/ella/gekko/web/routes/exchanges.js:17:6)
      at module.exports.next (<anonymous>)
      at Object.dispatch (/home/ella/gekko/node_modules/koa-router/lib/router.js:334:5)
      at dispatch.next (<anonymous>)
      at onFulfilled (/home/ella/gekko/node_modules/co/index.js:65:19)

```

lodash version after reinstall. 

```
│ └── lodash@4.17.10
│ ├── lodash@4.17.10
├── lodash@4.17.10
│ │ └── lodash@4.17.10
```

any idea what I missed?

**Comment by essramos** [comment]
I got it to work. I started from scratch, pulled gekko and then install dependencies, but I did ignore a security warning for lodash which I think I didn't when I first installed gekko, now everything worked after ignoring the warning.

**Comment by Nophi** [comment]
I have the same problem, how did you fix the problem? I performed an `npm audit fix --force`, I no longer have a problem with the install but when I run I don't have an exchange available and I have the same error.
Thx

**Comment by essramos** [comment]
@Nophi get a new copy of gekko and install all dependencies again, this time don't do the `npm audit fix --force` and see if that will work. I am not sure what the repercussions are for not fixing it though. @askmike Any issues if we dont fix the vulnerability?

**Comment by askmike** [comment]
no issues, I need to go through all of gekko to update dependencies.. Note that there is no security risk in using Gekko: the issues NPM is complaining about are not used by Gekko...

**Comment by Nophi** [comment]
It's ok, thanks

**Comment by MCPVOT** [comment]
Thank you so much i had same issue, up and running.

**Comment by mrcesc0** [comment]
I keep on getting 500 on /api/exchanges after reinstalled all node_modules... any idea?

**Comment by Martin-Luther** [comment]
I had the same issue and I had to replace the lodash version :
`npm install lodash@2.x`

**Comment by hacpro** [comment]
Hi guys. I know the Issue is already closed, but i cant sleep while you all are unsafe! never ignore the audit warnings :) 

- run: npm audit fix

- edit the file (line 17): gekkofolder/web/routes/exchanges.js
 change following code:

`
  const exchanges = exchangesDir
    .filter(f => _.last(f, 3).join('') === '.js')
    .map(f => f.slice(0, -3));
`

to

`  const exchanges = exchangesDir
    .filter(f => _.takeRight(f, 3).join('') === '.js')
    .map(f => f.slice(0, -3));`




loadash changed the impl of the "last" function. it dosent return any arrays anymore. but the "takeRight" function does.

i hope this may help you!

**Comment by bluesammer** [comment]
+-- async@2.1.2
| `-- lodash@4.17.11
+-- bitfinex-api-node@1.2.1
| +-- debug@2.6.9
| | `-- ms@2.0.0
| +-- lodash@4.17.11
| +-- request@2.87.0 deduped
| +-- request-promise@4.2.2 deduped
| `-- ws@3.3.3
|   +-- async-limiter@1.0.0 deduped
|   +-- safe-buffer@5.1.2 deduped
|   `-- ultron@1.1.1
+-- chai@4.1.2
| +-- assertion-error@1.1.0
| +-- check-error@1.0.2
| +-- deep-eql@3.0.1
| | `-- type-detect@4.0.8 deduped
| +-- get-func-name@2.0.0
| +-- pathval@1.1.0
| `-- type-detect@4.0.8
+-- co-fs@1.2.0
| +-- co-from-stream@0.0.0
| | `-- co-read@0.0.1
| `-- thunkify@0.0.1
+-- commander@2.17.0
+-- gekko@0.0.9
+-- humanize-duration@3.15.1
+-- koa@1.6.0
| +-- accepts@1.3.5
| | +-- mime-types@2.1.19 deduped
| | `-- negotiator@0.6.1
| +-- co@4.6.0
| +-- composition@2.3.0
| | +-- any-promise@1.3.0
| | `-- co@4.6.0 deduped
| +-- content-disposition@0.5.2
| +-- content-type@1.0.4
| +-- cookies@0.7.1
| | +-- depd@1.1.2
| | `-- keygrip@1.0.2
| +-- debug@2.6.9 deduped
| +-- delegates@1.0.0
| +-- destroy@1.0.4
| +-- error-inject@1.0.0
| +-- escape-html@1.0.3
| +-- fresh@0.5.2
| +-- http-assert@1.3.0
| | +-- deep-equal@1.0.1
| | `-- http-errors@1.6.3
| |   +-- depd@1.1.2 deduped
| |   +-- inherits@2.0.3 deduped
| |   +-- setprototypeof@1.1.0 deduped
| |   `-- statuses@1.5.0 deduped
| +-- http-errors@1.7.0
| | +-- depd@1.1.2 deduped
| | +-- inherits@2.0.3
| | +-- setprototypeof@1.1.0
| | +-- statuses@1.5.0 deduped
| | `-- toidentifier@1.0.0
| +-- koa-compose@2.5.1
| +-- koa-is-json@1.0.0
| +-- mime-types@2.1.19
| | `-- mime-db@1.35.0
| +-- on-finished@2.3.0
| | `-- ee-first@1.1.1
| +-- only@0.0.2
| +-- parseurl@1.3.2
| +-- statuses@1.5.0
| +-- type-is@1.6.16
| | +-- media-typer@0.3.0
| | `-- mime-types@2.1.19 deduped
| `-- vary@1.1.2
+-- koa-bodyparser@2.5.0
| +-- co-body@5.2.0
| | +-- inflation@2.0.0
| | +-- qs@6.5.2 deduped
| | +-- raw-body@2.3.3
| | | +-- bytes@3.0.0
| | | +-- http-errors@1.6.3
| | | | +-- depd@1.1.2 deduped
| | | | +-- inherits@2.0.3 deduped
| | | | +-- setprototypeof@1.1.0 deduped
| | | | `-- statuses@1.5.0 deduped
| | | +-- iconv-lite@0.4.23
| | | | `-- safer-buffer@2.1.2 deduped
| | | `-- unpipe@1.0.0
| | `-- type-is@1.6.16 deduped
| `-- copy-to@2.0.1
+-- koa-cors@0.0.16
+-- koa-logger@1.3.1
| +-- bytes@1.0.0
| +-- chalk@1.1.3
| | +-- ansi-styles@2.2.1
| | +-- escape-string-regexp@1.0.5 deduped
| | +-- has-ansi@2.0.0
| | | `-- ansi-regex@2.1.1
| | +-- strip-ansi@3.0.1
| | | `-- ansi-regex@2.1.1 deduped
| | `-- supports-color@2.0.0
| +-- humanize-number@0.0.2
| `-- passthrough-counter@1.0.0
+-- koa-router@5.4.2
| +-- co@4.6.0 deduped
| +-- debug@2.6.9 deduped
| +-- http-errors@1.7.0 deduped
| +-- methods@1.1.2
| `-- path-to-regexp@1.7.0
|   `-- isarray@0.0.1
+-- koa-static@2.1.0
| +-- debug@2.6.9 deduped
| `-- koa-send@3.3.0
|   +-- co@4.6.0 deduped
|   +-- debug@2.6.9 deduped
|   +-- mz@2.7.0
|   | +-- any-promise@1.3.0 deduped
|   | +-- object-assign@4.1.1 deduped
|   | `-- thenify-all@1.6.0
|   |   `-- thenify@3.3.0
|   |     `-- any-promise@1.3.0 deduped
|   `-- resolve-path@1.4.0
|     +-- http-errors@1.6.3
|     | +-- depd@1.1.2 deduped
|     | +-- inherits@2.0.3 deduped
|     | +-- setprototypeof@1.1.0 deduped
|     | `-- statuses@1.5.0 deduped
|     `-- path-is-absolute@1.0.1 deduped
+-- lodash@4.17.11
+-- mocha@5.2.0
| +-- browser-stdout@1.3.1
| +-- commander@2.15.1
| +-- debug@3.1.0
| | `-- ms@2.0.0 deduped
| +-- diff@3.5.0
| +-- escape-string-regexp@1.0.5
| +-- glob@7.1.2
| | +-- fs.realpath@1.0.0
| | +-- inflight@1.0.6
| | | +-- once@1.4.0 deduped
| | | `-- wrappy@1.0.2
| | +-- inherits@2.0.3 deduped
| | +-- minimatch@3.0.4 deduped
| | +-- once@1.4.0
| | | `-- wrappy@1.0.2 deduped
| | `-- path-is-absolute@1.0.1
| +-- growl@1.10.5
| +-- he@1.1.1
| +-- minimatch@3.0.4
| | `-- brace-expansion@1.1.11
| |   +-- balanced-match@1.0.0
| |   `-- concat-map@0.0.1
| +-- mkdirp@0.5.1
| | `-- minimist@0.0.8
| `-- supports-color@5.4.0
|   `-- has-flag@3.0.0
+-- moment@2.22.2
+-- opn@4.0.2
| +-- object-assign@4.1.1
| `-- pinkie-promise@2.0.1
|   `-- pinkie@2.0.4
+-- promisify-node@0.5.0
| +-- nodegit-promise@4.0.0
| | `-- asap@2.0.6
| `-- object-assign@4.1.1 deduped
+-- prompt-lite@0.1.1
| +-- async@0.1.22
| +-- colors@0.6.2
| +-- read@1.0.7
| | `-- mute-stream@0.0.7
| `-- revalidator@0.1.8
+-- proxyquire@1.8.0
| +-- fill-keys@1.0.2
| | +-- is-object@1.0.1
| | `-- merge-descriptors@1.0.1
| +-- module-not-found-error@1.0.1
| `-- resolve@1.1.7
+-- relieve@2.2.3
| +-- bluebird@3.5.1
| +-- debug@2.6.9 deduped
| +-- eventemitter2@2.2.2
| +-- ipcee@1.0.6
| | +-- debug@2.6.9 deduped
| | `-- eventemitter2@2.2.2 deduped
| `-- uuid@2.0.3
+-- request@2.87.0
| +-- aws-sign2@0.7.0
| +-- aws4@1.7.0
| +-- caseless@0.12.0
| +-- combined-stream@1.0.6
| | `-- delayed-stream@1.0.0
| +-- extend@3.0.2
| +-- forever-agent@0.6.1
| +-- form-data@2.3.2
| | +-- asynckit@0.4.0
| | +-- combined-stream@1.0.6 deduped
| | `-- mime-types@2.1.19 deduped
| +-- har-validator@5.0.3
| | +-- ajv@5.5.2
| | | +-- co@4.6.0 deduped
| | | +-- fast-deep-equal@1.1.0
| | | +-- fast-json-stable-stringify@2.0.0
| | | `-- json-schema-traverse@0.3.1
| | `-- har-schema@2.0.0
| +-- http-signature@1.2.0
| | +-- assert-plus@1.0.0
| | +-- jsprim@1.4.1
| | | +-- assert-plus@1.0.0 deduped
| | | +-- extsprintf@1.3.0
| | | +-- json-schema@0.2.3
| | | `-- verror@1.10.0
| | |   +-- assert-plus@1.0.0 deduped
| | |   +-- core-util-is@1.0.2
| | |   `-- extsprintf@1.3.0 deduped
| | `-- sshpk@1.14.2
| |   +-- asn1@0.2.4
| |   | `-- safer-buffer@2.1.2 deduped
| |   +-- assert-plus@1.0.0 deduped
| |   +-- bcrypt-pbkdf@1.0.2
| |   | `-- tweetnacl@0.14.5 deduped
| |   +-- dashdash@1.14.1
| |   | `-- assert-plus@1.0.0 deduped
| |   +-- ecc-jsbn@0.1.2
| |   | +-- jsbn@0.1.1 deduped
| |   | `-- safer-buffer@2.1.2 deduped
| |   +-- getpass@0.1.7
| |   | `-- assert-plus@1.0.0 deduped
| |   +-- jsbn@0.1.1
| |   +-- safer-buffer@2.1.2
| |   `-- tweetnacl@0.14.5
| +-- is-typedarray@1.0.0
| +-- isstream@0.1.2
| +-- json-stringify-safe@5.0.1
| +-- mime-types@2.1.19 deduped
| +-- oauth-sign@0.8.2
| +-- performance-now@2.1.0
| +-- qs@6.5.2
| +-- safe-buffer@5.1.2
| +-- tough-cookie@2.3.4
| | `-- punycode@1.4.1
| +-- tunnel-agent@0.6.0
| | `-- safe-buffer@5.1.2 deduped
| `-- uuid@3.3.2
+-- request-promise@4.2.2
| +-- bluebird@3.5.1 deduped
| +-- request-promise-core@1.1.1
| | `-- lodash@4.17.11
| +-- stealthy-require@1.1.1
| `-- tough-cookie@2.3.4 deduped
+-- retry@0.10.1
+-- semver@5.4.1
+-- sinon@4.5.0
| +-- @sinonjs/formatio@2.0.0
| | `-- samsam@1.3.0
| +-- diff@3.5.0 deduped
| +-- lodash.get@4.4.2
| +-- lolex@2.7.1
| +-- nise@1.4.10
| | +-- @sinonjs/formatio@3.2.1
| | | +-- @sinonjs/commons@1.4.0
| | | | `-- type-detect@4.0.8 deduped
| | | `-- @sinonjs/samsam@3.3.1
| | |   +-- @sinonjs/commons@1.4.0 deduped
| | |   +-- array-from@2.1.1
| | |   `-- lodash@4.17.11
| | +-- @sinonjs/text-encoding@0.7.1
| | +-- just-extend@4.0.2
| | +-- lolex@2.7.1 deduped
| | `-- path-to-regexp@1.7.0 deduped
| +-- supports-color@5.4.0
| | `-- has-flag@3.0.0 deduped
| `-- type-detect@4.0.8 deduped
+-- sqlite3@4.0.6
| +-- nan@2.10.0
| +-- node-pre-gyp@0.11.0
| | +-- detect-libc@1.0.3
| | +-- mkdirp@0.5.1 deduped
| | +-- needle@2.3.1
| | | +-- debug@4.1.1
| | | | `-- ms@2.1.1
| | | +-- iconv-lite@0.4.23 deduped
| | | `-- sax@1.2.4
| | +-- nopt@4.0.1
| | | +-- abbrev@1.1.1
| | | `-- osenv@0.1.5
| | |   +-- os-homedir@1.0.2
| | |   `-- os-tmpdir@1.0.2
| | +-- npm-packlist@1.4.1
| | | +-- ignore-walk@3.0.1
| | | | `-- minimatch@3.0.4 deduped
| | | `-- npm-bundled@1.0.6
| | +-- npmlog@4.1.2
| | | +-- are-we-there-yet@1.1.5
| | | | +-- delegates@1.0.0 deduped
| | | | `-- readable-stream@2.3.6
| | | |   +-- core-util-is@1.0.2 deduped
| | | |   +-- inherits@2.0.3 deduped
| | | |   +-- isarray@1.0.0
| | | |   +-- process-nextick-args@2.0.0
| | | |   +-- safe-buffer@5.1.2 deduped
| | | |   +-- string_decoder@1.1.1
| | | |   | `-- safe-buffer@5.1.2 deduped
| | | |   `-- util-deprecate@1.0.2
| | | +-- console-control-strings@1.1.0
| | | +-- gauge@2.7.4
| | | | +-- aproba@1.2.0
| | | | +-- console-control-strings@1.1.0 deduped
| | | | +-- has-unicode@2.0.1
| | | | +-- object-assign@4.1.1 deduped
| | | | +-- signal-exit@3.0.2
| | | | +-- string-width@1.0.2
| | | | | +-- code-point-at@1.1.0
| | | | | +-- is-fullwidth-code-point@1.0.0
| | | | | | `-- number-is-nan@1.0.1
| | | | | `-- strip-ansi@3.0.1 deduped
| | | | +-- strip-ansi@3.0.1 deduped
| | | | `-- wide-align@1.1.3
| | | |   `-- string-width@1.0.2 deduped
| | | `-- set-blocking@2.0.0
| | +-- rc@1.2.8
| | | +-- deep-extend@0.6.0
| | | +-- ini@1.3.5
| | | +-- minimist@1.2.0
| | | `-- strip-json-comments@2.0.1
| | +-- rimraf@2.6.3
| | | `-- glob@7.1.3
| | |   +-- fs.realpath@1.0.0 deduped
| | |   +-- inflight@1.0.6 deduped
| | |   +-- inherits@2.0.3 deduped
| | |   +-- minimatch@3.0.4 deduped
| | |   +-- once@1.4.0 deduped
| | |   `-- path-is-absolute@1.0.1 deduped
| | +-- semver@5.4.1 deduped
| | `-- tar@4.4.8
| |   +-- chownr@1.1.1
| |   +-- fs-minipass@1.2.5
| |   | `-- minipass@2.3.5 deduped
| |   +-- minipass@2.3.5
| |   | +-- safe-buffer@5.1.2 deduped
| |   | `-- yallist@3.0.3 deduped
| |   +-- minizlib@1.2.1
| |   | `-- minipass@2.3.5 deduped
| |   +-- mkdirp@0.5.1 deduped
| |   +-- safe-buffer@5.1.2 deduped
| |   `-- yallist@3.0.3
| `-- request@2.87.0 deduped
+-- stats-lite@2.1.1
| `-- isnumber@1.0.0
+-- tiny-promisify@0.1.1
+-- toml@2.3.3
`-- ws@6.0.0
  `-- async-limiter@1.0.0

**Comment by melroy89** [comment]
Same issue.. Still not fixed
