### ISSUE TITLE
Clear error message for missing broker dependencies

### ISSUE THREAD

**Issue by StevenHop** [askmike/gekko#2455]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ ] bug report
[X] question about the decisions made in the repository

**Action taken** (what you did)
Installing gekko without broker dependencies. When you run gekko, the error message is not clear for newbies.

**Expected result** (what you hoped would happen)
A clear error message like "Make sure Broker dependencies are set!".

**Actual result** (unexpected outcome)
Error messages in gekko, flooding on discord of users that don't have a clue in what they missed. Seen some on forum to.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
Maybe you are not aware but the discord channel is flooded by new users that have an error message that they cant link to the broker dependencies they missed in the documentation. We can off course, point hem to it but it would help if the error message was a bit more clear.

Now i do get that everything is in the documentation. And its a "nice to have", not a bug, but we all would benefit in more clear messages..

**Comment by askmike** [comment]
Very open to a PR for this in this case! Will pick it up myself in a bit, but if anyone wants to contribute this is should not be a hard one.

**Comment by askmike** [comment]
Fixed in latest develop, will land in next release. See #2464 for details.
