### ISSUE TITLE
External Reverse Proxy Does Resolve

### ISSUE THREAD

**Issue by circlenaut** [askmike/gekko#2458]
My instance of gekko (v0.5.13) has been running without issue through a reverse proxy located on another server within the same local network using the config below.
I've attempted to both upgrade using the upgrade guide [here](https://gekko.wizb.it/docs/installation/updating_gekko.html): and do a fresh install using [this](https://gekko.wizb.it/docs/installation/installing_gekko.html) guide. Unfortunately when copying over the web/vue/UIconfig.js and web/routes/baseConfig.js files to the new install the redirect address does not change from localhost to site.circlenaut.com which I believe is what's causing the reverse proxy to throw a 504 gateway not found error.
Is there something about the new v0.6 version that limits to localhost only? Are there new settings we need to address?
____________________________________________________________________

  GNU nano 2.5.3                      File: UIconfig.js                                                   

// This config is used in both the
// frontend as well as the web server.

// see https://github.com/askmike/gekko/blob/stable/docs/installing_gekko_on_a_server.md

const CONFIG = {
  headless: true,
  api: {
    host: '10.0.0.43',
    port: 3000,
  },
  ui: {
    ssl: true,
    host: 'site.example.com',
    port: 443,
    path: '/'
  },
  adapter: 'postgresql'
}

if(typeof window === 'undefined')
  module.exports = CONFIG;
else
  window.CONFIG = CONFIG;

**Comment by askmike** [comment]
> Unfortunately when copying over the web/vue/UIconfig.js

Just to be sure: In 0.6 you need to move that file to `web/vue/dist/UIconfig.js`. Did you do this?

>  the reverse proxy to throw a 504 gateway not found error.

Just wondering, what reverse proxy is that? NGINX talks about a timeout for 504.

**Comment by circlenaut** [comment]
That's it! Had to move to web/vue/dist/UIconfig.js. Thank you.
