### ISSUE TITLE
Gekko live don't work 

### ISSUE THREAD

**Issue by simoneant** [askmike/gekko#2459]
[2018-08-19 08-28-49.zip](https://github.com/askmike/gekko/files/2300137/2018-08-19.08-28-49.zip)

**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
When i open gekko every time appear the screen that tell me i'm disconnected, after when i want make a live trade and i push start gekko doesn't make nothing there's only the animation that works. I've upload a video in zip format so is more clear.

**Expected result** (what you hoped would happen)

**Actual result** (unexpected outcome)
I can't use gekko in live mode.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
I've installed gekko following the official website, https://gekko.wizb.it/docs/installation/installing_gekko_on_windows.html my system is windows 10 but i've tried on virtual machine with linux mint and give me the same problem.

**Comment by askmike** [comment]
That looks like microsoft edge, do you get the same result with firefox or chrome?

**Comment by simoneant** [comment]
In the video that i've uploaded here i've used firefox all software both windows and firefox at the last update. I've tried more times also with Google Chrome but unfortunaly with the same results. I've delated the folder of gekko and re-downloaded more times in the hope that changes something but nothing.
(In the video i've open the Edge browser only for search how use OBS because i've never used this software)

**Comment by askmike** [comment]
As to your your second error (trader won't start). People have reported problems with the websocket connection. A fix has been submitted but it is part of a stable release yet. See here: #2454. Would you mind trying that out and see if it solves your issue, you can get that version by following these steps: https://gekko.wizb.it/docs/installation/updating_gekko.html#Updating-the-develop-branch

As to your first error (ECONRESET), most likely the same as here: #2442 I'll keep that issue updated in regards to fixing it.

So I'll close this issue, but if the dev branch still does not fix your live trader please comment here and I'll reopen!
