### ISSUE TITLE
Market Watcher: Strat Calculations queue when no trades available for processing

### ISSUE THREAD

**Issue by storshun** [askmike/gekko#2461]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
1. "No new trades" are available from the exchange (binance in this case) and 2 or more candles of time elapse
2. A new trade is processed from the exchange at the next "request" interval

**Expected result** (what you hoped would happen)
1 candle of strategy calculation should be processed

**Actual result** (unexpected outcome)
All strategy calculations that should have run at the end of each candle, but no trades were available to process, ends up running at the same time as soon as a new trade is processed.

For instance: 
Candle Size: 3 Minutes
Strat: CCI

On XLM/ETH - No trades occurred for about 8 minutes.
As soon as a new trade could be processed -  and was processed - 3 CCI calculations were processed, and resulted in a false indication of a trend for 2 candles.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

The scenario above should - in my opinion - result in a single calculation and not trigger subsequent trend indications off a single data-point. Ideally, any time no data is available for a candle, that candle should not contribute to the calculation of a trend.

**Comment by askmike** [comment]
This is a design decision! The hard thing comes from some exchanges (in some scenarios) not sending a trade that happened at 11:59 until something like 12:06 (7 minutes later). By waiting for the next trade Gekko is not making any assumptions about lag anywhere between ME and Gekko (slow APIs under load, network issues, etc).

Note that is only a problem in very iliquid markets & on small candles. If you trade on 1 hour candles you'll hardly notice this when there are some trades.

There are a number of reasons why running Gekko with small candles on an illiquid market is a bad idea. For example see https://gekko.wizb.it/docs/features/backtesting.html#Simplified-simulation and https://github.com/askmike/gekko/issues/2380#issuecomment-408744682. I will try to explain this better in the docs.

Closing this but feel free to comment and let me know your thoughts.

**Comment by thisisloze** [comment]
How is this a design decision? What on earth were you thinking. This should not be the case for exchanges that offer candles!? We need to sync up with the exchange we are trading with as much as possible to minimize any error or.drift. I believe you decision was good at the time being (7 years ago) but now it's broken. If a exchange offers candles we should use them. Otherwise we should build

**Comment by thisisloze** [comment]
Also you keep saying illiquid markets. This is happening on pairs. BTCUSDT for one.

**Comment by askmike** [comment]
@thisisloze OP talks about XLM/ETH and minutes of no trades happening on this market. Please don't hijack other's people issues. I address you concerns here:https://github.com/askmike/gekko/issues/2524

**Comment by thisisloze** [comment]
I'm pretty sure this issue is related to candlebatcher. It's happening on
every pair Mike. Stop being like this lol!!

**Comment by askmike** [comment]
Please read this issue again, and after that read my response in #2524.
