### ISSUE TITLE
tradeErrored instead of tradeCompleted after Filled Order on Binance

### ISSUE THREAD

**Issue by cstegmann** [askmike/gekko#2465]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Running Gekko on the hotfix/binance-insufficient-funds in pm2 on the XLM/ETH pair.
EDIT: Also noticed that advice to go long afterwards was ignored because Gekko thought it was still in the process of selling. Then my strategy just assumed we were long.

**Expected result** (what you hoped would happen)
I expected a tradeCompleted event with a summary of the details of the trade.

**Actual result** (unexpected outcome)
After a trade was filled Gekko returned a tradeErrored event.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

```
2018-08-21 00:17:02 (DEBUG):
      Current market: bull
      Percent change predicted: -1.2390378175412227
      Current price: 0.00079735
      Last buy price: 0.00076684
      Current position: long
2018-08-21 00:17:02 (INFO):     Trader Received advice to go short. Selling  XLM
2018-08-21 00:17:02 (DEBUG):    Creating order to sell <my amount censored> XLM
2018-08-21 00:17:09 (DEBUG):    [ORDER] statusChange: SUBMITTED
2018-08-21 00:17:10 (DEBUG):    [ORDER] statusChange: OPEN
2018-08-21 00:17:11 (DEBUG):    Requested XLM/ETH trade data from Binance ...
2018-08-21 00:17:12 (DEBUG):    [ORDER] statusChange: FILLED
2018-08-21 00:17:12 (DEBUG):    Processing 4 new trades. From 2018-08-20 22:17:08 UTC to 2018-08-20 22:17:11 UTC. (a few seconds)
2018-08-21 00:17:21 (DEBUG):    Requested XLM/ETH trade data from Binance ...
2018-08-21 00:17:22 (DEBUG):    No new trades.
2018-08-21 00:17:31 (DEBUG):    Requested XLM/ETH trade data from Binance ...
2018-08-21 00:17:32 (DEBUG):    Processing 7 new trades. From 2018-08-20 22:17:22 UTC to 2018-08-20 22:17:23 UTC. (a few seconds)
2018-08-21 00:17:41 (DEBUG):    Requested XLM/ETH trade data from Binance ...
2018-08-21 00:17:42 (DEBUG):    Processing 6 new trades. From 2018-08-20 22:17:35 UTC to 2018-08-20 22:17:41 UTC. (a few seconds)
2018-08-21 00:17:51 (DEBUG):    Requested XLM/ETH trade data from Binance ...
2018-08-21 00:17:52 (DEBUG):    Processing 4 new trades. From 2018-08-20 22:17:45 UTC to 2018-08-20 22:17:49 UTC. (a few seconds)
2018-08-21 00:18:01 (DEBUG):    Requested XLM/ETH trade data from Binance ...
2018-08-21 00:18:02 (DEBUG):    Processing 3 new trades. From 2018-08-20 22:18:00 UTC to 2018-08-20 22:18:01 UTC. (a few seconds)
2018-08-21 00:18:02 (DEBUG):                                    [EVENT tradeErrored]
 { id: 'trade-13',
  adviceId: 'advice-13',
  date: moment("2018-08-21T00:17:14.221"),
  reason: 'Trades not found' }
2018-08-21 00:18:11 (DEBUG):    Requested XLM/ETH trade data from Binance ...
```

EDIT: Another log
```
0|XLM      |       Current market: bull
0|XLM      |       Percent change predicted: 0.7136731348248809
0|XLM      |       Current price: 0.0007862
0|XLM      |       Last buy price: 0.00076684
0|XLM      |       Current position: short
0|XLM      | 2018-08-21 01:07:12 (INFO):	Received advice to buy however Gekko is already in the process to sell
0|XLM      | 2018-08-21 01:07:12 (INFO):	Canceling sell order first
```

**Comment by askmike** [comment]
> Also noticed that advice to go long afterwards was ignored because Gekko thought it was still in the process of selling. Then my strategy just assumed we were long.

It wasn't ignored. Gekko wanted to cancel the sell first, after that was done it should have restarted the buy process. (cancelling and resyncing all state does take a few seconds). Did this not happen?

----

Your main issue:

> After a trade was filled Gekko returned a tradeErrored event.

The error came from createSummary function: The tradeCompleted event contains information regarding the trade (such as avg. execution price, effective price, fees, etc) which is fetched using createSummary. However that function errored. So while you right in that the trade was completed, the tradeCompleted event couldn't be fully created (with all properties) since Gekko was unable to retrieve all trade information from Binance. The error you see specified in the reason comes from here:

https://github.com/askmike/gekko/blob/172caf8d5847660596d0f4b3c869a20c370b1d6e/exchange/wrappers/binance.js#L348-L411

Gekko tried to get information on the trades generated by an order ID, which failed for some reason. Maybe we should try to fix that so you won't have this problem anymore.

Could you tell me a bit more:

- Are you doing anything else on that binance account (on any other market, etc)? Either with Gekko or some other trader?

**Comment by cstegmann** [comment]
> It wasn't ignored. Gekko wanted to cancel the sell first, after that was done it should have restarted the buy process. (cancelling and resyncing all state does take a few seconds). Did this not happen?

Nope, that didn't happen. It just went on and my strategy assumed I was long.

> Are you doing anything else on that binance account (on any other market, etc)? Either with Gekko or some other trader?

Yes, I have two other Gekko bots running on that same account using USDT and BTC as currency pairs.

**Comment by askmike** [comment]
> Yes, I have two other Gekko bots running on that same account using USDT and BTC as currency pairs.

Did they do heavy trading a the same time?

> Nope, that didn't happen. It just went on and my strategy assumed I was long.

I'm going to make a debug branch with a ton of logging, there clearly is not enough logging in gekko broker.

**Comment by cstegmann** [comment]
> Did they do heavy trading a the same time?

Not at the same time no. 
One bot trade before this error-bot: advice at 00:12:09, Filled at 00:13:29 and was done (tradeCompleted event) at 00:14:09.
The third bot got advice at 00:19:02, Filled at 00:21:08 and tradeCompleted at 00:22:12 .

So while it was around the 00:17:02 to 00:18:02 timeframe of the error-bot it wasn't at the same time.

**Comment by askmike** [comment]
It's still very strange that you are experiencing this. I have been trading successfully on binance in the last few days (almost hourly).

Unfortunately I still don't have enough debug information to figure out why this is plaguing you. Would you mind following these instructions? #2473

**Comment by cstegmann** [comment]
@askmike Ok, done.

**Comment by rkingy** [comment]
Is this the same issue as #2518 ?

**Comment by cstegmann** [comment]
@rkingy Could be, I'll update my bots in a bit.

**Comment by geeks121** [comment]
same issue here #2561

**Comment by askmike** [comment]
anyone following this: I have been working on getting rid of this problem in a different, see #2518 for details. In short: Please run the develop branch of Gekko and report all output related to either  "No trades found" error or a message like Binance doesnt know this order, retrying up to 10 times.. (which is the new updated handling) inside #2518.
