### ISSUE TITLE
Backtest Result Incorrect

### ISSUE THREAD

**Issue by georgezouq** [askmike/gekko#2466]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ - ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)

Backtest with my neural net strategy

**Expected result** (what you hoped would happen)

Result profit should be 9.21%

**Actual result** (unexpected outcome)

Actual result the same like market profit -28.43%. But my strategy only trade one time and get 9.21% profit.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

It's a neural net strategy

<img width="1672" alt="2018-08-21 5 46 56" src="https://user-images.githubusercontent.com/5990860/44394679-64bca080-a56a-11e8-9a19-fea6a66369fc.png">

**Comment by cstegmann** [comment]
@georgezouq You do see that you started with 10546.73 and ended with 7547.32 . Also your loss isn't the exact same as the Market Profit.

This probably happened because you started off with the asset being worth ~10500 and then it declined in relation to the currency.

**Comment by askmike** [comment]
Yes exactly! The paper trader started out with an amount of bitcoin, of which the value went down. If you don't want this to happen specify asset as 0 and currency as a number in the paper trader.
