### ISSUE TITLE
Gekko does not support tulips' standard deviation

### ISSUE THREAD

**Issue by shotty11** [askmike/gekko#2469]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)

I can't find the tulip standard deviation indicator in Gekko's tulind.js, although according to the tulip site (https://tulipindicators.org/stddev) it's one of the indicators. Am I missing something, or is tulind.js missing the indicator? Thanks for your help!

**Expected result** (what you hoped would happen)

**Actual result** (unexpected outcome)

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
Nice find, Gekko has a manual list of indicators from tulip, with information on how to run them (what kind of data to pass, not just your parameters but also market data). Here is the list:

https://github.com/askmike/gekko/blob/develop/core/tulind.js

Currently stddev is missing! Very open to PRs for this. But if not I'll try to get around it asap.
