### ISSUE TITLE
more digits on entry and exit balance

### ISSUE THREAD

**Issue by relbel1980** [askmike/gekko#2472]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ ] bug report
[x] question about the decisions made in the repository

**Action taken** (what you did)
Search for the right file

**Expected result** (what you hoped would happen)
Entry and exit balance on roundtrips to have more digits, i am not that rich :)

**Actual result** (unexpected outcome)
More digits

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc) I mean the roundtrips displayed on the web page live gekkos

**Comment by askmike** [comment]
This is all rounded inside the frontend, you can manually edit this:

https://github.com/askmike/gekko/blob/e12eea0279b2c16b2d3e308c09d77e7b24b2d95e/web/vue/src/components/backtester/result/roundtripTable.vue#L58

But note that after you do you need to recompile the frontend. See here: https://gekko.wizb.it/docs/internals/gekko_ui.html#Compiling-the-Gekko-UI-frontend

I am closing this to keep the bug tracker a bit tidy, but in the next UI I'll make sure this will be configurable.
