### ISSUE TITLE
 got start UI error message

### ISSUE THREAD

**Issue by w1t** [askmike/gekko#2474]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[X] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)

followed the installation instruction on https://gekko.wizb.it/docs/installation/installing_gekko.html 

**Expected result** (what you hoped would happen)
node gekko --ui 
expect to see the UI

**Actual result** (unexpected outcome)

module.js:549
    throw err;
    ^

Error: Cannot find module '/Users/ray/gekko/exchange/gekko'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by hiyan** [comment]
You need to run `node gekko --ui` in your gekko directory... eg: `/Users/ray/gekko/`

**Comment by askmike** [comment]
yep!
