### ISSUE TITLE
Gekko crashed

### ISSUE THREAD

**Issue by xbromy** [askmike/gekko#2476]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
running a live gekko since a few days. 
It's the development version pushed for #2442

**Expected result** (what you hoped would happen)
have it running

**Actual result** (unexpected outcome)
Aug 23 20:43:43 Test02 gekko[2002]:   <-- POST /api/getCandles
Aug 23 20:43:43 Test02 gekko[2002]:   --> POST /api/getCandles 200 302ms 26.1kb
Aug 23 20:43:44 Test02 gekko[2002]:   <-- GET /api/apiKeys
Aug 23 20:43:44 Test02 gekko[2002]:   --> GET /api/apiKeys 200 1ms 11b
Aug 23 20:43:44 Test02 gekko[2002]:   <-- GET /api/exchanges
Aug 23 20:43:44 Test02 gekko[2002]:   --> GET /api/exchanges 200 4ms 87.76kb
Aug 23 20:43:44 Test02 gekko[2002]:   <-- GET /api/imports
Aug 23 20:43:44 Test02 gekko[2002]:   --> GET /api/imports 200 1ms 2b
Aug 23 20:43:44 Test02 gekko[2002]:   <-- GET /api/gekkos
Aug 23 20:43:44 Test02 gekko[2002]:   --> GET /api/gekkos 200 1ms 9.74kb
Aug 23 20:44:41 Test02 gekko[2002]: /home/username/gekko/node_modules/ws/lib/Web                                                                                                                                                             Socket.js:313
Aug 23 20:44:41 Test02 gekko[2002]:       throw new Error('not opened');
Aug 23 20:44:41 Test02 gekko[2002]:       ^
Aug 23 20:44:41 Test02 gekko[2002]: Error: not opened
Aug 23 20:44:41 Test02 gekko[2002]:     at WebSocket.ping (/home/username/gekko/                                                                                                                                                             node_modules/ws/lib/WebSocket.js:313:13)
Aug 23 20:44:41 Test02 gekko[2002]:     at wss.clients.forEach.ws (/home/username/gekko/web/server.js:43:8)
Aug 23 20:44:41 Test02 gekko[2002]:     at Set.forEach (<anonymous>)
Aug 23 20:44:41 Test02 gekko[2002]:     at Timeout.setInterval [as _onTimeout] (                                                                                                                                                             /home/username/gekko/web/server.js:36:15)
Aug 23 20:44:41 Test02 gekko[2002]:     at ontimeout (timers.js:427:11)
Aug 23 20:44:41 Test02 gekko[2002]:     at tryOnTimeout (timers.js:289:5)
Aug 23 20:44:41 Test02 gekko[2002]:     at listOnTimeout (timers.js:252:5)
Aug 23 20:44:41 Test02 gekko[2002]:     at Timer.processTimers (timers.js:212:10                                                                                                                                                             )
Aug 23 20:44:41 Test02 gekko[2002]: disconnect
Aug 23 20:44:41 Test02 gekko[2002]: disconnect
Aug 23 20:44:41 Test02 systemd[1]: gekko.service: Main process exited, code=exit                                                                                                                                                             ed, status=1/FAILURE
Aug 23 20:44:41 Test02 systemd[1]: gekko.service: Unit entered failed state.
Aug 23 20:44:41 Test02 systemd[1]: gekko.service: Failed with result 'exit-code'                                                                                                                                                             .
Aug 23 20:44:51 Test02 systemd[1]: gekko.service: Service hold-off time over, sc                                                                                                                                                             heduling restart.
Aug 23 20:44:51 Test02 systemd[1]: Stopped gekko.service.
Aug 23 20:44:51 Test02 systemd[1]: Started gekko.service.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
After following the stack traces I see that this is caused by Gekko using an outdated version of the `ws` dependency..
