### ISSUE TITLE
Unexpected ')' when running custom strat in cli

### ISSUE THREAD

**Issue by moo5e** [askmike/gekko#2478]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ X] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)

Edited my custom strategy and attempted to backtest it in cli

**Expected result** (what you hoped would happen)

I expected the strat to run just like it did a few minutes ago

**Actual result** (unexpected outcome)

Cli printed an error 'SyntaxError: Unexpected token )'. It says the extra bracket is under the last line, so one line under 'module.exports = strat'. Ive looked through my code and couldnt find an extra ). The code was running fine and a small edit triggered this error. I undid my small edit and still the same error.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

More error info:

});
 ^
SyntaxError: Unexpected token )
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Actor.setupStrategy'

**Comment by askmike** [comment]
So this error means there is a bug in the code of your strategy. If you want us to help you'd need to post all the code of the strategy so we can figure it out. I am closing this (but feel free to comment with all the code) because this is the bug tracker for the whole Gekko project.
