### ISSUE TITLE
Cant run GekkoBacktestTOOl

### ISSUE THREAD

**Issue by Kashkun** [askmike/gekko#2479]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did) 
perl backtest.pl

**Expected result** (what you hoped would happen)
Running backtest

**Actual result** (unexpected outcome)
Error: Cannot find module '/home/gdax/gekko/Gekko-BacktestTool/gekko'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
ETH-LINK Backtest is failed.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
That error & file is not from Gekko. It's probably a third party tool that works with Gekko? Please contact the author of that tool.
