### ISSUE TITLE
Kraken: order was not fully executed

### ISSUE THREAD

**Issue by danielm001** [askmike/gekko#2486]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[X] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
start gekko v0.6.5 trade bot (cli)

**Expected result** (what you hoped would happen)
Order (long advice) would be fully executed

**Actual result** (unexpected outcome)
(1) The order was only partial executed and moved for 8 minutes. After that nothing happened anymore. 

(2) In the morning i restarted gekko, because i thought gekko would fill the rest of the order but he didn't: "NOT buying, already exposed" Is this behavior intended? 

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
please see the attached logs.

[kraken_usd_xlm_partial_fill.log](https://github.com/askmike/gekko/files/2329532/kraken_usd_xlm_partial_fill.log)

**Comment by askmike** [comment]
There have been some issues with kraken integration. Working on this asap. 

See #2412.

**Comment by danielm001** [comment]
Dear @askmike, I have some more logs of the Kraken USD/XLM bot, maybe they help.   
- First order wasn't executed at all
- Second order (after restart) was only partially executed

Just tell me, if you have enough logs or if i should switch to a debug branch. 
The Kraken EUR/XRP is working fine so far. Both bots are still running on Gekko v0.6.5

[kraken_usd_xlm_20180903.log](https://github.com/askmike/gekko/files/2346486/kraken_usd_xlm_20180903.log)

**Comment by askmike** [comment]
I am working on Kraken stability, keep an eye out on #2502.
