### ISSUE TITLE
Gekko Node  crashing with Live trader on Binance

### ISSUE THREAD

**Issue by exes74** [askmike/gekko#2487]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Hi,

I launched a traderbot on Binance BTC/BNB (based on neuralnet_zschro), but the bot crashes regularly after 2-3 trades and thus crash the Gekko Node as well (it takes usually less than 4h before the bot crashed once it went live - after learning period)
I've experienced this crash 2-3 times.
No problems with the paper trader, I guess something is wrong on the Exchange <=> Node connection management.

**Expected result** (what you hoped would happen)

No crash :)

**Actual result** (unexpected outcome)

The whole Gekko Node crashes.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Here is the stack that appears on Gekko.

events.js:167
throw er; // Unhandled 'error' event
^

Error: read ECONNRESET
at TCP.onread (net.js:660:25)
Emitted 'error' event at:
at WebSocket.finalize (/home/yca/gekko/gekko/node_modules/ws/lib/WebSocket.js:182:41)
at Socket.emit (events.js:182:13)
at emitErrorNT (internal/streams/destroy.js:82:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
at process._tickCallback (internal/process/next_tick.js:63:19)
disconnect
disconnect

Finally, a great thanks for all the work, even if the bot is not fully working all the time, it's a great way to deepen trading knowledge!

**Comment by askmike** [comment]
What version of gekko did you run? This one should have been fixed roughly a week ago. Please make sure you have tried the latest version :)

**Comment by exes74** [comment]
Hi, 

Thanks for the answer, Indeed I'm using Gekko v0.6.5 and Gekko UI v0.2.3.
I'll update to 0.6.6 asap and see if I get the same behavior.

Thanks again for the good work :+1:

**Comment by askmike** [comment]
I'm assuming this is fixed, if it isn't just recomment and we'll reopen :)

**Comment by bundarachada** [comment]
I'm having this same problem in Gekko v0.6.7 and Gekko UI v0.2.3. It happened a few times during that week.

```
uncaughtException {Error: socket hang up
     at TLSSocket.onHangUp (_tls_wrap.js: 1148:19)
     at Object.onceWrapper (events.js: 313:30)
     at emitNone (events.js: 111: 20)
     at TLSSocket.emit (events.js: 208: 7)
     at endReadableNT (_stream_readable.js: 1064: 12)
     at _combinedTickCallback (internal / process / next_tick.js: 139: 11)
     at process._tickCallback (internal / process / next_tick.js: 181: 9)
   code: 'ECONNRESET',
   path: null,
   host: 'api.binance.com',
   port: 443,
   localAddress: undefined}
RECEIVED ERROR IN GEKKO INSTANCE 2018-11-24-22-45-tradebot-54462357997822064
{code: 'ECONNRESET',
   path: null,
   host: 'api.binance.com',
   port: 443}
```
