### ISSUE TITLE
v0.6.6 and UI v0.2.3.: No markets or pairs to select in GUI importer

### ISSUE THREAD

**Issue by shimanotaka** [askmike/gekko#2491]
**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Tried to import more recent data

**Expected result** (what you hoped would happen)
Being able to select exchange and trading pair.

**Actual result** (unexpected outcome)
No drop-down boxes for exchanges and currencies visible in GUI.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
Windows 10, Chrome 68.0.3440.106 64-bit.

![screenshot 2018-09-01 13 06 37](https://user-images.githubusercontent.com/5903967/44944984-1f5d6600-ade9-11e8-8272-1f9f4cee5bdc.png)

**Comment by H256** [comment]
I had the same problem. It's because of missing dependencies in the `<your-gekko-location>/exchange` - folder.

Just browse to this folder and run `npm install` from a console-window. After that restart gekko.

**Comment by askmike** [comment]
yep! You can find this in the installation documentation: https://gekko.wizb.it/docs/installation/installing_gekko.html
