### ISSUE TITLE
https://registry.npmjs.org/windows-build-tools failed, reason: Hostname/IP doesn't match certificate's altnames:

### ISSUE THREAD

**Issue by HasanOZER1** [askmike/gekko#2492]
Hi,
when I was try to execute command;
npm install --global --production windows-build-tools

I'm getting below error , please help..

C:\Hasan_OZER\gekko-develop>npm install --global --production windows-build-tools
npm ERR! request to https://registry.npmjs.org/windows-build-tools failed, reason: Hostname/IP doesn't match certificate's altnames: "Host: registry.npmjs.org. is not in the cert's altnames: DNS:a.sni.fastly.net, DNS:a.sni.global-ssl.fastly.net"

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Özgür ÖZER\AppData\Roaming\npm-cache\_logs\2018-09-01T10_34_35_188Z-debug.log

**Comment by kroitor** [comment]
This is an issue with npm, which should self-resolve as soon as your provider's DNS cache is updated (usually less than 24 hours): https://status.npmjs.org/incidents/v22ffls5cd6h

**Comment by askmike** [comment]
yep! According to @kroitor's link it should be fixed now and you shouldn't experience this any longer.
