### ISSUE TITLE
Cannot add API key of other exchange than bitfinex

### ISSUE THREAD

**Issue by yotys** [askmike/gekko#2495]
**I'm submitting a ...**
[ x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Tried to add an API key and opened the Exchange dropdown.

**Expected result** (what you hoped would happen)
All [supported exchanges](https://gekko.wizb.it/docs/introduction/supported_exchanges.html) (i. e. Coinfalcon) are selectable.

**Actual result** (unexpected outcome)
Only bitfinex is displayed.

Did I miss some information in the documentation or is this a bug?

Using v0.6.6 on Windows 10.

**Comment by yotys** [comment]
Checked the install guide again and found the missing step (Install Gekko Broker's dependencies). Sorry for the spam.

**Comment by tonynguyen6221** [comment]
hey yotys im stuck in the same thing how do i add binance when they drop down menu only shows  bitfinex? in terminal i cant get gekko brokers dependencies to download

**Comment by yotys** [comment]
> hey yotys im stuck in the same thing how do i add binance when they drop down menu only shows bitfinex? in terminal i cant get gekko brokers dependencies to download

Hey, sorry for the late reply.

The point i missed first was the following:

> **Install Gekko Broker's dependencies:**
> 
> cd exchange
> npm install --only=production

This command installs the support for the additional exchanges.

I did not need to download any additional packages. Just used the latest release from [here](https://github.com/askmike/gekko/releases).

**Comment by snowman81** [comment]
hi, everyone.
For me it was the same problem, though I tried to install Broker dependencies.
It gave me a bunch of errors during the install.
Later I realized, that the whole installation of Gekko is broken.
I deleted all the directory, and reinstalled, with using **sudo** at every step.
Then it worked almost flawlessly, with just one minor error, that probably does not matter.
Please update the documentation, as for the newbies it can be a difficulty, same as for me.
Also, when you edit the config files, or making any copy/delete operations on the files, and if you do that with Midnight Commander 
(`sudo apt-get install mc`),
you need to start it with **sudo**, for it to perform as needed.
`sudo mc`
P.S.: I use Linux Mint 19.1 Mate on my old secondary PC.

**Comment by soot0-JoshR** [comment]
I've tried installing gekko's dependencies several times and bitfinex is still the only exchange I can see in where the list should be. I would simply use bitfinex but it doesn't even actually let me add an API key for the exchange. I have the latest version of gekko (Gekko v0.6.8 at this time) and I have already tried reinstalling the entire thing.
I run 'npm install --only=production' in the exchange directory and I get the same result every time.
What am I missing?

**Comment by GeorgiDimitrov87** [comment]
've tried installing gekko's dependencies several times and bitfinex is still the only exchange I can see in where the list should be. I would simply use bitfinex but it doesn't even actually let me add an API key for the exchange. I have the latest version of gekko (Gekko v0.6.8 at this time) and I have already tried reinstalling the entire thing.
I run 'npm install --only=production' in the exchange directory and I get the same result every time.
What am I missing?

**Comment by GeorgiDimitrov87** [comment]
updated npm and node and worked
