### ISSUE TITLE
errno : 11 - Code : SQLITE_COURRPT => Windows 10 Bash

### ISSUE THREAD

**Issue by LoayGhreep** [askmike/gekko#2497]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ ] bug report
[ ] question about the decisions made in the repository
[*] issue

**Action taken** (what you did)
'node gekko --ui' Then I Started a new binance trading bot

**Expected result** (what you hoped would happen)
trading bot would work

**Actual result** (unexpected outcome)
* In The Browser ( The Watcher )
![image](https://user-images.githubusercontent.com/42842021/44988981-b3b3fe00-af8c-11e8-937f-c2dcccf58037.png)
Then i get
![image](https://user-images.githubusercontent.com/42842021/44989119-2624de00-af8d-11e8-9cbf-6bbe38304bfa.png)
* In Terminal
![image](https://user-images.githubusercontent.com/42842021/44989045-e6f68d00-af8c-11e8-9b33-2e683990fdda.png)

**Other information**
* I`m Running on win 10 bash
* Tried https://github.com/askmike/gekko/issues/1086 But Didn't Work
* Tried http://gekkowarez.com/running-gekko-sqlite-in-windows-10-bash/ But Didn't Work

So ... help me :))

**Comment by LoayGhreep** [comment]
* Update : It Happens Only On Binance Only On USDT/EOS !!
Otherwise It Works Well With The rest
I Really Do not know how or why
Now i will try to re install all gekko again and tell if problem fixed

**Comment by LoayGhreep** [comment]
* Problem Solved 
* Simple Solution :
1 - https://github.com/askmike/gekko/issues/1086
2 - Reinstalling Gekko
* Advanced Solution
1 - https://github.com/askmike/gekko/issues/1086
2 - Remove All Imports Or Market Wachers Files Then Re-import
* Reason Was
My Windows Was Forced To Restart And Update While Gekko Is Running On USDT/EOS Trading
So It Refused To Start this Specific Market Watcher ... Only The Market Watcher Was The Problem
anyway ... Hope It Help any similar issue 😄

**Comment by LoayGhreep** [comment]
Hey Mr Mike
yesterday i was running bot and it worked well
today i tried to run tradepapers ( 15 ones )
it showed me the same error
the market watcher is the problem
also when i re installed gekko
every single list was empty ( strategy , coins , platfroms )

**Comment by askmike** [comment]
Woa that doesn't look that good. I am not familiar with Windows and how it can corrupt sqlite databases..

Would it be a problem to delete all your market data (delete everything inside gekko/history) and start fresh?

**Comment by LoayGhreep** [comment]
aha Mr. mike it was solved by deleting .db files into gekko/history
now i've small question ... i'm not familiar with linux as well
if i want to run this on linux what distribution would you suggest and browser to use UI ?

**Comment by askmike** [comment]
> if i want to run this on linux what distribution would you suggest and browser to use UI ?

Ubuntu is very user friendly I think, as for browser either chrome or firefox (make sure to use latest version).
