### ISSUE TITLE
UI "Live Gekkos" > "Market" section is empty

### ISSUE THREAD

**Issue by pangoyal** [askmike/gekko#2498]
**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
updated from v.0.6.5 to v.0.6.6

**Expected result** (what you hoped would happen)
UI should work properly

**Actual result** (unexpected outcome)
The "Live Gekkos" tab is rendered incorrectly having the "Market" section blanked out (below)
<img width="461" alt="screen shot 2018-09-03 at 16 22 31" src="https://user-images.githubusercontent.com/12811669/44994408-6b014280-af96-11e8-8df7-5caaea7b7001.png">

upon refreshing, it renders empty dropdowns like this (below)
<img width="453" alt="screen shot 2018-09-03 at 16 22 41" src="https://user-images.githubusercontent.com/12811669/44994432-8cfac500-af96-11e8-9f9d-ddcf36cfe8bb.png">

**Comment by pangoyal** [comment]
browser debug console displays following error:

vue.runtime.esm.js:1737 TypeError: Cannot read property 'markets' of undefined
    at a.currencies (marketpicker.vue:74)
    at un.Kw5r.un.get (vue.runtime.esm.js:3138)
    at un.Kw5r.un.evaluate (vue.runtime.esm.js:3245)
    at a.currencies (vue.runtime.esm.js:3503)
    at a.n (marketpicker.vue?d701:1)
    at a.t._render (vue.runtime.esm.js:4540)
    at a.r (vue.runtime.esm.js:2784)
    at un.Kw5r.un.get (vue.runtime.esm.js:3138)
    at new un (vue.runtime.esm.js:3127)
    at Ne (vue.runtime.esm.js:2791)

**Comment by askmike** [comment]
You haven't installed gekko broker dependencies, see here: https://gekko.wizb.it/docs/installation/installing_gekko.html#Installing-Gekko-39-s-dependencies

**Comment by pangoyal** [comment]
yeah I guess. I did npm install in exchange directory and it works fine. Sorry, my bad.

**Comment by mbartyzel** [comment]
For me still doesn't work even if I install npm deps

**Comment by Ksdbdex1998** [comment]
same here it didnt work at all for me
