### ISSUE TITLE
Version in "./docker-compose.yml" is unsupported

### ISSUE THREAD

**Issue by claytondukes** [askmike/gekko#2499]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[X] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)

Followed the [install guide](https://gekko.wizb.it/docs/installation/installing_gekko_using_docker.html)

- Checkout the repo, run `docker-compose build`

**Expected result** (what you hoped would happen)

build should...build.

**Actual result** (unexpected outcome)

I get the following error:

```
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

I'm running `Docker version 18.06.1-ce, build e68fc7a`

**Comment by claytondukes** [comment]
I'll leave this here in case anyone else has the same problem.

The issue is that Ubuntu had an old version of docker-compose in the apt repositories.

To fix that, remove docker-compose (`apt remove docker-compose`) and [get the one from their website](https://docs.docker.com/compose/install/#install-compose).

**Comment by askmike** [comment]
:+1:
