### ISSUE TITLE
How to add new exchange

### ISSUE THREAD

**Issue by SloRunner** [askmike/gekko#2507]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ ] bug report
[x] question about the decisions made in the repository

Is there a way to add new exchange to it? I could do PR, but i would need some pointers on where to start adding the exchange

Also [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) is not avaliable anymore

**Comment by askmike** [comment]
This doc contains all info you need: 

https://gekko.wizb.it/docs/extending/add_an_exchange.html

If you run into anything feel free to comment here or on the forum.

> Also getting help page is not avaliable anymore

The page has an underscore, this is the correct link: https://gekko.wizb.it/docs/introduction/getting_help.html
