### ISSUE TITLE
Add an new exchange

### ISSUE THREAD

**Issue by kyokokiss** [askmike/gekko#2510]
Hi, I want to add a new exchange by the link you provided on the contributing guidelines, but the link is invalid, so I open an issue to apply for it. 

Do you have interest in adding OceanONE —— A decentralized Exchange based on Mixin Network, guaranteed ‘0’ transfer fee & immediate transfer speed, it has the following characters:

High Security
Exchange code is open-sourced; User assets are stored in their own wallets
High Transparency
All transaction records are publicly available on the Mixin Network;
Transparent and checkable
Trading Experience - High-speed & Low-cost
Immediate order placement; No charges on Buying, Selling and Cancelling
Full set of crypto-currencies
Supports more than 11 main chains with more than 41,000 crypto-currencies
including XIN, BTC, Omni USDT, etc.
OceanONE  API Open-sourced 
Developers friendly, meeting different trading needs 
https://github.com/MixinNetwork/ocean.one

**Comment by askmike** [comment]
Hello,

I just saw that these links are indeed outdated. I have fixed them now. The correct document you are looking for is here: https://gekko.wizb.it/docs/extending/add_an_exchange.html

Unfortunately I am too busy for this right now. I will keep this open. Any programmer can do this and propose a PR to add an exchange to Gekko :)
