### ISSUE TITLE
Adding Robinhood to exchanges

### ISSUE THREAD

**Issue by t-16x** [askmike/gekko#2516]
It is the only exchange that I can find that doesn’t charge fees so the calculation would be much easier. There isn’t an official public api released (they posted on their forum saying they’re working on it) but I found that someone created their own in Python, so it’s completely possible. https://www.quantopian.com/posts/trading-with-the-unofficial-robinhood-api-w-slash-code-examples

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hnguyen2k** [comment]
This would be a great addition to Gekko. Someone also created a node project working with robinhood:
  
https://github.com/aurbano/robinhood-node

**Comment by askmike** [comment]
great idea! I'm a bit busy at the moment, but anyone else can pick this up, here are all the required docs:

https://gekko.wizb.it/docs/extending/add_an_exchange.html

**Comment by jakobzhao** [comment]
it would be a great function to Gekko. Hope it would be developed
