### ISSUE TITLE
Gekko stops processing data randomly after short time (bitmex)

### ISSUE THREAD

**Issue by LooOOooM** [askmike/gekko#2519]
**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
I am tring to get the new exchange bitmex running. Collection live trating results data.

**Expected result** (what you hoped would happen)
Gekko should fetch trading data and orocess then

**Actual result** (unexpected outcome)
In is hard to discripe what happens. All works well to a thirten point.
- Gekko looks for history data I got already within the DB, and finds it.
- Gekko get the history data with the live data in sync
- Gekko fetch and processs live data: 
   "Processing X new trades. From time_A UTC to time_B UTC. (a few seconds)" 
... so data is usable in strat 

This all works for a random time between few minutes until maybe one day.
Then the fequenty message "Processing X new trades. From time_A UTC to time_B UTC. (a few seconds)"
Will finnaly not any more appear, so Gekko is not processing any data anymore.

2018-09-10 22:51:21 (DEBUG):    Processing 6 new trades. From 2018-09-10 20:51:19 UTC to 2018-09-10 
2018-09-10T20:51:20.501Z
------------------------------------------------------------

2018-09-10 22:51:23 (DEBUG):    Processing 75 new trades. From 2018-09-10 20:51:20 UTC to 2018-09-10 
2018-09-10T20:51:20.701Z
------------------------------------------------------------

2018-09-10T20:51:20.701Z
------------------------------------------------------------

2018-09-10T20:51:20.701Z
------------------------------------------------------------

2018-09-10T20:51:20.701Z
`
Please also note that the Time stamp seems to hang, repeating endless.

This looks to me that a internal component of gekko crashed, but it is very hard to say why Gekko stopped processing data as ther is no error at all popping up.

I am using https://github.com/BitMEX/api-connectors for the connection. 
The connections seem to be fine, as I see that data is still arriving through the connection as responce.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
This Behalvier apears on both versions v0.5.11 and the latest development version 0.6.6, while the old version 0.5.11 appears to last far longer then the 0.6.6 before no trades gets processed anymore. With the new version I cannot come sometimes even not in sync with realtime before gekko refuse to process data.

Please help be to better debug this issue as I do not now where I should look further to identify this bug. It would help very much if you could point me to to the internal meachanism which goes nuts.

**Comment by askmike** [comment]
Since gekko doesn't come with any bitmex code, can you share the code you are trying? You shouldn't have any issues if you closely follow this spec: https://gekko.wizb.it/docs/extending/add_an_exchange.html

If Gekko seems to freeze the most likely situation I can think if is the bitmex wrapper code not firing a callback passed.

**Comment by LooOOooM** [comment]
I am on holydays for 14 days. After I came back I will post further. Thanks for your answer and your guess. I was seeing that you also tried bitmex implimentation as I found a bugreport from you https://github.com/BitMEX/api-connectors/issues/103
The Problem I appent ther eI already solved myself. What happened to the version you tried to implement?
For sure a version from the gekkoinventor would be much better then my version anyway.

**Comment by askmike** [comment]
@LooOOooM I am actively trading on bitmex, but not with Gekko. Note that Gekko only supports spot because it's a lot easier to trade on. Read this for more details: https://forum.gekko.wizb.it/thread-1516-post-57452.html#pid57452

If you hook up bitmex to Gekko you can trade, but all profit reports and calculations will be incorrect.

**Comment by askmike** [comment]
Closing this. Gekko does not support bitmex.
