### ISSUE TITLE
Error message does not show the line information anymore?

### ISSUE THREAD

**Issue by jasurakk** [askmike/gekko#2520]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Tried to run my own bot, and I got just this on error on the command prompt:
------------------------------------
  xxx POST /api/backtest 500 623ms -

  Error: non-error thrown: [object Object]
      at Object.onerror (C:\Gekko\node_modules\koa\lib\context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
------------------------------------

**Expected result** (what you hoped would happen)
Shouldn't there be a more specific information about the error and the cause of it? If I remember right, previously error messages told exactly the filename and the faulty line in it, but not on 0.6.6 anymore??

**Actual result** (unexpected outcome)
Cannot locate the line which caused the error.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by zartrade** [comment]
Make sure you dont require talib or tulip node libraries for your strategy. That error is quite generic indeed but from past experience it seems to be related to not having require libraries installed for node and your strategy/indicators.

**Comment by jasurakk** [comment]
Thanks but no, I don't use talib or tulip. And my method has been working previously just fine. But now, after maybe a month or so, I upgraded to the newest Gekko and started to code again, and noticed that I do not get valid error messages at all if I write dome bug on my bot??

**Comment by jasurakk** [comment]
Anyone? I still cannot get any error messages shown, which makes the development quite difficult since I don't get any clue if I make some mistake on my code..

**Comment by askmike** [comment]
Apologies for the late reply. Please see this video guide: https://www.youtube.com/watch?v=6-74ZhrG0BE

About your specific issue:

The latest version (both stable release & develop branch) should log the error, can you verify you are running the latest version? But after that: please run the strategy over the commandline, which is directly running your code in the same process. Using the UI there are a few layers in between, it should bubble through these errors.

I do want to look at it, but please provide a way to reproduce your problem. Since I currently cannot reproduce it locally.

**Comment by jasurakk** [comment]
Just to be sure, I downloaded the latest 0.6.6 version and extracted all files to my Gekko- folder. I don't know why, but something really changed; now I can't get any results for any strategy, they just keep on running with a text "Running Backtest..." on the UI, without stopping at all. I mean, even if I take some built-in example strategy such as MACD or RSI, I don't get any results for them, but I don't get any error messages anywhere either??

**Comment by askmike** [comment]
We are not having these issues, can you run them over the commandline with debug on and post logs?  Here is a guide how to if you are not aware: https://forum.gekko.wizb.it/thread-57581.html

**Comment by jasurakk** [comment]
Ok, going forward... I tried to run both MACD- and my own strategy from the command line, and they worked just fine, without any errors! :=)  And if I add some bug on the code, I'm getting a valid error message just like before.

But still, running the same backtest from UI makes the tester just halt, without any error messages shown anywhere. How could I help you to solve this problem somehow..?

**Comment by askmike** [comment]
By changing some code you can force log messages in the UI, read here how: https://github.com/askmike/gekko/issues/2451#issuecomment-413782847

**Comment by jasurakk** [comment]
Ok, now I did that and got more info on the screen. I can see that the backtester is running just fine, and my bot is doing some simulated trades. No errors anywhere. 

But, for some reason it seems that the testing is started all over again! After the testing is done first time, the line "Setting up Gekko in backtest mode" is written again, and exactly the same trades are listed on the CLI again. And the UI does not give any test report, it just comes back to a starting point with blue "Backtest"- button available.

**Comment by jasurakk** [comment]
Now I went back to 0.6.5 and backtester works just fine with it, even thru the UI. So there really might be something wrong with the backtester UI in 0.6.6?

And with 0.6.5 I don't get any valid error messages if there's a bug in my code, but maybe this was already fixed on 0.6.6.?

**Comment by askmike** [comment]
@jasurakk please provide a way for us to reproduce your problems. I am not experiencing your problems..

**Comment by jasurakk** [comment]
I would be more than happy to do that, if I just would know how?? But I'll try to dig some deeper in a few days, let's see what can I get.

**Comment by askmike** [comment]
Great thanks!
