### ISSUE TITLE
Gekko in Debug Mode in VSCode unable to import data.

### ISSUE THREAD

**Issue by bvanderdrift** [askmike/gekko#2521]
**I'm submitting a ...**
* bug report

**Action taken**
Run Gekko in debugger mode in VSCode and tried to import market data

**Expected result**
Successfully import data from `/history` folder or exchange

**Actual result**
Child process of `/core/workers/dateRangeScan` exits with exit code `12`

**Other information**
No output in console, no errors.

**Comment by askmike** [comment]
> debugger mode in VSCode

I'm not sure what this is. But Gekko is an app supposed to be run in nodejs, if VSCode doesn't run javascript in a complete nodejs environment (in a version supported by Gekko) it's not going to work.

> exits with exit code 12

Do you have debug logs?

**Comment by askmike** [comment]
Closing this since for inactivity & the fact that I don't think this is an issue. But feel free to keep commenting.
