### ISSUE TITLE
rest and websocket api

### ISSUE THREAD

**Issue by gve2000** [askmike/gekko#2523]
I am building a python application connecting to both the rest API for gekko control as well as the websocket for event updates.
Regarding the rest API, communication works well, and I also see some events coming in. 
But I noticed that either the rest API or the websocket are failing randomly if both are used at the same time (api calls are not executed and/or events are missed)

My python implementation uses the same url+port for both APIs (rest API and websocket (broadcast events). 
And as I get connected, I thought the Gekko config was ok.
From the config file, it seems only possible to define host and port for both (api section of UIconfig.js - I presume the ui section is for the webpages of the UI itself)

Is this correct or can I define different ports for the rest API and the websocket (broadcast events)

**Comment by askmike** [comment]
> From the config file, it seems only possible to define host and port for both (api section of UIconfig.js - I presume the ui section is for the webpages of the UI itself)

The API section defines where the server listens to (what port and what host). The UI section defines what the webpage listens to: most people who run Gekko in production don't expose the server directly on the internet, but instead put a webserver (like nginx) between the UI (browser) and the server, this way they can easily add authentication to the server.

It's not possible right now to access the websocket server from a different endpoint.

> But I noticed that either the rest API or the websocket are failing randomly if both are used at the same time (api calls are not executed and/or events are missed)

Strange: Everyone who uses the UI has the same setup, but does not experience these problems. The latest version of Gekko logs websocket errors, is there any strange output?

**Comment by gve2000** [comment]
Hi Mike,

thanks for this quick reply.

ok, your explanation about rest server (API section in config file) and websocket (but also webpages (?)) (UI section of the config file) seem clear to me.
I now have a config file where both servers seem to use localhost and same port (3000).  Although I don’t really understand how this can work, it does and the UI is operational.

With my python app, I want to connect to rest API (that seems to work) and also get the websocket events (I get a few events, but the socket disconnects).  My assumption is that I can’t support rest communication and websockets on the same port (maybe it is my limited network knowledge or the python lib that does not support it).    
Anyhow, I tried to get the rest api on a different port to avoid all problems.
As soon as I change the port in the gekko/web/baseUIConfig.js and gekko/web/vue/dist/UIconfig.js the webpage no longer works.

Is this config change not enough ?

Gert

**Comment by askmike** [comment]
> Anyhow, I tried to get the rest api on a different port to avoid all problems.

You can only change the port/host of BOTH the REST and WS API. You cannot change just one through the config.

> My assumption is that I can’t support rest communication and websockets on the same port (maybe it is my limited network knowledge or the python lib that does not support it).

This is not true, but I am not experienced enough with Python to know how to do this in Python. The UI (webpage) connects to the websocket and uses the same URL (port) for REST calls as well.

--------

If you really want to run the websocket API over a different port than the rest API you will need to change some Gekko code around:

https://github.com/askmike/gekko/blob/9cfb331bfd68ed888c2cddf2c72bc04084f30648/web/server.js#L10-L16

In the last line we pass the only server from Gekko (the one that runs on whatever is configured in the UIConfig) into the "websocket server", this means that both "run" on the same host = port. You can also not pass this server object in but instead create a new one buy passing a port number, see the docs of the websocket library: https://www.npmjs.com/package/ws#simple-server

So by tweaking one line you can get the behaviour you want, but it's definitely possible to connect to both websocket and the rest api over the same port.

I'm closing this as it's not an issue with Gekko. But feel free to keep commenting.

**Comment by gve2000** [comment]
Hi Mike,

1) regarding the config

you mentioned previously : 
The API section defines where the server listens to (what port and what host) : so this is rest API
The UI section defines what the website listens : so this should/could be websocket (as the websocket sends events out of gekko, I assumed it is not the rest API part)

But from your reply below, I understand that it is the rest server that also serves the websocket (same url/port)
the UI section of the config file, only defines the address on which the webpages are served.  

2) regarding rest API and websocket on the same url/port

i agree it should be possible, but I don’t really know how.  a socket is identified by its client url/port + server url/port combination.
So yes multiple connections should run concurrently as long as my outbound client port is different.  
The only thing I am sure of is that my current implementation does not work.

But just to get the context clear, I should be albe to keep a permanently open websocket active to receive events + concurrently execute rest requests. 
That would at least get the requirement for my implementation clear.

met vriendelijke groeten,

Gert

**Comment by askmike** [comment]
> The API section defines where the server listens to (what port and what host) : so this is rest API The UI section defines what the website listens : so this should/could be websocket (as the websocket sends events out of gekko, I assumed it is not the rest API part) 

No! the API section defines what both APIs (rest and ws) bind to. In other words, this determines where both APIs can be located.

The UI section defines what the webpage (**not websocket**) listens to. This because most people want to have gekko behind authentication. So they put a webserver between the two.

> But just to get the context clear, I should be albe to keep a permanently open websocket active to receive events + concurrently execute rest requests. That would at least get the requirement for my implementation clear.

That's also a requirement for the UI (the webpage), which is already happening.

So just to be sure we are on the same line:

- In your python code you can setup a websocket connection to `localhost:3000/` and receive websocket updates. In other parts of your code you can hit the rest API by hitting `localhost:3000/api/gekkos` (for example). You don't need to close the websocket, you can keep it open. The UI is already doing the exact same thing, just not in Python.
- If you have some python code that starts a webserver, you need to bind to a different port, since Gekko is using the one you have defined in the API section of your UIconfig (`localhost:3000`).
