### ISSUE TITLE
[Feacture] Init strat async

### ISSUE THREAD

**Issue by julesGoullee** [askmike/gekko#2525]
Behaviour to have async function in init method of the strategy:
if (!strat.init() instanceof Promise) keep actual
if (strat.init() instanceof Promise) wait defered

**Comment by askmike** [comment]
Great idea! I would like to go for the callback pattern, as the plugin API also supports async init (of plugins) via a callback.

The biggest issue I see is that I would like to keep backwards compatibility, so that strategies which are not async don't break (because they don't call any callback).

**Comment by askmike** [comment]
What do you think of strategies exposing some meta data, similar to the how exchange wrappers expose information on how Gekko should work with an exchange:

https://github.com/askmike/gekko/blob/9cfb331bfd68ed888c2cddf2c72bc04084f30648/exchange/wrappers/bitfinex.js#L297-L311

That way we can have strategies providing some information about them, like whether the init function is async or not.

**Comment by julesGoullee** [comment]
Yes perfect, with default values to ensure no breaking change with existing
strategy

**Comment by mark-sch** [comment]
Great discussion at the right time :-) Also for the strat.update and strat.check function it will be very useful to have either a callback function or the ability to return a Promise.

I am just wrapping the tulip and talib indicators into a native gekko indicator with async/await to use them in multi timeframe strategies where asyncIndicatorRunner is not available. Runs already pretty well, the strat.update callback is the last missing part.

Sample usage:

strat.init = function () {
   this.tulipFOSC = new TULIPSYNC({ indicator: 'fosc', length: 500, candleinput: 'close', options:[ this.Period ] });
}

strat.update = async function (candle) {
   this.tulipFOSC.result = await this.tulipFOSC.update(candle);
}

strat.check = function (candle) {  
  console.log(candle.start.format(), this.tulipFOSC.result);
}

In case there is a general interest I can open a pull request for these new wrappers.

**Comment by H256** [comment]
Async would be a great thing to have. It opens up completely new scenarios. I once tried to trade using forecasts I created based on xfffff's gekko datasets and fb prophet. Sadly it didn't work because there was no await possible inside the strat.init() and the dataset would load a few seconds upon init. So 👍 for this feature ;)

**Comment by mark-sch** [comment]
Created a PR: https://github.com/askmike/gekko/pull/2530
