### ISSUE TITLE
Start Time showed in live trading is wrong

### ISSUE THREAD

**Issue by htilmatine** [askmike/gekko#2527]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[X] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
I've started a live trading throught UI at 19:02 (UTC +2).

**Expected result** (what you hoped would happen)
When you check the "Watching since" it should says it started at 17:02 (UTC)

**Actual result** (unexpected outcome)
Instead it's showing 16:58. Always 4 min less.
But the console it's showing the correct time .

![image](https://user-images.githubusercontent.com/42221837/45564724-a67ef500-b851-11e8-8e8e-0917166c224e.png)

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

When I do a backtesting starting at 00:02 it gives me a way bigger profit than starting at 00:00 for example.
The start time of my backtesting is:
daterange: {
    from: "2018-06-03 00:02:05",
    to: "2018-09-14 00:00:00"
  },
  batchSize: 50

I would like to replicate exactly the same in live trading but I don't know if right now it's using the candle starting at 17:02 or it's really using 16:58

Btw what is the variable batchSize?

**Comment by askmike** [comment]
> Instead it's showing 16:58. Always 4 min less.

While you are technically correct what it's showing is from what point in time this Gekko has market data from, and when Gekko fetches binance it receives a few minutes of data. Maybe we should rename the lable?

> Btw what is the variable batchSize?

A technical one, it shouldn't matter much but if you have memory problems (for example on a rasppi you can lower this).

> I would like to replicate exactly the same in live trading but I don't know if right now it's using the candle starting at 17:02 or it's really using 16:58

It's using 16:58.

----

More people have requested a live gekko strat to start at a specific time, I'll work on a fix and keep this open unitl it's fixed!

**Comment by htilmatine** [comment]
Thanks a lot!
