### ISSUE TITLE
logging not working

### ISSUE THREAD

**Issue by kirstenjg** [askmike/gekko#2531]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
added log.debug code to my strategy and logging not appearing on UI. Running in UI mode

**Expected result** (what you hoped would happen)
Expect logging to output on screen. Also thge log directory remains empty

**Actual result** (unexpected outcome)
no logging

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
version 0.6.6

**Comment by bvanhou** [comment]
Running into a similar issue, 
    Logging works on MacOS and only shows errors on Linux

**Comment by askmike** [comment]
If you are not running backtests: sounds like a bug.

If you are running backtests: logging is surpressed because it slows down backtests very much. Can you tell me more about what you are doing (are you developing your own strat? Where do you want the logs to appear?)

**Comment by kirstenjg** [comment]
I am running back tests. It used to work but after upgrading to latest version it stopped working. But it's fine I am using console.debug instead.

**Comment by askmike** [comment]
> But it's fine I am using console.debug instead.

So you don't have problems anymore? Great!
