### ISSUE TITLE
add exchange

### ISSUE THREAD

**Issue by danielro7587** [askmike/gekko#2534]
Hi, I instal gekko correctly in windows and I have only 1 problem for adding exchange.
in your video you explain many things but when you open url, all exchanges be add.

I see Help page but do'nt understand means of this:

const Exchange = require('./wrapper' + [exchange slug]);
this.exchange = new Exchange({key: '', secret: '', username: '', currency: 'USD', asset: 'BTC'});

I must run this in bash or change in file?

I know my question is basically but very thanks for your answer please

**Comment by askmike** [comment]
Thanks for creating the issue, unfortunately I am not understanding your question.

Could explain a bit more clearly what you are trying to do with Gekko?

**Comment by danielro7587** [comment]
Hi,
thanks for your answer
I want to auto trade with gekko but  can't add exchange (binance)

**Comment by askmike** [comment]
Gekko has support for binance, when most people talk about adding an exchange they talk to adding support to a new exchange that gekko does not support.

If you have installed everything correctly you can already simulate over binance markets, and import historical data. See the importer. You can add your API required for live trading. See the documentation for that.

Note that Gekko is a technical tool, if you are asking these questions I don't think Gekko is the tool for you. This is also the bug tracker, were we track bugs in Gekko. Please see this page for better places to ask questions: https://gekko.wizb.it/docs/introduction/getting_help.html
