### ISSUE TITLE
this.advice is not a function

### ISSUE THREAD

**Issue by moo5e** [askmike/gekko#2539]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Added this to my code:
            this.advice({
                direction: 'long',
                trigger: {
                  type: 'trailingStop',
                  trailPercentage: 0.5
                }
            });

**Expected result** (what you hoped would happen)
Gekko would buy the asset with the trailing stop in action

**Actual result** (unexpected outcome)
the this.advice function doesnt trigger

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
this.advice('long') works in the same context as the above.
I'm running gekko v0.6.5 on ubuntu 18.04
Could this be due to an outdated gekko?

**Comment by askmike** [comment]
> I'm running gekko v0.6.5 on ubuntu 18.04
> Could this be due to an outdated gekko?

No.

Can you please post your full code in a gist (don't copy it here).

**Comment by moo5e** [comment]
The functions working know after I updated gekko.
Was this an error within my code?
I've realised theres another error aswell, when I start the backtest I get this:
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments:
[0] _isAMomentObject: true, _isUTC: true, _useUTC: true, _l: undefined, _i: 2018-08-5, _f: undefined, _strict: undefined, _locale: [object Object]
Error

**Comment by askmike** [comment]
Most likely an error in your code. You can ignore that other warning.

If this is fixed now can you close the issue?
