### ISSUE TITLE
Error while importing

### ISSUE THREAD

**Issue by Gythion** [askmike/gekko#2541]
<-- GET /api/imports
  --> GET /api/imports 200 0ms 2b
  <-- GET /api/gekkos
  --> GET /api/gekkos 200 0ms 24b
  <-- GET /api/apiKeys
  --> GET /api/apiKeys 200 0ms 2b
  <-- GET /api/exchanges
  --> GET /api/exchanges 200 562ms 87.76kb
  <-- POST /api/import
Import 74074835669277 started
  --> POST /api/import 200 62ms 149b
RECEIVED ERROR IN IMPORT 74074835669277

I can't download Import data

**Comment by askmike** [comment]
Strange, unfortunately there is no debug information. May i ask you to run the import over the commandline and post all logs here? Here is a step by step guide on how to do that: https://forum.gekko.wizb.it/thread-57656.html

**Comment by Gythion** [comment]
I have a file named Sample-config but not Config.js in the directory.

**Comment by askmike** [comment]
Ah let me clarify the first instruction:

> Copy gekko/sample-config.js into gekko/config.js

This means create a new file called config.js and copy the contents of sample-config.js into it. I'll update the text.
