### ISSUE TITLE
Help with installation and startup

### ISSUE THREAD

**Issue by ghost** [askmike/gekko#2547]
Hi, I installed gekko but when I opened it and I went to "Local Data" to import market data, the windows of "exchange" "currency" and "asset" doesn't open, so i'm not able to import anything. Then i went to config to configure api keys but the exchange windows had only one choice (bitfinex) but the credential column doesn't have any form to put in the log-in credential.

Hope you can help me, thanks

**Comment by DerBeweis** [comment]
go to discord kanal here : https://discord.gg/2xPMqB
you will get help for installation there

**Comment by askmike** [comment]
you most likely have not installed gekko broker dependencies. Please follow all steps in the installation doc. And as @DerBeweis said: a better place for support is discord or the forum.
