### ISSUE TITLE
Method.Update Function Not called with multiple Tulip Indicators

### ISSUE THREAD

**Issue by bvanhou** [askmike/gekko#2548]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[X ] bug report
[ ] question about the decisions made in the repository

newest Stabe build

**Action taken** (what you did)
Attempted to add multiple tulip indicators (any tulip indicators). 
Then run strategy via command line.

**Expected result** (what you hoped would happen)
The method.update function will be called.

**Actual result** (unexpected outcome)
The method.update function is not called.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

You can mix and match any of the tulip indicators. Declaring multiple of them just does not work.
```
this.addTulipIndicator('_mfi', 'mfi', {optInTimePeriod: 14});
  this.addTulipIndicator('_bb', 'bbands', {optInTimePeriod: 20, optInNbStdDevs:2});
  this.addTulipIndicator('_stoch', 'stoch', {optInFastKPeriod: 3, optInSlowKPeriod: 3, optInSlowDPeriod: 3});
  this.addTulipIndicator('_macd', 'macd', { optInFastPeriod: 10, optInSlowPeriod: 21, optInSignalPeriod: 9});
```

**Comment by askmike** [comment]
Thanks for the report, will check asap.

**Comment by bvanhou** [comment]
Thanks, this unfortunately is a big show stopper. I just tested and found that the issue occurs in v0.6.6 and not v0.6.5. Just verified.

#if this helps
config.tradingAdvisor = {
  enabled: true,
  method: 'tulip-multi-strat',
  candleSize: 1,
  historySize: 10,
}

**Note: Issue will always occur doesnt matter what you choose

**Comment by eusorov** [comment]
I can confirm, in standalone mode nothing happens but with UI-Mode it works like expected.

Added the 4 tulip indicators to tulip-multi-strat.js from above and the update method is called as expected.

In general it is probably difficult to see logs in console, because log.js prevents in UI-mode. But if you add to _write method a console.log(message); like this: 
```javascript
Log.prototype = {
   _write: function(method, args, name) {
   ...
    console.log(message);
    this.output[method](message);
}
```
than you see that the update method is called.

**Comment by eusorov** [comment]
In UI mode there is : 
candleSize = 1
historySize = 4

But in standalone mode, in  sample-config.js there is no such settings for tulip-multi-strat.

With the bugfix we check if historySize was provided or not.
