### ISSUE TITLE
candle-rewrite branch

### ISSUE THREAD

**Issue by askmike** [askmike/gekko#255]
I am rewriting huge parts of core. The current candleManager is doing a lot of things tightly related to eachother. Though because it is trying to do so many things it does them poorly, resulting in a lot of bugs. It currently does:

- do a lot of black magic figuring out what day (UTC) the history belongs to.
- get base history from DB (fixed to nedb)
- consumes new trades
- turn those into 1m candles
- turn those into Nm candles, where N is set in config
- add empty candles
- insert candles back in DB again
- do a lot of black magic trying to calculate what day (UTC) to insert new candles

New core consists of a lot more small loosely coupled parts. Each consisting of an constructor object with methods to do some thing (like transform trades into candles, those are easily testable) and an object that plugs it into the event chain in Gekko.

The new event chain is:

![photo 30-11-14 23 30 38](https://cloud.githubusercontent.com/assets/969743/5239685/03749800-78eb-11e4-9fbd-7c0432143ab5.jpg)

Once everything is solid I will create a better picture / docs.

TODO:

- [x] eventflow
- [x] heart
- [x] market data provider
- [x] small candle manager
- [x] candle manager
- [x] getCandles(since) from a datastore (1 for now)
- [x] storeCandles([]) to a datastore (1 for now)
- [x] trading advisor
- [x] trader
- [x] external plugins
- [x] update event flow (pugin) docs
- [x] add docs for adding datastore

**Comment by randy-jr-olive** [comment]
Is there work going on with the backtester somewhere on github? I'd like to see where it's at and maybe add if I can. I think I originally posted this in a closed issue.

**Comment by askmike** [comment]
bam!
