### ISSUE TITLE
Custom Strategy Backtest: non-error thrown

### ISSUE THREAD

**Issue by Bransonb3** [askmike/gekko#2550]
**I'm submitting a ...**
[X] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
checked over my code
reinstalled npm koa

**Expected result** (what you hoped would happen)
Backtest my custom strategy

**Actual result** (unexpected outcome)
xxx POST /api/backtest 500 479ms -

  Error: non-error thrown:
  This Gekko instance encountered an error and can't continue
      at Object.onerror (/root/gekko/node_modules/koa/lib/context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
Running on CentOS
Here is a link to my strategy: [https://pastebin.com/2AVYaKJs](https://pastebin.com/2AVYaKJs)

**Comment by Bransonb3** [comment]
This was a combination of some strategy code errors and not installing tulip properly.

**Comment by askmike** [comment]
:+1:
