### ISSUE TITLE
Error after click backtest

### ISSUE THREAD

**Issue by ezgoProject** [askmike/gekko#2551]
I get the error message after I click backtest.
  <-- GET /api/configPart/paperTrader
  --> GET /api/configPart/performanceAnalyzer 200 7ms 144b
  --> GET /api/configPart/paperTrader 200 4ms 132b
  --> GET /api/strategies 200 13ms 6.09kb
  <-- POST /api/scansets
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:992:11)
    at TCP.onread (net.js:618:25)

**Comment by askmike** [comment]
According to those logs you clicked "scan" not "backtest". Can you post more information?

- What version of Gekko?
- Has this ever worked?
- Have you ever ran a Gekko before?
- Have you imported data?
- etc..

**Comment by ezgoProject** [comment]
It's my database issue. The issue is gone after I change from sqlite to postgresql.
Thanks~!
