### ISSUE TITLE
Where can I find the log file for tradebot in commandline?

### ISSUE THREAD

**Issue by ezgoProject** [askmike/gekko#2554]
I see the log folder has all log files in webpage, but I can't find them from commandline.

**Comment by askmike** [comment]
If you run a CLI Gekko all output is shown in the command line (technically Gekko pipes it to stdout and stderr). So if you want to capture it in a file you can use something like:

    node gekko > my-gekko-log.txt

Or you can use something like pm2 to automatically store the output in logs.
