### ISSUE TITLE
Question on stochRSI from talib

### ISSUE THREAD

**Issue by ezgoProject** [askmike/gekko#2557]
I try to use stochRSI from talib. I just realize there are actually two outputs from talib. How can I get those two output from it?
var customStochRSI = {
		optInTimePeriod: 14,
		optInFastK_Period: 3,
		optInFastD_Period: 3,
		optInFastD_MAType: 0
	}
  this.addTalibIndicator('mystochrsi', 'stochrsi',  customStochRSI);
var stochRSIoutput = { this.outk,this.outd}
 customStochRSI = this.talibIndicators.mystochrsi.result;

this is my current code, but it's definitely wrong.

**Comment by askmike** [comment]
I'm guessing you figured i tout, since. you closes this issue?

**Comment by ezgoProject** [comment]
> I'm guessing you figured i tout, since. you closes this issue?

Yes. I found similar code  from somebody else  code. 
BTW do you know is that possible to install talib in windows 10?

**Comment by askmike** [comment]
No clue, I don't use Windows.
