### ISSUE TITLE
Kraken: TypeError: Assignment to constant variable

### ISSUE THREAD

**Issue by g1tt** [askmike/gekko#2559]
**I'm submitting a ...**
[ ] bug report

**Action taken** (what you did)
Kicked off a tradebot with Kraken. This issue exists with every currency on Kraken.

**Expected result** (what you hoped would happen)
I expected the tradebot to work 

**Actual result** (unexpected outcome)
it errors whenever it tries to retrieve the amount of currency, finds there isn't any and attempts to init a constant var to 0. 

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links 
Please see the thread at https://forum.gekko.wizb.it/thread-57644.html.
I have fixed the problem by modifying the file exchange/wrappers/kraken.js as follows -
Lines 226-229:
    if(!_.isNumber(assetAmount) || _.isNaN(assetAmount)) {
      console.log(`Kraken did not return portfolio for ${this.asset}, assuming 0.`);
      //assetAmount = 0;
    }
I have remmed out "assetAmount = 0;" on line 228 to fix the problem.
This fix needs rolling into the code.
I would love to do it but I'm not at that stage... yet! :)

**Comment by g1tt** [comment]
Sorry... I don't mean my "fix" needs rolling into the code... I mean the actual problem needs looking at and fixing! :)

**Comment by askmike** [comment]
Please run the develop branch! It has a number of fixes for kraken including this specific fix (in commit 7d548fb3ba8408cd631e0ec283db0c4f32276a12). Read here how to run the develop branch: https://gekko.wizb.it/docs/installation/updating_gekko.html#Updating-the-develop-branch

Closing this as it's fixed (in the develop branch), but I will push a new stable release asap!

**Comment by g1tt** [comment]
My apologies, I didn't realize you'd already fixed it! I am running latest develop version... I will remove my "fix" and give it a proper test! :)
