### ISSUE TITLE
[TYPO] in trader.js and paperTrader.js 'trialingStop' instead of 'trailingStop'

### ISSUE THREAD

**Issue by cstegmann** [askmike/gekko#2562]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Listened on Discord and user _philobbe_ noticed that in trader.js and paperTrader.js there's a typo. It should say 'trailingStop' but it says 'trialingStop' . Since I didn't see an issue posted (and this was said in Discord yesterday) I thought I'd post it.

**Expected result** (what you hoped would happen)

**Actual result** (unexpected outcome)

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
'm not on discord enough so thanks for reporting it here so I could fix it quickly.

I fixed it, but note that there are little consequences to this bug right now, since this was only a typo in Gekko saying "a new trigger is created with this type" and there is only 1 type (for now).

**Comment by cstegmann** [comment]
@askmike Ah ok, philobbe just found this after trying to figure out why he is seeing double sells when using trailingStop in backtesting. (Two red dots following one another on the UI graph).

**Comment by askmike** [comment]
If the problem persists, it would be great to have a new issue with debug
logs!
