### ISSUE TITLE
Sell order at the same price of buy orders 

### ISSUE THREAD

**Issue by Miguelpt1** [askmike/gekko#2565]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
started a live bot with UO strategy 1M candles. -> exchange: binance
Bot was started after days of backtesting

**Expected result** (what you hoped would happen)
Sell high -  buy low

**Actual result** (unexpected outcome)
When istart the bot he buys the coin at 14sats.
Bot places a sell order on 15sats -> bot cancel t he order
Bot places a sell order on 14sats = same price of buy.

**Comment by askmike** [comment]
That's not how Gekko works:

You should build or use a strategy that predicts the price of Gekko going up or down. Once the strategy thinks the price will go up Gekko will buy. The buy price depends on the market, not on your strategy. Read #2556 for exactly how Gekko comes with the price to buy/sell for.

It's very dangerous to only sell above your bow price. If you had a bot that did that in last December your bot would still be waiting to sell at 20k.

**Comment by Miguelpt1** [comment]
@askmike 
Maybe i did not explain myself in the best way.

in the moment 2 things are happening.

strategy a) 
Works very well on paper trade, nothing happens when i make it real. The bot doesnt even place a buy or sell order.

strategy b)
The bot starts selling at the same price that he has bought. It doesn't make sense.
The bot create a buy order and buys, then it places a sell order with profit, cancels the order and places a sell order at the buy price. 

Is this normal?

**Comment by askmike** [comment]
> The bot starts selling at the same price that he has bought. It doesn't make sense. The bot create a buy order and buys, then it places a sell order with profit, cancels the order and places a sell order at the buy price. Is this normal?

Yes this is normal, please read my first comment.

> Works very well on paper trade, nothing happens when i make it real. The bot doesnt even place a buy or sell order.

Please open a new issue for this, and please post all the logs. Without the logs we cannot see what is happening.
