### ISSUE TITLE
Trading With Half Balance

### ISSUE THREAD

**Issue by LoayGhreep** [askmike/gekko#2567]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ ] bug report
[*] question about the decisions made in the repository

**Is There Any Possible Way To Make Gekko Trading With My Half Balance ? Or Limit The Trade Balance ?**

**Comment by askmike** [comment]
Not right now, it's on the roadmap but doing this properly is a hard problem (specifically if we want Gekko to handle restarts properly).
