### ISSUE TITLE
Installation procedure on a mac

### ISSUE THREAD

**Issue by botsedge** [askmike/gekko#2574]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Installed Gekko on several macs as per given installation procedure

**Expected result** (what you hoped would happen)
Expected program to be installed correctly

**Actual result** (unexpected outcome)
No write permissions for the Gekko folder and the files within, so installing the dependencies failed

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Mike, i moved the installation problem to this new issue.
Once again here is the detailed procedure.
I installed Gekko on a Macbook Pro from 2011, on a Macbook Pro from 2015, on a Mac mini from 2015 and on an Imac from 2012. All macs were plugged in, none was running on bat power.

On all machines i was logged in as a normal user, the way Apple wants their users to use the computer. So when first buying that mac i created a user and a log in and used that login.

I then installed the newest nodejs version. This installation procedure went uneventful for all 4 machines.

I then installed git either via brew or via Xcode. The installation procedure again went uneventful, git was there.

I then git cloned the Gekko repo onto the machines using exactly the given command on the Gekko installation page. That went uneventful besides the only problem that afterwards the Gekko folder and all files within did not have write permission. The git cloning process cloned the repo onto my machines into ~/Gekko

Because there were no write permissions, installing the dependencies via npm install failed.

The solution for me was to manually set the write permission for the Gekko folder and the files within.
On the subsequent machines i did change the rights globally with 

`chmod -R 777 ~/gekko`

I am the only one using those macs so i don´t have a problem with the global write permission

**Comment by askmike** [comment]
When I download Gekko via git I do not have any permission problems. Just so that we are on the same line, you have these problems when you run the following:

    cd ~
    git clone https://github.com/askmike/gekko gekko-test
    cd gekko-test
    npm i
    cd exchange
    npm i

**Comment by askmike** [comment]
If the above fails, can you post the output of the following commands:

    whoami
    ls -lah /Users/
    ls -lah /Users/$(whoami)/gekko-test | grep gekko
