### ISSUE TITLE
Bitstamp requires "secret" to be set in the config

### ISSUE THREAD

**Issue by Helpsey** [askmike/gekko#258]
Hi there,

Getting the following error:

"Gekko encountered an error and can't continue

Meta debug info:

Gekko version: v0.1.2
Nodejs version: v0.10.3

Error:

Bitstamp requires "secret" to be set in the config"

Key, secret and username have been entered into the relevant section of config.js

Thanks

**Comment by askmike** [comment]
This should work fine (especially since version 0.2), if you still have problems let me know!
