### ISSUE TITLE
i have a problem?

### ISSUE THREAD

**Issue by TaranuStefan** [askmike/gekko#2582]
npm ERR!     C:\Users\Stef\AppData\Roaming\npm-cache\_logs\2018-10-07T18_01_54_429Z-debug.log

**Comment by TaranuStefan** [comment]
npm ERR! code ENOGIT
npm ERR! Error while executing:
npm ERR! undefined ls-remote -h -t ssh://git@github.com/askmike/npm-kraken-api.git
npm ERR!
npm ERR! undefined
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Stef\AppData\Roaming\npm-cache\_logs\2018-10-07T18_37_00_240Z-debug.log

**Comment by askmike** [comment]
You don't have git installed. Please install git first.
