### ISSUE TITLE
found 1 low severity vulnerability ...  error 

### ISSUE THREAD

**Issue by atifsari** [askmike/gekko#2585]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**
I just installed gekko on c:\ at the end I get this message error "node-pre-gyp WARN Using request for node-pre-gyp https download
[sqlite3] Success: "C:\gekko-develop\node_modules\sqlite3\lib\binding\node-v57-win32-x64\node_sqlite3.node" is installed via remote
added 213 packages from 175 contributors and audited 520 packages in 30.892s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details"

**I'm submitting a ...**
[ ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)

I run `npm audit fix` to fix them
**Expected result** (what you hoped would happen)
gave me another message " npm audit fix --force" and I follow it 

**Actual result** (unexpected outcome)
 gave me this last message : 

npm WARN using --force I sure hope you know what you are doing.
+ lodash@4.17.11
updated 1 package in 2.225s
fixed 1 of 1 vulnerability in 520 scanned packages
  1 package update for 1 vuln involved breaking changes
  (installed due to `--force` option)

I tried to reinstall it in different locations ... still, I get no combo box on the config page

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
> I run npm audit fix to fix them

Don't do this! The problem is that a part of a library used everywhere in Gekko (called Lodash) had a security issue (in a function Gekko does not use, as such there is no security issue when running Gekko). I'm in the process of updating the complete the usage in this lib in the complete gekko codebase so this message won't show. But that's not done yet.

**Comment by atifsari** [comment]
Thank you ... I solve it by using bash on windows.

**Comment by gekkocu** [comment]
hello, i have no skill about coding ,and i installed helping internet video and installed gekko but there was visible only 2 exchange poloniex and bitfinex thats way i searched another tutorial about installing but now gekko broken , and i guess if i reinstall it i think it can work again , how to uninstall it ? could you help me please ? thanks

**Comment by Lucky21110** [comment]
> Thank you ... I solve it by using bash on windows.

Hello, 
How did you solve it ? Can you explain a bit ?

I tried multiple things but all combox box are still empty.

Regards

**Comment by AdrianoImperador** [comment]
how did you guys solved this issue? just ignoring the vulnerability and proceeding with the broker's dependencies installation? 
i m installing gekko on windows

**Comment by userbox020** [comment]
Hello,
In this step
cd exchange
npm install --only=production
cd ..

I get this error, I attach the picture

It would be nice if someone can help me.

I already installed 
python-3.7.2-amd64.exe
BuildTools_Full.exe (I found it on microsoft webpage as VC++ 2015 build tool, dunno if is the right one)

![1](https://user-images.githubusercontent.com/47074021/51797442-55045080-21c9-11e9-820f-957cbe97211d.jpg)

Also, Im working with metatrader and I have a collections of bots for trading that I can share.

**Comment by MartijnvanGoor** [comment]
Hey Leon,

I hope you rsolved the issue. I looked over it and I'm not sure if I can be of any help. :(

I was ondering what your expirience is with Metatrader and which bots it is you use !

Would you care to share them with me (us) ? That would be great.

Thanx in advance... Greetz 020-Martijn

**Comment by userbox020** [comment]
Hello mike!

Sorry for the delay in answer you back, i just identify your email right
now! I kind of a fan of you, so i apreciate your time.

About the EAs i have tons of them i can share without problem. I have my
telegram group

Telegram group @botsgratiscryptoforex
My telegram: @userbox020

Please send me a pm so we can chat futher more.

**Comment by hashem1671** [comment]
Hi, I'm at the beginning of the installation of Gekko. Can you help me know the steps involved in installing Gekko dependencies? Thanks

**Comment by joe0023** [comment]
https://www.youtube.com/watch?v=-WiIkIIVnps&list=PL1t7sxpCVDDKCZStBot_RjPlPyy9Qa3aY

**Comment by technocoin** [comment]
Hi guys.
I was with the same problem, because I was all the time fixing the error msg's... Forget that!!

Just follow all steps of the installation and ignore all error msg's and that is it...

Working properly.

Thanks
