### ISSUE TITLE
TP

### ISSUE THREAD

**Issue by ghost** [askmike/gekko#2586]
Hi,
Is there a native way for issuing a sell signal without actually setting a short advice in strategy?( or the other way around)
I mean can I set a target profit for an advice?

**Comment by askmike** [comment]
Not yet! Trailing stop losses got added recently and they are effectively the reverse of what you want here (when you register a stop loss Gekko will take over watching the price and making sure your stop gets executed timely).

Trailing stop losses are implemented in a concept called "triggers". Implementing TP should be easy enough as they are just another trigger (a very simple one that triggers whenever the price hits X).

----

For now:

- You can script your own TP to trigger inside your strategy: make a note when you buy and after this check if the candle price moves above your TP target. If so signal a sell. There are some downsides (you can only trigger the TP once every candleSize minutes).
- Keep in mind that all executions are currently done via limit orders

**Comment by ghost** [comment]
*make a note when you buy and after this check if the candle price moves above your TP target. If so signal a sell.
I'm looking for the syntax for this action, can you pls give me an example on how to do exactly that?

**Comment by askmike** [comment]
here is an example: https://gist.github.com/askmike/0419e212ca70f595f30bffa65a201080

This works great but note:

- once the TP triggers Gekko will execute using limit orders, with no guarantee at what price you'll execute.
- This assumes you're going to buy close to the candle advice price. This is not guaranteed. Read this for more info: #2556 - you can use the experimental onTrade API to get the actual execution price, but in most cases (in liquid markets) there shouldn't be a big need.
