### ISSUE TITLE
gdax.js minimum order quantities are incorrect

### ISSUE THREAD

**Issue by g1tt** [askmike/gekko#2589]
**I'm submitting a ...**
[ ] bug report

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Some of the minimum order quantities are wrong in the exchange/wrappers/gdax.js file

The current/incorrect values are -

      { pair: ['EUR', 'ETH'], minimalOrder: { amount: 0.1, unit: 'asset' } },
      { pair: ['EUR', 'LTC'], minimalOrder: { amount: 0.01, unit: 'asset' } },
      { pair: ['EUR', 'BCH'], minimalOrder: { amount: 0.1, unit: 'asset' } },
      { pair: ['EUR', 'ETC'], minimalOrder: { amount: 0.1, unit: 'asset' } },

The correct values are -

      { pair: ['EUR', 'ETH'], minimalOrder: { amount: 0.01, unit: 'asset' } },
      { pair: ['EUR', 'LTC'], minimalOrder: { amount: 0.1, unit: 'asset' } },
      { pair: ['EUR', 'BCH'], minimalOrder: { amount: 0.01, unit: 'asset' } },
      { pair: ['EUR', 'ETC'], minimalOrder: { amount: 0.01, unit: 'asset' } },

(from https://blog.coinbase.com/market-structure-update-2650072c6e3b)

Also this probably now needs pairs for GBP against all currencies as coinbase have recently started to support this. Is it as simple as just adding the new entries to this array or is there more to be done?

**Comment by askmike** [comment]
Ah great.

Would you mind creating a pull request for this?

> Also this probably now needs pairs for GBP against all currencies as coinbase have recently started to support this. Is it as simple as just adding the new entries to this array or is there more to be done?

Yes, it should be that simple.

**Comment by g1tt** [comment]
First time git user here. I think I've done this -

https://github.com/askmike/gekko/pull/2591

Just keep in mind I have no idea what I'm doing!! ;)

**Comment by askmike** [comment]
you are doing great, that indeed solves it!
