### ISSUE TITLE
Changing tulip source code *not about gekko*

### ISSUE THREAD

**Issue by moo5e** [askmike/gekko#2590]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ ] bug report
[x ] question about the decisions made in the repository

This isnt directly about gekko but I dont know where else to get help so hopefully its not a big deal.
The talib stochrsi indicator isnt accurate so I did some searching and someone found out that if you call the stoch indicator with rsi instead of the default data.close, data.high and data.low, you can get accurate stochrsi results. Since im not experienced with JS, my only change is seeking help from someone with a bit more experience. My question is how to change the default tulip inputs to rsi. Thank you in advance for any help.

**Comment by mark-sch** [comment]
You mentioned both talib and tulip, which one do you want to use?

https://tulipindicators.org/list
http://ta-lib.org/function.html

Both libs support stoch and stochrsi but gekko has only stoch implemented in tulind.js. You can simply add stochrsi to gekko tulind.js, use talib instead or directly code with the node.js talib/tulip libraries.

**Comment by moo5e** [comment]
I added stochrsi to the tulind library and it worked fine. Thank you

**Comment by moo5e** [comment]
I re installed gekko and I know I cant seem to get the stochrsi to work, can you elaborate on how to add stochrsi to the tulind library?

**Comment by mark-sch** [comment]
Take a look at talib, stochrsi is already included and you are ready to go.

**Comment by moo5e** [comment]
The talib stochrsi is inaccurate,  so Im looking for a suitable replacement

**Comment by askmike** [comment]
> The talib stochrsi is inaccurate

The stratety StochRSI that comes with Gekko? Or the indicator from tulip?

Whichever, you can try the one from TA-lib.

**Comment by moo5e** [comment]
On the gekko documentation, it says that the stochrsi is only available from the talib library. The point of this post is to find a suitable replacement as the talib stochrsi is inaccurate. Also, the dm indicator from the tulip library produces different results as the dmi from trading view. Would you happen to know why this is?
