### ISSUE TITLE
I can't start Gekko

### ISSUE THREAD

**Issue by TaranuStefan** [askmike/gekko#2595]
C:\Users\Stef\Downloads\bot\gekko-develop\gekko-develop\exchange>node gekko --ui
module.js:550
    throw err;
    ^

Error: Cannot find module 'C:\Users\Stef\Downloads\bot\gekko-develop\gekko-develop\exchange\gekko'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

**Comment by TaranuStefan** [comment]
C:\Users\Stef\Downloads\bot\gekko-develop\gekko-develop\exchange>npm install windows-build-tools --global --production

> windows-build-tools@5.0.0 postinstall C:\Users\Stef\AppData\Roaming\npm\node_modules\windows-build-tools
> node ./dist/index.js



Downloading python-2.7.15.amd64.msi
[>                                            ] 0.0% (0 B/s)
Downloaded python-2.7.15.amd64.msi. Saved to C:\Users\Stef\.windows-build-tools\python-2.7.15.amd64.msi.
Downloading vs_BuildTools.exe
[>                                            ] 0.0% (0 B/s)
Downloaded vs_BuildTools.exe. Saved to C:\Users\Stef\.windows-build-tools\vs_BuildTools.exe.

Starting installation...
Please restart this script from an administrative PowerShell!
The build tools cannot be installed without administrative rights.
To fix, right-click on PowerShell and run "as Administrator".
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! windows-build-tools@5.0.0 postinstall: `node ./dist/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the windows-build-tools@5.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Stef\AppData\Roaming\npm-cache\_logs\2018-10-15T12_59_54_958Z-debug.log

**Comment by TaranuStefan** [comment]
I am stuck

**Comment by g1tt** [comment]
See this thread -
https://forum.gekko.wizb.it/thread-57665.html
In your first post you are trying to start gekko in the "exchange" directory.
Just "cd .." then "node gekko --ui"

For your second post...
Please restart this script from an administrative PowerShell!
The build tools cannot be installed without administrative rights.
To fix, right-click on PowerShell and run "as Administrator".
:)

**Comment by TaranuStefan** [comment]
PS C:\Users\Stef>
PS C:\Users\Stef>         gekko/config/backtest.toml
gekko/config/backtest.toml : The term 'gekko/config/backtest.toml' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At line:1 char:9
+         gekko/config/backtest.toml
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (gekko/config/backtest.toml:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by g1tt** [comment]
I have no idea what you are even trying to do now!

 I see you are on windows so to get gekko up and running go here -

https://gekko.wizb.it/docs/installation/installing_gekko_on_windows.html

Follow that guide, except for this bit -

Install Gekko Broker's dependencies:

cd exchange
npm install --only=production

Do this instead! 

cd exchange
npm install --only=production
cd ..

And that should get it up and running for you.

When you get to this part -

Install Tulip Indicators 

Make sure you are running those commands in an administrative window, not a standard DOS or PowerShell window!

HTH! :)

**Comment by askmike** [comment]
As @g1tt said, you need another `cd ..` after installing Gekko Broker dependencies.

Since multiple people ran into this, I have updated the documentation.
