### ISSUE TITLE
Exchange problems.

### ISSUE THREAD

**Issue by Zorochoris** [askmike/gekko#2596]
**I'm submitting a ...**
[ ] bug report
[ x ] question about the decisions made in the repository

**Action taken** (what you did)
Installed according to instructions.

**Expected result** (what you hoped would happen)
to start a new import.

**Actual result** (unexpected outcome)
Can't start a new import and I am getting this problem:
<-- GET /api/exchanges
XXX GET /api/exchanges 500 2ms

**Comment by Zorochoris** [comment]
<-- GET /api/gekkos
  --> GET /api/gekkos 200 9ms 24b
  <-- GET /api/imports
  --> GET /api/imports 200 6ms 2b
  <-- GET /api/apiKeys
  --> GET /api/apiKeys 200 3ms 12b
  <-- GET /api/exchanges
  xxx GET /api/exchanges 500 7ms -

  TypeError: _.last(...).join is not a function
      at exchangesDir.filter.f (C:\Users\Marius\Downloads\gekko\gekko-develop\web\routes\exchanges.js:17:31)
      at Array.filter (<anonymous>)
      at Object.module.exports (C:\Users\Marius\Downloads\gekko\gekko-develop\web\routes\exchanges.js:17:6)
      at module.exports.next (<anonymous>)
      at Object.dispatch (C:\Users\Marius\Downloads\gekko\gekko-develop\node_modules\koa-router\lib\router.js:334:5)
      at dispatch.next (<anonymous>)
      at onFulfilled (C:\Users\Marius\Downloads\gekko\gekko-develop\node_modules\co\index.js:65:19)
      at <anonymous>

**Comment by Zorochoris** [comment]
Ok I found my problem, C:\Users\Marius\Desktop\gekko>npm install --only=production

> sqlite3@4.0.2 install C:\Users\Marius\Desktop\gekko\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
[sqlite3] Success: "C:\Users\Marius\Desktop\gekko\node_modules\sqlite3\lib\binding\node-v57-win32-x64\node_sqlite3.node" is installed via remote
added 212 packages from 175 contributors and audited 518 packages in 45.712s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

I ran npm audit and installed that file, this time I left it like this and it works.

**Comment by askmike** [comment]
You shouldn't run `npm audit fix`! That might lead to other problems. Instead make sure gekko broker dependencies are installed as per the installation docs!
