### ISSUE TITLE
pre-Warmup UI and hot swap of strategy/parameters

### ISSUE THREAD

**Issue by GeorgeMurAlkh** [askmike/gekko#2601]
[ ] bug report
[X] question about the decisions made in the repository

Is someone doing now pre-Warmup with historical data for UI Gekko and hot swap of strategy/parameters?
I am sure that this functionality are strongly needed.
I need this functions so if anybody doing this or preparing for this - let me know.  If nobody doing this I will do for my self and then make a PR.

From UI it will be added 1 check box (load data for warm up) and 1 button which will make params active and after changing them it will restart strategy on current data. Also I need to figure out how logging for results of trading works.
Please if you know much about architecture of the project let me know which difficulties I can meet on my way.

**Comment by askmike** [comment]
hot swapping parameters compromises the idea that gekko runs (simulations, live runs) should be deterministic, or at least as deterministic as possible. It also becomes very hard to make it clear what will happen. See #2542 for more details.

> From UI it will be added 1 check box (load data for warm up)

We don't need a checkbox, once this functionality is completed there is no reason why one doesn't want it imo.

> Please if you know much about architecture of the project let me know which difficulties I can meet on my way.

The context is that I am working on a new UI that has different functions: you can stop a bot and start a new one with the same settings (but than tweak one setting), that's the UX flow I want people to go through.

Here is a demo of the new UI: https://app.gekkoplus.com/create-bot

As for helping out, it might be a while before that new UI hits github. If you want warmup data in the current UI, these are the steps that need to be completed:

> The CLI currently fetches older data from the database and tries to merge this with fresh exchange data. We need a similar system for the UI. Here is that file for the CLI: https://github.com/askmike/gekko/blob/de...js#L42-L45
>
> We need to extend the current UI logic here: https://github.com/askmike/gekko/blob/de...ue#L56-L67
>
> But while we do that, it shouldn't be in the frontend at all. It should be in the GekkoManager, around here: https://github.com/askmike/gekko/blob/de...ger.js#L18
>
> Simply said: this is going to be very hard without extensive knowledge of the Gekko codebase. We might be able to use the script the CLI is using, but it needs to be extended to handle the fact that the data is currently being fetched from a watcher and it can't pull the exchange directly anymore. 

Closing this for now but feel free to keep commenting :)

**Comment by GeorgeMurAlkh** [comment]
@askmike thanks for response. So new version of UI will do warmup data loading? And as I understand it will come not in near future? Also could you please repeat links to files in comment above (links corrupted with dots :) )
