### ISSUE TITLE
Binance-markets are outdated

### ISSUE THREAD

**Issue by easycryptos** [askmike/gekko#2605]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Reinstalled Gekko

**Expected result** (what you hoped would happen)
Binance markets were updated

**Actual result** (unexpected outcome)
Nothing happened

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Well this issue was because, I have seen some coins at binance that are not visible at gekko.

so i was checking gekko's code and I found this

"const _ = require('lodash');
const fs = require('fs');
const request = require('request-promise');
const Promise = require('bluebird');

let getOrderMinSize = currency => {
  if (currency === 'BTC') return 0.001;
  else if (currency === 'ETH') return 0.01;
  else if (currency === 'USDT') return 10;
  else return 1;
};

const options = {
  url: 'https://www.binance.com/exchange/public/product',
  headers: {
    Connection: 'keep-alive',
    'User-Agent': 'Request-Promise',
  },
  json: true,
};

request(options)
  .then(body => {
    if (!body && !body.data) {
      throw new Error('Unable to fetch product list, response was empty');
    }

    let assets = _.uniqBy(_.map(body.data, market => market.baseAsset));
    let currencies = _.uniqBy(_.map(body.data, market => market.quoteAsset));
    let pairs = _.map(body.data, market => {
      return {
        pair: [market.quoteAsset, market.baseAsset],
        minimalOrder: {
          amount: parseFloat(market.minTrade),
          price: parseFloat(market.tickSize),
          order: getOrderMinSize(market.quoteAsset),
        },
      };
    });

    return { assets: assets, currencies: currencies, markets: pairs };
  })
   .then(markets => {
    fs.writeFileSync('../../exchanges/binance-markets.json', JSON.stringify(markets, null, 2));
    console.log(`Done writing Binance market data`);
  })
  .catch(err => {
    console.log(`Couldn't import products from Binance`);
    console.log(err);
  });
"
this is at \util\genMarketFiles

I check te website https://www.binance.com/exchange/public/product and compare with markets shown at gekko's but there are a lot of coins that gekko is not showing.

**Comment by askmike** [comment]
You can run that script yourself! If you are in the gekko folder simply do this:

    cd exchange/util/genMarketFiles 
    node update-binance.js
    cd ../../..

I will make sure I update the markets in the next Gekko release (scheduled any day now).
