### ISSUE TITLE
setting config in develop mode

### ISSUE THREAD

**Issue by nj-io** [askmike/gekko#2609]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ ] bug report
[ x] question about the decisions made in the repository

**Action taken** (what you did)

added "dev": "nodemon ./web/server.js" in ./package.json 
and run npm run build in ./web/vue

**Expected result** (what you hoped would happen)

hoped current ./config.js file to be picked up

**Actual result** (unexpected outcome)

picks up some default config from unknown source

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Is there a way to set config.js if running straight from server.js? Or is this the wrong way to run a development environment? Any new conditions that I have set in ./config.js aren't relaying through

**Comment by askmike** [comment]
There is no `./config.js` file. The config situation has evolved into something very complex, the gist is:

You can run Gekko in two modes: UI mode or CLI mode.

- in CLI mode one config file is used to start 1 gekko instance. This config describes what kind of Gekko should run. If you manually create a `./config.js` file AND specify that with a commandline flag (such as `node gekko --config config.js`) it will be used by that instance.
- in UI mode you can run a lot of different gekko instances, they will all have different configs and are build dynamically in the UI.

On top of that there is a UIconfig that let's you configure the server used by the UI (ports, hosts, etc).

-----

> Is there a way to set config.js if running straight from server.js? Or is this the wrong way to run a development environment? Any new conditions that I have set in ./config.js aren't relaying through

Can you elaborate what you mean by development mode?
