### ISSUE TITLE
No text boxes

### ISSUE THREAD

**Issue by hschudo** [askmike/gekko#2615]
**I'm submitting a**
[ ] bug report

**Action taken** (what you did)
Installed gekko and can start it properly. 

**Expected result** (what you hoped would happen)
Add configuration in config tab of gekko website

**Actual result** (unexpected outcome)
But in all websites the text boxes are missing.
Can anybody help me with this issue?

**Comment by askmike** [comment]
Install gekko broker dependencies! See the install doc.
