### ISSUE TITLE
win10 bash gdax import http 502 error

### ISSUE THREAD

**Issue by wddxnyr** [askmike/gekko#2618]
**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Import data from coinbase (gdax)

**Expected result** (what you hoped would happen)
Normal data import

**Actual result** (unexpected outcome)
From time to time, I am getting 'HTTP 502 Error: null' error, which is not recoverable by default. I added it into the recoverable error list for a temp fix. But I do not know if this can cause an issue later. 

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
Binance works fine. It seems that this only happens to gdax. I am running gekko on win10 ubuntu bash.

**Comment by askmike** [comment]
> I added it into the recoverable error list for a temp fix. But I do not know if this can cause an issue later.

It should not! A timeout can be dangerous since in that case maybe GDAX actually replied, so you can't just retry calls that changed anything (create an order, cancel an order, etc).

So your solution should be fine, would you mind creating a PR?
