### ISSUE TITLE
"RangeError: Maximum call stack size exceeded" error with high historySize values

### ISSUE THREAD

**Issue by GryphonR** [askmike/gekko#2622]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Started a CLI bot (live or paper) running on 1 minute candles and a historySize of over 4000

**Expected result** (what you hoped would happen)
Trader starts as normal

**Actual result** (unexpected outcome)
RangeError: Maximum Call Stack Size Exceeded.

![image](https://user-images.githubusercontent.com/9595723/47852630-4e398d80-ddd4-11e8-99c2-cf5fcc33571f.png)

I think too many events are being fired? I've disabled all the plugins I can and not been able to remove the error. History size up to 4000 works, 5000+ crashes.

The strategy with larger historySizes runs fine in UI initiated backtests.

Node version 8.11.3
Gekko Version 0.6.6

Error occurs both on windows and Ubuntu.

**Comment by askmike** [comment]
This has been reported before but I'm unable to reproduce it. Very strange.

I don't think this fixes it, but can you try with the latest stable version? That's 0.6.7.

**Comment by askmike** [comment]
Also: can you make sure debug is enabled?

**Comment by GryphonR** [comment]
So I've switched to my win10 desktop, 3rd computer I've tried on. Pulled the latest develop - I'll try on stable in a bit. (Clean install of gekko and dependancies)

Config file is:
![image](https://user-images.githubusercontent.com/9595723/47870114-a1c1d080-de00-11e8-9c74-5feb1ee74060.png)

Gives exactly the same error. Debug is enabled. 

![image](https://user-images.githubusercontent.com/9595723/47870602-d97d4800-de01-11e8-9614-674fac83e9ac.png)

Odd that you can't reproduce it - I have reproduced it 100% reliably over three computers and three operating systems, win7, 10 and Ubuntu... The strategy selected doesn't seem to make a difference, purely the historySize.

If there is insufficient local data to seed the strategy the error doesn't occur.

Edit - Crashes on stable 0.6.7 too. Identical error.

**Comment by askmike** [comment]
10,000 history size, woow! I never tried that before honestly..

- Why such a big history size?
- Do you also have the error with a smaller history size?

*Note that history size does not determine how long your backtest will run for, we need to improve the naming here.*

EDIT: For me the market in your example (FUEL/BTC on binance) with the same tradingAdvisor settings does work:

    ➜  gekko git:(develop) ✗ node gekko -c config.js

        ______   ________  __    __  __    __   ______
       /      \ /        |/  |  /  |/  |  /  | /      \
      /$$$$$$  |$$$$$$$$/ $$ | /$$/ $$ | /$$/ /$$$$$$  |
      $$ | _$$/ $$ |__    $$ |/$$/  $$ |/$$/  $$ |  $$ |
      $$ |/    |$$    |   $$  $$<   $$  $$<   $$ |  $$ |
      $$ |$$$$ |$$$$$/    $$$$$  \  $$$$$  \  $$ |  $$ |
      $$ \__$$ |$$ |_____ $$ |$$  \ $$ |$$  \ $$ \__$$ |
      $$    $$/ $$       |$$ | $$  |$$ | $$  |$$    $$/ 
       $$$$$$/  $$$$$$$$/ $$/   $$/ $$/   $$/  $$$$$$/

      Gekko v0.6.7
      I'm gonna make you rich, Bud Fox. 


    2018-11-02 10:39:36 (INFO): Setting up Gekko in realtime mode
    2018-11-02 10:39:36 (INFO): 
    2018-11-02 10:39:36 (INFO): Setting up:
    2018-11-02 10:39:36 (INFO):    Trading Advisor
    2018-11-02 10:39:36 (INFO):    Calculate trading advice
    2018-11-02 10:39:36 (INFO):    Using the strategy: MACD
    2018-11-02 10:39:37 (INFO):   The trading method requests 150000 minutes of historic data. Checking availablity..
    2018-11-02 10:39:37 (INFO): 

    2018-11-02 10:39:37 (INFO):   No usable local data available, trying to get as much as possible from the exchange..
    2018-11-02 10:39:37 (INFO):   Preventing Gekko from requesting 150000 minutes of history.
    2018-11-02 10:39:37 (INFO):   Not seeding locally available data to the trading method.
    2018-11-02 10:39:37 (INFO): Setting up:
    2018-11-02 10:39:37 (INFO):    Paper Trader
    2018-11-02 10:39:37 (INFO):    Paper trader that simulates fake trades.
    2018-11-02 10:39:37 (INFO): 

    2018-11-02 10:39:37 (INFO): Starting to watch the market: Binance FUEL/BTC

**Comment by askmike** [comment]
> If there is insufficient local data to seed the strategy the error doesn't occur.

Didn't read this before. I understand the issue now. When local data is available it will pump that through the system using a different code path. This usually doesn't matter that much, but if you set your history to 10,000 that might be a bit much.

Can you help me understand why you want such a big historySize? If there is no good reason the best fix would be Gekko not allowing you to do this.

**Comment by GryphonR** [comment]
History size of 4000 and below works, 5000 and above doesn't... 4096 (2^12) might be the cut off I guess but I haven't tested to that resolution.

As to why I need it, I'm using the same very long SMA from Tommie's strategy to indicate bull/bear market, and a candle batcher in the strategy allowing it to act on advice every minute candle regardless of the timeframes of the actual indicators. 
An SMA 1000 on a ten minute timeframe requires 10,000 minutes of warmup history. If someone has a better way of judging bull bear I'm all ears :)

**Comment by askmike** [comment]
> If someone has a better way of judging bull bear I'm all ears :)

What about using a larger candleSize? A SMA 10 over 10 minute candles should be practically the same as a SMA 100 over 1 minute candles. It won't tick as often (but for averages that smooth I'd argue that's the point).

**Comment by askmike** [comment]
I'll look into what we can do to properly pipe in historical data (as opposed to blanket shoving the complete history into the gekkoStream as it's what happening now).

**Comment by GryphonR** [comment]
> What about using a larger candleSize? A SMA 10 over 10 minute candles should be practically the same as a SMA 100 over 1 minute candles. It won't tick as often (but for averages that smooth I'd argue that's the point).

Totally agreed, however the SMA in the strategy was SMA 1000 over 10 minute candles, now SMA 1000 over 4 minute candles.
The one minute candles are required for other indicators in the strategy - it's currently using indicators on about 5 different candle sizes in total, and running it at one minute candles from gekko allows entry and exits to be checked 10x more frequently than 10 minute candles. Have to run it at the lowest candle size required in the strategy and batch the candles for the other indicators.

Thanks for looking at it. Realize you're probably fully focused on gekko plus atm.

**Comment by medozero** [comment]
i am having the same issue now . using 12000 history size with 1 min multi timeframe strat using candle batcher .

**Comment by Shrike998** [comment]
Yes same here - using the same strat as Griffin and getting the exact same issue, has a work around been found for this yet anyone?

**Comment by Shrike998** [comment]
> 
> 
> Yes same here - using the same strat as Griffin and getting the exact same issue, has a work around been found for this yet anyone?

Bump..

**Comment by medozero** [comment]
i am trying to edit the code myself now . but in the same time i limited my strat to use 30 m candle to be able t reach longer history . hope that mike give better fix
