### ISSUE TITLE
Adding stochrsi to tulip

### ISSUE THREAD

**Issue by moo5e** [askmike/gekko#2623]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ ] bug report
[x ] question about the decisions made in the repository

Hello, 
I need some help with adding stochrsi to the tulip library used in gekko. The tulip library contains stochrsi but it only need to be implemented in gekko. I tried using the stochrsi code in gekko strategies but that seems to give incorrect results. Constant jumps from 0 to 100 and 100 to 0.

**Comment by askmike** [comment]
Gekko uses a file that manages the integration between Gekko and Tulip, we need to add a definition for stochRSI to it. Here is the file:

https://github.com/askmike/gekko/blob/develop/core/tulind.js#L47

You can simply copy another method and make the parameters match. After that Gekko should support it!

**Comment by moo5e** [comment]
Yes thank you
