### ISSUE TITLE
Live Trading vs. Backtest

### ISSUE THREAD

**Issue by starkadd3r** [askmike/gekko#2625]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ X] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
- live trading session did not trigger a sell while the backtest did it
- same asset/currency, method, candle size, history size and historical data

**Expected result** (what you hoped would happen)
- live trading session should have triggered a sell like backtest on the same data

**Actual result** (unexpected outcome)
- live trading session did not trigger a sell on that specific time frame

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
- i used neuralnet method 
- may be there is a simple reason i dont see

**Comment by sahni619** [comment]
Even I get a similar issue where it shows trades during backtesting, however in live trading it shows 0 trades on live gekko. But when I check the exchange, trade is happening there. It's strange.

**Comment by askmike** [comment]
Do you have logs available? If you run it through the UI logs can be found in the logs folder.

**Comment by askmike** [comment]
@sahni619 

> But when I check the exchange, trade is happening there.

Gekko only reports once the trade is fully completed. Meaning once it completely bought or sold the amount it wanted. That said there are some bugs in the current UI, work on the next on is in progress.

**Comment by sahni619** [comment]
@askmike Thanks for clarifying. Can you plz help with another issue #2646    Thanks again.
