### ISSUE TITLE
SQLite Version Issue

### ISSUE THREAD

**Issue by clickbrain** [askmike/gekko#2626]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[X ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Installed Gekko on MacOS(Mojave 10.14) and Ubuntu(18.04). 
Was able to get UI running on both. 
Updated all elements of the system prior to install
Ran the system.
Went to Local Data
Tried to run import

**Expected result** (what you hoped would happen)
Import a specific coins data for backtesting

**Actual result** (unexpected outcome)
On both installations, when I try to get data from an exchange in order to run backtests, I get the error that I need to install SQLite3.1.4
When I run the command given to me in the dialog box telling me I need it, I received a number of errors. See below
sudo npm install sqlite3@3.1.4

I then tried alternative ways of installing and also received errors during install. 
Both installs have a version of SQLite installed. 

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Error when trying to install on MacOS:
Brads-MBP:gekko bradnickel$ sudo npm install sqlite3@3.1.4
Password:

> sqlite3@3.1.4 install /Users/bradnickel/gekko/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/usr/local/bin/node',
node-pre-gyp verb cli   '/Users/bradnickel/gekko/node_modules/sqlite3/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.28
node-pre-gyp info using node@11.0.0 | darwin | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "/Users/bradnickel/gekko/node_modules/sqlite3/lib/binding/node-v67-darwin-x64/node_sqlite3.node" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.4/node-v67-darwin-x64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.4/node-v67-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download: https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.4/node-v67-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.4 and node@11.0.0 (node-v67 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.4/node-v67-darwin-x64.tar.gz 
node-pre-gyp verb command build [ 'rebuild' ]
node-pre-gyp ERR! Tried to download: https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.4/node-v67-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.4 and node@11.0.0 (node-v67 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http Connection closed while downloading tarball file 
node-pre-gyp verb command build [ 'rebuild' ]
gypgyp  ERR! ERR!configure error  
configure error 
gypgyp  ERR! stackERR! Error: EACCES: permission denied, mkdir '/Users/bradnickel/gekko/node_modules/sqlite3/build'
 stack Error: EACCES: permission denied, mkdir '/Users/bradnickel/gekko/node_modules/sqlite3/build'
gyp ERR! gypSystem Darwin 18.0.0
 ERR! System Darwin 18.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/bradnickel/gekko/node_modules/sqlite3/lib/binding/node-v67-darwin-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/Users/bradnickel/gekko/node_modules/sqlite3/lib/binding/node-v67-darwin-x64"
gyp gyp ERR!ERR!  cwdcommand /Users/bradnickel/gekko/node_modules/sqlite3
 "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/bradnickel/gekko/node_modules/sqlite3/lib/binding/node-v67-darwin-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/Users/bradnickel/gekko/node_modules/sqlite3/lib/binding/node-v67-darwin-x64"
gyp ERR! gypnode -v v11.0.0
gyp  ERR! ERR!node-gyp -v  v3.8.0
gyp cwdERR! /Users/bradnickel/gekko/node_modules/sqlite3
 gyp not okERR! node -v v11.0.0
 
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/bradnickel/gekko/node_modules/sqlite3/lib/binding/node-v67-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/bradnickel/gekko/node_modules/sqlite3/lib/binding/node-v67-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/bradnickel/gekko/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Darwin 18.0.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/bradnickel/gekko/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/bradnickel/gekko/node_modules/sqlite3
node-pre-gyp ERR! node -v v11.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.28
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/bradnickel/gekko/node_modules/sqlite3/lib/binding/node-v67-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/bradnickel/gekko/node_modules/sqlite3/lib/binding/node-v67-darwin-x64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@3.1.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@3.1.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bradnickel/.npm/_logs/2018-11-03T22_40_01_165Z-debug.log

**Comment by clickbrain** [comment]
Further to this, I installed SQLite version 3.24.0 2018-06-04 14:10:15 via Make process and it is running and I am still getting the popup dialog box about needing 3.1.4

**Comment by AlgoQ** [comment]
I had the same issue. Node version 11 isn't supported for each node modules. Download version 10 and try again.

**Comment by clickbrain** [comment]
Thanks. You mean I need to downgrade node.js to version 11? I'll have to research how to uninstall and then install version 10. Thanks for the heads up though. I'll give it a shot.

**Comment by AlgoQ** [comment]
Yes and if that doesn't work re do it on another pc/ virtual machine.
Goodluck!

**Comment by clickbrain** [comment]
Thank you for your help. Have a great day!

**Comment by FlPCrZ** [comment]
Hi, I may be late, but you could also try to have multiple node installations in your OS with nvm.. I personally never tried it but you can take a look at this article and  see if it helps: 
https://www.sitepoint.com/quick-tip-multiple-versions-node-nvm/
Good luck!

**Comment by clickbrain** [comment]
@kobej1 - Just wanted to come back in and thank you for taking the time to let me know about the Node version issue. I wiped the virtual I setup and reinstalled Ubuntu and all is well in the world. Thanks!.

**Comment by askmike** [comment]
:)

**Comment by greg1276** [comment]
in gekko dir:
edit gekko/package.json
change to "sqlite3": "^4.0.6"
npm install sqlite3

**Comment by tyeness** [comment]
> in gekko dir:
> edit gekko/package.json
> change to "sqlite3": "^4.0.6"
> npm install sqlite3

Can confirm this worked for me. Thanks Greg!
