### ISSUE TITLE
An small issue in the documentation

### ISSUE THREAD

**Issue by douglascrp** [askmike/gekko#2628]
The sample code in the check-function documentation is wrong
https://gekko.wizb.it/docs/strategies/creating_a_strategy.html#check-function

There is a missing , in the sample, just after the 'long' parameter:

**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Tried to create a custom strategy

**Expected result** (what you hoped would happen)
The code works

**Actual result** (unexpected outcome)
Got an error:
trigger: { // ignored when direction is not "long"
            ^^^^^^^
SyntaxError: Unexpected identifier

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

There is a missing , in the sample, just after the 'long' parameter:

```
this.advice({
  direction: 'long' // or short
  trigger: { // ignored when direction is not "long"
    type: 'trailingStop',
    trailPercentage: 5
    // or:
    // trailValue: 100
  }
});
```

should be:

```
this.advice({
  direction: 'long', // or short
  trigger: { // ignored when direction is not "long"
    type: 'trailingStop',
    trailPercentage: 5
    // or:
    // trailValue: 100
  }
});
```

**Comment by askmike** [comment]
Nice catch! Would you mind submitting a PR for this?

**Comment by bmarchesini** [comment]
I created a PR to solve the problem ;)

**Comment by douglascrp** [comment]
@bmarchesini LOL
You were faster than me

I have just created a new one :grin:

**Comment by askmike** [comment]
Ah! Well the important thing is that the issue is now fixed :)

@douglascrp thanks for the report and the PR!
@bmarchesini thanks for the PR!
