### ISSUE TITLE
 Bittrex API error message

### ISSUE THREAD

**Issue by demaxiya1982** [askmike/gekko#2632]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ ] bug report
Bittrex API error message
[ ] question about the decisions made in the repository
Bittrex's API can already create orders normally, but the data returned by the API in the method checkorder
How should I let him continue working?
**Action taken** (what you did)
I modified throw 'a'

  For (let i = 0; i < result.result.length; i++) {
      Let OrderUuid = result.result[i].OrderUuid;
       If(OrderUuid == order){
        Return callback(undefined, {
          Executed: result.result[i].Quantity === result.result[i].QuantityRemaining,
          Open: result.result[i].Closed,
          filledAmount:+result.result[i].QuantityRemaining
        });
       }
    }

**Expected result** (what you hoped would happen)
checkOrder returns json data
{
"success" : true,
"message" : "",
"result" : [{
"Uuid" : null,
"OrderUuid" : "09aa5bb6-8232-41aa-9b78-a5a1093e0211",
"Exchange" : "BTC-LTC",
"OrderType" : "LIMIT_SELL",
"Quantity" : 5.00000000,
"QuantityRemaining" : 5.00000000,
"Limit" : 2.00000000,
"CommissionPaid" : 0.00000000,
"Price" : 0.00000000,
"PricePerUnit" : null,
"Opened" : "2014-07-09T03:55:48.77",
"Closed" : null,
"CancelInitiated" : false,
"ImmediateOrCancel" : false,
"IsConditional" : false,
"Condition" : null,
"ConditionTarget" : null
}, {
"Uuid" : null,
"OrderUuid" : "8925d746-bc9f-4684-b1aa-e507467aaa99",
"Exchange" : "BTC-LTC",
"OrderType" : "LIMIT_BUY",
"Quantity" : 100000.00000000,
"QuantityRemaining" : 100000.00000000,
"Limit" : 0.00000001,
"CommissionPaid" : 0.00000000,
"Price" : 0.00000000,
"PricePerUnit" : null,
"Opened" : "2014-07-09T03:55:48.583",
"Closed" : null,
"CancelInitiated" : false,
"ImmediateOrCancel" : false,
"IsConditional" : false,
"Condition" : null,
"ConditionTarget" : null
}
]
}

**Actual result** (unexpected outcome)
But he can't work...

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
bittrex live trading is disabled because of problems described in https://github.com/askmike/gekko/pull/2310

Did you not get a message saying trading at bittrex is not enabled?
