### ISSUE TITLE
error

### ISSUE THREAD

**Issue by yacindou** [askmike/gekko#2639]

**Comment by yacindou** [comment]
Microsoft Windows [Version 6.1.7600]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Windows\system32>cd ..

C:\Windows>cd ..

C:\>cd Users

C:\Users>cd yassine1

C:\Users\yassine1>cd gekko

C:\Users\yassine1\gekko>npm install --only=production

> sqlite3@4.0.2 install C:\Users\yassine1\gekko\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaw
s.com/sqlite3/v4.0.2/node-v67-win32-ia32.tar.gz
node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.0.2 and node@11.1.0
 (node-v67 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Pre-built binaries not installable for sqlite3@4.0.2 and node@
11.1.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error Connection closed while downloading tarball file
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe".
 To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visua
l Studio 2005 or 3) add the location of the component to the system path if it
is installed elsewhere.  [C:\Users\yassine1\gekko\node_modules\sqlite3\build\bi
nding.sln]
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe".
 To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visua
l Studio 2005 or 3) add the location of the component to the system path if it
is installed elsewhere.  [C:\Users\yassine1\gekko\node_modules\sqlite3\build\bi
nding.sln]
gyp ERR! build error
gypgyp ERR! stack  Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild
.exe` failed with exit code: 1
ERR!gyp  ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_mod
ules\npm\node_modules\node-gyp\lib\build.js:262:23)
build errorgyp
 ERR!gyp ERR!  stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbui
ld.exe` failed with exit code: 1
gyp ERR!stack      at ChildProcess.emit (events.js:182:13)
stackgyp     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\no
de_modules\node-gyp\lib\build.js:262:23)
 ERR!gyp  ERR!stack      at Process.ChildProcess._handle.onexit (internal/child_
process.js:246:12)
stack     at ChildProcess.emit (events.js:182:13)
gyp gyp ERR! ERR!System  Windows_NT 6.1.7600
stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:
12)
gyp gyp ERR! System Windows_NT 6.1.7600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallb
ack-to-build" "--module=C:\\Users\\yassine1\\gekko\\node_modules\\sqlite3\\lib\\
binding\\node-v67-win32-ia32\\node_sqlite3.node" "--module_name=node_sqlite3" "-
-module_path=C:\\Users\\yassine1\\gekko\\node_modules\\sqlite3\\lib\\binding\\no
de-v67-win32-ia32" "--napi_version=3" "--node_abi_napi=napi"
ERR! gypcommand  "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallb
ack-to-build" "--module=C:\\Users\\yassine1\\gekko\\node_modules\\sqlite3\\lib\\
binding\\node-v67-win32-ia32\\node_sqlite3.node" "--module_name=node_sqlite3" "-
-module_path=C:\\Users\\yassine1\\gekko\\node_modules\\sqlite3\\lib\\binding\\no
de-v67-win32-ia32" "--napi_version=3" "--node_abi_napi=napi"
ERR!gyp  cwdERR! C:\Users\yassine1\gekko\node_modules\sqlite3
 cwdgyp C:\Users\yassine1\gekko\node_modules\sqlite3
 ERR!gyp  node -vERR! v11.1.0
 node -vgyp v11.1.0
 gypERR! node-gyp -v v3.8.0
gyp ERR! not ok
 ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.e
xe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.j
s build --fallback-to-build --module=C:\Users\yassine1\gekko\node_modules\sqlite
3\lib\binding\node-v67-win32-ia32\node_sqlite3.node --module_name=node_sqlite3 -
-module_path=C:\Users\yassine1\gekko\node_modules\sqlite3\lib\binding\node-v67-w
in32-ia32 --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\yassine1\gekko
\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi
ld_process.js:257:5)
node-pre-gyp ERR! System Windows_NT 6.1.7600
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\yass
ine1\\gekko\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallbac
k-to-build"
node-pre-gyp ERR! cwd C:\Users\yassine1\gekko\node_modules\sqlite3
node-pre-gyp ERR! node -v v11.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node
_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --m
odule=C:\Users\yassine1\gekko\node_modules\sqlite3\lib\binding\node-v67-win32-ia
32\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\yassine1\
gekko\node_modules\sqlite3\lib\binding\node-v67-win32-ia32 --napi_version=3 --no
de_abi_napi=napi' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.0.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@4.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\yassine1\AppData\Roaming\npm-cache\_logs\2018-11-05T23_00_
20_830Z-debug.log

C:\Users\yassine1\gekko>

**Comment by sahni619** [comment]
I think you need Windows built tools. you can try installing 

`npm install --global windows-build-tools`

**Comment by yacindou** [comment]
> أعتقد أنك بحاجة إلى أدوات Windows المبنية. يمكنك محاولة تثبيت
> 
> `npm install --global windows-build-tools`

Thank you
