### ISSUE TITLE
MACD strategy seems incorrect in 0.6.7 trading XRP/USD on Bitfinex

### ISSUE THREAD

**Issue by pyp007** [askmike/gekko#2642]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ x] bug report
[ ] question about the decisions made in the repository

**Action taken** (back testing shows 8% profit)

**Expected result** (trading bot with same MACD setting should make a profit)

**Actual result** (bot bought XRP at the MACD selling point and made a 3% loss)

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by pyp007** [comment]
Seems like the trading bot use the EMA lines and the back test the MACD ones or am i missing something?

**Comment by askmike** [comment]
Could you provide some numbers or screenshots?

**Comment by pyp007** [comment]
Hi Mike,

Thanks for the reply. I inverted the positive and negative in the
thresholds and it seems to work better. I cant really trace my settings
where the bot bought in Bitfinex, i adjusted my indicators the same as the
bot settings. Should i look at the normal MA indicators and not the one for
MACD? Does this strategy only use the MACD thresholds?

May you please send me a strategy where you combined more that one
indicaters? Want to get an idea how to code it.

Thanks for the great work!

Regards
Stephan
