### ISSUE TITLE
Unexpected token < in JSON at position 28

### ISSUE THREAD

**Issue by f47web** [askmike/gekko#2643]
Hi

I get the following error when running npm install --only=production in the exchange directory: 

Unexpected token < in JSON at position 28

Any ideas? :)

Thanks

**Comment by GryphonR** [comment]
Sounds like you have an incomplete merge in your package or package lock file. If you open it you'll find merge markers along the lines of :
```
<<<<<<<<<<<<<<<<<ID
code 
code
code
>>>>>>>>>>>>>>>>>>>>>>
<<<<<<<<<<<<<<<<<ID
code
code
code
>>>>>>>>>>>>>>>>>>>>>>
```
Delete all the <<< and >>> markers and one block of the code - generally the older one and try again. There may be other merge markers you need to fix if you've done an unscuccessful git merge.

**Comment by askmike** [comment]
Exactly! That should solve it :)

**Comment by IGUNUBLUE** [comment]
Hi, I have the same error. can you help me? could be more specific with the solution, please

**Comment by TheSpartanus** [comment]
Hi there, unfortunately I was observing the same error some minutes ago. Web research lead me to this conversation.... Which "lock" file do I have to open?
