### ISSUE TITLE
Gekko not able to run with nodejs 6.x

### ISSUE THREAD

**Issue by WimEderveen** [askmike/gekko#2644]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ ] bug report
[X] question about the decisions made in the repository

**Action taken** (what you did)

I'm trying to get Gekko running on my Qnap 459 pro II. But I'm running into nodejs version issues. The site states node 6 is required and I installed node 6.14.4 and gekko replies I need at least 8.11.2 the problem is I can't get 8.x versions running om my qnap due to a glibc version requirement. It needs glibc 2.7 and mine is 2.6.1. And I can't upgrade this.

**Expected result** (what you hoped would happen)

I hoped gekko would run in nodejs 6.x

**Actual result** (unexpected outcome)

The site states 6.x can be used but it requires 8.11.2 and up.

Would it be possible for you to create a branch in which gekko can be used with nodejs 6.x? Or us 8.x really needed for gekko to function? 
It would be a shame if I could not use my Nas to run Gekko

**Comment by askmike** [comment]
Apologies for the late reply.

> The site states 6.x can be used but it requires 8.11.2 and up.

It seems the documentation is outdated, Gekko really requires 8.11.2 and up.

> Would it be possible for you to create a branch in which gekko can be used with nodejs 6.x? Or us 8.x really needed for gekko to function?

Gekko used to run on node v6 but hasn't for a while. Reasons include some dependencies Gekko uses (for example the used bitfinex dependency requires node v7 and up). The only thing you can do (not recommended) is run an old version of Gekko, I'm not sure the last version was that ran over node 6 but you can browse to the history of this file to find the version that last supported it:

https://github.com/askmike/gekko/commits/develop/package.json

It's really going to be to complex to maintain multiple versions of Gekko I'm afraid.
