### ISSUE TITLE
Problem installing on window 7

### ISSUE THREAD

**Issue by yacindou** [askmike/gekko#2647]
C:\Users\yassine\gekko>npm install --only=production

> sqlite3@4.0.2 install C:\Users\yassine\gekko\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
[sqlite3] Success: "C:\Users\yassine\gekko\node_modules\sqlite3\lib\binding\node
-v64-win32-ia32\node_sqlite3.node" is installed via remote
added 213 packages from 175 contributors and audited 520 packages in 52.1s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

C:\Users\yassine\gekko>npm audit

                       === npm audit security report ===

# Run  npm install lodash@4.17.11  to resolve 1 vulnerability
SEMVER WARNING: Recommended action is a potentially breaking change

  Low             Prototype Pollution

  Package         lodash

  Dependency of   lodash

  Path            lodash

  More info       https://nodesecurity.io/advisories/577

found 1 low severity vulnerability in 520 scanned packages
  1 vulnerability requires semver-major dependency updates.

**Comment by verbraucher** [comment]
this is just a warning, does it run on your local machine or not?

**Comment by askmike** [comment]
Please check here for better places to ask your question: https://gekko.wizb.it/docs/introduction/getting_help.html

I don't have a windows machine so I can't help you, and this is the bug tracker used for discussing and tracking bugs within the code of Gekko.
