### ISSUE TITLE
log messages from a strategy during or after a backtest in the web browser

### ISSUE THREAD

**Issue by verbraucher** [askmike/gekko#2652]
**I'm submitting a ...**
[x] bug report
[x] feature request

**Information** 
Is there a way in ui-mode to log messages from a strategy during or after a backtest in the console of the web browser or in the browser itself?

**Comment by askmike** [comment]
No easy way currently, the preferred way to debug strategies while developing is to run them through the CLI. This video goes over how to set that up: https://youtu.be/6-74ZhrG0BE

I'm going to tackle the code between the child process and the server (and the UI) in the near future, will pick this up.
