### ISSUE TITLE
Can't start any live gekko strat/watcher

### ISSUE THREAD

**Issue by joaoleite20** [askmike/gekko#2653]
I just installed Gekko in my Raspberry Pi 3 B+ and can't start any live gekko (strat or watcher)

`2018-11-15 02:53 Gekko 2018-11-15-02-53-watcher-540294952449209 started.                                                                                     │  --> POST /api/startGekko 200 26ms 1.28kb                                                                                                                   │uncaughtException TypeError: _.contains is not a function                                                                                                    │    at load (/home/pi/gekko/core/pluginUtil.js:72:11)                                                                                                        │    at /home/pi/gekko/node_modules/async/dist/async.js:1156:9                                                                                                │    at replenish (/home/pi/gekko/node_modules/async/dist/async.js:1030:17)                                                                                   │    at /home/pi/gekko/node_modules/async/dist/async.js:1034:9                                                                                                │    at _asyncMap (/home/pi/gekko/node_modules/async/dist/async.js:1154:5)                                                                                    │    at /home/pi/gekko/node_modules/async/dist/async.js:1240:16                                                                                               │    at Object.mapSeries (/home/pi/gekko/node_modules/async/dist/async.js:1066:16)                                                                            │    at loadPlugins (/home/pi/gekko/core/pipeline.js:52:11)                                                                                                   │    at /home/pi/gekko/node_modules/async/dist/async.js:3845:9                                                                                                │    at replenish (/home/pi/gekko/node_modules/async/dist/async.js:1030:17)                                                                                   │RECEIVED ERROR IN GEKKO INSTANCE 2018-11-15-02-53-watcher-540294952449209                                                                                    │{}                                                                                                                                                           │2018-11-15 02:53 A gekko watcher crashed.                                                                                                                    │2018-11-15 02:53 was unable to start.`

**Comment by askmike** [comment]
You have wrong the wrong version of lodash installed.

Please delete your local node_modules & your local modified `package-lock.json`, pull the one from Github and install dependencies again.

Note: if NPM complains about running an audit command ignore it. Running that causes your issue.
