### ISSUE TITLE
Non Thrown Tulib Error

### ISSUE THREAD

**Issue by LoayGhreep** [askmike/gekko#2655]
My Simple Code : 
![image](https://user-images.githubusercontent.com/42842021/48666762-a230bb80-ead0-11e8-8378-77986fd7f154.png)

Backtest Error : 
![image](https://user-images.githubusercontent.com/42842021/48666770-b83e7c00-ead0-11e8-821d-cbbf1590f25b.png)

Paper Trading Error : 
![image](https://user-images.githubusercontent.com/42842021/48666787-08b5d980-ead1-11e8-8d47-589ad97f786b.png)

This Error Happens Only In This Indicator ( PSAR ) Otherwise Working well
i installed `npm install tulind --no-save` Already
I've been on gekko for a long time but this problem i didn't face before

**Comment by ghost** [comment]
try "npm install tulind --build-from-source"
