### ISSUE TITLE
Roundtrips: not enough data to display

### ISSUE THREAD

**Issue by motisb** [askmike/gekko#2659]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
When I run a backtest, I consistently get the message "Roundtrips - not enough data to display"

I am using the NeuralNet strategy on Poloniex with a 3-month dataset and the following parameters:
==================
method = 'adadelta'

threshold_buy = 1.00

threshold_sell = -1.00

price_buffer_len = 100

learning_rate = 0.01

momentum = 0.9

decay = 0.1

min_predictions = 720

stoploss_enabled = false

stoploss_threshold = 0.95
=====================

These are my Paper Trader settings:
================
feeMaker = 0.25
feeTaker = 0.25
feeUsing = 'maker'

[simulationBalance]
asset = 0
currency = 25000
===============

I have tried adjusting candle size and units, but the only result of that is that with some combinations of candle size / unit, the backtest doesn't even generate a graph.

**Expected result** (what you hoped would happen)
Expected a backtest graph with Roundtrips showing trades made

**Actual result** (unexpected outcome)
I got a backtest graph, but no trades shown, and under 'Roundtrips' the message "Not enough data to display"

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
That most likely means your backtest didn't do any trades. What amount does it say above the (empty graph)?
