### ISSUE TITLE
Guide for deploying to KuberNetes

### ISSUE THREAD

**Issue by tranceporter** [askmike/gekko#2662]
Hi,

Is there any guide to deploy Gekko to Google cloud using Kubernetes?

I have followed this guide, and I compiled a docker image for gekko, pushed it Google Cloud, created a Kubernetes cluster, created a deployment, exposed the deployment as a external IP address, but I do not understand how to run gekko on the Kubernetes node?

Guide : https://cloud.google.com/kubernetes-engine/docs/tutorials/hello-app

![image](https://user-images.githubusercontent.com/1443060/49119157-1e7c8900-f29f-11e8-9079-d50afd2be8e6.png)

Thanks,
Shreyas

**Comment by tranceporter** [comment]
I tried executing docker run --rm -p 8080:3000 gcr.io/fresh-gravity-223820/gekko-image:v0.6.7, which seems to have started gekko, but I still cannot view the UI? Sorry, I am new to this Kubernetes stuff..

**Comment by askmike** [comment]
> Is there any guide to deploy Gekko to Google cloud using Kubernetes?

Not that I am aware of, but I would very much like one :)

Note this is the issue tracker were we track and discuss bugs related to the Gekko code. Would you mind posting this in the forum?

- There is a subforum specifically for guides such as these: https://forum.gekko.wizb.it/forum-22.html
- If there is no guide yet, please ask in another forum (such as the technical or general discussion)

Thanks!

**Comment by tranceporter** [comment]
Thanks. It looks like we have a good guide for Amazon web servers, so I will give that a bash instead.
