### ISSUE TITLE
Gekko sell/buy on fixed price

### ISSUE THREAD

**Issue by sanitariu** [askmike/gekko#2665]
I am trying to make gekko buy on exact price and sell on exact price even if it has to wait 1 year.
How this could be done ? Anything like market limit ?

**Comment by LoayGhreep** [comment]
Gekko Works Like
When You advice him to buy
it get the market order book
if the highest bid is 1
it puts order at 1.01 even it was in selling orders
and keeps putting the highest bid everytime someone tries to put higher bid price
and the same for selling

**Comment by sanitariu** [comment]
Maybe i did not explained correctly.
Lets say we have crypto1 and crypto2.
I would like to buy with crypto1 my crypto2 only if price is =< 0.90. And sell all my crypto2 for crypto1 only if price is >= 0.95. 
Thats all and do nothing more. If price is different just wait.

**Comment by askmike** [comment]
This can't be done without editing Gekko yourself, it goes against the scope of the project. Read the scope here: https://gekko.wizb.it/docs/introduction/scope.html
