### ISSUE TITLE
[ Enhacement ] : Working With Multiple TimeFrames ( Can Be As Much As You Like )

### ISSUE THREAD

**Issue by LoayGhreep** [askmike/gekko#2666]
The Concept is simple
Using Write and read from txt file
Lets Say i want to : 
1) analyze with 4h timeframe
2) Get Entry Points With 1h Timeframe
3) Get The Phase ( Uptrend or downtrend ) With 5 Min Timeframe
4) Trade with 1 min timeframe
-------
1 , 2 and 3 will be paper traders , and 4 is tradebot
You make 3 Txt files anywhere each contain "0" as text
and the operation goes like
when 1 triggers knowing it's an uptrend it writes " 1 " to txt file 1
when 2 reads that txt file 1 contains 1 it start analyze then trigger on your conditions writing " 1 " to file txt 2
and the same when 3 reads 1 in txt2 it starts analyzing until it gets the point to buy or sell it writes " 1 or 2 " to the third txt file
the tradebot reads txt3 ... if 1 > sell ... if 2 > buy
this is just the concept ... the actual code i'll put it here within 2 days until i finish my full test
Thumbs up if you like :+1:

**Comment by Abrelaboca-zz** [comment]
Check out https://github.com/mark-sch/gekko
