### ISSUE TITLE
0x ZRX/USD Ticker Rate Limit Exceeded

### ISSUE THREAD

**Issue by johnemc2** [askmike/gekko#2674]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
During regular operation of a strategy, after a trade, Gekko returns this error from Coinbase.

**Expected result** (what you hoped would happen)
No error.

**Actual result** (unexpected outcome)
Rate limit exceeded for ticker.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

        _qs: [Object],
        _auth: [Object],
        _oauth: [Object],
        _multipart: [Object],
        _redirect: [Object],
        _tunnel: [Object],
        setHeader: [Function],
        hasHeader: [Function],
        getHeader: [Function],
        removeHeader: [Function],
        localAddress: undefined,
        pool: {},
        dests: [],
        __isRequestRequest: true,
        _callback: [Function],
        proxy: null,
        tunnel: true,
        setHost: true,
        originalCookieHeader: undefined,
        _disableCookies: true,
        _jar: undefined,
        port: 443,
        host: 'api.gdax.com',
        path: '/products/ZRX-USD/ticker',
        httpModule: [Object],
        agentClass: [Object],
        agent: [Object],
        _started: true,
        href: 'https://api.gdax.com/products/ZRX-USD/ticker',
        req: [Object],
        ntick: true,
        timeoutTimer: null,
        response: [Circular],
        originalHost: 'api.gdax.com',
        originalHostHeaderName: 'host',
        responseContent: [Circular],
        _destdata: true,
        _ended: true,
        _callbackCalled: true },
     toJSON: [Function: responseToJSON],
     caseless: Caseless { dict: [Object] },
     read: [Function],
     body: '{"message":"Public rate limit exceeded"}' },
     data: { message: 'Public rate limit exceeded' } }

**Comment by askmike** [comment]
Do you have more debug logs? I'm specifically interested in statusChange events of orders.

**Comment by johnemc2** [comment]
Watcher log uploaded.
[2018-12-05-21-37-watcher-540189018664338.log](https://github.com/askmike/gekko/files/2657828/2018-12-05-21-37-watcher-540189018664338.log)

Tradebot log uploaded.
[2018-12-06-13-57-tradebot-630227372414839.log](https://github.com/askmike/gekko/files/2657858/2018-12-06-13-57-tradebot-630227372414839.log)


I'm using the dev version of Gekko and was using advice as:

this.advice({
  direction: 'long',
  trigger: {
    type: 'trailingStop',
    trailPercentage: 1.0065
  }
});

I change that to the old way to pass long
this.advice('long');

and it stopped throwing the error.

**Comment by askmike** [comment]
Are you talking about this line in the watcher?

> 2018-12-05 23:03:26 (WARN):	GDAX returned an error while fetching trades: { Error: HTTP 429 Error: Public rate limit 

It seems Gekko was able to recover from that: Gekko tries to not query GDAX to often, but when GDAX replies with a message saying "rate imit hit" Gekko will back off and try again a few moments later. Gekko did this and continued just fine.

Based on those logs it didn't see there was any impact in Gekko's ability to monitor the market nor make trades, or do you think it did?

**Comment by lukacci** [comment]
Same problem here 
> Yapay zekaya dayalı trading sistemi yıllık ortalama %120 kazanç https://paradual.com

**Comment by askmike** [comment]
Can anyone post logs of where this is an issue? Also what the actual issue
is? Warnings as seen in the watcher logs are just warnings and no problem.
