### ISSUE TITLE
UI doesn't display backtesting results. Empty response

### ISSUE THREAD

**Issue by sergei-pankratov** [askmike/gekko#2678]
**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Downloaded and installed a strategy from here https://github.com/zschro/gekko-neuralnet
Run backtesing of this strategy via cli
`node  gekko --config sample-config.js --backtest`
Backtesting ran successfully, displaying backtesting results in the debug output
After that I tried to run backtesting via UI

**Expected result** (what you hoped would happen)
I would see backtesting result, after I schedulle backtesting using ui

**Actual result** (unexpected outcome)
After some time loading animation dissapears and nothing is shown

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
In Chrome console I see an error
`Failed to load resource: net::ERR_EMPTY_RESPONSE :3000/api/backtest:1 `
In the terminal I see
```  
--> POST /api/scansets 200 2,502ms 338b
<-- POST /api/backtest
```
The branch I am using is `develop`

**Comment by askmike** [comment]
Very strange, for me it's working.

> In the terminal I see
> 
> --> POST /api/scansets 200 2,502ms 338b
> <-- POST /api/backtest

That indicates the backtest call never completed, it should look something like this:

     --> POST /api/scansets 200 17s 263b
     <-- POST /api/backtest
     --> POST /api/backtest 200 43s 29.49kb

(in my case the backtest took 43 seconds).

**Comment by askmike** [comment]
Does the commandline output ever change? How long did the same backtest take when using the commandline? What kind of strategy are you simulating?

**Comment by sergei-pankratov** [comment]
@askmike 
>How long did the same backtest take when using the commandline?

With cli backtesting I used 30 days of 1-minute candles with a warmup set to 1000 candles. It took approximately 2 minutes 40 seconds. The same setup with UI takes approximately 2 minutes, before loading animation dissapears and an EMPTY_RESPONSE error is shown in the browser console.

>Does the commandline output ever change? 

I am not sure what you mean. When the strategy is backtested via CLI I see logs produced by the strategy and the end result, including roundtrips and stuff
When launched with UI - the last record I see is
` <-- POST /api/backtest`
I tried searching for a way to enable verbose logging in the UI mode, but I didn't find any

> What kind of strategy are you simulating?

I was trying out the strategy that uses neural net. I posted the link above, here it is again https://github.com/zschro/gekko-neuralnet

**Comment by sergei-pankratov** [comment]
I am new to nodejs ecosystem
However, I was trying to find a way to get debug logs in UI mode and I ended up with a hack, by adding a line
`    console.log(m.message);` on 29th line of core\workers\pipeline\parent.js
that allowed me to see backtesting logs in the terminal
I saw a profit report and the last line was `undefined`
So I added after my previous line
` if (!m.message)
     console.log(m);`
And thats what I got in the end. Does it help?
![image](https://user-images.githubusercontent.com/14931841/49813149-e3d32000-fd77-11e8-9b6c-a663ceb0b79e.png)

**Comment by sergei-pankratov** [comment]
Also an important note. I tried backtesting the same strategy with 1 hour candles and 10 candles warmup - it gets displayed in UI
So the issue seems to be either in 1000 warmup candles, or in overall number of candles

**Comment by askmike** [comment]
By default the server timeout is set to 2 minutes here:

https://github.com/askmike/gekko/blob/6546d5d383ab08d47b7dae2fafe34c588046b066/web/server.js#L117

To change the default setting open this file and change it to a bigger number: 

https://github.com/askmike/gekko/blob/6546d5d383ab08d47b7dae2fafe34c588046b066/web/vue/dist/UIconfig.js#L12

**Comment by askmike** [comment]
That should fix your issue :)
