### ISSUE TITLE
docs: paper trader 404

### ISSUE THREAD

**Issue by benjiqq** [askmike/gekko#2679]
**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
request https://gekko.wizb.it/docs/features/paper_trader.html

**Expected result** (what you hoped would happen)
info about trader

**Actual result** (unexpected outcome)
404 nout found

**Comment by bmarchesini** [comment]
https://gekko.wizb.it/docs/features/paper_trading.html I think you want to go to the wrong page, use this link

**Comment by benjiqq** [comment]
the link came from the main page

**Comment by bmarchesini** [comment]
Where in the main page?

**Comment by benjiqq** [comment]
no, actually the link came from here. can make a PR 
https://github.com/askmike/gekko/blob/develop/docs/features/trading_bot.md
