### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by LxiR445** [askmike/gekko#268]
npm WARN `git config --get remote.origin.url` returned wrong result (https://git
hub.com/naddison36/bitfinex.git) undefined
npm WARN `git config --get remote.origin.url` returned wrong result (https://git
hub.com/naddison36/bitfinex.git) undefined
npm ERR! git clone https://github.com/naddison36/bitfinex.git undefined
npm ERR! git clone https://github.com/naddison36/bitfinex.git undefined
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\LxiR\gekko-master\npm-debug.log

**Comment by KenanY** [comment]
@LxiR445 

```
npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.
```

Do you have `git` installed?

**Comment by Merculeses** [comment]
Make sure you have git installed in your PATH, check out how to do that here: http://stackoverflow.com/questions/26620312/installing-git-in-path-with-github-client-for-windows

Make sure you have the /cmd directory and the /bin directory in your path.
