### ISSUE TITLE
candle.start time drifts

### ISSUE THREAD

**Issue by Malefaz** [askmike/gekko#2680]
**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
started live-Gekko from CLI with candlesize=60 at 02:00 PM with data from kraken (EUR/XBT). 
I changed candle.stitcher with rkingy's code to start the livetrader in time:
https://github.com/askmike/gekko/issues/2219#issuecomment-424249361

**Expected result** (what you hoped would happen)
candle.start at 02:00 PM, 03:00 PM, 04:00 PM, ... (every 60 minutes)

**Actual result** (unexpected outcome)
candle.start drifts slowly like 02:00 PM, 03:01 PM, 04:01 PM, 05:02 PM, ...

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

First: thank you askmike and contributors! Gekko is great!

My problem:
The drift in live trading makes big differences to my backtesting . A delay of some minutes is no problem. But with the minutes summing up, my strategy loses in profit. 
At the moment I am regularly looking for the delay and restart gekko to get my candles in time. This is working fine but not the real purpose of using a bot...
  
I am using my own strategy with Gekko v0.6.7 with CLI.
I changed candle.stitcher with rkingy's code to start the livetrader in time:
https://github.com/askmike/gekko/issues/2219#issuecomment-424249361

While getting candle data from kraken i get in average about 5 times per hour this message:
2018-12-14T15:12:36.841Z 'Response code 520 (undefined)'
I think this causes the problem...

Is there a way to fix this or to get candles in time again? 

Thank you for your comments / explanations!

**Comment by IAMtheIAM** [comment]
This issue is still happening, I'm looking for a solution. Did you find one?

**Comment by Malefaz** [comment]
No, I did not find a solution, but actually the problem dissappeared for me, althought i did not change the setting. I don't know why...
But be careful: if your trading results change massively with some minutes of time shift while backtesting, your strategy ist probably overfitted an may give very bad results in live trading!

**Comment by IAMtheIAM** [comment]
I use linux `at` command to sync the gekko candle start with the exchange candle start time.

`echo "docker-compose up | at 16:00"` 
OR
`echo "node gekko.js | at 16:00"`

Now it will start my gekko bot at exactly 16:00 server time.
