### ISSUE TITLE
Gekko delay in backtest mode

### ISSUE THREAD

**Issue by AndreyZhuravlyov** [askmike/gekko#2693]
I'm submitting a bug report

**Action taken** (what you did)

We tested a simple strategy with 4 EMA's
2 EMA's for trend detection and 2 EMA's for long/short orders

**Expected result** (what you hoped would happen)

Gekko must long/short when 2 EMA's cross in backtest mode

**Actual result** (unexpected outcome)

Gekko long/short with delay by 1 candle in backtest mode
The same for any time frame
We plotted EMA's on backtest chart to check it
We plotted candle impulses to double check it
Gekko detects EMA crossing and make actions only on the next candle 
Probably Gekko waits until candle is closed and after that detects EMA crossing

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

The question is how to make Gekko act faster, without delay?
How to make Gekko detect EMA crossing inside the candle and long/short in actual candle?

**Comment by fib0618** [comment]
> I'm submitting a bug report
> 
> **Action taken** (what you did)
> 
> We tested a simple strategy with 4 EMA's
> 2 EMA's for trend detection and 2 EMA's for long/short orders
> 
> **Expected result** (what you hoped would happen)
> 
> Gekko must long/short when 2 EMA's cross in backtest mode
> 
> **Actual result** (unexpected outcome)
> 
> Gekko long/short with delay by 1 candle in backtest mode
> The same for any time frame
> We plotted EMA's on backtest chart to check it
> We plotted candle impulses to double check it
> Gekko detects EMA crossing and make actions only on the next candle
> Probably Gekko waits until candle is closed and after that detects EMA crossing
> 
> **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
> 
> The question is how to make Gekko act faster, without delay?
> How to make Gekko detect EMA crossing inside the candle and long/short in actual candle?

Hi mate, did you figure out the 1 candle delay issue in the backtest mode?
