### ISSUE TITLE
KVO indicator and programming a MVA for it

### ISSUE THREAD

**Issue by punishedbrains** [askmike/gekko#2697]
**I'm submitting a ...**
[ ] bug report
[x] question about the decisions made in the repository

**Action taken** (what you did)
Using the KVO tulip indicator

**Expected result** (what you hoped would happen)
A KVO value (which works great) and a signal value (Moving Average over the KVO).

**Actual result** (unexpected outcome)
Only the KVO is returned

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
My question is 2-fold;
1. Should the KVO indicator in this implementation have 2 return values?
2. If not, what would be a good way to collect 13 days of closing values to calculate an average myself? I was thinking about having 13 seperate variables being populated in the init fase using history data, but don't really know an elegant way to do that.

**Comment by punishedbrains** [comment]
Btw; I only backtested my strategy and just started to trade live. I noticed that for my first candle after 4 hours, the KVO was positive, while when looking on the tradingview chart, it should be negative. Is this something that can simply happen or is that a bug?

**Comment by mark-sch** [comment]
The Klinger oscillator from tulip returns only this single return value: https://tulipindicators.org/kvo

Maybe this is an inspiration for you on how to calculate the other values: https://github.com/cryptelligent/Cryptotrader/blob/master/examples/Klinger_Oscillator.coffee

**Comment by punishedbrains** [comment]
Thank you! That will definitely help. 

Vincent
