### ISSUE TITLE
Paper trader: CoinFalcon not working

### ISSUE THREAD

**Issue by philippscheer** [askmike/gekko#2698]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Tried to create a new paper trader with exchange set to CoinFalcon

**Expected result** (what you hoped would happen)
Correct creation of the trader

**Actual result** (unexpected outcome)
The paper trader loaded all the time and when I clicked 'Live Gekkos' (didn't finished after ~30min) the trader appeared but there was only basic data (exchange, pair and type) and a loader at 'Runtime'.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
Don't know if this an error with Gekko or CoinFalcon, API keys are correct, API set to read+write

**Comment by mspeedy2013** [comment]
CoinFalcon not working for me. Please help!

**Comment by aguiaradriano** [comment]
> CoinFalcon not working for me. Please help!

me too
