### ISSUE TITLE
Gekko Instances Closes unexpectedly 

### ISSUE THREAD

**Issue by sahni619** [askmike/gekko#2708]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ X ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did) 
Started 3 Gekko's in Paper Trade which were depending on a single watcher. 1 Minute, 2 Minute and 3 Minute Candles for the same market

**Expected result** (what you hoped would happen)
It started good. Did some Trades. 

**Actual result** (unexpected outcome)
Closes out unexpectedly

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

I am attaching a screenshot of the error 
<img width="1280" alt="screen shot 2019-01-22 at 2 40 42 pm" src="https://user-images.githubusercontent.com/17097887/51524558-627dab80-1e54-11e9-9f0d-5d51d2a9f5a4.png">

**Comment by Ahmet-Kaplan** [comment]
I think you have Out of Memory error.

**Comment by tomtom87** [comment]
out of memory error, you need to increase swap or ram on the instance
