### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by Qxboxone** [askmike/gekko#2711]
I'm completely new to coding and Gekko. My question is this, is it possible in the UI web version to tell it to sell if xyz percent of profit hits a certain percent and if xyz reaches  certain percent loss to sell? I'm sure this is a common question but I'm having a tough time figuring out how to do it. Any help would be much appreciated.

**Comment by tomtom87** [comment]
@Qxboxone hey man, no you would need to code a algo for that. I can help you out if you need
