### ISSUE TITLE
Change default port 3000

### ISSUE THREAD

**Issue by PanoPilot** [askmike/gekko#2715]
Hi there,

I want to run different version of gekko in parallel. Therefore I want to change the port 3000 on which gekko is running by default. Can anyone pls point me to the config files which i need to change to let gekko run on port e.g. 3005 instead the default one.

many thanks in advance!

best
Chris

**Comment by gknextlevel** [comment]
If you are running the UI the file is in: gekko root folder\web\vue\UIconfig.js
