### ISSUE TITLE
How does gekko’s tradebatcher work in the background?

### ISSUE THREAD

**Issue by NishidaRyu416** [askmike/gekko#2716]
I saw the doc of the architectural section, however, I’m still interested in how this application’s tradebatcher works in the background since seeing the `pacakage.json`, this application does have daemonizing module such as `pm2` or `forever`. So I’m guessing that as the Websocket driven stuff every time detects the changes, executes the works stored in the database. 
Am I right?
Thanks

**Comment by askmike** [comment]
The tradebatcher is a small in memory module:

- it consumes all trades (including duplicates)
- it spits out a list without duplicates.

The trades come from Gekko Broker modules that will ask a recent list of trades every few seconds form the exchange. All the trades go into the tradebatcher and out comes a list without duplicates. This is done using polling, not using a websocket.

Note that this is the technical tracker, would you mind posting these kind of questions on the forum next time? Thanks!
