### ISSUE TITLE
Re-Scan Available Data

### ISSUE THREAD

**Issue by marcpopp** [askmike/gekko#2717]
## I'm submitting a ...
[ ] bug report
[X] feature request
[ ] question about the decisions made in the repository

## Action taken (what you did)

1. Start import of local data
1. Go to the backtest page
1. Scan Available Data
1. No option available for rescan available data
1. Expected result (what you hoped would happen)
1. Button for rescan available data

## Actual result (unexpected outcome)
Page refresh necessary (resets changed parameters and settings)

**Comment by pflima92** [comment]
You can try the Gekko Quasar an external UI with that kind of feature https://github.com/H256/gekko-quasar-ui
