### ISSUE TITLE
Binance Alt coins Need Updating

### ISSUE THREAD

**Issue by nickypjames** [askmike/gekko#2723]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Reported Problem

**Expected result** (what you hoped would happen)
To be fixed and updated

**Actual result** (unexpected outcome)

unknown
**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Binance coins are missing i.e (BTT) BitTorrent

Several Coins remain on gecko but no longer in use on binance

**Comment by easycryptos** [comment]
Just update the data base, at genMarketFiles/ run the code at cmd promp  node update-binance.js with this the problem must be solved.
