### ISSUE TITLE
How to get NODE GEKKO --UI on UBUNTU AWS EC2 server IP address

### ISSUE THREAD

**Issue by zahidford** [askmike/gekko#2730]
I am running GEKKO on AWS EC2 Ubuntu server

**How do I direct the server to view the UI , My instance IP address is 3.85.36.175**

```
const CONFIG = {
    headless: true,
    api: {
        host: '0.0.0.0',
        port: 3000,
    },
    ui: {
        ssl: false,
        host: '3.85.36.175', // Set this to the IP of the machine that will run Gekko
        port: 3000,
        path: '/'
    },
    adapter: 'sqlite'

}

if(typeof window === 'undefined')
  module.exports = CONFIG;
else
  window.CONFIG = CONFIG;

```

ERROR MESSAGE:

**This site can’t be reached 3.85.36.175 refused to connect.**

**Comment by zahidford** [comment]
const CONFIG = {
  headless: false,
  api: {

    host: '0.0.0.0',
    port: 3000,
    timeout: 120000 // 2 minutes
  },
  ui: {

    ssl: false,

    host: '3.85.36.175',
    port: 3000,
    path: '/'
  },
  adapter: 'sqlite'
}

**Comment by pflima92** [comment]
Hi @zahidford 

Did you open your TCP port on with you elastic ip?
