### ISSUE TITLE
All strat runners are lost after restart

### ISSUE THREAD

**Issue by elaarabi** [askmike/gekko#2735]
**I'm submitting a ...**
[x ] bug report

**Action taken** (what you did)
Restart Gekko

**Expected result** (what you hoped would happen)

Having my strat runners back after restart

**Actual result** (unexpected outcome)
All strat runners are lost

Is there a possibility to resume my strat runners after restart ?

**Comment by arektdev** [comment]
I'm wondering the same. Or is there a plugin we can use?

**Comment by elaarabi** [comment]
I solved the problem with some changes in gekkoManager.js i will share the code once i believe it's stable.

**Comment by GregoryGHarding** [comment]
> I solved the problem with some changes in gekkoManager.js i will share the code once i believe it's stable.

Please do, im dealing with this aswell and its quite annoying especially having to warmup

**Comment by GregoryGHarding** [comment]
@elaarabi ?

**Comment by elaarabi** [comment]
> @elaarabi ?

Hello GregoryGHarding, sorry for being late, i share here my file, it was not properly programmed or commented, but im sure this will help u a lot figuring out how to reload the strat runners after a crash or a pm2 reload for example.
[gekkoManager.zip](https://github.com/askmike/gekko/files/3105217/gekkoManager.zip)
