### ISSUE TITLE
Gekko @Raspberry 3B Issue with installation

### ISSUE THREAD

**Issue by Oowii** [askmike/gekko#2737]
Hello everyone,
I just bought a raspberry 3B+ and installed raspbian on it, but I had issues installing Gekko on it.

**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
I followed instruction from https://gekko.wizb.it/docs/installation/installing_gekko_on_raspberry_pi_2_or_3.html

sudo apt-get install git
git clone git://github.com/askmike/gekko.git -b stable
cd gekko
npm install --only=production

**Expected result** (what you hoped would happen)

**Actual result** (unexpected outcome)
pi@raspberrypi:~/gekko $ npm install --only=production
npm WARN checkPermissions Missing write access to /home/pi/gekko/node_modules
npm ERR! path /home/pi/gekko/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/home/pi/gekko/node_modules'
npm ERR!  { [Error: EACCES: permission denied, access '/home/pi/gekko/node_modul                es']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, access \'/home/pi/gekko/node_modu                les\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/home/pi/gekko/node_modules' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the                 current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check t                he
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended                ).
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-03-11T12_37_09_017Z-debug.log

As I saw a lot of "permission issues", I tryed the last command with "sudo" : 
sudo npm install --only=production

and here is the result : 

> sqlite3@4.0.4 install /home/pi/gekko/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.4/node-v64-linux-arm.tar.gz
node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.0.4 and node@10.15.3 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Pre-built binaries not installable for sqlite3@4.0.4 and node@10.15.3 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error Connection closed while downloading tarball file
gypgyp  WARNWARN EACCES  user "root" does not have permission to access the dev dir "/root/.node-gyp/10.15.3"
EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.15.3"
gyp WARNgyp EACCES  attempting to reinstall using temporary dev dir "/home/pi/gekko/node_modules/sqlite3/.node-gyp"
WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/gekko/node_modules/sqlite3/.node-gyp"
gypgyp  WARNWARN  installinstall got an error, rolling back install
 got an error, rolling back install
gypgyp  WARNWARN  install got an error, rolling back install
install got an error, rolling back install
gypgyp  ERR!ERR!  configure errorconfigure error

gypgyp  ERR!ERR!  stackstack Error: EACCES: permission denied, mkdir '/home/pi/gekko/node_modules/sqlite3/.node-gyp'
 Error: EACCES: permission denied, mkdir '/home/pi/gekko/node_modules/sqlite3/.node-gyp'
gypgyp  ERR!ERR!  SystemSystem Linux 4.14.98-v7+
 Linux 4.14.98-v7+
gypgyp  ERR!ERR!  commandcommand "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/pi/gekko/node_modules/sqlite3/lib/binding/node-v64-linux-arm/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home/pi/gekko/node_modules/sqlite3/lib/binding/node-v64-linux-arm" "--napi_version=3" "--node_abi_napi=napi"
 "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/pi/gekko/node_modules/sqlite3/lib/binding/node-v64-linux-arm/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home/pi/gekko/node_modules/sqlite3/lib/binding/node-v64-linux-arm" "--napi_version=3" "--node_abi_napi=napi"
gypgyp  ERR! cwdERR! /home/pi/gekko/node_modules/sqlite3
 cwdgyp /home/pi/gekko/node_modules/sqlite3
 ERR! gypnode -v v10.15.3
 ERR!gyp  node -vERR! v10.15.3
 node-gyp -v v3.8.0
gyp gypERR!  node-gyp -vERR! v3.8.0
 not ok
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/pi/gekko/node_modules/sqlite3/lib/binding/node-v64-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/pi/gekko/node_modules/sqlite3/lib/binding/node-v64-linux-arm --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/gekko/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 4.14.98-v7+
node-pre-gyp ERR! command "/usr/bin/node" "/home/pi/gekko/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pi/gekko/node_modules/sqlite3
node-pre-gyp ERR! node -v v10.15.3
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/pi/gekko/node_modules/sqlite3/lib/binding/node-v64-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/pi/gekko/node_modules/sqlite3/lib/binding/node-v64-linux-arm --napi_version=3 --node_abi_napi=napi' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.0.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@4.0.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-03-11T12_36_21_610Z-debug.lo

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

For this try I installed nodej V10x instead of the v8x in the documentation but I had the same error with the V8x.

What I am doing wrong ? 
Thank you for your help.

**Comment by ghost** [comment]
Hi, looks like the installation script requires more permission to access some folders.
Try using `--unsafe-perm` .
Try `sudo npm install --unsafe-perm --only=production` instead of just `npm install --only=production`

**Comment by mamarais** [comment]
Thanks! This worked for me in installing Node and Blynk on a Raspberry Pi3B+.

This worked fine:
sudo npm install blynk-library -g

Installing onoff failed with permission errors as reported in the above post.

This worked:
sudo npm install --unsafe-perm onoff -g

thanks a lot!

**Comment by JeanCarlosChavarriaHughes** [comment]
Working with for  me.
--unsafe-perm
