### ISSUE TITLE
Is it possible to access the API without the UI? How?

### ISSUE THREAD

**Issue by Jaquedeveloper** [askmike/gekko#2739]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ ] bug report
[x] question about the decisions made in the repository

**Action taken** (what you did)
Deployed headless app at Heroku

**Expected result** (what you hoped would happen)
Be able to access the API without acessing the UI.
Goal: develop responsive UI for gekko to view strategies test results.

**Actual result** (unexpected outcome)
Can't access the data through the API urls. It's running realtime mode. Will use backtest.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
![Captura de Tela 2019-03-13 às 00 54 53](https://user-images.githubusercontent.com/2420271/54252819-0e757600-452b-11e9-8470-c70d84cb6dfa.png)

**Comment by pflima92** [comment]
Apparently, you have started in CLI mode, can you confirm which command have you used?

You should be able to access the api through the `/api` when executing with `--ui` argument. Furthermore, you can check the docs telling about the Web API: https://gekko.wizb.it/docs/internals/server_api.html
