### ISSUE TITLE
MAMP PRO servers do not start anymore

### ISSUE THREAD

**Issue by koenkrikilion** [askmike/gekko#2743]
**I'm submitting a ...**
question: 
my MAMP PRO servers won;t start anymore.
Can this have something tot do with installing gekko?

thx in advance for your messages

**Comment by pflima92** [comment]
Do you have any logs that help to investigate?

**Comment by koenkrikilion** [comment]
Hi, thx for your message. I spent a whole day searching and re-installing.
Until I deleted the mamp & mamp pro folders. Then it worked again. So I
don't think gekko had anything to do with it but it happened right after
istalling gekko.... sorry

Op wo 20 mrt. 2019 11:16 p.m. schreef Paulo Lima <notifications@github.com>:

**Comment by easycryptos** [comment]
> I spent a whole day searching and re-installing. Until I deleted the mamp & mamp pro folders. Then it worked again. So I don't think gekko had anything to do with it but it happened right after istalling gekko.... so

Please close this issue

**Comment by askmike** [comment]
> Until I deleted the mamp & mamp pro folders. Then it worked again. So I don't think gekko had anything to do with it but it happened right after istalling gekko.... sorry

Happy to know you solved it.
