### ISSUE TITLE
New UI on open Gekko?

### ISSUE THREAD

**Issue by rcoenen** [askmike/gekko#2744]
Hi,

sorry for cross posting this but it really matters to me: I was watching this video posted by @askmike https://www.youtube.com/watch?v=PKIxZ-Qaphk and at around 0:25 Mike states that the new UI should be available on both GekkoPlus and the open source Gekko. I have tried the open source version from Github today (22-March-2019) and the UI looks still like the old one. When can we expect the new UI on open Gekko?﻿ Am I missing something?

**Comment by Bretto** [comment]
Yes me too, I am looking into this atm...

**Comment by rcoenen** [comment]
thanks for letting me know @stalebot but this is still disappointing

**Comment by ar-to** [comment]
seems likely that the core team either is focusing on GekkoPlus or only gekko develop branch but no UI update in sight.

**Comment by rcoenen** [comment]
> seems likely that the core team either is focusing on GekkoPlus or only gekko develop branch but no UI update in sight.

Yes this is likely true. No UI work done on the Dev branch either. Generally little activity there anyway.
Given Gekko's wonky UI I end up using it in commandline mode mostly. However, once you go down that pathway there is a better option it seems: FreqTrader https://www.freqtrade.io/en/latest/
It requires you to learn Python but then again the entire industry seems to be moving into that direction, so this is not really a bad thing. And importantly, the FreqTrader dev community is very active.
