### ISSUE TITLE
Installing Gekko using Docker:  UI is unable to open a websocket connection

### ISSUE THREAD

**Issue by edudemy** [askmike/gekko#2750]
**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Installing Git Master Gekko using Docker #
$ docker-compose build
$ docker-compose up -d

**Expected result** (what you hoped would happen)
gekko instance running on localhost:3000.

**Actual result** (unexpected outcome)

> Disconnected
> Something happened to either Gekko or the connection. Please check the terminal where Gekko is running or your network connection.
> 
> This message is shown when the UI is unable to open a websocket connection with the Gekko Server.
> 

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

_Maybe this is something very basic, the web UI loads up in the background but the above error pops up saying the websocket is unable to connect._

Attaching Docker Logs
```

$ docker logs -f gekko_gekko_1


Serving Gekko UI on http://localhost:3000/

Something went wrong when trying to open your web browser. UI is running on http://localhost:3000/.
  <-- GET /favicon.ico
  --> GET /favicon.ico 404 4ms -
  <-- GET /favicon.ico
  --> GET /favicon.ico 404 1ms -
```
```


~/nodejs-projects/gekko/web/vue/dist @ slab [gamerjoe] $ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
78738f209005        gekko_gekko         "/usr/src/app/docker…"   About an hour ago   Up About an hour    0.0.0.0:3000->3000/tcp   gekko_gekko_1
1aadc1bbc61a        redis:latest        "docker-entrypoint.s…"   About an hour ago   Up About an hour    6379/tcp                 gekko_redis_1

~/nodejs-projects/gekko/web/vue/dist @ slab [gamerjoe] $ docker-compose ps
WARNING: The PORT variable is not set. Defaulting to a blank string.
ERROR: The Compose file './../../../docker-compose.yml' is invalid because:
services.gekko.ports is invalid: Invalid port ":", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
```

![Screen Shot 2019-04-03 at 6 44 25 PM](https://user-images.githubusercontent.com/2371533/55482611-8aeb0880-5642-11e9-994d-ed520979b568.png)

_Any pointers on how to solve this would be helpful. I'm running docker on Mac OS X._

**Comment by andydean565** [comment]
were you able to find a solution ? as i'm having the same issue when trying to deploy my gekko docker image to kubernetes

**Comment by viking76** [comment]
Don't use localhost prefere real IP and set a real Port, i think is **"The PORT variable is not set"** set it  to 3000. 
It was not be "Serving Gekko UI on http://localhost:3000/"  but Serving Gekko UI on http://IP:3000/
I have an docker who work well now :) with Environnement PORT:3000
If it doesn't work try to delete, download, make good environment IP & PORT and start, 
Why? : because it it wasn't good at 1st start the docker-entrypoint.sh wasn't work well after its faullty config, 
**Solution:** you can change before compose on **Dockerfile**
