### ISSUE TITLE
Timing of candles is far out of sync with TV

### ISSUE THREAD

**Issue by HurlyDesousa** [askmike/gekko#2755]
I'm running my Gekko Bot with a TD sequencil Indicator. on 1hr timeframes

There is no way to synce the 1hr bars with UTC time. 

I have tried starting the bot at a specific time, but this is very inaccurate. And a few seconds can make a big difference in the closing price of a 1hr candle. (when recreating the 1hr bar in the indicator out of 60 X 1min candles).

Even on my 1min timeframe test that i have done the Gekko bot is still out with the

**Comment by IAMtheIAM** [comment]
This is still an issue. This stale bot needs to stop closing things that are unresolved.
