### ISSUE TITLE
I have Issue in import

### ISSUE THREAD

**Issue by hems81** [askmike/gekko#2756]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...*file for error*
[ ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did) installed and open as per instruction, but import dropdown is not working to select exchange name, currency and asset 

**Expected result** (what you hoped would happen) dropdown to open

**Actual result** (unexpected outcome) drop down not working
![New Bitmap Image](https://user-images.githubusercontent.com/49524909/55965156-a33ad300-5c93-11e9-9a65-c1506346f6e9.jpg)
![New Bitmap Image](https://user-images.githubusercontent.com/49524909/55965157-a3d36980-5c93-11e9-9fda-bef516c2e9a6.jpg)

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by David-Darklake** [comment]
i have the same Problem

**Comment by bhouse044** [comment]
I'm having the same exact issue. I checked the project for the first time today. Any resolution?

**Comment by bhouse044** [comment]
@hems81, @Trader7000 any luck since you reported this issue?

**Comment by bhouse044** [comment]
@askmike please see above

**Comment by bhouse044** [comment]
I was able to find a solution per this: https://github.com/llSourcell/Watch-Me-Build-a-Trading-Bot/issues/3

**Comment by ghost** [comment]
You can mark this as solved with this solution:
https://github.com/llSourcell/Watch-Me-Build-a-Trading-Bot/issues/3#issuecomment-490804245

**Comment by hiyan** [comment]
Should have read the installation docs
