### ISSUE TITLE
How to inverse buy / sell

### ISSUE THREAD

**Issue by gofortiss** [askmike/gekko#2760]
[ ] bug report
[ x] question about the decisions made in the repository

I have created a config but i would like to sell when the bot buy and buy when the bot sell, in big i want to inverse buy/sell query.

Someone know if it's possible ?

**Comment by dachen0** [comment]
What do you mean by "in big"?
If you want it to inverse buy and sell during high volume you could make a custom version of the strategy that you are using to inverse advice when volume increases.
