### ISSUE TITLE
Gekko is not running on latest nodejs version

### ISSUE THREAD

**Issue by easycryptos** [askmike/gekko#2766]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

I have gekko installed on a windows machine, always have work fine but only with nodejs v 8.11
I tried to update nodejs to latest LTS version but gekko does not work.

**Action taken** (what you did)
Installed updated gekko version
Installed Updated nodejs LTS (V 9 to v 10.15.3)

**Expected result** (what you hoped would happen)
I expected gekko to work with lates LTS nodejs version.

**Actual result** (unepected outcome)
for me Gekko only runs on v 8.11.1

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by viking76** [comment]
It work on my docker nodejs V10.15.3 maked by default node container based on debian stretch 9, you can test it on dockerhub if you want..
I think its not gekko the problem, 
Just install the last nodejs version but don't update and try to install

**Comment by Coriou** [comment]
Have you reinstalled / recompiled the dependencies after upgrading node ? Try running `npm i --force` after the node upgrade to reinstall all dependencies and force the native ones to recompile against your current version of node.

On a side note: have a look at [nvm-sh/nvm](https://github.com/nvm-sh/nvm) which allows you run multiple, isolated, versions of node and makes for a much cleaner experience that just upgrading a single version of node.

**Comment by camel113** [comment]
For me it does not work with node v12.2.0
It works with node v10.15.0

**Comment by easycryptos** [comment]
Hi, thank you all for your responses, i did solve the problem just updating the package "promisify-node": "^0.4.0"  to "promisify-node": "^0.5.0"

doing this the problem was fully solved!.
