### ISSUE TITLE
How to add Binance API ?

### ISSUE THREAD

**Issue by vvcares** [askmike/gekko#2772]
Hi team,
I just fresh installed on my windows. Im seeing only Bitfinex as exchange on the dropdown menu. But my EXCHANGE folder has the Binance.js files. Kindly advise, how to use with Binance?

**Comment by ArashDerArcher** [comment]
hi, have you installed the exchange dependencies?

**Comment by askmike** [comment]
yep, please follow installation guide!

**Comment by carkod** [comment]
To solve this, you have to install the dependencies of the exchange folder:

`cd exchange`
`npm i`

Need to add this to the documentation?
