### ISSUE TITLE
TAlib not enabled error

### ISSUE THREAD

**Issue by Chad-69** [askmike/gekko#2777]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a bug report**
[X] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
I installed Talib and added a Talib indicator to my strategy (BBands) as described in https://gekko.wizb.it/docs/strategies/talib_indicators.html

**Expected result** (what you hoped would happen)
The strategy to execute

**Actual result** (unexpected outcome)
I get the error:

Gekko encountered an error and can't continue

Error:

Talib is not enabled

Meta debug info:

Gekko version: v0.6.8
Nodejs version: v9.11.2

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by Coriou** [comment]
Please try installing it again: 

* Go to the root directory of your Gekko clone (directory with the `gekko.js` file)
* Run `npm i talib`
* In that same directory open the `package.json` file and in the `dependencies` key, make sure you do have `talib`

Your `package.json` should look something like this (I've removed most of it for readability's sake):

```json
{
  "name": "gekko",
  "version": "0.6.8",
  "description": "A bitcoin trading bot for auto trading at various exchanges",
  "author": "Mike van Rossum <mike@mvr.me>",
  "dependencies": {
    "talib": "^1.0.6",
    ...otherDependencies
  },
  ...otherStuff
}
```

If you do see the talib dependency in there, you should be able to run your strategy and not have the `Talib is not enabled` error.

**Note**: This modified the `package.json` file. In the documentation you'll see that it's recommended to install Talib with the `--no-save` flag to avoid this modification. If you want to update Gekko through git later, you'll have to first `npm uninstall talib` then install it again after the update.

Of course, if you're comfortable with git and using branches, you'll just manage it yourself without having to uninstall it.

**Comment by Chad-69** [comment]
Many thanks. That worked!

**Comment by UnnikrishnanBhargavakurup** [comment]
`gekko/core/talib.js:40
            throw new Error(talibError + methodName + ' requires ' + paramName + '.');
            ^

Error: Gekko was unable to configure talib indicator:
	stoch requires optInFastK_Period.`

Getting this error on backtest
