### ISSUE TITLE
Wrong open and close prices from bitfinex

### ISSUE THREAD

**Issue by ExOmRa** [askmike/gekko#2778]
**I'm submitting a ...**
[X] bug report
[ ] question about the decisions made in the repository

**Action taken**
Compared a candles close prices on bitfinex exchange with prices in Gekko history

**Expected result**
Prices must be the same

**Actual result**
Some candles has a significant difference with open and close prices.

![gekko](https://user-images.githubusercontent.com/42189996/57586196-01044a00-74e2-11e9-8e22-6820d467f035.png)

**Other information**
I noticed it on many other pairs.
Exchange: Bitfinex
Cryptocurrency on the screenshot: IOTA.
Time: 2019-05-12 12:00 - 2019-05-12 12:10
Candle Size: 1 minute

**Comment by nick-dolan** [comment]
the same question

**Comment by ExOmRa** [comment]
I checked prices from Binance, its semm all fine. That mean the problem actual only for bitfinex. I think the problem may be with their API Version 1.1. Maybe if gekko will use API 2.0, the problem will be solved.

**Comment by IAMtheIAM** [comment]
@TeoWay  Why should the v1 api return incorrect data? The 2.0 is actually still in beta, so it wouldn't be good to integrate it yet as minor changes can still occur. 

I think there must be some other reason why the data could be off. I'll have to look into it more.

**Comment by IAMtheIAM** [comment]
@TeoWay Gekko already is using the v2 API for bitfinex, /exchange/package.json speceifies `bitfinex-api-node@2.0.0-beta` and the main package.json specifies `bitfinex-api-node@1.2.1^` both of which use v2 endpoints.

There must be another reason why the data is incorrect.
