### ISSUE TITLE
How to get average of previous prices in a simple buy at sell at strategy

### ISSUE THREAD

**Issue by dcornier** [askmike/gekko#2780]
Hi, im brand new and im not sure im posting at the right place this is a bit confusing for me ! Sorry if i do wrong !
Id like to create a simple buy at sell at strategy for trading over stable coins with for example de USD/USDT pair.
I already created the sell at buy at method and its working, but what i want is to get a variable with the current average price traded (like for the last 1h for example) and then use it as my trade price (with buy at "average - 0.005" and sell at "average + 0.005" for example) this is for avoiding the bot doing nothing for example when price just stay under 1.005 for 1 month for example.

I dont know if im clear, im new in JS programming and gekko so i can be a bit confused and im sorry if im not accurate or clear !

Thanks for your help !

This is my buyatsellat.js file working for now (pretty simple) 👍 

// helpers
// var _ = require('lodash');
var log = require('../core/log.js');

var config = require('../core/util.js').getConfig();
var settings = config.buyatsellat;

// let's create our own method
var method = {};

// prepare everything our method needs
method.init = function() {
  this.name = 'buyatsellat';

}

// What happens on every new candle?
method.update = function(candle) {
	//log.debug('in update');

}

// for debugging purposes log the last
// calculated parameters.
method.log = function(candle) {
	//log.debug(this)
}

method.check = function() {

	if (this.candle.close > 1.005) {
		this.advice('short');
		log.debug("Issued Buy @ " + this.candle.close)
		return;
	}
	if (this.candle.close < 0.995) {
		this.advice('long');
		log.debug("Issued Sell @ "  + this.candle.close)
		return;
	}

}

module.exports = method;

**Comment by IAMtheIAM** [comment]
Hello @dcornier Your posted strategy does nothing other than compare the close price with a fixed number. If you want to compare to a previous average, you need to store the value of each close on every tick in a global state object, and then on each tick calculate the new average. Then you would do the arithmetic on the average to come up with your buy / sell signals.

```
strat.init = function() {
  this.name = 'buyatsellat';

  // how many candles do we need as a base
  // before we can start giving advice?
  this.requiredHistory = this.tradingAdvisor.historySize;

  // global state object available on every candle tick
  this.state = {
    barHistory: {
      lastClose: 0,
      numberOfBars: 0
    }
  };
};

method.check = function() {
  // Add the current close to the running average
  this.state.barHistory.lastClose += this.candle.close;

  // Increment the number to calculate an average
  this.state.barHistory.numberOfBars += 1;

  let averagePrice = this.state.barHistory.lastClose / this.state.barHistory.numberOfBars;

  if (averagePrice > 1.005) {
    this.advice('short');
    log.debug("Issued Buy @ " + this.candle.close);
    return;
  }
  if (averagePrice < 0.995) {
    this.advice('long');
    log.debug("Issued Sell @ " + this.candle.close);
    return;
  }

};

```
This is a basic example but is pretty much what you asked for. Modify it to your needs. I hope that helps you accomplish your strategy goals.
