### ISSUE TITLE
maxAmount in reader.js is calculated incorrectly?

### ISSUE THREAD

**Issue by nhanpdnguyen** [askmike/gekko#2786]
https://github.com/askmike/gekko/blob/0ce9ddd577fa8a22812c02331a494086758dfadf/plugins/sqlite/reader.js#L17-L21

Hi,
Since ```from``` and ```to``` are unix value and gekko stores 1m candles in its database, I think ```maxAmount = (to - from)/60 + 1```,  right?

**Comment by hiyan** [comment]
Most people uses sqlite without issue there. Unless you have a specific problem, no reason to think why the code is wrong.
