### ISSUE TITLE
Cannot run gekko on Google app deployer. 

### ISSUE THREAD

**Issue by pranav3714** [askmike/gekko#2787]
**I'm submitting a ...**
[✓] bug report

**Action taken** (what you did)
I tried to deploy gekko on Google cloud as a node js app. Everything worked fine but when I tried to browse the app using the link provided by gcloud. It shows message "Gekko server cannot connect please check the terminal where u executed the npm start command on."
Looking to the terminal it does not print any error message.

**Expected result** (what you hoped would happen)
Should open gekko UI

**Actual result** (unexpected outcome)
Popup message says
 "Something happened to either Gekko or the connection. Please check the terminal where Gekko is running or your network connection.

This message is shown when the UI is unable to open a websocket connection with the Gekko Server."

**Comment by hiyan** [comment]
Check your UIconfig.js. There are 2 ports being used by Gekko, one for UI and another for API. Make sure both is accessible externally. Whenever I see that error, generally means the API port is not accessible.

**Comment by pranav3714** [comment]
`const CONFIG = {
  headless: false,
  api: {
    host: '127.0.0.1',
    port: 8080,
    timeout: 120000 // 2 minutes
  },
  ui: {
    ssl: false,
    host: 'localhost',
    port: 8080,
    path: '/'
  },
  adapter: 'sqlite'
}
`
This is my UIconfig file what is the error according to you. And thanks in advance.

**Comment by pranav3714** [comment]
I am using port 8080 bcz 

> Check your UIconfig.js. There are 2 ports being used by Gekko, one for UI and another for API. Make sure both is accessible externally. Whenever I see that error, generally means the API port is not accessible.
const CONFIG = { headless: false, api: { host: '127.0.0.1', port: 8080, timeout: 120000 // 2 minutes }, ui: { ssl: false, host: 'localhost', port: 8080, path: '/' }, adapter: 'sqlite' }
This is my UIconfig file what is the error according to you. And thanks in advance.

**Comment by pranav3714** [comment]
> Check your UIconfig.js. There are 2 ports being used by Gekko, one for UI and another for API. Make sure both is accessible externally. Whenever I see that error, generally means the API port is not accessible.

const CONFIG = { headless: false, api: { host: '127.0.0.1', port: 8080, timeout: 120000 // 2 minutes }, ui: { ssl: false, host: 'localhost', port: 8080, path: '/' }, adapter: 'sqlite' }
This is my UIconfig file what is the error according to you. And thanks in advance.

**Comment by hiyan** [comment]
127.0.0.1 and localhost should to be your external IP.

**Comment by acemi1** [comment]
const CONFIG = {
headless: true,
api: {
host: '0.0.0.0',
port: 3000,
timeout: 120000 // 2 minutes
},
ui: {
ssl: false,
host: 'xx.xxx.xx.xxx',
port: 3000,
path: '/' },
adapter: 'sqlite'}

if(typeof window === 'undefined')
  module.exports = CONFIG;
else
  window.CONFIG = CONFIG;

**Comment by acemi1** [comment]
host: 'xx.xxx.xx.xxx' ,
would you try to write your external ip address where xxx is in this line?
gekko/web/vue/dist/iuconfig.js file

If ssl is not enabled, do not use api. api key can get into the hands of foreign people
https://gekko.wizb.it/docs/installation/configuring_gekko_on_a_server.html

**Comment by hiyan** [comment]
Host should be your external IP.

Forums is the place for security concerns discussion.

**Comment by pranav3714** [comment]
Thanks to all I am closing this issue.
