### ISSUE TITLE
how to use custom strategy

### ISSUE THREAD

**Issue by zippergti** [askmike/gekko#2793]
Hello

For example, i want to use this strategy file: (in the 6th post)

https://gist.github.com/John1231983/0822062d6e252dda82e1759bb47ef4fb

with this config:
`config.StochRSI_MACD = {
  interval: 14,
  short: 12,
  long: 26,
  signal: 9, 
  thresholds: {
    low: 20,
    high: 80,
    down: -0.1,//-2,//-0.1,
    up: 0.1,//1.5,//0.25,   
    // How many candle intervals should a trend persist
    // before we consider it real?
    persistence: 3
  }
};`
how i do?

i tryed to do:
https://www.youtube.com/watch?v=YO3kbz-IAvo
https://github.com/askmike/gekko/issues/674
and waching this video:
https://gekko.wizb.it/docs/strategies/creating_a_strategy.html

but i dont know how

I think that i have to do is:

- download the file
- put on the strategy folder
- create a config.js in main directory
- copy/paste the config strategy on "  CONFIGURING TRADING ADVICE"
- create a *.toml with the parameters

If someone talk in spanish, tell me. 

sorry and thanks

**Comment by fib0618** [comment]
hey guys, any idea how to change data source input from 'close' to some other data stream like SMA(close,20) for talib indicators. At the moment, there is only optInTimePeriod as a parameter. 
Many thanks.
