### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by pensacola1989** [askmike/gekko#2805]
Hi, Gekko is a greate framework to do the quant robot trading, and here is not any issue or bugs, just same question,hope you would reply:P
1.  I know there is a fork for "mulitpletimeframe", which we can switch different candlesize in runtime, but the fork is too old,(3 years age),and I have check the discussions you mention at issue about the "mulitpletimeframe",But I think it's a very common scene, for humans to swtich different timeframes eg. 1 hour ,2 hour, 4hour,etc ,these things may be a strategy for someone who may implict with gekko too, any thoughts about that ? have you consider add the feature?
2. Does Gekko have some event on the connection with exchanges? like "timeout" etc,
Thank you!

**Comment by fabohax** [comment]
Good questions. I also want to know about the multiple time frames situation.
