### ISSUE TITLE
failure to install tulind and talib - any advise appreciated

### ISSUE THREAD

**Issue by lee12121** [askmike/gekko#2812]
this is what i get when i try to install the talib and tulind indicators on linux. any info or advise would be greatly appreciated. many thanks

...............................................................................................................................

make: Entering directory '/home/GLIgroup/gekko/node_modules/talib/build'
  CXX(target) Release/obj.target/talib/src/talib.o
make: g++: Command not found
make: *** [talib.target.mk:103: Release/obj.target/talib/src/talib.o] Error 127
make: Leaving directory '/home/GLIgroup/gekko/node_modules/talib/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.1.6-200.fc29.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /home/GLIgroup/gekko/node_modules/talib
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! talib@1.1.2 install: `node ./src/lib/build.js && node-gyp configure && node-gyp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the talib@1.1.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by ArashDerArcher** [comment]
hi lee, i think you might have a memory shortage, try stopping everything else, install your libraries then resume your workflow

**Comment by nhanpdnguyen** [comment]
You should try with node v8

**Comment by choiking** [comment]
Same failed here! on Mac

**Comment by Throwaway992** [comment]
same

**Comment by ArashDerArcher** [comment]
try this
npm install talib tulind - - no-save
