### ISSUE TITLE
feature request: please sort crypto alphabetically

### ISSUE THREAD

**Issue by rcoenen** [askmike/gekko#2813]
please sort crypto's alphabetically

![image](https://user-images.githubusercontent.com/753704/60631786-3a18b680-9dcf-11e9-9c5a-59ab51f1f78f.png)

**Comment by IAMtheIAM** [comment]
Hello @rcoenen 

I have created the feature you requested. It was a good idea and very simply to implement. Please see the attached PR https://github.com/askmike/gekko/pull/2816 and copy the code into your marketpicker.vue file until the PR is approved.

Enjoy!

![gekko sorted list](https://user-images.githubusercontent.com/13709948/60764009-7a796e00-a035-11e9-831c-17da3a71b376.png)

**Comment by rcoenen** [comment]
Sweet, thanks! Everyone will benefit!

**Comment by IAMtheIAM** [comment]
You're welcome, glad I could help.
