### ISSUE TITLE
Can't load exchanges data, error 500

### ISSUE THREAD

**Issue by Myx-supercode** [askmike/gekko#2814]
<img width="774" alt="Capture d’écran 2019-07-05 à 06 40 20" src="https://user-images.githubusercontent.com/6825523/60698579-53fdea80-9ef0-11e9-95cc-7f50ea5b1d75.png">
I have installed gekko 3 days ago and i still have this error, cant pull data from exchanges

**Comment by ArashDerArcher** [comment]
hi, try
npm install
cd exchanges
npm install

use sudo if needed

**Comment by Myx-supercode** [comment]
Hi, thanks, i tried but this error happens everytime and download stay stuck

<img width="785" alt="Capture d’écran 2019-07-05 à 15 14 34" src="https://user-images.githubusercontent.com/6825523/60724788-9e568a00-9f37-11e9-9d0b-33a55a419dc3.png">

**Comment by nathanp83** [comment]
I resolved that error by manually doing it.

cd exchange
sudo git clone git://github.com/askmike/npm-kraken-api.git

then
sudo npm install npm-kraken-api
+ kraken-api@1.0.0
updated 1 package and audited 10831 packages in 3.995s
found 0 vulnerabilities
