### ISSUE TITLE
Setup trouble on a subdomain on a VPS

### ISSUE THREAD

**Issue by antoinebrias** [askmike/gekko#2820]
Hello! I'm submitting a bug report:

**Action taken** (what you did)
I tried to install gekko on a subdomain of my VPS : gekko.example.com by following the tutorial.

**Expected result** (what you hoped would happen)
The instance works fine on gekko.example.com.

**Actual result** (unexpected outcome)
The instance works fine on gekko.example.com, BUT it also makes an instance on example.com which seems buggy. I don't want this one. 

**Other information** 
Here is my /etc/nginx/sites-enabled/default:

> server {
>     listen 80;
>     listen [::]:80;
>     server_name gekko.example.com;
>     return 301 https://$server_name$request_uri;
> }
> 
> upstream websocket {
>     server localhost:3000;
> }
> 
> server {
>     listen 443 ssl;
>     listen [::]:443 ssl;
>     root /var/www/html;
> 
>     ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem;
>     ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;
>     add_header Strict-Transport-Security "max-age=31536000";
> 
>     location / {
>             proxy_buffers 8 32k;
>             proxy_buffer_size 64k;
> 
>             proxy_pass http://websocket;
>             proxy_set_header X-Real-IP $remote_addr;
>             proxy_set_header Host $http_host;
>             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>             proxy_set_header X-NginX-Proxy true;
> 
>             proxy_http_version 1.1;
>             proxy_set_header Upgrade $http_upgrade;
>             proxy_set_header Connection "upgrade";
> 
>             proxy_read_timeout 86400s;
>             proxy_send_timeout 86400s;
> 
>             auth_basic "Restricted Content";
>             auth_basic_user_file /etc/nginx/.htpasswd;
>     }
> }

And the UIconfig.js :

> 
> const CONFIG = {
>     headless: true,
>     api: {
>         host: '127.0.0.1',
>         port: 3000,
>     },
>     ui: {
>         ssl: true,
>         host: 'gekko.example.com',
>         port: 443,
>         path: '/' // change this if you are serving from something like `example.com/gekko`
>     },
>     adapter: 'sqlite'
> }
> 
> if(typeof window === 'undefined')
>   module.exports = CONFIG;
> else
>   window.CONFIG = CONFIG;

What did I do wrong? Is there something bad in the reverse proxy configuration?

Thank you!

**Comment by uspen** [comment]
Create default server, like this:
`
    server {
        listen       80 default_server;
        server_name  example.com;
        root         /usr/share/nginx/html;
}
`
