### ISSUE TITLE
currency and assets list are not showing the current pairs on binance

### ISSUE THREAD

**Issue by billwilson12** [askmike/gekko#2825]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)

**Expected result** (what you hoped would happen)

**Actual result** (unexpected outcome)

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by ima-cache-that-pass** [comment]
Tried a different web browser already?

Are the pairs missing from other exchanges as well or just binance? 

Look through the command prompt for anything out of the ordinary after firing up Gekko and trying to import data and report it back here along with your OS and anything else relevant.
