### ISSUE TITLE
History directory does not exist. 

### ISSUE THREAD

**Issue by craterghost** [askmike/gekko#2826]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
node gekko --backtest --config config.js

**Expected result** (what you hoped would happen)
*backtests and works properly*

**Actual result** (unexpected outcome)

Gekko encountered an error and can't continue

Error:

History directory does not exist. 

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Meta debug info:

Gekko version: v0.6.8
Nodejs version: v10.16.0

**Comment by ima-cache-that-pass** [comment]
From gekko’s official documentation at https://Gekko.wizb.it (all credits to askmike)

For backtesting:
node gekko --config config.js --backtest

**Comment by Mounaiim** [comment]
still not working, same issue

**Comment by craterghost** [comment]
I just forgot to install the broker dependencies. I got it running now but I doubt that something written in node.js is capable of high frequency trading 




On Tue, Jul 30, 2019 at 7:31 AM +0200, "Mounaiim" <notifications@github.com> wrote:












still not working, same issue
