### ISSUE TITLE
Can't seem to get pass this error

### ISSUE THREAD

**Issue by idnr** [askmike/gekko#2827]
I'm running Gekko on my Ubuntu VPS, I'm new to this and getting this type of error

i'm trying to run this in a headless trusted environment.

`node gekko --config config.js`

output:
internal/modules/cjs/loader.js:628
    throw err;
    ^

Error: Cannot find module '/root/Geeko/gekko/node_modules/sqlite3/lib/binding/node-v72-linux-x64/node_sqlite3.node'
Require stack:
- /root/Geeko/gekko/node_modules/sqlite3/lib/sqlite3.js
- /root/Geeko/gekko/plugins/sqlite/handle.js
- /root/Geeko/gekko/plugins/sqlite/writer.js
- /root/Geeko/gekko/core/pluginUtil.js
- /root/Geeko/gekko/core/pipeline.js
- /root/Geeko/gekko/gekko.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/root/Geeko/gekko/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/Geeko/gekko/node_modules/sqlite3/lib/sqlite3.js',
    '/root/Geeko/gekko/plugins/sqlite/handle.js',
    '/root/Geeko/gekko/plugins/sqlite/writer.js',
    '/root/Geeko/gekko/core/pluginUtil.js',
    '/root/Geeko/gekko/core/pipeline.js',
    '/root/Geeko/gekko/gekko.js'
  ]
}

**Comment by ima-cache-that-pass** [comment]
Issue looks like the SQLite plugin/adapter.
Try the following in terminal and let us know how it goes! (Let the first command run and finish before executing the second command)

sudo apt-get update
sudo apt-get install sqlite3 libsqlite3-dev

**Comment by idnr** [comment]
I did the above command via terminal 

`sudo apt-get update`

output
Hit:1 https://deb.nodesource.com/node_12.x bionic InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu bionic InRelease                     
Get:3 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]   
Get:4 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]    
Get:5 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB] 
Get:6 http://us.archive.ubuntu.com/ubuntu bionic-updates/main i386 Packages [565 kB]
Get:7 http://us.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [696 kB]
Get:8 http://us.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [980 kB]
Get:9 http://us.archive.ubuntu.com/ubuntu bionic-updates/universe i386 Packages [962 kB]
Fetched 3,456 kB in 2s (2,160 kB/s)                      
Reading package lists... Done


then...
`sudo apt-get install sqlite3 libsqlite3-dev`

output:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
sqlite3 is already the newest version (3.22.0-1ubuntu0.1).
The following packages were automatically installed and are no longer required:
  gyp javascript-common libc-ares2 libhttp-parser2.7.1 libjs-async
  libjs-inherits libjs-jquery libjs-node-uuid libjs-underscore libssl-doc
  libssl1.0-dev libuv1 libuv1-dev node-abbrev node-ansi node-ansi-color-table
  node-archy node-async node-balanced-match node-block-stream
  node-brace-expansion node-builtin-modules node-combined-stream
  node-concat-map node-cookie-jar node-delayed-stream node-forever-agent
  node-form-data node-fs.realpath node-fstream node-fstream-ignore
  node-github-url-from-git node-glob node-graceful-fs node-gyp
  node-hosted-git-info node-inflight node-inherits node-ini
  node-is-builtin-module node-isexe node-json-stringify-safe node-lockfile
  node-lru-cache node-mime node-minimatch node-mkdirp node-mute-stream
  node-node-uuid node-nopt node-normalize-package-data node-npmlog node-once
  node-osenv node-path-is-absolute node-pseudomap node-qs node-read
  node-read-package-json node-request node-retry node-rimraf node-semver
  node-sha node-slide node-spdx-correct node-spdx-expression-parse
  node-spdx-license-ids node-tar node-tunnel-agent node-underscore
  node-validate-npm-package-license node-which node-wrappy node-yallist
  nodejs-doc python-pkg-resources
Use 'sudo apt autoremove' to remove them.
Suggested packages:
  sqlite3-doc
The following NEW packages will be installed:
  libsqlite3-dev
0 upgraded, 1 newly installed, 0 to remove and 8 not upgraded.
Need to get 633 kB of archives.
After this operation, 2,134 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://us.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libsqlite3-dev amd64 3.22.0-1ubuntu0.1 [633 kB]
Fetched 633 kB in 1s (939 kB/s)        
Selecting previously unselected package libsqlite3-dev:amd64.
(Reading database ... 75804 files and directories currently installed.)
Preparing to unpack .../libsqlite3-dev_3.22.0-1ubuntu0.1_amd64.deb ...
Unpacking libsqlite3-dev:amd64 (3.22.0-1ubuntu0.1) ...
Setting up libsqlite3-dev:amd64 (3.22.0-1ubuntu0.1) ...

the next command i did..
`node gekko --config config.js`

output:
internal/modules/cjs/loader.js:628
    throw err;
    ^

Error: Cannot find module '/root/gekko'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by andrew-acpatt** [comment]
@idnr when you ran " node gekko --config config.js" were you in the gekko folder? If not then that's probably why you get "Error: Cannot find module '/root/gekko'"
