### ISSUE TITLE
Wont do sell order, showing "2019-07-28 15:15:41 (INFO):     NOT buying, already exposed"

### ISSUE THREAD

**Issue by smokinamigo-create** [askmike/gekko#2829]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ ] bug report
[ xx] question about the decisions made in the repository

**Action taken** (what you did)
I am using a buysell.js strategy

**Expected result** (what you hoped would happen)
If exposure is >10% and sell price is below candle.close , it should initiate sell order. 

**Actual result** (unexpected outcome)
The logs register "INFO 2019-07-28 15:15:41 (INFO):     NOT buying, already exposed..," then it continues to collect data from gdax showing how many trades are happening , but wont initiate the sell order. Any thoughts why this is happening, I, for the life of me cannot figure out why it wont go to the ELSE IF "sell" loop after it realizes it is exposed. 

The "buy side" works perfectly fine every single time. It is only the "sell" function that is not registering. 

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by smokinamigo-create** [comment]
Anybody having the same issue, this is so frustrating since the code all looks to check out :(  @askmike  @tg44

**Comment by tg44** [comment]
I'm just trying to find out why am I mentioned here :D I don't remember any code I published to this repo modifying buy/sell logic (I'm not even found the file you mentioned.) I think I only found a bug in the pg connector, and add a better slack integration. Honestly no idea what the problem is with this limited information.

**Comment by ksystemsio** [comment]
Same issue, and it is really frustrating. Using neuralnet v2, 240 minutes history, 1 minute candle:

2019-09-29 21:14:36 (DEBUG):    Price = 7938.73, Prediction = 7973.848744331102
2019-09-29 21:15:36 (DEBUG):    Price = 7935.9, Prediction = 7972.802950769497
2019-09-29 21:15:36 (INFO):     NOT buying, already exposed
2019-09-29 21:16:36 (DEBUG):    Price = 7937.45, Prediction = 7971.737467114364
2019-09-29 21:17:36 (DEBUG):    Price = 7938.71, Prediction = 7970.795486360737
