### ISSUE TITLE
cant load the market menu

### ISSUE THREAD

**Issue by stellarossadibelgrado** [askmike/gekko#2835]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ ] bug report

**Action taken** (what you did)
i try to aceed to the importer 

**Expected result** (what you hoped would happen)
i try to selelct the market using the form under the write market 

**Actual result** (unexpected outcome)
there wasnt any form no exchange +, no asset no currencie 

**Other information** 
i cant use gekko at all with this problem. i cant even access to the market form in live trading so im not able to do anything. 
please help me to solve this problem

**Comment by stellarossadibelgrado** [comment]
i found this error in the console

TypeError: Cannot read property 'markets' of undefined
    at a.currencies (marketpicker.vue:74)
    at un.Kw5r.un.get (vue.runtime.esm.js:3138)
    at un.Kw5r.un.evaluate (vue.runtime.esm.js:3245)
    at a.currencies (vue.runtime.esm.js:3503)
    at a.n (marketpicker.vue?d701:1)
    at a.t._render (vue.runtime.esm.js:4540)
    at a.r (vue.runtime.esm.js:2784)
    at un.Kw5r.un.get (vue.runtime.esm.js:3138)
    at un.Kw5r.un.run (vue.runtime.esm.js:3215)
    at tn (vue.runtime.esm.js:2977)
Qt @ vue.runtime.esm.js:1737
Yt @ vue.runtime.esm.js:1728
Jt @ vue.runtime.esm.js:1717
t._render @ vue.runtime.esm.js:4542
r @ vue.runtime.esm.js:2784
Kw5r.un.get @ vue.runtime.esm.js:3138
Kw5r.un.run @ vue.runtime.esm.js:3215
tn @ vue.runtime.esm.js:2977
(anonymous) @ vue.runtime.esm.js:1833
ie @ vue.runtime.esm.js:1754
Promise.then (async)
te @ vue.runtime.esm.js:1802
le @ vue.runtime.esm.js:1846
on @ vue.runtime.esm.js:3064
Kw5r.un.update @ vue.runtime.esm.js:3205
Kw5r.pt.notify @ vue.runtime.esm.js:693
set @ vue.runtime.esm.js:1010
Rt @ vue.runtime.esm.js:1032
D @ mutations.js:9
(anonymous) @ vuex.esm.js:697
(anonymous) @ vuex.esm.js:389
(anonymous) @ vuex.esm.js:388
L2JU.d._withCommit @ vuex.esm.js:495
L2JU.d.commit @ vuex.esm.js:387
commit @ vuex.esm.js:335
(anonymous) @ sync.js:41
(anonymous) @ ajax.js:14
_.callback @ client.js:611
(anonymous) @ client.js:438
r.emit @ index.js:133
e.onreadystatechange @ client.js:705
XMLHttpRequest.send (async)
_._end @ client.js:772
_.end @ client.js:676
l @ ajax.js:29
_ @ sync.js:40
y @ sync.js:52
w @ init.js:13
S.b.onopen @ ws.js:39
(anonymous) @ reconnecting-websocket.min.js:2
h.onopen @ reconnecting-websocket.min.js:2

**Comment by stellarossadibelgrado** [comment]
![cattura gekko](https://user-images.githubusercontent.com/43149050/63282490-32de3700-c2af-11e9-872c-a57aaaa1fb84.PNG)

**Comment by stellarossadibelgrado** [comment]
please thats a good software i want to use it help me

**Comment by ArashDerArcher** [comment]
install exchange dependencies

cd exchange
npm i --only=production

**Comment by stellarossadibelgrado** [comment]
![cattura cmd](https://user-images.githubusercontent.com/43149050/63526292-716a3080-c4ff-11e9-940f-bbf2ba822510.PNG)
i got this error when i tried to download the exchange dependencies

**Comment by ArashDerArcher** [comment]
sry there was a typo in my answer
its: --only=production
(no space between tags - -)
read the documentation going forwards

**Comment by stellarossadibelgrado** [comment]
i read everything and as you can see in the photo i tried in the right way the second time but i continue getting the same error.

**Comment by sasanikolic90** [comment]
@stellarossadibelgrado As mentioned above, you (also) need to be inside the exchange folder and do `yarn --only=production`. 

So, try running `yarn --only=production` inside /gekko and /gekko/exchange. That's not specified in the documentation but worked for me.
