### ISSUE TITLE
gekko config.trader doesn't work and RSI strategy problems

### ISSUE THREAD

**Issue by Claudio-F** [askmike/gekko#2838]
**I'm submitting a ...**
[X] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Running gekko with command line and UI

**Expected result** (what you hoped would happen)
Run simple RSI strategy

**Actual result** (unexpected outcome)
I cannot run gekko with command line, in the config file if i set config.trader = {enabled: true...} i get error:
Error:

Do you understand what Gekko will do with your money? Read this first:

https://github.com/askmike/gekko/issues/201 

Meta debug info:

Gekko version: v0.6.8
Nodejs version: v12.9.0

It works with gekko --ui only.
Moreover, the RSI signals do not seem to coincide with those of the exchange! Gekko shows Different values!!! Then wrong long - short signals!!! :( Please help me, thanks.

**Other information** 
I use Poloniex exchange. I run gekko with a mac (macOS Mojave) and hp with Linux(mate). Same result.
Gekko version: v0.6.8
Nodejs version: v12.9.0

**Comment by adpinter** [comment]
Hello, Claudio,

I´ve had the same problem. When I am using UI there´s no problem, but using CLI it works just in backtest. When I set trader enable I get the same error.
Did you solve the problem or it remains ??

**Comment by dzfweb** [comment]
+1

**Comment by dzfweb** [comment]
@adpinter @Claudio-F 

the problem is very easy to solve, in my case i just setted to true this config at config.js

`config['I understand that Gekko only automates MY OWN trading strategies'] = true;`
