### ISSUE TITLE
Coinbase

### ISSUE THREAD

**Issue by screwfaze** [askmike/gekko#2844]
Is there planned support for Coinbase Exchange?

Thanks

**Comment by screwfaze** [comment]
Never mind I am using gdax.

Thanks

**Comment by Akagutz** [comment]
@screwfaze I think your question is one I'm also interested in. Is there going to be a support for coinbase??

**Comment by VikingTristan** [comment]
> @screwfaze I think your question is one I'm also interested in. Is there going to be a support for coinbase??

gdax is coinbase pro

**Comment by WyattSanders** [comment]
because they've changed the name from GDAX to Coinbase Pro, can anyone confirm that the API works the same, and is still working?

**Comment by askmike** [comment]
I am unfortunately not maintaining this project anymore. I'm marking the whole repo as read only.

Read more here: https://medium.com/@gekkoplus/archiving-open-source-gekko-dba02e6efc7
