### ISSUE TITLE
help with back testing not giving an out put

### ISSUE THREAD

**Issue by Redtile** [askmike/gekko#2846]
Hi, I am really not great when it comes to trying to troubleshoot things like this and I am honestly not even sure this is the right place for it but when I try to do a large back test like 1 day worth of training data in 1 minute candles (1440 total candles) the UI gives me the usual thinking about it bars down the bottom of the page and the cmd prompt tells me the request has been sent but it doesnt give me an output or results, I have tried to increase the memory it has access to and that hasn't made a difference and in task manager the node.js process that should be computing it looks like it is doing so but I haven't got a result out of it as of yet and it has been running for over an hour, I know it isn't a hardware issue as I have a very high end system so I would like to know what I can try next, I am using a neural network as shown by siraj raval and I don't understand much of node.js unfortunately, if you need further information please can you tell me how I can gather it up for you so I can post it here thanks in advance.

**Comment by IAMtheIAM** [comment]
What do you mean by `I am using a neural network`? Have you tried running the backtest regularly, via the UI? How about backtesting via the CLI?

Did you open the developer console (F12) and see on the `console` tab if there are any errors getting thrown on the page? 

You should post screenshots, error messages, or anything that can be helpful diagnosing your issue.
