### ISSUE TITLE
Unable to import data 

### ISSUE THREAD

**Issue by shashrvacai** [askmike/gekko#2847]
Hi, I managed to install and start Gekko. I was working fine, till one day the Ui of Gekko did not show the importer properly (attached image)
<img width="996" alt="Screen Shot 2019-09-14 at 6 03 05 PM" src="https://user-images.githubusercontent.com/20447610/64915383-3502ac80-d71a-11e9-988e-6f1d96441418.png">

I tried to reinstall .. so I removed Gekko and re-did the process. 
the terminal would hang when I would try to install the broker dependencies .(attached image)
<img width="480" alt="Screen Shot 2019-09-14 at 6 01 57 PM" src="https://user-images.githubusercontent.com/20447610/64915387-68ddd200-d71a-11e9-9748-86cfacdde946.png">

any suggestions?

**Comment by warfx2** [comment]
I managed to make mine work by installing lodash 2.0 ...
npm install lodash@2.x

**Comment by ardialamwijaya** [comment]
any update for this issue? i did the npm install lodash but still nothing for me

**Comment by IAMtheIAM** [comment]
I suggest you go to `package.json` and remove all `^` and any "~" if they are there, so this ensures you use a FIXED version of the packages listed. Otherwise, it will take a newer version as they are released and it can break many things. `ta-lib` for example doesn't work on the new minor version released, so removing the `^` fixes that.

**Comment by hesa2020** [comment]
I am having the same issue and tried the aboves suggestions.

Edit: This fixed it for me: https://github.com/askmike/gekko/issues/2835#issuecomment-523138722

**Comment by askmike** [comment]
I am unfortunately not maintaining this project anymore. I'm marking the whole repo as read only.

Read more here: https://medium.com/@gekkoplus/archiving-open-source-gekko-dba02e6efc7
