### ISSUE TITLE
gekko CLI

### ISSUE THREAD

**Issue by bmili** [askmike/gekko#2854]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ ] bug report
[x ] question about the decisions made in the repository

**Action taken** (what you did)
node gekko -config config.js -backtest

**Expected result** (what you hoped would happen)
backtest results

**Actual result** (unexpected outcome)

 error: unknown option `-n'

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
gekko UI is running in background.
sudo pm2 start gekko.js -f --name ui -x -- --ui --config config.js

But when I run gekko CLI I get the error:

unknown option `-n'

**Comment by adpinter** [comment]
pm2 and gekko have -- options, so you have to isolate the gekko command. Try to start backtest with another background process, like this:
pm2 start "node gekko --config config.js --backtest" --name aName

**Comment by bmili** [comment]
How can I add bchusdt ticker.?  Update-binance never adds it.

Regards

V pon., 16. dec. 2019 15:18 je oseba stale[bot] <notifications@github.com>
napisala:
