### ISSUE TITLE
Gdax (pro coinbase) - HTTP 429 Error: Public rate limit exceeded

### ISSUE THREAD

**Issue by kuceraf** [askmike/gekko#2859]
**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Running live Gekko (as tradebot) on gdax exchange from Gekko UI. When my trading strategy start executing order it fails with this error:
Error: HTTP 429 Error: Public rate limit exceeded
(full log: 
[gekko_error_log.txt](https://github.com/askmike/gekko/files/3726097/gekko_error_log.txt)
)

**Expected result** (what you hoped would happen)
Gekko place order on Gdax market

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
Gdax (pro coinbase) probably change its API and gdax.js wrapper needs to be fixed.
Running Gekko in paper trader mode on Gdax market works fine.
I'm using version: 0.6.8

**Comment by IAMtheIAM** [comment]
The error is clear, you've exceeded the public rate limit. That means you have too many bots running on the same exchange, or are trying to run the bot and importer at the same time, or sometimes the importer does this if importing a lot of data.

Try running only 1 bot per exchange and see if it works. 

P.S The error log you attached was only a partial log, so I couldn't see what came before that rate limit error. It's best to post a full log.

**Comment by kuceraf** [comment]
Thanks for the reply. I've tried to run it again and it seems to be working.
