### ISSUE TITLE
I cant run the importer, and having no error

### ISSUE THREAD

**Issue by ardialamwijaya** [askmike/gekko#2863]
**I'm submitting a bug where the importer dropdown is not working on Windows 10**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** 
- i create folder on D:/askmike/gekko
- i clone the reppo
- i did npm install
- i did node gekko --ui
- i went to local data, try the importer and didnt have the combobox
- i googled about the bug
- i did cd D:/askmike/gekko/exchange and npm i --only=production, still failed
- i googled again
- i did cd D:/askmike/gekko npm i --only=production, still failed
- i googled again
- i did npm install lodash@2x,still failed

(image gekko1.png and gekko2.png)
![gekko2](https://user-images.githubusercontent.com/6219924/67682620-6251a400-f9c2-11e9-839a-e08ad39c6ee1.png)
![gekko1](https://user-images.githubusercontent.com/6219924/67682621-62ea3a80-f9c2-11e9-8971-9d4a7b02854e.png)

it gives me no error, just blank importer (gekko4.png)
![gekko4](https://user-images.githubusercontent.com/6219924/67682795-bb213c80-f9c2-11e9-8f51-504e98cfe9f8.png)

do i need to provide api key? but when i want to provide api key for binance, i can only provide it with bitfinex api, and it doesnt have any api key for other exchange (image gekko3.png), is it just me or thats an expected result?
![gekko3](https://user-images.githubusercontent.com/6219924/67682615-61b90d80-f9c2-11e9-9907-64f56c0a38ab.png)

**Expected result**  i want to be able to choose my exchange (such as binance)

**Actual result** i can not choose anything

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by IAMtheIAM** [comment]
It appears your `console` is not actually showing the console messages because you have the `what's new` tab highlighted. X that or click `console` to the left of it and see if there are any errors. 

I'm almost certain that there will be errors since your UI is not loading correctly.

It is not necessary to provide an API key for using the importer since those are publicly available APIs

**Comment by ardialamwijaya** [comment]
i solved this issue by installing gekko using docker. and since im in windows 10, i need to switch my docker container to linux container. and its good to go. hope it helps others for those who have the same issue with me
