### ISSUE TITLE
Access previous EMA

### ISSUE THREAD

**Issue by pl0o0f** [askmike/gekko#2875]
Hi there,

I'm trying to access the previous EMA for a calculation purpose.
I have the EMA but I also want to have access to the EMA that happened previously.

Is there a way to get access to this?

UPDATE: my bad, problem resolved.

**Comment by askmike** [comment]
I am unfortunately not maintaining this project anymore. I'm marking the whole repo as read only.

Read more here: https://medium.com/@gekkoplus/archiving-open-source-gekko-dba02e6efc7
