### ISSUE TITLE
Cant install on windows

### ISSUE THREAD

**Issue by mad-tunes** [askmike/gekko#2876]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[*] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Trying to follow this to install on Windows Server 2019: https://gekko.wizb.it/docs/installation/installing_gekko_on_windows.html
[#2626 ](https://github.com/askmike/gekko/issues/2626) got sqlite3 installed but then running 
cd exchange
npm install --only=production
leads to errors about files in gekko\exchange\node_modules\.staging missing.

**Expected result** (what you hoped would happen)
No errors, working Gekko

**Actual result** (unexpected outcome)
If I carry on, Gekko will open but doesnt show any exchanges when trying to get their data.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

[2019-12-20T13_27_54_909Z-debug.log](https://github.com/askmike/gekko/files/3988486/2019-12-20T13_27_54_909Z-debug.log)

**Comment by mad-tunes** [comment]
Not sure whether to remove this or add what got it going..
In case it's of use:

Removing this line:
`"kraken-api": "askmike/npm-kraken-api#a69dfb3eb296b9c795cfa48dd31edcdc1b3d5398",`
from \exchange\package.json got it going

Thanks @Astrali

**Comment by Astrali** [comment]
you are welcome @mad-tunes :)

**Comment by askmike** [comment]
I am unfortunately not maintaining this project anymore. I'm marking the whole repo as read only.

Read more here: https://medium.com/@gekkoplus/archiving-open-source-gekko-dba02e6efc7
