### ISSUE TITLE
Windows WSL Related Setup

### ISSUE THREAD

**Issue by Griodin** [askmike/gekko#2878]
**I'm submitting a ...**
Possible update to Windows 10 Windows Subsystem for Linux (WSL) Related Setup steps or added information.  You may use this or not as you desire.

**Action taken** (what you did)
I was only able to get this to work by changing the version of node to 8.11.3.  I also had too make sure AVG Antivirus/Firewall/Windows Firewall settings allowed bash.exe/port 3000 TCP/UDP traffic. Unfortunately, I was all over the place resolving this issue so I can't provide steps.  The following are the steps I took to get things working that I was able to record, just in case you see some ideas to add to the documentation.  

sudo apt-get update
_**nvm use 8.11.3**_
sudo apt-get install -y nodejs
sudo apt-get install -y build-essential

sudo apt-get install git

git clone git://github.com/askmike/gekko.git
cd gekko
npm install --only=production
cd exchange
npm install --only=production
cd ..

**Not related but notable mentions (in my opinion):**

**- VcXsrv, Windows X Server**
https://sourceforge.net/projects/vcxsrv/
Allows opening sublime text editor (or other gui linux applications) in Windows via X Server and connect directly to the Linux folders for editing directly.  Without this or another solution, you may have issues editing files.

wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
sudo apt-get install apt-transport-https
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
sudo apt-get update
sudo apt-get install sublime-text

DISPLAY=127.0.0.1:0.0
export DISPLAY
subl

Once running, for clipboard between Windows and Sublime you may need to disable the "Clipboard may use PRIMARY selection" setting in VxXsrv. Taskbar Notification > Right Click "X" icon > 

**- Forgotten password to WSL:**
https://winaero.com/blog/reset-password-wsl-linux-distro-windows-10/
From DOS
ubuntu config --default-user root
ubuntu.exe # (to run WSL in the current Windows command prompt)
whoami # (to see who I'm currently logged in as)
tail -3 /etc/passwd # (to see the last three users added to the Ubuntu system)
passwd user01 # (to change the password for user01)
exit # (to exit WSL)
ubuntu config --default-user user01 # (to set the default user for the WSL terminal)

**- WSL2**
There is experimental WSL2 but this requires non-released version of Windows as of 12/22/2019.  This version allows mapping with windows for using VSCode and other editors.
https://docs.microsoft.com/en-us/windows/wsl/wsl2-install

**Comment by askmike** [comment]
I am unfortunately not maintaining this project anymore. I'm marking the whole repo as read only.

Read more here: https://medium.com/@gekkoplus/archiving-open-source-gekko-dba02e6efc7
