### ISSUE TITLE
TypeError: _.last(...).join is not a function

### ISSUE THREAD

**Issue by veffisot** [askmike/gekko#2882]
**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Prepare Windows 10 to install gekko from git.

**Expected result** (what you hoped would happen)
pi@DESKTOP-xxx:/mnt/c$ git clone git://github.com/askmike/gekko.git -b stable
Cloning into 'gekko'...
remote: Enumerating objects: 15192, done.
remote: Total 15192 (delta 0), reused 0 (delta 0), pack-reused 15192
Receiving objects: 100% (15192/15192), 5.90 MiB | 7.77 MiB/s, done.
Resolving deltas: 100% (9967/9967), done.

------------------------------------

pi@DESKTOP-xxx:/mnt/c$ cd gekko/
pi@DESKTOP-xxx:/mnt/c/gekko$ sudo npm install --only=production

> sqlite3@4.0.4 install /mnt/c/gekko/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
[sqlite3] Success: "/mnt/c/gekko/node_modules/sqlite3/lib/binding/node-v57-linux-x64/node_sqlite3.node" is installed via remote
added 213 packages from 175 contributors and audited 520 packages in 11.24s
found 12 vulnerabilities (1 low, 1 moderate, 10 high)
  run `npm audit fix` to fix them, or `npm audit` for details

------------------------------------

pi@DESKTOP-xxx:/mnt/c/gekko$ sudo npm audit fix

> sinon@4.5.0 postinstall /mnt/c/gekko/node_modules/sinon
> node scripts/support-sinon.js

Have some ❤️ for Sinon? You can support the project via Open Collective:
 > https://opencollective.com/sinon/donate

added 37 packages from 751 contributors and updated 3 packages in 6.572s
fixed 9 of 12 vulnerabilities in 520 scanned packages
  1 package update for 3 vulnerabilities involved breaking changes
  (use `npm audit fix --force` to install breaking changes; or refer to `npm audit` for steps to fix these manually)

------------------------------------

pi@DESKTOP-xxx:/mnt/c/gekko$ sudo npm audit fix --force
npm WARN using --force I sure hope you know what you are doing.
+ lodash@4.17.15
updated 1 package in 2.275s
fixed 3 of 3 vulnerabilities in 528 scanned packages
  1 package update for 3 vulnerabilities involved breaking changes
  (installed due to `--force` option)
  
------------------------------------
  
pi@DESKTOP-xxx:/mnt/c/gekko$ cd exchange/
pi@DESKTOP-xxx:/mnt/c/gekko/exchange$ sudo npm install --only=production

> websocket@1.0.26 install /mnt/c/gekko/exchange/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/mnt/c/gekko/exchange/node_modules/websocket/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory '/mnt/c/gekko/exchange/node_modules/websocket/build'
added 115 packages from 165 contributors and audited 400 packages in 10.797s
found 10 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
  
------------------------------------  
  
pi@DESKTOP-xxx:/mnt/c/gekko/exchange$ sudo npm audit fix
+ lodash@4.17.15
updated 1 package in 2.172s
fixed 10 of 10 vulnerabilities in 400 scanned packages

------------------------------------
pi@DESKTOP-xxx:/mnt/c/gekko/exchange$ cd ..

**Actual result** (unexpected outcome)
pi@DESKTOP-xxx:/mnt/c/gekko$ node gekko --ui

    ______   ________  __    __  __    __   ______
   /      \ /        |/  |  /  |/  |  /  | /      \
  /$$$$$$  |$$$$$$$$/ $$ | /$$/ $$ | /$$/ /$$$$$$  |
  $$ | _$$/ $$ |__    $$ |/$$/  $$ |/$$/  $$ |  $$ |
  $$ |/    |$$    |   $$  $$<   $$  $$<   $$ |  $$ |
  $$ |$$$$ |$$$$$/    $$$$$  \  $$$$$  \  $$ |  $$ |
  $$ \__$$ |$$ |_____ $$ |$$  \ $$ |$$  \ $$ \__$$ |
  $$    $$/ $$       |$$ | $$  |$$ | $$  |$$    $$/
   $$$$$$/  $$$$$$$$/ $$/   $$/ $$/   $$/  $$$$$$/

        Gekko v0.6.8
        I'm gonna make you rich, Bud Fox.

Serving Gekko UI on http://localhost:3000/

Something went wrong when trying to open your web browser. UI is running on http://localhost:3000/.
  <-- GET /api/imports
  --> GET /api/imports 200 5ms 2b
  <-- GET /api/apiKeys
  --> GET /api/apiKeys 200 1ms 2b
  <-- GET /api/exchanges
  <-- GET /api/gekkos
  --> GET /api/gekkos 200 5ms 24b
  xxx GET /api/exchanges 500 11ms -

  TypeError: _.last(...).join is not a function
      at exchangesDir.filter.f (/mnt/c/gekko/web/routes/exchanges.js:17:31)
      at Array.filter (<anonymous>)
      at Object.module.exports (/mnt/c/gekko/web/routes/exchanges.js:17:6)
      at module.exports.next (<anonymous>)
      at Object.dispatch (/mnt/c/gekko/node_modules/koa-router/lib/router.js:334:5)
      at dispatch.next (<anonymous>)
      at onFulfilled (/mnt/c/gekko/node_modules/co/index.js:65:19)
      at <anonymous>

------------------------------------

  <-- GET /api/configPart/performanceAnalyzer
  <-- GET /api/strategies
  xxx GET /api/strategies 500 2ms -

  TypeError: _.last(...).join is not a function
      at strategyDir.filter.f (/mnt/c/gekko/web/routes/strategies.js:9:31)
      at Array.filter (<anonymous>)
      at Object.module.exports (/mnt/c/gekko/web/routes/strategies.js:9:6)
      at module.exports.next (<anonymous>)
      at Object.dispatch (/mnt/c/gekko/node_modules/koa-router/lib/router.js:334:5)
      at dispatch.next (<anonymous>)
      at onFulfilled (/mnt/c/gekko/node_modules/co/index.js:65:19)
      at <anonymous>

  <-- GET /api/configPart/paperTrader
  --> GET /api/configPart/performanceAnalyzer 200 64ms 144b
  --> GET /api/configPart/paperTrader 200 16ms 132b

**Other information** 
I tried to reinstall gekko, performed the audit fix and still had the same error.

pi@DESKTOP-xxx:/mnt/c/gekko$ npm -v
6.13.4

pi@DESKTOP-xxx:/mnt/c/gekko$ nodejs -v
v8.17.0

pi@DESKTOP-xxx:/mnt/c/gekko$ npm list | grep lodash
│ └── lodash@4.17.15
│ ├── lodash@4.17.15
├── lodash@4.17.15
│ │ └── lodash@4.17.15
│ ├── lodash.get@4.4.2
│ │ │   └── lodash@4.17.15

**Comment by askmike** [comment]
I am unfortunately not maintaining this project anymore. I'm marking the whole repo as read only.

Read more here: https://medium.com/@gekkoplus/archiving-open-source-gekko-dba02e6efc7
