### ISSUE TITLE
Cannot trade on coinfalcon

### ISSUE THREAD

**Issue by PGTBoos** [askmike/gekko#2888]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ x] bug report
[ ] question about the decisions made in the repository

There is no data import happening using the standard version of gekko 
**Action taken** (what you did)
try to import data

**Expected result** (what you hoped would happen)
get the data, and be able to trade with coinfalcon

**Actual result** (unexpected outcome)
it halts at around 86% or so and it never finishes

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

There have bene problems in the past with bitfalcon, may it be related to it
They have a doc to their API online, though i dont see overlap in it yet.
https://docs.coinfalcon.com/reference/markets#getmarketsmarkettrades

**Comment by askmike** [comment]
I am unfortunately not maintaining this project anymore. I'm making the whole repo as read only.

Read more here: https://medium.com/@gekkoplus/archiving-open-source-gekko-dba02e6efc7
