### ISSUE TITLE
Gekko crashes when processing bitfinex trades

### ISSUE THREAD

**Issue by zxpectre** [askmike/gekko#289]
Gekko recently crashed while processing trades using bitfinex exchange.
I'm using:
* Lubuntu 64bits
* node v0.10.25,
* Gekko v0.1.2,
* config.js has no custom values other than api keys and exchange setup.

> ... 
> 2015-11-17 15:05:29 (DEBUG):	Processed trades, sleeping for a minute...
> 2015-11-17 15:06:17 (DEBUG):	Requested BTC/USD trade data from Bitfinex ...
> 2015-11-17 15:06:22 (DEBUG):	Fetched 1000 new trades, from 2015-11-17 13:31:35 UTC to 2015-11-17 15:06:18 UTC
> 2015-11-17 15:06:22 (DEBUG):	minimum trade treshold: 2015-11-17 15:01:01 UTC
> 2015-11-17 15:06:22 (DEBUG):	processing 36 trade(s)
> 2015-11-17 15:06:22 (DEBUG):	from 2015-11-17T15:01:12+00:00 to > 2015-11-17T15:06:18+00:00
> c [ { s: 903,
>     o: 334.35,
>     h: 334.79,
>     l: 334.35,
>     c: 334.79,
>     v: 22.57981056,
>     p: 334.7480368490036 },
>   { s: 904,
>     o: 334.7,
>     h: 334.7,
>     l: 334.6,
>     c: 334.6,
>     v: 1.21754825,
>     p: 334.69815598683664 },
>   { s: 901,
>     o: 334.23,
>     h: 334.25,
>     l: 333.97,
>     c: 334.25,
>     v: 2.1770676399999997,
>     p: 334.09331280308777 },
>   { s: 902,
>     o: 334.32,
>     h: 334.32,
>     l: 334.05,
>     c: 334.05,
>     v: 1.6808620499999998,
>     p: 334.22437426569303 },
>   { s: 903,
>     o: 334.35,
>     h: 334.79,
>     l: 334.09,
>     c: 334.09,
>     v: 14.816453529999999,
>     p: 334.65754964583624 },
>   { s: 906,
>     o: 334.53,
>     h: 334.56,
>     l: 334.43,
>     c: 334.43,
>     v: 17.5,
>     p: 334.490261882 } ] s { s: 903,
>   o: 334.35,
>   h: 334.79,
>   l: 334.35,
>   c: 334.79,
>   v: 22.57981056,
>   p: 334.7480368490036 } e undefined
> 
> Weird error 2

**Comment by askmike** [comment]
this is fixed in 0.2.
