### ISSUE TITLE
Sqlite issue, Gekko no finding sqlite on live trader start attempt.

### ISSUE THREAD

**Issue by JosephEBarker** [askmike/gekko#2892]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Fresh install on Raspberry pi 3
Followed the instructions on the 
https://gekko.wizb.it/docs/installation/installing_gekko_on_raspberry_pi_2_or_3.html
page
I admit I am a big ubuntu newbie, but I have been searching the web for the last 2 weeks to try to fix this, even tried different OS's and node versions/ sqlite install commands. I am totally stumped.

**Expected result** (what you hoped would happen)
Gekko throws sqlite error when starting and then wehn I try to trouble shoot with force install of dependencies I get this long bunch of errors.

**Actual result** (unexpected outcome)
Error on Sqlite install:

pi@raspberrypi:~ $ cd gekko
pi@raspberrypi:~/gekko $ npm i sqlite3 --build-from-source

> sqlite3@4.1.1 install /home/pi/gekko/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
make: Entering directory '/home/pi/gekko/node_modules/sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3300100/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3300100/sqlite3.o
Release/obj/gen/sqlite-autoconf-3300100/sqlite3.c: In function ‘strftimeFunc’:
Release/obj/gen/sqlite-autoconf-3300100/sqlite3.c:14234:27: warning: cast between incompatible function types from ‘int (*)(void *)’ to ‘void (*)(void *)’ [-Wcast-function-type]
 #define SQLITE_DYNAMIC   ((sqlite3_destructor_type)sqlite3MallocSize)
                           ^
Release/obj/gen/sqlite-autoconf-3300100/sqlite3.c:22212:52: note: in expansion of macro ‘SQLITE_DYNAMIC’
                       z==zBuf ? SQLITE_TRANSIENT : SQLITE_DYNAMIC);
                                                    ^~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3300100/sqlite3.c: In function ‘sqlite3ErrorWithMsg’:
Release/obj/gen/sqlite-autoconf-3300100/sqlite3.c:14234:27: warning: cast between incompatible function types from ‘int (*)(void *)’ to ‘void (*)(void *)’ [-Wcast-function-type]
 #define SQLITE_DYNAMIC   ((sqlite3_destructor_type)sqlite3MallocSize)
                           ^
Release/obj/gen/sqlite-autoconf-3300100/sqlite3.c:30555:54: note: in expansion of macro ‘SQLITE_DYNAMIC’
     sqlite3ValueSetStr(db->pErr, -1, z, SQLITE_UTF8, SQLITE_DYNAMIC);
                                                      ^~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3300100/sqlite3.c: In function ‘sqlite3VdbeMemSetStr’:
Release/obj/gen/sqlite-autoconf-3300100/sqlite3.c:14234:27: warning: cast between incompatible function types from ‘int (*)(void *)’ to ‘void (*)(void *)’ [-Wcast-function-type]
 #define SQLITE_DYNAMIC   ((sqlite3_destructor_type)sqlite3MallocSize)
                           ^
Release/obj/gen/sqlite-autoconf-3300100/sqlite3.c:75784:15: note: in expansion of macro ‘SQLITE_DYNAMIC’
     if( xDel==SQLITE_DYNAMIC ){
               ^~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3300100/sqlite3.c: In function ‘valueFromExpr’:
Release/obj/gen/sqlite-autoconf-3300100/sqlite3.c:14234:27: warning: cast between incompatible function types from ‘int (*)(void *)’ to ‘void (*)(void *)’ [-Wcast-function-type]
 #define SQLITE_DYNAMIC   ((sqlite3_destructor_type)sqlite3MallocSize)
                           ^
Release/obj/gen/sqlite-autoconf-3300100/sqlite3.c:76190:55: note: in expansion of macro ‘SQLITE_DYNAMIC’
       sqlite3ValueSetStr(pVal, -1, zVal, SQLITE_UTF8, SQLITE_DYNAMIC);
                                                       ^~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3300100/sqlite3.c:14234:27: warning: cast between incompatible function types from ‘int (*)(void *)’ to ‘void (*)(void *)’ [-Wcast-function-type]
 #define SQLITE_DYNAMIC   ((sqlite3_destructor_type)sqlite3MallocSize)
                           ^
Release/obj/gen/sqlite-autoconf-3300100/sqlite3.c:76238:29: note: in expansion of macro ‘SQLITE_DYNAMIC’
                          0, SQLITE_DYNAMIC);
                             ^~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3300100/sqlite3.c: In function ‘sqlite3VdbeExec’:
Release/obj/gen/sqlite-autoconf-3300100/sqlite3.c:91559:38: warning: cast between incompatible function types from ‘int (*)(u32,  void *, void *, void *)’ {aka ‘int (*)(unsigned int,  void *, void *, void *)’} to ‘void (*)(void *, const char *)’ [-Wcast-function-type]
       void (*x)(void*,const char*) = (void(*)(void*,const char*))db->xTrace;
                                      ^
Release/obj/gen/sqlite-autoconf-3300100/sqlite3.c: In function ‘printfFunc’:
Release/obj/gen/sqlite-autoconf-3300100/sqlite3.c:14234:27: warning: cast between incompatible function types from ‘int (*)(void *)’ to ‘void (*)(void *)’ [-Wcast-function-type]
 #define SQLITE_DYNAMIC   ((sqlite3_destructor_type)sqlite3MallocSize)
                           ^
Release/obj/gen/sqlite-autoconf-3300100/sqlite3.c:114219:25: note: in expansion of macro ‘SQLITE_DYNAMIC’
                         SQLITE_DYNAMIC);
                         ^~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3300100/sqlite3.c: In function ‘generateColumnNames’:
Release/obj/gen/sqlite-autoconf-3300100/sqlite3.c:14234:27: warning: cast between incompatible function types from ‘int (*)(void *)’ to ‘void (*)(void *)’ [-Wcast-function-type]
 #define SQLITE_DYNAMIC   ((sqlite3_destructor_type)sqlite3MallocSize)
                           ^
Release/obj/gen/sqlite-autoconf-3300100/sqlite3.c:127513:58: note: in expansion of macro ‘SQLITE_DYNAMIC’
         sqlite3VdbeSetColName(v, i, COLNAME_NAME, zName, SQLITE_DYNAMIC);
                                                          ^~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3300100/sqlite3.c:14234:27: warning: cast between incompatible function types from ‘int (*)(void *)’ to ‘void (*)(void *)’ [-Wcast-function-type]
 #define SQLITE_DYNAMIC   ((sqlite3_destructor_type)sqlite3MallocSize)
                           ^
Release/obj/gen/sqlite-autoconf-3300100/sqlite3.c:127520:52: note: in expansion of macro ‘SQLITE_DYNAMIC’
       sqlite3VdbeSetColName(v, i, COLNAME_NAME, z, SQLITE_DYNAMIC);
                                                    ^~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3300100/sqlite3.c: In function ‘sqlite3InvokeBusyHandler’:
Release/obj/gen/sqlite-autoconf-3300100/sqlite3.c:157821:12: warning: cast between incompatible function types from ‘int (*)(void *, int)’ to ‘int (*)(void *, int,  sqlite3_file *)’ {aka ‘int (*)(void *, int,  struct sqlite3_file *)’} [-Wcast-function-type]
     xTra = (int(*)(void*,int,sqlite3_file*))p->xBusyHandler;
            ^
Release/obj/gen/sqlite-autoconf-3300100/sqlite3.c: In function ‘sqlite3_busy_timeout’:
Release/obj/gen/sqlite-autoconf-3300100/sqlite3.c:157899:30: warning: cast between incompatible function types from ‘int (*)(void *, int,  sqlite3_file *)’ {aka ‘int (*)(void *, int,  struct sqlite3_file *)’} to ‘int (*)(void *, int)’ [-Wcast-function-type]
     sqlite3_busy_handler(db, (int(*)(void*,int))sqliteDefaultBusyCallback,
                              ^
Release/obj/gen/sqlite-autoconf-3300100/sqlite3.c: In function ‘sqlite3_trace’:
Release/obj/gen/sqlite-autoconf-3300100/sqlite3.c:158242:16: warning: cast between incompatible function types from ‘void (*)(void *, const char *)’ to ‘int (*)(u32,  void *, void *, void *)’ {aka ‘int (*)(unsigned int,  void *, void *, void *)’} [-Wcast-function-type]
   db->xTrace = (int(*)(u32,void*,void*,void*))xTrace;
                ^

This is where my pi freezes and shuts down. Had this on at least 5-7 different installs of the os and tries with different node versions.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
I am unfortunately not maintaining this project anymore. I'm making the whole repo as read only.

Read more here: https://medium.com/@gekkoplus/archiving-open-source-gekko-dba02e6efc7
