### ISSUE TITLE
gekko/node_modules/btc-e/btc-e.js:114 - TypeError: undefined is not a function

### ISSUE THREAD

**Issue by Nargren** [askmike/gekko#292]
I recently tried enabling the trader on BTC-e after extensively testing and tweaking my settings. I received the following error:

/home/nargren/gekko/node_modules/btc-e/btc-e.js:114
  this.makeRequest('getInfo', {}, callback);
       ^
TypeError: undefined is not a function
    at BTCE.getInfo (/home/nargren/gekko/node_modules/btc-e/btc-e.js:114:8)
    at null._onTimeout (/home/nargren/gekko/exchanges/btce.js:79:25)
    at Timer.listOnTimeout (timers.js:119:15)

I will look into this, however if someone knows the solution, help would be appreciated.

**Comment by n3lz0n** [comment]
i fixed above...now new error....

http://puu.sh/o5r2x/d41c6cf5f2.png

well I hope it was an error so I have some hints how to fix it....this one ^^

thanks in advance :)

**Comment by Nargren** [comment]
How did you manage to fix the above error? Could you please submit a pull request or share the fixed part?

Thanks in advance.

**Comment by n3lz0n** [comment]
the module? npm install poloniex

so I run in.... inside the poloniex folder
http://puu.sh/o5vKz/78b54dcfbc.png

i took them out..... to be under node_modules 

then run the node gekko.... 

then now I hit a dead end.... the author said he got it working..... no im stuck.... LOL...

**Comment by n3lz0n** [comment]
u will encounter many errors its because u need to NPM INSTALL _______ (whatever missing module s like async / emailjs / lodash and so on.....)

now if u could discover how to fix this 

http://puu.sh/o5vSM/c9007dbd17.png

^^^ this is core\TradeFetches.js 

goodluck to us :)

**Comment by askmike** [comment]
It took a while, but should be fixed now.

**Comment by LockjawTheOgre** [comment]
Greetings, 

Have  you already seen the latest news from our dear friend? You've got to see that for sure <http://hope.mxpdx.com/lnlvuvcl>

Warmest, LOCKJAW

**Comment by LockjawTheOgre** [comment]
Hi, 

After a month of   journey I  went back home, it  was a lovely journey, take a  look at some photos of it   <http://ease.gavinpai.com/lnebdiou>

LOCKJAW

**Comment by LockjawTheOgre** [comment]
Hey friend, 

I've created a couple of web-sites and  wanted to ask you  some questions abou them, please answer them here <http://second.wiltonn.com/lnfqfol>.  Thank you!


LOCKJAW
