### ISSUE TITLE
Be able to load historical data

### ISSUE THREAD

**Issue by thiagof** [askmike/gekko#297]
Trading first time with the system should be easier if historical data could be loaded on initial run.

I have tried to make the configuration `exchange.providesHistory` to work with partial success. https://github.com/askmike/gekko/pull/296

CandleManager needs to handle datasets with several days (loaded in a single `getTrades`) , which is not fully supported

**Comment by thiagof** [comment]
The PR is now very functional.

**Comment by askmike** [comment]
is fixed now in 0.2. Curious as to what you think!
