### ISSUE TITLE
Can't to fugure out why i getting this message

### ISSUE THREAD

**Issue by brudazengija** [askmike/gekko#301]
http://prntscr.com/ba8wf0

I was add LSK in exchange.js:
{ pair: ['BTC', 'LSK'], minimalOrder: { amount: 0.01, unit: 'asset' } },
also and asset in same file.

In config.js i was added my poliniex API and Secret key, and when i was try to start it it giving me this error: **either start looping right away (`since`) or first determine starting point dynamically**

**Comment by askmike** [comment]
I am currently working on a different version (see this [branch](https://github.com/askmike/gekko/tree/candle-rewrite)), where this is fixed. Will get to adding all exchanges from current master version in there soon!

**Comment by askmike** [comment]
poliniex monitoring is fixed in that branch [now](https://github.com/askmike/gekko/commit/0da0558424356e412067da7233826c9425f88ac1).
