### ISSUE TITLE
QA and merge commits from other forks

### ISSUE THREAD

**Issue by bugron** [askmike/gekko#306]
I went through all 329 forks and found some of them with extra commits that may be useful but are not included in this repo. Check the appropriate checkbox after merging commits of a fork. Look for any changes in all branches.
Here is the list of those forks.
- [x] https://github.com/carmaa/gekko
- [x] https://github.com/consp/gekko
- [x] https://github.com/djmuk/gekko
- [x] https://github.com/f0ster/gekko
- [x] https://github.com/GoodDragon/gekko
- [x] https://github.com/ingram0529/gekko/tree/ingram0529-patch-1
- [x] https://github.com/johndoe75/gekko/tree/devel
- [x] https://github.com/jimmynguyc/gekko/tree/bitx
- [x] https://github.com/JohnDorien1/gekko
- [x] https://github.com/toomyem/gekko
- [x] https://github.com/kuzetsa/gekko
- [x] https://github.com/mc96107/gekko/tree/backtest
- [x] https://github.com/mlmurray/gekko
- [x] https://github.com/michalkow/gekko
- [x] https://github.com/NathanGRomano/gekko
- [x] https://github.com/NeoBelerophon/gekko
- [x] https://github.com/QBall147/gekko
- [x] https://github.com/robusta/gekko/
- [x] https://github.com/SamThomp/gekko
- [x] https://github.com/siergiej/gekko/tree/develop
- [x] https://github.com/shermdog/gekko/tree/shermdog-local-api
- [x] https://github.com/sschepis/gekko
- [x] https://github.com/stancarney/gekko
- [x] https://github.com/streetlogics/gekko
- [x] https://github.com/thiagof/gekko/tree/exchange-history
- [x] https://github.com/wupeng1211/gekko
- [x] https://github.com/yin/gekko/tree/db-tests
- [x] https://github.com/z3hyn/gekko

In addition to https://github.com/askmike/gekko/issues/216.

**Comment by askmike** [comment]
(Is this an automated issue?)

I'll go through this list, but I am pretty sure most of this commits were made on top of the legacy codebase (currently still master branch).

**Comment by bugron** [comment]
No, it's not. That took me 2 hours.

**Comment by askmike** [comment]
Woow thanks a bunch! I was thinking about doing something similar but the amount of forks (329) kept me away. This list is definitely manageable and I should be able to spot interesting commits quickly (probably bug fixes, new exchanges and new plugins). I'll get around this soon.

**Comment by askmike** [comment]
Went through most of them and definitely found some gems in there :)

**Comment by bugron** [comment]
@askmike that's awesome!
Mike, I wrote a basic bx.in.th exchange API wrapper based on your btcchina package. I have their public API working but I can't test their private API. I'll push it later to GitHub, would you mind to check it out?

**Comment by askmike** [comment]
Great! I'll check it out later (going to bed now). You can also publish it
to npm if you want.

@askmike https://github.com/askmike that's awesome!
Mike, I wrote a basic bx.in.th exchange API wrapper based on your btcchina
package. I have their public API working but I can't test their private
API. I'll push it later to GitHub, would you mind to check it out?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/askmike/gekko/issues/306#issuecomment-224434664, or mute
the thread
https://github.com/notifications/unsubscribe/AA7MD5SvHkTEnXWCtMGcC8DYhvKAwnshks5qJfFygaJpZM4Iu1Jt
.

**Comment by bugron** [comment]
OK, pushed to GitHub, here is the repo https://github.com/bugron/bitexthai, I've published it to npm too, `npm i bitexthai`.

**Comment by Piega** [comment]
Check this repo for other api or implement XChange lib in gekko: https://github.com/timmolter/XChange

**Comment by askmike** [comment]
@Piega that looks great, I'll keep an eye on that. Unfortunately it's a java project which Gekko can't easily use..

**Comment by valeriominetti** [comment]
https://github.com/kuzetsa/gekko has nice additions to cexio.js now underlying api is not restricted to ghs/btc trade and he parametrized  it better removing some hardcoded strings.
his exchanges.js  definition for cexio is still outdated but just adding the right pairs seems to work fine ( tested on gekko stable).

**Comment by askmike** [comment]
done!
