### ISSUE TITLE
Remove config.js from git

### ISSUE THREAD

**Issue by bugron** [askmike/gekko#307]
I've found a fork which exposes sensitive data. So for security reasons I suggest to remove `config.js` from git.
**Option 1**. Rename `config.js` to something like `sample-config.js`, add `config.js` to `.gitignore` and add instructions to actually rename `sample-config.js` to `config.js`. As result, `config.js` is not in git history from now, all changes to config file go to `sample-config.js` and `config.js` will not be commited with sensitive data.
**Option 2**. Simply ignore `config.js`, instead move it's contents to `Configuring_gekko.md` doc file with extra instructions.

**Comment by askmike** [comment]
Great idea!  Also solves the problem of being unable to update gekko (by git pull) if you have an updated config.js.

I'd say option 1 is the way to go. Will get around to this soon (also open for pulls).
