### ISSUE TITLE
Update project's dependencies

### ISSUE THREAD

**Issue by bugron** [askmike/gekko#308]
| Package | Current | Wanted | Latest |
| --- | --- | --- | --- |
| async | 0.2.10 | 0.2.10 | 2.0.0-rc.5 |
| bitstamp | 0.1.10 | 0.1.10 | 0.2.1 |
| btc-e | 0.0.16 | 0.0.16 | 1.0.5 |
| chai | 2.3.0 | 2.3.0 | 3.5.0 |
| lodash | 2.4.2 | 2.4.2 | 4.13.1 |
| moment | 2.4.0 | 2.4.0 | 2.13.0 |
| semver | 2.2.1 | 2.2.1 | 5.1.0 |
| sqlite3 | 3.1.3 | 3.1.3 | 3.1.4 |

**Comment by raffus** [comment]
Hey guys,

I'm running gekko on backtest mode with no problems, until I try to run it in live mode.

When running in live mode, this error keeps comming up:

ekko encountered an error and can't continue

```
Error:

The plugin sqlite adapter expects the module sqlite3 to be installed. However it is not, install it by running: 

        npm install sqlite3@3.1.4 

Meta debug info:

Gekko version: v0.4.10
Nodejs version: v7.10.1
```

And when I try to install sqlite again:

```
# npm install sqlite3@3.1.4 

> sqlite3@3.1.4 install /home/infra/gekko/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

[sqlite3] Success: "/home/infra/gekko/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node" is installed via remote
gekko@0.4.10 /home/infra/gekko
└── sqlite3@3.1.4  invalid

```

This does not happen when running in backtest mode.

Any idea?

Thanks

**Comment by Herklos** [comment]
Hey !

Try to install it by
`npm install sqlite3` 
(newer version)

Worked for me ;)

**Comment by raffus** [comment]
Thanks @Herklos.

The problem was that I was running "nodejs" instead of just "node".

Thanks once again.
BR.
R

**Comment by doepat** [comment]
@raffus i have the same issue probably - what did you change exactly?

**Comment by askmike** [comment]
@doepat the issue with sqlite3? Make sure you have the nodejs LTS version before trying to install it.

**Comment by greenbigfrog** [comment]
@askmike is this still a issue? I believe this can be closed.

**Comment by askmike** [comment]
there are some deps that definitely need updating, like lodash. But I'll track that somewhere outside of this issue, so yes. Let's close it :)
