### ISSUE TITLE
Make running test easier

### ISSUE THREAD

**Issue by bugron** [askmike/gekko#310]
Currently I have to install `make` to run tests but it's easier to move `./node_modules/.bin/mocha -u tdd --reporter spec` to npm scripts. `npm test` will still work and I don't think there will be problems with Travis CI too. Any reason not to do this?

**Comment by askmike** [comment]
No reason that I know of, as long as we can locally test & travis accepts it.

Sidenote: only core functionality of budfox is under test specs right now, we probably need more test coverage.

**Comment by bugron** [comment]
In that case I'll send a PR tomorrow and we'll see if Travis likes this idea.
