### ISSUE TITLE
New Pairs for kraken?

### ISSUE THREAD

**Issue by dennym** [askmike/gekko#318]
There are plenty new pairs in kraken that are not implemented into gekko.
Is it sufficent to just add them in the exchange.js and kraken.js? Or are there other factors to be aware off?

best regards
denym_

**Comment by askmike** [comment]
I am pretty sure that would be sufficient. Will test later today.

**Comment by askmike** [comment]
I have added all markets (contained in [this API call](https://api.kraken.com/0/public/AssetPairs)). I tested a few of these pairs and they all seem to be working (monitoring as well as trading).
