### ISSUE TITLE
Error: Unsupported exchange

### ISSUE THREAD

**Issue by pimbolilu** [askmike/gekko#319]
Hi,

I got this error,
can someone help me with this?

br,
Pim.

/root/gekko/gekko.js:84
  util.die(`Unsupported exchange: ${config.watch.exchange.toLowerCase()}`)
           ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by askmike** [comment]
That is very strange, Gekko is trying to tell you that the exchange you configured is not supported. But while trying to do so it fails for some reason (That check is working fine for me). What version of node are you running (`node -v`)?

**Comment by pimbolilu** [comment]
Hi,

node version = v0.10.25

I have no idea about the problem :/

**Comment by askmike** [comment]
Your version of nodejs is too old. Please download a more recent version (v4 or higher).

**Comment by askmike** [comment]
If you have any problems with supported/unsupported exchanges please comment here. The currently supported exchanges can be found [here](https://github.com/askmike/gekko/blob/0.2/docs/supported_exchanges.md).
