### ISSUE TITLE
Why only one exchange/market restriction?

### ISSUE THREAD

**Issue by tongxiaofeng** [askmike/gekko#356]
Like tradewave.net, all algorithm is implemented in the strategy, which should be written by the user. I don't understand why Gekko chose a different architecture.

**Comment by tongxiaofeng** [comment]
And why the trip advisor only give long or short advice without amount?

**Comment by askmike** [comment]
> Like tradewave.net, all algorithm is implemented in the strategy, which should be written by the user.

What do you mean? You can write your own algorithm, see here how to write your [own trading method](https://github.com/askmike/gekko/blob/stable/docs/internals/trading_methods.md).

> And why the trip advisor only give long or short advice without amount?

If you write your own method you can specify whichever amount you see fit.
