### ISSUE TITLE
hi mike,help me，I want buy 1btc every time ,how config

### ISSUE THREAD

**Issue by wupeng1211** [askmike/gekko#357]
Ths

**Comment by wupeng1211** [comment]
And in method.check = function() {},
How should I get the open,,close,high,low

**Comment by askmike** [comment]
Hey Wupeng,

A very simple trading method that would buy every 10 minutes would be:

Create a new file called `alwaysbuy.js` and place it in `gekko/methods`. Copy the following into it:

```
var config = require('../core/util.js').getConfig();
var settings = config.custom;

// Let's create our own method
var method = {};

// Prepare everything our method needs
method.init = function() {
  this.requiredHistory = 0;
}

// What happens on every new candle?
method.update = function(candle) {
  // nothing!
}

// For debugging purposes.
method.log = function() {
  log.debug('BUY!');
}

// Based on the newly calculated
// information, check if we should
// update or not.
method.check = function() {
  // always advice
  this.advice('long');
}

module.exports = method;
```

This will keep buying Bitcoin (every minute). Note that Gekko always buys the full amount of Bitcoin in the account, so if you want to buy new Bitcoin every x minutes, you have to put new currency in the account every minute (there is a discussion on how to limit the amount Gekko can spend in a single order, see #335.

> And in method.check = function() {}, How should I get the open,,close,high,low

You can access them like this:

```
method.update = function(candle) {
  var open = candle.open;
  var close = candle.close;
  var high = candle.high;
  var low = candle.low;
}
```

**Comment by askmike** [comment]
I am closing this for now, if you need more information just ask :)
