### ISSUE TITLE
 TypeError: fetcher.getTrades is not a function

### ISSUE THREAD

**Issue by wupeng1211** [askmike/gekko#359]
/home/wp/gekko/importers/exchanges/btcc.js:50
    fetcher.getTrades(false, from, handleFirstFetch);
            ^

TypeError: fetcher.getTrades is not a function
    at Object.fetch (/home/wp/gekko/importers/exchanges/btcc.js:50:13)
    at Market.get (/home/wp/gekko/core/markets/importer.js:82:16)
    at bound [as get](/home/wp/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at new Market (/home/wp/gekko/core/markets/importer.js:67:8)
    at /home/wp/gekko/gekko.js:171:18
    at /home/wp/gekko/node_modules/async/lib/async.js:232:13
    at /home/wp/gekko/node_modules/async/lib/async.js:142:25
    at /home/wp/gekko/node_modules/async/lib/async.js:229:17
    at /home/wp/gekko/node_modules/async/lib/async.js:556:34
    at subscribePlugins (/home/wp/gekko/gekko.js:158:3)

**Comment by askmike** [comment]
That is very strange, it is working fine for me. Could you post the full output?

**Comment by antonyx** [comment]
@wupeng1211 i had the same issue, it's related to the version of nodejs you're using. try with nodejs 6, it works.

**Comment by askmike** [comment]
I am unable to reproduce, if you have more information please post here.

**Comment by antonyx** [comment]
@askmike try to reproduce use node v4.x
