### ISSUE TITLE
TypeError: Cannot read property 'port' of undefined

### ISSUE THREAD

**Issue by Pascal66** [askmike/gekko#363]
In my own config in config/ folder, i've : 

config.webserver = {
  enabled: true,
  ws: {
    port: 1338,
    host: 'localhost'

  },
  http: {
    port: 1339,
    host: 'localhost'
  }
}

and this error : 

gekkonew\web\server.js:53
      .replace('{{port}}', serverConfig.ws.port)
                                          ^

TypeError: Cannot read property 'port' of undefined
    at null.<anonymous> (gekkonew\web\server.js:53:43)
    at bound (gekkonew\node_modules\lodash\dist\lodash.js:729:21)
    at FSReqWrap.readFileAfterClose [as oncomplete](fs.js:380:3)

**Comment by hoddy** [comment]
I just tried those ports out on my config, and they seem to work fine. Have you got any other servers assigned to those ports or have you got a previous instance of Gekko running (using those ports)?

Does Gekko work with the default 8080 and 8081?

**Comment by Pascal66** [comment]
Nothing one those ports, and same result with the default port.

**Comment by Pascal66** [comment]
It work with the new sample config instead my own old config.sample

Maybe a typo error somewhere

**Comment by hoddy** [comment]
Ah, brilliant good to hear you found it

**Comment by askmike** [comment]
That error is about not being able to make sense of the port property in the config.

Could you:
- post your whole config (excluding API keys)
- post the output of `node gekko --version`
- post the output of `git log | head -n 3`

Thanks.

**Comment by gunguy79** [comment]
I am getting this exact same error. Below is my config, "node gekko --version" and "git log | head -n 3" outputs:

CONFIG (host.domain.com is not what I'm actually using)
----------
const CONFIG = {
    headless: true,
    api: {
        host: '127.0.0.1',
        port: 3000,
    },
    ui: {
        ssl: true,
        host: 'host.domain.com',
        port: 443,
        path: '/' // change this if you are serving from something like `example.com/gekko`
    },
    adapter: 'sqlite'
}


"node gekko --version"
----------
Gekko version: v0.5.6
Nodejs version: v6.11.1

"git log | head -n 3"
----------
commit b940767faebb3d3684a3e97edb6e2d74c9cc2652
Merge: aaa21f3 e42bcb4
Author: Mike van Rossum <mike@mikevanrossum.nl>
