### ISSUE TITLE
web frontend

### ISSUE THREAD

**Issue by Pascal66** [askmike/gekko#364]
Could someone look at [tribeca frontend](https://github.com/michaelgrosner/tribeca) ?
That can be a good insipration for the future ?

**Comment by askmike** [comment]
I am actually working on a webinterface!

> tribeca is a very low latency cryptocurrency market making trading bot

The thing about Tribeca is that it has an extremely different purpose. Where Tribeca is interested on [market microstructures](https://en.wikipedia.org/wiki/Market_microstructure). Gekko only cares about more macro market information.
- Tribecca can be used for things like arb (I'd say), market making, etc. And the interface is designed towards understanding microstructure market behaviour.
- Gekko can be used to see "the bigger picture", identify long term trends and price movements.

In addition to how Backtesting is handled the interface willl have charts and the like that can help yo understand backtesting data.

**Comment by askmike** [comment]
see #380!
