### ISSUE TITLE
Your local version of Node.js is too old. You have v4.2.1 and you need atleast >=5.0

### ISSUE THREAD

**Issue by ghost** [askmike/gekko#367]
Hey,

after upgrading to last version when i try to start it gives me this erro

Your local version of Node.js is too old. You have v4.2.1 and you need atleast >=5.0

Im running gekko in a RasPi and i cant find "upgrading package" to nodejs 5.0. Can you help me find the solution (one more time) ? :+1: 

Thank U in advance

**Comment by hoddy** [comment]
If you installed Node.js via apt-get then you can run from terminal:
`sudo apt-get update`
Then
`sudo apt-get upgrade`
Type Y when prompted
Otherwise there are plenty of guides to updating via npm like this one:
https://davidwalsh.name/upgrade-nodejs 
Hope this helps

**Comment by askmike** [comment]
@luiscastanheta 

There was a weird bug (see #359) in node pre v5. Also note: I am adding really cool new functionality soon that allows you to "spawn a gekko" per market. This will be the foundation of a webbased shell (finally a decent looking interface). **However for this we need node v6.** So if you are going to compile node, please compile v6+.
