### ISSUE TITLE
error after changing config trader from false to true

### ISSUE THREAD

**Issue by Pascal66** [askmike/gekko#369]
gekkonew\exchanges\btce.js:174
    var trades = _.map(data[this.pair], function(t) {
                           ^
TypeError: Cannot read property 'eth_usd' of undefined

config.trader = {
  enabled: true,

**Comment by askmike** [comment]
could you post your `config.watch` configuration?

**Comment by Pascal66** [comment]
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
//                         WATCHING A MARKET
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// Monitor the live market
config.watch = {
  exchange: 'btce', // see gekko/docs/supported_exchanges.md
  currency: 'USD',
  asset: 'ETH'
}

But i see another error that can explain that : 
Gekko encountered an error and can't continue
Error:
Your local version of Node.js is too old. You have v4.4.7 and you need atleast >=5.0
Meta debug info:
Gekko version: v0.2.5
Nodejs version: v4.4.7

**Comment by askmike** [comment]
Could you please try with a more recent nodejs and see if you get the same error? Thanks!

**Comment by Pascal66** [comment]
2016-07-05 13:48:12 (INFO):     Gekko v0.2.5 started
2016-07-05 13:48:12 (INFO):     I'm gonna make you rich, Bud Fox.

2016-07-05 13:48:12 (INFO):     Setting up Gekko in realtime mode
2016-07-05 13:48:12 (INFO):
2016-07-05 13:48:12 (INFO):     Setting up:
2016-07-05 13:48:12 (INFO):              Candle writer
2016-07-05 13:48:12 (INFO):              Store candles in a database

Gekko encountered an error and can't continue

Error:
The plugin sqlite adapter expects the module sqlite3 to be installed. However it is not, install it by running:
        npm install sqlite3@3.1.3
Meta debug info:

Gekko version: v0.2.5
Nodejs version: v5.11.2-nightly2016062103d36aea4f

tried npm install sqlite3@3.1.3 10 times

tried :+1: C:\Users\Pascal\Desktop\Trading\gekkonew>npm cache clean

C:\Users\Pascal\Desktop\Trading\gekkonew>npm update -g

C:\Users\Pascal\Desktop\Trading\gekkonew>node --version
v5.11.2-nightly2016062103d36aea4f

C:\Users\Pascal\Desktop\Trading\gekkonew>npm install

always asking for sqlite3

**Comment by Pascal66** [comment]
git pull
Already up-to-date.

npm install
npm WARN gekko@0.2.5 No license field.
npm WARN You are using a pre-release version of node and things may not work as expected

C:\Users\Pascal\Desktop\Trading\gekkonew>node gekko --config config/sample-config.js
2016-07-05 13:53:49 (INFO):     Gekko v0.2.5 started
2016-07-05 13:53:49 (INFO):     I'm gonna make you rich, Bud Fox.

2016-07-05 13:53:49 (INFO):     Setting up Gekko in realtime mode
2016-07-05 13:53:49 (INFO):
2016-07-05 13:53:49 (INFO):     Setting up:
2016-07-05 13:53:49 (INFO):              Candle writer
2016-07-05 13:53:49 (INFO):              Store candles in a database

Gekko encountered an error and can't continue

Error:

The plugin sqlite adapter expects the module sqlite3 to be installed. However it is not, install it by running:

```
    npm install sqlite3@3.1.3
```

Meta debug info:

Gekko version: v0.2.5
Nodejs version: v5.11.2-nightly2016062103d36aea4f

**Comment by askmike** [comment]
git you run:

```
npm remove sqite3
npm install sqlite3@3.1.4
```

and see if that works?

On Tue, Jul 5, 2016 at 1:52 PM, Pascal notifications@github.com wrote:

> git pull
> Already up-to-date.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/askmike/gekko/issues/369#issuecomment-230457640, or mute
> the thread
> https://github.com/notifications/unsubscribe/AA7MD1WwG6nZvXLnRP-qdrMn267pVb6Lks5qSkV1gaJpZM4JE88o
> .

## 

PGP key at keybase.io/mikevanrossum
https://keybase.io/mikevanrossum/key.asc

**Comment by Pascal66** [comment]
seems to work with a fresh install of a stable version 5.12.0 of nodejs

**Comment by askmike** [comment]
Thanks for testing it out. So that is sqlite as well as btc-e trading?

**Comment by Pascal66** [comment]
seems to work eeven if i've no advice  for the moment

**Comment by askmike** [comment]
let me know if it breaks!

**Comment by Pascal66** [comment]
working and no break  for the moment :+1:
