### ISSUE TITLE
Method

### ISSUE THREAD

**Issue by Atroci** [askmike/gekko#372]
Hey, can someone help me build a custom method to where I can use 2 indicators at the same time and only if the 2 indicadores say the same thing the bot gives an advice?

I don't need the parameters, but if you have something like that and don't mind sharing or telling me how to do it.

Thanks

**Comment by askmike** [comment]
here you go: [RSI + MACD](https://gist.github.com/askmike/8957b52abef47ebfc1225c19d845b530#file-custom-js).

EDIT: if you are having trouble figuring it out yourself, let me know what is unclear and I'll try to improve that.
