### ISSUE TITLE
TypeError: Cannot read property 'watch' of undefined

### ISSUE THREAD

**Issue by askmike** [askmike/gekko#374]
see [here](https://github.com/askmike/gekko/issues/362#issuecomment-231263455)

> I tracked it down to commit 4df979dd2e298a2cbd14e5b574948b42d610065e that broke things for me. > All the commits up to that point run. But when I update to that commit it has the error: 
> 
> ```
> `/usr/src/gekko/core/budfox/marketFetcher.js:22
> var provider = config.watch.exchange.toLowerCase();
> ^
> 
> TypeError: Cannot read property 'watch' of undefined
> at new Fetcher (/usr/src/gekko/core/budfox/marketFetcher.js:22:24)
> at new Manager (/usr/src/gekko/core/budfox/marketDataProvider.js:18:17)
> at new BudFox (/usr/src/gekko/core/budfox/budfox.js:28:29)
> at /usr/src/gekko/core/pipeline.js:160:20
> at /usr/src/gekko/node_modules/async/lib/async.js:232:13
> at /usr/src/gekko/node_modules/async/lib/async.js:142:25
> at /usr/src/gekko/node_modules/async/lib/async.js:229:17
> ```
> 
> at /usr/src/gekko/node_modules/async/lib/async.js:556:34
> at prepareMarket (/usr/src/gekko/core/pipeline.js:143:7)
> at /usr/src/gekko/node_modules/async/lib/async.js:551:21

**Comment by BarnumD** [comment]
Got past that error but now I get this when I build against a184473
`{ Error: SQLITE_ERROR: unrecognized token: "{"
    at Error (native) errno: 1, code: 'SQLITE_ERROR' }

Gekko encountered an error and can't continue

Error:

DB error at `get`
`
