### ISSUE TITLE
Commit e41ff50 breaks bitfinex.

### ISSUE THREAD

**Issue by BarnumD** [askmike/gekko#376]
If you have 'Bitfinex' configured in config.js this commit breaks gekko:

/usr/src/gekko/exchanges/bitfinex.js:82 Trader.prototype.getFee = function(callback) { ^^^^^^ SyntaxError: Unexpected identifier at Object.exports.runInThisContext (vm.js:53:16) at Module._compile (module.js:513:28) at Object.Module._extensions..js (module.js:550:10) at Module.load (module.js:458:32) at tryModuleLoad (module.js:417:12) at Function.Module._load (module.js:409:3) at Module.require (module.js:468:17) at require (internal/module.js:20:19) at Actor.checkExchangeTrades (/usr/src/gekko/plugins/tradingAdvisor.js:160:22) at bound [as checkExchangeTrades](/usr/src/gekko/node_modules/lodash/dist/lodash.js:729:21)

**Comment by BarnumD** [comment]
I see that there is probably a missing bracket on line 63, but even with that it's still broken.

**Comment by askmike** [comment]
yep, working on it. ping @xhad!
