### ISSUE TITLE
feature request: access multiple exchange in one strategy.

### ISSUE THREAD

**Issue by tongxiaofeng** [askmike/gekko#383]
If my understanding is correct, now gekko only watch one exchange (one API account, one asset/currency pair). My strategy need to run upon multiple paris, multiple exchange.

Below is a sample strategy that I want to implement:
function GetTicker() {
    if(exchanges[0].ticker.last > exchanges[1].ticker.last){
         exchanges[0].buy(...);
         exchanges[1].sell(...);
    }
}

Actually I'm using https://www.botvs.com/api to backtest and running my strategy. I really suggest you check this site for your reference.

**Comment by tongxiaofeng** [comment]
at the bottom of www.botvs.com you can switch the language.

**Comment by askmike** [comment]
Very good idea, it would not be extremely hard to add something like this to Gekko. However for this we were need to make some changes to [the core architecture](https://github.com/askmike/gekko/blob/stable/docs/internals/architecture.md):

![Gekko architecture](https://wizb.it/gekko/static/architecture.jpg)

Gekko uses node streams to pass market data into a gekkoStream (wrapper around the trading advisor and potentially other plugins listening to market data). But since the code that does this is very simple ([the realtime market stream for example](https://github.com/askmike/gekko/blob/stable/core/budfox/budfox.js#L67-L77)) we could easily replace this when people want to create strategies for multiple markets.

---

However I will wait with building this until I have some concrete example of how people want to use multiple markets (remember that you cannot do arbitrage or similar things with Gekko). I am very open to discussions and pull requests (if I need to point someone in the right direction in regards to how Gekko currently does things, just let me know!)

**Comment by tongxiaofeng** [comment]
Why gekko is designed to not supporting arbitrage? I think the most profitable and stable strategy is arbitrage among different markets and exchanges.  Cryptocurrency market could be easily manipulated and technical analysis will lose effectiveness.

Actually I'm using botvs to do such things and proved feasible.

**Comment by askmike** [comment]
> www.botvs.com

Unfortunately only the homepage is in english, almost everything else is in Chinese.

> Why gekko is designed to not supporting arbitrage? I think the most profitable and stable strategy is arbitrage among different markets and exchanges. 

Yes you are right, arb is very profitable. The reason that Gekko isn't build for that is that arbitrage is very zero-sum. There is a certain amount of money to be made (like bitcoin mining) and it will be divided a certain way amongst everyone who does arbitrage (the faster you are, the more you will get). Making a good open source bot that does arbitrage is like giving free mining hardware away: everybody will make less money this way (and people will just make arb bots that are just faster than the most popular open source ones). If you want to arb, it's always better to build it yourself (which it sounds like you can do).

> Cryptocurrency market could be easily manipulated and technical analysis will lose effectiveness.

It might be if you are using a single simple indicator (like MACD), but this just means you need to build a better statistical model (Gekko doesn't force you to use technical analysis, you can use any type of prediction modeling you want. However Gekko is currently optimized for trend watching algorithms).

**Comment by tongxiaofeng** [comment]
I doesn't mean changing Gekko to an arb robot.  Gekko should be a platform to support various kinds of strategies. The strategy should be developed by the user of gekko. The end user is strategy developer or quant. Or will Gekko is a money maker out of box that any one could make money just by running Gekko?

I really appreciate your wonderful work and want to do something if I can. I was a developer about 12years ago. Now I'm learning again. 

BTW, to show my appreciation to your great work and selflessness I send a little Bitcoin to you the day before yesterday. Thanks!

**Comment by tongxiaofeng** [comment]
I will translate the API and write something to introduce concepts and structure of Botvs to you.

Just for your reference.

**Comment by Pascal66** [comment]
Wish I can play with my own arbitrage thing with gekko instead of my android :+1:

**Comment by tongxiaofeng** [comment]
[Introduction to BOTVS strategy and code structure](https://github.com/askmike/gekko/files/365423/BOTVS.copy.pdf)

I'm a user of botvs.com. I wrote this to help you understand the structure and design of botvs. 

The problem with botvs is that your strategy is transparent to the owner of this website. If you have a very profitable strategy you will never using it's service.

**Comment by tongxiaofeng** [comment]
BOTVS itself is not open source. But many people(mostly Chinese) wrote their strategy and shared as open source. Check https://github.com/botvs/strategies. The title of the strategies are most in Chinese. Just read the codes.

**Comment by askmike** [comment]
Out of scope for now :*(

**Comment by dumbanddumbererest** [comment]
Hey i know this is closed, but are we able to get prices for different pairs into the one strategy? It could all be on the one exchange, and we could look for cointegration, for example.

**Comment by hugokoopmans** [comment]
I am also interested in combining Trade advisse from multiple Asset/Currency pairs.

Given the architcture of Gekko would it be possible to use more then one "Trading Advisor" signal in real or paper trader?

**Comment by le4ker** [comment]
Any updates on this feature?
