### ISSUE TITLE
option mutally disable another one ?

### ISSUE THREAD

**Issue by Pascal66** [askmike/gekko#384]
Since I've set config.trader = true (with good key for btce), i've just advice and profit report.
No trade are made
Do I miss something wrong ? Do I wait ? Do I have more asset or currency in wallet?
Thank you

// Want Gekko to perform real trades on buy or sell advice?
// Enabling this will activate trades for the market being
// watched by `config.watch`.
config.trader = {
  enabled: true,
...

config.adviceLogger = {
  enabled: true
}
// do you want Gekko to calculate the profit of its own advice?
config.profitSimulator = {
  enabled: true,
  // report the profit in the currency or the asset?
  reportInCurrency: true,
  // start balance, on what the current balance is compared with
  simulationBalance: {
    // these are in the unit types configured in the watcher.
    asset: 1,
    currency: 100,
  },
  // // only want report after a sell? set to `false`.
  // verbose: false,

  // how much fee in % does each trade cost?
  fee: 0.2,
  // how much slippage/spread should Gekko assume per trade?
  slippage: 0.05
}

// Monitor the live market
config.watch = {
  exchange: 'btce', // see gekko/docs/supported_exchanges.md
  currency: 'USD',
  asset: 'ETH'

config.tradingAdvisor = {
  enabled: true,
  method: 'CCI', //'MACD',StochRSI
  candleSize: 60,
  historySize: 25,
  adapter: 'sqlite',
  talib: {
    enabled: false,
    version: '1.0.2'
  }
}
// CCI Settings
config.CCI = {
    constant: 0.015, // constant multiplier. 0.015 gets to around 70% fit
    history: 90, // history size, make same or smaller than history
    thresholds: {
        up: 100, // fixed values for overbuy upward trajectory
        down: -100, // fixed value for downward trajectory
        persistence: 1 // filter spikes by adding extra filters candles
    }
}

**Comment by hoddy** [comment]
You will need to have enough currecy to cover your fee's in the btc-e online wallet to be able to trade (say 0.5ETH), also are you sure gekko should have traded following your strategy yet? I find it good to map out the charts on xbtce then you can see what gekko should be doing.

Hope this helps if not i will check it later against my config as mine is currently set for btc-e and eth too.

**Comment by Pascal66** [comment]
I’ve a few eth, but enough to trade, i’ve manually triyed to sell some.
never saw traded things, only trading advice.
maybe, it’s the normal way my strategie work , i dont know.

**Comment by Pascal66** [comment]
> Hope this helps if not i will check it later against my config as mine is currently set for btc-e and eth too.
> @hoddy  sure :)
