### ISSUE TITLE
 Failed to get average tp from indicator.

### ISSUE THREAD

**Issue by Pascal66** [askmike/gekko#387]
2016-07-21 11:58:09 (INFO):     Starting to watch the market: BTC-e /
2016-07-24 11:55:36 (ERROR):    Failed to get average tp from indicator.

Waiting 3 days for an error using CCI

**Comment by Pascal66** [comment]
Another time : 

2016-07-25 21:07:50 (INFO):     Starting to watch the market: BTC-e /
2016-07-27 04:08:45 (ERROR):    Failed to get average tp from indicator.

Just modified history size in both: 
// CCI Settings
config.CCI = {
    constant: 0.015, // constant multiplier. 0.015 gets to around 70% fit
    history: 45, // history size, make same or smaller than history
    thresholds: {
        up: 100, // fixed values for overbuy upward trajectory
        down: -100, // fixed value for downward trajectory
        persistence: 1 // filter spikes by adding extra filters candles
    }
};
and : 
config.tradingAdvisor = {
  enabled: true,
  method: 'CCI', //'MACD',StochRSI
  candleSize: 60,
  historySize: 50,
  adapter: 'sqlite',
  talib: {
    enabled: false,
    version: '1.0.2'
  }
}

**Comment by askmike** [comment]
I'll check it out!

**Comment by Pascal66** [comment]
It work with the default values.
btw i donot have good working values foreach

**Comment by Grzesiek83** [comment]
Same issue here... with latest version of gekko. After one day of gathering stats i received "Failed to get average tp from indicator." error. 

Any idea how to get rid of it?

Setup of CCI:

config.tradingAdvisor = {
  enabled: true,
  method: 'CCI',
  candleSize: 17,
  historySize: 10,
  adapter: 'sqlite',

// CCI Settings
config.CCI = {
    constant: 0.015, 
    history: 90, 
    thresholds: {
        up: 160, 
        down: -10, 
        persistence: 0 
    }

Exchange -> BTC-E

**Comment by nozyqubis** [comment]
Hello everyone,
Getting same issue after i update to the latest vesrsion.

**Comment by chrisedington** [comment]
Getting it too on CCI

**Comment by imkane** [comment]
I'm also seeing this with CCI.

**Comment by joernroeder** [comment]
me too

**Comment by catastrophix** [comment]
and me on Bittrex

**Comment by blastbeng** [comment]
anyone solved this?

**Comment by Sungray** [comment]
Hi, I'm having this issue. Not sure if it's blocking. Trying to setup using CCI, on Bitstamp.
@askmike ?

**Comment by jlcd** [comment]
Same issue with CCI

**Comment by ipansensoy** [comment]
experiencing this on CCI any update?

**Comment by Atem18** [comment]
Same problem with CCI on Bitfinex

**Comment by pootato255** [comment]
Same problem with CCI on binance @askmike how to fix it?

**Comment by askmike** [comment]
This has been fixed since #2162.
