### ISSUE TITLE
Req: Adding new table to db for trading history

### ISSUE THREAD

**Issue by SkaTeMasTer** [askmike/gekko#394]
It would be nice if there was a log of BUY/SELL orders in the database.  

That way it would be easy to more creative output, like say line graphs for a more visual overview of the bot's activities with algorithm details and statistics on trade history.

**Comment by askmike** [comment]
good point, will add that to the todo!

**Comment by greenbigfrog** [comment]
@askmike actually a issue that shouldn't be closed, but this need a bump :smile:
