### ISSUE TITLE
Have 4BTC, only want to trade 0.4. How to set limit?

### ISSUE THREAD

**Issue by 0b01** [askmike/gekko#395]
other than pulling funds from exchange of course.

**Comment by 0b01** [comment]
in portfolioManager. Set buy amount to 0.1*amount

**Comment by SkaTeMasTer** [comment]
Request: move this option to config file.

**Comment by askmike** [comment]
the hard thing about this is that if you configure gekko in a way where you trading just 0.4 at a time but you are constantly losing, you will still end up with your account fully drained..

**Comment by 0b01** [comment]
@askmike The only way to implement a prevent loss feature is by adding a db of trading history. I will implement this db.

**Comment by saeeds255** [comment]
What do you mean by adding a db for trading history? How you can prevent loss bu doing this?

The good way is to try and find a good config for trading.

**Comment by marcosgabbardo** [comment]
I agree with @rickylqhan it is important to have money limits for trades (buy) in exchanges... today i use 2 accounts in the same exchange to resolve this problem... maybe a good solution is to put a plugin in config for that where it is possible to put a fixed amount or implementing a rule.

**Comment by Pascal66** [comment]
One easy idea this morning was to add an optional parameter to this.advice('short'/'long');

Can be in percent like : **this.advice('short', 10)** (10 for 10% of amount)

**Comment by askmike** [comment]
What you described is already implemented, see [here](https://github.com/askmike/gekko/blob/stable/core/baseTradingMethod.js#L235-L239) (the portfolio indicates how much of the portfolio should be moved into this position, with 1 being 100%). Unfortunately the trading plugin ignores this property..

**Comment by mathiasrw** [comment]
@askmike the link in your last post is 404 - do you know where I can find it?
