### ISSUE TITLE
How long before advices start appearing?

### ISSUE THREAD

**Issue by FFMG** [askmike/gekko#396]
This is a question rather than an issue, (do you have a forum that I could use rather?)

I pulled the latest version and ran `node gekko`, everything seems fine.

All the values in my config.js are default, apart for the exchange and one or two values.

```
config.debug = false; // for additional logging / debugging
...
config.watch = {

  // see https://github.com/askmike/gekko#supported-exchanges
  exchange: 'Poloniex',
  currency: 'USDT',
  asset: 'BTC'
}
...
config.adviceLogger = {
  enabled: true
}
...
// do you want Gekko to calculate the profit of its own advice?
config.profitSimulator = {
  enabled: true,
  // report the profit in the currency or the asset?
  reportInCurrency: true,
  // start balance, on what the current balance is compared with
  simulationBalance: {
    // these are in the unit types configured in the watcher.
    asset: 1,
    currency: 100,
  },
  // how much fee in % does each trade cost?
  fee: 0.25,
  // how much slippage/spread should Gekko assume per trade?
  slippage: 0.05
}
```

I have emails setup, (and I get an email when Gekko start).

I have been running for a little over 24hrs and so far nothing at all, not a single trade advisory, is that normal?

Am I missing something? Maybe I am not looking in the right place, it anything logged somewhere else?

Thanks

FFMG

**Comment by 0b01** [comment]
What trading strategy are you using and what parameters did you put? You can test to see if the strategy gives you any advice by running backtests.

**Comment by FFMG** [comment]
I am using everything default, no strategies changed or anything.

Maybe it is just me, but this is how I learn how things work, see the 'default' behaviour and see how it goes and then make some changes.

I wonder, seen the events of the last few days, maybe the market is very uncertain at the moment and this is been reflected in the advices?

**Comment by 0b01** [comment]
Yes it's very likely. You can change the strategy to DEMA with candles 1, history 2, long 3, short 4 to see an extremely short term trading strategy.
