### ISSUE TITLE
Listen to websocket

### ISSUE THREAD

**Issue by 0b01** [askmike/gekko#400]
Hi,

Is there anyway to listen to websocket instead of heartbeat?

Ricky

**Comment by 0b01** [comment]
How to switch away from heartbeat? Is it okay to reimplement poloniex using this library?

https://www.npmjs.com/package/poloniex-unofficial

**Comment by askmike** [comment]
See [here](https://github.com/askmike/gekko/issues/336#issuecomment-233128317):

> Gekko works with a concept of [markets](https://github.com/askmike/gekko/blob/stable/docs/internals/architecture.md#a-market), so we just need to add a "websocket" market type. Not a lot of functionality needs to be written for that (we can just pipe them straight into the [tradeBatcher](https://github.com/askmike/gekko/blob/stable/core/budfox/tradeBatcher.js) or [candleCreator](https://github.com/askmike/gekko/blob/stable/core/budfox/candleCreator.js).
> 
> The bad thing about websockets is that you don't have access to historical data, also the situation that if you lose connection for a minute you have incomplete data.

**Comment by 0b01** [comment]
Without WebSocket it's impossible to execute orders without slippage.

**Comment by askmike** [comment]
What do you mean? Whenever Gekko receives a signal from a strategy it will check the orderbook to base the order price on. Also, Gekko only creates limit orders.

**Comment by 0b01** [comment]
In my use case, the orderbook has to be up to date within a second.

**Comment by askmike** [comment]
That sounds like high frequency, are you able to use Gekko at all since all
trading data is summarized as minute OHLC data?

**Comment by 0b01** [comment]
Yes I was able to create a bot with a custom indicator with a 40% odds. The slippage was 20-140% depends on market volatility. I ended up implementing my own bot using code from tribeca. Now the odds are 62% so it's profitable in the long run.

Your code is definitely an inspiration. Thank you.
