### ISSUE TITLE
Log info

### ISSUE THREAD

**Issue by AddicTed2Github** [askmike/gekko#403]
Hello, 

When you run the Gekko's backtest, the terminal gives all info about the market price, the value of the indicator and the advice but when i watch real-time market, Gekko is not giving these infomations on the terminal after each candle. The only information i get is the trading request for the exchange platform.

Is it possible to print (or record in a file) these informations while watching real-time market ?

**Comment by 0b01** [comment]
What sort of information are you talking about? Can you upload a section of the backtest printout?

I'm guessing it's because the market condition is not triggering an advice, whereas in backtests, days of market information is available.

**Comment by AddicTed2Github** [comment]
Here is what i get with the backtest mode, I have the log.debug enabled: [gekko_backtest_BTC-ETH.txt](https://github.com/askmike/gekko/files/404986/gekko_backtest_BTC-ETH.txt).

I have already ran gekko in real-time for days, and i only receive debug output: 

> (DEBUG) Requested / trade data from Poloniex...

my real-time log : [gekko_realMode-BTC-ETH.txt](https://github.com/askmike/gekko/files/405139/gekko_realMode-BTC-ETH.txt)

 my config file :  [config_ETH.txt](https://github.com/askmike/gekko/files/404997/config_ETH.txt)

As you can see, output log in real-time mode doesn't give me this info part,

> 2016-08-06 00:51:13 (DEBUG):   calculated MACD properties for candle:
> 2016-08-06 00:51:13 (DEBUG):        short: 0.01777941
> 2016-08-06 00:51:13 (DEBUG):        long: 0.01753833
> 2016-08-06 00:51:13 (DEBUG):        macd: 0.00024108
> 2016-08-06 00:51:13 (DEBUG):        signal: 0.00015195
> 2016-08-06 00:51:13 (DEBUG):        macdiff: 0.00008913
> 2016-08-06 00:51:13 (DEBUG):   In no trend

like the output log in the backtest mode.

**Comment by 0b01** [comment]
The market is not triggering advice. I suggest you change your strategy and backtest it properly. Keep in mind that past performance is not a guarantee of future outcomes.

**Comment by AddicTed2Github** [comment]
Well, restart help. Thank's for the help.
