### ISSUE TITLE
Architecture

### ISSUE THREAD

**Issue by 0b01** [askmike/gekko#411]
Here is how I imagine the architecture should look like from a user's standpoint.
# Create a Strategy
1. Decide on parameters
2. import the indicators (could be custom)
3. import orderbook, portfolio, past trades
4. Write down the logic for entering/exiting the market
5. returns a tuple with advice and amount
# Create an Execution thread
1. Inject the Strategy (with the parameters of choice)
2. Load and Inject a Data Feed
3. ExecuteOrder
4. run(); optionally ... plot()

So next thing to do is:
1. make orderbook, portfolio, past trades accessible in strategy
2. plot trades

**Comment by askmike** [comment]
Regarding the first list: this is how i've seen most trading platforms implemented. However I chose to go a different way: I want a strategy to be completely decoupled from both trading and market logic: this way you can develop a strategy, backtest it, simulate it over live markets, and maybe even run it. Running your strategy against any other datasource should not require you to change to the code. 

The way Gekko works is by having the strategy be part of a module called the trading advisor, and trading simulation is another module that hooks in this advice (same as real trading). These are all plugins connected to eachother and are fed a "market" (depending on configuration realtime or backtest). 

See these docs:

https://github.com/askmike/gekko/blob/stable/docs/internals/architecture.md
https://github.com/askmike/gekko/blob/stable/docs/internals/plugins.md
https://github.com/askmike/gekko/blob/stable/docs/internals/trading_methods.md

---

about plotting: I was working on a web UI for gekko, see the  branch web-wrapper. This WIP will manage "Gekkos", plot market and strategy (and trades, etc). 

This will also make it more user friendly, plugins are internal components and the user can just create a strategy and click through a wizard to set up paper trading for example.

**Comment by saeeds255** [comment]
Is there anyway to test one strategy according to history chart? So everyone can create their logic and test it in minutes using one year history chart !
I myself created a strategy that was profitable over a week with  the average of 0.5 percent gain per day by the way I cant trust it for larger capital

**Comment by askmike** [comment]
sounds like you are looking for backtesting, read more here:

https://github.com/askmike/gekko/blob/stable/docs/Backtesting.md

**Comment by saeeds255** [comment]
Thanks !
But I don't know how to set data range .
I don't know how to backtest it on historical data, I edited config file like this :

```
config.backtest = {
  adapter: 'sqlite',
  daterange: {
        from: "2015-08-08 21:00:00",
        to: "2016-08-12 14:00:00"
        },
  batchSize: 50
}
```

but it returns the following error :

```
Error:
Query returned no candles (do you have local data for the specified range?)
```

What should I do now ?

**Comment by 0b01** [comment]
You need to do `--import` before running a backtest.

**Comment by 0b01** [comment]
@askmike what is a good place to put this module in? https://github.com/evilive3000/poloniex-orderbook

**Comment by greenbigfrog** [comment]
@askmike this can most likely be closed
