### ISSUE TITLE
Profitable strategies

### ISSUE THREAD

**Issue by FFMG** [askmike/gekko#412]
I have been testing gekko for about a week and, as far as I can tell, none of the default strategies are profitable, (on average I **loose** about 9% per week using any of them).

Is there a documentation somewhere that explains all the strategies as used by Gekko?

Or do you have some strategies that are 'better' than the default ones given on install?

(sorry this is more a question rather than an issue)

**Comment by PhillRob** [comment]
Only have been testing MACD on bitstamp w/ different moving averages and yes only losses. Testing PPO now. Probably advisable to use the paper trader as an indicator and manually trade. cryptowat.ch is actually shows the MACD in realtime...

**Comment by n3lz0n** [comment]
that is right, I had the same results......it's trading blindly....... no good......move along....

**Comment by FFMG** [comment]
I wouldn't say that it is trading blindly, but the default strategies all work at a loss, (I have tried them all), and the documentation does not really make it easy to see where a mistake was made.
The losses are consistent, so it cannot be just down to a down/bad market.

**Comment by n3lz0n** [comment]
end of the story ---> not profitable.... lol

nuff said

**Comment by FFMG** [comment]
Ok, we get it n3lz0n. then please move on if you want.

I, on the other hand, know enough about trading to know that the strategies might need some tweaking and/or the default ones might not be optimal.

And this was my comment/question was about, how to improve the default strategies.

**Comment by askmike** [comment]
Gekko is a free and open source market platform which you can use for a number of things, including running automated strategies. It comes with strategies out of the box that serve as examples.

**If there was a simple strategy that would profit all the time, it wouldn't be open source.**

Keep in mind that if you find a successful strategy it probably only works for one specific market (say BTC/USD on bitstamp), it most likely will perform badly at an altcoin market. I also don't know any successful strategies that worked a few months ago and still work today.

---

For strategies I recommend:
- experiment writing your own strategies yourself, [read here](https://github.com/askmike/gekko/blob/stable/docs/internals/trading_methods.md) how to implement them in Gekko.
- get inspiration out of external sources, try to look at strategies [on cryptotrader for example](https://cryptotrader.org/strategies). (You can also use their platform to run them, however Gekko is open source and runs on your own hardware).
- use a tool that tries to find optimal strategies for you, [this is](https://github.com/mkmarek/forex.analytics) an interesting project to look at.

**Comment by rspereiratech** [comment]
The link for "writting own strategies" is broken.

**Comment by askmike** [comment]
@master2501 which one exactly? You can find the correct document here:

https://github.com/askmike/gekko/blob/stable/docs/strategies/creating_a_strategy.md

**Comment by pcjoker** [comment]
Hi,

I would love to use this tool, but I am terrible at programming. I would like to use the candlestick data (open, close, high, low) rather then some indicators, but just don't know how to integrate them. Anyone willing to help me with writing?

**Comment by askmike** [comment]
@pcjoker if you want Gekko to do X unfortunately you do need to script / program that X in javascript. But the good thing is that the strategy will always have access to candlestick data (open, close, high, low as well as vwp, volume, amount of trades).

In the boilerplate strategy here:

https://gekko.wizb.it/docs/strategies/creating_a_strategy.html#Boilerplate-strategies

You can access a candle in your update function (for example), if you replace that with:

    // Based on the newly calculated
    // information, check if we should
    // update or not.
    strat.check = function(candle) {
      console.log(candle.open)
      console.log(candle.high)
      console.log(candle.low)
      console.log(candle.close)
    }

You will log the numbers per candle.
