### ISSUE TITLE
Cant backtesting while running

### ISSUE THREAD

**Issue by Pascal66** [askmike/gekko#413]
2016-08-12 10:56:11 (INFO):     Scanning local history for backtestable dateranges.
    { Error: SQLITE_BUSY: database is locked at Error (native) errno: 5, code: 'SQLITE_BUSY' }

Gekko encountered an error and can't continue

Error:
DB error at `get`

Meta debug info:

Gekko version: v0.3.2
Nodejs version: v6.3.0

**Comment by askmike** [comment]
will look into, work around for now is: copy the history folder (to history2 for example) and specify that path in the second config ([here](https://github.com/askmike/gekko/blob/stable/sample-config.js#L268))

**Comment by askmike** [comment]
Now you can! Use the UI :)
