### ISSUE TITLE
two instances

### ISSUE THREAD

**Issue by Pascal66** [askmike/gekko#414]
Sometimes i cant launch two instances of gekko with differents asset/currency
look like #413 even if this morning i've three instance lauched i dont know how.

 { Error: SQLITE_BUSY: database is locked
    at Error (native) errno: 5, code: 'SQLITE_BUSY' }

**Comment by askmike** [comment]
As for now: copy the history folder and configure each instance to use a different one OR use different exchanges. Will sort this out once the web-wrapper is at a further stage.

Sorry about the inconvenience!

**Comment by askmike** [comment]
I just pulled in a commit that changs DB behaviour (by using [WAL mode](https://www.sqlite.org/wal.html)), you could try to download the develop branch of Gekko and see if the problem is fixed here.
