### ISSUE TITLE
Why is Cexio not on the supported trading exchange list?

### ISSUE THREAD

**Issue by ghost** [askmike/gekko#417]
Great work on this project by the way!

Cex.io is only marked for monitoring, yet I've been running a live trading instance on the same for more than 24 hours. 

Is the trading value set to false on the table because it is buggy?

**Comment by askmike** [comment]
Cex.io was added a long time ago (when the only supported market was GHS/BTC). The real trading implementation had a lot of problems at the time.

A few updates have been done to support more markets (not by me, see b6cfc4), but I never actually got around fully testing cex.io.

> I've been running a live trading instance on the same for more than 24 hours.

Could you let me know the results as soon as gekko made any real trades (and if everything went smoothly)?

**Comment by ghost** [comment]
I tested for about 3 days. 

It bought and sold successfully.

It made trades but only if the asset balance was greater than 0. If you started with 0 BTC. It gives an undefined amount error. 

However even if your BTC balance is 0.0001 it will run, as long as it is not 0.

**Comment by greenbigfrog** [comment]
@askmike this possibly can be closed

**Comment by askmike** [comment]
:+1:
