### ISSUE TITLE
[Improvment]core/baseTradingMethod dynamics indicators

### ISSUE THREAD

**Issue by Pascal66** [askmike/gekko#429]
Can it parse method/indicators dynamicaly ?
So each time theres a modification to this file, it can read all methods including own testing methods,
instead modify it and add manually methods that we testing ?

**Comment by askmike** [comment]
Sorry for the late response!

What do you mean exactly? Do you mean that you want to change the method file while Gekko is running and re apply?

**Comment by Pascal66** [comment]
No, I mean, adding/removing indicators, without modifying core/baseTradingMethods.js file

**Comment by askmike** [comment]
great idea!

**Comment by greenbigfrog** [comment]
Gonna bump this here. This would be sth rather nice to have

**Comment by askmike** [comment]
Unfortunately this is now out of scope: all the focus is on TA-lib and tulip nowadays!
