### ISSUE TITLE
Gekko seems to be working backwards

### ISSUE THREAD

**Issue by CliffS** [askmike/gekko#435]
I'm wondering if I have something set up wrong.  Every time the price fluctuates upwards, Gekko buys and then it sells when the price drops.

I gave it XBT 0.5 to play with and it's now down to 0.41.

My config is:

```
config.watch = {
    exchange: 'Bitstamp',
    currency: 'EUR',
    asset: 'BTC'
}


config.tradingAdvisor = {
    enabled: true,
    method: 'MACD',
    candleSize: 30,
    historySize: 50,
    adapter: 'sqlite',
    talib: {
        enabled: true,
        version: '1.0.2'
    }
}

config.MACD = {
  short: 10,
  long: 21,
  signal: 9,
  thresholds: {
      down: -0.025,
      up: 0.025,
      persistence: 1
      }
};

config['talib-macd'] = {
    parameters: [10, 21, 9],
    thresholds: {
        down: -0.025,
        up: 0.025,
        persistence: 1
        }
}
```

I really don't understand what I'm doing. Any advice?

**Comment by marcosgabbardo** [comment]
@CliffS you set up right, and Gekko is following your strategy. Like others advices, MACD is not a strategy that  is profitable every time. Try to implement your own strategy (try to change parameters) and backtest a lot of times before using in real world.

All users here are looking for best strategies everyday, this is a day to day work and it is hard... it is hard to be rich ;)

**Comment by Pascal66** [comment]
Never play with indicators without a good method.
The problem was giving method from indicators, without any strategie.
DONT USE INDICATOR WITHOUT A STRATEGIE FROM IT.
as @marcosgabbardo say, this is a day to day work.

**Comment by askmike** [comment]
The "default strategy" is just a simple MACD indicator inspired by the thread [Goomboo's Journal](https://bitcointalk.org/index.php?topic=60501.0). Unfortunately nobody is able to predict where the price is going all the time, if you figure out a strategy that does keep it to yourself ;)

Note that most successful strategies (in my experience) only make successful bets 50% of the time, they just make more on successful ones than they lose on bad ones.
