### ISSUE TITLE
[bug]I received 3 emails for one advice.

### ISSUE THREAD

**Issue by Pascal66** [askmike/gekko#436]
short or long gave me 3 advices in my email for the same things.
Second things, was to not have an email for long and another one for short.
They are the same work. 

ie:   var subject = 'New advice: go ' + advice.recommendation;
subject must be the same as config.watch.exchange

**Comment by greenbigfrog** [comment]
@askmike since it hasn't been mentioned in quite a while, this probably can be closed.
