### ISSUE TITLE
Limit of short, long, possible answer to #395

### ISSUE THREAD

**Issue by Pascal66** [askmike/gekko#438]
#395

One easy idea this morning was to add an optional parameter to this.advice('short'/'long');
Can be in percent like : this.advice('short', 10) (10 for 10% of amount)

**Comment by Pascal66** [comment]
usefull and working  with #448 #449 #450 in branch develop

**Comment by greenbigfrog** [comment]
I think this has been implemented or has open PRs for it

**Comment by askmike** [comment]
No but it will be very soon. Active discussion now in #1834.
