### ISSUE TITLE
can not use local history？

### ISSUE THREAD

**Issue by wupeng1211** [askmike/gekko#439]
hi mike, this is my config.js,
[config.tradingAdvisor = {
   enabled: true,
   method: 'MACD',
   candleSize: 60,
   historySize: 25,](url)
I've imported the history since 2016, when the run is also shown gekko

[2016-09-06 16:07:33 (DEBUG):    Full history locally available. Seeding the trading method with all required historical candles.
2016-09-06 16:07:33 (INFO):              Using the trading method: RSI](url)

But gekko did not use history, and still need to run 25 hours before providing TRADING ADVICE, there can not be as straightforward as the local historical backtest data acquisition history of the candle? Can provide trading advice based on historical data gekko start running? ths.

**Comment by 3zveruga** [comment]
Hello.i have this problem too. Gekko download from Poloniex historical data poloniex_0.1.db, Gekko stop after import ,thn i typing command node gekko, But gekko did not use history, and still need to run 25 hours before providing TRADING ADVICE

**Comment by 3zveruga** [comment]
in windows cant install talib? it is normal
[config.txt](https://github.com/askmike/gekko/files/467091/config.txt)
if all Ok, How long until first trade?

**Comment by askmike** [comment]
> But gekko did not use history, and still need to run 25 hours before providing TRADING ADVICE, 

Why do you think so?

**Comment by 3zveruga** [comment]
thanks

**Comment by wupeng1211** [comment]
if Full history locally available. Could loading history candle, immediately gives TRADING ADVICE @askmike

**Comment by wupeng1211** [comment]
config.tradingAdvisor = {
enabled: true,
method: 'MACD',
candleSize: 60,
historySize: 25}

  @askmike  For example this configuration, according to the current need to collect 25 \* 60 minute candle, that is, every time I restart the system, or any other operation, is to give trading advice to one days later. If you can directly load the history of candle, then in a complete historical data, it can immediately give trading advice based on yesterday's candle. Thank you.

**Comment by askmike** [comment]
This should be working now, right?

**Comment by nozyqubis** [comment]
With the latest update i have the same issue despite my local data are more than 100 days back.

The trading method requests 1350 minutes of historic data. Checking availablity..
2017-04-05 03:50:32 (INFO):	

2017-04-05 03:50:32 (INFO):		Usable local data available, trying to match with exchange data..
2017-04-05 03:50:32 (INFO):		Preventing Gekko from requesting 465 minutes of history.
2017-04-05 03:50:37 (INFO)--->>>:		Not seeding locally available data to the trading method.
2017-04-05 03:50:37 (INFO):		The exchange does not return enough data. 0 minutes are still missing.

**Comment by askmike** [comment]
@nozyqubis Gekko needs to stitch history together:

If you have a year of history ending at `2017-04-04 12:00:00` and you start Gekko and Gekko can only fetch exchange data up until `2017-04-04 14:00:00` it cannot use your old local data since you have 2 hours missing which Gekko cannot fill. The 100 days of data can still be used for backtesting, and the exchange you watch supports importing you can easily fill the missing data. If you need help or think something else is wrong please open a new issue!

**Comment by nozyqubis** [comment]
i have filled the latest history, if it solved i will update for this.Thank you for your response.Wish you a happy day.

**Comment by askmike** [comment]
Great! Just let me know if you run into anything else :) (please open a new issue though).

**Comment by stefano-neri** [comment]
I could solve this on Windows Server with changing 'WAL' to 'DEL' and adding the sqlite dependencies in the config:
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
//                       CONFIGURING ADAPTER
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

config.adapter = 'sqlite';

config.sqlite = {
  path: 'plugins/sqlite',

  dataDirectory: 'history',
  version: 0.1,

  journalMode: '**DEL**', // setting this to 'DEL' may prevent db locking on windows

  dependencies: [{
      module: 'sqlite3',
      version: '3.1.4'
    }]
}
