### ISSUE TITLE
 Reverse Trading Master my gekko

### ISSUE THREAD

**Issue by hlboys** [askmike/gekko#441]
gekko has many benefits program.
1. Easy installation and setup. (In the manual it is almost good.)
2. Support for multiple Exchange
3. Runs on Windows, etc.

So this seems to be managed except if one the best.
1. Trading on the method also too simple.
   - The only indicator that one Trading will not see the road light.
   - If it is difficult to implement Fibonacci retracement of the harmonic pattern
     Take advantage of the indicators at https://www.tradingview.com.
   - Recommended indicators
      a. "The Rational Flibbr Indicator v2" + "CM_Williams_Vix_Fix Finds Market Bottoms" ★★
      b. "[LAVA] Renko Mod" ★★
      c. "Indicator: WaveTrend Oscillator [WT]"  ★ 
      d. "VDUB_Rejection_Spike_V3"★ 
      e. "CM_Ultimate RSI MTF" ★ 
      f.  "Godmode3.1"
      g. "Squeeze Momentum Indicator [LazyBear]"
      h. "ANN Strategy"
      i. "Chande Composite Momentum Index"
      j. "COG Double Channel [LazyBear]"
     - This will be one of the higher profit.
       best of best indicator is "[LAVA]Renko Mod"
2. Auto Trading is necessary to money management.
   - Profit or stop loss feature is essential
3. be able to see the bot trade statistics.
   - Confirmed bot operated from a remote location
   - If possible to control bots

https://github.com/carlos8f/zenbot is programs are a lot of advantages trading bots.

It would be best of best of best of best of best of best if combined with gekko

**Comment by Pascal66** [comment]
funny but mongodb usage and no windows support

**Comment by JFD3D** [comment]
@Pascal66 This user posted the same thing in the zenbot issues (copy/paste), except he linked gekko. Not exactly sure what to do to help besides recommending learning JavaScript and Node.js

**Comment by hlboys** [comment]
I mean, that combine the advantages

**Comment by JFD3D** [comment]
@hlboys Is there any reason you wouldn't do this yourself? What you are asking here is to combine two projects with completely different codebases, it's a lot to ask. It seems are interested in automatic live trading so maybe the best course of action for you is to do it yourself. I've learned a lot by reading through open source code projects on GitHub and you can do the same. There are plenty of free JavaScript and Node.js tutorials on YouTube as well as free courses online provided by many different organizations and even universities.

**Comment by hlboys** [comment]
@JFD3D 음.. 역시 번역기로는 의사 전달이 제대로 안되나보네요.
당연히 제가 직접 만드는 것이 내 생각을 표현 할 수 있는 최고의 방법입니다.
제가 원하는 대로 해 달라고 칭얼거린 것 같았나요?
전 두 제작자가 서로의 생각을 공유하면 더 나은 결과가 있지 않을까 싶어서
의견을 적었을 뿐, 두 제작자에게 그렇게 해달라고 강요 또는 부탁한 것이 아닙니다.
그렇게 하거나 하지 않거나 그건 두 제작자 마음일 뿐 이지요.

달리는 자동차와 날아다니는 비행기를 만드는 사람들에게 같은 얘길 한다고
날으는 자동차를 만들라는 얘기가 아니죠.
날으는 자동차는 그 사람들이 떠올릴 수 있는 생각일 뿐입니다.

난 영어를 못해 구글 번역기로 글을 읽고 글을 올립니다.
제가 여기서 자바 스크립트나 Node.js를 배운다면 영어부터 배워야 할 판이죠.
영문권, 중문권은 커뮤니티도 크고 정보도 많아 좋죠?
당신도 이 글을 제대로 읽으려면 한글을 직접 배우거나 번역기가 한글을 완벽히 배울 때 까지 기다리거나,
한글 아는 사람에게 번역을 맡기거나 무시하면 됩니다.

그러나 조언은 고맙습니다. ^-^

**Comment by GO1984** [comment]
Is there already a strategy called: „ [LAVA] Renko Mod „for GEKKO?
I am searching for a renko code snipped, maybe someone can help me out?
