### ISSUE TITLE
Plugin or something else ?

### ISSUE THREAD

**Issue by Pascal66** [askmike/gekko#451]
Are StopLoss & TakeProfit can be made in plugin (wich only use candle for 1 minute) or in indicators or in a method ?

**Comment by askmike** [comment]
a trading method! If you need higher than 1 minute resolution you cannot really use Gekko. You probably also want to use a realtime websocket API instead of the REST API Gekko always uses.

**Comment by Pascal66** [comment]
It work with #448 #449 and #450 ;)
Do not need 1mn resolution, just need to place sl & tp
