### ISSUE TITLE
zwebsocket

### ISSUE THREAD

**Issue by miquael** [askmike/gekko#452]
server.js won't run without zwebsocket, but can't find zwebsocket anywhere (?)

**Comment by askmike** [comment]
unfortunately the webserver in the stable branch is broken. I was working on a different way (see the [web-wrapper](https://github.com/askmike/gekko/tree/web-wrapper) branch), but that is a) in early development and b) seems to break Gekko for windows (#456).

I am very open to pull requests but I don't think I'll be having any time soon.
