### ISSUE TITLE
LTC auto trading in Okcoin.cn

### ISSUE THREAD

**Issue by hlboys** [askmike/gekko#453]
![okcoin-api](https://cloud.githubusercontent.com/assets/22008188/18623467/6a65e7dc-7e78-11e6-8a5b-a60d20186ade.png)

Being traded BTC price

**Comment by askmike** [comment]
What exactly is the problem here?

**Comment by hlboys** [comment]
![6a65e7dc-7e78-11e6-8a5b-a60d20186ade](https://cloud.githubusercontent.com/assets/22008188/18678840/5a85c640-7f98-11e6-9f3d-4c875dc6e73a.png)
제가 영어를 못합니다.

**Comment by askmike** [comment]
And you configured Gekko to watch the market CNY/LTC?

**Comment by hlboys** [comment]
60 interval
Okcoin.cn - LTC/CNY
MACD mathod

**Comment by greenbigfrog** [comment]
@askmike can most likely be closed
