### ISSUE TITLE
GEKKO: broken on windows

### ISSUE THREAD

**Issue by ghost** [askmike/gekko#456]
[npm-debug.txt](https://github.com/askmike/gekko/files/480931/npm-debug.txt)

**Comment by askmike** [comment]
- Wat version of Windows are you on?
- What version of nodejs are you running?

That error comes from [relieve](https://www.npmjs.com/package/relieve). I'll see what I can do about removing that dependency.

**Comment by ajthemacboy** [comment]
I am getting this as well.

Windows 10 Professional 64bit Insider Preview, build 14926
Node.js version 6.6.0 and Gekko 0.3.2

I get "Error: Cannot find a config file." when trying to run `node gekko`.

**Comment by askmike** [comment]
@ajthemacboy you need to configure Gekko, read [this](https://github.com/askmike/gekko/blob/stable/docs/Configuring_gekko.md).

**Comment by ghost** [comment]
Win 7 and the latest version from the node download site. I did upload the lawn hopefully it will be useful for you

Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Mike van Rossum notifications@github.com Date: 9/20/16  02:44  (GMT-09:00) To: askmike/gekko gekko@noreply.github.com Cc: bneyjr bneyjr@gmail.com, Author author@noreply.github.com Subject: Re: [askmike/gekko] NPM install fails with No License Field Error
  (#456) 

Wat version of Windows are you on?
What version of nodejs are you running?

That error comes from relieve. I'll see what I can do about removing that dependency.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/askmike/gekko","title":"askmike/gekko","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/askmike/gekko"}},"updates":{"snippets":[{"icon":"PERSON","message":"@askmike in #456: - Wat version of Windows are you on?\r\n- What version of nodejs are you running?\r\n\r\nThat error comes from [relieve](https://www.npmjs.com/package/relieve). I'll see what I can do about removing that dependency."}],"action":{"name":"View Issue","url":"https://github.com/askmike/gekko/issues/456#issuecomment-248266424"}}}

**Comment by vilkates** [comment]
Hello,

i have a problem install gekko:
(C:\Users\forex\Desktop\gekko-stable>npm install
npm WARN package.json gekko@0.3.2 No license field.
npm WARN engine relieve@2.1.1: wanted: {"node":">=6.0.0"} (current: {"node":"4.6.0","npm":"2.15.9"})
|

> relieve@2.1.1 postinstall C:\Users\forex\Desktop\gekko-stable\node_modules\relieve
> bash links.sh

'bash' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! relieve@2.1.1 postinstall: `bash links.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the relieve@2.1.1 postinstall script 'bash links.sh'.
npm ERR! This is most likely a problem with the relieve package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bash links.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs relieve
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls relieve
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\forex\Desktop\gekko-stable\npm-debug.log)

Who can help resolve it?

**Comment by askmike** [comment]
@bneyjr I removed the dependency that caused npm install to crash. Could you try again please?
