### ISSUE TITLE
PLUGIN: XMPP broken

### ISSUE THREAD

**Issue by prfiredragon** [askmike/gekko#466]
What is the correct way to make it work? or It have a bug?

2016-10-02 20:46:25 (INFO): Setting up:
2016-10-02 20:46:25 (INFO):      XMPP bot
2016-10-02 20:46:25 (INFO):      XMPP module lets you communicate with Gekko on Jabber.
2016-10-02 20:46:25 (ERROR):    ERROR LOADING DEPENDENCY node-xmpp

 The plugin xmppbot expects the module node-xmpp to be installed. However it is not, install it by running: 

```
npm install node-xmpp@0.12.0 
```

mike@Mike:~/gekko$ npm install node-xmpp@0.12.0 
npm WARN deprecated node-xmpp@0.12.0: Please use node-xmpp-client / node-xmpp-server / node-xmpp-component
npm WARN deprecated buffer-browserify@0.2.5: Package not maintained. Recent browserify uses https://github.com/feross/buffer

> node-stringprep@0.2.3 install /home/mike/gekko/node_modules/node-stringprep
> node-gyp rebuild

make: se ingresa al directorio «/home/mike/gekko/node_modules/node-stringprep/build»
  CXX(target) Release/obj.target/node_stringprep/node-stringprep.o
In file included from ../node-stringprep.cc:1:0:
../node_modules/nan/nan.h: In function ‘v8::Handlev8::Value NanError(const char_)’:
../node_modules/nan/nan.h:340:38: error: ‘New’ is not a member of ‘v8::String’
 # define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                      ^
../node_modules/nan/nan.h:360:13: note: in expansion of macro ‘_NAN_ERROR’
     return  _NAN_ERROR(v8::Exception::Error, errmsg);
             ^
../node_modules/nan/nan.h: In function ‘void NanThrowError(const char_)’:
../node_modules/nan/nan.h:345:7: error: ‘ThrowException’ is not a member of ‘v8’
       v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
       ^
../node_modules/nan/nan.h:364:5: note: in expansion of macro ‘_NAN_THROW_ERROR’
     _NAN_THROW_ERROR(v8::Exception::Error, errmsg);
     ^
../node_modules/nan/nan.h:340:38: error: ‘New’ is not a member of ‘v8::String’
 # define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                      ^
../node_modules/nan/nan.h:345:26: note: in expansion of macro ‘_NAN_ERROR’
       v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
                          ^
../node_modules/nan/nan.h:364:5: note: in expansion of macro ‘_NAN_THROW_ERROR’
     _NAN_THROW_ERROR(v8::Exception::Error, errmsg);
     ^
../node_modules/nan/nan.h: In function ‘void NanThrowError(v8::Handlev8::Value)’:
../node_modules/nan/nan.h:369:5: error: ‘ThrowException’ is not a member of ‘v8’
     v8::ThrowException(error);
     ^
../node_modules/nan/nan.h: In function ‘v8::Handlev8::Value NanError(const char_, int)’:
../node_modules/nan/nan.h:376:53: error: ‘New’ is not a member of ‘v8::String’
     v8::Localv8::Value err = v8::Exception::Error(v8::String::New(msg));
                                                     ^
../node_modules/nan/nan.h:378:14: error: ‘New’ is not a member of ‘v8::String’
     obj->Set(v8::String::New("code"), v8::Int32::New(errorNumber));
              ^
../node_modules/nan/nan.h:378:65: error: no matching function for call to ‘v8::Int32::New(const int&)’
     obj->Set(v8::String::New("code"), v8::Int32::New(errorNumber));
                                                                 ^
../node_modules/nan/nan.h:378:65: note: candidate is:
In file included from /home/mike/.node-gyp/6.6.0/include/node/node.h:42:0,
                 from ../node_modules/nan/nan.h:130,
                 from ../node-stringprep.cc:1:
/home/mike/.node-gyp/6.6.0/include/node/v8.h:2558:25: note: static v8::Localv8::Integer v8::Integer::New(v8::Isolate_, int32_t)
   static Local<Integer> New(Isolate\* isolate, int32_t value);
                         ^
/home/mike/.node-gyp/6.6.0/include/node/v8.h:2558:25: note:   candidate expects 2 arguments, 1 provided
In file included from ../node-stringprep.cc:1:0:
../node_modules/nan/nan.h: In function ‘v8::Handlev8::Value NanTypeError(const char_)’:
../node_modules/nan/nan.h:340:38: error: ‘New’ is not a member of ‘v8::String’
 # define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                      ^
../node_modules/nan/nan.h:390:12: note: in expansion of macro ‘_NAN_ERROR’
     return _NAN_ERROR(v8::Exception::TypeError, errmsg);
            ^
../node_modules/nan/nan.h: In function ‘void NanThrowTypeError(const char_)’:
../node_modules/nan/nan.h:345:7: error: ‘ThrowException’ is not a member of ‘v8’
       v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
       ^
../node_modules/nan/nan.h:394:5: note: in expansion of macro ‘_NAN_THROW_ERROR’
     _NAN_THROW_ERROR(v8::Exception::TypeError, errmsg);
     ^
../node_modules/nan/nan.h:340:38: error: ‘New’ is not a member of ‘v8::String’
 # define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                      ^
../node_modules/nan/nan.h:345:26: note: in expansion of macro ‘_NAN_ERROR’
       v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
                          ^
../node_modules/nan/nan.h:394:5: note: in expansion of macro ‘_NAN_THROW_ERROR’
     _NAN_THROW_ERROR(v8::Exception::TypeError, errmsg);
     ^
../node_modules/nan/nan.h: In function ‘v8::Handlev8::Value NanRangeError(const char_)’:
../node_modules/nan/nan.h:340:38: error: ‘New’ is not a member of ‘v8::String’
 # define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                      ^
../node_modules/nan/nan.h:398:12: note: in expansion of macro ‘_NAN_ERROR’
     return _NAN_ERROR(v8::Exception::RangeError, errmsg);
            ^
../node_modules/nan/nan.h: In function ‘void NanThrowRangeError(const char_)’:
../node_modules/nan/nan.h:345:7: error: ‘ThrowException’ is not a member of ‘v8’
       v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
       ^
../node_modules/nan/nan.h:402:5: note: in expansion of macro ‘_NAN_THROW_ERROR’
     _NAN_THROW_ERROR(v8::Exception::RangeError, errmsg);
     ^
../node_modules/nan/nan.h:340:38: error: ‘New’ is not a member of ‘v8::String’
 # define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                      ^
../node_modules/nan/nan.h:345:26: note: in expansion of macro ‘_NAN_ERROR’
       v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
                          ^
../node_modules/nan/nan.h:402:5: note: in expansion of macro ‘_NAN_THROW_ERROR’
     _NAN_THROW_ERROR(v8::Exception::RangeError, errmsg);
     ^
../node_modules/nan/nan.h: At global scope:
../node_modules/nan/nan.h:421:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:137:71: note: in definition of macro ‘NAN_INLINE’
 # define NAN_INLINE(declarator) inline __attribute__((always_inline)) declarator
                                                                       ^
../node_modules/nan/nan.h:421:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h:137:71: note: in definition of macro ‘NAN_INLINE’
 # define NAN_INLINE(declarator) inline **attribute**((always_inline)) declarator
                                                                       ^
../node_modules/nan/nan.h: In function ‘v8::Localv8::Object NanNewBufferHandle(char_, size_t, int)’:
../node_modules/nan/nan.h:424:44: error: ‘callback’ was not declared in this scope
     return node::Buffer::New(data, length, callback, hint);
                                            ^
../node_modules/nan/nan.h:424:54: error: ‘hint’ was not declared in this scope
     return node::Buffer::New(data, length, callback, hint);
                                                      ^
../node_modules/nan/nan.h: In function ‘v8::Localv8::Object NanNewBufferHandle(char_, uint32_t)’:
../node_modules/nan/nan.h:431:40: error: no matching function for call to ‘New(char_&, uint32_t&)’
     return node::Buffer::New(data, size);
                                        ^
../node_modules/nan/nan.h:431:40: note: candidates are:
In file included from ../node_modules/nan/nan.h:131:0,
                 from ../node-stringprep.cc:1:
/home/mike/.node-gyp/6.6.0/include/node/node_buffer.h:31:40: note: v8::MaybeLocalv8::Object node::Buffer::New(v8::Isolate_, size_t)
 NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate\* isolate, size_t length);
                                        ^
/home/mike/.node-gyp/6.6.0/include/node/node_buffer.h:31:40: note:   no known conversion for argument 1 from ‘char_’ to ‘v8::Isolate_’
/home/mike/.node-gyp/6.6.0/include/node/node_buffer.h:34:40: note: v8::MaybeLocalv8::Object node::Buffer::New(v8::Isolate_, v8::Localv8::String, node::encoding)
 NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate_ isolate,
                                        ^
/home/mike/.node-gyp/6.6.0/include/node/node_buffer.h:34:40: note:   no known conversion for argument 1 from ‘char_’ to ‘v8::Isolate_’
/home/mike/.node-gyp/6.6.0/include/node/node_buffer.h:39:40: note: v8::MaybeLocalv8::Object node::Buffer::New(v8::Isolate_, char_, size_t, node::Buffer::FreeCallback, void_)
 NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate_ isolate,
                                        ^
/home/mike/.node-gyp/6.6.0/include/node/node_buffer.h:39:40: note:   candidate expects 5 arguments, 2 provided
/home/mike/.node-gyp/6.6.0/include/node/node_buffer.h:46:40: note: v8::MaybeLocalv8::Object node::Buffer::New(v8::Isolate_, char_, size_t)
 NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate\* isolate,
                                        ^
/home/mike/.node-gyp/6.6.0/include/node/node_buffer.h:46:40: note:   candidate expects 3 arguments, 2 provided
In file included from ../node-stringprep.cc:1:0:
../node_modules/nan/nan.h: In function ‘v8::Localv8::Object NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:435:34: error: no matching function for call to ‘New(uint32_t&)’
     return node::Buffer::New(size);
                                  ^
../node_modules/nan/nan.h:435:34: note: candidates are:
In file included from ../node_modules/nan/nan.h:131:0,
                 from ../node-stringprep.cc:1:
/home/mike/.node-gyp/6.6.0/include/node/node_buffer.h:31:40: note: v8::MaybeLocalv8::Object node::Buffer::New(v8::Isolate_, size_t)
 NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate_ isolate, size_t length);
                                        ^
/home/mike/.node-gyp/6.6.0/include/node/node_buffer.h:31:40: note:   candidate expects 2 arguments, 1 provided
/home/mike/.node-gyp/6.6.0/include/node/node_buffer.h:34:40: note: v8::MaybeLocalv8::Object node::Buffer::New(v8::Isolate_, v8::Localv8::String, node::encoding)
 NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate_ isolate,
                                        ^
/home/mike/.node-gyp/6.6.0/include/node/node_buffer.h:34:40: note:   candidate expects 3 arguments, 1 provided
/home/mike/.node-gyp/6.6.0/include/node/node_buffer.h:39:40: note: v8::MaybeLocalv8::Object node::Buffer::New(v8::Isolate_, char_, size_t, node::Buffer::FreeCallback, void_)
 NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate_ isolate,
                                        ^
/home/mike/.node-gyp/6.6.0/include/node/node_buffer.h:39:40: note:   candidate expects 5 arguments, 1 provided
/home/mike/.node-gyp/6.6.0/include/node/node_buffer.h:46:40: note: v8::MaybeLocalv8::Object node::Buffer::New(v8::Isolate_, char_, size_t)
 NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate\* isolate,
                                        ^
/home/mike/.node-gyp/6.6.0/include/node/node_buffer.h:46:40: note:   candidate expects 3 arguments, 1 provided
In file included from ../node-stringprep.cc:1:0:
../node_modules/nan/nan.h: In function ‘v8::Localv8::Object NanBufferUse(char_, uint32_t)’:
../node_modules/nan/nan.h:442:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(data, size);
            ^
../node_modules/nan/nan.h: In constructor ‘NanCallback::NanCallback()’:
../node_modules/nan/nan.h:712:49: error: no matching function for call to ‘v8::Object::New()’
     v8::Localv8::Object obj = v8::Object::New();
                                                 ^
../node_modules/nan/nan.h:712:49: note: candidate is:
In file included from /home/mike/.node-gyp/6.6.0/include/node/node.h:42:0,
                 from ../node_modules/nan/nan.h:130,
                 from ../node-stringprep.cc:1:
/home/mike/.node-gyp/6.6.0/include/node/v8.h:3006:24: note: static v8::Localv8::Object v8::Object::New(v8::Isolate_)
   static Local<Object> New(Isolate\* isolate);
                        ^
/home/mike/.node-gyp/6.6.0/include/node/v8.h:3006:24: note:   candidate expects 1 argument, 0 provided
In file included from ../node-stringprep.cc:1:0:
../node_modules/nan/nan.h: In constructor ‘NanCallback::NanCallback(v8::Handlev8::Function&)’:
../node_modules/nan/nan.h:718:49: error: no matching function for call to ‘v8::Object::New()’
     v8::Localv8::Object obj = v8::Object::New();
                                                 ^
../node_modules/nan/nan.h:718:49: note: candidate is:
In file included from /home/mike/.node-gyp/6.6.0/include/node/node.h:42:0,
                 from ../node_modules/nan/nan.h:130,
                 from ../node-stringprep.cc:1:
/home/mike/.node-gyp/6.6.0/include/node/v8.h:3006:24: note: static v8::Localv8::Object v8::Object::New(v8::Isolate_)
   static Local<Object> New(Isolate_ isolate);
                        ^
/home/mike/.node-gyp/6.6.0/include/node/v8.h:3006:24: note:   candidate expects 1 argument, 0 provided
In file included from ../node-stringprep.cc:1:0:
../node_modules/nan/nan.h: In destructor ‘NanCallback::~NanCallback()’:
../node_modules/nan/nan.h:725:12: error: ‘class v8::Persistentv8::Object’ has no member named ‘Dispose’
     handle.Dispose();
            ^
../node_modules/nan/nan.h:726:12: error: ‘class v8::Persistentv8::Object’ has no member named ‘Clear’
     handle.Clear();
            ^
../node_modules/nan/nan.h: In member function ‘void NanCallback::SetFunction(v8::Handlev8::Function&)’:
../node_modules/nan/nan.h:177:26: error: ‘NewSymbol’ is not a member of ‘v8::String’
 #define NanSymbol(value) v8::String::NewSymbol(value)
                          ^
../node_modules/nan/nan.h:731:39: note: in expansion of macro ‘NanSymbol’
     NanPersistentToLocal(handle)->Set(NanSymbol("callback"), fn);
                                       ^
../node_modules/nan/nan.h: In member function ‘v8::Localv8::Function NanCallback::GetFunction()’:
../node_modules/nan/nan.h:177:26: error: ‘NewSymbol’ is not a member of ‘v8::String’
 #define NanSymbol(value) v8::String::NewSymbol(value)
                          ^
../node_modules/nan/nan.h:735:46: note: in expansion of macro ‘NanSymbol’
     return NanPersistentToLocal(handle)->Get(NanSymbol("callback"))
                                              ^
../node_modules/nan/nan.h:736:25: error: expected primary-expression before ‘>’ token
         .Asv8::Function();
                         ^
../node_modules/nan/nan.h:736:27: error: expected primary-expression before ‘)’ token
         .Asv8::Function();
                           ^
../node_modules/nan/nan.h: In member function ‘void NanCallback::Call(int, v8::Handlev8::Value_)’:
../node_modules/nan/nan.h:177:26: error: ‘NewSymbol’ is not a member of ‘v8::String’
 #define NanSymbol(value) v8::String::NewSymbol(value)
                          ^
../node_modules/nan/nan.h:744:13: note: in expansion of macro ‘NanSymbol’
         Get(NanSymbol("callback")).Asv8::Function();
             ^
../node_modules/nan/nan.h:744:51: error: expected primary-expression before ‘>’ token
         Get(NanSymbol("callback")).Asv8::Function();
                                                   ^
../node_modules/nan/nan.h:744:53: error: expected primary-expression before ‘)’ token
         Get(NanSymbol("callback")).Asv8::Function();
                                                     ^
../node_modules/nan/nan.h:746:9: error: ‘GetCurrent’ is not a member of ‘v8::Context’
         v8::Context::GetCurrent()->Global()
         ^
../node_modules/nan/nan.h: In member function ‘void NanAsyncWorker::SavePersistent(const char_, v8::Localv8::Object&)’:
../node_modules/nan/nan.h:177:26: error: ‘NewSymbol’ is not a member of ‘v8::String’
 #define NanSymbol(value) v8::String::NewSymbol(value)
                          ^
../node_modules/nan/nan.h:793:17: note: in expansion of macro ‘NanSymbol’
     handle->Set(NanSymbol(key), obj);
                 ^
../node_modules/nan/nan.h: In member function ‘v8::Localv8::Object NanAsyncWorker::GetFromPersistent(const char_)’:
../node_modules/nan/nan.h:177:26: error: ‘NewSymbol’ is not a member of ‘v8::String’
 #define NanSymbol(value) v8::String::NewSymbol(value)
                          ^
../node_modules/nan/nan.h:800:24: note: in expansion of macro ‘NanSymbol’
     return handle->Get(NanSymbol(key)).Asv8::Object();
                        ^
../node_modules/nan/nan.h:800:53: error: expected primary-expression before ‘>’ token
     return handle->Get(NanSymbol(key)).Asv8::Object();
                                                     ^
../node_modules/nan/nan.h:800:55: error: expected primary-expression before ‘)’ token
     return handle->Get(NanSymbol(key)).Asv8::Object();
                                                       ^
../node_modules/nan/nan.h: In member function ‘virtual void NanAsyncWorker::HandleErrorCallback()’:
../node_modules/nan/nan.h:822:30: error: ‘New’ is not a member of ‘v8::String’
         v8::Exception::Error(v8::String::New(errmsg))
                              ^
../node_modules/nan/nan.h: In function ‘bool _NanGetExternalParts(v8::Handlev8::Value, const char__, size_t_)’:
../node_modules/nan/nan.h:990:12: error: ‘class v8::String’ has no member named ‘IsExternalAscii’
   if (str->IsExternalAscii()) {
            ^
../node_modules/nan/nan.h:991:11: error: ‘ExternalAsciiStringResource’ in ‘class v8::String’ does not name a type
     const v8::String::ExternalAsciiStringResource\* ext;
           ^
../node_modules/nan/nan.h:992:5: error: ‘ext’ was not declared in this scope
     ext = str->GetExternalAsciiStringResource();
     ^
../node_modules/nan/nan.h:992:16: error: ‘class v8::String’ has no member named ‘GetExternalAsciiStringResource’
     ext = str->GetExternalAsciiStringResource();
                ^
../node-stringprep.cc: In static member function ‘static void StringPrep::Initialize(v8::Handlev8::Object)’:
../node-stringprep.cc:23:58: error: no matching function for call to ‘v8::FunctionTemplate::New(void (&)(const v8::FunctionCallbackInfov8::Value&))’
     Local<FunctionTemplate> t = FunctionTemplate::New(New);
                                                          ^
../node-stringprep.cc:23:58: note: candidates are:
In file included from /home/mike/.node-gyp/6.6.0/include/node/node.h:42:0,
                 from ../node_modules/nan/nan.h:130,
                 from ../node-stringprep.cc:1:
/home/mike/.node-gyp/6.6.0/include/node/v8.h:4483:34: note: static v8::Localv8::FunctionTemplate v8::FunctionTemplate::New(v8::Isolate_, v8::FunctionCallback, v8::Localv8::Value, v8::Localv8::Signature, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/mike/.node-gyp/6.6.0/include/node/v8.h:4483:34: note:   no known conversion for argument 1 from ‘void(const v8::FunctionCallbackInfov8::Value&)’ to ‘v8::Isolate_’
/home/mike/.node-gyp/6.6.0/include/node/v8.h:4487:34: note: static v8::Localv8::FunctionTemplate v8::FunctionTemplate::New(v8::Isolate_, v8::FunctionCallback, v8::Localv8::Value, v8::Localv8::Signature, int, v8::ConstructorBehavior)
   static Local<FunctionTemplate> New(
                                  ^
/home/mike/.node-gyp/6.6.0/include/node/v8.h:4487:34: note:   candidate expects 6 arguments, 1 provided
../node-stringprep.cc:28:17: error: ‘NewSymbol’ is not a member of ‘v8::String’
     target->Set(String::NewSymbol("StringPrep"), t->GetFunction());
                 ^
../node-stringprep.cc: In member function ‘v8::Handlev8::Value StringPrep::prepare(v8::String::Value&)’:
../node-stringprep.cc:139:34: error: too few arguments to function ‘v8::Localv8::Primitive v8::Undefined(v8::Isolate_)’
             return v8::Undefined();
                                  ^
In file included from /home/mike/.node-gyp/6.6.0/include/node/node.h:42:0,
                 from ../node_modules/nan/nan.h:130,
                 from ../node-stringprep.cc:1:
/home/mike/.node-gyp/6.6.0/include/node/v8.h:324:27: note: declared here
   friend Local<Primitive> Undefined(Isolate\* isolate);
                           ^
../node-stringprep.cc:145:28: error: ‘New’ is not a member of ‘v8::String’
     Local<String> result = String::New(dest, destLen);
                            ^
../node-stringprep.cc: In function ‘void ToUnicode(const v8::FunctionCallbackInfov8::Value&)’:
../node-stringprep.cc:230:28: error: ‘New’ is not a member of ‘v8::String’
     Local<String> result = String::New(dest, destLen);
                            ^
In file included from ../node-stringprep.cc:1:0:
../node_modules/nan/nan.h: In instantiation of ‘void NanDispose(v8::Persistent<T, v8::NonCopyablePersistentTraits<T> >&) [with T = v8::Object]’:
../node_modules/nan/nan.h:771:34:   required from here
../node_modules/nan/nan.h:415:5: error: ‘class v8::Persistentv8::Object’ has no member named ‘Clear’
     handle.Clear();
     ^
make: **\* [Release/obj.target/node_stringprep/node-stringprep.o] Error 1
make: se sale del directorio «/home/mike/gekko/node_modules/node-stringprep/build»
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.13.0-96-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/mike/gekko/node_modules/node-stringprep
gyp ERR! node -v v6.6.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
gekko@0.3.2 /home/mike/gekko
├── blueimp-md5@2.3.1  extraneous
├── brfs@0.0.8  extraneous
├── browser-request@0.3.3  extraneous
├── browserify@2.35.4  extraneous
├── faye-websocket@0.11.0  extraneous
├── ltx@2.5.0  extraneous
├── node-expat@2.3.15  extraneous
├── node-xmpp-component@0.1.1  extraneous
└── node-xmpp-server@0.2.4  extraneous

npm WARN gekko@0.3.2 No license field.
npm ERR! Linux 3.13.0-96-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "node-xmpp@0.12.0"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! node-stringprep@0.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-stringprep@0.2.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-stringprep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-stringprep
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-stringprep
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mike/gekko/npm-debug.log
mike@Mike:~/gekko$

**Comment by askmike** [comment]
will look into this asap!

**Comment by prfiredragon** [comment]
I am trying to fix this and understand how it works.

1- On xmppbot.js I change that `var xmpp = require('node-xmpp-client');`

2- On plugins.js I change that 

```
dependencies: [{
      module: 'node-xmpp-client',
      version: '3.0.2'
    }]
```

3- I run `npm install node-xmpp-client@3.0.2`

now i see its working 

The only problem that I have is the `this.priceTime.fromNow()`, from `xmppbot.js` `TypeError: Cannot read property fromNow of undefined`

**Comment by askmike** [comment]
Great that you are trying to make it work!

So the problem most likely comes from [this line](https://github.com/askmike/gekko/blob/8f6af8a29f154161d7ef975247430628c78246d8/plugins/xmppbot.js#L78):

```
Actor.prototype.processCandle = function(candle) {
  this.price = candle.close;
  this.priceTime = candle.date;
};
```

`candle.date` has been renamed to `candle.start`. If it works it would be great if you could send a PR. If there is another problem, let me know!
