### ISSUE TITLE
Not issue, need help.

### ISSUE THREAD

**Issue by 3zveruga** [askmike/gekko#477]
Need help to config trade in gekko
![2016-10-11 12-51-55](https://cloud.githubusercontent.com/assets/6505608/19266293/8e02a316-8fb1-11e6-927f-63ed7dc02040.png)

my config
![2016-10-11 12-53-08](https://cloud.githubusercontent.com/assets/6505608/19266337/c869b5b2-8fb1-11e6-85cf-98b131935a49.png)

**Comment by askmike** [comment]
What exectly are you having problems with? If you want to create real orders using gekko, please see this document: 

https://github.com/askmike/gekko/blob/stable/docs/Plugins.md#trader

**Comment by 3zveruga** [comment]
Gekko trading, And i lose btc, have no profit. What i do wrong.

**Comment by askmike** [comment]
What kind of strategy are you using? Do you get different results when backtesting or paper trading? Read this very carefully:

https://github.com/askmike/gekko/issues/201
