### ISSUE TITLE
Bittrex integration

### ISSUE THREAD

**Issue by askmike** [askmike/gekko#478]
development has started here: https://github.com/Stoner19/gekko/tree/develop

**Comment by sudo-tee** [comment]
Any news on this, I would lov to see bittrex integration

**Comment by groentebroer** [comment]
+1, a lot of coins are only available on Bittrex, so integration would be sweet... Too little experience to do it myself, sorry!

**Comment by luismelodev** [comment]
@askmike any news?

**Comment by askmike** [comment]
@luishmelo I don't have time for this anytime soon, all my time in Gekko is going towards #737.

Almost all exchanges available within Gekko were added by other people. I don't know anyone working on bittrex at the moment unfortunately. Feel free to pick it up, all info you need can be found [here](https://gekko.wizb.it/docs/extending/add_an_exchange.html) :)
