### ISSUE TITLE
Poloniex error when user dont have enough BTC for buying

### ISSUE THREAD

**Issue by rajeshdalsaniya** [askmike/gekko#480]
Hi @askmike 
I am addressing this error coming when user dont have enough BTC for buying other currency when geeko try to execute order based on advice

```
2016-10-14 19:02:07 (INFO): We have new trading advice!
2016-10-14 19:02:07 (INFO):      Position: long
2016-10-14 19:02:07 (INFO):      Market price: 0.0000212
2016-10-14 19:02:07 (INFO):      Based on market time: 2016-10-14 13:31:00

2016-10-14 19:02:07 (INFO): (PROFIT REPORT) original simulated balance:  0.09726 BTC
2016-10-14 19:02:07 (INFO): (PROFIT REPORT) current simulated balance:   0.08985 BTC
2016-10-14 19:02:07 (INFO): (PROFIT REPORT) simulated profit:        -0.00742 BTC (-7.62527%)
2016-10-14 19:02:11 (INFO): Attempting to BUY 0.00047192071731949034 POT at Poloniex
2016-10-14 19:02:12 (INFO): Send advice via email.
2016-10-14 19:02:13 (ERROR):    unable to buy: null { error: 'Total must be at least 0.0001.' }
```

**Comment by askmike** [comment]
Do you know how much BTC was available at the time?

**Comment by rajeshdalsaniya** [comment]
i know the cause of error . there is not enough fund. I just addressing you ( @askmike ) may be it helps you to update in code. right now its 0.0000001 bts something in wallet

**Comment by LordAntonio99** [comment]
I try to use Poloniex but just say No new trades... Do you know what should I do?

**Comment by askmike** [comment]
hey @ToNiiCR I am not sure what you mean. Could you please [create a new issue](https://github.com/askmike/gekko/issues/new) with the output of Gekko and what you expected differently?

**Comment by jonathancross** [comment]
Should this be closed?

**Comment by xyzzy529** [comment]
@rajeshdalsaniya ... are you running Gekko from a computer in India?
We are having problems using Poloniex from our computer in Pune.

Thanks!

**Comment by askmike** [comment]
@xyzzy529 this specific error:

> 'Total must be at least 0.0001.'

Comes from Poloniex complaining that the total of the order (volume * amount) is under 0.0001 I think. Are you still having this issue?

**Comment by xyzzy529** [comment]
Our issue is not with the same error.
Our issue seems to be that the requests to Poloniex are not returning any data.
Other Exchanges are working (like BTCC and GDAX) but not Poloniex.

I was thinking it might be that Poloniex blocks certain IP address blocks. Therefore I asked Rajesh if he was in India to help rule that issue out (thinking if he is able to use Poloniex from India, albeit it with other errors, then we should be able to as well).

I was searching the Issue Que for anything that might shed light on our problem.

**Comment by askmike** [comment]
Ah interesting, I was asking because @rajeshdalsaniya opened this issue a year ago.

> I was searching the Issue Que for anything that might shed light on our problem.

I am not 100% sure, but I don't think there is anything on the issue tracker with that problem. You are welcome to create a new one (with logs and debug information).

**Comment by xyzzy529** [comment]
I saw that, but was hoping he would get an email and be able to answer.

I like what you have done with Gekko and bravo for doing all this work.

We continue to work on the problem and will fill out an issue or PR once we get something concrete. Right now I am leaning to some non-Gekko problem that is causing this.

Thanks for the reply .... and I would close this original issue as "Not a Gekko Problem" ... just an "Economic one" ;-)

**Comment by askmike** [comment]
Let's hope he responds!

> I like what you have done with Gekko and bravo for doing all this work.

np :)

> Thanks for the reply .... and I would close this original issue as "Not a Gekko Problem" ... just an "Economic one" ;-)

good thinking ;)

**Comment by chinciusan** [comment]
I have this issue too, right now. 
`2017-10-22 20:47:32 (ERROR):	unable to buy: null { error: 'Total must be at least 0.0001.' }`  

this comes every couple of seconds after the trader received buy advice.

**Comment by askmike** [comment]
You don't have enough funds available! The check for poloniex does not work
but you understand the problem :)

On 23 Oct 2017 00:51, "Marian Chinciusan" <notifications@github.com> wrote:

I have this issue too, right now.
2017-10-22 20:47:32 (ERROR): unable to buy: null { error: 'Total must be at
least 0.0001.' }

this comes every couple of seconds after the trader received buy advice.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/askmike/gekko/issues/480#issuecomment-338495988>, or mute
the thread

**Comment by chinciusan** [comment]
I understand, so should I leave it like that?
