### ISSUE TITLE
Setting Trading Amount / Percentage

### ISSUE THREAD

**Issue by Misanthrop87** [askmike/gekko#491]
Hey,

is there any possibility to set a maximum amount of how much money shall be set per bid? Or a percentage of the existing money? I cannot find it in the configuration... and I dont find a documentation of it. Or is it maybe the "currency" in the profit simulator?

Kind regards
David

**Comment by Pascal66** [comment]
see #450

**Comment by askmike** [comment]
Will merge that in tonight!

**Comment by greenbigfrog** [comment]
Duplicate of #937 . @askmike this issue should be closed
