### ISSUE TITLE
 Error: Nonce must be greater than...

### ISSUE THREAD

**Issue by Lorkshem** [askmike/gekko#499]
Error: Nonce must be greater than 1479308401823498. You provided 147930837470400.

My bot can't operate with my current balance.
I try in other account with lower valour and it's ok.
![error poloniex in gekko](https://cloud.githubusercontent.com/assets/5292512/20352657/c8060f4c-abf6-11e6-8550-1293f62cf976.png)

**Comment by rafaelcmrj** [comment]
same thing here

**Comment by rafaelcmrj** [comment]
I'm using Poloniex

**Comment by rafaelcmrj** [comment]
@Lorkshem FYI I fixed my problem creating a new API Key/Secret Key

**Comment by Lorkshem** [comment]
@rafaelcmrj thank very much for sugestion!!! ^^
Solved my problem too!
