### ISSUE TITLE
Profitable strategy for 1min period

### ISSUE THREAD

**Issue by Lorkshem** [askmike/gekko#500]
I know it's asking too much, but ...
Could anyone point out the most profitable strategy for the Poloniex XMRBTC market?
Obs: With a period of 1min and using the standard strategies available in gekko.
So far I have not been able to make a profit ... :(

**Comment by Lorkshem** [comment]
I've read the documentation a little better and learned that the best way to verify this is to perform tests with the backtest mode.

**Comment by askmike** [comment]
yes! If you run into problems with backtest mode let me know.

Note that you can import historical data from Poloniex, that will make it way easier to get data to backtest over.
