### ISSUE TITLE
Real trades 

### ISSUE THREAD

**Issue by rafaelcmrj** [askmike/gekko#501]
I have enabled trades in my config.js but I'm only receiving advices in my email "go short", "go long", but the bot doesn't do any trade

**Comment by Lorkshem** [comment]
Check "config['I understand that Gekko only automates MY OWN trading strategies'] = true;" on the end of file config.

**Comment by askmike** [comment]
if that doesn't work post your config (without api keys).

**Comment by rafaelcmrj** [comment]
@askmike it was working... I was confusing advice with real trade.. not necessarily what it advises you it trades... thank you

**Comment by askmike** [comment]
good point: if you have the trader and the mailer active the mailer will still email you "advices" instead of trades that actually occurred. It's on my todo list..
