### ISSUE TITLE
Help on custom method, please!

### ISSUE THREAD

**Issue by Lorkshem** [askmike/gekko#502]
What change should I make in the code to not allow the short price to be lower than the last long price?

    // helpers
    var _ = require('lodash');
    var log = require('../core/log.js');

    // configuration
    var config = require('../core/util.js').getConfig();
    // let's create our own method
    var method = {};

    // prepare everything our method needs
    method.init = function() {

      this.name = 'Scalping';
      this.currentTrend;
      this.requiredHistory = config.tradingAdvisor.historySize;
      // define the indicators we need
      var parameters = {short: 13, long: 21, signal: 1};
      this.addIndicator('macd1', 'MACD', parameters);
      var parameters = {short: 21, long: 34, signal: 1};
      this.addIndicator('macd2', 'MACD', parameters);
      var parameters = {short: 34, long: 144, signal: 1};
      this.addIndicator('macd3', 'MACD', parameters);
      this.addIndicator('ema21', 'EMA', 21);
      this.addIndicator('ema34', 'EMA', 34);
      this.addIndicator('ema144', 'EMA', 144);
    }

    // what happens on every new candle?
    method.update = function(candle) {
      // nothing!  
    }

    // for debugging purposes: log the last calculated
    method.log = function() {
    }

    method.check = function() {
      var macd1 = this.indicators.macd1.diff; 
      var macd2 = this.indicators.macd2.diff;
      var macd3 = this.indicators.macd3.diff;
      var ema21 = this.indicators.ema21.result;
      var ema34 = this.indicators.ema34.result;
      var ema144 = this.indicators.ema144.result;

      if(macd1>0 && macd2>0 && macd3>0 && ema21>ema34 && ema21>ema144) {
        this.advice('long');
      log.debug('buy price:', this.lastPrice.toFixed(8));
      } 
      
      if(macd1<0 && macd2<0 && macd3<0 && ema21<ema34 && ema21<ema144) {  
        this.advice('short');
      log.debug('sell price:', this.lastPrice.toFixed(8));
      } 
      
    }

    module.exports = method;

**Comment by Lorkshem** [comment]
Suggestion # 503 of including the option that shorts are always greater than the longs would probably solve the problem if it were added to the trader.

**Comment by askmike** [comment]
If you only want to advice short if all this passes:

```
if(macd1<0 && macd2<0 && macd3<0 && ema21<ema34 && ema21<ema144) {  
```

AND if the current price is higher than the last long price:

https://gist.github.com/askmike/2c4b8e9201c380503ac347ff69c199d5

Let me know if you need to figure out anything more?

**Comment by Lorkshem** [comment]
Thank you very much. I had tried something similar but his answer helped me to have several ideas through the properties of the candles.

**Comment by DeBelserArne** [comment]
Quick question on this.

I added a new file to my strategies named: Scalping.js, I can see the file in my Gekko UI when I launch gekko.

But if I try to run it, I can't put any parameters, probably because it's not initiated in the script. My question is, how do I make it so I can put parameters here (screenie):

https://i.gyazo.com/9d853269b6c4358c725c380b9022fdaf.png

Thanks in advance

**Comment by DeBelserArne** [comment]
I found that these parameters are saved in .toml files. So I tried adding a .toml file with some parameters, but it doesn't show in my custom strategy.
