### ISSUE TITLE
 Important tips for profitSimulator

### ISSUE THREAD

**Issue by Lorkshem** [askmike/gekko#503]
First: I do not think he should consider longs or consecutive shorts, since operations usually use the full amount available.

Second: I think he should have a choice that short was always larger than the previous long.
edit: The second suggestion could also be very useful if it were added to the trader.

**Comment by Lorkshem** [comment]
Many thanks for the reply. I tried to implement something similar but still did not know the variable "candle.close".
I also tried to avoid consecutive longs and consecutive shots with a variable "sold_out" but it did not work ... :(

**Comment by greenbigfrog** [comment]
@askmike can most likely be closed
