### ISSUE TITLE
I do not know the indicator

### ISSUE THREAD

**Issue by BarnumD** [askmike/gekko#509]
Trying to create a custom method and custom indicator.  Indicator called methods\indicators\EMAATR.js.  Method called methods\custom.js.  When i try to run `I get I do not know the indicator EMAATR`.  Running develop branch.  Do I need to add the indicator to a list somewhere?

**Comment by askmike** [comment]
For now, yes :/

https://github.com/askmike/gekko/blob/develop/plugins/tradingAdvisor/baseTradingMethod.js#L29

**Comment by askmike** [comment]
![screen shot 2016-11-26 at 15 09 51](https://cloud.githubusercontent.com/assets/969743/20641203/e6c8a024-b3ea-11e6-9bad-70831dc60106.png)
