### ISSUE TITLE
installing on windows might fail (sqlite3 dep)

### ISSUE THREAD

**Issue by askmike** [askmike/gekko#512]
By default Gekko uses sqlite as a backend, and for thats needs a compiled version of [sqlite3](https://github.com/mapbox/node-sqlite3) which [should be precompiled](https://github.com/mapbox/node-sqlite3/wiki/Binaries), however it failed to install that one on the windows 10 machine I have available:

![gekko](https://cloud.githubusercontent.com/assets/969743/20709412/13b695b6-b62d-11e6-8de2-43b48ab33355.jpg)

**Comment by Pascal66** [comment]
Work well on W10 here since the beginning Mike

**Comment by askmike** [comment]
that is very strange, I'll close this for now and if someone else runs into the issue re open it.

**Comment by ofek-a** [comment]
I ran into the exact same issue, looking here for a solution :/

EDIT:
This solved my issue: https://github.com/mapbox/node-sqlite3/issues/637

**Comment by kifirkin** [comment]
Building `sqlite3` from source also solved this issue for me
