### ISSUE TITLE
Custom strategy persistent storage

### ISSUE THREAD

**Issue by osnwt** [askmike/gekko#516]
This question is inspired by another question on how to prevent short below last long. While it was clear, it will not work after gekko restart since last strategy saved price is never stored persistently and after restart it may result to undesired short or in some cases to prevent any trades (depending on the strategy). Much better if gekko saves its state on exit and resumes on restart.

How can I implement a persistent storage for a custom strat to save such values? I mean not reinventing the wheel and reusing existing framework.

Things to consider:
- there may be few instances of custom strategy running in few gekkos on different pairs;
- it should persist when trading but probably should not when backtesting for obvious reasons.

PS. This probably may also be used when writing a strategy with portfolio management when you split the portfolio into some peaces and track each one. I did not thing about that yet, but it might be useful.

**Comment by askmike** [comment]
I am wondering, do you really want to only short (sell at the moment) after a certain price? That would lock you into the asset in case of a crash.

-----

Anyway, there are two ways of solving this problem:

## Option 1: use the warmup period to recalculate

When you start gekko it will first go through a warmup period where it will not ask the strat for advice (by executing the `check` method in your strat). Read the details for that in #515) You could move all logic to the `update` method of your strat (except for the logic that actually calls `this.advice`). That way when the strat comes out of warmup it should already have the state required.

## Option 2: save state in file

(this is very hacky). You can create a very simple script that will on load pull state out of a json file (for example), and on every update of the state write it back. You can conditionally do this (only if this is NOT a backtest) by calling the following in your method:

    var mode = var config = require('../core/util.js').getMode();
    // mode is realtime when not backtesting

----

Let me know if you need help with either one.

**Comment by askmike** [comment]
I am closing this for now as I don't think it's a general issue (very specific), but feel free to keep replying anyway.

**Comment by osnwt** [comment]
Locking into asset is an issue, but it depends on the strategy. In some cases it might still be useful to set a soft limit and keep asset for some time, selling it only if price crashes below. I assume that crashes are rare comparing to usual pumps and dumps, at least, if you trade cryptocurrencies, not BTC_USD pair that is more or less stable and slow.

Assume an example from yesterday: ETC/BTC was pumped. Since gekko is not an instant buy robot, it missed it using MACD and bought by an average pump price. Then price slowly goes down, MACD does not detect it. And it will finally sell ETC when price is far below last long. I want to prevent this behaviour since it is better (for me now) to keep it instead of dumping it. Or maybe sell it when current price approaches the last long going down. But of course I am not a trader, I am hobbyist, so it does not matter as far as I can implement own ideas. And the idea is to keep reference to the last long to do something (or maybe last few orders from orderbook to use in a strategy). Actually, it is not my only issue, it directly follows #502.

I thought about Option 2 but using a **well-defined API to save persistent data and not thinking in terms of files or databases to use**. I can write any script of course, but the idea was to provide such option out of the box using, for example, the same database provider as gekko uses, or at least a predefined (preconfigured) file name and options to deal with few instances.

**Comment by askmike** [comment]
>  Since gekko is not an instant buy robot, it missed it using MACD and bought by an average pump price. Then price slowly goes down, MACD does not detect it.

Note that MACD is only a very simple strat that comes with Gekko, it is highly recommended that you use your own strats with (potentially) different indicators. MACD only tries to detect trends, and will most likely perform poorly when:

> Assume an example from yesterday: ETC/BTC was pumped.

There are also a few other ones that come with Gekko (check the methods directory).

--------

> I thought about Option 2 but using a well-defined API to save persistent data and not thinking in terms of files or databases to use.

So another thing is: Gekko is not supposed to crash, if it crashes a lot for you we should maybe focus on improving stability?

Regardless, I'm open to adding something to Gekko that is able to get/set state from an adapter (database). However I won't have time for this for quite a while.

**Comment by osnwt** [comment]
To be clear: I do not expect from gekko to make me rich. At least not out of the box. So I am not a person who will ask how to use it since it doesn't have GUI.

I know that there are other strats, and at the moment I am playing with my own. As I said, I have no experience with trading, so wanted to use gekko as a playground framework. Some time ago I read [this paper](http://bigpicture.typepad.com/comments/files/turtlerules.pdf), and thought about implementing it from scratch. AFAIK it cannot be done with gekko now since it requires some portfolio management to keep tracks of few orders.

I did not say that it (the software) crashes for me, I said that I may want to restart it in case of changes in strategy and/or options since it cannot update config dynamically. It should not be every day event, but it is possible.

Finally, I did not expect from you to write anything I may want :)  I only posted it here as a feature request/idea to consider. I can stay with what exists and add anything I need. But I thought that it is better to discuss it with the author first, and implement or hack last, rather than duplicate efforts and spend time to tasks incompatible with the main development.

**Comment by askmike** [comment]
Sorry for making a bunch of assumptions!

>  I said that I may want to restart it in case of changes in strategy and/or options since it cannot update config dynamically.

You're right, my bad.

------

>  I only posted it here as a feature request/idea to consider.

I'm glad you did! It's a very interesting idea and brings forward a problem I did not consider before (state in strats as opposed to dumb / pure strats). I'm sure eventually I'll run into this problem and have to really think on how to fix this properly as I haven't yet (when I do, I'll reopen this issue).

If you want to hack option 2 together and run into anything let me know!
