### ISSUE TITLE
Poloniex market order simulation and custom order types

### ISSUE THREAD

**Issue by osnwt** [askmike/gekko#517]
Poloniex does not have a concept of market orders via API, and this is an issue to make instant trades for some similar projects. I think market sell order may be emulated with low order value and immediateOrCancel API option. AFAIK, in that case it should instantly sell for the best bid price (not a low price given in the order) and save some time to react.

I am also thinking about more order types like stop-limit etc to use in custom strategies. I realise that it is not portable across exchanges, but each one may have own tricks and while no way to support all portably should be a way to use supported options at least in custom strategies using documented interface to trader.

What do you think?

**Comment by askmike** [comment]
Hey,

The portfolioManager (responsible for turning strat advices into orders) is very outdated, I have plans to improve this to be more inline with todays exchanges (to give an example, the [infitityOrder prop](https://github.com/askmike/gekko/blob/stable/exchanges.js#L8) had to do with the API of Mt. Gox).

However my main focus is releasing a workable UI (see #513 and #489), that at first might not even support real trading. After that I want to pick up the portfolioManager. I was thinking about something like:

A strat can give an advice together with something like:

- priority (how important is it that this happens FAST) -> should be executed as market order (or similar).
- portfolio (how much of the available balance should be moved into position).

An then a more advanced portfolioManager which uses these and creates the best possible orders (supported by exchange), maybe additionally tweaked by a config (does the user want specific order types, etc RISK/COST decision).

Would that work for you?

**Comment by osnwt** [comment]
Would be good if portfolioManager could work with more than a single order at once and keep track of them. As for me, I would prefer a flexible and powerful core controlled from command line instead of UI since UI is an option, and core is a must.

Anyway, it is thoughts only. I am newbie with trading robots and actually with trading at all, so may think about wrong things. I just see how volatile may be prices and want to be able to react ASAP along with slow processes. That's why I wish to have a core that is capable of providing everything including realtime orderbook processing using push APIs, but I have no any experience using this in real trading yet.

**Comment by askmike** [comment]
> I would prefer a flexible and powerful core controlled from command line instead of UI since UI is an option, and core is a must.

Everything will always stay available over the command line. But you might be one of the few who rather uses command line, the biggest question I get about Gekko is how to use it (with the command line). Therefor I am now focussing on making a UI wrapping around it (so all my time will go there until that is working).

That said, I am working on some new features that for now require the UI in some way (leech markets for example, see #513) that might open the door for some new stuff like watching multiple markets.

-----------

> Would be good if portfolioManager could work with a more than a single order at once and keep track of them.

Yes, the first thing would be to work out how to do this. When backtesting (or papertrading) the portfolioManager is not used (but the profitSimulator). So whatever the strategy is giving as advice, it should be fed to both the portfolioManager and the profitSimulator.

I am very open to suggestions on how to do this.

**Comment by greenbigfrog** [comment]
I think this is outdated

**Comment by askmike** [comment]
Yes, for anyone reading: this is out of scope.
