### ISSUE TITLE
Regression: profit simulator reports zero value when logging

### ISSUE THREAD

**Issue by osnwt** [askmike/gekko#518]
Initial: 0.010 BTC, 0.000 ETC

git checkout stable:

```
2016-12-07 14:10:00: Profit simulator got advice to short       0.010 BTC <= 0.000 ETC
2016-12-07 14:32:00: Profit simulator got advice to long        0.010 BTC => 9.562 ETC
                                                                ^^^^^
```
git checkout develop:

```
2016-12-07 17:10:00: Profit simulator got advice to short       0.010 BTC <= 0.000 ETC
2016-12-07 17:32:00: Profit simulator got advice to long        0.000 BTC => 9.523 ETC
                                                                ^^^^^
```

**From** value is always zero in both directions.

**Comment by askmike** [comment]
darn.. I just wrote a comment about how old that module is and how bad it needs refactoring..

Nice find, I think it only displays wrong numbers, but I'll recheck.

> From value is always zero in both directions.

What do you mean? Isn't the behaviour in develop how it should behave?

**Comment by osnwt** [comment]
It only displays wrong numbers.

It depends.
If was expected "all assets (now 0) converted to currency (now Y), then it is ok    **<- in develop**
If was expected "assets (was X) converted to currency (now Y), then it is not     **<- in stable**
Did you change you preferences?

The module might be old, but when I change something I try do not break what worked. Maybe you have another idea. Sorry, I think I should not bother you anymore.

**Comment by askmike** [comment]
> Sorry, I think I should not bother you anymore.

You found a bug, I am happy that you reported it (but not happy that there was a bug, my fault).

> If was expected "all assets (now 0) converted to currency (now Y), then it is ok <- in develop
> If was expected "assets (was X) converted to currency (now Y), then it is not <- in stable
> Did you change you preferences?

It is supposed to display how it now displays in develop, but that means that in stable it is wrong. I'll fix this asap!

**Comment by askmike** [comment]
I have rewritten the profitSimulator (now called paperTrader) and I've considered this 0 logging expected behaviour. If you still want to see this fixed reply here and I'll re-open.
