### ISSUE TITLE
Plugin MySQL

### ISSUE THREAD

**Issue by victorperin** [askmike/gekko#521]
I think using mysql could be a good plugin for Gekko and I'll work on it next weekend.

Since there's already a postgres plugin, this would be easy to implement.

Any advice and help here is accepted.

**Comment by askmike** [comment]
Hey @victorperin,

That would be awesome. The main thing to note is that I am working on a new version with an UI, that has some additional methods. The main adapter is the sqlite one, so might be good to use that one as a base.

Check out these files if you want to merge it into stable (no UI): https://github.com/askmike/gekko/blob/develop/plugins/sqlite/reader.js

And these if you want it to work with the UI:
https://github.com/askmike/gekko/blob/ui/market-watchers/plugins/sqlite/reader.js

**Comment by askmike** [comment]
if you have any specific questions, just let me know!

**Comment by mnofresno** [comment]
Hi @victorperin any news on this?

**Comment by victorperin** [comment]
Sorry, I forgot about it. hehe
I'll need to get a time to read the source again, to make it and I don't have such time now.

But It's in my backlog again, if i get any advance on this, I'll open a new issue.

**Comment by mnofresno** [comment]
@victorperin https://github.com/askmike/gekko/pull/2511

I think this is the same.

**Comment by victorperin** [comment]
Thanks! :)
Seems pretty solid. when I have some time, I'll try to fix those problems described in the issues.
