### ISSUE TITLE
feature request: include muteSoft in IRC module

### ISSUE THREAD

**Issue by Stoner19** [askmike/gekko#523]
I've been running several instances of Gekko for trading advice posted to IRC. Is it possible for the bot to include a `muteSoft: true` function on the IRC module?

**Comment by askmike** [comment]
Sure, would be simple to add. I am not sure when I have the time for this though.

**Comment by Stoner19** [comment]
I'm probably not knowledgable enough to know what to add, but I'll take a look at things to see if maybe I can figure it out. It doesn't appear that the IRC bot provides advice in line with that of [https://github.com/askmike/gekko/blob/7fde07b15703f5b98d7429b0b9e100f7be684c93/plugins/adviceLogger.js#L22](https://github.com/askmike/gekko/blob/7fde07b15703f5b98d7429b0b9e100f7be684c93/plugins/adviceLogger.js#L22) unless I'm just not setting it up right. All I see is 
```
[02:27:18 pm] testbot:	Guys! Important news!
[02:27:18 pm] testbot:	Advice for poloniex BTC/ETC using RSI at 30 minute candles, is:
[02:27:18 pm] testbot:	long ETC (from a few seconds ago)
```
(either long, short, or soft). Thanks for all your hard work Mike!

**Comment by Stoner19** [comment]
Pull request submitted and merged: https://github.com/askmike/gekko/pull/528
