### ISSUE TITLE
Warmup Period

### ISSUE THREAD

**Issue by KryptoNova** [askmike/gekko#527]
Hello @askmike  

I am really struggling with trying to integrate a method to signal to a plugin when the warm up period is completed.  My plan is to use some sort of indicator to be able to signal the trader that the last catch up candle was processed.  

I think this may be a good way to handle the problem during startup and initial load.  This way when that first load event is fired, it is a guarantee that all the current history has been loaded and that the recent advice that is processed is applicable to the real-time market conditions.  Perhaps using the "once" call so that the listener is removed after it is fired so it doesn't risk listening later.

I was able to modify how candles are processed a bit to use the update in the methods to determine when the last candle in a batch was processed.  However, this required a way to track the last candle in the batch being processed and individual candles are passed to that method.  I also didn't think it was a good idea to change the candle objects, because it is rudimentary to the gekko system and reused everywhere.
I also made a plugin listen to the tick event, but that may fire while the history is processing (if there is a lot).

If possible, could you point me to a place in the code where a "load done" event would make sense and could be fired so that listeners could take action based on the current trading advice?

Thank you and keep up the great work!

**Comment by askmike** [comment]
I am not sure if I exactly understand what your problem is.

> I think this may be a good way to handle the problem during startup and initial load. This way when that first load event is fired, it is a guarantee that all the current history has been loaded and that the recent advice that is processed is applicable to the real-time market conditions. Perhaps using the "once" call so that the listener is removed after it is fired so it doesn't risk listening later.

The main idea is that your strategy implements two methods: `update` and `check`. The first one is ran every candle (use indicator & calculation logic) while the second one only runs after the "warmup period". If you only call `advice` in your `check` method, your strat will never do anything before the warmup is done.

Is this not exactly what you need?

> If possible, could you point me to a place in the code where a "load done" event would make sense and could be fired so that listeners could take action based on the current trading advice?

What about [this](https://gist.github.com/askmike/30ab1744e21aa98d2c414e3a1dd78907)?

**Comment by KryptoNova** [comment]
Thank you for the suggestion.  I think I may have misunderstood what the warmup period means for gekko.  

What happened was when I was running the trader plugin, it fired buy and sell orders while reviewing three days of trading history from the DB being stitched with the exchanged.  This cause lots of long and short orders to be processed on information that was at least two days stale.

When I debug, the check method of the MACD.js method seems to be firing as historical candles are being processed.

The event that I am trying to handle is when all the data has been stitched from both the exchange and database.  My plan would be to process the long/short position that is recommended and take the safety off the trader plugin so buy/sell orders can happen.

Is there a place in the gekko code where such an emit event could live for interested methods or plugins to handle?

**Comment by askmike** [comment]
> What happened was when I was running the trader plugin, it fired buy and sell orders while reviewing three days of trading history from the DB being stitched with the exchanged. This cause lots of long and short orders to be processed on information that was at least two days stale.

> When I debug, the check method of the MACD.js method seems to be firing as historical candles are being processed.

That's def very strange! What version of Gekko are you running (what branch)?

-----

So it sounds to me like Gekko is not working properly for you. [This is the code](https://github.com/askmike/gekko/blob/develop/plugins/tradingAdvisor/baseTradingMethod.js#L210-L214) in gekko (note this is the `develop` branch):

    Base.prototype.propogateTick = function() {
      this.update(this.candle);
      if(this.requiredHistory <= this.age) {
        this.log();
        this.check(this.candle);
      }
      // (...)

`this.requiredHistory` is based on your config historySize (which is the warmup period). You could change this if check (for example, by registering the time gekko started and checking whether the current candle time is AFTER gekko start time).

**Comment by KryptoNova** [comment]
Thanks!
That may be my problem.  I was using the Stable branch.

I'll do my testing against develop and see if it behaves better.  Comparing the two different branches, I can definately see that the code is much different.

Thanks again and have a Merry Christmas!

**Comment by KryptoNova** [comment]
Hello @askmike ,
I tried the suggestion that you made about the develop branch.  When I tested, it was still firing buy and sell orders as it was processing historical candles.

What I am trying to find is a place in the code where I could determine that the loading from both the DB candles and the exchange are completed.  Is there someplace in the code that would indicate that the database and exchange candles are fully processed?

At that point, I would like to fire a one time event that tells gekko's trader that it is now OK to act on the most recent advice (buy/sell) and monitor the real time market.

Thanks!

**Comment by askmike** [comment]
> I tried the suggestion that you made about the develop branch. When I tested, it was still firing buy and sell orders as it was processing historical candles.

> What I am trying to find is a place in the code where I could determine that the loading from both the DB candles and the exchange are completed. Is there someplace in the code that would indicate that the database and exchange candles are fully processed?

So inside Gekko there are actually 3 different processes:

1. Determine how much history is needed. Example: 24 hours (1 day)
2. Figure out whether we have access to history until now (this includes mixing local available history with historical data provided by the exchange). If this turns out to be fully available the trading method will get seeded with this data.
3. The trading method does not know and care where data comes from, it will get fed data and as soon as it received as much data as needed (step 1) it will go on and call the `check` method.

-------

Could you be a little bit more specific about this:

> I tried the suggestion that you made about the develop branch. When I tested, it was still firing buy and sell orders as it was processing historical candles.

And maybe provide log files (turn on debug). I still don't understand exactly what Gekko does that you don't want it to do.

**Comment by KryptoNova** [comment]
Thank you for your response.  

I think you may have identified the problem I am having in item 3 above.  The method is firing off buy and sell orders as the history is processed through the trading method.  They appear to be queued while the trading method is loaded then processed as they are encountered after the method completes processing the candles.  The problem is shown in the attached log file at the very end where the two sell/buy
 orders are sent to the trader.

[Log.txt](https://github.com/askmike/gekko/files/679706/Log.txt)


My goal is to:
1) Create an alternative trader plugin that will not respond while the history is processed to buy/sell orders are not processed as market and db candles are stitched.
2) Utilize the last piece of advice that was part of the data stitching to direct the trader what needs to happen.
3) (Near Term) Utilize persistence of the prior trades to determine how to utilize the recommendation from step 2 above.
4) (Extra Long Term) Create an accounting plugin to handle events thrown by the alternative trader.

**Comment by KryptoNova** [comment]
I think that I may have figured out a place to do this and it seems to be doing exactly what I want it to.  In the /core/budfox/TradeBatcher.js, at this location: [https://github.com/askmike/gekko/blob/develop/core/budfox/tradeBatcher.js#L59-L61](url).

I modified this to emit an event to look like this:
```
  if(!amount) {
    this.emit('all_loaded');
    return log.debug('No new trades.');
  }
```
This will emit an all_loaded event to my custom trader plugin.  From there the trader plugin can be adapted to handle the event using `once` so that it stops listening after the first occurrence.  This is the code in the constructor of the listener in my custom plugin.
```
  var TradeB = require(dirs.budfox +'tradeBatcher');
  _.each(this, function(fn, name) {
    TradeB.prototype[name] = fn;
  });
  
  this.tradeB = new TradeB (require(util.dirs().core + 'exchangeChecker')
                            .settings(config.watch).tid);
  //This works to register the all_done in a plugin!!
  var hitIt = function () {
    log.debug("Hit It!!!");
  }
  this.tradeB
    .once('all_loaded', hitIt);
```
OUTPUT:
```
2016-12-31 22:33:19 (INFO):	We have new trading advice!
2016-12-31 22:33:19 (INFO):		 Position: long
2016-12-31 22:33:19 (INFO):		 Market price: 0.0138669
2016-12-31 22:33:19 (INFO):		 Based on market time: 2017-01-01 02:46:00

2016-12-31 22:33:38 (DEBUG):	Requested XMR/BTC trade data from Bittrex ...
2016-12-31 22:33:38 (DEBUG):	Hit It!!!
2016-12-31 22:33:38 (DEBUG):	No new trades.
2016-12-31 22:33:58 (DEBUG):	Requested XMR/BTC trade data from Bittrex ...
2016-12-31 22:33:58 (DEBUG):	No new trades.
```
I'm till very new to Node.JS and not yet confident if I am using it properly.  If you think that this is OK, please feel free to close this issue as resolved.  If you think this is not a good approach, then let me know what you would suggest to handle this differently.

Thank you very much for you time.  Hopefully, I can make some worthwhile contributions at some point in the future.

**Comment by KryptoNova** [comment]
Found this strategy was not working as I had hoped.  I think that timing the warm up period is probably a better approach. It seems this is how the software was intended to work and trying to change it is too much brute force.
