### ISSUE TITLE
Wrong start time for candle <60 minutes

### ISSUE THREAD

**Issue by edward81** [askmike/gekko#529]
I wanted to export some generated data to csv.  
I made a custom indicator based on macd.js to log to a file the data. In this way i noticed duplicated dates on the data. This happen if you set the _candleSize_ with a value <60minutes.  
I made a printout on _method.check_ with _this.candle.start.format('DD/MM/YY HH:MM')_
This is the result:
```
19/11/16 07:11	740.00
19/11/16 08:11	739.00
19/11/16 08:11	744.30
19/11/16 09:11	744.00
19/11/16 10:11	739.86
19/11/16 11:11	741.66
19/11/16 11:11	739.30
19/11/16 12:11	740.99
19/11/16 13:11	740.22
19/11/16 14:11	739.55
19/11/16 14:11	739.90
```

**Comment by decoye** [comment]
hey edward, how do you create those reports?

**Comment by askmike** [comment]
What are you logging besides the dates? If that's price it doesn't look very good, as the candles on the same date log different numbers.

Gekko tries to merge local data to exchange data, strange that it bugs. What branch are you running?

**Comment by edward81** [comment]
@decoye with this:
http://pastebin.com/4XyqAsK2
@askmike 
Yes is the price. Develop branch

**Comment by edward81** [comment]
Okay, I thought I was wrong, but I have to reopen this bug. Using Talib Indicator, incoming candles on "strategies/talib-macd.js" are wrong with duplicate timestamp If you set a candle size different of 60 minutes, try 30 minutes for example.. A simple print on the exec method lets you see what I mean https://pastebin.com/jUgvUq5W

**Comment by greenbigfrog** [comment]
@edward81 is this still a issue?

**Comment by askmike** [comment]
This is a design decision: if gekko where to round candles to hours it would become easy to predict and thus game.

**Comment by Neon-Ice** [comment]
Using : this.candle.start.format('DD/MM/YY HH:MM') 
gives you months instead of minutes in the time formatting.
Use : this.candle.start.format('DD/MM/YY HH:mm')
