### ISSUE TITLE
Get balance in method

### ISSUE THREAD

**Issue by BarnumD** [askmike/gekko#534]
If I wanted to get the account balance (simulation or real) in my method what variable would I call to get that?

**Comment by askmike** [comment]
You can't right now unfortunately, the trading method currently has no concept of a portfolio/funds. This is to make it easier to use simulation or real balance (or both / neither).

But I do think this could be very helpful, could you explain a little bit what it is you are trying to achieve in your method?

**Comment by BarnumD** [comment]
I'm thinking about making a method that adjusts the amount invested based on market indicators and available balance.  Although, now I realize that adjusting the amount invested per trade is also not supported, is it?

While I'm on the subject it seems like a lot of investors would use advanced strategies to buy into a position (ie, not all at once at a single price.)  Perhaps that could be another feature request.

**Comment by greenbigfrog** [comment]
@askmike I think this has been implemented

**Comment by wahnker** [comment]
I would also like to be able to read the balance.

**Comment by hilkoc** [comment]
> @askmike I think this has been implemented

@greenbigfrog I need this feature too. Can you show me how it has been implemented? or how to use it?
Thanks!

**Comment by askmike** [comment]
Unfortunately this will stay out of scope for a while, while we are introducing very limited data to go into the strategy (stoploss / take profit triggers) this will remain extremely limited.
