### ISSUE TITLE
Says buy successful on bitstamp but no trade or order made

### ISSUE THREAD

**Issue by joelbrennan0** [askmike/gekko#538]
Hi,

Everything was fine until today and made several trades on BitStamp without any issue.  However something seems to have gone wrong today..

Here is the terminal output:

2017-01-03 14:09:03 (INFO):     (PROFIT REPORT) original simulated balance:      71.01750 USD
2017-01-03 14:09:03 (INFO):     (PROFIT REPORT) current simulated balance:       71.32758 USD
2017-01-03 14:09:03 (INFO):     (PROFIT REPORT) simulated profit:                0.31008 USD (0.43663%)
2017-01-03 14:09:03 (INFO):     Attempting to BUY 0.06852757002924836 BTC at Bitstamp
2017-01-03 14:10:04 (INFO):     BUY was successfull

But nothing happened on BitStamp ... No order or anything.

Trader is enabled, and to my knowledge I haven't changed anything apart from DEMA / MACD config settings.

Can anyone offer any advice please?

**Comment by askmike** [comment]
you enabled a trade simulator. Enable the real trader!

**Comment by askmike** [comment]
Is this closed because it did buy? Or?

**Comment by joelbrennan0** [comment]
Hi,

Thanks for getting back Mike, sorry for being a pain, its more than likely I'm doing something wrong here and getting into a panic.

I have deleted everything and cloned anew to be sure..

The old version was selling but not buying on advice.

I can't work out if the new version is buying or not.

I'm still having weirdness happening, sells fine but says it's attempting to / buy successful  but never see any evidence of the buy order on bitstamp:
cant figure this out.. ( please see attached output:)
[gekko1mCandle.txt](https://github.com/askmike/gekko/files/684911/gekko1mCandle.txt

After this run I'm still in USD, is that correct?

Sorry I should try and get this on my own but haven't had time to look under the hood yet.  I'm really not familiar with node apps either.

Is there any good way of debugging you can recommend to me?  could I catch the query string data and see whats happening?  Are you able to help point out where I'm going wrong?

Please let me know if you need any further information.

Cheers...  I'll keep trying.. It's probably something silly I'm doing this end..

**Comment by joelbrennan0** [comment]
Also I f**kd up and didn't back up my sqlite history so I'm starting again there :/  any body have a bitstamp file they may be able to share for the last couple of days?  At this stage I'm not too worried about the settings I just want to confirm that buy / sell orders are being executed as intended.

Thx

**Comment by joelbrennan0** [comment]
update: Maybe a credentials problem from bitstamp as I'm now getting the following error: 
C:\Users\Joel\Desktop\Programs\TradeBots\gekko\exchanges\bitstamp.js:45
    if(!_.isEmpty(data.error))
                      ^

TypeError: Cannot read property 'error' of undefined
    at Trader.<anonymous> (C:\Users\Joel\Desktop\Programs\TradeBots\gekko\exchanges\bitstamp.js:45:23)
    at IncomingMessage.<anonymous> (C:\Users\Joel\Desktop\Programs\TradeBots\gekko\node_modules\bitstamp\bitstamp.js:48:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

I'll reset my API key and try all again..

Sorry keep having problems, everything seemed great for a while.  Not sure what went wrong.

**Comment by joelbrennan0** [comment]
Hi Mike,

Seems the problem was somewhere within my credentials or something specific to BitStamp.

Switched everything back to btc-e and all is fine.  The only reason I was running on BS is as I said I'm running a c# bot on btce concurrently with gekko.  Therefore I have done a quick and dirty change in btc-e.js to only trade .33% of my balance thru gekko and added to .gitignore.

Now I seem to be able to use both bots together on btc-e which is exactly what I wanted in the first place so all is good please mark my problems resolved!

Thx for your help.

**Comment by joelbrennan0** [comment]
Sorry I closed it because I wasn't sure if it was an issue or not.  But the gekko bot stopped executing BUY trades on BitStamp.  It works fine on btc-e so that's good for me.  Thank you for sharing the gekko bot.  It is great.

Thank you

Joel

**Comment by sidren** [comment]
I'm also unable to BUY from BitStamp. Selling seems to be going fine, but GEKKO reports "BUY successful" and it doesn't even place an order?
