### ISSUE TITLE
Exit market advice?

### ISSUE THREAD

**Issue by BarnumD** [askmike/gekko#541]
The docs say advice is either long or short (buy or sell short.)  Is there such a thing as advice to exit the market. ie, if long position open - close the position by placing a sell.  If short position open - close the position by placing a buy.  The thought behind it would be to implement some kind of strategy that attempts to take some or all profits at a certain point but does not necessarily want to switch from long to short.  Maybe the advice would stay long or maybe it would just be to exit the market altogether.

Can you give gekko advice like that?

**Comment by askmike** [comment]
Even though the trading methods advice either "long" and "short", the real trader (nor the paper trader) do not actually short: For now this is mapped to "buy" and "sell". This makes it easy to implement what you want by advicing short (to take profits). Advicing short will close out the position of {asset} and take a full position in {currency}
