### ISSUE TITLE
Data Visualization by Plotting the price chart... anyone?

### ISSUE THREAD

**Issue by SkaTeMasTer** [askmike/gekko#555]
I think it would be interesting to add some simple histogram data to plot the data you've processed as well as snapshots when notifications are send...

example:

from pylab import plotfile show, gca
   import matplotlib.cbook as cbook
   fname = cbook.get_sample_data('amzn.csv',
   asfileobj=False)
   plotfile(fname, ('date', 'high', 'low', 'close'), subplots=False)
   show()

Matplotlib already has a working example to plot the stock chart, which is elaborate enough and includes Relative Strength Indicator (RSI) and Moving Average Convergence/Divergence (MACD), and is available at 

http://matplotlib.org/examples/pylab_examples/finance_work2.html

The coding is quick and clean, anyone else agree?

**Comment by ofek-a** [comment]
Isn't a web UI being worked on as we speak? I think it would make more sense to use the web UI for that and perhaps take a snapshot from there.

**Comment by askmike** [comment]
@OfekA is right, please take a look at #489. But note that I have been extremely busy and will be the coming time. So I won't have a lot of time to work on this.

Note that currently this does not include graphing indicators. Though this is definitely not hard to add.

**Comment by SkaTeMasTer** [comment]
I was just imagining that a snapshot of date range could be sent along with a "notification", as they say in pictures and thousand words.  ;)
