### ISSUE TITLE
Add ability to specify the "last buy or sell price" when run Gekko

### ISSUE THREAD

**Issue by tregismoreira** [askmike/gekko#567]
Here's the scenario:

You set the parameters and start the bot. It's tracking your profit, let's say you have 5% so far... Then you figure out that you could change some specific parameter. So you will have to stop the bot, change the parameter and start again.

This way, the bot won't know the last buy/sell price and it won't know your profit so far... Then it will start tracking over again and won't display the correctly profit.

What if we add a parameter to `node gekko` to set the last buy/sell price? Then I guess the bot will calculate the profit right.

**Comment by askmike** [comment]
better would be to store trades in a database, so Gekko can figure out what happened in the past.

**Comment by askmike** [comment]
If this were to be implemented, I'd say it has be configured using the UI. Unfortunately I don't have time this soon.

**Comment by thegamecat** [comment]
This is not so easy as you would need to get the actual trades from the exchange. Indeed this is probably the best way of getting a pnl from live trading.

**Comment by askmike** [comment]
@thegamecat I have been thinking about the same for a while, what about this? #693.

After we have that table as a base, we can use it like so:

- for backtesting & paper trading, simulate all data
- for live trading ask the exchanges at what price all orders were filled & populate table using REAL numbers :)

**Comment by thegamecat** [comment]
That is spot on man!

I will try and test this on the dev branch tomorrow. 

What is the function / file that actually places the trades, works out how much can be placed (ie 100% of currency / asset....

**Comment by askmike** [comment]
@thegamecat

for simulation (paper trading & backtesting): https://github.com/askmike/gekko/blob/stable/plugins/paperTrader/paperTrader.js
for real trading: https://github.com/askmike/gekko/blob/stable/plugins/trader/trader.js

**Comment by greenbigfrog** [comment]
This can be closed

**Comment by dragonlong206** [comment]
Dear sir
Do we have this function right now and how to achieve this? I need last buy/sell price to test a new strategy.
Thanks
