### ISSUE TITLE
Is REST API available?

### ISSUE THREAD

**Issue by michaldev** [askmike/gekko#568]
I would like create mobile application, for control bot (like that web dashboard). Do you share rest api?

**Comment by askmike** [comment]
You are talking about the rest API exposed by the web wrapper (dev branch)? Yes you are free to build whatever you want! However I have not written docs for it, but the comments should be clear enough:

- here are [all API routes](https://github.com/askmike/gekko/blob/develop/web/server.js#L38-L48)
- here is a [sample comment of an API route](https://github.com/askmike/gekko/blob/develop/web/routes/scanDatasets.js#L6-L9)

And if you can't figure it out, feel free to ask (or look at the frontend code). Note that updates for running gekkos (early stage) are broadcasted over websockets.
