### ISSUE TITLE
Gatecoin integration

### ISSUE THREAD

**Issue by milkeg** [askmike/gekko#571]
Hello,
I would like to integrate GateCoin exchange (https://api.gatecoin.com/swagger-ui/index.html).
I couldn't find any guideline on how to integrate the exchange in Gekko.
Could you provide some guidance / guidelines ?
Thanks,

**Comment by askmike** [comment]
Read this document:

https://github.com/askmike/gekko/blob/stable/docs/internals/exchanges.md

And if you run into issues, feel free to ask!
