### ISSUE TITLE
Bitx currency pairs not supported

### ISSUE THREAD

**Issue by HappyMan811** [askmike/gekko#572]
The current exchange "bitx" exists , but apparently the currency pair of XBT and ZAR are not supported even though they exist in the exchanges file. Would like to understand what may cause it to do that.

**Comment by hoddy** [comment]
From where I'm sitting it's looks like it is already ready to work on those currencys, have you written in the variables exactly as they appear in exchanges.js?

**Comment by HappyMan811** [comment]
Thank you for your reply , Yes I have.

**Comment by askmike** [comment]
Can you post the exact error?

**Comment by HappyMan811** [comment]
'' Gekko does not support this currency/assets pair''

 exchange: 'bitx',
 currency: 'ZAR',
 asset: 'XBT'

**Comment by askmike** [comment]
Can you try again (by downloading the develop branch)?

**Comment by HappyMan811** [comment]
still getting the same error

**Comment by HappyMan811** [comment]
Never mind , was pulling the wrong project. It is working now . Thank you very much for your help

**Comment by askmike** [comment]
👍  if you run into anything else, feel free to ask.
