### ISSUE TITLE
Trader, buy in limitations

### ISSUE THREAD

**Issue by decoye** [askmike/gekko#576]
Hey, 

for the real money trader i have a idea.

i think a feature is great that lets the trader only buy if the uptrend is less then a defined amount.

The Problem is, if the gekko stopped for like 4 hours and a trend has changed, then the trader would make a buy, even tho the "good" point for a buy in to this trend is long gone.

What do you think about this?

**Comment by askmike** [comment]
Sorry for never responding to this.

> The Problem is, if the gekko stopped for like 4 hours and a trend has changed, then the trader would make a buy, even tho the "good" point for a buy in to this trend is long gone.

I'm not sure what you mean: if gekko stops no trades are made, and if you start it again it will wait a certain amount of candles before being sure about the trend.

**Comment by decoye** [comment]
My gekko behaves differently.
gekko has history available of the exchange, and when i start it it things it shall trade. means he can be in a short or long period. but nessesarily never the right moment to be in one when its getting started...

thats why im making that request.
so gekko sees, that he has passed the trend and does not chase the trend.
