### ISSUE TITLE
Does anyone have historical btc-e.com btcusd data?

### ISSUE THREAD

**Issue by thegamecat** [askmike/gekko#581]
Hi, does anyone have historical btc-e.com btcusd data they can share?

And if not, what format/schema does a file need to be to import btce data?

**Comment by jonathancross** [comment]
**Edit:** should point out that [importing data from btc-e is not supported](https://github.com/askmike/gekko#supported-exchanges).

You could probably buy this data from bitcoinaverge.com: info@bitcoinaverage.com
They offer direct [download of historical average data](https://bitcoinaverage.com/en/data-store/historical-bitcoin-exchange-rates), but not segregated by exchange.  Their API might be another option, but I couldn't get it to work for this purpose.

**Comment by thegamecat** [comment]
Thanks. I'm assuming I can throw all the 1m candles into sqlite?

**Comment by thegamecat** [comment]
The answer is yes, you can put any amount of historical data into the sqlite db in 1 minute candles.

**Comment by askmike** [comment]
Let me know if you run into problems converting the data to the exact format expected by Gekko.

**Comment by thegamecat** [comment]
All good. I wrote a php candle writer and used that. Took a while to do the conversion from 2011 to today but it worked.
