### ISSUE TITLE
I can not load --ui on windows

### ISSUE THREAD

**Issue by maxpingo** [askmike/gekko#585]
I am trying to load the command --ui in windows I do not know if the path is correct.
C:\Users\Administrator\Desktop\gekko-stable\gekko-stable>node gekko --ui

  error: unknown option `--ui'
Thanks to all this is a great project
![screenshot_57](https://cloud.githubusercontent.com/assets/25653864/22769529/6eef2206-ee70-11e6-9f0a-e36f3e2bcaf2.png)

**Comment by richardpetithory** [comment]
The ui is not in the stable branch yet. Use the develop branch.

**Comment by maxpingo** [comment]
I thought it was working because I found a video, you can measure some tips on how to use, I want to operate in poloniex and bitstamp?

**Comment by rcalastro** [comment]
you have to download the latest gekko-develop branch (instead of gekko-stable). After that you will be able to run "node gekko --ui"
