### ISSUE TITLE
Sells but wont buy on bitstamp

### ISSUE THREAD

**Issue by sidren** [askmike/gekko#590]
Anyone else having an issue with Gekko placing buy orders on bitstamp? I see no open orders, and gekko states the buy is successful. 

Ive gotten it working on btc-e, but something seems up with bitstamp?

Thanks for any help

**Comment by jjongman** [comment]
#538. I submitted a pull request to work around this.

**Comment by sidren** [comment]
Thanks!

**Comment by greenbigfrog** [comment]
@askmike can most likely be closed, has been fixed
