### ISSUE TITLE
But not selling at good % idk why

### ISSUE THREAD

**Issue by ghost** [askmike/gekko#591]
i'm running gekko since 15/02 so they make a good "long" position, and i take like 4% but they don't sell... and i'm loosing today -4%. Gekko don't have "stop" or something like that to move if you got loosing position? And he's not selling with good % at poloniex... 3 days and no sell activities... but in backtest works good

**Comment by askmike** [comment]
Gekko automates your strategies, if the one from Gekko isn't working, please write your own:

https://github.com/askmike/gekko/blob/stable/docs/trading_bot/creating_a_trading_method.md
