### ISSUE TITLE
Unreliable data import @ poloniex

### ISSUE THREAD

**Issue by generalectric** [askmike/gekko#593]
Ok so I've been backtesting multiple currencies at poloniex. What I've found is that trending data over the course of months to a year on all currencies with high profit percentages are completely different from numbers gathered from watching the market in real time. For instance I watched a coin for the last 48 hours. My half year of backtesting went from 6000% yearly profit to 1000... With just 48 hours of realtime data added to the db. I've come to the conclusion that using the import data from poloniex is totally unreliable and found that creating a method with the real time data requires totally different settings to run profitably

**Comment by generalectric** [comment]
Accidentally hit submit before I was finished. Anyways I just wanted to see if this is an issue for anyone else. Thanks!

**Comment by generalectric** [comment]
works fine just delete db and do a fresh import. closing this issue

**Comment by askmike** [comment]
Ok great, if you do have think there is weird behaviour between import and live market data do let me know (as well as more detailed information to debug).
