### ISSUE TITLE
ta-lib giving "undefined symbol TA_IMI"

### ISSUE THREAD

**Issue by voidzero** [askmike/gekko#597]
This might be out of scope but I couldn't find info elsewhere - when trying to run with talib (on Linux, x86_64) I am getting:

<pre>
Error: /user/gitrepos/gekko/node_modules/talib/build/Release/talib.node: undefined symbol: TA_IMI
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /user/gitrepos/gekko/core/pluginUtil.js:28:19
    at Function.forEach (/user/gitrepos/gekko/node_modules/lodash/dist/lodash.js:3298:15)
    at Object.cannotLoad (/user/gitrepos/gekko/core/pluginUtil.js:26:9)
    at Object.<anonymous> (/user/gitrepos/gekko/core/baseTradingMethod.js:18:33) '\n\n'

Meta debug info:

Gekko version: v0.3.4
Nodejs version: v7.5.0
</pre>

**Comment by thegamecat** [comment]
Did you author an indicator?

**Comment by askmike** [comment]
And exactly which indicator where you trying to use? Could you please test if it works with the develop branch?

**Comment by voidzero** [comment]
I haven't authored an indicator. Just went with most of the defaults. I was testing it with the MACD indicator. I'll test the development branch and check back in.

**Comment by thegamecat** [comment]
Unless I'm mistaken I think you need to create a method, add it to the config and then you can run it. How are you trying to call the method?

**Comment by askmike** [comment]
@thegamecat,

**Comment by askmike** [comment]
If the issue persists on develop, please reopen!

**Comment by askmike** [comment]
@thegamecat 

> Unless I'm mistaken I think you need to create a method, add it to the config and then you can run it. How are you trying to call the method?

it appeared to be an issue with talib using methods that came with Gekko.

**Comment by voidzero** [comment]
Ok, just tried it on develop - exactly the same issue. I haven't changed much in the config, basically all I did was to set config.tradingAdvisor.talib.enabled to true. And, if it matters (which I doubt but just in case) - I am using postgresql.

The backtrace is exactly the same.

I can't reopen the issue - not enough permissions - so hope you can do that for me @askmike. Cheers.

**Comment by askmike** [comment]
When you said:

> basically all I did was to set config.tradingAdvisor.talib.enabled to true.

So exactly what trading method were you trying to run? The error you posted comes from TAlib, which is not used when using the default 'MACD' trading method.

**Comment by voidzero** [comment]
I see. That might be it then. I'm not sure - this is all a bit new to me as you probably guessed. Here is the relevant portion of the config:

```javascript
config.tradingAdvisor = {
  enabled: true,
  method: 'MACD',
  candleSize: 60,
  historySize: 25,
  adapter: 'postgresql',
  talib: {
    enabled: true,
    version: '1.0.2'
  }
}
```

and

```javascript
// MACD settings:
config.MACD = {
  // EMA weight (α)
  // the higher the weight, the more smooth (and delayed) the line
  short: 10,
  long: 21,
  signal: 9,
  // the difference between the EMAs (to act as triggers)
  thresholds: {
    down: -0.025,
    up: 0.025,
    // How many candle intervals should a trend persist
    // before we consider it real?
    persistence: 1
  }
};
```

**Comment by askmike** [comment]
Could you turn debug on and post the full log?

**Comment by voidzero** [comment]
I assume you mean config.debug = true. When I set that the output is not much different. The only lines marked [DEBUG] are related to connecting with the postgresql database succesfully. The rest, until the error (already posted above):

```
(INFO):     Setting up:
(INFO):              Trading Advisor
(INFO):              Calculate trading advice
(WARN):              Config already has MACD parameters. Ignoring toml file
(INFO):              Using the trading method: MACD
(ERROR):    ERROR LOADING DEPENDENCY talib

Gekko encountered an error and can't continue
```

**Comment by askmike** [comment]
You can disable TAlib in your config: TAlib is [a library](http://ta-lib.org/) that has a lot of indicators. But Gekko won't use it unless you use a trading method that relies on a talib indicator (the only method that comes with gekko is [talib-macd](https://github.com/askmike/gekko/blob/develop/methods/talib-macd.js)). Simply enabling it will only load the module (which is failing for you).

If you do want to create your own method using talib indicators, we can debug this further: could you try to installing node 6.6.0 (that is what I am running without any talib problems).

**Comment by voidzero** [comment]
Alright, I just did. Node 6.6.0, removed my node_modules dir, and reinstalled using npm install, followed by pushover-notifications@0.2.4 irc pg talib. Then when I tried to execute, I got exactly the same issue. I've also added feedback to an already existent issue ticket over at the talib github: https://github.com/oransel/node-talib/issues/39 So far no response there though, sadly.

**Comment by askmike** [comment]
Ah darn,

So to reiterate: you only need talib if you want to run a method that relies on a talib indicator, which is only really a problem when creating your own methods.

As for other possible solutions: There is another low level library supporting a lot of indicators: https://tulipindicators.org/ We could try to integrate that in gekko as well (using [this wrapper for example](https://www.npmjs.com/package/tulind))
