### ISSUE TITLE
UI not working properly

### ISSUE THREAD

**Issue by nicolinux** [askmike/gekko#601]
Ok, I know this is the development branch. I just tried to at least get to the state that was shown in the last video where one could run backtests against some data. Right now when I pull the latest dev branch and start gekko with the "--ui" option, this is the only output I get in the logs (using docker):

```
# docker logs -f gekko
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 9

    ______   ________  __    __  __    __   ______
   /      \ /        |/  |  /  |/  |  /  | /      \
  /$$$$$$  |$$$$$$$$/ $$ | /$$/ $$ | /$$/ /$$$$$$  |
  $$ | _$$/ $$ |__    $$ |/$$/  $$ |/$$/  $$ |  $$ |
  $$ |/    |$$    |   $$  $$<   $$  $$<   $$ |  $$ |
  $$ |$$$$ |$$$$$/    $$$$$  \  $$$$$  \  $$ |  $$ |
  $$ \__$$ |$$ |_____ $$ |$$  \ $$ |$$  \ $$ \__$$ |
  $$    $$/ $$       |$$ | $$  |$$ | $$  |$$    $$/
   $$$$$$/  $$$$$$$$/ $$/   $$/ $$/   $$/  $$$$$$/

	Gekko v0.4.4
	I'm gonna make you rich, Bud Fox.


Serving Gekko UI on http://localhost:3000/

Feb 25 13:06:25 03443f219dd1 syslog-ng[15]: syslog-ng starting up; version='3.5.6'
  <-- GET /favicon.ico
  --> GET /favicon.ico 404 8ms -
```

I am able to use the interface but it won't find any datasets or it does not import anything. Without the "--ui" option I am able to run backtests or import data just fine.
Is there something I am missing? An user error?
I also see that gekko when started with "--ui" does not output its usual trading info (scraping Poloniex now). I have the impression that with "--ui" it just powers the interface and does nothing else.
Maybe I don't understand how it should be used - so sorry if this is an user error...

**Comment by askmike** [comment]
Yes, the `--ui` flag simply starts a server and will ignore your normal config, using the interface generates new configs (depending on what you are doing) on the fly and run those silently (in child processes).

> I am able to use the interface but it won't find any datasets or it does not import anything.

It looks like you are using docker, do you experience the same without docker? The dockerized version relies on volumes for historical data I think.

**Comment by nicolinux** [comment]
Ok, thanks for the clarification. So the ui should only be used for backtests and importing data (so far).
Can I safely start another gekko process with the usual config next to the one with the ui?

With Docker I have created a dedicated volume where the sqlite db resides. When I start the very same container without the `--ui` flag, it is able to find the old data sets. I am starting the docker container like this:

```
docker run -d -v /opt/docker/mount/gekko-cfg-mount/service_start_gekko.sh:/service_start_gekko.sh  -v /opt/docker/mount/gekko-cfg-mount/config.js:/usr/src/gekko/config.js -v gekko-history:/usr/src/gekko/history -p 3000:3000 --name gekko barnumd/gekko
```

**Comment by askmike** [comment]
> So the ui should only be used for backtests and importing data (so far).

In the future (soon hopefully) you can do everything with the UI.

> Can I safely start another gekko process with the usual config next to the one with the ui?

Yes, though you might run into rate limits if you start importing and running a normal gekko on the side (depending on exchange). There might be some issues with the database being locked, but you can always try and see what happens (I am not sure how the docker volume effects sqlite on the FS level).
