### ISSUE TITLE
Email advisor extra functions

### ISSUE THREAD

**Issue by decoye** [askmike/gekko#615]
Hello,

id like to add ome functions to gekko,  but i wonder if people would find them useful.

I think it would be helpful to get info about the current standing on your account with email or message.

and also the achieved profits since gekko is running your strategy.

would this be possible/helpful for someone?

**Comment by askmike** [comment]
> I think it would be helpful to get info about the current standing on your account with email or message.

Sounds great! There is a plugin already that will email every new advice. You can take a look at that plugin [here](https://github.com/askmike/gekko/blob/stable/docs/Plugins.md#mailer) and [here](https://github.com/askmike/gekko/blob/stable/plugins/mailer.js).

> and also the achieved profits since gekko is running your strategy.

So you mean real profits for people using the real trader? Sounds great, that is definitely something that a lot of people requested.

----

So go ahead! And let me know once you need any help :)

**Comment by decoye** [comment]
Yeah great.

I started to alter the information gekko sends with telegram. But in a very basic fashion.
Question is.

Where does gekko put the standing, what's the variable name?
I assume it's in trading advisor plug in but can't manage to parse it into my telegram code.

**Comment by askmike** [comment]
What do you mean with "standing"? The idea is that all modules (plugins)
are decoupled and interact via events. When the tradingAdvisor (which
implements a trading method) has new advice, other plugins are notified via
an event broadcasted by the trading advisor.

**Comment by decoye** [comment]
Standing would be the current amount that your account holds.

How do I access the variable that the trader creates when he calculates to long or short?

- sent from iphone -

Mit freundlichen Grüßen
Andreas Schindler


Schindler Lichtdesign
Warstr 20a 30167 Hannover
Germany.

www.andreasschindler.com
info@andreasschindler.com

Mobil: +49 151 25 31 42 66 
Buero:  
+49 511 71 300 385





> Am 08.03.2017 um 17:35 schrieb Mike van Rossum <notifications@github.com>:
> 
> What do you mean with "standing"? The idea is that all modules (plugins)
> are decoupled and interact via events. When the tradingAdvisor (which
> implements a trading method) has new advice, other plugins are notified via
> an event broadcasted by the trading advisor.
> 
>

**Comment by askmike** [comment]
> Standing would be the current amount that your account holds.

This would not be something the tradingAdvisor would know about, the tradingAdvisor just emits advice from a trading method. The trader (which implements a portfolioManager) would pick up this advice and figure out whether we can perform a trade.

If you want to know account balance in a plugin (sounds very reasonable) we should emit an event from the trader like "portfolioUpdate" which other plugins (like an email plugin, or a telegarm plugin) can subscribe to.

> How do I access the variable that the trader creates when he calculates to long or short?

What variable do you mean?

**Comment by thegamecat** [comment]
This would be very cool indeed.

**Comment by thegamecat** [comment]
Decoye, you posted a graph of a backtest on here a while back. How did you build the graph? It would be a really helpful tool for this.

**Comment by decoye** [comment]
> How do I access the variable that the trader creates when he calculates to long or short?
>>What variable do you mean?

there must be something in memory that holds my account balance, both fiat and currency.
i should be able to put this information into a variable that i can access with the email advisor or telegrambot.

the graph is from the web ui.

**Comment by askmike** [comment]
@thegamecat 

> How did you build the graph?

Have a look here: #489.

> there must be something in memory that holds my account balance, both fiat and currency.

Ah yes, there is. Though because of how modularized Gekko is this is not accesable by other plugins (like email advisor or telegrambot). As said before:

> If you want to know account balance in a plugin (sounds very reasonable) we should emit an event from the trader like "portfolioUpdate" which other plugins (like an email plugin, or a telegarm plugin) can subscribe to.

I'll will update Gekko (ASAP) so that plugins can act on an updated portfolio like so:

    processPortfolioUpdate = function(portfolio) {
      // portfolio is an array like
      // [ { name: 'BTC', amount: 5 }, { name: 'USD', amount: 100 } ]
    }

[(the same as how new candles are now being given to plugins)](https://github.com/askmike/gekko/blob/stable/plugins/mailer.js#L93).

**Comment by askmike** [comment]
To come back on your original idea:

> I think it would be helpful to get info about the current standing on your account with email or message.

Right now it emails advice from the trading method, which is not very useful if gekko is trading for real (in this case it would be better to email a report of the trade, together with the new portfolio). You could implement this as a setting in the mailer via the config.

----

I am closing this now, but feel free to ask questions here and open a PR if you have some code.
