### ISSUE TITLE
UI Gekko Importing Data abort option

### ISSUE THREAD

**Issue by decoye** [askmike/gekko#620]
Hey Mike, 

when i import data from a Exchange, and i define the range of 2017-01-01 00:00:00 to 2017-03-09 12:00:00.

it tells me wrong time range. that is probably just an issue of me.

but, if i define a wrong timerange it still trys to import this range and therefore will never stop to do so. a button to abort the scan would be nice. even for a scan that hast started if you incase made a mistake or something.

**Comment by askmike** [comment]
If I use those dates it works great, can you post a screenshot of the error?

**Comment by decoye** [comment]
Sorry, but now im also not able to reproduce it.
excuse me, fault on my side.

**Comment by askmike** [comment]
No problem, I am happy people are testing it out!

**Comment by ConorCorp** [comment]
Hey, So I accidentally ran 2 data imports of pretty much the same range within the UI, I'd definitely like to second the option for an 'abort' button on the /imports page under the 'currently running imports' section as well as on the actual import's own page.
