### ISSUE TITLE
Gekko crashes on new kraken account.

### ISSUE THREAD

**Issue by decoye** [askmike/gekko#621]
Hello.

As it seems, gekko crashes on new kraken accounts that did not have made any transactions yet and only hold one currency.
Let's say account is holding 0.1btc.
You start gekko with trader plug in.
Gekko will notice 0.1 btc and stores it. But the 0.0000€ wont be read by gekko.
It seems kraken does not supply this value with no trade yet on this account.
Once you made a sale everything works fine.

Gekko crashes with undefined err in fund, the moment he wants to trade long.

**Comment by askmike** [comment]
that should not happen on latest develop. Can you post the full error log (with debug enabled)?

**Comment by decoye** [comment]
can you give me a heads up of how to enable debug?

i dont have a vanilla kraken account available tho.
