### ISSUE TITLE
Develop: Using Sqlite instead of Mongodb + Mongodb broken

### ISSUE THREAD

**Issue by domgolonka** [askmike/gekko#625]
I am trying to use the importer with mongodb.

Even when changing the config.js, Gekko is using sqlite from the web/route/baseConfig.js file. 

When changing baseConfig to 'mongodb' as the adapter, it gives the error:

> gekko/plugins/mongodb/handle.js:12
>   dependencies: config.adapters.mongodb.dependencies
>                                ^
> 
> TypeError: Cannot read property 'mongodb' of undefined
>     at Object.<anonymous> (/Users/domzmac/Documents/webdev/gekko/plugins/mongodb/handle.js:12:32)
>     at Module._compile (module.js:571:32)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
>     at Module.require (module.js:498:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/Users/domzmac/Documents/webdev/gekko/plugins/mongodb/writer.js:8:14)
>     at Module._compile (module.js:571:32)
> RECEIVED ERROR IN IMPORT 454450365356766
> Child process has died.

**Comment by askmike** [comment]
> Gekko is using sqlite from the web/route/baseConfig.js file

What branch are you on? And how are you running the importer?

**Comment by domgolonka** [comment]
I am using the "develop" branch and import using the ui.

**Comment by askmike** [comment]
Unfortunately all adapters (except for sqlite) are not working in the UI, gekko needs some additional calls which are not implemented yet in anything but sqlite.

I've added this to the todo (#611)!
