### ISSUE TITLE
CLI Dev -  ERROR: Please specify a config file.

### ISSUE THREAD

**Issue by thegamecat** [askmike/gekko#627]
I have config.js but I'm guessing it's in the wrong place. Where should it be to support CLI backtesting?

**Comment by askmike** [comment]
I want to move towards the UI being the default way to use gekko. Gekko CLI is still supported, but you simple need to specify where the config is, for example:

    node gekko --config config.js

**Comment by thegamecat** [comment]
So node gekko --backtest --config config.js ?

Understand the desire to use the UI but it would be great to keep the CLI as it actually provides more information and is easier to interact with when writing new strategies. 

(it also currently supports backtests which the UI doesn't, as discussed)

**Comment by askmike** [comment]
You are right, and I will definitely keep the CLI version around.

I updated a lot of documentation in the [develop branch](https://github.com/askmike/gekko/tree/develop): it suggest to run the UI on default, and CLI related stuff has been moved to to [docs/advanced_usage](https://github.com/askmike/gekko/tree/develop/docs/advanced_usage). But I do need to write a document explaining how to run the CLI version (with config flag, etc).

> (it also currently supports backtests which the UI doesn't, as discussed)

I want to merge dev into stable soon, and this is one of the few things I still need to fix before I can do that. Note that the talib bug is fixed now (you can now run talib-macd in the UI - if you have talib installed, just not other custom methods).

**Comment by thegamecat** [comment]
Yep, don't worry about that issue, very low priority, and the date range feature will fix it in a much more practical way. 

The talib bug has been fixed for some time which is absolutely brilliant.

**Comment by askmike** [comment]
> The talib bug has been fixed for some time which is absolutely brilliant.

So last time you mentioned it you needed to enable talib in a hidden config (baseConfig.js), but this is not necessary anymore now :)

**Comment by thegamecat** [comment]
Ah, you're a ninja!

**Comment by askmike** [comment]
>  and the date range feature will fix it in a much more practical way.

This is included in the latest develop now, the list is getting shorter :)

**Comment by thegamecat** [comment]
Amazing thanks!
