### ISSUE TITLE
UI backtest error - dev branch

### ISSUE THREAD

**Issue by thegamecat** [askmike/gekko#631]
getting this error in console after a very short period of the backtester starting in ui:

<-- POST /api/backtest
xxx POST /api/backtest 500 7,778ms -

Error: non-error thrown: Child process has died.
at Object.onerror (/Users/freefall/gekkoinstalls/gekko-develop/node_modules/koa/lib/context.js:105:40)
at process._tickCallback (internal/process/next_tick.js:103:7)

This is with any date range (changed or otherwise, any sized dataset and any strategy;rsi, talib macd and custom talib.

Using btce and poloniex dbs, different currency pairs.

Default toml settings and custom. All have the same issue.

**Comment by askmike** [comment]
fixed now! Thanks for reporting to quickly, I should better test before I push code.

The bug had to do with me assuming "01-02-2017" meant the first of February (European style), but the [date library](https://momentjs.com/) Gekko uses had other ideas.

In the UI I am displaying all dates as `DD-MM-YYYY`, this should probably change into `YYYY-MM-DD` at some point to prevent confusion.
