### ISSUE TITLE
Backtest  - pass cfg / strategy variable in and return %gain loss out

### ISSUE THREAD

**Issue by thegamecat** [askmike/gekko#632]
Is it currently possible to call gekko with another application, passing in the trading advisor and strategy config variables - and getting the % gain / loss as a return value?

**Comment by askmike** [comment]
Yes, the UI found in the dev branch consists of two parts:

A HTML5 webapp and a webserver. You can also start the webserver without starting the UI by running the following:

    cd web
    node server

The server will serve an API from wherever is configured in [UIconfig.js](https://github.com/askmike/gekko/blob/develop/web/vue/UIconfig.js).

You can run a backtest for example by sending a POST call to:

    http://localhost:3000/api/backtest

You need to pass a valid gekko config with all parameters configured properly. The result will be [JSON like this](https://gist.github.com/askmike/8fb011842a597e9cad3bf200c595b127).

There are also API calls that let you query available history, query available strats and their parameters, etc.

**Comment by askmike** [comment]
Note that the API is currently not stable at all, and is changing fast. After releasing the UI I will write some documentation on how to use the API.

**Comment by thegamecat** [comment]
Perfect, do you know what all the post variables are? Or which file can I look at to spot them?

**Comment by thegamecat** [comment]
[ga.txt](https://github.com/askmike/gekko/files/853601/ga.txt)
So I've created this .js file in the web routes directory. I can run the file, it starts but then errors, seemingly the config I pass doesn't get used - and the sqlite handler returns an error that there is no watch exchange in undefined - which is reasonable if the config isn't overwriting the default that is used by the web server when it starts. 

I'm sure I'm doing something wrong, some guidance would be awesome :)

**Comment by askmike** [comment]
> Perfect, do you know what all the post variables are? Or which file can I look at to spot them?

The easiest would be to use your browser, if you are using chrome:

- open the UI
- right click on page, click inspect
- click the network tab
- start a backtest
- in the bottom of the list click on `backtest`
- in the headers tab, scroll all the way down

![screen shot 2017-03-20 at 00 53 14](https://cloud.githubusercontent.com/assets/969743/24086457/a4f277bc-0d07-11e7-8eb7-c2bc8961f5bf.png)

EDIT: judging by your script you already found this!

-------

> So I've created this .js file in the web routes directory

Will test your script that out asap, I am not familar with `node-fetch`, but maybe the way JSON is passed in the POST request to the webserver is not supported by the body parser I am using.

**Comment by thegamecat** [comment]
Hah, you were right, I switched to using a standard request and bam, it works:
https://gist.github.com/thegamecat/a5fceb09122787e7d2700a238a1d1e78

**Comment by askmike** [comment]
Great! If you have more questions feel free to ask. Do keep in mind that the API will probably change around a lot, for example: the backtest now includes candles, but I will probably remove those to fix #603.

**Comment by thegamecat** [comment]
Understand it will change.

What do you mean remove candles? That makes me a little nervous :P

**Comment by askmike** [comment]
So when you do a backtest, gekko will run a strat against a dataset. If you set the tradingAdvisor.candleSize to 1 that means the strat will run against 1 minute candles. In your example from #603:

> So this means that Gekko is quite able to backtest over so much data, but it's hard to get the results into the UI (all data needed to spawn the price chart, which in your case is ~6 months x 30 days x 24 hours x 60 minutes = 259,200 data points).

Each of these datapoints is an object in the candles array like [this one](https://gist.github.com/askmike/8fb011842a597e9cad3bf200c595b127#file-backtest-ouput-txt-L11-L21). So that would be a JSON output with 259,200 * 10 = over 2 million properties, eg. at least a few MB.

-----

A solution to this problem would be to not return the candles in the backtest (just the trades), and let the client be responsible for retrieving market data that can actually be displayed in a chart: There is another API call for getting candles, so the client can after the backtest simply do a call for getCandles for the full 6 months with daily candles instead. Which can render properly in a chart.

**Comment by thegamecat** [comment]
Ahhhh yes I think that's a good idea. It's interesting how it only affects the UI though. The CLI works perfectly with big datasets / date ranges.

**Comment by BaptisteOrieux** [comment]
Hey guys !

I have the same issue with UI, but i don't understand your solution of not returning the candles in the backtest
Could you please explain ?
