### ISSUE TITLE
Error: Cannot find module gekko/core/../plugins/undefined/writer'

### ISSUE THREAD

**Issue by albertolive** [askmike/gekko#633]
Hi,

I'm in develop branch and I'm getting now this error launching `node gekko --config config.js`

Error: Cannot find module gekko/core/../plugins/undefined/writer'

With `node gekko` saids:

 ERROR: Please specify a config file.

Thanks

**Comment by askmike** [comment]
the config has changed a bit, could you base your config on the sample-config found in the root of the directory?
