### ISSUE TITLE
Telegram Plugin Crash DEV

### ISSUE THREAD

**Issue by decoye** [askmike/gekko#639]
Hello,

got this about a minute ago

[Unhandled rejection TimeoutError: operation timed out
    at afterTimeout (/home/andreas/gekko/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/timers.js:16:15)
    at Timeout.timeoutTimeout (/home/andreas/gekko/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/timers.js:59:9)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

ERROR: Failed to tick in time, see https://github.com/askmike/gekko/issues/514 for details

**Comment by askmike** [comment]
> ERROR: Failed to tick in time, see #514 for details

This usually happens when your computer went into sleepmode or hibernation (like closing your laptop). Was this the case?

**Comment by decoye** [comment]
nope

**Comment by askmike** [comment]
Are you able to reproduce it every time something specific happens?

**Comment by decoye** [comment]
im currently trying to figure out what happens to make it crash.

**Comment by decoye** [comment]
i assume that this one here then can also be viewed as solved as the database error may be a well enough explanation for this beviour too.

**Comment by subhead** [comment]
On my desktop rig i have disabled any sleepmode or hibernation and i also have this problem. When i disable the telegram plugin i recieve an "Failed to tick in time error".

**Comment by subhead** [comment]
On my desktop rig i have disabled any sleepmode or hibernation and i also have this problem. When i disable the telegram plugin i recieve an "Failed to tick in time error" instead.

**Comment by askmike** [comment]
@subhead The "Failed to tick in time error" is another error.

Could you open a new issue and describe your setup (computer, what you are doing with gekko, etc).

**Comment by RobboRobson1** [comment]
Hi. Was this ever resolved because I keep getting the error that the OP posted

Thanks

James
