### ISSUE TITLE
Stable Branch Backtester Live Trader Bug

### ISSUE THREAD

**Issue by decoye** [askmike/gekko#641]
Hey Mike,

Backtester advises to trade short at 7:20 @1120€ on kraken.

Live Trader Trades short 4 Hours later @945€.

**Comment by askmike** [comment]
So you are running a backtester as well as live trader, and your issue is that the advices are different?

Can you give some info like:

- what branches are both gekkos running?
- what strat are you running?
- over what daterange are you backtesting?
- for how long ahs the live trader been running?

**Comment by decoye** [comment]
- what branches are both gekkos running?

stable, both of them. with the same data

- what strat are you running?
DEMA

- over what daterange are you backtesting?
6 Months

- for how long ahs the live trader been running?
6 Months

**Comment by askmike** [comment]
Can you send/post the logs? Preferable debug logs!

**Comment by askmike** [comment]
closing this until we can debug using logs.
