### ISSUE TITLE
Gekko Crashing when trader is ON; set on Bitfinex and there are enough market data

### ISSUE THREAD

**Issue by manu314** [askmike/gekko#643]
Hello,

I am having the following error when I restart gekko with enough market data on bitfinex.
The tarder is activated and is working/

home/pi/gekkobf/plugins/trader/portfolioManager.js:255
      '(' + amount.toFixed(12) + ')',
                   ^

TypeError: amount.toFixed is not a function
    at Manager.sell (/home/pi/gekkobf/plugins/trader/portfolioManager.js:255:20)
    at Manager.bound [as sell] (/home/pi/gekkobf/node_modules/lodash/dist/lodash.js:729:21)
    at Manager.act (/home/pi/gekkobf/plugins/trader/portfolioManager.js:162:12)
    at bound (/home/pi/gekkobf/node_modules/lodash/dist/lodash.js:729:21)
    at /home/pi/gekkobf/node_modules/async/lib/async.js:232:13
    at /home/pi/gekkobf/node_modules/async/lib/async.js:142:25
    at /home/pi/gekkobf/node_modules/async/lib/async.js:229:17
    at /home/pi/gekkobf/node_modules/async/lib/async.js:556:34
    at Manager.<anonymous> (/home/pi/gekkobf/plugins/trader/portfolioManager.js:76:7)
    at /home/pi/gekkobf/exchanges/bitfinex.js:55:5

This does not happen when the directory history is empty or when there are not enough data to start directly the trader.
 Anyone has any idea to help?

Branch is stable.

Best regards,

Manu

**Comment by askmike** [comment]
Will have a look ASAP!

**Comment by manu314** [comment]
OK thanks!

**Comment by askmike** [comment]
Sorry for the late reply. This is fixed as part of the new trader for the UI (in development, see #737). Therefor I am closing this issue already.
