### ISSUE TITLE
Backtest / API  tradingAdvisor issue

### ISSUE THREAD

**Issue by thegamecat** [askmike/gekko#645]
In the dev branch I now need to pass through the tradingAdvisor config in a way that was not previously necessary (good).

The issue is if I pass it through as: 
tradingAdvisor:
{ enabled: true,
candleSize: 60,
historySize:30,
method: 'talib-dmi-vix'
}

I get an error on the server side saying; candleSize is not a number.

Now the value is clearly coming through to the candlebatcher but it's not a number. 

This a bug? If I remove the error catchers in candlebatcher then I get the same error on optintimeperiod....

Any idea?

**Comment by askmike** [comment]
> the server side

Could you give more information like:

- how exactly are you starting the backtest?
- what is the exact input (in json)?

**Comment by thegamecat** [comment]
async.mapSeries(tests_series, function (data, callback) {
        var outconfig = {
            tradingAdvisor: {
enabled: true,
method: 'talib-dmi-vix',
candleSize: 60,
historySize: 30,
adapter: 'sqlite',
talib: {
enabled: true,
version: '1.0.2'
}
},
            watch: {exchange: 'poloniex', currency: 'BTC', asset: 'BELA'},
            profitSimulator: {
                fee: 0.25,
                slippage: 0.05,
                simulationBalance: {asset: 1, currency: 100},
                enabled: true
            },
            'talib-dmi-vix': {
                parameters: {optInTimePeriod: data.optInTimePeriod},
                adxparameters: {optInTimePeriod: data.adxOptInTimePeriod},
                thresholds: {
                    adxthreshold: data.adxthreshold,
                    minusgap: data.minusgap,
                    plusgap: data.plusgap,
                    vixperiod: data.vixPeriod,
                    upperwvf: data.upperwvf,
                    lowerwvf: data.lowerwvf,
                    t1: data.t1,
                    t2: data.t2
                }
            },
            valid: true
        };
        request.post({
                url: 'http://localhost:3000/api/backtest',
                form: outconfig
            },
            function (err, httpResponse, body) {
                jsongap = JSON.parse(body);
                results.push(jsongap.report.profit);
                return callback(null, body);
            });
    }, function () {
        callback(results)
    });

**Comment by thegamecat** [comment]
Basically if i leave out the trading advisor part then there is no error. 
But of course it doesn't actually run the backtest with the values / strategy.

**Comment by askmike** [comment]
Would you mind putting that code in a gist / pastebin? This is unreadable.

**Comment by thegamecat** [comment]
https://gist.github.com/thegamecat/759bb188e66943d3276c86404d88f94b

**Comment by thegamecat** [comment]
I think the issue may be connected to the way the config merge is happening in backtest.js. But I could be wrong. I think it's adding quotes to the variables.

**Comment by askmike** [comment]
That gist isn't super helpful for me since I cannot run that code (I don't have `tests_series` nor your trading method).

It will be hard for me to debug this issue without a standalone use case. So maybe you can: Can you add the following code:

    console.log('DEBUG', this.request.body);

[on this line](https://github.com/askmike/gekko/blob/develop/web/routes/backtest.js#L11)? And look at your console to see if your config was correctly passed correctly to gekko.

----

It's hard to know exactly what goes wrong because the config passed will be merged with the baseConfig (another thing I want to get rid of soon, since it only makes the code harder to reason with).

EDIT: please change it into this line (since it might get logged after the merge):

    console.log('DEBUG', JSON.stringify(this.request.body, null, 4));

**Comment by thegamecat** [comment]
Ok so that returns the config i would expect except all the values are in single quotes. And that is what is causing the issues.

**Comment by thegamecat** [comment]
I will dig out a script that you can run as well.

**Comment by askmike** [comment]
> single quotes

This is definitely not your issue! You can use single quotes and double quotes interchangeably within javascript (UNLESS you are sending JSON, but in this case you already sent JSON which got parsed by the API library gekko is using).

As to your original error:

> candleSize is not a number

Is candleSize in quotes at all? This is supposed to be not in quotes (since it is a number and not a string).

**Comment by thegamecat** [comment]
candleSize is not in quotes.

**Comment by thegamecat** [comment]
[ga.txt](https://github.com/askmike/gekko/files/865391/ga.txt)

Rename .js and I run it from web/routes directory. You'll need to install a couple of modules.

**Comment by thegamecat** [comment]
And just to make this a little clearer, if I comment the error catch in candleBatcher line 17

And I console.log params on line 29 in core/talib.js it returns:
{optIntimePeriod: '24' }

throw talibError + paramName+ ' needs to be a number';

**Comment by askmike** [comment]
The request code you used malformed the JSON, instead of:

    request.post({
      url: 'http://localhost:3000/api/backtest',
      form: outconfig
    },

do

    request.post({
      url: 'http://localhost:3000/api/backtest',
      json: outconfig
    },

**Comment by thegamecat** [comment]
Doh!!! Maybe one for the documentation. Thanks as always.

**Comment by thegamecat** [comment]
Nevermind it's working perfectly!

**Comment by askmike** [comment]
@thegamecat I am updating the backtest API, you now need to pass data like this:

https://github.com/askmike/gekko/commit/0f6e7676931a7bcc954d133c4f34ec1c9c14d2fa#diff-216169f28100958139800d9ffec8d13aR10

(pushed to develop, not live on stable branch yet), by setting data to false you can prevent gekko from sending you data you are not interested in (if you only want the report).

**Comment by amhed** [comment]
I went ahead and modified the JSON payload as suggested. This is the error I get whenever I try to access the /api/backtest endpoint

```
<-- POST /api/backtest
  xxx POST /api/backtest 500 213ms -

  Error: non-error thrown: Child process has died.
      at Object.onerror (/Users/amhed/Sites/gekko/node_modules/koa/lib/context.js:105:40)
      at process._tickCallback (internal/process/next_tick.js:109:7)
```

I pulled from latest develop. Here's how my simple test strategy looks like: 

```js
var outconfig = {
          gekkoConfig: {
            watch: {
              exchange: 'poloniex', 
              currency: 'USDT', 
              asset: 'ETC'},
            profitSimulator: {
                fee: 0.25,
                slippage: 0.05,
                simulationBalance: {asset: 1, currency: 100},
                enabled: true
            },
            'macd': {
                parameters: {
                  short: data.short,
                  long: data.long,
                  signal: data.signal 
                },
                thresholds: {
                    up: data.up,
                    down: data.down,
                    persistence: data.persistence,
                }
            },
            valid: true
          },
          data: {
            candleProps: ["close", "start"],
            indicatorResults: true,
            report: true,
            roundtrips: true
          }
        };
```

**Comment by salym5** [comment]
![default](https://user-images.githubusercontent.com/9304236/27761458-84225d6c-5e75-11e7-9185-360ef08c0986.png)
