### ISSUE TITLE
[UI] [minor] Date consistency?

### ISSUE THREAD

**Issue by brian000** [askmike/gekko#646]
Any chance we can shore up date consistency across the UI?  For example, the import pages and CLI use ISO 8601 (YYYY-MM-DD) however the backtester uses DD-MM-YYYY.  IMO it makes the importer easier to use.  

(I'm on the latest commit, 2b70ef2)

_Bonus points if you can use the browser's local TZ offset when going to import/backtest!_

**Comment by askmike** [comment]
Good point, would `YYYY-MM-DD` everywhere work for you?

> Bonus points if you can use the browser's local TZ offset when going to import/backtest!

Will put that on the roadmap for later, I want to aim for consistency first.

**Comment by brian000** [comment]
ISO 8601 best 8601!

**Comment by askmike** [comment]
done :)

**Comment by tuxitor** [comment]
I think a 24 hour timeline under the graph woul be a good thing. Now it shows AM/PM
