### ISSUE TITLE
Market Watcher. Graph is not displayed.

### ISSUE THREAD

**Issue by MarvinDivo** [askmike/gekko#647]
Hello,
Using Gekko v0.4.4 and Gekko UI v0.1.5. (Latest develop branch)
Default gekko settings.
Browser is Google Chrome
Same problem for different Exchange/Market combinations.
Steps below.

## **Step 1**

![image](https://cloud.githubusercontent.com/assets/13578263/24315769/caf4b54a-10f1-11e7-99ce-b7f744f10a2d.png)

## **Step 2**

![image](https://cloud.githubusercontent.com/assets/13578263/24315787/fd3efb78-10f1-11e7-9803-9bd7d63dc749.png)

**Comment by askmike** [comment]
You found that quick, sorry about that. Fixed in latest develop :)
