### ISSUE TITLE
candlewriter as a separate node program

### ISSUE THREAD

**Issue by tuxitor** [askmike/gekko#650]
So far I have only tried Gekko backtesting on bitstamp and bitfinex. I have noticed that stopping and starting gekko creates a new candle dataset. 
My idea is to separate the writeCandles function into a separate program. The benefit is continous data collecting even if gekko is stopped for updating or reconfiguration purposes. This program could be started from inside or outside Gekko like this or similar: [nohup] node gekkoCollect &lt;exchange&gt; [&]

**Comment by askmike** [comment]
hey @eigilb! I just now (an hour ago) pushed a new version of Gekko that includes a lot of upgrades and a web interace.

On of the other things it includes is two submodes:

- A market watcher (that only pushes candles into the database)
- A "leecher" stratrunner that gets the information out of the database.

More information can be found in #513.

This allows what you are describing and more:

- Keep the watcher runner, restart and stop the trader/stratrunner/etc.
- Try out different strats against one market (while only watching the market once)
- etc.

Setting up these two submodes can be done automatically using the UI. And I will think about how to expose them using the CLI (if you have any ideas how you think this should be configured easily, let me know).

**Comment by askmike** [comment]
The functionality requested is part of the live UI. Closing this for now.
