### ISSUE TITLE
[Feature Request] Live configuration changes

### ISSUE THREAD

**Issue by tuxitor** [askmike/gekko#654]
Changing strat parameters through the Web UI is great when experimenting with backtesting. As it is now you need to stop and restart gekko to make the changes permanent. That also means holes in the candle data and the appearance of a new dataset in the web UI.

A few ideas to solve this:

For the CLI interface use a kill signal to kick the process into rereading configuration files like "kill -HUP &lt;process ID&gt;" As it is now I cannot see which process or child is doing what from "ps aux". It should be possible to fix that.

For the Web UI expose the PID with a choice to reload/restart/reconfig the process

During live trading, I would like to switch between live and paper trading through a toggle on the Web UI

The possibility to remove old data sets from the Web UI without the need to remove DB files would be nice.

**Comment by askmike** [comment]
This is definitely a great idea (and should be part of 0.5, this is important functionality).

> For the CLI interface use a kill signal to kick the process into rereading configuration files like "kill -HUP <process ID>"
> For the Web UI expose the PID with a choice to reload/restart/reconfig the process

Yes definitely, there [already is an endpoint](https://github.com/askmike/gekko/blob/stable/web/routes/killGekko.js) for killing a gekko instance (but it does't actually kill the process, just deregisters it).

> The possibility to remove old data sets from the Web UI without the need to remove DB files would be nice.

Good idea!

> During live trading, I would like to switch between live and paper trading through a toggle on the Web UI

From a UX perspective live trading is pretty dangerous, trading using the commandline version only works after [you set a special flag to true](https://github.com/askmike/gekko/blob/stable/gekko.js#L49-L53). I want to implement a modal for the UI (when starting a live trading instance). But not sure how this would work if you can toggle it on or off.

The other thing is that I am not sure how clear that would be: The live gekko has a profit report and will have a list of trades, all these need to be reset if you toggle it from paper trader to real trader. What about a button in a paper trader that says something "live trade using these settings"?

**Comment by tuxitor** [comment]
> What about a button in a paper trader that says something "live trade using these settings"?

You are the expert here. I don't yet fully understand the inner workings of gekko. But the purpose of the idea is to be closely following the trades in daytime when awake and switch off at night. Scheduled trading could be another alternative. 
A start button for live trading might be a good idea anyway.

I have a wish for the web UI, too small to deserve a new issue: 
On the "Backtest" page the information text under the history size should be split into days and minutes for easier reading when setting the size.

Maybe a good idea to have a discussion thread or a new tag for Web UI issues/features?

**Comment by askmike** [comment]
> Maybe a good idea to have a discussion thread or a new tag for Web UI issues/features?

Done!

> On the "Backtest" page the information text under the history size should be split into days and minutes for easier reading when setting the size.

This one?

![screen shot 2017-03-30 at 17 59 35](https://cloud.githubusercontent.com/assets/969743/24516495/c704939e-1572-11e7-937a-06bc608aa62d.png)

**Comment by tuxitor** [comment]
Exactly!
Saves some headache when trying to calculate. My brain is 72 years+  :-P

**Comment by askmike** [comment]
Done, looks like this now:

![historysize](https://cloud.githubusercontent.com/assets/969743/24578919/5acc43c6-16e3-11e7-8c59-ad82851a27fb.gif)

**Comment by tuxitor** [comment]
Very good!

**Comment by greenbigfrog** [comment]
@askmike was there anything else here you wanted to edit?
