### ISSUE TITLE
Suggestion:use webworker/thread/threadpool,improve the Plugin's response speed

### ISSUE THREAD

**Issue by zfsamzfsam** [askmike/gekko#657]
use webworker/thread/threadpool,improve the Plugin's response speed
https://github.com/audreyt/node-webworker-threads

**Comment by askmike** [comment]
Gekko already moves all CPU intensive work to childprocesses (backtesting, data scanning, etc.). Are you experiencing any problems or slowness with gekko?

**Comment by askmike** [comment]
I'm not sure if you are talking about a specific plugin or not. Please reply here with the issue you are having specifically, or specifically what plugin you think should be improved.
