### ISSUE TITLE
Links to Configuring_gekko.md are dead

### ISSUE THREAD

**Issue by burnzzz** [askmike/gekko#659]
There is a dead link in https://github.com/askmike/gekko/blob/stable/docs/internals/exchanges.md pointing to Configuring_gekko.md which does not exist

**Comment by askmike** [comment]
Nice spot, I see I missed updating some documentation: If you are using the UI, configuring Gekko is as easy as following the steps on the screen (used to be a lot harder). Will fix it asap.

**Comment by askmike** [comment]
Fixed! I removed the sentence because since the UI you don't have to "configure" Gekko anymore :) (just follow the instructions on screen).

**Comment by askmike** [comment]
See 74d3c38
