### ISSUE TITLE
Nohup: ignoring input (ERROR: Cannot find config file)

### ISSUE THREAD

**Issue by Nargren** [askmike/gekko#660]
Hello,
I have just upgraded my gekko (git pull && npm update) and it started producing the following error:
`cat history.log`
```
nohup: ignoring input

    ______   ________  __    __  __    __   ______
   /      \ /        |/  |  /  |/  |  /  | /      \
  /$$$$$$  |$$$$$$$$/ $$ | /$$/ $$ | /$$/ /$$$$$$  |
  $$ | _$$/ $$ |__    $$ |/$$/  $$ |/$$/  $$ |  $$ |
  $$ |/    |$$    |   $$  $$<   $$  $$<   $$ |  $$ |
  $$ |$$$$ |$$$$$/    $$$$$  \  $$$$$  \  $$ |  $$ |
  $$ \__$$ |$$ |_____ $$ |$$  \ $$ |$$  \ $$ \__$$ |
  $$    $$/ $$       |$$ | $$  |$$ | $$  |$$    $$/ 
   $$$$$$/  $$$$$$$$/ $$/   $$/ $$/   $$/  $$$$$$/

	Gekko v0.4.6
	I'm gonna make you rich, Bud Fox. 

 ERROR: Cannot find the specified config file.
```

nohup: 8.21
node: 6.10.1
npm: 4.2.0
Starting gekko with
`nohup node gekko --config myconfig.js &> history.log &`

I have been starting gekko via the same command and same config file for quite some time now. Suddenly it does not work.

**Comment by askmike** [comment]
Strange, it is working for me. What OS are you on?

**Comment by Nargren** [comment]
Ubuntu 14.04.05
Also strange, I had to `sudo npm update` the last time, it was asking for administrator permissions for some update. I don't think I had to run that as root before. 
I will try to collect some more info and see if I can track down the problem.

**Comment by askmike** [comment]
Can you double check if the file `myconfig.js` actually exists within the root folder of gekko? For me it is working fine on Ubuntu:

    mike@main:~/projects/gekko$ node gekko --config myconfig.js 

        ______   ________  __    __  __    __   ______
       /      \ /        |/  |  /  |/  |  /  | /      \
      /$$$$$$  |$$$$$$$$/ $$ | /$$/ $$ | /$$/ /$$$$$$  |
      $$ | _$$/ $$ |__    $$ |/$$/  $$ |/$$/  $$ |  $$ |
      $$ |/    |$$    |   $$  $$<   $$  $$<   $$ |  $$ |
      $$ |$$$$ |$$$$$/    $$$$$  \  $$$$$  \  $$ |  $$ |
      $$ \__$$ |$$ |_____ $$ |$$  \ $$ |$$  \ $$ \__$$ |
      $$    $$/ $$       |$$ | $$  |$$ | $$  |$$    $$/ 
       $$$$$$/  $$$$$$$$/ $$/   $$/ $$/   $$/  $$$$$$/

            Gekko v0.4.6
            I'm gonna make you rich, Bud Fox. 


    2017-04-02 11:44:20 (INFO):     Setting up Gekko in realtime mode
    2017-04-02 11:44:20 (INFO):
    2017-04-02 11:44:20 (INFO):     Setting up:
    2017-04-02 11:44:20 (INFO):              Candle writer
    2017-04-02 11:44:20 (INFO):              Store candles in a database
    2017-04-02 11:44:20 (INFO):

    2017-04-02 11:44:20 (INFO):     Starting to watch the market: Bitstamp BTC/USD
    2017-04-02 11:44:20 (DEBUG):    scheduling ticks
    2017-04-02 11:44:20 (DEBUG):    Requested BTC/USD trade data from Bitstamp ...

EDIT: this is case sensitive.

**Comment by Nargren** [comment]
I normally give the full path to the config, but it is actually in the gekko directory.
Executing gekko from within the directory, gives,
```
node gekko --config BTCe-MACD.js 

    ______   ________  __    __  __    __   ______
   /      \ /        |/  |  /  |/  |  /  | /      \
  /$$$$$$  |$$$$$$$$/ $$ | /$$/ $$ | /$$/ /$$$$$$  |
  $$ | _$$/ $$ |__    $$ |/$$/  $$ |/$$/  $$ |  $$ |
  $$ |/    |$$    |   $$  $$<   $$  $$<   $$ |  $$ |
  $$ |$$$$ |$$$$$/    $$$$$  \  $$$$$  \  $$ |  $$ |
  $$ \__$$ |$$ |_____ $$ |$$  \ $$ |$$  \ $$ \__$$ |
  $$    $$/ $$       |$$ | $$  |$$ | $$  |$$    $$/ 
   $$$$$$/  $$$$$$$$/ $$/   $$/ $$/   $$/  $$$$$$/

	Gekko v0.4.6
	I'm gonna make you rich, Bud Fox. 


2017-04-02 19:00:54 (INFO):	Setting up Gekko in realtime mode
2017-04-02 19:00:54 (INFO):	
2017-04-02 19:00:54 (INFO):	Setting up:
2017-04-02 19:00:54 (INFO):		 Candle writer
2017-04-02 19:00:54 (INFO):		 Store candles in a database
module.js:471
    throw err;
    ^

Error: Cannot find module '/home/nargren/Software/gekko/core/../plugins/undefined/writer'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at load (/home/nargren/Software/gekko/core/pluginUtil.js:90:25)
    at /home/nargren/Software/gekko/node_modules/async/dist/async.js:1156:9
    at replenish (/home/nargren/Software/gekko/node_modules/async/dist/async.js:1030:17)
    at /home/nargren/Software/gekko/node_modules/async/dist/async.js:1034:9
    at _asyncMap (/home/nargren/Software/gekko/node_modules/async/dist/async.js:1154:5)
    at /home/nargren/Software/gekko/node_modules/async/dist/async.js:1240:16

```

**Comment by askmike** [comment]
> I normally give the full path to the config

You can't do that anymore (judging by the new code), I will fix that as some point though.

> Error: Cannot find module '/home/nargren/Software/gekko/core/../plugins/undefined/writer'

The format of the config has changed (the adapter section specifically). Please update your config! And you should be good.

**Comment by Nargren** [comment]
Thank you, it worked just fine after updating my config file.
