### ISSUE TITLE
Remote-Access to GUI

### ISSUE THREAD

**Issue by hoerbi1000** [askmike/gekko#662]
is it possible to access the gekko-ui via browser on another pc?
my gekko is running on my ubuntu server, and i want to access via my chrome/firefox from my windows machine. 

but if i do i get always 
![image](https://cloud.githubusercontent.com/assets/26603435/24608972/1f120914-1879-11e7-9eea-83ec19d18127.png)

i have looked the config , and tried to set localhost do the hostname of my server? 
must i do someting special?

**Comment by askmike** [comment]
> and tried to set localhost do the hostname of my server?

I'm not sure if you looked at the correct config, but you need to change [this one](https://github.com/askmike/gekko/blob/stable/web/vue/UIconfig.js#L7), change the host on line 7 to the IP address of your ubuntu server.

EDIT: make sure you leave the quotes, so set it to something like:

        host: '192.168.1.161',

**Comment by hoerbi1000** [comment]
yes i have it configured there 

`const CONFIG = {
  api: {
    ssl: false,
    host: 'myserver',
    port: 3000,
    path: '/'
  }
}`

added it to my hosts
`less /etc/hosts | grep myserver
192.168.0.3	myserver`

also my nw adapter is like that
`enp1s0    Link encap:Ethernet  HWaddr 84:39:be:62:1f:79  
          inet addr:192.168.0.3  Bcast:192.168.0.255  Mask:255.255.255.0`


gekko is also showing the IP 
`Serving Gekko UI on http://myserver:3000/

`

**Comment by askmike** [comment]
Very strange, can you follow the following instructions:

https://github.com/askmike/gekko/issues/637#issuecomment-288793793

And make screenshots of the result?

**Comment by hoerbi1000** [comment]
thanks this thread is what i was needing

changing the name direct to my IP was the solution 
[https://github.com/askmike/gekko/issues/637#issuecomment-288801607](url)

`const CONFIG = {
  api: {
    ssl: false,
    host: '192.168.0.3',
//    host: 'myserver',
    port: 3000,
    path: '/'
  }
}
`

**Comment by askmike** [comment]
great!
