### ISSUE TITLE
SQLITE_BUSY: database is locked

### ISSUE THREAD

**Issue by hoerbi1000** [askmike/gekko#664]
When im running gekko, im nearly getting always this error after about 1 -6 hours

`2017-04-04 21:34:28 (DEBUG):    In downtrend since 7 candle(s)
events.js:161
      throw er; // Unhandled 'error' event
      ^
Error: SQLITE_BUSY: database is locked`

does anyone else also know about the bug? 
i have nothing special run in background.

**Comment by tneele** [comment]
I experience the same when I run a market watcher at the same time as running an import. In that case, this error seems like the logical result: two workers want to write to the database.
Because of this, I wanted to switch to MongoDB completely, but unfortunately, it is not yet supported in the UI.

**Comment by askmike** [comment]
@hoerbi1000 

> When im running gekko, im nearly getting always this error after about 1 -6 hours

Are you only running a single Gekko (through the commmandlie)?

@ThomasNeele 

> I experience the same when I run a market watcher at the same time as running an import.

I will try to reproduce, but I'm not sure how much we can do about it. Are you interested in different markets on the same exchange, or simply one market?

mongodb support was updated by @zeroX-tj (I have reviewed it but untested), could you try that out on the develop branch (and let me know how that goes)?

**Comment by tneele** [comment]
At that time, I was tracking as well as importing one market.

There were still some issues with MongoDB for me in the development branch as well. I have tried to fix those in a PR.

**Comment by askmike** [comment]
@ThomasNeele Thanks a lot for that.

@hoerbi1000 I am able to reproduce, but it's a hard problem to fix at the moment. You can workaround this for now by not importing + running live gekkos against the same exchange..

**Comment by hoerbi1000** [comment]
@askmike 
Okay thanks for the Support ;)

**Comment by darklow** [comment]
@askmike I am experiencing same problem as well. Since you were able to reproduce and know why the problem appears - is it sqllite specific and would moving to postgres database help to solve this issue?
I am also running commandline trader plus I am running few market monitors to store data to analyze in backtest later.

**Comment by askmike** [comment]
>  is it sqllite specific and would moving to postgres database help to solve this issue?

Yes, judging by your use case (running multiple gekkos at the same time) postgresql would be a better option.

**Comment by xyzzy529** [comment]
I start a fresh Server instance from Windows CMD prompt. Then start a Live Gekko Paper Trader.
After about 20-30 minutes, get this error.
Running fresh install with no changes. Installed per Instructions on Document site.

```
  --> POST /api/getCandles 200 452ms 2b
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: SQLITE_BUSY: database is locked
    at Error (native)
RECEIVED ERROR IN GEKKO 525892288974239
Child process has died.
  <-- GET /api/imports
  --> GET /api/imports 200 1ms 2b
```

**Comment by thegamecat** [comment]
A general Gekko usage tip - 

if you're doing imports do them under a different database

I have multiple history folders each with a different set of databases, and I manage these across multiple instances of gekko depending on what i'm doing. 

Not saying it's the best way, but it works. 

For example, I often copy over the dbs from the production box and backtest tweaks against them to see if I could have made more etc.

**Comment by AidasK** [comment]
Does switching to postgres solve locking problems?
