### ISSUE TITLE
Poloniex - Add more USDT Pairs

### ISSUE THREAD

**Issue by travislwilson** [askmike/gekko#675]
Hello, I was wonder how would I go about adding more USDT pairs for poloniex like USDT/XMR.
I tried adding more to the market section of poloniex inside of exchange.js in the main folder but they do not show up under the market section in imports on the website. Thank you for your time and effort with this it is really fun switching from c++ to javascript and trying to figure out how trading api's work.

**Comment by askmike** [comment]
Gekko comes in two parts: a frontend and a backend (both written in javascript). That exchange file was exactly the place you needed to be at, however the frontend needs to be recompiled in order for the changes to show up in the UI.

So after updating that exchange file go to:

     cd gekko/web/vue
     npm install
     npm run build

See [this document](https://github.com/askmike/gekko/blob/stable/docs/internals/gekko_ui/frontend.md) for more details.

**Comment by askmike** [comment]
If this works feel free to create a pull request (to the develop branch) so this will be the default for Gekko :) If you have any problems let me know.
