### ISSUE TITLE
Can you add whaleclub to supported exchanges

### ISSUE THREAD

**Issue by ghost** [askmike/gekko#680]
Is there a way to add whaleclub to supported exchanges since they just released their api?

**Comment by askmike** [comment]
Hey!

For a different project I actually already created an API wrapper which could be used for this:

https://github.com/askmike/whaleclub

I won't have time for this anytime soon, but if you (or anyone) feels adventurous I am very open to pull requests. Here is the documentation that has everything you need to know to add an exchange to Gekko:

https://github.com/askmike/gekko/blob/stable/docs/internals/exchanges.md

**Comment by askmike** [comment]
Closing this as I won't have time for this unfortunately. I'd love a pull request though :)
