### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by thegamecat** [askmike/gekko#682]
I'm not exactly expecting you to know what is causing this, but if I run a backtest via api / ui it works fine.

However, if I run a GA that is hitting the api with say 50 population it will work for a couple of epochs then hit me with a Segmentation fault (core dumped), no further explanation. Any idea what may be causing this? Have you ever seen it in a back test?

**Comment by askmike** [comment]
>  50 population

How have you implemented this? Are you running 50 backtests at the same time?

**Comment by thegamecat** [comment]
No, sadly sequentially.

**Comment by askmike** [comment]
So you are doing a POST call to start a backtest, and only starting the next one once the POST call responds? Nodejs is async, so if you have code that does something like:

    post('api/backtest1', config, (err, res) => {
      // process result
    })
    
    post('api/backtest2', config, (err, res) => {
      // process result
    })

You are already doing two at the same time.

----

> it will work for a couple of epochs 

What do you mean by this?

**Comment by thegamecat** [comment]
No that's not how the code works. The code manages the aync to run sequentially.

**Comment by askmike** [comment]
> The code manages the aync to run sequentially.

👍 

> Have you ever seen it in a back test?

No I haven't..

So this is happening every time you run the same script? Are you able to run a single backtest? What if you lower the population size?

**Comment by thegamecat** [comment]
Nope never happens in a single backtest.
With a lower pop size I can run for 20+ epochs then it dies.
It's very curious.

**Comment by askmike** [comment]
What happens if you wait ~5 seconds between each epoch? I think the error is related to sqlite, maybe the handles are not closed properly by the time the next epoch starts.

**Comment by askmike** [comment]
I am closing this for now. But I do want to resolve this, so please keep commenting :)

**Comment by thegamecat** [comment]
No problem, I'll put a timer in the GA and see.
