### ISSUE TITLE
When will live trading be supported?

### ISSUE THREAD

**Issue by ghost** [askmike/gekko#683]
it says live trading is not supported for now, when will it be supported?

**Comment by askmike** [comment]
The web interface is pretty new. Live trading in the UI will work be part of the next release (0.5, see #653) for details. You can already trade by using Gekko over the commandline, see this document for details:

https://github.com/askmike/gekko/blob/stable/docs/internals/plugins.md

You need to configure the following plugins: candle store, strat runner (in that document called trading advisor) & trader.
