### ISSUE TITLE
DoS

### ISSUE THREAD

**Issue by tomih** [askmike/gekko#695]
Hi,
few days ago, I received an email from my service provider, that they disconnected my server due to DoS attack.
After some investigation I realized that my server is acting as being DoSed, but in reality it was not my server under attack but the attacker.

It problem was Gekko. I had running 28 different CLI gekkos to grab data from Stamp, Finex, Okcoin, Polo and Kraken. Everything worked nicely for more then 6 months.
Few days ago, finex removed BFX pairs so they started returning error that wasn't handled by script (it kept trying to get data).
Obviously finex reported bad requests to cloudflare who refused all requests from my server and as a countermeasure they didn't close the connections (thus the impression my server is under attack). All this resulted in server crash and ban from cloudflare.

Before I restart grabbing we should definitely introduce some better error handling (status in UI, email on critical errors, ...).

So, stay nice to cloudflare!

T.

**Comment by askmike** [comment]
I'm sorry for the damage this might have caused.  I definitely want to improve this!

> Few days ago, finex removed BFX pairs so they started returning error that wasn't handled by script (it kept trying to get data).

This is an exact issue which we can fix: if we get an error saying something like "this market is not available" error should crash in full. I'll work on this asap!

**Comment by tomih** [comment]
No damage done.

It should crash (alert) as soon as it doesn't receive expected results. There are tons of different reasons for error and they all need human attention as soon as they occur.

T.

**Comment by askmike** [comment]
> There are tons of different reasons for error and they all need human attention as soon as they occur.

In my experience the APIs of multiple exchanges (including bfx) throw a lot of errors (as well as network errors). Gekko deals around with this by retrying automatically. But there should be exceptions for situations like this (as well [as backoff algo](https://en.wikipedia.org/wiki/Exponential_backoff), which is currently not used). Gekko will automatically retry in these cases (especially at extremely volatile times).

**Comment by greenbigfrog** [comment]
bump
