### ISSUE TITLE
Gekko buying high and selling low?!?!

### ISSUE THREAD

**Issue by mjsmorgan** [askmike/gekko#702]
Hello there,

I am new to Gekko and am using just the stock UO strategy, I have noticed that Gekko is buying high and selling low,  I have an example of a few trades. Is this due to the of one of the default strategies? I am still reading on how to write a custom strategy, but I have only been using Gekko for about 2 weeks. Disregard the BCN transactions.
![gekkth](https://cloud.githubusercontent.com/assets/2512824/25193349/6c4431f0-24fc-11e7-9f1b-ca4e451ec119.png)

**Comment by askmike** [comment]
Gekko automates strategies you configure, if your Gekko is buying high and selling low it has to do with how you configured the strategy (either the example strategies that come with Gekko or your custom ones).

**It is important to understand that if there was a simple way that always makes money without risk, you wouldn't be able to download it for free on the internet.**

Gekko allows backtesting as well as paper trading live markets which you can use to simulate the strategies.

Please be sure you read and understand #201 before live trading using Gekko.
