### ISSUE TITLE
Custom Strategy Repo - just an idea

### ISSUE THREAD

**Issue by mjsmorgan** [askmike/gekko#703]
I think there should be a centralized repository (or website) of custom strategies that people have written for Gekko. This will benefit in two areas; it will give newbies like me a better understanding of how to write custom strategies for their own bots, and it will improve the strategies one has written through others testing and discussing their results

**Comment by askmike** [comment]
Great idea!

When/if people want to share strategies please send them to me (or post them here). I could create a page on the website where I list all of them. Or we could add them to the example strats:

https://gekko.wizb.it/docs/strategies/example_strategies.html

**Comment by askmike** [comment]
A few issues similar to this has have been posted in the past, but if not a lot of discussion is happening inside this issue I'm not sure if this is the best place for it.

We can also think about other discussion platforms for this:

- I used to have an IRC channel for Gekko stuff, but I'd rather opt for something more web friendly.
- Someone once made a subreddit for Gekko stuff: https://www.reddit.com/r/GEKKO/ (but I'm not sure if it was ever used)
- We could have a forum? I'm just a bit worried about the time it would take to maintain.

What would people think would work?

**Comment by thegamecat** [comment]
Tbh, people can post their strats up on github, I found at least 1 that way. I'm trying to figure out the best way to do this for the GA as it happens, but now you've changed the API call so I need to re-test.

For me, it's not about sharing stats so much but the approach to working out what is the best approach to writing and testing your strat. For example, I'm a complete trading noob, but by looking at strat output data, mashing them together, tracking changes in trends via the console etc I can test and learn.

This works for me, and frankly I managed to come to the same conclusion as the GA on a couple of strats just using my puny human brain.

**Comment by generalectric** [comment]
I was actually thinking about this a couple days ago when I was way off topic on an issue. I was thinking a forum would be perfect for discussion and also help people get proactive should they choose to do so. Setting up a web irc client is simple but with just a forum the information will be there for everyone to learn from. I really like the idea of a irc channel for people actively developing gekko but I feel in the end it would be more like live tech support.

**Comment by thegamecat** [comment]
I can throw up a forum if need be.

**Comment by oedo808** [comment]
I have a discourse server already set up for comments on a blog that I never post to so the comments will never be used.  It wouldn't take but a few minutes to delete the old data out, remove the part on the blog that auto creates forums, and set up a couple of moderators.

**Comment by albertolive** [comment]
I also asked in another issue which strategies did people use to let the newbies learn from others. I think this is a great idea.

**Comment by Antownee** [comment]
What about Telegram? or slack? They seem to be pretty popular right now and many people probably are already on at least one

**Comment by chrisedington** [comment]
Im keen, where can we collab?

**Comment by notaprog** [comment]
I just subbed in the reddit GEKKO.

**Comment by greenbigfrog** [comment]
@askmike this is kinda old

**Comment by askmike** [comment]
yes, for anyone interested in sharing strategies: head over to the forum :)

**Comment by greenbigfrog** [comment]
@askmike shouldn't this issue be closed?
