### ISSUE TITLE
Different select boxes for assets and currencies for the importer

### ISSUE THREAD

**Issue by tudorconstantin** [askmike/gekko#705]
When selecting the market (asset/currency pair), there's currently a single select box, which makes it quite annoying to scroll and search for BTC/ETH for example.

If we'd have 2 select boxes, then we'd be able to quickly select BTC as the currency and then click on the second select box, press 'e' a few times until ETH gets selected

**Comment by askmike** [comment]
You are talking about both importing as well as a live market?

This was actually a part of a very early version of the UI, you had to select currency & asset. ~That code is still there and can be found in [configbuilder/marketpicker](https://github.com/askmike/gekko/blob/stable/web/vue/src/components/global/configbuilder/marketpicker.vue).~ I might have removed that code!

**Comment by tudorconstantin** [comment]
Was there a reason why you chose back then to use a single select box? 

Do you think the same reason still exists with my updates also? Or, is there something more I can do to overcome it?

PS: I like it how it looks with the select boxes on the same line

**Comment by tudorconstantin** [comment]
I think this can be closed, since you already merged the changes that implement this
