### ISSUE TITLE
Support tulip indicators (windows TA library)

### ISSUE THREAD

**Issue by askmike** [askmike/gekko#708]
Gekko supports [TA-lib](http://ta-lib.org/index.html), a well known technical analysis library that supports a lot of different indicators. However it is very hard to compile this library on Windows (which Gekko supports).

[Tulip indicators](https://tulipindicators.org/) is a relative new library that supports roughly the same indicators. The node wrapper [just added precompiled windows binaries](https://github.com/TulipCharts/tulipnode/issues/2) which makes installing on windows a breeze.

Please +1 this if you want this implemented, will work on this regardless but might prioritise if a huge number of people want this.

**Comment by generalectric** [comment]
Impressive looking at the benchmarks and well documented too... +1!

**Comment by thegamecat** [comment]
So I agree with doing this but....from my testing on windows, just run gekko in bash on windows 10 then talib is fine.

If you use SQLite then go to the file gekko/plugins/sqlite and change the line 53 from:
db.run("PRAGMA journal_mode = WAL");

to 

db.run("PRAGMA journal_mode = DEL");

And if you're copying SQLite dbs from another install of gekko then make sure you change the db pragma journal mode to DEL in a tool like DB Browser for SQLite.

I would love to know the performance difference between DEL and WAL or even if they are used, but I have a 500meg btcusd dataset and it seems to make no difference.

All that said, the more indicators the merrier, I am personally unsure if it should be a priority, but I'd be happy with it integrated.

Edit; just reviewed the performance....this would be marvelous to implement! +1 from me.

**Comment by Pedro942** [comment]
+1

**Comment by vpatel9202** [comment]
+1

**Comment by deke997** [comment]
+1 
I would love to have this implemented! In the mean time, I have installed gekko in bash on Windows 10.  Thank you @thegamecat for the instuctions to get that working... I was pulling my hair out trying to figure it out, but once I made the necessary change to handle.js, everything started working flawlessly (I think... at the very least, it stopped throwing errors)

Maybe we should add instructions to the docs to get gekko running on bash on Windows 10

**Comment by BrentEaston** [comment]
+1

**Comment by serzhiio** [comment]
I need awesome oscillator but Ta-Lib doesn't have one.
Tulip is in need...

**Comment by askmike** [comment]
All thanks to @cmroche this is now available in the develop version of Gekko! (download here: https://github.com/askmike/gekko/tree/develop - using that link you can also browse the `docs` folder to find updated documentation on how to implement this in your strategies).

It will be available in the next release of gekko! As such I am closing this issue already :)

**Comment by jdiegosierra** [comment]
+1

**Comment by askmike** [comment]
@dyeghikoo tulip has been available for a while now, see here: https://gekko.wizb.it/docs/strategies/tulip_indicators.html

**Comment by rube-de** [comment]
If it is implemented now, can please the installation guides be updated?

**Comment by xKraken** [comment]
Hi,
I don't really understand what is going on in the actual stage. Since that on https://gekko.wizb.it/docs/installation/installing_gekko_on_windows.html we are told to install Tulip Indicators.
Is there **any difference** (as of today) between the Tulip and TA-lib librairies, regarding the overall compatibilities of existing open source strategies ? 
In other words, are existing strategies (with common indicators) compatible regardless of the library you use ? 
My question can sound dumb but I just got into the Gekko environment

**Comment by tiagosargiani** [comment]
+1
