### ISSUE TITLE
[RPi] Immediate Unexpected Token

### ISSUE THREAD

**Issue by wereii** [askmike/gekko#711]
I want to run gekko on my Rpi  (model B i think, old one). I was able to install node/npm using apt or cUrl, I tried both and also tried installing from tars. Everytime it ends on this. I don't know what I've missed. 
![image](https://cloud.githubusercontent.com/assets/8504482/25359153/598a60ba-2944-11e7-94e4-d8e68bfa1a35.png)

Node -v
v7.9.0

npm -v 
4.2.0
Thx.

**Comment by askmike** [comment]
Did you install gekko's dependencies with `npm install`? If you did could you try to remove the  `node_modules` directory and install them again?

**Comment by wereii** [comment]
I everytime did 'npm install --only=production' first and then tried to run it. Atm I am trying to re-install modules (some DEPRECATED warns there) . Will update if it helps. 

EDIT: issuing 'npm whaomi' gives bunch of errors, do I need to have npm user created for this usage ?

**Comment by askmike** [comment]
So npm is package manager that comes with node. I have had similar problems when trying to combine different versions of node and npm. Please post the output of the following:

    node -v
    npm -v
    which node
    which npm

EDIT:

this is the output on my rasppi:

    pi@raspnode:~ $ node -v
    v7.9.0
    pi@raspnode:~ $ npm -v
    4.2.0
    pi@raspnode:~ $ which node
    /usr/local/bin/node
    pi@raspnode:~ $ which npm
    /usr/local/bin/npm

**Comment by generalectric** [comment]
It works fine here on rpi3 with jessie lite... though I do recall having that exact same error moment.js at some point. This is what Im running at the moment with no problems.

    adm1n@rpi:~ $ node -v
    v7.6.0
    adm1n@rpi:~ $ npm -v
    2.15.11
    adm1n@rpi:~ $ which node
    /usr/local/bin/node
    adm1n@rpi:~ $ which npm
    /usr/local/bin/npm
    adm1n@rpi:~ $ lsb_release -a
    No LSB modules are available.
    Distributor ID: Raspbian
    Description:    Raspbian GNU/Linux 8.0 (jessie)
    Release:        8.0
    Codename:       jessie

**Comment by wereii** [comment]
![image](https://cloud.githubusercontent.com/assets/8504482/25395374/2944ee64-29e1-11e7-9bd6-7957b1221086.png)

I see the difference, will look in this.

**Comment by askmike** [comment]
that's not bad perse, but it's very strange. Could you put the content of `/home/pi/gekko/node_modules/moment/moment.js/` in a gist and link it here?

**Comment by wereii** [comment]
I ~~am~~ was running. 
Latest npm error was EACESS according to logs it was unable to acces /home/pi/gekko/node_modules - weird. 
But otherwise it prints 'TAlib disabled' 'serving geko on ip:port' 

And then  UnhandledPromiseRejectionWarning and DeprecationWarning .

My moment.js - https://gist.github.com/tinytom/17fe72765612c78ec9d59ac978e2596f

**Comment by askmike** [comment]
> Latest npm error was EACESS according to logs it was unable to acces 

Very strange, are you currently still having problems with anything?

> But otherwise it prints 'TAlib disabled' 'serving geko on ip:port'

Great, everything is working!

> And then UnhandledPromiseRejectionWarning and DeprecationWarning .

This is harmless. You are seeing this because your UIconfig has headless configured to false. Which means Gekko will try to open a browser on that machine (which is failing). Gekko is running and you should be able to connect, let me know how it goes.

**Comment by wereii** [comment]
Gekko running, web avaliable.  
Voila, my thanks guys. 

I still don't know what was wrong, also there are some problems with node / npm on RaspberryPi as I was again able to have multiple versions all around pi, and thats not only one time it happened to me with something on linux. One from raspbian repos (apt-get install ), one using curl from nodejs.org and third by installing tar from same site.

**Comment by wereii** [comment]
Back here. 
Sqlite didn't installed properly, without sudo it says EACESS with sudo it gets weird. 
![image](https://cloud.githubusercontent.com/assets/8504482/25404725/516f7c40-2a01-11e7-938c-99a8a4fef580.png)

I selected paper trader, hit MACD and clicked run, console said sqlite is missing try npm install it. So I am doing it right now.

**Comment by askmike** [comment]
sqlite is a dependency for Gekko that needs to be compiled. If you run a LTS version of nodejs (or some other versions) npm will download pre compiled binaries. This screenshot simply shows that precompiled binaries are not available for your version of nodejs (7.9.0). But after these errors it will try to compile from source. So please also screenshot what happens after these lines, because these lines are not that important.

**Comment by wereii** [comment]
Sorry for my latest fake alert. 
It compiled with 0 errors, gekko is running again no errors showing up I am already importing data from poloniex. Thx again, closing.

**Comment by askmike** [comment]
👍  if you run into antything else let me know :)
