### ISSUE TITLE
Backtesting with talib causes incorrect candle dates 

### ISSUE THREAD

**Issue by southerton81** [askmike/gekko#715]
I have encountered a problem when backtesting, it manifests when I add talib indicator to mock strategy. Tested on 1m and 15m candles and it produces gaps in the log. 1 hour candles work ok. 

```
var strat = {};

strat.init = function() {

  var settingsSMA = {
    optInTimePeriod: 20
  }

  this.addTalibIndicator('mysma', 'sma', settingsSMA);
}

strat.update = function(candle) {}

strat.log = function() {}
strat.check = function(candle) {
  console.log(candle.start.format());
}

module.exports = strat;

```

> 2017-04-27T20:54:00+03:00
2017-04-27T20:54:00+03:00
2017-04-27T20:54:00+03:00
2017-04-27T20:54:00+03:00
2017-04-27T20:54:00+03:00
2017-04-27T20:54:00+03:00
2017-04-27T20:54:00+03:00
2017-04-27T21:02:00+03:00
2017-04-27T21:02:00+03:00

Here's a related closed issue, however, the case seems to be different. #681

**Comment by askmike** [comment]
Nice find! Investigating..

**Comment by askmike** [comment]
I'm pretty sure I fixed this, I was relying on `this.candle` which in case of async indicators (such as talib) might be more recent than the candle this indicator was run over.

Can you download the develop branch and see if this fixed it for you?

**Comment by southerton81** [comment]
Switched to develop branch and the problem is gone, thank you. 
I assume the problem was only with backtesting, not real market watcher.

**Comment by askmike** [comment]
yes indeed: with backtesting the strat gets fed a lot of candles very quickly. This was the result of a race condition (also the reason why you only saw it with 15min and not with 1h candles), which won't happen in realtime mode since candles only come per minute.
