### ISSUE TITLE
[feature request] UI improvements

### ISSUE THREAD

**Issue by tudorconstantin** [askmike/gekko#716]
I think that implementing the below features would be **highly appreciated** by the ones who are using gekko
- add the option to close the modal when the connection is re-established
- add the ability to click on any elements in the row when selecting the dataset in backtesting

**Comment by tudorconstantin** [comment]
I've implemented the above and submitted the PR #717

**Comment by askmike** [comment]
I commented on the PR!

> add the option to close the modal when the connection is re-established

The reason for the modal after reconnection is that the state in the web UI is broken:

When you load the UI in your browser the UI will fetch state of current gekkos (live gekkos, imports, etc), after that websockets are used to keep the state up to date. But in case the UI is reconnected you might have missed a ton of websocket messages (maybe the UI was disconnected for X hours), so all state displayed in the UI can be out of date. To fix we need to refetch state and the easiest way to do this (right now) is refresh the browser.

**Comment by askmike** [comment]
Let's keep the discussion about the reconnection modal in the PR instead of having it in 2 different places!

**Comment by askmike** [comment]
Both of improvements have been merged (into develop branch, will merge into stable branch very soon). So I am closing this already :)
