### ISSUE TITLE
Command line Backtest VS UI Backtest VS Real Trading

### ISSUE THREAD

**Issue by jeremyloe** [askmike/gekko#718]
In the config.js - CandleSize should be based on minutes correct?

config.tradingAdvisor = {
  enabled: true,
  method: 'RSI',
  candleSize: 5,          //5 minutes
  historySize: 10,
  adapter: 'sqlite',
  talib: {
    enabled: false,
    version: '1.0.2'
  }
}

When running the command line backtest all looks good and mostly matches the UI test

But when performing a real trade. I see the following statement as it starts up.
The trading method requests **50 minutes of historic data**. Checking availability... 
This would mean the config.js candlesize is based on a hour right?

When I run the same settings in the UI backtester it shows
Warmup period (in 5 minute candles):
(will use 50 seconds of data as history)

If I modify the UI backtester to 5 hour candlesize it shows
Warmup period (in 5 hour candles):
(will use 50 minutes of data as history)

**Comment by askmike** [comment]
> When I run the same settings in the UI backtester it shows
> Warmup period (in 5 minute candles):
> (will use 50 seconds of data as history)

This is a display bug in the UI! It will actually require 50 minutes of historical data. So the CLI and the work the same way & always require the history:

     candleSize * historySize (in minutes)

*Note that historySize is labeled as warmup period in the UI.*

**Comment by askmike** [comment]
this is now fixed in the develop branch, issue will close once it will be in stable.
