### ISSUE TITLE
Dynamically loaded indicators

### ISSUE THREAD

**Issue by generalectric** [askmike/gekko#725]
I got an idea last night when I thought about using multiple strategies and trying to figure out combined results... if one strategy sold and another bought. So I got to thinking and figured.... shouldnt it be pretty straight forward to create a multi-talib strategy that dynamically loads all indicators like so....

    var talind = ['ACCBANDS','AD','ADOSC','ADX' etc.........];

    for (i = 0; i < talind.length; i++) {
          if(`settings.${talind[i]}.enabled` == 'true')
                  this.addTalibIndicator(talind[i].toLowerCase(), talind[i].toLowerCase(), `settings.talind[i]`);
    }

the above is not working btw thats another question.... how do I make the setting check work with a variable that can loop through all the indicators and enable the selected ones.

And for config just make one giant toml though the following is in config format...

    ACCBANDS: {
      enabled: true,
    },
    AD: {
      enabled: false
    },
    ADOSC: {
      enabled: false
    },
    ADX: {
      enabled: false,
      optInTimePeriod: 1,
    },

etc...............

Any thoughts?

**Comment by thegamecat** [comment]
Yep nothing wrong with that, big issue is the way you build the loop in async.

**Comment by askmike** [comment]
Interesting Idea!

> the above is not working btw thats another question.... how do I make the setting check work with a variable that can loop through all the indicators and enable the selected ones.

Will look at that asap.

> I got an idea last night when I thought about using multiple strategies and trying to figure out combined results... if one strategy sold and another bought.

The main thing here is:

I designed the interface of strategies (put a file in `strategies`, make sure it has these methods, call `this.addIndicator`, etc.) according to what I think would be useful for people building generic TA based trading strategies.

In theory this still allows to do what you are doing, but can you explain what you are trying to achieve? Eg. I can easily add another method called `addAllTalibIndicators`, but why are you trying to calculate all indicators? Simply said: If you can explain what you are trying to do I can let Gekko help you do that (if other people and me think it makes sense for Gekko ;) ).

**Comment by generalectric** [comment]
Well my idea was to make it simple for people to use multiple indicators in the UI... So have a strategy named multitalib for example. And a toml file with all settings for a list of Talib indicators with an enable or disable setting... As for the longs and shorts they are really just if less than if greater than for ups or downs... I mean there's some like bbands where you have band up band down and band middle would be kinda be left out. But the idea is loop through all the indicators for long and shorts for each indicator that's enabled. This would allow people to add one strategy at a time adjust the settings to get over all buys and sells where they want them while seeing them graphed and giving results. They will be able to use ten different indicators with tight settings where over a twenty day period one indicator may only short or long once but it was at an extreme high or low where another indicator would pick up the other entry or exit. This would allow people to add multiple TA's without having to write their own custom strategy.

**Comment by thegamecat** [comment]
I did exactly with 8 indicators, just not in a loop. 

It's pretty straight forward.

if settings.indicatorX.run== 1 then
etc

then just have indicatorX = 1 or 0  in the toml file with the indicatorX params and thresholds etc.

**Comment by generalectric** [comment]
So basically just a strategy that can make use of all talib indicators possible without writing a strat for each and every one. The output of each indicator read into an array then check the field names against the settings for that indicator in the config etc.... vs writing a massive strat for each one statically. Then people could simply select enable true and adjust the settings for each type of indicator they wanted to add to their strategy in the toml without having to write their own strategy. So I wasnt proposing some new functionality but rather just a multitalib strat that ships with gekko to give people the ability to use multiple strats without having to write their own custom strategy.

The other option is write a strategy for each and every one and make the backend run the strats async for combined results which is what I think yall are talking about?

I'll write a mock up and post it here in a gist!

**Comment by generalectric** [comment]
Ok so here is a quick mock up... i mean just an idea of course its not working but i think you should be able to see what im talking about. of course it would need some more work.

https://gist.github.com/generalectric/88222816467a31e943d328ee9273715f

**Comment by generalectric** [comment]
Correct way to do this would be create strat for each indicator and tie them together with gekko

I'm closing this one up due to lack of activity/interest

**Comment by askmike** [comment]
> Correct way to do this would be create strat for each indicator and tie them together with gekko

We can definitely do something like that, so I've been working on showing single stratrunners (=a gekko that runs in realtime with a strategy) in the UI. We have a lot of performance metrics such as profit, sharpe, current position (LONG or SHORT).

We can create a screen that plots all of these "stratrunners" (per market for example) in a table or grid, sorted by profit (or risk) with a color of their current position (green = currently long / red = currently short), that would help a lot for a systemic trading system (Gekko can help traders make decisions). What do you think?

**Comment by generalectric** [comment]
Sounds great! And then a way to pair two or more of them together meaning they would all have to agree to take action
