### ISSUE TITLE
Exchange question

### ISSUE THREAD

**Issue by kza95** [askmike/gekko#726]
Has anyone requested Whaleclub as an exchange? Because they have some interesting leverage options and different cryptocurrency pairs/forex that would be amazing when used with Gekko.

**Comment by askmike** [comment]
This has been asked but not done yet. See #680 for details :)

I won't have time to do this anytime soon unfortunately (too busy with #653 and #737).

TLDR: It's not hard to add exchanges for Gekko but I won't have time for this.
