### ISSUE TITLE
Running in cloud?

### ISSUE THREAD

**Issue by burtnderson** [askmike/gekko#729]
I have been backtesting Gekko on my local machine and am ready to try running it on an Amazon Ec2 instance. However, on the gekko.wizb.it site it says that it is recommended to use a reverse proxy. Is this needed if I only allow my local machine ip address to access my virtual machine? I have never heard of a reverse proxy before and am trying to understand what it is and if I would need one. I think Gekko is pretty amazing and would like to make sure I set it up properly.

**Comment by askmike** [comment]
If you run Gekko exposed to the internet everyone will be able to access the UI. With the UI you (and thus everyone else) can import some data and start a backtest. This will be very CPU intensive and may make your server unable to do other things. Once someone with bad intentions knows how to access your gekko he can backtest 24/7.

This is mostly dangerous if you run websites or some tools on the same instance.

-----

Note that if you just rent an instance for Gekko this is not really a problem right now. The main reason I added this to the docs is that in the short future you can manage your exchange balances through Gekko (live trade, etc) - exposing and giving access to your money (if you enable live trading).

Those are the risks, if you have any more questions feel free to comment :)

**Comment by burtnderson** [comment]
Okay thanks. I will go ahead and use NGINX just in case then. 

Not sure if you would know the answer to this, but I have another question about configuring the uiconfig.js for Amazon. I have edited the uiconfig.js to what it says on gekko.wizb.it, and was wondering if I change the "host: 'gekko.example.com'," line to my machine address? My amazon instance has a public and private ip address. Do you know which one I would change it to if needed?

**Comment by askmike** [comment]
> Do you know which one I would change it to if needed?

Yes the public one! This is needed so that the UI (webinterface - which runs in your browser) can properly connect to the gekko running on AWS. I'll try to clear this up in the docs.

**Comment by burtnderson** [comment]
Okay sounds good. I assume I would also change the "server_name gekko.example.com;" line in my nginx config file to my public ip too then?

**Comment by CyborgDroid** [comment]
What if you limit the access by IP address on the EC2 instance? That would make EC2 "invisible" to everyone else. Plus the nginx password.
