### ISSUE TITLE
Error on importing any local data (Invalid date?)

### ISSUE THREAD

**Issue by Stadicus** [askmike/gekko#731]
On a freshly installed Gekko on Linux Mint 18.1 the import of any local data fails. After specifying e.g. (poloniex) (USDT) (BTC) in three separate dropdown boxes with a timeframe of e.g. 3 days (not until now to be safe, but until yesterday), the following appears

Error Popup
> IMPORT ERROR: Gekko encountered an error and can't continue

Status information
> Importing data..
> 
> Market: poloniex:USDT/BTC
> From: 2017-04-29 22:51:00
> To: 2017-05-02 21:51:00
> Imported data until: Invalid date
> To go: 0 seconds

Strange: although using Gekko v0.4.9 and Gekko UI v0.1.10, the interface looks a bit different than in your installation video (the three dropdown boxes, for example)...
`

**Comment by askmike** [comment]
the three dropdowns was added last week: #707.

Could you let me know if there is any information in the commandline?

**Comment by greenbigfrog** [comment]
@askmike can most likely be closed

**Comment by 0xYasser** [comment]
this still happening for me.

**Comment by greenbigfrog** [comment]
@R7AL are you on the latest version of gekko?

**Comment by 0xYasser** [comment]
Never mind I fixed it, the issue was an error installing splitter. sorry

**Comment by greenbigfrog** [comment]
@askmike can be closed.
