### ISSUE TITLE
Issue With TA-LIB indicators

### ISSUE THREAD

**Issue by Pedro942** [askmike/gekko#732]
When I enable the Talib indicators in my strategy they tell me to install them (Error:

The plugin tradingAdvisor expects the module talib to be installed. However it is not, install it by running:

        npm install talib@1.0.2)
 After I do so this is what i get

C:\Users\xxxx\Desktop\BOTS\gekko-stable>npm install talib@1.0.2
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "talib@1.0.2"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code EBADPLATFORM

So can't we use them with windows 10 ? 

npm ERR! notsup Unsupported platform for talib@1.0.2: wanted {"os":"darwin,linux","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    darwin,linux
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\xxxx\AppData\Roaming\npm-cache\_logs\2017-05-04T01_17_35_913Z-debug.log

**Comment by generalectric** [comment]
It compiles fine for me on windows 10 using bash

also npm install talib is sufficient you do not need the version number

**Comment by Pedro942** [comment]
Okay i'm going to try this and give you results

**Comment by Pedro942** [comment]
Still nothing it keeps saying the same error

**Comment by askmike** [comment]
Unfortunately TAlib is not really supported under windows, see this issue from the library Gekko uses for TAlib integration: https://github.com/oransel/node-talib/issues/8

There is nothing we can do about it at this point. There is a discussion going about using another TA library here: https://github.com/askmike/gekko/issues/708 But that is early stage and will take a while.

**Comment by askmike** [comment]
I suggest running linux (in a virtualbox or something if you really need talib).

**Comment by deke997** [comment]
You can run gekko with TA-lib on Bash on Windows 10 (as long as you are running the 64 bit version of Windows 10). 
If you don't have Bash on Windows 10 yet, follow the instructions [here](https://www.windowscentral.com/how-install-bash-shell-command-line-windows-10)

Step 1: Open up bash and install node.js: (taken from [here](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions))

```
sudo apt-get update
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo apt-get install -y build-essential
```

Step 2: Install Git

`sudo apt-get install git`

Step 3: Download and install gekko: (taken from [here](https://gekko.wizb.it/docs/installation/installing_gekko.html)):

```
git clone git://github.com/askmike/gekko.git
cd gekko
npm install --only=production
```

Step 4: Edit the handle.js file (taken from [here](https://github.com/askmike/gekko/issues/708#issuecomment-296329300))

Navigate to gekko/plugins/sqlite:

`cd  ~/gekko/plugins/sqlite`

Change line 53 in handle.js from 

`db.run("PRAGMA journal_mode = WAL"); `

to 

`db.run("PRAGMA journal_mode = DEL"); `

(I use nano for this --> `nano handle.js`)

Step 5: navigate back to /gekko and make sure you have the correct version of talib (taken from [here](https://github.com/askmike/gekko/issues/908#issuecomment-319657408))

```
cd ~/gekko
npm remove talib
npm install talib@1.0.2
```

Step 6: Start gekko:

`node gekko --ui`

Everything should work then!

**Comment by thegamecat** [comment]
Great instructions Deke, I reckon this is worth including in the Gekko documentation.

Bash on windows is great.

**Comment by deke997** [comment]
@thegamecat @askmike I created a PR to update the docs with this info.
