### ISSUE TITLE
Needing some strategy example

### ISSUE THREAD

**Issue by Pedro942** [askmike/gekko#733]
Hi guys i would like to ask if someone or even you Askmike can post a strategy using a native MACD and a SAR from Talib just to set it as an example because I don't really know how to do it even if i've read the documentation.

Just one example of a strategy using a native MACD and Talib SAR please i'm in need of it.

**Comment by Pedro942** [comment]
Sorry for the second post, Even a 2 native indicators can be good for me as long as I have a windows OS (and for 2 indicators i want gekko to buy only is they both say BUY or Sell for example if only one works it shouldn't do anything.

**Comment by askmike** [comment]
dup of #736.
