### ISSUE TITLE
Propose buy/sell orders

### ISSUE THREAD

**Issue by generalectric** [askmike/gekko#742]
Currently in gekkos strategies we can either long or short. If we had the ability to create buy and sell orders at a price point our strategies could have a sliding buyin for instance to move up or down with the ema each candle... ie: advice('buy', 0.00044645)... advice('buy', candleEMA)... this would be especially useful for catching dips on uptrends. Any thoughts?

**Comment by askmike** [comment]
I like the idea a lot!

One thing to note is that it will be very hard to backtest strategies that use this (with the current historical data Gekko is gathering). Doing this properly requires syncing the orderbook and simulating orders on that level.

Another thing is that I am working on is the live trader, for now I want to get the existing live trader integrated in the UI (see #737) which uses limit orders (eg. orders where you can actually set a price for). But after that: I am thinking about the trader to have different execution algorithms, one with limit orders and one with market orders (depending on how quickly you want Gekko to take a position). You cannot set a price for market orders..

**Comment by generalectric** [comment]
Awesome! I think I found it... From placing and checking to see if it was filled, to recreating the order, it looks like most of the work to create the functionality I'm looking for is already done. Nice job! I'm gonna close this up as I didn't realize you were already working on this.

**Comment by askmike** [comment]
Great :) If you need to know anything don't hesitate to ask!
