### ISSUE TITLE
Error during WebSocket handshake

### ISSUE THREAD

**Issue by Rogmodr** [askmike/gekko#752]
Hi!
I'm install Gekko on debian VM and configure nginx as described here: https://gekko.wizb.it/docs/installation/installing_gekko_on_a_server.html

But only for websocket requests i got this:
WebSocket connection to 'wss://192.168.1.139/api/' failed: Error during WebSocket handshake: Unexpected response code: 404
reconnecting-websocket.min.js: formatted:46 

pls, help me with this beautiful this project

**Comment by askmike** [comment]
The response is 404, which means `wss://192.168.1.139/api/` resolves to a server (most likely NGINX) but NGINX does not know how to properly upstream it. The IP address sounds like you are running Gekko in a local network. Can you try connecting to Gekko without NGINX?

**Comment by Rogmodr** [comment]
I deploy gekko to VM, all working fine when inside VM, but when i try connect from host - UI working fine, ws request failing with error above

**Comment by Rogmodr** [comment]
![default](https://cloud.githubusercontent.com/assets/13059687/26283679/3ff3636c-3e35-11e7-8073-5a3e85492080.png)
my nginx config
![default](https://cloud.githubusercontent.com/assets/13059687/26283694/737645ce-3e35-11e7-84e9-02d8336a3f36.png)
gekko vue UIconfig

**Comment by askmike** [comment]
Your config looks fine, it might be a problem with your VM environment. What kind of VM software are you using?

EDIT:

Actually, can you change this:

    upstream websocket {
        server localhost:3000;
    }

to:

    upstream websocket {
        server http://localhost:3000;
    }

**Comment by Rogmodr** [comment]
Hypper-V on windows 10, Debian 8 on VM

**Comment by askmike** [comment]
Nevermind my previous EDIT, do you have access to nginx logs? Usually they are stored in `/var/log/nginx/access.log` and `/var/log/nginx/error.log`. They might have more information about why NGINX is returning a 404.

**Comment by Rogmodr** [comment]
errors
![default](https://cloud.githubusercontent.com/assets/13059687/26283934/523bab3e-3e39-11e7-94b7-dff378a8867c.png)
access
![default](https://cloud.githubusercontent.com/assets/13059687/26283964/c9c734ca-3e39-11e7-9c85-9d20f1d8f4e2.png)

**Comment by askmike** [comment]
So the error log is saying that the connection was refused by `http://127.0.0.1/api/`. Which seems to indicate a problem with the Gekko server not listening. If you run the following command:

    sudo netstat -pantu

Do you see anything listening on part 3000?

**Comment by Rogmodr** [comment]
Hmmm, should i run 2 gekko instances for api and ui?

**Comment by Rogmodr** [comment]
after i run "node gekko --ui" netstat:
![default](https://cloud.githubusercontent.com/assets/13059687/26284392/7f6538d8-3e42-11e7-9c0b-17cd7f90c66f.png)

**Comment by generalectric** [comment]
also host in the ui should be set to server name as per your nginx conf as server_name

    const CONFIG = {
      headless: true,
      api: {
          host: '127.0.0.1',
          port: 3000,
      },
      ui: {
          ssl: true,
          host: 'some.server.name',
          port: 443,
          path: '/'
      },
      adapter: 'postgresql'
    }
    
    if(typeof window === 'undefined')
      module.exports = CONFIG;
    else
      window.CONFIG = CONFIG;

**Comment by askmike** [comment]
You need to run gekko once (node gekko --ui), but it needs to keep running.

So when it was not working, you still had it running?

**Comment by Rogmodr** [comment]
when i try it all requests in my browser go to some.server.name and all failing when dns server on router can't resolve it

**Comment by Rogmodr** [comment]
yes, i run one gekko instance in separate session

**Comment by generalectric** [comment]
headless should be true... though i believe that just prevents a call for local browser open... and change some.server.name to 192.168.1.39 in both configs or set it to a domain name though you still need ports 80 and 443 forwarded to your local ip. is some.server.name a FQDN? looking at your error line server is blank

**Comment by askmike** [comment]
General: you don't need to specify a servername, if you don't use one nginx
will always serve using that config. Also the error log states that nginx
tried to upstream but could not. So the issue is between nginx and gekko.

So just to be clear: in the VM you can access the UI fine, but outside it
(from the host) you cannot. Are both these situations using nginx? Are you
able the use the UI from the host machine without nginx (by directly
connecting to the UI)?

**Comment by generalectric** [comment]
and what is the result of netcat -v 127.0.0.1 3000

**Comment by Rogmodr** [comment]
generalectric:
![default](https://cloud.githubusercontent.com/assets/13059687/26285611/11aa1b3c-3e5c-11e7-9b47-fc32a338afb1.png)

 askmike:
yes, but i can't test all on VM - no UI, cli installation. From host not working only websocket communications. Js UI loaded fine, take a look gekko output:
![default](https://cloud.githubusercontent.com/assets/13059687/26285761/7792cabe-3e5e-11e7-9f78-0e85e121278e.png)

**Comment by Rogmodr** [comment]
> Are you able the use the UI from the host machine without nginx (by directly connecting to the UI)?

How to check it?

**Comment by askmike** [comment]
Check here: https://gekko.wizb.it/docs/installation/installing_gekko_on_a_server.html#Configuring-Gekko-to-run-headless-in-a-trusted-environment

Follow the steps under "Configuring Gekko to run headless in a trusted environment" And not the ones under "Configuring Gekko to run in the cloud".

**Comment by generalectric** [comment]
Rogmodr: heres my output both ui running:

    Connection to 127.0.0.1 3000 port [tcp/*] succeeded!

and not running:

    netcat: connect to 127.0.0.1 port 3000 (tcp) failed: Connection refused

do you have any firewall rules set?

**Comment by Rogmodr** [comment]
@askmike it's really work, but now i can't use Postgresql adapter because all my configs not loading in UI mode - how to setup it?

**Comment by askmike** [comment]
> because all my configs not loading in UI mode

What do you mean with this?

**Comment by Rogmodr** [comment]
When i start with -c config.js - configs loading from this file.
When i start with --ui - what config file i should update with my pg creds?

**Comment by askmike** [comment]
Ah like that:

- you need to set postgresql here: https://github.com/askmike/gekko/blob/stable/web/vue/UIconfig.js#L18
- and you need to configure credentials here: https://github.com/askmike/gekko/blob/stable/web/routes/baseConfig.js#L51

**Comment by Rogmodr** [comment]
Thanks! Your product really cool 👍 🥇
