### ISSUE TITLE
Not really an Issue, but a Question 

### ISSUE THREAD

**Issue by trendgiver** [askmike/gekko#753]
How do I set 1 min. candle size in config.tradingAdvisor 
there are lines:
  candleSize: 1,
  historySize: 3,

is candle size 1 = 1 min or 1 hour ?

**Comment by askmike** [comment]
it's in minutes! So `1` is 1 minute and `60` is one hour. If you have more questions just feel free to ask. Also note that you can use the UI for almost everything, it's a lot more user friendly :)
