### ISSUE TITLE
Is it possible to visualize real trader trade history?

### ISSUE THREAD

**Issue by darklow** [askmike/gekko#760]
Thank you for all the great work and time invested in this library. I find it very interesting to experiment with and well built. I did some days of backtesting and just started some experiments with real trader using command line. 

Question: Is it possible to somehow visualize real trader buy/sell points in real-time (or based on some logs afterwards) the same way as strat runners are being visualized? It would be great to see real trader history along strat runners in web ui.

Thanks.

**Comment by askmike** [comment]
Not yet, but that is the next upcoming feature (the trader will be part of the UI as well). See here for more info: #737
