### ISSUE TITLE
Feature to stop strat runner or market watcher

### ISSUE THREAD

**Issue by darklow** [askmike/gekko#761]
Have I missed it or there is currently no way how to stop either a Strat runner or Market watcher? I've set up few, but now I would like to stop some strat runners, without restarting app, because I don't want to interrupt Market watchers, but can't find any stop buttons.

Is there a way to discover strat runner PID and kill them by PID in process list?
Thanks.

**Comment by askmike** [comment]
There is currently now way..

Yes this keeps slipping through! Will definitely be part of the next release!

**Comment by askmike** [comment]
I will track this feature in #911.
