### ISSUE TITLE
Running Live Mode with Docker

### ISSUE THREAD

**Issue by MrBsGit** [askmike/gekko#763]
Hi,

When I start Gekko in a Docker container it automatically fires up the UI, but it doesn't start live trading mode although I configured it in the config.js file.

Am I doing something wrong or is it not possible yet to run live trading in a Docker container?

**Comment by askmike** [comment]
So instead of starting up the gekko UI you want to run a commandline single version (that does live trading) instead?

Edit [this line](https://github.com/askmike/gekko/blob/stable/package.json#L14) to how you want to start gekko and try again :)
