### ISSUE TITLE
E403: https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/node-v51-linux-arm.tar.gz 

### ISSUE THREAD

**Issue by PhillRob** [askmike/gekko#764]
running `npm install --only=production`a `AccessDenied` error gets retruned for ` https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/node-v51-linux-arm.tar.gz `

**Comment by askmike** [comment]
This is most likely not a fatal error. npm will fallback compiling manually. If it is a fatal error, post full logs.

Another note: Are you running node 5.1? If so: Gekko requires a node version higher than 6, we recommand the LTS version.
