### ISSUE TITLE
Emit config settings to strategy

### ISSUE THREAD

**Issue by thegamecat** [askmike/gekko#768]
Is there currently a way of reading the config settings from a strategy? 

It would be useful to be able name / categorize csv output files with the coin pair, candle size etc, having to do this manually at the moment.

**Comment by askmike** [comment]
Do you mean that you are using the API to backtest? The config settings of the strategy where part of the input (the POST request) so you should have access to it in your own code, or not?

as in, if you want run X backtests and store the result in CSV your pseudo code can look something like this:

    var config = { tradingAdvisor: { strategy: 'MACD', ...}, macd: {short: 10, long: 21, ..} }
    request.post('/api/backtest', config, (error, result) => {
        // here you have access to both config (which includes your strat settings) and the result
    })

**Comment by thegamecat** [comment]
Ah no. Already sussed that bit out for calling via the API. I only use that approach when using the GA.

What I'm referring to here is when I run a strat backtest or live through the UI or command line. 

So the strat - on initiation would be great if it knew the config settings.

**Comment by askmike** [comment]
When you use the UI the strat settings you used will still be visible above the backtest results, scroll up (if not that's a bug and please share a screenshot). So this only really applies to the commandline version:

You can hack it in yourself by logging the config around here: https://github.com/askmike/gekko/blob/stable/plugins/tradingAdvisor/tradingAdvisor.js#L47

But I don't think this is something that would benefit other users (easy way would be stringifying JSON, which goes against readability).

**Comment by thegamecat** [comment]
I don't think we're talking about the same thing tbh.

Let's say I want to write the strat output to a csv file via fsw.appendFileSync(this.fname, outtxt, encoding='utf8');

I would like this.fname to be - strat name (from config) - candlesize (from config) - asset name (from config) - currency name (from config)

How do I achieve this?

**Comment by askmike** [comment]
> Let's say I want to write the strat output to a csv file via fsw.appendFileSync(this.fname, outtxt, encoding='utf8');

Gekko doesn't have any existing functionality or plugins to write CSV files, so whatever the case you have to script this yourself.

I think by far the easiest way would be to spin up the gekko server and write a little script that calls the API to do a backtest and writes the results you want to a CSV file. Because as soon as you start doing `fs.appendFileSync` within Gekko code you most likely break a bunch of things since the event loop gets delayed.

Another option would be to [create a plugin](https://gekko.wizb.it/docs/extending/add_a_plugin.html), however I am assuming you want to log the results of the backtest as well, which requires access to data currently not part of the plugin event system (will be at some point in the future).

**Comment by thegamecat** [comment]
Sorry it's not the csv bit, I've got that already, it's the data from the config I'm asking about.

And fyi the appendfilesync works wonderfully and breaks nothing :)

**Comment by askmike** [comment]
> And fyi the appendfilesync works wonderfully and breaks nothing :)

It might, there might be bugs and things might not work as expected. If everything works, great.

> Sorry it's not the csv bit, I've got that already, it's the data from the config I'm asking about.

I think we are not talking about the same thing. Where have you written all your code? If within the gekko codebase just import the main util and call `util.getConfig()`?

**Comment by thegamecat** [comment]
Oh wow that sounds perfect. I'll try that in a bit!

**Comment by thegamecat** [comment]
I am a fool...this was already being referenced....doh.

var config = require('../core/util.js').getConfig();
