### ISSUE TITLE
Live - buy happens at different price to market value at decision time

### ISSUE THREAD

**Issue by thegamecat** [askmike/gekko#775]
How far after the decision to buy does a buy actually happen, and what is the basis for the buy price? 

I'm seeing a different buy price (sometimes higher) on the exchange than the price quotes in the gekko console.

This is in live trading.

**Comment by thegamecat** [comment]
I've looked at the portfolio trader and it's clear why this is happening. There is a lag (not sure why) between when it makes the decision and the buy price which the system calculates as the market ticker. How do i get this to place an order at the price "decided" at the point of decision?

I don't see any value made available to the portfolio trader should I wish to buy/sell at that price. It would be great to have that option should I wish to use it.

**Comment by askmike** [comment]
> There is a lag (not sure why) between when it makes the decision and the buy price which the system calculates as the market ticker.

As soon as your strat signals a BUY signal the portfolioManager will try to execute (the delay between this should not be more than a few ms). However in order to execute Gekko needs up to date information on your account balance so it needs to fetch the ticker and the portfolio this adds a delay. However the impact of this should not be significant.

When you are talking about a lag, what sort of time are you talking about? A few ms, a few seconds or more?

**Comment by thegamecat** [comment]
What ive noticed is that the bid and ask are the wrong way round for my strat however just swapping them doesnt work with any reliability either. So I am working on testing some new logic. What I have noticed also is the cancel order api call is pretty random as well, if often doesnt happen.

**Comment by askmike** [comment]
Do note that the new trader I am working on (see open PR) has a different
execution strategy. With the bid and ask flipped (to not cross spread but
slower execution). Maybe you can look for inspiration there.

**Comment by thegamecat** [comment]
OOO I look forward to seeing that!

I have already swapped bid and ask to assist, but the cancel doesn't work most of the time  - using polo or btce

**Comment by zeroX-tj** [comment]
On Kraken it did work most of the time, i had them swapped too for some time now because of this behavior.

Probably fails if the api times out/has other issues, there is no retry for errors?

**Comment by thegamecat** [comment]
The cancel on btc doesn't exist and the polo one seems to fail most of the time.

**Comment by askmike** [comment]
That seems like a completely unrelated error. This issue now describes your
experience with different exchanges for different problems without any
details. Could you create an issue per issue and attach logs and debug
information (logs, errors) per issue?

**Comment by askmike** [comment]
I am closing this, feel free to keep responding :)
