### ISSUE TITLE
Candles of multiple sizes

### ISSUE THREAD

**Issue by f0o** [askmike/gekko#778]
Is it possible to have multiple resolutions of the candles in the same strategy?

Say I want to combine multiple indicators but feed them candles of different sizes to each, how would I go on doing this?

**Comment by dozoisch** [comment]
The way right now would be to use the smallest denominator and aggregate candles yourself in bigger candles inside the update function.

**Comment by thegamecat** [comment]
A guy has forked gekko to do this, but I haven't looked at it personally.

**Comment by f0o** [comment]
@dozoisch yeah that's what I currently do, just wasn't sure if there was a global function (such as the BatchCandles et. al) that could relief me from code-duplication.

@thegamecat Do you recall the guy's name? I'd like to check it out :)

**Comment by tomih** [comment]
@f0o it's here: https://github.com/tomih/gekko/tree/multitimeframe

**Comment by f0o** [comment]
Thanks!
