### ISSUE TITLE
Live trading not available 

### ISSUE THREAD

**Issue by NoobFullStack** [askmike/gekko#779]
I finally got it all running on a Ubuntu 16.04 virtual machine. Was able to fetch the market data via the localhost:3000 web interface.. After some tweaking i got a back test making 380.000%. Lovely to find out how a live trade on that would go, but the webinterface tell me :

Live trading is not available. 

Any idea what i have wrong?

**Comment by dghete** [comment]
Live Trader in UI is still work in progress. 
You can check the progress here: https://github.com/askmike/gekko/pull/737

**Comment by NoobFullStack** [comment]
I just noticed. I'm very sorry for opening an issue for this. Gonna try to make it working without the ui.
