### ISSUE TITLE
Run on ubuntu fail after install: Cannot find module 'moment'

### ISSUE THREAD

**Issue by scidran** [askmike/gekko#783]
Hi to all.
I'm a newbie abuot trading bot and i don't know very well code language...
I tried to follow a guide to intall gekko on ubuntu 12.04 but i have 16.04.

I've done all these steps:
sudo apt-get install nodejs
cd $home
git clone git://github.com/askmike/gekko.git
cd gekko
npm install
node gekko

This is the output:
module.js:328
    throw err;
    ^
Error: Cannot find module '/home/fabio/gekko'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

What is the problem?

**Comment by acceleratorlastorder** [comment]
Hello, you should look at this https://gekko.wizb.it/docs/installation/installing_gekko.html,

git clone git://github.com/askmike/gekko.git
cd gekko
npm install --only=production
node gekko --ui
if everything is alright a server should be available on http://localhost:3000/
:)

**Comment by scidran** [comment]
Ok: i had to install also nodejs at 6.x version manually... but all work fine now!
Thanks!

**Comment by developdaly** [comment]
I had an old version of `npm` which didn't do all of the installation. Updating from `3.10.10` to `5.3.0` fixed it.
