### ISSUE TITLE
Docker startup: exec user process caused "no such file or directory"

### ISSUE THREAD

**Issue by subhead** [askmike/gekko#784]
Hello,

when i startup the docker containers with `docker-compose up -d` the redis container comes up fine but the gekko container keeps restarting all the time. When i check he docker logs i can only see the message `standard_init_linux.go:178: exec user process caused "no such file or directory"`.

I tried to rebuild the containers but the problem still exists. Does anybody know what the problem here is?

Thanks!

**Comment by anysomewhere** [comment]
Had the same problem. If you run it on windows check for correct line endings of the file "docker-entrypoint.sh".

**Comment by subhead** [comment]
I tried to run gekko on windows so the line ending did the trick. thank you!
