### ISSUE TITLE
How to run multiple instances with Docker

### ISSUE THREAD

**Issue by subhead** [askmike/gekko#785]
Do i need to clone the complete repository again to run a second instance of gekko or what is the best way to run multiple instances?

sorry for asking that but im quite new to the docker thing.

**Comment by askmike** [comment]
ping @DeviaVir, do you know this?

**Comment by DeviaVir** [comment]
@subhead I wonder why you would want to run multiple instances, since I think you can run multiple gekko's on a single one..

regardless, here is how that would look like (`docker-compose.yml`):
https://gist.github.com/DeviaVir/3eee73245cb0b0df16c783dc54d68795

**Comment by subhead** [comment]
How can i run multiple gekkos in a single container? Thats the thing i want to archive.

**Comment by BarnumD** [comment]
A common methodology with contains is to run multiple instances of
something in different contains.  The instances may or may not have
different run parameters.
