### ISSUE TITLE
Option in UI to delete local data

### ISSUE THREAD

**Issue by shanehull** [askmike/gekko#786]
An option in the UI to delete local data would be helpful.

I've also accidentally selected "BTC:BTC" as an import and now I receive the following error every time I scan available data:
<img width="979" alt="screen shot 2017-06-16 at 12 29 06 pm" src="https://user-images.githubusercontent.com/20835304/27209564-df19ef2e-528f-11e7-8512-89fc817a4624.png">

It would be good to be able to delete those too, or maybe restrict doubles from being selected at the importer!

**Comment by askmike** [comment]
Deleting is definitely something I'll put on the backlog (not a very big priority though).

> or maybe restrict doubles from being selected at the importer!

If you import data you already had it nothing bad will happen. The "Unable to find datasets" message usually only pops up if you started an import which did not run. In your picture: The market BTC/BTC does not make sense. Did you select this through the UI or via the CLI?

**Comment by shanehull** [comment]
I selected it through the UI by accident, then (I think) I hit import!

**Comment by askmike** [comment]
Ah that's something we can solve: you should be able to select BTC/BTC (as it does not make any sense), this should stop Gekko from displaying the warning message.

**Comment by AntiLopa** [comment]
For the meanwhile, can you describe how would one delete dataset manually?

**Comment by askmike** [comment]
yes: assuming you are storing data in sqlite (the default), either connect to it using the commandline or use a tool like this: http://sqlitebrowser.org/

You can open the database file for the exchange that has the wrong market and delete the whole table for that market :)

**Comment by AntiLopa** [comment]
Cool, and where is the database file locate?

**Comment by askmike** [comment]
in the history folder: `gekko/history`.

**Comment by AntiLopa** [comment]
Great, thanks.

**Comment by PlayboySatoshi** [comment]
Also I think It`ll be useful to add the size of the data in that table
