### ISSUE TITLE
BTCC FEE is error

### ISSUE THREAD

**Issue by 383131600** [askmike/gekko#788]
2017-06-17 20:04:12 (INFO):     BTCC trading fee will be: 0%

unable to sell: { Insufficient balance: BTCChina.executeRequest() API returned error code -32004 from POST request to url https://api.btcchina.com/api_trade_v1.php with tonce 1497701075550000, method sellOrder2 and params [18804.01,0.0053,"BTCCNY"]
Error message: Insufficient balance

The FEE is 0.2%

**Comment by askmike** [comment]
I am working on a new trader (as part of the UI) and I will go over all exchange integrations and fix them, I've put BTCC on the list as well. See # Hope to fix this soon!

**Comment by 383131600** [comment]
Sir, I also found a serious problem. When I fix the fee, the order price of the robot in cmd was different from the price actually released in BTCC, and I tried a variety of settings. The selling price must be less than the buying price.

buy=买入
sell=卖出
success deal=全部成交
![image](https://user-images.githubusercontent.com/20080808/27474890-e07ed360-5835-11e7-945a-d8b84b46e643.png)

**Comment by askmike** [comment]
Hello, I am trying to fix compatibility with Gekko and BTCC. However I am unable to find the page where I can create API keys. Where did you create those for BTCC?

**Comment by reppolice** [comment]
@askmike https://www.btcchina.com/account/apikeys

**Comment by askmike** [comment]
Unfortunately BCC is not enabled anymore..
