### ISSUE TITLE
UI shows no data when accesing from remote

### ISSUE THREAD

**Issue by subhead** [askmike/gekko#790]
I have a gekko instance running on a second laptop and all is working fine when i use the browser installed on this laptop. But when i use a other computer and browser to access the gekko instance i cannot see any gathered data or the running market watchers.

How can i access the gekko ui from a remote computer?

**Comment by askmike** [comment]
What do you mean cannot see any data? When you click on the "scan data" button nothing pops up?

**Comment by subhead** [comment]
i cannot see any running market watchers or when i click on scan data it did not shows any previous gathered data.

**Comment by askmike** [comment]
It sounds like you are running 2 gekkos: You only need to start Gekko once (with `node gekko --ui`).


If you have 2 computers and want to run Gekko on computer A and watch it on computer B (and A) you need to follow these instructions: https://gekko.wizb.it/docs/installation/installing_gekko_on_a_server.html#Configuring-Gekko-to-run-headless-in-a-trusted-environment

The gist is:

- configure the Gekko (using UIconfig) to listen for network connections, and set the UI up for connecting to Gekko over a network.
- start Gekko once (on the machine you want to run it)
- Connect to Gekko everywhere by typing in your browser `http://[IP ADDRESS]:3000`.

If that does not solve it, please reply here :)
