### ISSUE TITLE
Installation issues on Raspberry Pi 1B (sqlite3)

### ISSUE THREAD

**Issue by Yroethiel** [askmike/gekko#792]
Short version: Have spent four days trying to get gekko installed on an original Raspberry Pi B, with no luck. Issue is unable to install sqlite3 for some reason. I see in config.js it's possible to define other database options...would it be possible to find some guidance on how to use something other than sqlite3?

Background:

- First issue was finding an appropriate version of node for armv6 architecture, which was eventually successfully installed (6.11.0).
- Cloned latest gekko via git, went into directory, ran install with npm with no issues (npm version 5.0.3) (a few deprecated warnings, but all worked out fine)
- I can initiate gekko in ui mode, and the interface at localhost:300 works (haven't tried any functionality)
- Moment I try run gekko in live mode, gekko drops with an error saying sqlite3 isn't installed (candleWriter)
- Unsure why the npm package didn't seem to pick sqlite3 up, I see there's a previous issue for gekko which was resolved after compiling from source (#711)

Google-fu has led to a number of solutions for installing sqlite3...I've tried with sudo, without sudo, with --unsafe-perm enabled, without, older versions of sqlite3, newer versions, compiling from source (latest gcc and g++ installed), using npm to remove everything, using different versions of npm.

The error I get during building from source is "EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.11.0" ". I've tried running without using root, and get a permission denied error for trying to access "../gekko/node_modules"

Unsure where to go from here - each install attempt can take an hour+, and have tried several options. There does seem to be a lack of armv6 support for sqlite3, hence asking how to configure gekko to use something else. Perhaps if I were to successfully be able to get past the "access denied" issues with/without root?

Any help appreciated! Loving gekko and have done well with it - just hoping to run it off a Pi instead of my laptop!

**Comment by askmike** [comment]
Greetings,

I have Gekko running on my raspberry PI as well and I have no problems, so I can tell you it is possible.

> The error I get during building from source is "EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.11.0" ".

Very strange, sounds like something went really wrong during installation.

------

## The sqlite way:

NVM manages nodejs versions but it does this by creating different folders -> it might just be the case that this way node-gyp would not use `/root/.node-gyp/6.11.0`. You can install it like so: https://github.com/creationix/nvm#install-script (and after installing it, run another version of nodejs so that it actually switches folders, maybe version 8.0.0 or so).

If that doesn't work:

## Postgresql

Postresql is another database you need to install (and manage) yourself on your raspberry pi, after that you can configure [here](https://github.com/askmike/gekko/blob/stable/web/routes/baseConfig.js#L54). Finally you need to configure Gekko to use postgresql [here](https://github.com/askmike/gekko/blob/stable/web/vue/UIconfig.js#L18).

**Comment by dinankou** [comment]
Hello,
I installed gekko on pi-zero-W a couple of weeks ago. Everything has been running fine ever since...
Have you tried upgrading node.js to 8.1.2 ? I installed that version on my pi.
https://nodejs.org/dist/v8.1.2/node-v8.1.2-linux-armv6l.tar.xz

**Comment by Yroethiel** [comment]
Hey dinankou,

Thanks for the response. Very interesting, because the pi-zero-W has the same chip as my original Pi (although more RAM).

Since I posted the issue, I have done the following, still with no luck:

- formatted my SD card, and reinstalled the latest version of Raspbian Jessie to get rid of any complex permission issues
- installed latest version of nodejs (8.1.2), which includes npm (5.0.3)
- git cloned gekko to get the latest version, and ran the npm install (--only=production)
- no errors during installation
- run "node gekko --ui" successfully, although only waited until the front page had loaded up in browser
- ported my custom strategy/config file into Pi's gekko (both work on a Windows install of gekko)
- run "node gekko --config config.js"
- received the "no sqlite3 installed" error again :(
- run "npm install sqlite3", it can't find a pre-compiled armv6 version (error 403), so decides to build from source
- voila, this time no permission errors
- however, I then can't successfully finish the build...the Pi just freezes (left it running for 24+ hours, and have tried with sqlite3 versions 3.1.8 and 3.1.4, and 3.1.3)

Wondering if it's a RAM limitation, because I'm essentially starting with a clean slate, and using all-new versions of everything.  I've had no luck finding a tarball/binary for sqlite3 for armv6, so now might have to go down askmike's helpful postgresql option above. Was really hoping to keep everything as close to default as possible...really scratching my head on this one!

**Comment by dinankou** [comment]
I thought sqlite3 was already included in Jessie...
have you tested wether sqlite was working ?
    sqlite3
    .save test.db
    .exit
have you tried installing sqlite using apt-get ?

**Comment by Yroethiel** [comment]
It wasn't preinstalled, no luck after installing apt-get either.

The issue (once I got past the permissions mix up) seems to be that the original Raspberry Pi just couldn't build sqlite3 from source. I upgraded to an RPi3B, and used the exact process above...all works fine now.

The original issue isn't fixed, but @askmike, you can probably consider this as closed. Thanks for your help!

**Comment by askmike** [comment]
@Yroethiel glad you found a solution (although with changing the hardware).

So to sum up: You are unable to compile sqlite3 on the Raspberry PI B ([this model](http://socialcompare.com/en/review/raspberry-pi-model-b))? Is that regardless of what OS is installed on the device? So similar to [this issue](https://github.com/mapbox/node-sqlite3/issues/664) (except for that fix)?

**Comment by koenvanderlinden** [comment]
On my RP2 I had same problems. Fixed it by installing the build essentials and restarted the npm install.

So run:
sudo apt-get install build-essential
npm install --only=production

it will then compile missing binaries for the Raspberry.

**Comment by Nickduino** [comment]
I have a B+ with the same issue.

> Very interesting, because the pi-zero-W has the same chip as my original Pi (**although more RAM**).
I wonder if that's not the problem, indeed. I tried to install it after having activated a 1 GB swap file with no luck.

**Comment by trexfun2** [comment]
I have a raspberry 3B+ and tried for the last7 days to install gekko. but i have the same pb with sqlite3. Did you find a solution? if not I may have to buy an old raspberry, which one do you advise for gekko?
