### ISSUE TITLE
Some noob questions

### ISSUE THREAD

**Issue by pittvailer** [askmike/gekko#795]
Can gekko monitor all crypto pairs at a given exchange or is it have to be 1 bot=1 pair?
If not. Is it possible to write a single bot that will monitor all the altcoins prices on the poloniex and then choose which one to buy based on some parameters? All the bots I see are usually for one predetermined pair only. thanks for the help

**Comment by askmike** [comment]
Gekko is meant for one market (1 pair), but using the UI you can start multiple Gekkos (one for each market pair). However you currently can not create strategies that do something with market data from more than a single market.

Though you can easily run a market watcher for each pair and end up with a database full of data, this way you can create your own little script that polls the database and look at all the markets you are interested in.

**Comment by pittvailer** [comment]
Thank you, I will look into that.
