### ISSUE TITLE
Serious problem about BTCC trader

### ISSUE THREAD

**Issue by 383131600** [askmike/gekko#797]
I  found a serious problem. When I fix the fee, the order price of the robot was different from the price actually released in BTCC, and I tried a variety of settings. The selling price must be less than the buying price.

buy=买入
sell=卖出
success deal=全部成交
cancel deal=已撤单
![image](https://user-images.githubusercontent.com/20080808/27475098-7ec56fe8-5836-11e7-9c05-31357baf1c56.png)

**Comment by askmike** [comment]
Apologies for these problems. When you say:

> the order price of the robot was different from the price actually released in BTCC, and I tried a variety of settings.

You mean that Gekko did an order at the wrong price? If so compared to what price?

Or maybe you only mean:

> The selling price must be less than the buying price.

The basic strategies that come with Gekko act as trend watching strategies. The only thing they do is look at the market and if they think it is an uptrend signal BUY (and if a downtrend signal SELL).

However if you want to be sure you only buy if the price is higher than last sell you can implement that in your own strategy, see #772 for an example. Feel free to ask more questions.
