### ISSUE TITLE
GUI import error: "Request has been terminated"

### ISSUE THREAD

**Issue by imkane** [askmike/gekko#798]
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.

![screenshot - 6_23_2017 9_12_39 am](https://user-images.githubusercontent.com/2041683/27490778-78447f48-57f4-11e7-9ebd-1d8e2a52b71b.png)

I'm running CentOS 7 with nginx reverse-proxy, Let's Encrypt SSL cert.

Any ideas?

**Comment by imkane** [comment]
Solved it, silly me!

https://gekko.wizb.it/docs/installation/installing_gekko_on_a_server.html#configuring-gekko-to-run-in-the-cloud

**Comment by askmike** [comment]
if the docs are not clear enough, feel free to let me know how to improve them!

**Comment by imkane** [comment]
Nah this was just a lack of proper reading on my part :) But at least now that this issue is logged if it happens to other folks they can search and find the solution.
