### ISSUE TITLE
ZEC Poloniex import

### ISSUE THREAD

**Issue by Rescue9** [askmike/gekko#803]
ZEC is listed in Poloniex's markets section of the exchanges.js file, but not in the currencies section. Thus when trying to import the ZEC data, it fails with an error.

**Comment by askmike** [comment]
Fixed on develop branch. This will be part of the next release (you can already try it out by downloading the develop version).

**Comment by Rescue9** [comment]
Yea… sorry about that. Been a while since I’ve coded so I completely forgot to check devel before submitting issue.

**Comment by askmike** [comment]
No problem, I am already happy you reported the issue. Because of this I could fix it myself in a minute :)

**Comment by tkh23** [comment]
Hi. Did you remove zec again? I pulled dev branch (I think, used this command: git clone git://github.com/askmike/gekko.git --branch develop) and there's no ZEC.....

**Comment by askmike** [comment]
It should be there (and for me it is), you can select:

- USDT/ZEC
- ETH/ZEC
- XMR/ZEC

Can you post a screenshot if you are not able to select these?
