### ISSUE TITLE
FYI - added a couple of new Indicators Fib and TWIGs

### ISSUE THREAD

**Issue by thegamecat** [askmike/gekko#804]
https://github.com/thegamecat/gekko-trading-stuff

You can find them here - just add the indicators to your Strategy / Indicators folder and then use them in your Strategies.

Obviously I'm interested in your feedback - these wont make you money on their own btw, but rather part of a wider strategy.

**Comment by askmike** [comment]
Awesome! I would love a PR (and if not: what is the license?), could alternatively list it here: https://gekko.wizb.it/docs/extending/other_software.html

**Comment by thegamecat** [comment]
I don't what PR is in this context, happy to discuss 👍

**Comment by askmike** [comment]
PR = pull request = proposal to add it to Gekko :)

**Comment by thegamecat** [comment]
Ah, no idea how. I'm a complete noob at github.

**Comment by askmike** [comment]
If you can clean up the indicators (TWIG has a bunch of console.log statements) and write some documentation I can add them myself (referencing you as the author). But for now I am closing!
