### ISSUE TITLE
Unable to obtain LTC price data for BTCC, whether Tradebot or Importing 

### ISSUE THREAD

**Issue by FreeAlexhere** [askmike/gekko#806]

**Comment by askmike** [comment]
Hello, I am trying to fix compatibility with Gekko and BTCC. However I am unable to find the page where I can create API keys. Where did you create those for BTCC?

**Comment by FreeAlexhere** [comment]
I am a bit poor in English, the following is translated by google translation.
btcc this exchange company, which has two main sites, respectively, btcchina.com bitbell Chinese platform, and btcc.com bit currency cc. Their api addresses are https://www.btcchina.com/apidocs/ and https://www.btcc.com/apidocs. Btcchina.com should be the earliest trading volume of the largest.

**Comment by askmike** [comment]
I am trying to login in either and create API keys, but the API keys page gives this error:

<img width="1057" alt="screen shot 2017-07-04 at 21 21 53" src="https://user-images.githubusercontent.com/969743/27842127-f43aaef2-60fe-11e7-86db-70a0c77c008d.png">

But if I go to the link everything is filled in and okay:

<img width="1110" alt="screen shot 2017-07-04 at 21 22 11" src="https://user-images.githubusercontent.com/969743/27842133-fe9e16cc-60fe-11e7-8a75-fb9fa3d4be9a.png">

---

I am not sure how I can debug btcc exchange if I cannot create API keys..

**Comment by FreeAlexhere** [comment]
(Access Key) : 6b736416-b581-48fe-a5a9-5fe44d5e7462

 (Secret Key) : 003e501f-f1f6-4c7c-ab1e-9e14001e73fd
There is no balance in the account, do not know whether there is an impact

**Comment by tuxitor** [comment]
@FreeAlexhere You should cancel/delete the exposed keys immediately. You don't want the public to see your secrets

**Comment by askmike** [comment]
@FreeAlexhere like @tuxitor said it is better to revoke rights to these keys (consider them compromised).

If you can provide me keys and a deposit address I can work on Gekko on BTCC (I cannot promise anything though). Can you please mail me at gekko@mvr.me?

**Comment by FreeAlexhere** [comment]
@tuxitor The apI no money, but still thank you for your reminder,

**Comment by FreeAlexhere** [comment]
@askmike I sent an e-mail to you, real-name authentication request to upload a photo of the identity card, also requires the bank certification, I can not complete the time. Unfortunately

**Comment by reppolice** [comment]
Gentlemen I am a bit confused, is BTCC working? If not I can share new credentials

**Comment by askmike** [comment]
Unfortunately BTCC is not enabled anymore..
