### ISSUE TITLE
How could I access and open my local data(poloniex_0.1.db) using console?

### ISSUE THREAD

**Issue by avatar-lavventura** [askmike/gekko#807]
For example I have pulled a data:
<img width="910" alt="screen shot 2017-06-28 at 20 28 12" src="https://user-images.githubusercontent.com/18537398/27651246-5826e19c-5c40-11e7-9aaa-2a2d61381d7f.png">

Using console could I have view the obtained dataset? Like I would like to access this raw-data not from the gekko's website but from my console. But I was not able to find this raw data on my gekko's directory. Where did it stored?

When I did `cat history/poloniex_0.1.db` it showed some random values.

Thank you for your valuable time and help/

**Comment by askmike** [comment]
By default Gekko stores data in a sqlite database, you can use a SQLite viewer like http://sqlitebrowser.org/ to have a look at the data. Note that all data is stored as OHCLV data on a 1 minute resolution.

**Comment by askmike** [comment]
I am not sure what you mean by "accessing from the console". But you can write a [gekko plugin](https://gekko.wizb.it/docs/commandline/plugins.html) that prints out candles as they are going through [the pipeline](https://gekko.wizb.it/docs/internals/architecture.html).
