### ISSUE TITLE
Module Error Running Script

### ISSUE THREAD

**Issue by JoshS0515** [askmike/gekko#808]
Can anyone lend support on this error? I am a first time user. 

module.js:471
    throw err;
    ^

Error: Cannot find module 'Z:\Downloads\gekko-stable\gekko-stable'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3

**Comment by askmike** [comment]
What is the command you tried to run?

**Comment by JoshS0515** [comment]
Z:\Downloads\gekko-stable>node gekko-stable --config config.js

I have a gekko stable folder in a gekko stable folder for what ever reason.

**Comment by askmike** [comment]
Even though the folder is called gekko-stable, the command you need to run is (within the inner directory gekko-stable):

    node gekko --config config.js

If you are here `Z:\Downloads\gekko-stable` you first need to change the directory into the inner gekko stable by running:

    cd gekko-stable

**Comment by JoshS0515** [comment]
that is what I ran. The part is just the path the folder is in? How is that any different than what I ran?

**Comment by askmike** [comment]
So the folder you need to be in when you run the command is `Z:\Downloads\gekko-stable\gekko-stable` (because as you say the folders are nested). However the command you run should never include the `-stable` part. You posted `node gekko-stable` while it should be `node gekko`.

**Comment by JoshS0515** [comment]
Oh. You just still had stable in your example. I will give that a go then. Thank you.

**Comment by JoshS0515** [comment]
Z:\Downloads\gekko-stable\gekko-stable>node gekko --config config.js

    ______   ________  __    __  __    __   ______
   /      \ /        |/  |  /  |/  |  /  | /      \
  /$$$$$$  |$$$$$$$$/ $$ | /$$/ $$ | /$$/ /$$$$$$  |
  $$ | _$$/ $$ |__    $$ |/$$/  $$ |/$$/  $$ |  $$ |
  $$ |/    |$$    |   $$  $$<   $$  $$<   $$ |  $$ |
  $$ |$$$$ |$$$$$/    $$$$$  \  $$$$$  \  $$ |  $$ |
  $$ \__$$ |$$ |_____ $$ |$$  \ $$ |$$  \ $$ \__$$ |
  $$    $$/ $$       |$$ | $$  |$$ | $$  |$$    $$/
   $$$$$$/  $$$$$$$$/ $$/   $$/ $$/   $$/  $$$$$$/

        Gekko v0.4.10
        I'm gonna make you rich, Bud Fox.



 ERROR: Cannot find the specified config file.

**Comment by JoshS0515** [comment]
Now it says the file isn't there when I can locate it just fine at that location.

**Comment by askmike** [comment]
Make sure the config file is inside the second nested gekko-stable folder.

**Comment by JoshS0515** [comment]
![capture](https://user-images.githubusercontent.com/16510577/27687636-90ae4ebe-5ca5-11e7-9730-538373cf3079.PNG)
