### ISSUE TITLE
If exchange balance changes, does trader need to be restarted?

### ISSUE THREAD

**Issue by imkane** [askmike/gekko#809]
If I were to, say transfer 1 BTC to Poloniex, do I need to restart the trader app so it picks up the new balance? Or does it even matter?

**Comment by shanehull** [comment]
From my experience it checks the amount before placing an order and uses all the funds.

**Comment by imkane** [comment]
Thanks @shanehull !

**Comment by askmike** [comment]
Exactly like @shanehull said: you don't need to. Your strategy will simply suggest SHORT or LONG regardless of your own balance. And once this happens Gekko rechecks your balance and try to order (if you don't have any balance it won't).

However note that the upcoming version (live trader in the UI) will calculate profit statistics and these will be wrong if you start moving money in and out of the account.
