### ISSUE TITLE
More informative notifcations

### ISSUE THREAD

**Issue by Ali1** [askmike/gekko#810]
Notifications would be more helpful if details about the trade were also sent such exactly how much ends up being traded.

This is possible if the trader module is running before the notifying modules such as mailer.

Is it? If so, is it worth exploring how the trader module could log the exact details of the trade to be retrieved a few moments later by the notifying modules?

**Comment by askmike** [comment]
Yes! Exactly this is being worked in in #737. How it works is that the "roundtrips" visible in the UI (right now for backtesting and paper trading only) will hold information regarding the execution price.

Note that this requires quite a few changes (per exchange as well as through the codebase).

**Comment by askmike** [comment]
I am closing this as it's functionality that is coming soon. But feel free to keep commenting.
