### ISSUE TITLE
[Question] Can I run Gekko as a service using nginx or anything?

### ISSUE THREAD

**Issue by prathanbomb** [askmike/gekko#811]
I just wanna put Gekko in some VM such as Digital Ocean and let it run as a service.

**Comment by askmike** [comment]
Not 100% what you mean with run gekko as a service. You can definitely run it in the cloud and it will be up 24/7 (which is what a lot of people do).

Most people use nginx as a revere proxy, this allows you to password protect access  to Gekko.

If you go to this page: https://gekko.wizb.it/docs/installation/installing_gekko_on_a_server.html

- under "Configuring Gekko to run in the cloud" you can find how to setup Gekko
- under "Configuring NGINX as a reverse proxy" you find a basic guide on how to put nginx in front of it.

If this does not answer your question, please comment and let me know what you mean!

**Comment by imkane** [comment]
I think by "service" he may mean in the background/daemon. So even if the server reboots or if you lose your SSH connection it'll still be running.

I use PM2 myself:  http://pm2.keymetrics.io/

**Comment by prathanbomb** [comment]
Thanks a lot @imkane .
