### ISSUE TITLE
Failed at the sqlite3@3.1.8 install script 'node-pre-gyp install --fallback-to-build'.

### ISSUE THREAD

**Issue by EslamAwwad** [askmike/gekko#812]
Hi akmike,
An error have been happened whenever I try to set up gekko.
It is shown at the final page in the attached pdf
[Error.pdf](https://github.com/askmike/gekko/files/1113700/Error.pdf)
The error is"Failed at the sqlite3@3.1.8 install script 'node-pre-gyp install --fallback-to-build'."
The error repeated on two different PCs, So I don't know is the problem in my following to the instillation steps or what.

Thanks

**Comment by askmike** [comment]
Very strange, judging by your logs it appears you are installing on a windows computer. Can you let me know the windows versions?

**Comment by netcoding** [comment]
This was my solution,
`npm install sqlite3 --unsafe-perm`

**Comment by EslamAwwad** [comment]
windows 10

**Comment by askmike** [comment]
@EslamAwwad can you try proposed fix by @netcoding? I don't have access to a windows machine right now.

**Comment by EslamAwwad** [comment]
I tried "npm install sqlite3@3.1.4" and it wors
thanks guys

**Comment by askmike** [comment]
great :)
