### ISSUE TITLE
Cannot use importer or use already gathered historical data

### ISSUE THREAD

**Issue by subhead** [askmike/gekko#813]
after a week of running multiple market watchers i hab to restart the docker containers. After the restart i cannot see any historical data in the ui. But the database files are all present on the filesystem. also i cannot start any new import or market watchers. When i try to start a importer, i recieve the following error:

![chrome_2017-06-30_14-48-17](https://user-images.githubusercontent.com/601434/27736850-30791216-5da6-11e7-8705-d5c930920b0a.png)

I tried to remove all databases and start fresh but the problem stillt exists. Any ideas what is going wrong here?

**Comment by askmike** [comment]
That error is most likely unrelated from any data that might or might not be stored in a database. When exactly in the UI does this error pop up?

**Comment by subhead** [comment]
when i click on the import button after filling out all the informations for the import process.

**Comment by askmike** [comment]
Are you able to go to local data and click on scan?
Also: can you post the output of "docker logs [name of gekko instance]"?

**Comment by subhead** [comment]
When i click on scan under local data my previous scanned data did not apper. 

Output of docker logs <gekkoinstance>:
` > gekko@0.4.10 start /usr/src/app
> node ./gekko --config config.js --ui


    ______   ________  __    __  __    __   ______
   /      \ /        |/  |  /  |/  |  /  | /      \
  /$$$$$$  |$$$$$$$$/ $$ | /$$/ $$ | /$$/ /$$$$$$  |
  $$ | _$$/ $$ |__    $$ |/$$/  $$ |/$$/  $$ |  $$ |
  $$ |/    |$$    |   $$  $$<   $$  $$<   $$ |  $$ |
  $$ |$$$$ |$$$$$/    $$$$$  \  $$$$$  \  $$ |  $$ |
  $$ \__$$ |$$ |_____ $$ |$$  \ $$ |$$  \ $$ \__$$ |
  $$    $$/ $$       |$$ | $$  |$$ | $$  |$$    $$/
   $$$$$$/  $$$$$$$$/ $$/   $$/ $$/   $$/  $$$$$$/

        Gekko v0.4.10
        I'm gonna make you rich, Bud Fox.


TAlib is enabled
Serving Gekko UI on http://localhost:3000/

npm info lifecycle gekko@0.4.10~poststart: gekko@0.4.10
npm info ok`

**Comment by askmike** [comment]
> When i click on scan under local data my previous scanned data did not apper.

but the error also did not appear? You only get the error while trying to import?

-----

These logs are after you've seen the error in your screen?

**Comment by subhead** [comment]
yes thats correct. the error only occurs when i try to run the importer.

**Comment by subhead** [comment]
Any news on this? As i said  the gekko version of gekko is unusable for me at the moment. Or do you need additional informations from me?

**Comment by askmike** [comment]
Hey, sorry for the late reply. I was unable to reproduce here, can you please (assuming you are using chrome):

- open dev tools (right click in UI, click on inspect)
- go to network tab
- click the button that gives the error
- there should be a red item in the list (under network tab)
- click that and post the screenshot

**Comment by subhead** [comment]
screenshot
https://lh3.googleusercontent.com/-ttOqmtpCayM/WVqw5fb_H9I/AAAAAAAAVgE/7MsBEyiqOKoP7XteXlpZMjHTo9dGbFVJQCHMYCw/s0/chrome_2017-07-03_23-02-26.png

**Comment by askmike** [comment]
Connection refused, that most likely means something went wrong in the terminal where you had the ` node gekko --ui` running. Is there anything in these logs (other than what you posted before)?

**Comment by netcoding** [comment]
Don't use SSH-Tunnel for gekko-UI.
This was my failure. You can change you api-address here("web/vue/UIconfig.js"),
`const CONFIG = {
    headless: false,
    api: {
        host: '192.168.1.2',
        port: 3000,
    },
    ui: {
        ssl: false,
        host: '192.168.1.2',
        port: 3000,
        path: '/'
    },
    adapter: 'sqlite'
}`

**Comment by GigabitGuy** [comment]
I'm having the exact same issue on a new install om Ubuntu server. 
@netcoding I'm not sure what you mean? Is it a problem to SSH into the server and start gekko? and how does that relate to changing the api address? Does this mean I can't run gekko headless?

**Comment by GigabitGuy** [comment]
Sorry, I figured it out - had only changed the api-address and not the ui-adresse, both should be changed if others experience this.

**Comment by askmike** [comment]
I am assuming this is fixed, if it is not. Please comment :)
