### ISSUE TITLE
General questions on gekko method

### ISSUE THREAD

**Issue by EslamAwwad** [askmike/gekko#814]
Hi,

I have different general questions:
01- Gekko ran for 3 hours without any trade, I know that this might be a short period but I need to check if it is working. So how I can change its sensitivity to work on a shorter periods?
02- Adding customized strategies is hard, for me at least, but I think it will be better for any user to double check with 2 or 3 strategies using some of the famous indicators. So, if it possible, you can add another two indicators and if anyone needs more then he should do it.
03- There is no stop button for the live trading. What if I want it to stop for a while? or what if I running two live trading processes and want to stop only one of them? Or what if I want it to only watch the market in a certain time then to continue without the need for closing it and open a new process.
04- You really explained the way of installing it enough, but I think the way of the using the final program itself need more explanation. you can do a live run to show the procedures beside the backtest in the YouTube video.
05- I entered my key and secret in the config file, but if they could be entered in the Gekko ui it will be easier.
06- is there any way to continue importing the data from the exchanging sites if it stop? when I try to import the data, it stops at the beginning  (0.4%). Is this related to the net speed?
07- Can I defined the amount of coins that I want Gekko to trade with? Where?

that's enough for now :D 
I really appreciate your work. And I will ask if there is any thing I tried to figure out but can't.
Thank you

**Comment by askmike** [comment]
Hey Eslam,

> 01- Gekko ran for 3 hours without any trade, I know that this might be a short period but I need to check if it is working. So how I can change its sensitivity to work on a shorter periods?

Yes, you can use set the candle size very small (a few minutes or so) and use the `custom` strategy. This will randomly go short and/or long. Note that if you do this with real money you will most likely lose a lot of it.

> 02- Adding customized strategies is hard, for me at least, but I think it will be better for any user to double check with 2 or 3 strategies using some of the famous indicators. So, if it possible, you can add another two indicators and if anyone needs more then he should do it.

My current focus is live trading in the UI, after that I will work on this. I have a few ideas about this :)

> 03- There is no stop button for the live trading. What if I want it to stop for a while? or what if I running two live trading processes and want to stop only one of them? Or what if I want it to only watch the market in a certain time then to continue without the need for closing it and open a new process.

Yes this is a problem and will be fixed asap! See #761.

> 04- You really explained the way of installing it enough, but I think the way of the using the final program itself need more explanation. you can do a live run to show the procedures beside the backtest in the YouTube video.

Thanks! I will try to put some more time into this, maybe I'll make a few videos (but this will also wait until after the live trader in the UI). What I do want to make clear is that Gekko is and will be a technical tool. It can help you create/test/validate strategies that you will have to create yourself.

> 05- I entered my key and secret in the config file, but if they could be entered in the Gekko ui it will be easier.

Yes, the biggest thing I am working on now, you can track progress here: #737.

> 07- Can I defined the amount of coins that I want Gekko to trade with? Where?

This has been a big thing, at the moment it's not possible..

-------

Keep in mind that Gekko is just a hobby project for me, I work on it in my spare time but am not getting paid for it. So development does not always go very fast.

**Comment by EslamAwwad** [comment]
Thank you!

I read "the guidelines for contributing" after writing the issue and thought that you will not reply on a lot of different things, but you replied, thanks.

I think we will wait for the update, and meanwhile I can study the strategies and by some programming I can create my own complex strategy. And about that, can you open a side issue for all users to share their strategies and their results, if they want.

Do you have a Facebook account?

**Comment by askmike** [comment]
> And about that, can you open a side issue for all users to share their strategies and their results, if they want.

There is one here: #610.

**Comment by askmike** [comment]
If you run into anything designing your strat feel free to comment here or create a new issue :)
