### ISSUE TITLE
Cannot delete Imported data

### ISSUE THREAD

**Issue by ludolfking** [askmike/gekko#815]
My geeko start importing data of 3 months, and stops on 2 days of data.
The importer says there is a proccess runing, and when I go inside it says its competed, but the data collected is only for 2 days

**Comment by askmike** [comment]
On what exchange are you trying to import?

**Comment by ludolfking** [comment]
Poloniex, default usdt/usd

**Comment by ludolfking** [comment]
Im runing on a Docker inside a raspberry
using images custom for raspi: rpi-node, rpi-redis, rpi-postgresql

When I was using it outside docker it fas ferching the data
uing it inside the docker has that problem

And changing from sqllite to posgresql it show me a problem, that I cannot store on 'importer'

**Comment by JohannesFerner** [comment]
@askmike i tried it with: 
kraken USD/ETH, now i have this entry in local data -> scan available datasets: 

![gekko](https://user-images.githubusercontent.com/1781395/28379627-a958d4b0-6cb4-11e7-8e16-9ece6ddb83dd.png)
Would be nice to be able to delete the data if it was not possible to import.

**Comment by askmike** [comment]
Yes: as part of #737 I made the exchange select box limited to the context:
if you select a live trader you can only pick an exchange where gekko can
actually live trade on. I will extend that to also include the exchange
selection for the importer.

**Comment by greenbigfrog** [comment]
I think this has been fixed or the like @askmike

**Comment by askmike** [comment]
-
