### ISSUE TITLE
Dont Import imported data

### ISSUE THREAD

**Issue by ludolfking** [askmike/gekko#816]
when you are importing data, and try to reimport on other timeframe, it download again the same candles, and slows the process.

what if you just store the importing process, telling what range has been downloaded
then merge the imports if their time range collapses

_like so:_
**ImportProcess** `{ from: 1, to: 20, pair: 'btc/ltc', collectedFrom: 1, collectedTo: 15 }`

**if there is proccess on the same pair:**

Dont colapse:
**ImportProcess** `{ from: 1, to: 10, pair: 'btc/ltc', collectedFrom: 1, collectedTo: 8 }`
**ImportProcess** `{ from: 10, to: 20, pair: 'btc/ltc', collectedFrom: 1, collectedTo: 15 }`

Colapse:
**ImportProcess** `{ from: 1, to: 10, pair: 'btc/ltc', collectedFrom: 1, collectedTo: 10 }`
**ImportProcess** `{ from: 10, to: 20, pair: 'btc/ltc', collectedFrom: 10, collectedTo: 15 }`
to:
**Imported** `{ from: 1, to: 20, pair: 'btc/ltc', collectedFrom: 1, collectedTo: 15 }`

You can use Redis for the ImportProcess, so it is data that is fast to edit, and is data to erase
For the **Imported** object, it can be stored on DB

PD:_Love to see the project with Promises_

**Comment by askmike** [comment]
Hey,

Thanks for the feedback.

> what if you just store the importing process, telling what range has been downloaded
then merge the imports if their time range collapses

Gekko already has functionality that queries the database and figure out exactly what dateranges of historical data exist in a given market (see [here](https://github.com/askmike/gekko/blob/develop/core/tools/dateRangeScanner.js)), this is [also wrapped in child process](https://github.com/askmike/gekko/tree/develop/core/workers/dateRangeScan) for even easier consumption.

Though the difficult part is that before an import Gekko sets up a pipeline that roughly looks like this:

    [fetch trade data] > [filter out dup trades] > [transform into candles] >[ insert into database ]

Each part in this pipeline is a streamlike object that takes incoming data and spits out transformed data, assuming that all data comes in chronologically.

For example: If the user requests an import from `2017-01-01` until `2017-06-01` but Gekko already has data for the month of february, the importer should only fetch data until the end of January, skip February and continu with March. But the candle transformer would assume no trades happened during march and calculate empty candles, potentially miscalculating candles edged to these periods. To do this properly we would have to set up a pipeline for each "daterange" we need to fetch data for.

I am very open to PRs for this! I won't have time for this anytime soon.

**Comment by ludolfking** [comment]
I really would like to PR... but don't have time right now to do it,
I have ideas to contribute to the code, but my job absorbs all my time

**Comment by askmike** [comment]
>  but my job absorbs all my time

I have the same problem unfortunately.

---

I don't see this as a high priority since there is no harm in importing the same data twice and people can specify exactly what dates to want to download data from. Apart from that the solution is quite complex, as it's a lot harder than simply starting a single pipeline (multiple need to be created, managed, etc). But if anyone feels this is needed, feel free to pick it up and open a PR :)
