### ISSUE TITLE
Backtest conducts multiple buys without sell in between

### ISSUE THREAD

**Issue by jebbgrenham** [askmike/gekko#817]
When backtesting, the bot will imply that it would have made multiple buys without selling. As the trader plugin uses 100% of your available balance; this is impossible - therefore the backtest will never be accurate. Or am I missing something?

**Comment by askmike** [comment]
Very good point, this is a bug that has been plaguing us for a while. Fixed it now :)

**Comment by thegamecat** [comment]
If you are writing your own strategy you can control this yourself anyway.

**Comment by southerton81** [comment]
What if the previous buy or sell advice was unsuccessful? Shouldn't we keep giving the same advice if strategy still considers it valid?

**Comment by askmike** [comment]
What do you mean unsuccessful? If Your strat signals to buy Gekko will try to buy (and on error retry) until it actually bought.
