### ISSUE TITLE
DEMA Buying high, Selling low

### ISSUE THREAD

**Issue by jakemenner** [askmike/gekko#818]
Alright, so I'm still playing around with Gekko and trying to understand how it works, but I'm not too sure what I'm doing wrong here.

I'm trying to backtest a DEMA configuration on GDAX historical data but it appears to produce unexpected results.
Not too sure if I'm misunderstanding the configuration fields.

I've plotted EMAs on a particular bitcoin online chart. The crossover points makes sense here.
(Look especially at the 5th May period)

![image](https://user-images.githubusercontent.com/29828873/27767161-eab9236c-5f1f-11e7-804e-095d1d901702.png)

I tried backtesting the same thing on Gekko using the same time periods and EMA periods. However, the results does not make much sense here. It's mostly buying high, selling low.

![image](https://user-images.githubusercontent.com/29828873/27767235-ade2a30c-5f22-11e7-9318-c3c72ed8e698.png)

Doesn't seem right there. Am I missing something?

EDIT: My bad! Think I looked at the chart wrongly. I think the points are correct.

**Comment by askmike** [comment]
> EDIT: My bad! Think I looked at the chart wrongly. I think the points are correct.

Great!

> It's mostly buying high, selling low.

Just to clarify: The strategy you use will 100% determine buy and sell signals in Gekko, if your DEMA strategy signals to buy at the bottom and sell at the top there is nothing Gekko will do about it.

If you have any other questions, feel free to ask here :)
