### ISSUE TITLE
Question about Exchanger

### ISSUE THREAD

**Issue by FSchneid2001** [askmike/gekko#822]
Hi, nice progrm good job.
I use Bittrex and i want to ask if you can take Bittrex in your code to use it with API ?

next question: how can i delete imported data?
and can you put some stopbutton in your script? i start some live fews and backtest and can`t stop them.

thanks

**Comment by askmike** [comment]
> I use Bittrex and i want to ask if you can take Bittrex in your code to use it with API ?`

It is not added yet, on the todo (#478 as well as my own todo). But if you can do javascript you can add it as well: https://gekko.wizb.it/docs/extending/add_an_exchange.html (if you want to do that please open another issue as the exchange spec is changing in the next version of gekko)

> next question: how can i delete imported data?

Also on the todo, in #786 you can read about how to delete manually.

> and can you put some stopbutton in your script? 

Yes, also on the todo (see #761).

-----

You touched upon a few pain points that a lot of people have commented on, but I will all fix them as soon as possible! If you have more questions feel free to ask :)

**Comment by FSchneid2001** [comment]
yes first i am sorry i don`t now about java. i must learn it ;-), it`s very hard for me. i understand it because i now a little bit from c++ and php, html, but forgott a lot of them.
now i have an nother problem.

Error: Request has been terminated
Posible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the Page is being unloaded etc.

i don`t understand this. i don`t now this node.js

did you have an idea? and so i have seen your are from nederland, so can you talk german?

greeting

**Comment by askmike** [comment]
The error you have souds similar to this one: #823. Can post the output the terminal or commandline where gekko was running? (copy the text or make a screenshot).

Unfortunately I don't speak german.
