### ISSUE TITLE
Unknown Strat runner - Gekko doesn't know what strat runner this is...

### ISSUE THREAD

**Issue by joetech** [askmike/gekko#823]
**Action Taken:**
Start a new live Gekko

**Expected Result:**
A new live Gekko would start

**Actual Result:**
"Gekko doesn't know what strat runner this is..."

**Setup:**
Installed in Ubuntu (not in Docker)
Poloniex
USDT
BTC
Paper Trader (this all works for just Market Watch)
MACD
1 Hour
10 Hour history
Paper Trader:
`fee = 0.25
slippage = 0.05
riskFreeReturn = 2

[simulationBalance]
asset = 1
currency = 100`

**Output looks normal:**
'Gekko 357214610036416 started
  --> POST /api/startGekko 200 3ms 542b'

**Comment by askmike** [comment]
Can you post output logs of the terminal (where `node gekko --ui` is running)?

EDIT: just saw your last sentence, very strange. I will try to reproduce here..

**Comment by joetech** [comment]
**_EDIT: I stopped gekko and restarted it and then started a new paper trader gekko with no error or warning.  I'll have to wait until tonight/tomorrow for the results._**

@askmike That's in the report above.  If it helps, here's a little more info:

Gekko version: v0.4.10
Nodejs version: v8.1.3

I haven't found any other logs, but here's the console output from some of before, up to, and including the problem.

'Gekko 21581260773857 started
  --> POST /api/startGekko 200 3ms 541b
  <-- GET /api/configPart/candleWriter
  --> GET /api/configPart/candleWriter 200 0ms 47b
  <-- GET /api/strategies
  <-- GET /api/configPart/paperTrader
  --> GET /api/configPart/paperTrader 200 1ms 108b
  --> GET /api/strategies 200 11ms 1.49kb
  <-- POST /api/startGekko
Gekko 667836587879864 started
  --> POST /api/startGekko 200 3ms 542b
  <-- GET /api/configPart/candleWriter
  --> GET /api/configPart/candleWriter 200 0ms 47b
  <-- GET /api/strategies
  <-- GET /api/configPart/paperTrader
  --> GET /api/configPart/paperTrader 200 1ms 108b
  --> GET /api/strategies 200 2ms 1.49kb
  <-- POST /api/startGekko
Gekko 3995914540126853 started
  --> POST /api/startGekko 200 6ms 517b
  <-- GET /api/configPart/candleWriter
  --> GET /api/configPart/candleWriter 200 0ms 47b
  <-- GET /api/strategies
  <-- GET /api/configPart/paperTrader
  --> GET /api/configPart/paperTrader 200 0ms 108b
  --> GET /api/strategies 200 3ms 1.49kb
  <-- POST /api/startGekko
Gekko 357214610036416 started
  --> POST /api/startGekko 200 3ms 542b'

On a side note, the initial install complained when I tried to run it and I had to manually install a couple more node modules.  Once we figure this out, I'll go back and do it all again and submit a PR if one is needed.

**Comment by askmike** [comment]
> I stopped gekko and restarted it and then started a new paper trader gekko with no error or warning.

Strange, so the message "Gekko doesn't know what strat runner this is..." should only happen after it crashes, in which case there should be some logs about why it crashed. Let me know how it goes!

> On a side note, the initial install complained when I tried to run it and I had to manually install a couple more node modules. Once we figure this out, I'll go back and do it all again and submit a PR if one is needed.

Great, thanks! Are you running the stable branch or the dev branch?

**Comment by joetech** [comment]
Stable.  I'll let you know if anything else happens with it.

**Comment by askmike** [comment]
👍  for now I'll assume this was a one off issue, so I'll close this. But feel free to reopen once it happens again.

**Comment by xtrinch** [comment]
Same issue here, with both docker and native installs on windows 10.

`Gekko doesn't know what gekko this is...`, or sometimes it just shows the loading bar and nothing happens. Crashes if I refresh the page. Requests look as the original poster's: - ` --> POST /api/startGekko 200 14ms 1.23kb`

Tried with both stable and latest version. Cannot get it to start paper trading at all. Backtesting works.

Using node 10.0.0 locally and whatever docker compose installs in containers.

**Comment by askmike** [comment]
I think this has something to do with the websocket connection.

@xtrinch are you using firefox or chrome?

**Comment by xtrinch** [comment]
Tried both, same result. Also the importer sometimes imports a few days, but never shows a progress bar and always requires a page refresh to see any results.

Update: I checked, and there really is no data flowing through the websocket stream.

**Comment by askmike** [comment]
Are you running gekko on your own system? Is there any webserver between
gekko and the browser (such as nginx, Apache)

**Comment by mariodantas** [comment]
Same issue here (Gekko doesn't know what gekko this is...) and same behaviour as @xtrinch , I have a VPS with Gekko (port 3000) and Apache for my virtualhosts (Apache has nothing to do with gekko)

**Comment by askmike** [comment]
Well if Apache is upstreaming the connection between gekko and your browser
you have to make sure it also upstreams the websocket connection!

**Comment by mariodantas** [comment]
When I stop Apache server the Gekko behaviour is exactly the same

**Comment by xtrinch** [comment]
I'm running gekko on my own system and as I mentioned, I also tried with docker but the result was the same. There is no webserver between gekko and the browser.

**Comment by askmike** [comment]
As long as your browser does not connect to Apache (to load the gekko UI)
there should indeed be no difference.

All: I will create a test branch with a ton of websocket debugging asap.

**Comment by xtrinch** [comment]
@askmike Tracked the error down to https://github.com/askmike/gekko/blob/bc745a2afcebe39695ed9496b7f445d0df6ca4ec/web/server.js#L28

If I replace this with `wss.clients.forEach(function(client) {...` everything starts working as expected.

Something to do with lodash then perhaps?

**Comment by k3nnet** [comment]
I had the same issue as @xtrinch  for the past few days . I impemented @xtrinch solution to replace _.each with  wss.clients.forEach(function(client)  an hour ago and it worked.

**Comment by askmike** [comment]
Woa nice find! Anyone mind opening a PR? Else I'll do it when behind laptop.

**Comment by k3nnet** [comment]
@askmike got it ! gladly.
