### ISSUE TITLE
add bowhead

### ISSUE THREAD

**Issue by ghost** [askmike/gekko#824]
bowhead is a trading bot that already has a built in strategy that works

https://github.com/joeldg/bowhead

what if we added it to gekko? Combined with Gekko's web UI it would be fast and easy to use

**Comment by askmike** [comment]
I've had a conversation with the creator of bowhead on reddit: https://www.reddit.com/r/Bitcoin/comments/6kdd6j/lets_write_a_cryptocurrency_bot_part_2_medium/djlgx3g/

The TLDR is: Gekko is a tool to do something different, the author of bowhead has used Gekko in the past, but went out to create something different.

Also bowhead is built on a completely different code stack, no idea where to start integrating this.

That said: Gekko exposes a rest API that can be consumed by other projects, but it is up to other people to use implement that API and build their own stuff on top  (example: #767).

**Comment by thegamecat** [comment]
@ak9250 Question - what was the envisaged outcome from an integration?
