### ISSUE TITLE
Limiting investment amount

### ISSUE THREAD

**Issue by decoye** [askmike/gekko#826]
Hey there im wondering if it is possible to tell gekko that only a part of the total amount available on the account is available for trading?

**Comment by tomav** [comment]
Same question here

**Comment by rlbewick** [comment]
That would be a good option but at the same time be able to set the amount for each trade as either a percentage or actual value.

**Comment by thegamecat** [comment]
That's very easy, you just update the trading plugin to use a %

**Comment by rlbewick** [comment]
That's fantastic!  Adding it to the UI would be even better.

**Comment by rlbewick** [comment]
thegamecat said... That's very easy, you just update the trading plugin to use a %.

How exactly do you do that, I know very little about Javascript.  Seems to me PHP would be a better avenue to follow...  I guess because it's so simple.

**Comment by askmike** [comment]
Having the trader limit the size per trade is easy, but this would break all profit reporting, risk calculation and still would not guard you in some market situations (your strategy can still "lose" more money than your limit). I will add this properly at some point, for now you are recommended to not have more funds on the account than you want Gekko to trade with.

**Comment by wahnker** [comment]
Just leaving a note to say that I would love to see this feature added.  Part of what I would like to do is run multiple bots simultaneously.  So I could split my balance into say 4 equal parts and run 4 bots to see which is more profitable in a live situation.  It would be nice to just define the starting balance in the `init` function.
