### ISSUE TITLE
Getting TAlib is disabled when running Gekko in Bash Windows 10

### ISSUE THREAD

**Issue by uxdxdev** [askmike/gekko#828]
```
damorton@desktop:/mnt/c/projects/gekko/web$ node server
TAlib is disabled
Serving Gekko UI on http://localhost:3000/
```

**Comment by uxdxdev** [comment]
Seems to work without the error when running Gekko on the command line from the root directory in live trading mode. 

damorton@desktop:/mnt/c/projects/gekko$ node gekko --config live-trading-config.js

**Comment by thegamecat** [comment]
Ensure talib is enabled in the config. 

I'm running talib strats in windows / bash in both UI and command prompt without issues. 

Has been fine in both v 14 and v16 bash.

**Comment by jnorthrup** [comment]
i have had trouble locating documentation as to where each configuration feature is documented.  the comments.  talib and tulip appear to be disabled in windows 10 bash by default.  how to verify this feature enabled?  where are sample configs?

**Comment by lkru** [comment]
did you find a way to solve this?

**Comment by jnorthrup** [comment]
> did you find a way to solve this?

no documentation located to date
