### ISSUE TITLE
Multiple Strategies

### ISSUE THREAD

**Issue by uxdxdev** [askmike/gekko#829]
How can I have multiple strategies working together during live trading? for example MACD and RSI producing buy/sell signals.

**Comment by askmike** [comment]
Gekko has the concept of strategies and indicators. If you want to signal buy/sell signals based on result of MACD and RSI you should create **one strategy** that implements **these two indicators**. This way you have full control over what you want to happen if your MACD is bullish but your RSI is bearish.

Here is documentation on how to create your own strategy: https://gekko.wizb.it/docs/strategies/creating_a_strategy.html

Also take a look here at the same question and my example strategy: #674.

**Comment by uxdxdev** [comment]
Thanks @askmike is there a slack channel or something so I dont have create issues for questions like these?

**Comment by askmike** [comment]
Not at the moment no, there was an IRC channel in the past and someone created https://www.reddit.com/r/GEKKO/ when I started working on Gekko.

I can only really work in my spare time on Gekko so I'm not sure how much support I can give..

**Comment by thegamecat** [comment]
The problem with this is how much people want to share.

But to answer your question damorton look into the documentation for writing your own strategies because it's very easy to do.
