### ISSUE TITLE
Adding a new coin to the database ?

### ISSUE THREAD

**Issue by gabev** [askmike/gekko#830]
Hello there ,
I was wondering how can we add a new currency for Kraken ? I was trying to import EOS/USD data  but after I selected kraken as exchange I could.t see EOS.  Is that even possible ?

**Comment by askmike** [comment]
Gekko has a list of assets and markets per exchange that it supports trading on, you would need to add EOS to the following lines:

- https://github.com/askmike/gekko/blob/develop/exchanges/kraken.js#L267
- https://github.com/askmike/gekko/blob/develop/exchanges/kraken.js#L268
- https://github.com/askmike/gekko/blob/develop/exchanges/kraken.js#L16

You are more than free to open a pull request for it :)
