### ISSUE TITLE
START LIVE TRADING - HOW?

### ISSUE THREAD

**Issue by focamonca** [askmike/gekko#834]
I'm quite new on GEKKO
I'm stuck since yesterday on how to start the real trade.. 
I read on the MAIN FEATURES: 

_**## Automated trading (trade bot)**
Paper trading (for TA strategies)
Backtester (for TA strategies)
Tool for systematic trading
Low level market library
Monitor the live market
Import historical market data
Broadcast market data over pubsub messaging systems
Web interface as well as a commandline interface_

But by now I'm not able to insert my data or start it properly..
Can someone help me?

**Comment by Herklos** [comment]
I am also new on gekko but it is well explained [on gekko website](https://gekko.wizb.it/docs/commandline/tradebot.html).

For the moment, you can only trade by command line.

First to simulate real trading :
- Create a copy of sample-config.js and edit it (choose your strategy, other settings...)
- **Keep the `config.trader` to false** (test your configuration before)
- `node gekko --config your_config.js`

With this command gekko will show you a simulation of real trading.

If your strategy is well configured and you have enough data you can start real trading by enable `config.trader`.

**Comment by focamonca** [comment]
thanks, i'll keep you up to date!
THANKS

**Comment by askmike** [comment]
I am very close to pushing a new update that allows trading via the interface. See #737.

**Comment by focamonca** [comment]
why did U close it? 
I want to learn trading via command line

**Comment by askmike** [comment]
Because it's not a bug or issue with Gekko. If you have any questions on how to set it up after reading what @Herklos posted, feel free to reply here :)

**Comment by kza95** [comment]
let's say I got the ui running with tradebot(which is dumb I know since it's not completely implemeneted..but I just wanted to test it a bit)....would it be enabled to make trades already if I start it or is there some restrictions preventing it until it's moved to the stable branch. @askmike

**Comment by focamonca** [comment]
Man, when will u relase the online tool?

**Comment by focamonca** [comment]
well.. the  UI implementation of live trading?

**Comment by Multty** [comment]
Kudos for the great job over the years. Your relentless effort on the Gekko project inspires me in so many ways. Can't wait to see the implementation of live trading on UI. Thumb up for you boss and more grease to your elbow @askmike
