### ISSUE TITLE
Cannot import data

### ISSUE THREAD

**Issue by afski** [askmike/gekko#835]
![errorgekko](https://user-images.githubusercontent.com/29988393/27995849-84a46544-64a3-11e7-9781-c0afe0974c54.png)

Mike,

This is the error that I receive when trying to import data when using the UI in a web browser. It is just the basic default import from poloniex for USDT/BTC. I am running gekko from my rpi2B and using Chrome from my other pc to access the UI. I have set everything up according to the installation guide as well as the running on a server guide. Now following your Youtube video on how to use the UI.  Everything has worked as it was supposed to, except now I am stopped at this part in the guide. 

Error from putty: 

Error: Cannot find module '/home/pi/gekko/core/../plugins/undefined/writer'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at load (/home/pi/gekko/core/pluginUtil.js:90:25)
    at /home/pi/gekko/node_modules/async/dist/async.js:1156:9
    at replenish (/home/pi/gekko/node_modules/async/dist/async.js:1030:17)
    at /home/pi/gekko/node_modules/async/dist/async.js:1034:9
    at _asyncMap (/home/pi/gekko/node_modules/async/dist/async.js:1154:5)
    at /home/pi/gekko/node_modules/async/dist/async.js:1240:16
RECEIVED ERROR IN IMPORT 56854461652958
Child process has died.

**Comment by askmike** [comment]
Did you change any of the config files? Specifically this line: https://github.com/askmike/gekko/blob/stable/web/vue/UIconfig.js#L18

**Comment by afski** [comment]
That is exactly what I was missing just wanted to say, that was removed because I copy and pasted this from the "Installing Gekko on a Server" page and just edited the local address, but it clearly leaves out the adapter line and comma above it :
 
const CONFIG = {
    headless: true,
    api: {
        host: '0.0.0.0',
        port: 3000,
    },
    ui: {
        ssl: false,
        host: 'x.x.x.x', // Set this to the IP of the machine that will run Gekko
        port: 3000,
        path: '/'
    }
}

**Comment by askmike** [comment]
Ah yes, the documentation was written before that got added to the config.
I will update the documentation!
