### ISSUE TITLE
Define backtest period

### ISSUE THREAD

**Issue by AntiLopa** [askmike/gekko#836]
Hi,

I've data set which is 2 years old, I wish to run the test on shorter period (to test my strategy against down trades).
I tried to download the same trade on shorter period but the 2 year period "sucked" it and I can't define a period to run on.

Thanks.

**Comment by askmike** [comment]
Are you using the UI?

In that case you can define your range here:

<img width="903" alt="screen shot 2017-07-09 at 20 52 02" src="https://user-images.githubusercontent.com/969743/27997085-8e600abc-64e8-11e7-86d0-8f824f0a7f7b.png">

and:

<img width="977" alt="screen shot 2017-07-09 at 20 52 16" src="https://user-images.githubusercontent.com/969743/27997087-92bd167c-64e8-11e7-8ca9-16fb3e6e982b.png">
