### ISSUE TITLE
Use backtests in some markets and use defined strategy in others

### ISSUE THREAD

**Issue by galindro** [askmike/gekko#838]
Is it safe to run backtests in one market (for example poloniex) and use the defined strategy in other market like cex.io? I'm asking this because cex.io isn't supported for importing according to docs: https://gekko.wizb.it/docs/introduction/supported_exchanges.html and I'm using it as exchange.

**Comment by askmike** [comment]
Note that if you run a market watcher (or paper trader) Gekko will store all live market data as Gekko sees it, this way you can backtest over this data later.

----

I can't give a blanket answer, as each market will have different [market microstructures](https://en.wikipedia.org/wiki/Market_microstructure) (different traders, different market markers, etc), but what I can say is that accuracy will go up by raising the candleSize (to at least a few hours imo).
