### ISSUE TITLE
IMPORT ERROR

### ISSUE THREAD

**Issue by focamonca** [askmike/gekko#846]
I'm getting this error continuosly:

> IMPORT ERROR: 
>  ERROR: The exchange Kraken does not provide full history (or Gekko doesn't support importing it)

Any solution?

ANd it's not only for Kraken, but every other Exchange

**Comment by askmike** [comment]
no solution, importing is only supported at some exchanges unfortunately. See this table (look under importing): https://gekko.wizb.it/docs/introduction/supported_exchanges.html

An integration could technically be made between kraken and gekko to support this, but I am to busy for that at this time (will do at some point in the future).
