### ISSUE TITLE
sample-config.js

### ISSUE THREAD

**Issue by raffus** [askmike/gekko#847]
Hi guys,

I'm new to gekko and  have just installed it few days ago.

I found out there's a sample-config.js file at the root folder.
I can't see any changes on the interface after changing this file.

I've tried to rename it to config.js and had no success. Same thing when copying the file into the config folder.

Any tip?

Thanks

**Comment by askmike** [comment]
Yes: you don't need / cannot use this file when using the UI.

Is there anything you want to change but cannot do in the UI?

**Comment by raffus** [comment]
Yes. I'm trying to change some default values and add new strategies. To do that, I was adding some configuration into the config.js file but could not see updates in action.

I do have another question. To use the gekko robot, should I use the UI or just the console commands?

Thanks a lot @askmike.

**Comment by askmike** [comment]
> I do have another question. To use the gekko robot, should I use the UI or just the console commands?

In the future you can do everything through the UI. But not all features are supported yet (like live trading, see #737).

**Comment by GO1984** [comment]
> Yes. I'm trying to change some default values and add new strategies. 
I'm new to gekko using the UI and i have the same problem. How to add new strategies to the new UI?
Do i have to use the custom.js? If so, how to add multiple new/own strategies?
