### ISSUE TITLE
Question regarding pair trading

### ISSUE THREAD

**Issue by JoshS0515** [askmike/gekko#848]
Hello, 

This is a general question but what happens if you are running the script twice? One on BTC/USDT and then another on ETH/USDT. Would the script know how to handle new funds hitting USDT from the other pairing? Would it just move between the three based on what ever trade happens first? Are there any steps you can take to make sure the script knows that X amount of USDT is assigned to BTC trading and another is assigned to ETH? 

Thanks

**Comment by askmike** [comment]
Hey,

> Would it just move between the three based on what ever trade happens first?

Yes, it would unfortunately.

> there any steps you can take to make sure the script knows that X amount of USDT is assigned to BTC trading and another is assigned to ETH?

Not at the moment, but there are a few issues open where people are thinking about solutions. See #826 for example.

-----

A solution to this is currently not available but is being investigated :) A temporary workaround is using different exchange accounts per gekko instance.
