### ISSUE TITLE
Backtest: different results each time

### ISSUE THREAD

**Issue by astronaute77** [askmike/gekko#850]
Hi,

I get completely different results from exactly same test (default values RSI for example) each time I run it.

Is this expected or am I doing something wrong?

[rsi_backtest.zip](https://github.com/askmike/gekko/files/1150511/rsi_backtest.zip)

Thank you

**Comment by raffus** [comment]
I do have the same behavior.
I'm not sure, but I believe the "robot" does different analysis each time, depending on the warming analysis, but again, this is just a guess.

BR,
R

**Comment by askmike** [comment]
> I get completely different results from exactly same test (default values RSI for example) each time I run it.
> I do have the same behavior.

This is very strange.. Can you tell me a bit more about your setup?

- where are you running gekko (desktop, server, rasppi)?
- what OS do you have?
- did you change any configuration (are you using the default database)?

------

> I'm not sure, but I believe the "robot" does different analysis each time, depending on the warming analysis, but again, this is just a guess.

No, it is supposed to be fully deterministic: if you run it twice with the same settings you should get the same result. Which for me is very much happening.

**Comment by astronaute77** [comment]
@askmike I'm on windows 10 and am running the gekko on node.

You can see my screenshots and initial post for all informations. If you need anything just ask.

**Comment by askmike** [comment]
Can you download the development branch and try again?

**Comment by astronaute77** [comment]
It seems to work with develop branch, thank you :)
I continue my exploration now !

**Comment by jeeyer** [comment]
Sorry to comment on a closed thread but I'm experiencing the same issue as @adnandoric. 

Every time I hit back test (with the same dataset and strategy) I get totally different results. 
@askmike With development branch do you mean node.js? v8.4.0? 

I'm running on OSX v10.11.2 El Capitan.

J.

**Comment by askmike** [comment]
@jeeyer could you email me the following:

- your strategy (if you did not use one that came with Gekko)
- a zip your history (found in the `history` folder inside Gekko)
- a screenshot of the backtest settings (strat params, etc)

Than I'll try to reproduce that locally. My email is *redacted*

**Comment by jeeyer** [comment]
@askmike I think I made a mistake selecting the strategy. Assuming it was an updated version of custom.js but still standard custom.js

Gekko wasn't displaying/updating the new strategies that I've put in the strategy folder for some reason. It does now and it also gives the same results over and over while backtesting!

**Comment by askmike** [comment]
Great stuff :)

**Comment by jeeyer** [comment]
Thanks for the quick follow-up!
