### ISSUE TITLE
Recompiling breaks the UI

### ISSUE THREAD

**Issue by Gab0** [askmike/gekko#852]
Trying to recompile the UI results in a blank webpage on localhost:3000. 

$git clone [repo]
$cd gekko
$npm install
(everything works at this point)
$cd web/vue
$npm install
$npm run build

Flawless build. But after starting the app, http://localhost:3000/#/home is now a blank webpage named 'Gekko'. Am I missing something?

**Comment by askmike** [comment]
Very strange, could you check the console of your browser for any errors?

**Comment by Gab0** [comment]
Pretty short console log..
`
Error in parsing value for ‘display’.  Declaration dropped.  furtive.min.css:1:453
Error in parsing value for ‘display’.  Declaration dropped.  furtive.min.css:1:5432
Error in parsing value for ‘word-wrap’.  Declaration dropped.  furtive.min.css:1:5736
Unknown property ‘appearance’.  Declaration dropped.  furtive.min.css:31:12
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector.  furtive.min.css:63:2
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector.  furtive.min.css:67:2
Unknown pseudo-class or pseudo-element ‘-o-prefocus’.  Ruleset ignored due to bad selector.  furtive.min.css:119:2
Error in parsing value for ‘background’.  Declaration dropped.  furtive.min.css:159:14
Error in parsing value for ‘background’.  Declaration dropped.  furtive.min.css:160:14
SyntaxError: An invalid or illegal string was specified  reconnecting-websocket.min.js:2
"You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html"  build.js:6:71580
`

**Comment by Gab0** [comment]
There is this error... last entry on the console:
```
SyntaxError: An invalid or illegal string was specified                    reconnecting-websocket.min.js:2
	a/this.open http://localhost:3000/assets/reconnecting-websocket.min.js:2:1076
	a http://localhost:3000/assets/reconnecting-websocket.min.js:2:2485
	l http://localhost:3000/dist/build.js:6:72494
	<anonymous> http://localhost:3000/dist/build.js:16:83487
	<anonymous> http://localhost:3000/dist/build.js:16:82832
	e http://localhost:3000/dist/build.js:1:96
	<anonymous> http://localhost:3000/dist/build.js:1:483
	<anonymous> http://localhost:3000/dist/build.js:1:2
```

**Comment by askmike** [comment]
Can you post your UIconfig.js located in: `gekko/web/vue/UIconfig.js`?

**Comment by Gab0** [comment]
Stock config... could it be a system language issue or something? xD

```
const CONFIG = {
    headless: false,
    api: {
        host: '127.0.0.1',
        port: 3000,
    },
    ui: {
        ssl: false,
        host: 'localhost',
        port: 3000,
        path: '/'
    },
    adapter: 'sqlite'
}

if(typeof window === 'undefined')
  module.exports = CONFIG;
else
  window.CONFIG = CONFIG;

```

**Comment by askmike** [comment]
It should not be..

Can you try downloading the `develop` branch and compiling that UI?

**Comment by Gab0** [comment]
During build got this error a couple of times;
`Unhandled rejection Error: Cannot find module 'jade'`

But everything works ^^
`develop` branch got the fix.

**Comment by askmike** [comment]
great :D

**Comment by askmike** [comment]
The develop branch now has a fix for the `Cannot find module 'jade'` problem.
