### ISSUE TITLE
Where is the log/debug file?

### ISSUE THREAD

**Issue by raffus** [askmike/gekko#854]
Hi guys,

I'm a begginer with Gekko and am trying to create a new strategy.

When I use
`log.debug('down trend');`

for example, I can't see this log in gekko console.

Also, I'm having a hard time looking for candle.variables. Any related documentation?

Thanks!

**Comment by askmike** [comment]
Ah yes: I have yet to update all documentation to assume the UI. If you replace `log.debug` with `console.log` you will at least see logs when using the UI. Alternatively you can run the backtest using the commandline and set `config.debug` to `true` in your config.

**Comment by raffus** [comment]
Hi @askmike, thanks for your help.
I'd be glad to help the project with the documentation.

Since I'm new here I do have lots of questions, which you're mostly helping me on. As a retribution, I'd like to help to improve the documentation, but I'd need people's help to get more detailed information about gekko.

Thanks again.

**Comment by askmike** [comment]
> but I'd need people's help to get more detailed information about gekko.

Feel free to open as many issues as you like. As soon as you feel comfortable enough to rewrite some of the documentation. You can go to the docs folder on the develop branch: https://github.com/askmike/gekko/tree/develop/docs

Pick a document and click edit (you cannot directly update - but this way you propose updated documentation in the form of a PR).
