### ISSUE TITLE
Plugins page not found

### ISSUE THREAD

**Issue by raffus** [askmike/gekko#856]
Hey guys,

I was trying to look for the Plugin's page and it seems to be down.

Please check out the link:
https://gekko.wizb.it/docs/commandline/Plugins.html

Hope you can make it work again.

In time, I wonder if is it possible to run the import command to grab more than one currency history at time. If so, how can we make it?

Cheers,

R

**Comment by askmike** [comment]
Needs to be a small p in the link, where did you see this link with a big P? That's where we need to fix it.

**Comment by raffus** [comment]
It was @ the documentation page. Seems to be fixed now. Weird. I'll let you know in case I find it again.

**Comment by raffus** [comment]
Oopz!
I've found it.

Go to:
https://gekko.wizb.it/docs/commandline/importing.html

Click at the the link within the text
"For importing you should [enable and configure](https://gekko.wizb.it/docs/commandline/Plugins.html) the following plugin:"

That needs to be fixed.

This is my first of many contribution. ;)

Thanks for all the help
