### ISSUE TITLE
[request] Enhance Backtest Results

### ISSUE THREAD

**Issue by JohannesFerner** [askmike/gekko#857]
Hi,

As seen in the screenshot below it would be nice to have the following KPIs included: 

- Buy&Hold (from Start) : XX.XX%
- Strategy outperformed by: XX.XX%
- Buy&Hold from 1st Signal: 
- Strategy outperformed by: XX.XX%

![fullscreen_19_07_2017__17_46](https://user-images.githubusercontent.com/1781395/28376510-91b7c5be-6caa-11e7-9045-18908a2b0530.png)

I may have time to submit a PR for this feature.

br. 
Johannes

**Comment by imkane** [comment]
Good suggestion!

**Comment by JohannesFerner** [comment]
@imkane thanks. 
I think especially in this Bull Market where Crypto is currently an outperforming factor eg. > 200-400% would be something a sophisticated strategy might perform.

In the current market situations some really bad strategies show up great gains in % which are in reality less than the HODL approach, but the market itself performs in such a bullish way that you would not recognize this at first sight. 

I did not work with vue.js so far but I'll have a look into this feature.

**Comment by JohannesFerner** [comment]
More KPIs in random order:
 
- Profit Loss Ratio
- Maximum Account Drawdown
- Maximum Weekly Drawdown
- Maximum Daily Drawdown
- Number of Trades per Day
- Win Rate% (UI= Barometer)
- loss Rate % (UI= Barometer)
- Win Average %
- Loss Average %
- % of profitable Months/Weeks/Days
- Average Holding Time

Here are some Screenshots from other tools:

![quantconnect-backtest_jpg__612x323_](https://user-images.githubusercontent.com/1781395/28378378-410539de-6cb0-11e7-89c1-b29f95ddfc75.png)

![johannesferner__johannesferner_stats_ _etoro](https://user-images.githubusercontent.com/1781395/28378391-4cab7c9e-6cb0-11e7-9510-678a1ca62503.png)

![johannesferner__johannesferner_stats_ _etoro](https://user-images.githubusercontent.com/1781395/28378439-730e2a4e-6cb0-11e7-9b35-3384f39df5d9.png)

![backtest_result_-_google-suche](https://user-images.githubusercontent.com/1781395/28378501-abdc670a-6cb0-11e7-804a-14e69d89c760.png)

**Comment by askmike** [comment]
Interesting, to come back on your initial metrics:

- The buy&hold is already present, it's called 'market' and it's listed on the left.
- How much the strat outpeformed the market used to be part of the output, it's called the "alpha". I am not sure what happened to it and why it is not present anymore. Do keep in mind that your strategy might definitely underperform the market, which doesn't make it bad if it was able to do this with considerably less risk.
- `Buy&Hold from 1st Signal:` this one is a bit random, what value does it add? The first signal depends 100% on when you start the backtest..

> I did not work with vue.js so far but I'll have a look into this feature.

Great if you want to work on a PR for this, note that all these metrics are not calculated in vue, but in the performanceAnalyzer plugin (in the upcoming release of gekko), this is the code you are interested in:

https://github.com/askmike/gekko/blob/feature/ui-trader/plugins/performanceAnalyzer/performanceAnalyzer.js#L131

**Comment by askmike** [comment]
Another great example: https://github.com/quantopian/pyfolio
