### ISSUE TITLE
[request] Backup & Import Local Data

### ISSUE THREAD

**Issue by JohannesFerner** [askmike/gekko#858]
Hi,

if i was going to setup multiple gekko instances or transfer one instance to another server ... 
i would have to distribute the backtesting data manually from one instance to another.

It would be more comfortable to have an import&export of the OHCL Data in whatever format suits best.

If one would also crawl a big amount of data from the exchanges and share this initial data we would take away some load of the exchanges API and could more easily test a strategy across different symbols. One of the contributors could also create and maintain an initial Dataset (hosted eg. on Dropbox). 

br. 
Johannes

**Comment by askmike** [comment]
Great idea, has been discussed a number of times before but still valid nonetheless. Because Gekko only needs 1min OHCL data sharing huge amounts of market data is very trivial.

I will probably at some point offer this data through my own platform [wizbit](https://wizb.it).

**Comment by askmike** [comment]
But that will unfortunately take a while, I only work on Gekko whenever I have some free time, and as soon as I start hosting stuff I might be required to spend more time than I have (what if the hosting goes down, becomes to expensive, etc). I am against using third party services like dropbox for privacy reasons.

I am closing this right now. But I am still open to discuss it :)
