### ISSUE TITLE
[request] Save Backtests

### ISSUE THREAD

**Issue by JohannesFerner** [askmike/gekko#859]
Hi,

Another useful feature from my point of view would be saving the Backtests to a local backtest journal.

This would enable one to enhance either the strategy itself or the parameters passed to the strategy. 

Things i would save: 
- Input Parameters
- Backtest Results
- Trade Journal (which enables to regenerate the chart)
- maybe the Strategy File itself in a Blob-Storage (then you don't have to check your VCS for a first quick-comparison)

br.
Johannes

**Comment by askmike** [comment]
Backtests are cheap and easy to run, what would the end goal be of storing the results on disk?

**Comment by thegamecat** [comment]
I store all backtests to csvs using the code you can find in the readme here:
https://github.com/thegamecat/gekko-trading-stuff

**Comment by JohannesFerner** [comment]
Hi @askmike , @thegamecat,

The reason why i would like to persist the results and parameters of backtests is 
1 - you can more easily compare the results of different input parameters on the same strategy. 
2 - normally a dev will adapt its strategy rapidly in the process of development. If you have several backtests according the version of the strategy it's easier to measure the performance of the backtest KPIs and rate the several stages of strategy. Maybe you are familiar with the quantconnect (https://www.quantconnect.com/) project in order to experience the value of this feature.

@thegamecat thanks for the snippet, I'll look into it.

**Comment by askmike** [comment]
@JohannesFerner another problem I see is that if you only store the hash of the strat file we cannot show the full strat (if you iterated 10 times and your 5th was the best), so that would leave questionmarks about which version was ran.

Also how would you visualize any of this? The backtest page is very simple at the moment, at the top you configure one and at the bottom you see the results. How would your proposal work?

----

I don't see why we would need to store/save results, can't we just cache them in memory (vuex)?

**Comment by thegamecat** [comment]
This is a great topic for me.

**What version was run ?**

I solved this by adding variables to the file name which means I can identify it. Equally you could put these in a meta file alongside an output csv.

**How would you visualise it ?**

Another great question - I just open the files in Excel and manipulate accordingly. Could use any of a myriad of tools, I have been wondering how to output the whole thing to a webapp / trading view viewer, not sure how that would work though. One to consider later.

**The backtest page is very simple at the moment, at the top you configure one and at the bottom you see the results. How would your proposal work?**

I suspect he would like a trading view output with the points at which a strat bought and sold so you can see at a glance what worked within the context of the indicators used. And be able to flip between different "backtests" to see the variances alongside the pnl of each. 

At least that's what I do, just in a clunky way using excel.

**Comment by greenbigfrog** [comment]
Any plans on implementing this or the like? Else old issues should be closed...
