### ISSUE TITLE
[request] Equitity Chart

### ISSUE THREAD

**Issue by JohannesFerner** [askmike/gekko#860]
Hi,

Currently the Backtest Chart shows the Symbol we were testing including Buy/Sell Points. 

Another Chart Showing the Absolute and Relative Account Performance would be useful to visually classify and rate the underlying strategy. 

MockUp: 

![gekko](https://user-images.githubusercontent.com/1781395/28378747-898e875e-6cb1-11e7-89fd-330a93a75265.png)

**Comment by askmike** [comment]
I will try to pick this up as part of #793!

The main idea currently is that there will be a few different line charts:

- price chart (with buy/sell orders) -> this one exists
- indicator chart per indicator
- a portfolio balance chart, showing development of profit/loss over time.

**Comment by greenbigfrog** [comment]
ping
