### ISSUE TITLE
[request] Allow Multi-Import

### ISSUE THREAD

**Issue by JohannesFerner** [askmike/gekko#861]
Hi,

a Usability Request: 

It would be easier to have a multi-select popup on the asset selection droddown in order to start multiple imports at once. 

Mockup: 

![multi-import](https://user-images.githubusercontent.com/1781395/28379798-4c06b56a-6cb5-11e7-896c-ad0db1c5ecc4.png)

br.
Johannes

**Comment by askmike** [comment]
I see the UX reasons behind this, but there would be 2 major limitations:

- by default data is stored in sqlite. Each import (is currently designed to) run in a seperate process which means they cannot share one database connection. Sqlite will start complaining pretty fast, see #664.
- allowing users to start a lot of imports in parallel is a great way to get rate limited / API banned from the exchange really fast. Without sufficient information on hard/soft caps it's better to not try your luck imo.
