### ISSUE TITLE
[request] prepend UTC in front of date values + Clock in Header

### ISSUE THREAD

**Issue by JohannesFerner** [askmike/gekko#862]
Hello,

I personally agree to using UTC Dates, but ... 
it would help to include a clock and "UTC" in front of certain important dates.

![item-0_and_item-0_and_item-0_and_item-0_and_item-0_and_item-0_and_item-0_and_item-0_and_item-0_and_applebluetoothextra_and_airportextra_and_displaysextra_and_appleclockextra_and_appleuser](https://user-images.githubusercontent.com/1781395/28380193-b36bf476-6cb6-11e7-8da5-5a0575c9505c.png)

br.
Johannes

**Comment by askmike** [comment]
Hey,

Within Gekko all dates are UTC, the reasoning is that makes it easy to copy settings and compare screens all over the world, regardless of the timezone of the exchange or your own timezone.

As for making this clear, I'd rather at this to the docs (maybe we should create a FAQ with this in it or so), else the whole UI will be clogged up with the string "UTC" everywhere. What do you think?

**Comment by JohannesFerner** [comment]
Hi @askmike, 

Ok, valid point. Leaving the UI as clean as possible is definitely good. 
I would leave the prepended "UTC" string, but integrate a small clock in the header like this (only visible if you're not in UTC):

![28380193-b36bf476-6cb6-11e7-8da5-5a0575c9505c_png__1564x876_](https://user-images.githubusercontent.com/1781395/28408230-1ac7e154-6d37-11e7-9144-e7101af1b13d.jpg)

**Comment by wuhkuh** [comment]
In my own bot I'm using UTC internals based on timestamps. The GUI converts this to the local time. I'd suggest doing so as well, as most JS implementations will automatically convert this to local time + locale. This is how:

```
// multiplication of 1000 is because Date is in milliseconds
const localDate = new Date(timestamp * 1000).toLocaleString()
```

Example:
```
const localDate = new Date(1500000000 * 1000).toLocaleString()
console.log(localDate)
```
> 2017-7-14 04:40:00

http://www.convert-unix-time.com/?t=1500000000

> In your local time zone: Friday 14th July 2017 04:40:00 AM
> UTC: Friday 14th July 2017 02:40:00 AM

That's exactly what we want, right? You're still using UTC internals, but now with the GUI in local time.
I wouldn't use the UTC + local clock, as it will be confusing at best.

**Comment by askmike** [comment]
@wuhkuh 

> In my own bot I'm using UTC internals based on timestamps. The GUI converts this to the local time. 

internally Gekko also uses UTC based moment objects internally. The point I was trying to get across is: regardless of where you are when watching the UI (`toLocaleString`), I want the UI to look the same so people can copy paste date ranges, compare charts, etc.

**Comment by greenbigfrog** [comment]
boop

**Comment by kevinxh** [comment]
I agree that default to UTC is useful, but it would also be nice if there is an option to switch between local time and UTC.

**Comment by IAMtheIAM** [comment]
I vote for the addition of a timezone flag for both the CLI and the UI, so we can easily compare to other charts which already have converted to local time. 

What is a good way to accomplish this?
