### ISSUE TITLE
[request] Add cryptopia.co.nz Exchange 

### ISSUE THREAD

**Issue by JohannesFerner** [askmike/gekko#863]
cryptopia.co.nz is one of the Exchanges which trades a lot of unpopular coins; 
This may be very interesting for some traders here

**Public API Docs:** 
https://www.cryptopia.co.nz/Forum/Thread/255

**Private API Docs:**
https://www.cryptopia.co.nz/Forum/Thread/256

**API Examples:**
https://www.cryptopia.co.nz/Forum/Thread/262

**Comment by askmike** [comment]
I will be to busy to add more exchanges in the coming time. The good thing is that anyone can add an exchange to gekko and submit a pull request to have it added. The required documentation can be found here: https://gekko.wizb.it/docs/extending/add_an_exchange.html

**Comment by askmike** [comment]
I am closing this as I don't see this as an existing issue. I am very open to a PR and if you have questions let me know!
