### ISSUE TITLE
CCI doesn't work but DEMA does

### ISSUE THREAD

**Issue by JoshS0515** [askmike/gekko#866]
If all I change is the method name from DEMA to CCI it no executes trades. I left the trader on for 2 days and though my trading view chart showed it had a multitude of buying and selling opportunities it never once executes the trade. 

Here is the error message:

2017-07-20 06:59:31 (INFO):     Setting up Gekko in realtime mode
2017-07-20 06:59:31 (INFO):
2017-07-20 06:59:31 (INFO):     Setting up:
2017-07-20 06:59:31 (INFO):              Trading Advisor
2017-07-20 06:59:31 (INFO):              Calculate trading advice
2017-07-20 06:59:31 (INFO):              Using the strategy: CCI
2017-07-20 06:59:31 (WARN):     Warning, trading method has no name
2017-07-20 06:59:31 (INFO):             The trading method requests 300 minutes of historic data. Checking availablity..
2017-07-20 06:59:31 (INFO):

2017-07-20 06:59:31 (INFO):             No usable local data available, trying to get as much as possible from the exchange..
2017-07-20 06:59:31 (INFO):             Preventing Gekko from requesting 300 minutes of history.
2017-07-20 06:59:32 (INFO):             Not seeding locally available data to the trading method.
2017-07-20 06:59:32 (INFO):     Setting up:
2017-07-20 06:59:32 (INFO):              Trader
2017-07-20 06:59:32 (INFO):              Follows the advice and create real orders.

Here is where I set the method:

config.tradingAdvisor = {
  enabled: true,
  method: 'CCI',
  candleSize: 30,
  historySize: 10,
  adapter: 'sqlite',
  talib: {
    enabled: false,
    version: '1.0.2'
  }
}

I am not sure what else to look at past that.

**Comment by askmike** [comment]
>  though my trading view chart showed it had a multitude of buying and selling opportunities

What do you mean by this in context of the CCI strategy / indicator?

If you think the CCI strat is broken, can you backtest over a longer period?

**Comment by JoshS0515** [comment]
I am not sure if the CCI is broken at all. I was watching at another location using the Trading View website to indicate when it would buy or sell. CCI went well into the -300s and it never made a sell for something set at -100s to sell. 

I would imagine it has more to do with this: 2017-07-20 06:59:31 (WARN): Warning, trading method has no name

**Comment by askmike** [comment]
> I would imagine it has more to do with this: 2017-07-20 06:59:31 (WARN): Warning, trading method has no name

Ah no this is unrelated, you can ignore that. Can you enable debug in your config (seeing you are running gekko over the commandline)? And post debug logs of the calculated CCI output?

**Comment by JoshS0515** [comment]
I don't see that in the documentation off hand. Can you share its location or the command line to run it?

**Comment by askmike** [comment]
In the config you are using, can you set this to true? https://github.com/askmike/gekko/blob/stable/sample-config.js#L10

**Comment by JoshS0515** [comment]
Yep will run again and return with results

**Comment by askmike** [comment]
Great thanks! Quick tip:

If you had the plugin candleWriter enabled in the config, you can backtest over the same period you initially live ran over and you should get the same results (backtesting requires different plugins though, see [here](https://gekko.wizb.it/docs/commandline/backtesting.html)).

**Comment by JoshS0515** [comment]
Now would be a great time for it to buy but it isn't still. 
![capture](https://user-images.githubusercontent.com/16510577/28425997-e2402e14-6d3f-11e7-91ce-2858c89a2f5d.PNG)

All I see from Gekko is that there is new trades it is processing.

**Comment by JoshS0515** [comment]
![image](https://user-images.githubusercontent.com/16510577/28436191-06865306-6d64-11e7-9e61-014d4aba249f.png)


Only option 1 returns results. 

Though on TradingView (the website with the same settings) claims there are multiple opportunities to sell.

Is there any advice to continue? It is weird that it is just CCI. Also, the options above seem very small in size when I attempt to run the script for multiple hours (Even days) at a time so I am not sure if the script is cut off at any point as well?

**Comment by thegamecat** [comment]
Trading view indicators are not giving the same values as gekko, do not rely on a direct read across.

write the prices and strat values to a csv and learn from that.

**Comment by JoshS0515** [comment]
@thegamecat can you give me any idea on how to print that info to CSV from the command line? I am still having issues with CCI

**Comment by greenbigfrog** [comment]
this is outdated @askmike
