### ISSUE TITLE
Localhost connection refused

### ISSUE THREAD

**Issue by NAmenta** [askmike/gekko#872]
Hello, I am very new to Java and Gekko. I am trying to get it up and running but am encountering issues. First one being that when I navigate to the UI http://localhost:3000 I get an error message:

localhost refused to connect.
Try:
Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

I am using windows 10 with a wifi connection if that helps.
Thanks and any help would be greatly appreciated!

**Comment by askmike** [comment]
So are you running Gekko in a command prompt? Can you take a screenshot of all the output there?

**Comment by NAmenta** [comment]
This is what I have so far:


​[image: Inline image 1]

**Comment by askmike** [comment]
@NAmenta The image is not visible unfortunately.

**Comment by NAmenta** [comment]
I'm sorry, is the image there but you can't make out what it says or did it
not sens properly. i can try to send it as an attachment if you like.

**Comment by askmike** [comment]
Can you email it to me? gekko@mvr.me

**Comment by askmike** [comment]
I've seen the pictures now, strange

> I am using windows 10

Can you check if you have a firewall enabled or something? It appears Gekko is able to start fine but still somehow chrome can't reach it..

**Comment by NAmenta** [comment]
Ok i turned windows firewall off. I tried making an exception but
apparently that wasnt enough. Works now but hopefully i can figure out
actually getting it up and running and trading properly.

**Comment by askmike** [comment]
> and trading properly.

Note that for live trading (as opposed to running simulations) you need the latest develop branch: https://github.com/askmike/gekko/tree/develop

I recommand first trying to get your hands dirty simulating though :)

**Comment by NAmenta** [comment]
Most definitely! Thanks so much. If I have issues can I email you again?

**Comment by askmike** [comment]
Please first open an issue, this way other people who have the same issue can also discuss/read.

**Comment by NAmenta** [comment]
I will be sure to do that. Thanks Mike!
