### ISSUE TITLE
ubuntu 17.04 node install no gui

### ISSUE THREAD

**Issue by jeremiahtenbrink** [askmike/gekko#873]
I have tried installing gekko on my ubuntu server 17.04. I have node and npm installed and current version of node is 6.11.1 and npm version is 3.10.10. I have edited the UIconfig.js file to match my network. I'm on my other computer trying to get the ui to load and it wont load for some reason. I can't think of anything else I missed. Please if anyone has any ideas I would be very grateful.

**Comment by askmike** [comment]
What do you mean with "it wont load"?

**Comment by jeremiahtenbrink** [comment]
wont start up. If I go to the webpage x.x.x.x:3000 it wont connect. There is a blank page.

**Comment by askmike** [comment]
So is it fully blank (white)? Or is there an error message? Can you post output of the gekko process in the terminal/command prompt?

**Comment by jeremiahtenbrink** [comment]
jeremiah@ubuntu:~/gekko$ nodejs gekko --ui

    ______   ________  __    __  __    __   ______
   /      \ /        |/  |  /  |/  |  /  | /      \
  /$$$$$$  |$$$$$$$$/ $$ | /$$/ $$ | /$$/ /$$$$$$  |
  $$ | _$$/ $$ |__    $$ |/$$/  $$ |/$$/  $$ |  $$ |
  $$ |/    |$$    |   $$  $$<   $$  $$<   $$ |  $$ |
  $$ |$$$$ |$$$$$/    $$$$$  \  $$$$$  \  $$ |  $$ |
  $$ \__$$ |$$ |_____ $$ |$$  \ $$ |$$  \ $$ \__$$ |
  $$    $$/ $$       |$$ | $$  |$$ | $$  |$$    $$/
   $$$$$$/  $$$$$$$$/ $$/   $$/ $$/   $$/  $$$$$$/

        Gekko v0.4.10
        I'm gonna make you rich, Bud Fox.


TAlib is disabled
Serving Gekko UI on http://10.1.10.112:3000/

**Comment by jeremiahtenbrink** [comment]
This site can’t be reached

10.1.10.112 refused to connect.
Search Google for 112 3000
ERR_CONNECTION_REFUSED

**Comment by askmike** [comment]
Is this still an issue? Since in #878 your UI works fine.

**Comment by jeremiahtenbrink** [comment]
No because I got it working on my windows PC. Thanks for your help. I appreciate it.
