### ISSUE TITLE
Install on windows npm says to fix the package.json file. 

### ISSUE THREAD

**Issue by jeremiahtenbrink** [askmike/gekko#878]
I'm including the log file that npm is telling me to include. I've looked through the package.json file and I can't find anything wrong. However I'm a newb. When you get some time would you be ever so kind as to helping me figure this out. I would really like to test the bot out. Please and thank you. 

[npm-debug.txt](https://github.com/askmike/gekko/files/1168655/npm-debug.txt)

**Comment by askmike** [comment]
For some weird reason it is complaining about a dependency, can you try cleaning the npm cache and installing again?

    npm cache clean
    npm install

Thanks!

**Comment by jeremiahtenbrink** [comment]
I did that and now I'm getting an error about my python vs being 3.6 which isn't supported by gyp. Command line says you can pass the --python switch to point to python >=v2.5.0 & < 3.0.0. 

Is that something I do from the command line? I'll start looking to see if I can come up with something. Hopefully I can figure it out before you get back to this. Thanks for the assistance. Hope to hear from you soon.

**Comment by jeremiahtenbrink** [comment]
It started the UI just fine. I'm going to try and run a config file now. Maybe that corrected the issue.

**Comment by askmike** [comment]
if the UI is fine I wouldn't worry about anything gyp (or anythng else related to npm install) is saying. Note that the config.js file is not needed if you use the UI.

**Comment by jeremiahtenbrink** [comment]
everything seems to be working just fine now. Thanks alot for the help. I really appreciate it. I was hoping to automate trading with IOTA. The program says it only supports LTC ETH and BTC. Is it possible to incorporate IOTA into the program any time soon?

**Comment by askmike** [comment]
You can propose a PR if you want, you can edit the assets per exchange in their corresponding exchange file in the folder `/exchanges/`. Note that for this you need to be using the develop branch of gekko, since where this data was stored is changing.

Example: https://github.com/askmike/gekko/blob/develop/exchanges/poloniex.js#L234

**Comment by askmike** [comment]
Here is an example of someone adding GNT #867.
