### ISSUE TITLE
Making orders using Gekko

### ISSUE THREAD

**Issue by raffus** [askmike/gekko#880]
Hi there,

I've just written my own strategy using Gekko and it has been running for about 30 hours now.

Since the last start, I've received two emails:

> Gekko is watching poloniex and has detected a new trend, advice is to go long.
> The current BTC price is 2713.99999999

And then this:

> Gekko is watching poloniex and has detected a new trend, advice is to go short.
> The current BTC price is 2751.89791548

When I checked out my exchange account, there were no operations made.

In my strategy code, I'm using this method (imagining that this is for purchase):

`this.advice("long");`

And this when selling:

`this.advice("short");`

I'm not sure if this are the buy/sell commands or if there's another one to do this.

Thanks a lot guys.

R

**Comment by askmike** [comment]
How are you running Gekko? CLI or UI? Can you post setup information for how you ran the gekko?

**Comment by askmike** [comment]
Actually since you configured the emailer:

In Gekko the strats just emit the advice, if you want something to happen (in this case: real exchange orders), you need to enable the "trader" plugin in your config (and fill in API keys).

**Comment by askmike** [comment]
I am assuming it was a configuration issue, if not: please turn on debug in your config and post logs.

**Comment by raffus** [comment]
Hi @askmike,

I've found the problem.
You're write, I forgot to set

```
config.trader = {
  enabled: true
}
```

After doing it, now when running on CLI I'm getting this error:

```
2017-07-24 11:40:35 (INFO):	Setting up:
2017-07-24 11:40:35 (INFO):		 Trader
2017-07-24 11:40:35 (INFO):		 Follows the advice and create real orders.
2017-07-24 11:40:35 (DEBUG):	getting balance & fee from Poloniex
2017-07-24 11:40:35 (INFO):	

Gekko encountered an error and can't continue

Error:

Nonce must be greater than 1500907226273167. You provided 150090723639900. 

```

Thanks

**Comment by askmike** [comment]
You've used the API keys with another tool. You need to generate new API keys at poloniex and not use them anywhere else. EDIT: that is what it looks like, even if you didn't could you please generate new ones and try again?

**Comment by raffus** [comment]
Yeahh!! That worked!! :)
Huge thanks buddy.
