### ISSUE TITLE
gekko tradebot- encountered error and can't continue

### ISSUE THREAD

**Issue by kza95** [askmike/gekko#882]
using the develop branch for ui to test out...I got a new api but it's still not working. Did I do something wrong?

RECEIVED ERROR IN GEKKO 325093676714448

Gekko encountered an error and can't continue

Gekko encountered an error and can't continue

Error:

Gekko was unable to set the portfolio

Meta debug info:

Gekko version: v0.5.0
Nodejs version: v7.9.0

**Comment by askmike** [comment]
Does you api key has the proper permissions to check balance?

**Comment by kza95** [comment]
yeah, I did. I actually figured it out...I had two api-keys.js and I think that messed it up. I deleted one, got a new api, and restarted it...it seems to be working now. Thanks :D

**Comment by doepat** [comment]
Hi I had the same issue. I deleted my api key, generated a new one (Without (!) IP Check). Is this an open issue? in other words. is this known, that IP check within API (e.g. Poloniex) is not supported?

**Comment by ghost** [comment]
I have the same problem

**Comment by nealkernohan** [comment]
I have this same issue on stable branch.  I'm using TSI, setup from the UI and typically fails every 2-3 hours with this message.  My API keys are setup correctly as Gekko will make some trades but then falls over later with this message.  I'm on Poloniex using a small amount of BTC as a test.   If I move my UI settings to a config (I'm not sure how to) would it make Gekko more stable or what action can I take?  reinstall node, Gekko and all dependencies?

**Comment by SxmickY** [comment]
Hi, I have the same problem too, do you have any news?
