### ISSUE TITLE
I can't seem to get bitfinex to start trading. 

### ISSUE THREAD

**Issue by jeremiahtenbrink** [askmike/gekko#885]
I've been looking at this code for proablably the last two days trying to figure out why it says bitfinex can't trade at this time. I was wondering if anyone knows where I should be looking/ editing to try and make this possible.

**Comment by askmike** [comment]
What branch of gekko are you running? And can you post the exact error or message you are seeing?

**Comment by lipka** [comment]
Bitfinex seems to be missing the `tradable` capability in `Trader.getCapabilities`.

**Comment by lipka** [comment]
https://github.com/askmike/gekko/pull/917

**Comment by askmike** [comment]
This has since been fixed :)
