### ISSUE TITLE
Populate candleProps for non Talib indicators/strategies

### ISSUE THREAD

**Issue by thegamecat** [askmike/gekko#891]
From playing around I've noticed that candleProps doesn't get set unless you add a Talib indicator to your strategy. From testing this is the line that does this contained in baseTradingMethod:

 if(this.asyncTick) {
    this.candleProps.open.push(candle.open);
    this.candleProps.high.push(candle.high);
    this.candleProps.low.push(candle.low);
    this.candleProps.close.push(candle.close);
    this.candleProps.volume.push(candle.volume);

    if(this.age > this.candlePropsCacheSize) {
      this.candleProps.open.shift();
      this.candleProps.high.shift();
      this.candleProps.low.shift();
      this.candleProps.close.shift();
      this.candleProps.volume.shift();
    }
}

If I rem out the  if(this.asyncTick) { then candleprops is set and usable to my non Talib indicators.

Can I be confident that the values set are correct and not jumbled due to async? (ie what is the purpose of the if statement?)

**Comment by askmike** [comment]
> If I rem out the if(this.asyncTick) { then candleprops is set and usable to my non Talib indicators.

Except that non talib indicators get price updates directly from the candle. So `this.candleProps` is only used for talib indicators and for nothing else.

---

The baseTradingMethod is a bit of a mess at the moment, if you have any questions about how it works (or is supposed to anyway) feel free to ask here!

**Comment by askmike** [comment]
The indicators get updates every candle here: https://github.com/askmike/gekko/blob/stable/plugins/tradingAdvisor/baseTradingMethod.js#L166-L173

**Comment by thegamecat** [comment]
> Except that non talib indicators get price updates directly from the candle. So this.candleProps is only used for talib indicators and for nothing else.

Yes, but then I have to create and manage the arrays in the strategy - this way I always have candleProps to reference which is preferable to me as there is one version of the truth for all indicators then.

**Comment by askmike** [comment]
These props were not meant to be exposed (and used in strategies), you can definitely uncomment them if you want though :)

**Comment by askmike** [comment]
What about an option in the `tradingAdvisor` that populates these arrays regardless of ASYNC candles?

**Comment by thegamecat** [comment]
Not sure what you mean - so long as the candles are populated I don't think it matters much.

**Comment by askmike** [comment]
I know, but I don't want to always populate them. They are only needed for TAlib indicators or for you. They will be populated when there are TAlib indicators, so we could add a config switch so they will be populated for you.

**Comment by thegamecat** [comment]
Ah I see, ok. But as someone pointed out  all the data should be available all of the time.

I’m also convinced that talib will be replaced at some point, it’s just too slow.

**Comment by askmike** [comment]
> Ah I see, ok. But as someone pointed out  all the data should be available all of the time.

Who pointed that out? They are not available at all times and that's a design decision.

> I’m also convinced that talib will be replaced at some point, it’s just too slow.

I don't think it's TAlib that's slow, just the overhead of calling it per candle. In the past I commented on why the current backtester is slow and what to do to make it faster, I am convinced that TAlib indicators will be a lot faster in that setup (assuming it runs native, no idea how windows bash works).
