### ISSUE TITLE
MACD in two candlesize

### ISSUE THREAD

**Issue by dtotti08** [askmike/gekko#893]
How do I use the MACD strategy in two different candle times? For example: give buy when the MACD of 4 hours is indicating purchase and the of 2 hours also indicating purchase! Thank you in advance!

**Comment by askmike** [comment]
The easy answer: Unfortunately that is not possible with Gekko right now, however some other people have extended Gekko to support a feature called multi time frame. Here are two relevant discussions: #496 and #762.

---

Note that with MACD you can easily create a strategy that registeres two different MACDs:

- one with the short and long quite far apart (results in a "sensitive" diff signal)
- one with the short and long quite closer together (results in a "less sensitive" diff signal).

This mimics the behaviour you are looking for, however this is not possible with all indicators.
