### ISSUE TITLE
[bug] According to living countries Time Zone Calibration.

### ISSUE THREAD

**Issue by DrFREEST** [askmike/gekko#895]
The current chart data is applied market time zone.
but the transaction details are displayed in the local pc time in Gekko UI mode.
The sync between the two data is invalid.

In the UI Config tab, please update the time zone settings.

thank you:)

**Comment by askmike** [comment]
Would you be able to post a screenshot of exactly what details are displayed incorrectly?

**Comment by askmike** [comment]
This is a screenshot from another user with the same problem. That user is in UTC8:


![](https://media.discordapp.net/attachments/342488930983215115/342653800705949696/Screenshot_from_2017-08-03_21-03-33.png)

**Comment by DrFREEST** [comment]
I'm sorry.
I don't have a screenshot ...
After finding the first error, 
Yet I don't take any extra screen shots because the deal wasn't trading ...

**Comment by DrFREEST** [comment]
[2017-08-10 update]
![image](https://user-images.githubusercontent.com/21992858/29149852-b7d0ae24-7db1-11e7-8224-58d29f1dd849.png)


This is my trading chart.
the trading points nine hours apart.

**Comment by apeironn8** [comment]
I'm having the same issue here at gmt+1 there's one hour difference between the chart and the table 
![image](https://user-images.githubusercontent.com/31378572/29844695-13131a78-8d08-11e7-9aa4-3cb6374ca414.png)

any workaround to this? and is the correct data the one in the table or the one plotted in the chart?

**Comment by apeironn8** [comment]
still wondering if there's anything we could do to workaround this? its making it really hard to backtest

**Comment by askmike** [comment]
Took way too long, but finally fixed in develop!

**Comment by bullsei** [comment]
Hi, this is supposed to be fixed but i still got some problems with it it seems.

![image](https://user-images.githubusercontent.com/13682116/33217267-7ed1b27e-d137-11e7-9a45-935a4e256c7a.png)

As you can see the times are still off by 1 hour
If you need more information let me know.
