### ISSUE TITLE
BollingerBands strategy

### ISSUE THREAD

**Issue by endorianix** [askmike/gekko#898]
Hello,
Anyone got working BollingerBand (Talib) strategy and maybe can share it over here?

**Comment by CyborgDroid** [comment]
+1. If you know how to code it (I don't). I would start with defining if it will be an exponential moving average or a simple moving average. Periods, and how many standard deviations from the EMA or MA you want the bands to be at. Also set a shorter EMA to know if it is a downtrend or uptrend. If short EMA is smaller than real EMA then it is a downtrend and the EMA becomes the upper limit trigger with some persistence set. At the same time EMA - STDEV would be the lower limit with same persistence set before buying. 

On the other hand, if the short EMA > normal EMA that means there is an upward trend. So the EMA becomes the buy signal and EMA + STDDEV becomes the sell signal after some persistence is reached.

If you succeed, please share so I can play with it too :)

**Comment by decoye** [comment]
whats the reason to ask for a specific indicator strategy? 
Are you a fan of bollinger or a fan of making profits?

**Comment by thegamecat** [comment]
Well it's worth learning all the strategies as they all have strengths and weaknesses.

**Comment by decoye** [comment]
thats absolutely true, thats why i wonder why he asked about a bollinger band strategy ONLY.

**Comment by decoye** [comment]
https://cryptotrader.org/backtests/5eNpP3xAMzenPd6uu

`###
  The script engine is based on CoffeeScript (http://coffeescript.org)
  The Cryptotrader API documentation is available at https://cryptotrader.org/api
  
  EMA CROSSOVER TRADING ALGORITHM
  
  The strategy enters buy orders when the short-term EMA crosses above the long-term EMA 
  or enters sell orders when the short-term EMA crosses below the long-term EMA.

  
###

trading = require 'trading' # import core trading module
talib = require 'talib' # import technical indicators library (https://cryptotrader.org/talib)

# Initialization method called before the script starts. 
# Context object holds script data and will be passed to 'handle' method. 
init: ->
    @context.buy_treshold = 0.25
    @context.sell_treshold = 0.25

# This method is called for each tick
handle: ->
    # data object provides access to market data
    instrument = @data.instruments[0]
     # calculate EMA value using ta-lib function
    short = instrument.ema(10)
    long = instrument.ema(31)       
    # plot chart data
    plot
        short: short
        long: long
    diff = 100 * (short - long) / ((short + long) / 2)
    # Uncomment next line for some debugging
    #debug 'EMA difference: '+diff.toFixed(3)+' price: '+instrument.price.toFixed(2)+' at '+new Date(data.at)
 
    if diff > @context.buy_treshold
        # The portfolio object gives access to information about funds 
        # instrument.base() returns base asset id e.g cny
        if @portfolio.positions[instrument.base()].amount > 0
            # open long position
            trading.buy instrument  
    else
        if diff < -@context.sell_treshold
            # instrument.asset() returns traded asset id, for example: "btc"
            if @portfolio.positions[instrument.asset()].amount > 0
                # close long position
                trading.sell instrument

`
