### ISSUE TITLE
'size too precise' buying at GDAX

### ISSUE THREAD

**Issue by CMyers79** [askmike/gekko#899]
I'm running stable branch from the command line on windows, I get this error when the bot tries to buy at GDAX:

![gekko-error](https://user-images.githubusercontent.com/30599967/28784867-8616e942-75c9-11e7-99a0-d4c2d71fb7b5.jpg)

**Comment by askmike** [comment]
What version of Gekko are you running? You can check by running: `node gekko --version`

**Comment by CMyers79** [comment]
Gekko v0.5.0
Nodejs v6.11.1

**Comment by askmike** [comment]
I am sorry about this, it should be fixed now. Can you try again with the latest version?

**Comment by askmike** [comment]
Assuming this is fixed, if it isn't please reopen.

**Comment by CMyers79** [comment]
Yes, thanks for the quick response!
