### ISSUE TITLE
Need some clarity on thresholds and persistance.

### ISSUE THREAD

**Issue by ElscottHavoc** [askmike/gekko#902]
So, I have a pretty good idea on what MACD is but I'm not completely sure how the thresholds and persistence work.

My understanding is that the up and down thresholds allow you to set a minimum distance between the signal line and the MACD line before the bot takes an action.  So setting both to 0 would just take an action at the point that the two lines cross, but otherwise you can change those variables to allow for greater profit taking by setting the up threshold higher while decreasing the down variable to set a sort of stop loss.  But I'm not sure if those thresholds are percentages or amounts in BTC or USD.

Secondly, does the persistence of the number of candles you set mean that the bot only takes action if both the lines cross and it has a single candle moving in that trend, or does it mean it waits X number of candles after the signal line has crossed before it takes an action.

Thank you.  I've been playing around with these and trying to read at forex sites and stock sites that use similar indicators, but it appears most of them don't take into consideration the thresholds and the persistence of a trend, instead just focusing and discussing the short, long, and signal numbers - I'm assuming then just taking action whenever those lines cross is what they're doing.  Just looking for a better understanding if possible.

**Comment by askmike** [comment]
Hey,

> My understanding is that the up and down thresholds allow you to set a minimum distance between the signal line and the MACD line before the bot takes an action. So setting both to 0 would just take an action at the point that the two lines cross

Yes this is correct

> but otherwise you can change those variables to allow for greater profit taking by setting the up threshold higher while decreasing the down variable to set a sort of stop loss.

You are right about the "stop loss" (though it will react very slow, will just trigger a short signal - very different from a stop loss order on an exchange), but a higher threshold doesn't mean more profit. It only means: it requires the distance between the signal line and the MACD line to be higher. This way the markets needs to be going up *more* before the strategy will trigger an advice (and thus go long = buy into the uptrend).

> But I'm not sure if those thresholds are percentages or amounts in BTC or USD.

These are in percentages!

> does the persistence of the number of candles you set mean that the bot only takes action if both the lines cross and it has a single candle moving in that trend

If you set persistence to 3 the strategy will only advice to go long after the indicator's output pass the upper threshold 3 candles (consecutively).

--------

> I've been playing around with these and trying to read at forex sites and stock sites that use similar indicators, but it appears most of them don't take into consideration the thresholds and the persistence of a trend, instead just focusing and discussing the short, long, and signal numbers - I'm assuming then just taking action whenever those lines cross is what they're doing. 

So MACD by itself is an indicator, which means that given a market (and some parameters) it will spit out numbers. However we don't want numbers, we want buy and sell signals. So when you use Gekko and you select the strategy MACD, you run a [very simple strategy](https://github.com/askmike/gekko/blob/stable/strategies/MACD.js) that implements this indicator (which should be the same as on other Forex sites). And takes the numbers that come out of the indicator and do some checking on these numbers to turn them into advice (thresholds + persistence).

-------

So the MACD strategy found in Gekko just wraps some ideas about how one can use the MACD indicator to generate long/short signals. But the idea with Gekko is that the strategies that come with Gekko are very basic and serve as an example of your own strategies you can build. Nonetheless here is some documentation about some of them:

https://gekko.wizb.it/docs/strategies/example_strategies.html

**Comment by askmike** [comment]
Feel free to keep on commenting :)
