### ISSUE TITLE
No UI on Linux?

### ISSUE THREAD

**Issue by TheFutureIsCrypto** [askmike/gekko#904]
I'm just playing around trying to get Gekko to run on my Ubuntu Box. After copying sample-config to Config folder and starting this way in terminal:
cd Programs/gekko-stable
node gekko --config config.js

Gekko runs but i get no UI?
Any ideas?

![gekko](https://user-images.githubusercontent.com/30638188/28848276-314d2d8c-76c7-11e7-901d-8dc521564c57.png)

**Comment by TheFutureIsCrypto** [comment]
PS: If i start Gekko with:
node gekko

I get:  ERROR: Please specify a config file.

Chromium Browser

**Comment by askmike** [comment]
If you want to start Gekko in the UI mode you can completely ignore the `sample-config.js` file and run the following command:

    node gekko --ui

Where did you read that you should run `node gekko --config config.js`?

**Comment by TheFutureIsCrypto** [comment]
Thanks Mike....that did it
Everywhere i looked i saw "node gekko" for starting.
When i got the error to specify config file, I tried "node gekko --config config.js"
It should be more prominent somewhere that to run the program with UI... "node gekko --ui" should be used.
Thanks for your quick reply

**Comment by askmike** [comment]
I will look into improving the docs! The UI was only added to Gekko a few
months back, while the command line version dates back 4 years now. If you
can link to specific docs that specify node gekko that would be great!

**Comment by TheFutureIsCrypto** [comment]
Hey Mike,
Geeesh.....looking back over where i "thought" i saw node gekko, everywhere seems to say "node gekko --ui" now. It's amazing how our brains can fool us sometimes. Your program's running good for me now on Ubuntu. I built a trader in VBA with excel back in the internet bubble and plan on playing with yours quite a bit. It's finally time to learn javascript.
Keep up the good work!
