### ISSUE TITLE
Cancel and delete imports

### ISSUE THREAD

**Issue by ramirez3805** [askmike/gekko#905]
Hello and thank you!
I just set this up and I don't see an option to cancel the imports. I didn't know it would take such a long time to import certain data ranges, also, is there a way to delete imports?

Thanks!

**Comment by askmike** [comment]
Good point,

managing (deleting data) is on the roadmap, I will add canceling imports to it. (Just to be clear: when you want to cancel you want to keep the data up until that point?)

**Comment by ramirez3805** [comment]
Naw, because if you wanted to get the data up to a certain point, you can just rerun the import. Thanks so much. Another question, I'm not a super programmer or anything like that, I know a bit of python though, is there anyway I can help out. Also, do you are a link to add new coins and or exchanges, I think you had that before but the page I saw was down. Thanks again.

**Comment by askmike** [comment]
The link is here: https://gekko.wizb.it/docs/extending/add_an_exchange.html

> Naw, because if you wanted to get the data up to a certain point, you can just rerun the import. 

But it's not bad that it will be stored right? The importer will actually pump market data straight into the database when it receives it. So stopping halfway would store half the import. But I guess this doesn't matter once you can easily delete datasets as well.

**Comment by ramirez3805** [comment]
Up to you man, Sounds great, thanks so much! Keep up the good work!

**Comment by dimisjim** [comment]
Is there any updates on this? I try to import data from binance but it doesn't start at all.

I get this message on console:

> Deprecation warning: moment().add(period, number) is deprecated. Please use moment().add(number, period). See http://momentjs.com/guides/#/warnings/add-inverted-param/ for more info.

**Comment by DataCourier** [comment]
Yeah being able to get rid of the imports that didn't even start would be nice.
It would also be useful to re-run past imports to get the latest data.
