### ISSUE TITLE
Restarting vs live gekkos

### ISSUE THREAD

**Issue by gulfcoastdev** [askmike/gekko#906]
Thanks for the great software. That must have been a lot of effort to write it!
My paper-trading Gekko got stuck and didn't perform any trades in last couple days. It could be network connection or other unrelated problem. That's really not the issue. So I decided to restart the program assuming that it will automatically restart the live geccos. But after restarting it my live gekkos are gone. 
Is there a way to preserve them on restart?

**Comment by askmike** [comment]
Good idea, not there yet. I would first like to discuss what the desired behaviour should be.

What about an extra option when starting a paper trader saying "This should restart on Gekko restart"?

**Comment by gulfcoastdev** [comment]
Yes, that sounds great. That could be just a checkbox next to it.
Is the real trading Gekko restarted or it has the same behavior as the paper trading Gekko?

**Comment by askmike** [comment]
> Is the real trading Gekko restarted or it has the same behavior as the paper trading Gekko?

Same behaviour. Note that you can also use the commandline interface to run trading Gekkos, this will probably be a lot easier to manage in a 24/7 environment (server/raspi).

---

I am closing this as I just added the requested feature to #911! But if you have more questions feel free to ask.

**Comment by iquirino** [comment]
My paper stops because my memory is fully.
In this case it will restart when any issue occur? Like network problems. 
Im running gekko with pm2 which monitor node process, but i cannot monitor live gekkos running from the UI. 
And the UI is Nice to work... I can RUN my strategies with my smartphone...
