### ISSUE TITLE
Error while upgrading

### ISSUE THREAD

**Issue by KimHono** [askmike/gekko#907]
Hi,

I'm trying to update as advised; "git pull" is OK, but "npm install --only=production" is returning this error :
native array.js:122
iT[zY=½=S)return 4rue?
  ^

SyntaxError: Invalid or unexpected token

Strange, isn't it ?

**Comment by askmike** [comment]
This is very strange, is there any other output besides this?

**Comment by KimHono** [comment]
None, but Gekko crashed with the same error.
Surprisingly, I restarted my computer and just launched "npm install --only=production".
This time it worked !
