### ISSUE TITLE
TA-lib indicators not working

### ISSUE THREAD

**Issue by ghost** [askmike/gekko#908]
When I try back testing using the TA-lib indicators (even the MACD implemented here in the code on GitHub) it throws an error.

TAlib is enabled
Serving Gekko UI on http://localhost:3000/

[…]

/Users/jellevandevelde/gekko/core/talib.js:11
            if(result.error)
                     ^

TypeError: Cannot read property 'error' of null
    at /Users/jellevandevelde/gekko/core/talib.js:11:22
  xxx POST /api/backtest 500 412ms -

  Error: non-error thrown: Child process has died.
      at Object.onerror (/Users/jellevandevelde/gekko/node_modules/koa/lib/context.js:105:40)
      at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by askmike** [comment]
The talib dependency just updated, and Gekko still relies on the old version. You can install the correct one by running:

    npm remove talib
    npm install talib@1.0.2

I think we should add this to the docs somewhere..

**Comment by ghost** [comment]
That did the trick!

**Comment by askmike** [comment]
great :)

**Comment by TechupBusiness** [comment]
As a reminder: please put it in the documentation :)! I was running into this issue. @askmike

**Comment by azpublic** [comment]
For people having similar problem on windows I solved it by doing 

npm install tulind@0.8.13 --build-from-source
