### ISSUE TITLE
Calculating profits

### ISSUE THREAD

**Issue by ghost** [askmike/gekko#910]
<img width="869" alt="screen shot 2017-08-02 at 22 41 29" src="https://user-images.githubusercontent.com/3035059/28876330-c9914260-77d3-11e7-902e-38d6a212bc76.png">

Why are my profits lower than the market growth, even if I didn't make any trades during this back testing? My end balance changed though…

**Comment by askmike** [comment]
Because your profit = the relative increase of your portfolio balance (both currency + asset). But only the *asset* part of your portfolio increased in value.

See #883 for more details.
