### ISSUE TITLE
How to use gekko at Okcoin.cn.

### ISSUE THREAD

**Issue by codewithyou** [askmike/gekko#912]
when i run gekko in command ,it shows log as below : 

Unsupported exchange: okcoin.cn

**Comment by codewithyou** [comment]
config.watch = {

  // see https://gekko.wizb.it/docs/introduction/supported_exchanges.html
  exchange: 'Okcoin.cn',
  currency: 'CNY',
  asset: 'BTC',
    tickrate: 8
  // You can set your own tickrate (refresh rate).
  // If you don't set it, the defaults are 2 sec for
  // okcoin and 20 sec for all other exchanges.
  // tickrate: 20
}

**Comment by askmike** [comment]
You have specify as: `exchange: 'okcoin'`.
