### ISSUE TITLE
Unsupported exchange: okcoin.cn 

### ISSUE THREAD

**Issue by codewithyou** [askmike/gekko#913]
Unsupported exchange: okcoin.cn 

how to support it ?

**Comment by codewithyou** [comment]
config.watch = {

  // see https://gekko.wizb.it/docs/introduction/supported_exchanges.html
  exchange: 'Okcoin.cn',
  currency: 'CNY',
  asset: 'BTC',
    tickrate: 8
  // You can set your own tickrate (refresh rate).
  // If you don't set it, the defaults are 2 sec for
  // okcoin and 20 sec for all other exchanges.
  // tickrate: 20
}

**Comment by askmike** [comment]
duplicate of #912.
