### ISSUE TITLE
SQLITE_CORRUPT: database disk image is malformed errno: 11

### ISSUE THREAD

**Issue by metachris** [askmike/gekko#916]
Hi,

A data download aborted and since then I get this error:

    { Error: SQLITE_CORRUPT: database disk image is malformed errno: 11, code: 'SQLITE_CORRUPT' }

How would I go about deleting or resetting the database?

Would be great to get some feedback inside the UI.

**Comment by askmike** [comment]
Ah yes, I never had this happen actually. I am afraid you have to delete the sqlite file for now, it's stored in the history folder inside the gekko folder.

> Would be great to get some feedback inside the UI.

Could you actually before you delete it email it to me, that why I can work on adding support for giving feedback (I never had this happen before). You can email to gekko@mvr.me

**Comment by metachris** [comment]
thanks. i just sent you the database.

cheers!

**Comment by askmike** [comment]
Great thanks!

**Comment by lost-bro** [comment]
Hello
I am getting the same:

{ Error: SQLITE_CORRUPT: database disk image is malformed errno: 11, code: 'SQLITE_CORRUPT' }

on my data base disk image for a couple of my Binance data bases.

Is there a solution to this yet?
Is there a particular reason for this happening?
Thanks in advance.
mjd
 P.S. I have noticed that once this error occurs, then I cannot further download additional data to that asset/coin pair.

**Comment by rd350** [comment]
Instructions for fix - 
The pragma DEL or truncate option did not work for me. The following is what i did to fix it - 
1. Connect to db from bash (my db is bitfinex)
`bash> sqlite3 bitfinex_0.1.db`
`sqlite3> .open bitfinex_0.1.db`
2. Run analyze to check for errors:
`sqlite3>  analyze;`
3. `sqlite3> .mode insert`
4. `sqlite3> .output mydb_export.sql`
5. `sqlite3> .dump`
6. `sqlite3> .exit`
7. Rename the existing db to something else 
`bash> mv bitfinex_0.1.db bitfinex_0.1.db.original`
8. import the dump file as your db
`bash> sqlite3 bitfinex_0.1.db < mydb_export.sql`

9. Run analyze again to check for errors. If there are no errors then good to go.

All your downloaded scansets should be available, cheers!
