### ISSUE TITLE
BitFinex transaction history import for backtesting

### ISSUE THREAD

**Issue by pelletencate** [askmike/gekko#918]
BitFinex allows import of history trades using the `v1/trades/SYMBOL` endpoint. Gekko should be able to use it to import trades in order to backtest on them.

**Comment by askmike** [comment]
Good idea, I need to work on documentation on how to add importing support per exchange..

**Comment by cmroche** [comment]
@pelletencate Changes were merged into develop this morning, if you grab the latest you should be able to confirm that bitfinex importing is working.
