### ISSUE TITLE
Place market making orders (a.k.a. limit, i.e. strategically priced) to duck trading fees

### ISSUE THREAD

**Issue by pelletencate** [askmike/gekko#919]
A lot of exchanges have maker/taker fees, where the maker fees are usually much lower than the taker fees, sometimes they're even 0%. I found that if you place an order a fraction above or below (depending if it's short or long) the bid price, usually they get filled instantly, while still being able to benefit from lower market fees.

I think Gekko's portfolio manager should be able to do this. Since the taker fees are usually not lower than 0.2%, the costs can add up quite quickly.

**Comment by askmike** [comment]
The (new version of the) portfolio Manager is supposed to set trades on your side of the book, meaning that if your strat signals short the portfolio manager would place an ask at the same price as the current top ask. Advantages are:

- you'll pay maker fees
- you don't cross the spread (and also no slippage)

While disadvantages being slow execution and ordering against the trend.

----

> I found that if you place an order a fraction above or below (depending if it's short or long) the bid price, usually they get filled instantly

Do you mean that if your strat signals sell, you should place an ask one cent below the best bid? This would impact trade price since you cross the spread (but also means faster execution).

**Comment by thegamecat** [comment]
I guess there could be a setting variable of +/- % buy and sell prices vs spread bid and ask.

**Comment by pelletencate** [comment]
@askmike Wait, did you mean to say that that's the behaviour of the code that's currently in `master`? Then I misread the source code in the portfolio manager, my bad. :-)

I am by no means an expert, so I want to hear your opinions about the following thought. I think for algo trading, if you do cross the spread and bid/ask just the smallest amount below the market rate, I think the following happens:

* Pro: super fast execution, basically you get in on the first deal against the trend.
* Pro: no slippage, provided somebody trades against the trend.
* Pro: immediate killing the competition of aggressive bots that try to make an advantage of the spread
* Pro: you don't have to be aggressive yourself on super-fast order book polling and order adjustments
* Cons: worse price, but depending on the spread, which is usually quite low due to previously mentioned aggressive market maker bots.

So, I haven't studied the Gekko source code quite enough, but it seems to me that taking advantage of the spread requires multiple order book updates and order adjustments per second. 

What do you guys think?

**Comment by thegamecat** [comment]
I actually think that we collectively need to come up with a list of requirements for this, then buying/selling strategy needs to be coded as configurable.

There are trading strategies that rely on different approaches to buying and selling, indeed it is clear some people use Gekko to trade based on one minute signals while others trade on much longer candles. 

In summary I don't believe there is a one size fits all approach; this is just my opinion.

As it happens I have just gone live with a new fully GAd strategy, so we will see how the new buy/sell works vs my own custom approach I have had live for a couple of months on the old code base.

**Comment by askmike** [comment]
> Wait, did you mean to say that that's the behaviour of the code that's currently in master? Then I misread the source code in the portfolio manager, my bad. :-)

So currently in master is not exactly what you propose: you propose crossing the spread (in case of buying go 1 cent under the top ask), currently Gekko (in case of buying) places an order on the highest top bid. You are right about the pros, but another con is that if by the time your order goes through the orderbook has changed (in my experience on Kraken it takes on average ~10 seconds between you placing an order, and the order being executed).

> So, I haven't studied the Gekko source code quite enough, but it seems to me that taking advantage of the spread requires multiple order book updates and order adjustments per second.

When Gekko receives a buy/sell signal right now, it checks the orderbook and immediately places an order. If then checks back in 40 seconds whether it was taken (in full), if not it will redo the process.

----

> I guess there could be a setting variable of +/- % buy and sell prices vs spread bid and ask.

Good idea!

> I actually think that we collectively need to come up with a list of requirements for this, then buying/selling strategy needs to be coded as configurable.
> In summary I don't believe there is a one size fits all approach; this is just my opinion.

I was thinking something similar: a few different "trade modes", the current implementation is slow (in selling/buying) but very conservative (best price & most safe but also slowest). Maybe we can add different "modes" for the user to select:

- the option you propose (you lose the spread but gain speed).
- the option to do go fully into the top of the other side of the book (you take some and make the ramining, still no slippage).
- the option to do a market order (up to certain % of slippage).

What do you guys think?

**Comment by thegamecat** [comment]
I would prefer the % -+ either side of buy and sell individually personally as it has the maximum flex in it.

**Comment by askmike** [comment]
@thegamecat agreed that it is the most flexible, but it also requires the most understanding about markets & knowledge about this specific market (liquidity). A few different options (like `slow + cheap` VS `medium` VS `fast + expensive`) would allow Gekko to figure this out whenever it needs to do a trade. This way you're not stuck with the initial setting should liquidity change during crashes when market makers pull out / months of the market developing.

**Comment by thegamecat** [comment]
That's true, but then the strategy should identify the crash and could set the buy/sell %+- accordingly.

**Comment by dlasher** [comment]
+1 need this idea.

**Comment by vicmarto** [comment]
This would be wonderful, please askmike...

**Comment by askmike** [comment]
@vicmarto this is already how Gekko has worked for months.
