### ISSUE TITLE
[Idea] Update local dataset with newer data

### ISSUE THREAD

**Issue by metachris** [askmike/gekko#921]
It would be great if we could simply update an existing dataset with new data (until now). Is there anything for this / what are you using? I couldn't find anything in the docs.

**Comment by pelletencate** [comment]
I'm not 100% sure, but in my experience it seems the importer takes care of this, simply select the date range from whenever your last registered trade was (or a few minutes/hours before that time) and the current time, and the importer glues them together into one set, removing the duplicates.

**Comment by askmike** [comment]
>  simply select the date range from whenever your last registered trade was (or a few minutes/hours before that time) 

Exactly, but for now you'd have to do this manually. I think @metachris wants a button that automatically checks the available data and fills it with new data, right?

**Comment by metachris** [comment]
Oh alright! Thanks for the answers -- I had no idea that the importer already does this. Perhaps this would be good additional info in the downloader. Also a button to check and fill the data would be nice! ;)

**Comment by askmike** [comment]
> Perhaps this would be good additional info in the downloader.

Definitely, we can:

- improve these docs: https://gekko.wizb.it/docs/features/importing.html
- link to these docs in the importer screen.

**Comment by askmike** [comment]
I am open for a PR for this, but myself I am too busy. This can actually be fully build in the UI (in maybe 25 LoC):

- in the list of datasets, if data is older than 1 day add a button to "sync to now" (or whatever)
- when you click the button, create a new import based on market of that item.

**Comment by Nickduino** [comment]
That would be a nice feature.
