### ISSUE TITLE
Install trouble, Windows 10

### ISSUE THREAD

**Issue by QuadAlpha** [askmike/gekko#932]
Installed nodejs already, getting this error when installing gekko:

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@3.1.9 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.1.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by askmike** [comment]
Could you post the version of node and npm installed?

**Comment by QuadAlpha** [comment]
Installed x64 version, v6.11.2 (includes npm 3.10.10)

**Comment by askmike** [comment]
Can you manually run this and let me know what happens:

    npm install sqlite3@3.1.9

**Comment by askmike** [comment]
In #939 the user with the same problem was able to solve it by running: 

    npm install --global --production windows-build-tools

Let me know if that works.

**Comment by QuadAlpha** [comment]
Getting errors in NPM; going to do a full removal and re-install of nodejs:

Error: Cannot find module 'C:\Program
Files\nodejs\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by QuadAlpha** [comment]
Fully removed nodejs and re-installed, that fixed the issue and was able to install Gekko.  THANKS MIKE!
