### ISSUE TITLE
Poloniex CCI Live Trading active but no Trades

### ISSUE THREAD

**Issue by dark0ni** [askmike/gekko#938]
Hello,

first of all thank you for the great software. I have following Problem:

I connected gekko with poloniex and created a live trader with CCI for USDT <> XRP, all with the UI.

API:
key: XXXXXXXX-XXXXXXXX-XXXXXXXX-XXXXXXXX
secret: long hash

Settings are set with the UI: 

CCI
{
    "constant": 0.015,
    "history": 90,
    "thresholds": {
        "up": 90,
        "down": -130,
        "persistence": 0
    }
}

Gekko created successful a Strat Runner and a Market Watcher.
Backtesting work without Problem.

I have additional Questions:

1. When I use the gekko UI is the config.js required and also the agreement Use = true? I found nothing in Documentation and github.
1.1. When I use the live trader with UI, is an additional configuration required? When yes there i can find a explanation to configure the trader with the UI?
2. When I add the API Key for Poloniex, must I generate a public key or ist the key format above correct?

Thanks for your future help.

**Comment by askmike** [comment]
> When I use the gekko UI is the config.js required and also the agreement Use = true? I found nothing in Documentation and github.

You can fully ignore the config.js file when working with the UI. Setting the agreement to true is currently not needed, but will be in the next version (there will be a popup in the UI).

> When I add the API Key for Poloniex, must I generate a public key or ist the key format above correct?

The above format looks correct to me, so if you add that to the config page you should be good. I am also thinking about adding a small button on the config page where you can "test" your credentials.

**Comment by askmike** [comment]
What is the problem with the live trader?

**Comment by dark0ni** [comment]
@askmike  the live trader dont trade, the amount of trades is still zero and the terminal shows only that he gets the candles.

![screenshot_gekko](https://user-images.githubusercontent.com/4546899/29107573-131aba86-7cdb-11e7-87fd-71e4a4c45386.png)

**Comment by askmike** [comment]
If you run a separate backtest with the same setting settings (and candle size), does Gekko trade in that backtest? Maybe there has not been a buy or sell signal yet?

**Comment by dark0ni** [comment]
@askmike Perhaps thats the problem, I just let it keep running over 1 week and then give you feedback. The backtest runs fine with that options on the poloniex data. It buys or sell nearly daily with that options.

![screenshot_gekko_2](https://user-images.githubusercontent.com/4546899/29119023-c16736e0-7d04-11e7-9de0-afeeece79e1f.png)

**Comment by dark0ni** [comment]
@askmike thank you for helping and answering some of my questions. The buy signal taked longer when backtest buy signals.

**Comment by askmike** [comment]
ah yes! I will write some docs on current order execution. But the live trader will try to get a good deal, this might take a while.

**Comment by askmike** [comment]
See #919 for a discussion about details of the current strategy and different strategies that might make it in a future version of Gekko.
