### ISSUE TITLE
Processes crash (child and main) when running multiple watchers and papertraders.

### ISSUE THREAD

**Issue by Lafunamor** [askmike/gekko#940]
Hey there
I'm running two wathers (kraken EUR/XBT and kraken EUR/ETH) and 4 DEMA strategies (two on each watcher).
This ran fine for a couple of hours but then suddenly the two watcher child processes died. Soon after I started new watchers the main process died as well.
Sadly I have no logs for that period. I've now started the process again and I'm redirecting the stdout to a file to get some more information. Do you have experienced a similar behavior or do you have any tips to get meaningful logs?

**Comment by askmike** [comment]
> This ran fine for a couple of hours but then suddenly the two watcher child processes died

In the next version I will simply restart the watchers when they die (they don not effect the strat runners).

>  Soon after I started new watchers the main process died as well.

Would love to see logs for this.

> Do you have experienced a similar behavior or do you have any tips to get meaningful logs?

For keeping track of logs I would suggest either using screen or [pm2](https://github.com/Unitech/pm2)!

**Comment by askmike** [comment]
There is a discussion around adding more logging to each individual gekko when using the UI. I am closing this in favor of that issue: #972.
