### ISSUE TITLE
Data and live Grkos lost on crash/restart

### ISSUE THREAD

**Issue by Lafunamor** [askmike/gekko#941]
When I restart the app using CTRL + C to exit and `node gekko --ui` to start it again I loos all ,y previously started Gekkos and data. Is this an expected behavior?

**Comment by askmike** [comment]
This will be added in the next release, see #906 and #911.

**Comment by Lafunamor** [comment]
aaah thanks, sorry for the duplicate.

**Comment by askmike** [comment]
No problem :)
