### ISSUE TITLE
Poloniex trading bot posts 99% roundtrip loss from 1970-01-01 00:00

### ISSUE THREAD

**Issue by markanderson** [askmike/gekko#942]
I've been seeing some strange behavior with Poloniex trading bots where the bot will finish with an entry and exit date of 1970-01-01 00:00 and subsequently close out. Is this a known issue?

```
Entry at | Exit at | Exposure | Entry balance | Exit balance | P&L | Profit
-- | -- | -- | -- | -- | -- | --
2017-08-09 12:15 | 2017-08-09 13:57 | 2 hours | 0.409 | 0.425 | 0.016 | 3.885
1970-01-01 00:00 | 1970-01-01 00:00 | a few seconds | 0.417 | 0.000 | -0.417 | -99.988
```

## Context
* Indicator: CCI
* Candle size: 2 minutes
* Using the stable branch on an AWS Linux EC2 instance

## Other strange behavior
* 7 trades have been made, however only 2 roundtrips have been calculated (should there be 6? )
* Starting balance is reported to be 0

<img width="419" alt="screen shot 2017-08-09 at 9 12 12 pm" src="https://user-images.githubusercontent.com/1906643/29154180-74dffa94-7d47-11e7-819d-579c1bd9a8b7.png">

<img width="1679" alt="screen shot 2017-08-09 at 8 44 49 pm" src="https://user-images.githubusercontent.com/1906643/29153669-a43c5cf0-7d43-11e7-8648-1ee13151d992.png">

**Comment by askmike** [comment]
Never seen this before no, will debug!

**Comment by ghost** [comment]
Dont know if its related, but I am seeing something similar in the console  

> (ROUNDTRIP) entry date          exit date               exposed duration P&L                 profit
/root/gekko/plugins/performanceAnalyzer/logger.js:52
    rt.entryAt.format('YYYY-MM-DD HH:mm'),
              ^

TypeError: Cannot read property 'format' of undefined

**Comment by askmike** [comment]
@markanderson 

> Starting balance is reported to be 0

This is a live trading bot? How much [currency] was in the account? Also: are you (or any other) trading on the same account at the same time as gekko is running?

@Beaconsilver are you running over the commandline? In that case yes they appear to be related.

**Comment by ghost** [comment]
I am running over the command line.

**Comment by askmike** [comment]
And are you running a live trader or paper trader?

**Comment by ghost** [comment]
I am running live, and from what I can tell I am not getting this problem from paper trading.

**Comment by askmike** [comment]
also poloniex?

**Comment by ghost** [comment]
Yes

**Comment by markanderson** [comment]
@askmike 

The live trading bot was made via the UI with a starting balance of 0.4 ETH. I had also tried an earlier bot with the same indicator settings and exchange, that time with 6 ETH and ran into the same issue with seeing 1970-01-01 00:00 (unfortunately, i killed my docker instances and lost the history on that).

Also, it has only been me trading on the account with only one bot running at any given time.

Thank you for looking into this!

**Comment by sheerlox** [comment]
This is unrelated to the topic
@Beaconsilver I think you shouldn't run Gekko as `root`, as you should never run any software as `root` ... In example Apache and others will run under their dedicated users without `sudo` rights for security purposes :smile:

**Comment by ghost** [comment]
@SherlockStd Thanks for the concern, and you are not wrong. Never run applications under root. But that server gets a format at least once a week.

**Comment by danKHUU** [comment]
I am also getting the same entry date: 1970-01-01. Running live trading bot via UI.

![image](https://user-images.githubusercontent.com/30988992/29254029-89f5ddfa-80cf-11e7-96f2-d69f5a4f51bc.png)

**Comment by ghost** [comment]
This appears to be from Poloniex side. It sometimes returns "0" for all values when the price is deep into the double precision's

**Comment by mronus** [comment]
The similar issue exists in binance as well. All entry exit date formats are broken.
![image](https://user-images.githubusercontent.com/2014677/34905663-b0f2258c-f86e-11e7-98c8-967516c4b986.png)

**Comment by ghost** [comment]
I had the same issue on Binance with a scary 99.9% (fake) loss through the web UI, luckily this didn't happen.
I also noted those errors in the log, there are a lot of it:

`(ERROR):	[binance.js] (cancelOrder) returned an irrecoverable error: Error: Response code 400`
`(DEBUG):	[binance.js] entering "cancelOrder" callback after api call, err [binance.js] Response code 400 data: {"code":-2011,"msg":"UNKNOWN_ORDER"}`
`(DEBUG):	[binance.js] entering "getOrder" callback after api call, err null data: {"` it has some data inside
`(DEBUG):	[binance.js] entering "getTicker" callback after api call, err: null data: 274 symbols`
