### ISSUE TITLE
Postgresql connection in Docker containers not working

### ISSUE THREAD

**Issue by cassvail** [askmike/gekko#946]
I set up a docker-compose environment with gekko (original build image) and a postgresql-9.6 container.
The gekko container is linked to the postgresql container.
Edited the /web/vue/UIconfig.js to:
`adapter: 'postgresql'`
Edited the config.js file with the postgresql configuration:
```
config.adapter = 'postgresql';
...
config.postgresql = {
  path: 'plugins/postgresql',
  version: 0.1,
  connectionString: 'postgres://username:password@postgresql:5432', // if default port
  database: 'gek', // if set, we'll put all tables into a single database.
  schema: 'public',
  dependencies: [{
    module: 'pg',
    version: '6.1.0'
  }]
}
```
(Notice that @postgresql in docker is the linked host name)

The Web UI is running correctly but as soon as I interact with the database (i.e. clicking on "scan available data") I get this error:
```
Gekko encountered an error and can't continue

Error:

{ Error: connect ECONNREFUSED 127.0.0.1:5432
    at Object.exports._errnoException (util.js:1012:11)
    at exports._exceptionWithHostPort (util.js:1035:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432 } '\n\n'

Meta debug info:

Gekko version: v0.5.2
Nodejs version: v6.3.1


npm info lifecycle gekko@0.5.2~start: Failed to exec start script
npm ERR! Linux 4.9.36-moby
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! gekko@0.5.2 start: `node ./gekko --config config.js --ui`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gekko@0.5.2 start script 'node ./gekko --config config.js --ui'.
```

The connection host "127.0.0.1:5432" is obviously uncorrect, because it shoud use the Docker-compose link instead of localhost 127.0.0.1. 
Is this a bug or there's some other configuration needed in order to have Postgresql running?

**Comment by cassvail** [comment]
Just added a PR #947 which adds postgresql to docker-compose config file. Could be useful to debug this issue and to have available in general

**Comment by askmike** [comment]
Under the hood Gekko uses configs for all functionality. All configs build by the UI are dynamically build with this as the baseConfig: https://github.com/askmike/gekko/blob/stable/web/routes/baseConfig.js

- You can see on line 36 that this is initialized with the adapter set in the UIConfig.
- Line 54 has your problem, it sets the postgre server to localhost.

----

A workaround is editing that file, better would be allowing this to be set in the UIConfig file.

**Comment by cassvail** [comment]
I tested the baseConfig.js and it works fine.
I added a couple of commits to the PR to properly build Dockerfile for pg support

* To run postgresql, it's needed to add the module "pg" in the package.json, but if the default config is sqlite, I don't know you want to that or not 
Postgresql is a far greater solution than sqlite. Sqlite crashed for db locks a few times while running multiple imports. However sqlite it's immediate setup as is, but with docker you have an immediate setup of postgresql too

**Comment by askmike** [comment]
> I don't know you want to that or not Postgresql is a far greater solution than sqlite. Sqlite crashed for db locks a few times while running multiple imports. However sqlite it's immediate setup as is, but with docker you have an immediate setup of postgresql too

You are 100% right, I also think postgresql is a better database. The main reason for sqlite is that npm can install it and doesn't need to be managed outside a node process. This changes "installing Gekko" from: "First install this specific version of postgreSQL and than configure the IP and credentials in this config file - after that run npm install" to: "run npm install".

So for that reason sqlite is added to package.json whilst pg is not (it's de default). In case of a docker setup if sqlite could be removed from the package.json that would be great :)

**Comment by cassvail** [comment]
Yeah! instead of "npm install & npm run" the command would be "docker-compose up", of course docker must be installed on the machine, but it's a matter of choice here.
I think the issue itself could be closed ;)

**Comment by askmike** [comment]
Ah yes, with docker it wouldn't be that hard. Though I don't dare running that on windows (which is a supported platform for Gekko).
