### ISSUE TITLE
Advice logger / writer

### ISSUE THREAD

**Issue by sheerlox** [askmike/gekko#948]
Hi Mike !

I don't understand well the advice logger / writter.
```javascript
config.adviceLogger = {
  enabled: true,
  muteSoft: false // disable advice printout if it's soft
}

config.adviceWriter = {
  enabled: true,
  muteSoft: false,
}
```

I suppose the `adviceWritter` is same as `candleWriter`, it saves advices to db.
But there is the `muteSoft` option, should I put `true` or `false` to enable advice printout on `adviceLogger`, and what does it do on `adviceWritter` ?

Thanks in advance,
Sherlock

**Comment by askmike** [comment]
The adviceWriter was never (publicly) added to Gekko, we need to update the sample-config to remove this section, as there is no plugin that will actually be started.

Soft advice was part of a very old interface that let strategies broadcast repeated signals, it is not recommended to soft advice from strats anymore. Safest is to put that to true, but it should not matter.

**Comment by sheerlox** [comment]
I activated adviceWriter soon and it was writing advices to db is that normal ?

**Comment by askmike** [comment]
I don't think it should be no. Could you give more information?

- What DB? Mongo?
- screenshot or DB output of the advices stored in DB
- What gekko mode?

**Comment by sheerlox** [comment]
- Yes MongoDB
- I deleted the Mongo collection ... Next time I got some I'll do
- Gekko Live

Collection name's `poloniex_advices`.

**Comment by sheerlox** [comment]
@askmike 
Console:
```
2017-08-13 16:18:09 (DEBUG):	Writing advice 'short' to database.

2017-08-13 16:18:09 (INFO):	We have new trading advice!
2017-08-13 16:18:09 (INFO):		 Position: short
2017-08-13 16:18:09 (INFO):		 Market price: 0.0005323
2017-08-13 16:18:09 (INFO):		 Based on market time: 2017-08-13 16:17:00
```
BSON Object in Mongo:
```
{
  "_id": ObjectId("59907bc134d4e03152a241cf"),
  "time": {
    ...
    "_d": ISODate("2017-08-13T16:18:09.086Z"),
    ...
  },
  "marketTime": {
    ...
    "_d": ISODate("2017-08-13T16:17:00Z"),
    ...
  },
  "pair": "BTC_LSK",
  "recommendation": "short",
  "price": 0.0005323,
  "portfolio": 1
}
```

**Comment by askmike** [comment]
do you have still have logs of gekko starting?

**Comment by sheerlox** [comment]
```
2017-08-13 16:13:03 (INFO):	Setting up Gekko in realtime mode
2017-08-13 16:13:03 (INFO):	
2017-08-13 16:13:03 (INFO):	Setting up:
2017-08-13 16:13:03 (INFO):		 Candle writer
2017-08-13 16:13:03 (INFO):		 Store candles in a database
2017-08-13 16:13:03 (DEBUG):	Enabling adviceWriter.
2017-08-13 16:13:03 (DEBUG):	Enabling candleWriter.
```

**Comment by askmike** [comment]
so no output for besides:

> 2017-08-13 16:13:03 (DEBUG):	Enabling adviceWriter.

strange, I will debug later. You are running latest stable?

**Comment by sheerlox** [comment]
yep
