### ISSUE TITLE
Changing configuration with docker

### ISSUE THREAD

**Issue by arnold-maderthaner** [askmike/gekko#957]
Hi !

I just started to experiment with gekko and launched it using docker on my ubuntu 16.04 NAS. How can I adjust now the configuration (except those which are done using the web interface) ?

thanks for your help! 

yours

arnold

**Comment by askmike** [comment]
Hey, what specific settings did you have in mind? The UI allows you to configure all the strategy settings and such without touching a configuration file.

There is a PR open for adding postgresql to the docker files, see #947.

**Comment by arnold-maderthaner** [comment]
how can I configure gekko as an autotrade bot without touching the config file ?

yours

Arnold

Am 13. Aug. 2017, 17:17 +0200 schrieb Mike van Rossum <notifications@github.com>:

**Comment by askmike** [comment]
First you install Gekko as explained here: https://gekko.wizb.it/docs/installation/installing_gekko.html

After that start the UI, go to live gekkos, configure it how you want it (in the UI) and click "tradebot"!

**Comment by arnold-maderthaner** [comment]
ok - I have now a tradebot - but how can I delete it again ?

**Comment by askmike** [comment]
As in stop the bot? Will be part of the next release, see here: #911!

**Comment by arnold-maderthaner** [comment]
yes stopping the bot so that I can configure a new one. thats why I asked where to modify config files. also how does the hot decide which amount he is tradibg with ?

sorry for maybe dumb questions

yours

Arnold

Am 13. Aug. 2017, 22:13 +0200 schrieb Mike van Rossum <notifications@github.com>:

**Comment by askmike** [comment]
Gekko will always use the full balance available!
