### ISSUE TITLE
Minimum date for UI-based import

### ISSUE THREAD

**Issue by alienss** [askmike/gekko#960]
Hey, 

Is there any way to check and display what is the earliest date for an import for a given exchange? I tried running on poloniex since 2011, got some weird errors. I'd simply like to backtest against all available data.

Cheers!

**Comment by askmike** [comment]
Hey,

This information is not really exposed via the API, so there is no way for Gekko to know.. What you could do is go to the exchange websites and zoom the charts out to as far as you can go!

Note that Gekko expects all dates in UTC.
