### ISSUE TITLE
Haven't been able to get anything working yet.

### ISSUE THREAD

**Issue by Ruthless21** [askmike/gekko#962]
<-- GET /api/imports
  --> GET /api/imports 200 8ms 2b
  <-- GET /api/gekkos
  --> GET /api/gekkos 200 2ms 2b
  <-- GET /api/apiKeys
  --> GET /api/apiKeys 200 5ms 12b
  <-- GET /api/exchanges
  <-- GET /api/gekkos
  --> GET /api/gekkos 200 2ms 2b
  --> GET /api/exchanges 200 1,178ms 31.39kb
  <-- GET /api/configPart/candleWriter
  <-- GET /api/configPart/performanceAnalyzer
  <-- GET /api/strategies
  --> GET /api/configPart/candleWriter 200 9ms 47b
  --> GET /api/configPart/performanceAnalyzer 200 8ms 144b
  <-- GET /api/configPart/paperTrader
  --> GET /api/configPart/paperTrader 200 2ms 88b
  --> GET /api/strategies 200 23ms 1.49kb
  <-- POST /api/startGekko
Gekko 7493007174526274 started
  --> POST /api/startGekko 200 15ms 149b
  <-- POST /api/startGekko
Gekko 332391733728556 started
  --> POST /api/startGekko 200 7ms 417b
RECEIVED ERROR IN GEKKO 332391733728556

Gekko encountered an error and can't continue

Gekko encountered an error and can't continue

Error:

Gekko was unable to set the portfolio

Meta debug info:

Gekko version: v0.5.2
Nodejs version: v6.11.2

**Comment by Ruthless21** [comment]
I realize this is most likely just me having missed something obvious and not an issue with your software but if you could refer me to a good source that could walk me through setting this up it would be great.

**Comment by gweedobtc** [comment]
Sounds like the api keys are not configured correctly in the config tab or on the exchange.

**Comment by Ruthless21** [comment]
Thank you for responding but I double checked my poloniex api key, I don't think its that. I think it has to do with the USDT currency option because when I tried doing BTC/XMR it worked fine.

**Comment by askmike** [comment]
> Gekko was unable to set the portfolio

Most likely means a problem with your API keys. I would suggest removing them in the config panel and create fresh ones on poloniex and adding those.

----

Note that it is advised to first dry run Gekko (backtest - paper trade) before you actually trade for real.

**Comment by Ruthless21** [comment]
alright I will try again

**Comment by askmike** [comment]
I assume this is an API issue since a lot of people are running polo without problems, if you still can't get it working please comment here.
