### ISSUE TITLE
Running gekko on aws but cant connect to gekko home page

### ISSUE THREAD

**Issue by ergunpp** [askmike/gekko#967]
Hi,
I have installed node and gekko on ec2 instance. But I can not open gekko home page when I go to the address of gekko server on web browser.

When I run gekko with node gekko -uui I get a message like this:

TAlib is disabled
Serving Gekko UI on http://localhost:3000/

(node:29550) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Exited with code 3
(node:29550) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Appreciate prompt help.
Thanks,

**Comment by gweedobtc** [comment]
Hi @ergunpp,

Try setting in this file https://github.com/askmike/gekko/blob/58e622d50ea9353ffa86bb615f1b607c6c9c5373/.env

the localhost to 0.0.0.0

That should help.

**Comment by ergunpp** [comment]
Thank you very much.  Where is the file after installation? which folder? The name of the file?

**Comment by gweedobtc** [comment]
It is the same folder you run node gekko --ui, it is .env

just do like nano .env and you should be able to edit it.

**Comment by ergunpp** [comment]
I have done as you directed, changed .env localhost to 0.0.0.0 and checked it twice.
But when I start node gekko --ui ,it says "Serving Gekko UI on http://localhost:3000/"

Is there any other setting?

**Comment by gweedobtc** [comment]
It looks like you already have to do here as well https://github.com/askmike/gekko/blob/53ffdf33faaec273c9725490228f081499341e5c/web/vue/UIconfig.js

**Comment by askmike** [comment]
Hey @gweedobtc you should ignore that .env file.

@ergunpp if you want to host Gekko please follow the instructions (and edit the UIConfig.js) as followed here: https://gekko.wizb.it/docs/installation/installing_gekko_on_a_server.html#Configuring-Gekko-to-run-in-the-cloud

> (node:29550) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Exited with code 3

That warning is caused by not configuring headless to true. in the UIConfig

---

Feel free to ask questions :)

**Comment by ergunpp** [comment]
Thank you.
If i set the host for api in UIconfig js to '0.0.0.0' instead of 127.0.0.1, the home page is displayed but immediately after that follows the error: "Disconnected
Something happened to either Gekko or the connection. Please check the terminal where Gekko is running or your network connection."

If i leave it as it is (127.0.0.1) connection is refused when opening the page.

Now one problem seems to be solved, but why does it get "disconnected" immediately after displaying the page?

**Comment by askmike** [comment]
That means the UI cannot setup a websockets connection with gekko. Could
you post the UIconfig and info about your server?

**Comment by ergunpp** [comment]
// This config is used in both the
// frontend as well as the web server.

// see https://github.com/askmike/gekko/blob/stable/docs/installing_gekko_on_a_server.md

const CONFIG = {
  headless: true,
  api: {
    host: '0.0.0.0',
    port: 3000,
  },
  ui: {
    ssl: false,
    host: '0.0.0.0',
    port: 3000,
    path: '/'
  },
  adapter: 'sqlite'
}

if(typeof window === 'undefined')
  module.exports = CONFIG;
else
  window.CONFIG = CONFIG;

**Comment by roneetshaw** [comment]
Hi @ergunpp 
I am also facing the same issue. The UI is accessible but immediately it disconnnects, where you able to find the solution?

**Comment by askmike** [comment]
@ergunpp and @roneetshaw you need to configure the UIConfig to point to your server, the UIConfig posted 2 comments above will not work since  the host (for both UI and api) is set to `0.0.0.0` which points to your local machine. Set this to the IP address or domain of your server.

**Comment by askmike** [comment]
And set the port to 3000 for the host. Also set it to 3000 for the UI if you are not upstreaming (via nginx). Set it to the public nginx port if you are using nginx. See the documentation for details:

https://gekko.wizb.it/docs/installation/installing_gekko_on_a_server.html

**Comment by roneetshaw** [comment]
@askmike the IP should be the IP which I connect using ssh or the physical IP of the AWS instance?

**Comment by askmike** [comment]
Not sure what you mean with physical IP. But if you have an IP you can SSH into from home (from the public internet) that should work!

**Comment by roneetshaw** [comment]
Thank you so much, It worked!

**Comment by roneetshaw** [comment]
If I have to add some authentication so that not everyone can access the link? Is there any way to do so?

**Comment by antonrifco** [comment]
make sure you set the following UIConfig.js in vi web/vue/UIconfig.js 

const CONFIG = {
    headless: true,
    api: {
        host: '127.0.0.1',
        port: 3000,
    },
    ui: {
        ssl: true,
        host: '<change to your domain>',
        port: 443,
        path: '/' // change this if you are serving from something like `example.com/gekko`
    },
    adapter: 'sqlite'
}

**Comment by ricksternyc** [comment]
Hello, 

Running in circles here with varying results, at the point where I've lost track of what was almost working and not working at all. 

Following instructions here.....
https://gekko.wizb.it/docs/installation/installing_gekko_on_a_server.html#configuring-gekko-to-run-in-the-cloud

cd gekko/web/vue  
vi UIconfig.js

`CONFIG = {
    headless: true,
    api: {
        host: 'xx.xx.xx.xx', // Using IPv4 Public IP from AWS EC2, correct?
        port: 3000,
    },
    ui: {
        ssl: true,
        host: 'gekko.example.com',
        port: 443,
        path: '/' // change this if you are serving from something like `example.com/gekko`
    },
    adapter: 'sqlite'
}

if(typeof window === 'undefined')
  module.exports = CONFIG;
else
  window.CONFIG = CONFIG;
`
**nginx/sites-enabled 
sudo vi default**

`server {
    listen 80;
    listen [::]:80;
    server_name gekko.example.com;
    return 301 https://$server_name$request_uri;
}

upstream websocket {
    server localhost:3000;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    root /var/www/html;

    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;

    location / {
            proxy_buffers 8 32k;
            proxy_buffer_size 64k;
`

running from gekko directory 'node gekko --ui'

`
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRNOTAVAIL xx.xx.xx.xx:3000 //again using IPv4 Public IP from EC2
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at Server.setupListenHandle [as _listen2] (net.js:1243:19)
    at listenInCluster (net.js:1307:12)
    at doListen (net.js:1432:7)
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
`


I previously had it working to the point where it said "Serving on gekko.example.com:443" 
tried localhost in place, that didn't work. At the point where I give up, lol, any advice? Thanks!

**Comment by ricksternyc** [comment]
Hello,

Running in circles here with varying results, at the point where I've lost track of what was almost working and not working at all.

Following instructions here.....
https://gekko.wizb.it/docs/installation/installing_gekko_on_a_server.html#configuring-gekko-to-run-in-the-cloud

**cd gekko/web/vue
vi UIconfig.js**


CONFIG = {
    headless: true,
    api: {
        host: 'xx.xx.xx.xx', // Using IPv4 Public IP from AWS EC2 
        port: 3000,
    },
    ui: {
        ssl: true,
        host: 'gekko.example.com',
        port: 443,
        path: '/' // change this if you are serving from something like `example.com/gekko`
    },
    adapter: 'sqlite'
}
//this bit not in the installation docs, but read in previous thread it should be included?
if(typeof window === 'undefined')
  module.exports = CONFIG;
else
  window.CONFIG = CONFIG;


**nginx/sites-enabled
sudo vi default**

server {
listen 80;
listen [::]:80;
server_name gekko.example.com;
return 301 https://$server_name$request_uri;
}

upstream websocket {
server localhost:3000;
}

server {
listen 443 ssl;
listen [::]:443 ssl;
root /var/www/html;

ssl_certificate /etc/nginx/ssl/nginx.crt;
ssl_certificate_key /etc/nginx/ssl/nginx.key;

location / {
        proxy_buffers 8 32k;
        proxy_buffer_size 64k;


**running from gekko directory 'node gekko --ui**

Result:

events.js:163
throw er; // Unhandled 'error' event
^

Error: listen EADDRNOTAVAIL xx.xx.xx.xx:3000 //again using IPv4 Public IP from EC2
at Object.exports._errnoException (util.js:1050:11)
at exports._exceptionWithHostPort (util.js:1073:20)
at Server.setupListenHandle [as _listen2] (net.js:1243:19)
at listenInCluster (net.js:1307:12)
at doListen (net.js:1432:7)
at _combinedTickCallback (internal/process/next_tick.js:83:11)
at process._tickCallback (internal/process/next_tick.js:104:9)
at Module.runMain (module.js:607:11)
at run (bootstrap_node.js:427:7)
at startup (bootstrap_node.js:151:9)
at bootstrap_node.js:542:3


I previously had it working to the point where it said "Serving on gekko.example.com:443"
tried localhost in place, that didn't work. At the point where I give up, lol, any advice? Thanks!

**Comment by netcoding** [comment]
@All,

at me it was the ssh-config(Forwarding Port). 
if you define another port as default("3000"), i.e. port("3123") and you hast define in the UI-Config Port("3000"), then fails, because the WebSocket can NOT reached Port("3000"), because you has define SSH-LocalForward Port("3123").

That was my Problem and i must switch back to normal Forwarding-Port("3000")   ;-)
