### ISSUE TITLE
BCH support

### ISSUE THREAD

**Issue by bcoufal** [askmike/gekko#969]
Is BCH support planed?

**Comment by askmike** [comment]
Do you have a specific exchange in mind? It wouldn't be hard to add in Gekko :)

**Comment by bcoufal** [comment]
Poloniex?

**Comment by askmike** [comment]
It just got added to the development branch (see here #971), you can download that version of gekko here: https://github.com/askmike/gekko/tree/develop

It will automatically be part of the next Gekko release.
