### ISSUE TITLE
API / GA: write outputs for debugging

### ISSUE THREAD

**Issue by thegamecat** [askmike/gekko#970]
I'm currently experiencing econnreset issues using the API. I think its something I've done but I need to do some debugging - which needs to start with the output results produced by Logger.js. However I cant seem to trigger any outputs from it. Any ideas?

**Comment by askmike** [comment]
The Logger.js is only used when running a CLI gekko, not when running through the UI (or REST API).

**Comment by askmike** [comment]
The logger is meant to display stats in the commandline (which shouldn't be used when using the UI or the REST interface). I just proposed a new plugin that stores roundtrips in CSV: #978 

Let's move the discussion there!

**Comment by thegamecat** [comment]
Not relevant but for your interest: I fixed the problem by adding a connection: close to the GA  request header.
