### ISSUE TITLE
[FEATURE] Store logs of UI gekkos

### ISSUE THREAD

**Issue by GuyPaddock** [askmike/gekko#972]
I know that running via CLI dumps trade advice / debug info to standard out. But, where does this info go (if anywhere) when running in UI mode?

**Comment by askmike** [comment]
Gekko UI doesn't log the same data unfortunately. How would you like to see it work? If you run 3 gekkos through the UI the logs would all be messed up.

**Comment by GuyPaddock** [comment]
Hmmm. Well... when debugging an issue I'm seeing with the server while using the UI, it would still be great if I can enable logging temporarily, even if the logs would be very busy. Similar to how you can turn on debug logging for CLI, it'd be great to have an option to toggle it on. If I happen to be stupid and run multiple Gekkos through the UI, that's on me.

**Comment by GuyPaddock** [comment]
Alternatively, what if a new log _file_ was generated for each Gekko?

**Comment by thegamecat** [comment]
This is largely why I write backtests and live buy/sells to my own csvs. 

I would be attaching a session id to each gekko and either running a different log file for each session, or one log which each activity identified as a session.

**Comment by askmike** [comment]
More people have been asking for this, we can add logging. What about this?

- We don't allow logging whilst backtesting in the UI
- When starting a live gekko there is an advanced section where people can toggle on "log-debug-output-to-file"?

Though some plugins (like the performance analyzer) either log to stdout OR upstream to parent process, so we would have to change some stuff around.

**Comment by thegamecat** [comment]
I don't like this approach to not log backtests - it's actually causing me an issue here: https://github.com/askmike/gekko/issues/970

We should be writing logs for everything, maybe they go to a different folder for backtests but still, they should happen. 

For reference - I write all buy/sell/strategy outputs to a strategy_log folder, for example (rename to csv):

[test-all-1-poloniex-USDT-ETH-1502697116356.txt](https://github.com/askmike/gekko/files/1227640/test-all-1-poloniex-USDT-ETH-1502697116356.txt)



[test-all-1-poloniex-USDT-ETH-2017-08-14T07-51-56.384Z-roundtrips.txt](https://github.com/askmike/gekko/files/1227642/test-all-1-poloniex-USDT-ETH-2017-08-14T07-51-56.384Z-roundtrips.txt)

**Comment by askmike** [comment]
What about logging trade info to CSV regardless (also an advanced option)?
I see this as something different than logs.

**Comment by thegamecat** [comment]
Totally agree about trades being different to logs. 

What I use to eval when not using the GA is:

1) Trades / buys and sells, times, balance etc. 
2) Every single tick logged with indicator, price, buys and sells

**Comment by askmike** [comment]
Can you check out the develop branch? All logging for UI gekkos are stored in the `/logs` folder. Note that this not include trade and roundtrip information from the performanceAnalyzer (just from the portfolioManager) at the moment.

**Comment by GuyPaddock** [comment]
OMG @askmike you rock! I will definitely try this out.
