### ISSUE TITLE
[Question][Discussion] Wiki

### ISSUE THREAD

**Issue by deke997** [askmike/gekko#974]
Why aren't we using the [Wiki](https://github.com/askmike/gekko/wiki)? It seems like it would make managing docs a lot easier.

Any thoughts?

**Comment by askmike** [comment]
I want the least vendor lockin from github as possible, also rather point people to a documentation website than a github wiki (to make it as frictionless as possible - also for non developers).

For that reason all docs are stored in gekko/docs and [this repo](https://github.com/askmike/gekko.wizb.it) compiles all the docs into the website: https://gekko.wizb.it/
