### ISSUE TITLE
BitX/Luno support

### ISSUE THREAD

**Issue by mattcrafte** [askmike/gekko#976]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[ X] feature request
[ ] question about the decisions made in the repository

Hi,

I see in the doc that BitX (now Luno) is supposedly supported. I cannot however add the API for it. It is not in the list

**Comment by askmike** [comment]
Hey! 

Bitx was added on 12 aug 2015, I am not sure if it still works. That said you should be able to select it like this:

<img width="810" alt="screen shot 2017-08-16 at 14 12 32" src="https://user-images.githubusercontent.com/969743/29364937-1c3324e8-828d-11e7-891b-34734762a66c.png">

Is that not working for you? Note that I doubt it still works, if it doesn't please post the errors here :)

**Comment by jonathankretzmer** [comment]
Looks like Monitoring still works.  Perhaps @mattcrafte is asking for Live Trading support, that looks to never have been implemented.

**Comment by askmike** [comment]
Ah yes: This chart shows where Gekko can do live trading: https://gekko.wizb.it/docs/introduction/supported_exchanges.html

Unfortunately bitx is not one of them. If anyone wants to add support, simply follow this document:

https://gekko.wizb.it/docs/extending/add_an_exchange.html
