### ISSUE TITLE
Gekko UI live trader does not show trades

### ISSUE THREAD

**Issue by jwijmans** [askmike/gekko#982]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
I've started the UI live trader with a DEMA strategy running. I filled my Kraken API key in the config and see trades in the Kraken Dashboard. The issue is that in my Gekko UI it does not show any trade. It just says: "Waiting for at least one trade.."

I cannot find any debuging information in the console which could help, only message are posts of the candles.

Thanks for your support.

* **Expected result** (what you hoped would happen)
Show the trades in the Gekko UI

* **Actual result** (unexpected outcome)
Does not show the trades but executes them

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
Under most configurations Gekko only trades a few times a week. The strategies that come with Gekko are meant as examples. I am not sure if it's a good idea to run these for real money if you don't know how they are supposed to trade.

I suggest to first backtest and/or paper trade to get a sense of what is supposed to happen!

That said: We are working on improving the UI to better reflect what is happening at a live gekko, see #911 for details.

**Comment by jwijmans** [comment]
I did backtest the bot extensively. I wrote a script to automate my backtesting and gives me a top 5 of best parameters with my backtest. And indeed it will only trade when it meets the tresholds.

The issue is however that my running bot does not show any trade in it's status. But on my Kraken account I can see several trades done (in a time window of a week+). I now stopped the bot because I don't know what kind of error it gets in the background. I don't see this bug mentioned in the post you send me but hopefully will be fixed in your new version then. Thanks!

**Comment by askmike** [comment]
Ah! So the bug is that Gekko is trading but the trades are not showing up.

As for logs when running the UI, see #972. That should also provide more debug insight in what is happening.

----

What API key permissions does the API key have on kraken? Also can you provide maybe a screenshot of sorts with orders as seen on kraken (hide amounts and sensitive stuff).

**Comment by jwijmans** [comment]
Yes that is indeed the case. See attached two screenshots, one of the api settings and the other is a selection of my orderbook.
<img width="641" alt="kraken api settings" src="https://user-images.githubusercontent.com/29977182/29454770-b150e9ca-840e-11e7-8c11-0637f4cc9030.PNG">
<img width="721" alt="kraken orders" src="https://user-images.githubusercontent.com/29977182/29454778-b94bdda6-840e-11e7-9f71-79efe74bd359.PNG">

**Comment by askmike** [comment]
strange, I'd say the best way to go is work on #972 to add logging. Until than it's hard to figure out why the trades are not propagating..

**Comment by askmike** [comment]
#972 has landed in stable, if you download and run a new UI instance you'll have logs stored in the logs folder.

However I think it's highly likely that your issue is the same as #931 (except that since the UI didn't log, you are unable to see that error). If you have more information please comment here.

**Comment by glegarand** [comment]
Sorry to reopen this, but I have the same problem with the BTC/TRX pair on Binance. The web UI doesn't show any trade, but I can see them on the Binance app. Nothing related to the #931 ...
I only use the web UI and I have a paper trader on Binance BTC/TRX with the same parameters that shows the trades.

**Comment by ghost** [comment]
/gekko/logs/*tradebot.log shows me that Gekko do trade.
 
buy/sell back and forth but "profit" is still 0 in in webUI.

I run three strat runners and all of them have made trades in the logs and on the exchanges but webui show no trades happened, gekko still collects the market tho.

poloniex | USDT | BTC | 2018-04-18 20:48 | 5 hours, 39 minutes | RSI_BULL_BEAR | 0
kraken | USD | ETH | 2018-04-18 20:48 | 5 hours, 38 minutes | RSI_BULL_BEAR | 0
bitstamp | USD | XRP | 2018-04-18 20:49 | 5 hours, 38 minutes | RSI_BULL_BEAR | 0

Running on Raspberry Pi2
Linux raspberrypi 4.14.30-v7+ #1102 SMP Mon Mar 26 16:45:49 BST 2018 armv7l GNU/Linux

**Comment by zgwenwen** [comment]
same here, it does trade but UI is not showing.
Trading on Quadriga with strategy neuralnet_v2.
Please help, thank you
