### ISSUE TITLE
Can't open sqllite file

### ISSUE THREAD

**Issue by ergunpp** [askmike/gekko#983]
Hi,
I' getting this error:

SQLITE_CANTOPEN: unable to open database file
RECEIVED ERROR IN IMPORT 090215820292934
Child process has died.

I have deleted all files in the history file but am still getting that same error. 
Can anybody help?
Thanks

**Comment by askmike** [comment]
Can you:

- delete all files in your history folder
- run a live gekko (market watcher)
- as soon as it runs restart gekko
- try to import again?

Thanks

**Comment by ergunpp** [comment]
Thank you. Everything fine now

**Comment by askmike** [comment]
great :)

**Comment by tionebDotsamapha** [comment]
thks
