### ISSUE TITLE
Poloneix get incomplete data when importing

### ISSUE THREAD

**Issue by gweedobtc** [askmike/gekko#994]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Run an import from the command line over 7 days

* **Expected result** (what you hoped would happen)
A successful import

* **Actual result** (unexpected outcome)
Incomplete trade data, causing a JSON syntax issue making it seem as there are no more trades to import.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
Attached
[output.txt](https://github.com/askmike/gekko/files/1232091/output.txt)
 This output is from adding a console.log on line 28 of https://github.com/askmike/gekko/blob/1c0700d312e3f6bc6e4fb9f4d1fdcda5d3392736/importers/exchanges/poloniex.js#L27

**Comment by askmike** [comment]
- What branch of gekko where you running?
- Could you post the exact code you used to log?

**Comment by gweedobtc** [comment]
* stable, latest. It started right after I did a git pull to get the latest changes.
* console.log(result); // which should give me the raw data from the exchange.

**Comment by askmike** [comment]
The thing is that `fetcher.getTrades` does not return any JSON (but javascript objects). So malformed JSON cannot be your problem..

**Comment by askmike** [comment]
Could you let me know what import you were running (market + dates)? I'll try to reproduce..

**Comment by gweedobtc** [comment]
It seems to be working today, I don't know why, but closing for now.

**Comment by askmike** [comment]
Ah great. Well if you run to it again let me know the market and timeframe
:)
