### ISSUE TITLE
BCH support on poloniex

### ISSUE THREAD

**Issue by ergunpp** [askmike/gekko#996]
Hi,
I have read some threads about trading BCH on poloniex but I am a new semi technical user. I have already a gekko running. What is the best adn easiest way to add bch?
I have already one strategy running.
Thanks,

**Comment by askmike** [comment]
BCH landed in the develop branch (see #971). If you already want it download this version of Gekko:

https://github.com/askmike/gekko/tree/develop

**Comment by ergunpp** [comment]
Do I need to download it or can I update with git?

**Comment by ergunpp** [comment]
Will it be enough if I just copy poloniex.js to exchanges folder?

**Comment by askmike** [comment]
yes you can update via git, but you need to switch to the develop branch:

    git fetch
    git checkout develop
    git pull

> Will it be enough if I just copy poloniex.js to exchanges folder?

You can do that as well, but upgrading in the future becomes harder (merge conflicts, etc.)
