### ISSUE TITLE
Incorrect error: "amount is too small" when retrying an unfilled trade

### ISSUE THREAD

**Issue by pelletencate** [askmike/gekko#999]
* **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] question about the decisions made in the repository

* **Action taken** (what you did)
Run Gekko live on GDAX and wait for an order

* **Expected result** (what you hoped would happen)
Keep trying until the order is fulfilled

* **Actual result** (unexpected outcome)
```
2017-08-17 20:33:32 (INFO):     Attempting to SELL 0.2748845 ETH at GDAX price: 257.97
2017-08-17 20:34:33 (INFO):     SELL order was not (fully) filled, cancelling and creating new order
2017-08-17 20:34:34 (INFO):     Attempting to SELL 0.2748845 ETH at GDAX price: 257.97
2017-08-17 20:35:35 (INFO):     SELL order was not (fully) filled, cancelling and creating new order
2017-08-17 20:35:36 (INFO):     Attempting to SELL 0.2748845 ETH at GDAX price: 257.98
2017-08-17 20:36:37 (INFO):     SELL order was not (fully) filled, cancelling and creating new order
2017-08-17 20:36:58 (ERROR):    Wanted to buy EUR but the amount is too small (0.000000000000) at GDAX
```

This last message is incorrect. Yet, no sell order was placed after this message. Could it be the case that the new order is placed before the old order is properly canceled?

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
> Could it be the case that the new order is placed before the old order is properly canceled?

It looks like it yes, I am unable to actually trade on non sandbox GDAX for now. @GuyPaddock have you seen this before?

**Comment by imperator6** [comment]
Thats sounds like a similar issue i had with bittrex. https://github.com/askmike/gekko/pull/968

Remember,  I've added a 10 seconds sleep before placing the new order (after the cancel process).  May be 10 sec is a bit to long, but you could consider to wait a least a second before replacing acanceld oder in general.

**Comment by askmike** [comment]
@imperator6 I think you are right. There are a few bugs regarding GDAX at the moment, hope to test/fix them soon.

**Comment by askmike** [comment]
This one is fixed in develop now.

**Comment by GuyPaddock** [comment]
I had not seen this behavior on GDAX, no.

**Comment by pelletencate** [comment]
@askmike I would like this one reopened, it happened to me again, even after the 10 second countdown.

![image](https://user-images.githubusercontent.com/2717093/29773091-208b4ad4-8bfc-11e7-8e5c-0a5daed6ca79.png)

**Comment by askmike** [comment]
After this happened, did you have EUR or BTC?
